### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by AmsterDaan** [SmashMC-Development/Bugs-and-Issues#1]
**Describe the Bug**
Test

**To Reproduce**
1. Go to 'area'
2. Click on 'NPC'
3. Scroll down to 'Menu'
4. See error : null

**Servers with the Bug**
All

**Expected behavior**
Test

**Screenshots**
(link)

**Additional context**
Test

**Comment by HackuJacku** [comment]
Test

**Comment by HackuJacku** [comment]
test

**Comment by HackuJacku** [comment]
test

**Comment by HackuJacku** [comment]
test

**Comment by HackuJacku** [comment]
test

**Comment by HackuJacku** [comment]
Test
