### ISSUE TITLE
Gym fight froze

### ISSUE THREAD

**Issue by SiennaAffliction** [SmashMC-Development/Bugs-and-Issues#1000]
**Describe the Bug**
I was fighting the water gym on the Groudon server, one of my Pokemon died, I waited, then waited some more and nothing happened except a load screen, I was forced to /endbattle and now have to wait 12 hours to try again.

**To Reproduce**

**Servers with the Bug**
This happened twice to me on the Groudon server, it probably happens on all of them though

**Expected behavior**
I'm not sure if you can unfreeze a battle or prevent it from happening, but reducing the timer on the gym battles down to even 6 hours (which is still a long time) would soften the blow of the match freezing.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Bug related to PixelmonMod. Forwarded it.
