### ISSUE TITLE
Winning tournament offline may not give rare crate key 

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#1001]
**Describe the Bug**
This is in reference to ticket 40772. A player logged off shortly before winning the tournament and did not receive the rare crate key. Maybe can test it by starting a tournament and having someone win while being offline and see if they receive the key.
**To Reproduce**
1. Join a tournament on Groudon
2. Log off
3. Have other people in the tournament forfeit
4. See you win and not get the key while offline

**Servers with the Bug**
Please provide a list of which servers have this bug.
This happened on Groudon
**Expected behavior**
I'm not really sure it might be better to have people forfeit when they log off. But it's expected whenever anyone wins a tournament to get a key whether they are offline or not I guess. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
Refer to ticket 40772
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
I'm confused. How does someone win a tournament while being offline?

**Comment by piplupqueenn** [comment]
I am not sure to be honest. The logs show hypher logging off and then winning while offline.

**Comment by piplupqueenn** [comment]
I think when he logged off he didn't leave the tournament. The other player forfeited. I guess sometimes when people log off during tourney they don't leave idk

**Comment by piplupqueenn** [comment]
> I'm confused. How does someone win a tournament while being offline?

Just tested it can confirm if you quit your mc launcher while in tourney you stay in the tournament. This is what happened with hypher and since the only other person in the tournament forfeited, hypher won while being offline.

**Comment by HackuJacku** [comment]
Same issue as #978
