### ISSUE TITLE
Didn't show shiny option in Zekrom server for gen starters

### ISSUE THREAD

**Issue by AssassinPlay** [SmashMC-Development/Bugs-and-Issues#1002]
**Describe the Bug**
I didnt get any option for making my starter pokemon a scorbunny a shiny.

**To Reproduce**

**Servers with the Bug**
Zekrom server

**Expected behavior**
I wanted a shiny scorbunny but didn't get one.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Hello! The button is right here:
![image](https://user-images.githubusercontent.com/24925669/147904117-87203389-e3c2-45c4-aefc-db280a82562c.png)
