### ISSUE TITLE
someone stole my stuff even tho i claimed my land

### ISSUE THREAD

**Issue by Superpuglead** [SmashMC-Development/Bugs-and-Issues#1003]
**Describe the Bug**
when i claimed my land to build on so it is safe from anyone going into my chests. then just today i go back online and check my chests and most of my valuable stuff is missing like my 6 poke healers 2 stacks of ultra balls that i farmed myself and my 7 pcs also some other stuff for my building.

**Servers with the Bug**
The pixelmon mcsmash {rayquazar}

**Expected behavior**
that i should still have all my items in my chest if it says my user name claims this

**Screenshots**
If appli
![Screenshot (4)](https://user-images.githubusercontent.com/96502557/147762757-5c2a5efb-5797-401f-88e6-3f245ea438a4.png)
![Screenshot (3)](https://user-images.githubusercontent.com/96502557/147762760-514023fe-88b3-43bb-95f3-6f7a5989c4bb.png)
![Screenshot (2)](https://user-images.githubusercontent.com/96502557/147762765-c953940a-8686-42c6-917a-fac67affca31.png)
![Screenshot (1)](https://user-images.githubusercontent.com/96502557/147762766-425d41a1-4997-4ded-9915-57e2c4b87011.png)
![Screenshot (6)](https://user-images.githubusercontent.com/96502557/147762770-628cd131-016a-4003-8bd7-dd8d17879b61.png)
![Screenshot (5)](https://user-images.githubusercontent.com/96502557/147762773-622e57bf-c954-4902-8703-525bea2521ab.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
please is there a way i can get all my stuff back because i worked so hard to get it

**Comment by M1n0j** [comment]
Hey, for this issue you will need to open a ticket on the discord which can be done by going to #botspam and typing "-ticket open (reason)". From there a Staff member will be able help you find what happened to your items.

**Comment by Mikirae** [comment]
Hello, please make sure your things are properly claimed. Many people leave out a portion of their chests and it results in them being able to be griefed. Please open a ticket as directed above and we will be able to get everything sorted :)
