### ISSUE TITLE
2nd Elite 4 on Kyurem doesnt start battle

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1004]
**Describe the Bug**
The 2nd Elite 4 on Kyurem doesn't start

**To Reproduce**
1. Challenge the 2nd E4
2. Have the Battle accepted
3. The battle will not start and all the players Pokémon will be put into their PC

**Servers with the Bug**
Seen on Kyurem but may affect others

**Expected behavior**
Battle should start

**Screenshots**
Players POV:
![image](https://user-images.githubusercontent.com/84816052/147784534-182a1452-cb02-4282-ba78-881e1f0f606e.png)

Elite 4s POV:
https://youtu.be/exbVgkDpWtY

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
