### ISSUE TITLE
Whimsicott cannot learn Encore via Buymoves

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1005]
**Describe the Bug**
Whimsicott cannot learn Encore via Buymoves

**To Reproduce**
1. Do /buymove encore with a Whimsicott in your party
2. Says its not learnable

**Servers with the Bug**
All

**Expected behavior**
Should be able learn Encore from /buymove

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/147838781-76189b57-b84d-4e1c-a710-c4fef7199576.png)
![image](https://user-images.githubusercontent.com/84816052/147838786-2d51b3a0-e219-488b-9594-197796eb4520.png)
^ U can see Whimsicott in my party

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This may be an issue with Buymoves, as I can teach it via TR.

**Comment by HackuJacku** [comment]
This is not an issue with buymoves. It's an issue with the stat file, on Pixelmon's end. I have however fixed it from the next reboot.
