### ISSUE TITLE
Elite 4 bug

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1006]
**Describe the Bug**
Not sure how to describe it so I will explain what happened.
I was challenged by someone for a elite four battle, the person didn’t have the same team as it was a while since he beat the first one. In the fight he only had 2 Pokémon, which were both in my pc. These were Pokémon that he used in his first e4 battle but he no longer had as I had stolen it from him. So basically the game took the two Pokémon from my pc and gave them to him, he still had them when we finished the battle

**To Reproduce**
Not sure how to reproduce this, I guess you do this:
1. Beat the first e4 battle
2. Give or get a Pokémon stolen from you that you sued in that first e4 battle
3. Challenge the second e4 battle and it should take the Pokémon out of the person who stole it from you pc and basically give it to you

**Servers with the Bug**
Groudon

**Expected behavior**
The game shouldn’t take the Pokémon out of that persons pc and give it to someone else

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
