### ISSUE TITLE
Elite 4 bug

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1007]
**Describe the Bug**
You don't need all 8 badges to challenge the Elite 4

**To Reproduce**
1. Don't have all the badges
2. Challenge the Elite 4

**Servers with the Bug**
Groudon

**Expected behavior**
You shouldn't be allowed to challenge the elite 4 if you don't have all 8 badges

**Screenshots**
![image](https://user-images.githubusercontent.com/90443761/147844235-1f15d35e-cd21-48e8-8bdf-b48b7be4e2ce.png)
![image](https://user-images.githubusercontent.com/90443761/147844239-2e340bcc-ac42-4282-9172-7e4001e9d665.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
