### ISSUE TITLE
/breeding still not working

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#1008]
**Describe the Bug**
/breeding for legend rank+ still does not work. The breeding info GUI still shows up instead of the command notifying you when your eggs are ready. I made a github about it like a month ago it said it was fixed but still an issue. It is also a 2 in 1 issue as the breeding GUI doesn't bring up the breeding info it just doesn't work

**To Reproduce**
1. Do /breeding see it still brings up the breeding wiki gui. 
2. While in /breeding try and use the wiki also doesn't work

**Servers with the Bug**
Kyo

**Expected behavior**
When doing the command it should notify when eggs are done. 
The breeding wiki should also display the info

**Comment by Mikirae** [comment]
Just get better lol
But I thiiiiiink I fixed it for next restart? If not just let me know and I'll go cry and try something else

**Comment by ajdawg48** [comment]
I took your advice and got better now it works ty

**Comment by Mikirae** [comment]
I'm glad you listened and were able to improve yourself good sir
