### ISSUE TITLE
/tpa while healing breaks the game

### ISSUE THREAD

**Issue by luckymerlo2007** [SmashMC-Development/Bugs-and-Issues#1009]
**Describe the Bug**
whenever someone accepts a /tpa request the game breaks causing it to permanently think your healing your pokemon not allowing any imputs.

**To Reproduce**
1. /tpa to someone
2. use a healer
3. while the person is still healing have the /tpa be accepted
4. the person will be stuck in place and will have to relog

**Servers with the Bug**
rayquaza

**Expected behavior**
I expected to be teleported to my friend and either have my pokemon stop being healed or have it not teleport me in general.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
So, this might be a Pixelmon bug, but I'll see if there's anything we can do to fix it on our end :) Thank you for reporting!

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
