### ISSUE TITLE
Gts broken on ray

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1010]
**Describe the Bug**
Once you open the gts, it keeps flickering and resetting and you are unable to click on any of the flickering mons to buy them

**To Reproduce**
1. Go to rayquaza gts
2. Click on a flickering pokemon
3. You cannot purchase the pokemon

**Servers with the Bug**
Rayquaza

**Expected behavior**
no flickering 

**Screenshots**

https://user-images.githubusercontent.com/86555718/147880384-09d30b62-02d6-40ba-b216-6ead3b266e9c.mp4

**Comment by Dxhcky** [comment]
Issue seems to have fixed itself after a server restart however it happened on groudon too and a restart was needed to fix it there, so it's a reoccurring error

**Comment by HackuJacku** [comment]
Fixed from next reboot.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
