### ISSUE TITLE
Jails dont unjail players automatically if they were jailed while offline

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1011]
**Describe the Bug**
When someone is jailed while offine and they rejoin and wait the time they are not automatically unjailed

**To Reproduce**
1. Go to any server
2. Jail a player while they are offline
3. They do not get unjailed automatically once they join back and are online for the correct amount of time

**Servers with the Bug**
All

**Expected behavior**
Should unjail the player when they were online for amount of jail time no matter if they were jailed while offline

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/147967430-8be85e07-93aa-401b-84a1-c2f2ae44821c.png)
![image](https://user-images.githubusercontent.com/84816052/147968941-7daa25dd-d433-4472-a2ad-653c44603abf.png)

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Forwarded to relevant tracker: https://github.com/NucleusPowered/Nucleus/issues/1626
