### ISSUE TITLE
Clears delete some special pokemon such as bosses / mega bosses

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1012]
**Describe the Bug**
Clears dont just delete normal pokemon, but also pokemon they shouldnt such as bosses

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to server
2. Spawn in mega boss
3. Have a clear happen
4. Boss gone 

**Servers with the Bug**
Rayquaza, haven't tested on others 

**Expected behavior**
Boss shouldnt leave

**Screenshots**

https://user-images.githubusercontent.com/86555718/147976595-c52d21b1-58be-414d-b511-7c41d20e6091.mp4

**Comment by mDerinho** [comment]
I can confirm this has happend to me today, on the Kyogre server so is most likely a server wide issue

**Comment by Dxhcky** [comment]
Also happened on Groudon earlier today

**Comment by HackuJacku** [comment]
Should be fixed from next reboot.
