### ISSUE TITLE
Pressure Plates in the fossil rooms in spawn dont work

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1014]
**Describe the Bug**
Pressure Plates in the fossil rooms in spawn dont work if a player stands on them

**To Reproduce**
1. Go to fossil rooms in spawn
2. Stand on Pressure Plates
3. does not close the door

**Servers with the Bug**
All

**Expected behavior**
Doors should close

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/148124523-c2b9fd6a-eb92-48b3-a668-60e396b9130c.png)

**Additional context**
Doors do close if a pokemon is on them, but a player cannot

**Comment by Superfire96** [comment]
Fixed
