### ISSUE TITLE
deleting scrolls

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1016]
**Describe the Bug**
Whenever you right click a kubfu with a scroll of darkness, when its standing next to a scroll of water, the scroll of darkness dissapears from your inventory. Also works the other way around (when the waterscroll is in ur inv and the scroll of darkness is around). 

**To Reproduce**
1. Get a kubfu
2. Get both scrolls (scroll of waters and scroll of darkness)
3. Place one scroll down and keep one scroll in ur end
4. Right click the kubfu with either scroll in ur hand while the other scroll is on the ground
5. The scroll in ur hand will disappear

**Servers with the Bug**
All

**Expected behavior**
I'd expect the scroll not to dissapear

**Screenshots**
N/A

**Additional context**
https://www.youtube.com/watch?v=6HeUs9QjxRA

**Comment by Mikirae** [comment]
So this unfortunately is a Pixelmon bug and we're unable to do anything about it. Thank you for reporting it, though! :)
