### ISSUE TITLE
Voting link dont work 

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1017]
**Describe the Bug**
The voting link that I will put below does not give the key when voting.
https://minecraftservers.org/server/548790

**To Reproduce**
Steps to reproduce the behavior.
1. Go to website 
2. vote
3. don't get key

**Servers with the Bug**
All pixelmon servers

**Expected behavior**
Should give key

**Screenshots**
N/A

**Additional context**
Pip told me to make this so any details that don't make sense go to her lol

**Comment by HackuJacku** [comment]
This works fine. It doesn't work when the player is offline but forwarded to the dev.
