### ISSUE TITLE
Chat telling wrong spawn location

### ISSUE THREAD

**Issue by Pajamapants1200** [SmashMC-Development/Bugs-and-Issues#1019]
I was playing and a bunch of things spawned on me that weren’t there. I was in a swamp and a bunch of Pokémon from bones not even near me spawned on me. Then a legendary spawned and it said on me and in the same biome then someone not near me got it. I checked my map and everything.
![Uploading 0F5CD875-ABA6-49C4-B880-9D548E6B9682.jpeg…]()

**Comment by HackuJacku** [comment]
Forwarded to Pixelmon already.
