### ISSUE TITLE
BuyMove command

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Bugs-and-Issues#102]
**Describe the Bug**
Charizard is unable to learn dragon dance when supposed to

**To Reproduce**
1. Go to Any server
2. Click on Run the command /buymove and it won't be able to learn it 

**Servers with the Bug**
All

**Expected behavior**
charizard is supposed to learn dragon dance via tr (or /buymove)

**Screenshots**
N/a

**Additional context**
N/a

**Comment by HackuJacku** [comment]
Fixed in 8.2, should be updating in a couple of days.
