### ISSUE TITLE
Tournament Flag Command

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#1020]
**Describe the Bug**
Change it to something like /tournament bug because every time you are someone to do it....they think you are asking them to forfeit. It gets annoying pretty quickly. It is not a bug but sure is an issue.

**Servers with the Bug**
All.

**Comment by HobnobberJunior** [comment]
Good idea

**Comment by Mikirae** [comment]
Well unfortunately I can't make it be "tournament bug" because that'd require tapping into Tournaments and learning code and I'm stupid, so I made it "/tournamentbug" effective on all servers when they're next rebooted :)
And next time use the Suggestions forum please <3

**Comment by ghost** [comment]
Thanks, it was a huge issue because newer players think you are asking them to forfeit.
