### ISSUE TITLE
Gts bug

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Bugs-and-Issues#1021]
**Describe the Bug**
The gts is flickering making it hard to press the icons.

**To Reproduce**
Go to kyogre
Type /gts
See it flicker

**Servers with the Bug**
Kyogre as far as im aware

**Expected behavior**
Should not be flickering

**Comment by Mikirae** [comment]
This is something that's hopefully fixed in a recent update and is being tested by Hacko tomorrow. Please be patient while we try to get this fixed :)

**Comment by HobnobberJunior** [comment]
The gts is not flickering for me anymore.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
