### ISSUE TITLE
Boss/shiny/legendary spawn chat command wrong

### ISSUE THREAD

**Issue by Pajamapants1200** [SmashMC-Development/Bugs-and-Issues#1022]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Pajamapants1200** [comment]
I play on rayquaza. A shiny spawned and I expected that it would be in a biome near me but it wasn’t so I ignored it and stayed in the biome. Then a second shiny i expected to be in my biome wasn’t in a biome near me. Finally a legendary spawned on me and o thought it was actually on me so I looked but then someone no where near me caught it. I checked the map with the j button but he was no where near me.
![Uploading 3482F18C-32E2-405A-80B5-DFDA42FB34EF.jpeg…]()

**Comment by Pajamapants1200** [comment]
![E9ED0713-EE97-4781-9199-B809A425203F](https://user-images.githubusercontent.com/94767543/148468132-29499b2f-7948-4142-9f05-4e10183478b6.jpeg)
![50757304-0F96-4A95-9DE2-66DF11336230](https://user-images.githubusercontent.com/94767543/148468138-ce156d74-0918-4a18-9d8d-fc5aebd92dc1.jpeg)
![024D1813-65E1-4F0F-86B5-0ECB77F53545](https://user-images.githubusercontent.com/94767543/148468144-685b83cc-a11c-4042-bf90-972500a2da34.jpeg)

**Comment by Mikirae** [comment]
I've made a ticket for the developer on the Pixelmon website. Thank you for reporting this! :)

**Comment by HackuJacku** [comment]
Fixed
