### ISSUE TITLE
The warzone (Time Frozen) bug

### ISSUE THREAD

**Issue by Chockeyz** [SmashMC-Development/Bugs-and-Issues#1023]
**the bug which makes you stay in warzone for infinite hours**
So basically for example 
If a player called A and a player called B battled in the warzone and if the player A crashes then the battle will end but the frozen time will be stuck with the player B so it makes that he could leave whenever he wants to

**To Reproduce**
1. Go to 'warzone'
2. Go on 'battle someone'
3. If the 'other player crashes.'
4. See the frozen time 

**idk**
Just seen zekrom

**thought that it's just a display issue**

**'N/A'**

**'N/A'**

**Comment by Mikirae** [comment]
This is known and needs to be fixed by the developer. I'm closing this ticket as we already have one on our end, but thank you for reporting! :)
