### ISSUE TITLE
gmsp and afk error message

### ISSUE THREAD

**Issue by br183adl** [SmashMC-Development/Bugs-and-Issues#1024]
**Describe the Bug**
error message  displays in chat when being in spectator and becoming afk

**To Reproduce**
1. enter game mode spectator
2. wither wait for the automatic afk message or run the command /afk
3. displays error message in chat to everyone
4. 

**Servers with the Bug**
all servers
**Expected behavior**
for the error message to be removed from everyone's view in chat or not displayed or fix said error

**Screenshots**

![2022-01-07_18 15 32](https://user-images.githubusercontent.com/84156993/148589381-37876c3a-a48b-4bed-838f
![2022-01-07_18 15 34](https://user-images.githubusercontent.com/84156993/148589393-7e220171-d0a0-4a89-bc23-75b839ba0294.png)
![2022-01-07_18 15 37](https://user-images.githubusercontent.com/84156993/148589403-179fa5df-2187-4ad6-87a0-1cd18b267bf6.png)

-4ebe69aa98c0.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Not a bug, feature of the spectator gamemode.
