### ISSUE TITLE
/textures doesnt work

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1025]
**Describe the Bug**
When you do /textures it sends you to an invalid site 

**To Reproduce**
1. Go to a server
2. Do /textures
3. Click on link

**Servers with the Bug**
Potentially all

**Expected behavior**
Textures download

**Screenshots**
![image](https://user-images.githubusercontent.com/86555718/148596413-ed446130-a674-4e59-a18d-bf7bbac707fa.png)

**Comment by jahangir6969** [comment]
Thank you for the report. The link has been updated.
