### ISSUE TITLE
/breed

### ISSUE THREAD

**Issue by jlee1604** [SmashMC-Development/Bugs-and-Issues#1026]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jlee1604** [comment]
/breed does not work on zekrom
it keeps saying some null thing
can you please fix the bug
I am a smash rank but /breed is not working

**Comment by HackuJacku** [comment]
![image](https://user-images.githubusercontent.com/18508413/148648775-858400cc-deb7-4651-98fd-5e4f9e8465d9.png)
Works fine as shown here, @jlee1604. You need to provide us with more information than you currently have.

**Comment by Mikirae** [comment]
Can you let us know if you have any issues with this still, please?
