### ISSUE TITLE
Warzone Popplio + Evolutions do not spawn

### ISSUE THREAD

**Issue by linefax** [SmashMC-Development/Bugs-and-Issues#1027]
**Describe the Bug**

Hello, Popplio, Brionne, Primarina do not spawn in Warzone atm.
I tried catching all the starter Pokemon and got all 1-3 Evolution of all starter stages except for Popplio + Evolutions.

I havent got a single Popplio, Brionne or Pormarina.
I asked other people on the Server too and they said the same, that they never found one.

Im playing on Rayquaza.

**Comment by HobnobberJunior** [comment]
We do not have scorbunny, reboot and cinderace in wz on kyogre either.

**Comment by Superfire96** [comment]
Was fixed
