### ISSUE TITLE
Nihilego hidden evolution?! just kidding, it's missingno

### ISSUE THREAD

**Issue by ShuuraOni** [SmashMC-Development/Bugs-and-Issues#1028]
**Describe the Bug**
My nihilego turned into missingno at first, so I disconnected and reconnected. but later on, it turned into an egg and then Guzzlord  and I disco/reco again... It's not the first time I see MissingNo out of nowhere but it's the first time it turned one of my pkm into something else

**To Reproduce**
I don't know why it happens...

**Servers with the Bug**
I was playing on the Kyogre server

**Expected behavior**
I wasn't sure disconnecting and reconnecting would do the trick but it seems so...

**Screenshots**
N/A

**Additional context**
I was doing some landscaping during the bug...? maybe the rythme I was breaking blocks or something, I'm using an efficiency diamond axe.

**Comment by jantjewieger** [comment]
This is a visual bug

**Comment by Superfire96** [comment]
It's a visual bug, closing this up
