### ISSUE TITLE
Icons/Info on GTS are incorrect on Rayquaza for Items and Pokemon

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1029]
**Describe the Bug**
The icons/info on the GTS are not the same as the items/pokemon listed

**To Reproduce**
1. Go to Rayquaza
2. Do /gts
3. Hover over a random icon and the icons/info do not line up with the pokemon or items listed

**Servers with the Bug**
Rayquaza

**Expected behavior**
Should show correct icons/info for each pokemon and item

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/148662000-54d7b542-8e5a-4e1a-9f52-291f7a3a7dfb.png)
![image](https://user-images.githubusercontent.com/84816052/148662003-4e89c9a3-c338-4a00-a037-58d524c10d97.png)

Honedge us Steel/Ghost and is shown here as Dark/Dragon
![image](https://user-images.githubusercontent.com/84816052/148662034-c06f0a20-9943-4620-b541-d9b6c5e6f2d9.png)

Cleffa when 1st log on 
![image](https://user-images.githubusercontent.com/84816052/148662045-c3cd3128-fc76-4149-886f-ef511368e355.png)
Cleffa when relogged (which still shows incorrect icon/info)
![image](https://user-images.githubusercontent.com/84816052/148662049-7bfe4672-81e4-4fe4-ab11-494168a4fa7c.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
So I haven't heard of anyone else having this issue so I figured I'd ask.
Do you have any mod that edits your inventory? Like InventoryTweaks?

**Comment by ghost** [comment]
I was having this issue as well. I think it happens when you search something on GTS. Not sure though. I have the server modpack, no additional mods.

**Comment by M1n0j** [comment]
No extra mods, there was a couple of tickets about it at the time of making this and a few people confused in game. Only seems to be on Ray however

**Comment by Dxhcky** [comment]
lots of people have complained about it on ray so it is a bug for everyone I believe

**Comment by HackuJacku** [comment]
@M1n0j and @Dxhcky: is still this an issue? I've been unable to reproduce it.

**Comment by Dxhcky** [comment]
I'll have a look tomorrow but multiple people have mentioned it so I think it might be

**Comment by M1n0j** [comment]
Doesn't seem to be an issue anymore. Asked 2 other people and looks fine for them also.

**Comment by HackuJacku** [comment]
Please open a new issue if it occurs again.

**Comment by ghost** [comment]
It was still a issue for me yesterday. I also noticed the same issue on other servers(Reshiram and Groudon) as well.
