### ISSUE TITLE
Glow in warzone can be disabled

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#103]
**Describe the Bug**
When warping to warzone and standing on the boat you are able to type the command /glow toggle , and sometimes it will stay disabled for a while or some minutes

**To Reproduce**
1. Go to /Warp warzone
2. Type /glow toggle
3. Step on the pressure plate to join the warzone

**Servers with the Bug**
The only server i was able to test it it's Mew, as i couldn't join other warzones

**Expected behavior**
Players should not be able to disable the glow, even for few minutes

**Comment by Rasgnarok** [comment]
Fixed on all Warzones.
