### ISSUE TITLE
Rayquaza server crashed and some people lost money

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#1030]
**Describe the Bug**
On the rayquaza server, there was a crash and some people lost money. 
**To Reproduce**
1. Go to Rayquaza
2. It crashed
3. People logged back on and lost money

**Servers with the Bug**
Please provide a list of which servers have this bug.
Rayquaza

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
In reference to tickets 41173-i lost 30k when the server rebooted, #41170 lost 60k after server resetcrash, #41168 server crashed mid raid lost park ball 1000 pokedollars

**Comment by HackuJacku** [comment]
Tickets please
