### ISSUE TITLE
Players lost stuff due to dungeons disabled

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#1031]
**Describe the Bug**
A bunch of people who were in the dungeon when they got disabled and turned off and shut down the server lost all their gear and items.

**Servers with the Bug**
Kyogre, maybe other servers but I cant say so.

**Expected behavior**
Get their stuff back

**Screenshots**
(ticket 41209)

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
Ticket.
