### ISSUE TITLE
Warzone Legendary spawning outside of the Warzone field

### ISSUE THREAD

**Issue by linefax** [SmashMC-Development/Bugs-and-Issues#1032]
**Describe the Bug**
The Spawnmessage of the Legendary is popping up in chat, but 4 people that are in wz in the time cant find them. This happened 3 times in the last 20min Xerneas, Kyogre, mew2.
There is no message that someone cought the Legendary or that it despawned which should happen after some mins.

**Servers with the Bug**
Rayquaza Server

**Expected behavior**
Please try to fix the bug, that Pokemon spawn outside of Warzone.

**Comment by HackuJacku** [comment]
As established before, this isn't possible as outside isn't valid spawning grounds.. I've checked the logs, they all spawned inside the Warzone.
