### ISSUE TITLE
Sell wands on survival go into claim inspection mode

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#1033]
**Describe the Bug**
When right-clicking a chest on survival with a sell wand it goes into claim inspectation mode. 
**To Reproduce**
1. Go to Survival
2. Right click chest

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival
**Expected behavior**
It's expected for a sell wand to sell the sellable items in the chest that it rightclicks. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![sellwandclaim](https://user-images.githubusercontent.com/85481519/148854189-fdd56da2-70c9-4561-888a-c6e674b05823.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
