### ISSUE TITLE
npc teleporter in survival spawn is saying "unlock more commands at smashmc.co"

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#1034]
**Describe the Bug**
In spawn in survival, there is an iron golem that says "click me to start your adventure". When you right-click it, it says "ERROR: unlock more commands at smashmc.co"
**To Reproduce**
1. Go to Survival
2. /spawn
3. find iron golem at spawn and right click it
4. See error message

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival
**Expected behavior**
It is expected for the iron golem to rtp players when right clicked.
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by piplupqueenn** [comment]
Same thing happens when you go to the arena master in spawn which is the blaze it does not bring you to the arena it instead gives the same error message

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
