### ISSUE TITLE
no way to get out of warp pvp on survival if you rtp

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#1035]
**Describe the Bug**
Since the rtp cooldown is 4 hours, and it is the only way to leave warp pvp, there is no way to get out of warp pvp until the cooldown runs out. 
**To Reproduce**
1. /rtp
2. go to /warp pvp
3. do /rtp 

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival
**Expected behavior**
It is expected for there to be another way to leave warp pvp without waiting for a cooldown that long. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
Same issue as #834
