### ISSUE TITLE
Wz Battle "Crashes" 

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#1036]
**Describe the Bug**
The bug is the fact if you dc you cant get stolen from, if I fight a player, and am about to beat them they just disconnect, and I cant steal from them, seems a lot of players use this

**To Reproduce**
1. you and someone else go to warzone
2. fight each other
3. one person disconnect
4. See that you cant steal

**Servers with the Bug**
all

**Expected behavior**
your able to steal, if they did crash they can just get there pokemon back via a ticket

**Screenshots**

**Additional context**
a lot of players seem to be "crashing" as this has gotten a lot more known

**Comment by Mikirae** [comment]
This is unfortunately a known issue that needs to be fixed by the developer. I'll be closing this as we have a ticket available in that repo already, but thank you very much for reporting :)
