### ISSUE TITLE
Warzone Lag

### ISSUE THREAD

**Issue by Abouchet123** [SmashMC-Development/Bugs-and-Issues#1038]
**Describe the Bug**
Everytime i go into warzone, my minecraft starts freezing every 3 seconds. So if i am in a battle, i basically lose because i cant even click anything. It happens everytime i go into warzone
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Groudon
**Expected behavior**
I want to be able to go into the warzone and it not be freezing every 3 seconds 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
I've been there many times and this doesn't happen to me. Next time it happens, can you press F3 and check if your memory is maxing out?

**Comment by HackuJacku** [comment]
Please create a support ticket on our Discord, we'll able to help you there! Like Miki said, I think this is to do with a lack of RAM dedicated to Minecraft.
