### ISSUE TITLE
Can go to another server while in Warzone

### ISSUE THREAD

**Issue by CaretsPuppy** [SmashMC-Development/Bugs-and-Issues#104]
**Describe the Bug**
You can go into another server while in warzone. 
For example:
I enter Palkia warzone then do /darkrai

**To Reproduce**
1. Go to Warzone
2. Type /(servername)
3. You will be teleported to the server of choice

**Servers with the Bug**
Palkia (Assuming all)

**Expected behavior**
The only method of getting out of warzone is via /safeplace

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Same as #90.
