### ISSUE TITLE
no permission for /nameban

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1040]
**Describe the Bug**
Smods and mods don't have permission to use /nameban

**To Reproduce**
1. see a bad name
2. try using /nameban
3. get 'You do not have permission to use this command'

**Servers with the Bug**
All

**Expected behavior**
I'd expect to have permission

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Added for senior moderators and above.
