### ISSUE TITLE
Can't throw balls at pokemon when in raid

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1041]
**Describe the Bug**
After completing a raid, you can't throw pokeballs at it. it shows up saying you don't have any pokeballs, when you do in your inventory.

**To Reproduce**
1. Defeat raid
2. try throw pokeball
3. says you dont have any

**Servers with the Bug**
Only happened on rayquaza I think

**Expected behavior**
Should let you use pokeballs

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/149323536-0eb5036f-7dc2-4677-8361-810f1493ba01.png)

![image](https://user-images.githubusercontent.com/89798207/149323550-2c802056-f995-4e77-94dc-1b75f43fd1d4.png)

**Additional context**
I created this github on behalf of the player "Adripin".

**Comment by Superfire96** [comment]
Should be fixed, as i haven't seen it happening anymore

**Comment by WalkAway7** [comment]
Yeah haven't seen this happen since, I think it was fixed in a hotfix

Thanks

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
