### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1042]
**Describe the Bug**
LawlessHarbor66 seems to have a problem that everytime they engage a pokemon in battle, it kicks them from the server

**To Reproduce**
1. Be LawlessHarbor66
2. Engage a pokemon in battle

**Servers with the Bug**
Rayquaza

**Expected behavior**
Should not kick them frmo the server

https://user-images.githubusercontent.com/90443761/149442795-df4e30cf-4ea9-4233-b0a9-da1995a3fd6d.mp4

**Comment by HackuJacku** [comment]
This needs to be a ticket, not a GitHub report. You've provided a lack of information here so we can't do anything sadly.
