### ISSUE TITLE
Gts bug

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1043]
**Describe the Bug**
Kamarll has a problem when they try to sell items on the gts, it doesn’t allow them to switch from Pokémon to items

**To Reproduce**
1.Go to gts
2. Go to sell
3. Try to switch to items

**Servers with the Bug**
Limited to rayquaza

**Expected behavior**
Should let him sell items

https://user-images.githubusercontent.com/90443761/149465438-d1a9690b-57d1-4e0e-9cc0-30f6463dfe92.mp4

**Comment by HackuJacku** [comment]
Fixed
