### ISSUE TITLE
Hole in Kyurem Ice Dungeon First room

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1044]
**Describe the Bug**
There are 4 holes where pokemon spawn that if you fall in you cannot get out in the first room

**To Reproduce**
1. Go to Kyurem
2. Go to Ice Dungeon
3. See the holes with no way out

**Servers with the Bug**
Seen on Kyurem but may also be on others

**Expected behavior**
Should be able get out of the holes

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Was fixeddd
