### ISSUE TITLE
Battle Tower Bugged

### ISSUE THREAD

**Issue by llnama** [SmashMC-Development/Bugs-and-Issues#1048]
**Describe the Bug**
I bought a 50|50 Shiny Crate with 100BP but didn't receive the crate key. Made a ticket and got it all sorted out. However, It could be a potential bug for other people.

**To Reproduce**
1. Go to '/warp battletower'
2. Click on 'The NPC that sells you item'
3. Scroll down to 'Buy 50|50 Shiny Crate and purchase'
4. Don't find a key in /keys and nothing in your inventory

**Servers with the Bug**
Rayquaza, but could be all.

**Expected behavior**
Should be given a 50|50 shiny crate key

**Screenshots**

![javaw_bohfmf41gX](https://user-images.githubusercontent.com/97389160/149685363-9591fbc3-843f-4a13-8997-4e42353df64a.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
Hacko fixed this. Thank you for reporting!
