### ISSUE TITLE
Meteroite glitch

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1049]
**Describe the Bug**
The meteroite doesn't transform deoxys into its speed form, it skips over it.

**To Reproduce**
1. Have a metorite and deoxys
2. Try to change deoxys into its speed form

**Servers with the Bug**
Tested on zekrom and groudon

**Expected behavior**
Deoxys should be able to change into its speed form

**Additional context**

https://user-images.githubusercontent.com/90443761/149689198-758f6933-21ea-4c33-822d-5428e22cc866.mp4

**Comment by Superfire96** [comment]
Seems to be working fine for me, could you test it again and see if it's still an issue?

**Comment by Superfire96** [comment]
Was fixed
