### ISSUE TITLE
Fall damage active

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#105]
**Describe the Bug**
Just noticed that on a server the fall damage and lava damage are actives.

**To Reproduce**
1. Go to the rayquaza server
2. do /rtp
3. Go high enough to get fall damage and jump down / find lava and jump in it

**Servers with the Bug**
The only server i've seen with this bugs it's Rayquaza, this happens in the overworld and ultraspace too.

**Expected behavior**
No fall damage or lava damage should be taken, as all the other servers

**Comment by HackuJacku** [comment]
@Superfire96 - are you stood within a claim or not please?

**Comment by Rasgnarok** [comment]
Closing, it's normal to get fall-damage when out of an admin claim.

**Comment by Superfire96** [comment]
Sorry for the late reply, but in all the other servers, fall damage is not
active, even outside of an admin claim


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 21 mag 2021 alle ore 02:51 Rasgnarok ***@***.***>
ha scritto:
