### ISSUE TITLE
tourney mons lil broken

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1052]
**Describe the Bug**
You can /wt pokemon that you obtained from a tournament. When the player that receives that mon then obtains the mon from tourney he can't use it bc its a rental mon after all.

**To Reproduce**
1. Join a tournament
2. do /wt on one of the mons from tournament
3. Get a free random pokemon and give someone else the rental mon

**Servers with the Bug**
All

**Expected behavior**
I'd expect them not to be able to wt rental mons

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/149782160-030a53c4-53d7-41a5-997c-030f4cf2c539.png)

![image](https://user-images.githubusercontent.com/87021826/149782209-45469ecd-abec-427a-88c8-54addb7b4c71.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Bug within WT, not tournaments. Forwarded to the developer.
