### ISSUE TITLE
GS Balls might not have been added back

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#1053]
**Describe the Bug**
People have been asking about GS balls and I don't know anyone who has one. There's 3 different ways to get a GS ball, many people have not found them in temples, I don't know of anyone who has completed the quest, and if people have killed a celebi there's a 10% chance but I still haven't seen anyone with a GS ball. Also, other legend spawning items like clear bells, tidal bells, etc. also seem to not be present. I could be wrong but could be worth looking into.

**Servers with the Bug**
Please provide a list of which servers have this bug.
all

**Comment by WalkAway7** [comment]
It's because before reset the main way of obtaining them was through vote parties, and either they aren't in the current vote parties, or it's because they don't come around as often anymore

**Comment by Superfire96** [comment]
Added as rare reward from Spooky Bosses
