### ISSUE TITLE
Ray GTS Broken

### ISSUE THREAD

**Issue by DragonBoyz12** [SmashMC-Development/Bugs-and-Issues#1054]
how to reproduce:

1: look at a mon in the gts
2: shows mon as something else

Expected Behavior:
shows proper mons and proper items

On other servers:
N/A

Screen shot:

![Screenshot 2022-01-18 091345](https://user-images.githubusercontent.com/93355923/149986424-0ff021ac-5c61-4da7-95e2-f8eef493b521.png)

**Comment by HackuJacku** [comment]
Forwarded to developer.
