### ISSUE TITLE
Tab shows the wrong rank

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1056]
**Describe the Bug**
When you click tab to see players online, it shows the wrong rank next to players

**To Reproduce**
1. Press Tab
2. See. for example. an elite player being shown as with the ace rank

**Servers with the Bug**
All

**Expected behavior**
Should show the correct rank

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://user-images.githubusercontent.com/90443761/150099737-fc1e966f-7abb-487d-a3aa-0fca34b8a424.png)
![image](https://user-images.githubusercontent.com/90443761/150099773-08115a3f-9cf9-49b9-894b-2d81f101851d.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed from next reboot
