### ISSUE TITLE
Tab is showing wrong server

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1057]
**Describe the Bug**
I'm currently in zekrom, and it is showing that I am in rayquaza when I press tab, which is wrong.

**To Reproduce**
1. Go to zekrom
2. Press tab
3. see at the top it says rayquaza instead of zekrom

**Servers with the Bug**
Zekrom

**Expected behavior**
Should say zekrom

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/150158275-cede5af4-9f60-490e-a9b6-a2ec7633e05b.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed from next reboot
