### ISSUE TITLE
dungeon bug

### ISSUE THREAD

**Issue by rhytor** [SmashMC-Development/Bugs-and-Issues#1058]
So i have a full level 100 team and wanted to do dungeon so i went to enter one, so i was loading and was supposed to be in the dungeon i was in the void and died. After dying i was in spawn with a timer and seeing ''pokemon left : 8" and wasnt allowed to do any command such as /home so i went to lobby and back in to the kyurem server and saw that i couldn't go in the dungeon for today this was the third time to happen. 

the kyurem server has this bug for me

i expected to be on the dungeon floor and not in the void.

![2022-01-19_09 42 57](https://user-images.githubusercontent.com/98040352/150165210-a4a33e6f-a7bc-4d0d-9c84-c5eb7390624b.png)

**Comment by Mikirae** [comment]
Which dungeon spawned you into the void? I can't seem to reproduce it, but I reported it to the developer :)

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
