### ISSUE TITLE
Glitch After using /home or /pw on Survival server

### ISSUE THREAD

**Issue by British-Commie** [SmashMC-Development/Bugs-and-Issues#106]
**Describe the Bug**
Some Players have Glitched after /home or /pw they move back and forth between two spots and gives the you are in combat message

**To Reproduce**
1. Use /home or /pw
2. Glitch May happen but rare

**Servers with the Bug**
Survival

**Expected behavior**
Repeated Glitchy movement between two points close to the /pw or /home 

**Screenshots**
'N/A'.

**Additional context**
 Seems it may be the combat system

**Comment by jahangir6969** [comment]
@British-Commie Can you try again

**Comment by jahangir6969** [comment]
Issue has been fixed.
