### ISSUE TITLE
Incorrect message displayed when /pwiki command is ran

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#1060]
**Describe the Bug**
The message "The name <anything but a pokemon name> does not respond to a pokÃ©mon name" is displayed instead of "The name <anything but a Pokemon name> does not respond to a Pokémon name"

**To Reproduce**
Run the command /pwiki randomname  (name can be anything but a pokemon name. /pwiki Archie /pwiki garados etc)
See the text that comes with it be displayed incorrectly. Shown below

**Servers with the Bug**
All servers

**Expected behavior**
The text: "The name <anything but a Pokemon name> does not respond to a Pokémon name" should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/86004012/150180542-422e80bc-06e8-4548-8b05-092a355e7f8c.png)

**Additional context**
Not urgent.

**Comment by Superfire96** [comment]
Was fixed
![image](https://user-images.githubusercontent.com/83550357/163584266-0c340ad4-612b-4f97-b180-1e4b37ba7447.png)
