### ISSUE TITLE
ultra beast spawn rates a little broken

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#1061]
**Describe the Bug**
Ultra beasts spawn rates are very very good

**To Reproduce**
1. Go to ultra space
2. go to a biome with ultra beats
3. see how much they spawn 

**Servers with the Bug**
all

**Expected behavior**
them to not be this common
**Screenshots**
![2022-01-19_11 01 00](https://user-images.githubusercontent.com/83245837/150187707-cc7241c9-e0f2-4449-a0fc-3716eb678fa7.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
> Describe the Bug
Ultra beasts spawn rates are very very good

_too_ good, you mean

**Comment by Rasgnarok** [comment]
Handled, rebalanced the rates for Blacephalon, Buzzwole, Celesteela, Guzzlord, Kartana, Nihilego, Pheromosa, Poipole, Stakataka and Xurkitree.

**Comment by DaniloJonko** [comment]
man that sucks i was gonna get myself 5 boxes of karts again -_-
