### ISSUE TITLE
[Master] GTS Pricing Issues

### ISSUE THREAD

**Issue by HackuJacku** [SmashMC-Development/Bugs-and-Issues#1062]
Please use this issue ticket to recommend price values for different Pokémon attributes (e.g: Shiny, HA, Legendary, Ultra Beast, specific number of IVs, specific growth, ETC) for the GTS and Auction House.

See below for the different Pokémon Attributes:
![image](https://user-images.githubusercontent.com/18508413/150215567-297ff04e-3a57-46b9-8322-53c70b48b911.png)

* E.G: IF Shiny, add 10,000.
* IF Legendary, add 10,000.
* IF HA, add 100,000

**Comment by ThePapaChunks** [comment]
If HA i'd double it from its original price so if its 80k for them mon id make it 160k

**Comment by WalkAway7** [comment]
In what way do you want all of us to structure this information? This table can seem confusing to all people coming along.

**Comment by jantjewieger** [comment]
Can we please get the if HA add 100.000 implemented so we dont get things like this. This one specifically for HA greninja/froakie/Frogadier on Reshi. 
If BP add another 50.000 please

![image](https://user-images.githubusercontent.com/87021826/151408101-614d64a9-8cd1-4f74-8712-5902e97bbcf7.png)

**Comment by ThePapaChunks** [comment]
KYO:BP 50-100K BPHA 150K MIN
GROUDON: BP 30-70 BPHA 100K MIN
KYU: BP 40K BPHA 80K
ZEK:BP BP 40K UNBREED BPHA 100K MIN
RAY: BP 30-50K BPHA 60-100K
RESHI:50-60K BPHA 75-80K
The prices for each is also in unbreed form.

This also would average a price of 41K for bp if taken the median of every price range and averaging it out 
And for BPHA if you take the prices and average them aswell it would be 115K for unbreed bpha
for breeds 2X the price of the unbreeds
I went onto every server asked prices from top breeders to get there opinion most people agreed with these prices 
I think these prices of the averages should be added as the minimal prices on GTS to stabilize the economy on the servers,and the reason I think this is people have complained about bps being sold at very low prices like on zekrom a player was selling bp breedable eevees for 1k each.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
