### ISSUE TITLE
Staff Chat Error

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#1063]
**Describe the Bug**
My name (only me I believe) appears twice in Staff chat?! lol

**To Reproduce**
I send a message to staff chat "/sc"
My name appears twice. See below

**Servers with the Bug**
All servers

**Expected behavior**
Only Show my name once.

**Screenshots**
![image](https://user-images.githubusercontent.com/86004012/150232427-e562626b-90db-478d-aabb-fead7a1f2a38.png)
![image](https://user-images.githubusercontent.com/86004012/150232488-a48c93a4-e905-4855-ac5e-dbfbebe8e403.png)

**Additional context**
I don't believe I have changed anything since it last worked.

**Comment by Archie4690** [comment]
Also happening to Piplopp too.

**Comment by Mikirae** [comment]
Is it maybe like when you have /sc toggled and then also do /sc Message?

**Comment by Archie4690** [comment]
SOrry for the slow reply, It is only when i toggle it.
