### ISSUE TITLE
Dungeons on kyurem may be broken

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1065]
**Describe the Bug**
When passing through the dungeons, a player had found that they were unable to complete the dungeon due to there being no more boss pokemon to defeat. It may have been because the player had rushed through, but we are unsure for now. It was in the Ice dungeon.

**To Reproduce**
1. Go to the ice dungeon
2. Defeat the first room
3. Go onto the second room and there aren't any bosses

**Servers with the Bug**
Only kyurem from what I know.

**Expected behavior**
There should be bosses to defeat.

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/150347437-57249976-fa96-49fb-b198-800252118429.png)

**Additional context**
I made this github report on behalf of the player "TommyTaco29" As they weren't able to create one. Anything I missed out may be on the original discord support ticket, the number is "41567".

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
