### ISSUE TITLE
pokemon will not be retreived

### ISSUE THREAD

**Issue by vszarkowski** [SmashMC-Development/Bugs-and-Issues#1068]
I put my dustox for sale on GTS and will not be put away no  matter what i do, i took it out of gts, placed it in my pc, used a healer and even disconnected then reconnected. Even if it isn't in my party it is still out and follows me around like a usual Pokémon would. It's starting to creep me out. I just released it and it is still out and following me.

**Servers with the Bug**
Reshiram

**Expected behavior**
I expected it to be put away

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
This has been a Pixelmon bug for ever since I was playing but it's super rare. I think the only fix for it is to wait for the server to restart. Dying might also fix it, but I can't remember.
