### ISSUE TITLE
Battle Tower!

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#1069]
**Describe the Bug**
Your progress gets reset if you get stuck in waiting in battle tower beause only way to get out is /endbattle. It gets annoying if you are not a very high level.

**Servers with the Bug**
Rayquaza.

**Expected behavior**
There should be a way to continue at the same level if you get waiting bug.

**Comment by Mikirae** [comment]
Unfortunately the dev on this isn't active anymore, so there isn't really much we can do :(
I believe I asked about it before and they told me there's no way they can check for a waiting bug, so the only option was to allow anyone to endbattle on any level and basically just opt out of the battle if they're about to lose.
