### ISSUE TITLE
Warzone bug

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1070]
**Describe the Bug**
So I fought a player, they disconnected, and then warzone randomly teleported me to somewhere, and my time was frozen. I couldn't throw out pokemons, or safeplace, as it would say "Already safeplacing" or something like that.

**To Reproduce**
1. Attack player
2. they disconnect
3. get rtped in warzone
4. then you are bugged with frozen time, and can't throw out mons or safeplace

**Servers with the Bug**
reshiram

**Expected behavior**
Should just rtp you away without frozen time, and being able to throw out mons and safeplace

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/150538999-cead0362-b2e3-4a64-ac5a-079e16222644.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
Should be now fixed
