### ISSUE TITLE
Cant list more items on gts

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#1071]
**Describe the Bug**
after listing an item and getting to max listing on gts you cant sell more, after the previous items have been taken off of gts or been sold

**To Reproduce**
1. Go to rayquaza
2. list 5 items on ray gts
3. take them off/ let them get bought
4. See that you cant list more

**Servers with the Bug**
tested on ray and kyurem, and only ray had the issue

**Expected behavior**
after items are taken off of gts, you can put more on gts

**Screenshots**
N/A 
**Additional context**

**Comment by HackuJacku** [comment]
Forwarded to the developer
