### ISSUE TITLE
Shooting star quest not working

### ISSUE THREAD

**Issue by Martiin24** [SmashMC-Development/Bugs-and-Issues#1072]
When you finish all the tasks for the shooting star quest it should tell you to go back to the professor and talk to him. On the Zekrom server however, this won’t show up as a task in the quest. When you try to talk to the professor he doesn’t do anything.

I don’t know if this bug is on more servers besides the Zekrom server.

<img width="1436" alt="3D2CA30B-EE71-449A-8915-713ED9A4BB30" src="https://user-images.githubusercontent.com/98181568/150578597-4151d046-82e0-4ecf-9ca7-977fd3441b74.png">

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
