### ISSUE TITLE
Bosses and legendarys spawn message not on correct player

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#1073]
**Describe the Bug**
when a new boss/legend/ultra beast spawns it says its on the wrong player, and when its a mega pokemon it doesn't say its mega

**To Reproduce**
1. Go to any server
2. wait for a boss / any type of spawn message
3. see that it spawned on someone, then its on another player

**Servers with the Bug**
all I believe

**Expected behavior**
It to say it spawned don't he correct player, and for it to say its a mega when its a mega

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Dwag0n** [comment]
![2022-01-22_09 22 05](https://user-images.githubusercontent.com/83245837/150646932-acc9a59a-9542-421c-bca0-6ceb9711fab8.png)
screenshot of it ^ also that was a mega heracross and not a normal one

**Comment by Mikirae** [comment]
Is this still an issue? I think I remember reporting this a while back but idk if it was ever fixed

**Comment by ajdawg48** [comment]
@Mikirae Yes still broken. Plz fix my son

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
