### ISSUE TITLE
GTS Auction glitch

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#1076]
**Describe the Bug**
On Kyogre, doing /gts and choosing auction causes everything listed to sell for $0. 
**To Reproduce**
1. Go to kyogre
2. do /gts
3. sell something on the auction
4. have someone buy it and see that it sold for $0. 

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre
**Expected behavior**
Expected to sell items for the price you set it for not for it to be sold for $0. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
https://youtu.be/51wgDCLHx_c
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by piplupqueenn** [comment]
This is also an issue on reshiram everything sells for 0 dollars including pokemon

**Comment by piplupqueenn** [comment]
This is also on zekrom

**Comment by Rasgnarok** [comment]
Issue has been reported to the developer. AH has now been disabled until the fix is completed.
