### ISSUE TITLE
Able to evolve pokemon in Tourney

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#1077]
**Describe the Bug**
Players are able to evolve pokemon in tourney by giving them any form of exp candy.

**To Reproduce**
Enter tournament, with the level 100 pokemon it gives you. 
Find a pokemon that is able to be evolved by level in your party and give it a exp candy.
Your pokemon should evolve.

**Servers with the Bug**
All

**Expected behavior**
You should not be able to level up your pokemon inside of a tournament

**Screenshots**
link to video from: mDer 
https://streamable.com/qq0p98

**Comment by Dxhcky** [comment]
This also happens with /evofix

**Comment by HackuJacku** [comment]
Fixed from next reboot
