### ISSUE TITLE
GTS bugged

### ISSUE THREAD

**Issue by linefax** [SmashMC-Development/Bugs-and-Issues#1078]
**Describe the Bug**
You cant place the maximum items/pokemon on GTS, (i think the max is 5 pokemon/items)

**To Reproduce**
1. Go to rayquaza
2. /gts
3. put the maximum items/pokemon in, and cancel the sell
4. you cant put any items/pokemon in after that.

**Servers with the Bug**
Rayquaza

**Comment by HackuJacku** [comment]
Already reported to the developer, waiting on an update.
