### ISSUE TITLE
Overworld NPC gym Leader battle error

### ISSUE THREAD

**Issue by Bkdevileu** [SmashMC-Development/Bugs-and-Issues#108]
**Describe the Bug**
There's an Overworld NPC Fire gym in Jirachi that, when you battle, after 2-3 turns, it promptly ends the battle with an error. (Need to confirm if it's just this gym or all gyms)

**To Reproduce**
Just battle the gym leader and, after 2-3 turns, it gives the error (Tried 5 times, all ended with an error)

**Servers with the Bug**
Jirachi

**Expected behavior**
Able to battle it and get the badge.

**Screenshots**
![Bug1](https://user-images.githubusercontent.com/84034504/117871222-0e9d6780-b295-11eb-8089-ffd2e3d0b821.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
@Bkdevileu - I need to know the exact steps to reproduce it please. For example: which moves are being used.

**Comment by Bkdevileu** [comment]
Any moves used, always with the same result. Used different pokemons/moves.
Gym Coords: 
![image](https://user-images.githubusercontent.com/84034504/118326820-676f3900-b4fd-11eb-8bda-28b892804b6d.png)

Sent you the video as well

**Comment by HackuJacku** [comment]
Was unable to reproduce. Please provide me the exact Pokémon you used and the opponent used - I'll need the movesets of both if possible too please.

**Comment by HackuJacku** [comment]
Outdated and no response.
