### ISSUE TITLE
Zekrom third e4 won’t work

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#1080]
**Describe the Bug**
whe I challenged the e4 Bork said he couldn’t accept the battle 

**To Reproduce**
Challenge the third e4 on zekrom 

**Servers with the Bug**
Zekrom 

**Expected behavior**
He should be able to accept the challenge 

**Screenshots**
n/a

**Additional context**
N/a

**Comment by Rasgnarok** [comment]
Duplicate
