### ISSUE TITLE
Ultimate Boss Drops

### ISSUE THREAD

**Issue by linefax** [SmashMC-Development/Bugs-and-Issues#1081]
The Boss drops on this Server are not the standard drops that you can look up at the pixelmon Wiki on google.

Would it be possible to change the drops to the normal rate or atleast make items like Ultra-Necrozium Z or Solganium Z easier to get?
To be honest, i have no idea if you can even get these Z stones somehow.

**Comment by HackuJacku** [comment]
This is intention, not a bug. You are still able to get Z-Crystals from bosses, but the higher tier ones.
