### ISSUE TITLE
kyurem e4 issue

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1082]
**Describe the Bug**
You can use ubers and more than the 2 legs/ubs cap in e4 battle

**To Reproduce**
use ubers and more than 2 legs/ubs
send chal
battle can be accepted

**Servers with the Bug**
Kyurem

**Expected behavior**
thought there was something that prevents these teams being used for e4 battles

**Comment by M1n0j** [comment]
Issue is also happening on with Gyms as the ban list allows all legends but limits you to 2 of them

![image](https://user-images.githubusercontent.com/84816052/163883295-b759ebc5-0de0-4d71-9fb2-b4481df5f7b3.png)

Should be banned - Rayquaza, Mewtwo, Lugia, Ho-oh, Kyogre, Groudon, Deoxys (Base Form, Attack form, Speed form), Dialga, Palkia, Giratina (Both forms normal and origin), Shaymin-Sky, Arceus, Tornadus-Therian, Reshiram, Zekrom, Landorous (base form), Kyurem-Black, Kyurem-White, Meloetta-Pirouette, Genesect, Xerneas, Yveltal, Zygarde (50% and Complete which is via ability Power Construct), Solgaleo, Lunala, Pheromosa, Magearna, Marshadow, Naganadel, Zacian, Zamazenta, Eternatus, Urshifu-Single-Strike, Spectrier, Calyrex-Ice, Calyrex-Shadow

**Comment by M1n0j** [comment]
Also is on all servers not just Kyurem

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
