### ISSUE TITLE
GTS bug

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#1083]
**Describe the Bug**
GTS doesn't let you post items when there is a custom server paper like legendary shiny convert in your inventory. So, you can put custom papers on GTS. I have only tested with legendary shiny convert but assuming it is the same with other custom papers.

**To Reproduce**
1. Put 1 legendary shiny convert paper in your inventory.
2. Open GTS and select the sell option
3. Press Toggle Pokemon/Item button
4. Doesn't show the items in your inventory

**Servers with the Bug**
Groudon and probably other server.

**Expected behavior**
Should be able to sell custom papers on GTS and Auction House.

**Video**
[https://youtu.be/Cmta0azZvXs](url)

**Comment by Dxhcky** [comment]
also happens with non leg random iv boost

**Comment by Mikirae** [comment]
Will take a look but I'm stupid with GTS so I'm tagging the best GTSer in here @Rasgnarok <3

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
