### ISSUE TITLE
Ferrothorn moveset

### ISSUE THREAD

**Issue by IsThief** [SmashMC-Development/Bugs-and-Issues#1085]
**Describe the Bug**

ferrothorn cant learn Stealth rock and knock off

**To Reproduce**
1. Go to /warp mart
2. Click on buy moves npc
3. ferrothorn cant learn Stealth rock and knock off

**Servers with the Bug**
Please provide a list of which servers have this bug.

Ray but probably all servers

**Expected behavior**

ferrothorn to ba able to  learn Stealth rock and knock off

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Dxhcky** [comment]
I think in this pixelmon version knock off is an egg move, as for stealth rock, you should be able to learn that with a TR

**Comment by Dxhcky** [comment]
In game type /wiki ferrothorn eggmoves and see if knock off is on there, as I'm not 100% sure it's an eggmove

**Comment by Superfire96** [comment]
Indeed knock off is an egg move and ferrothorn can learn stealth rocks with a TR
