### ISSUE TITLE
Dynamax quest bug

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1087]
**Describe the Bug**
Seems a bug as surfaced with the dynamax quest. Players can complete the first part of the quest, but then right after the NPC will not offer the quest again, and they cannot complete the quest. We had 3 tickets open around the same time on the exact same issue, same server.

**To Reproduce**
1. Get dynmax quest
2. complete first part
3. Go to NPC
4. will not offer the quest, will not have the purple question mark above head

**Servers with the Bug**
Seems to be only on zekrom, as that is where all of these 3 tickets opened from.

**Expected behavior**
Should let the player continue on the quest

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/150771849-26f6aad4-4cb7-4b48-887f-fad7a9b65100.png)

**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
