### ISSUE TITLE
Issue with jail time

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1089]
**Describe the Bug**
If you get jailed and log off, the timer will get paused at the time it was when you logged off, and it will not resume even after logging on, making the player get stuck as the timer does not go down

**To Reproduce**
1. Go to a server and get jailed
2. Log off
3. Log back on 

**Servers with the Bug**
Rayquaza, could be all 

**Expected behavior**
Timer to resume

**Comment by Mikirae** [comment]
This is a bug with the plugin and I don't know if there's a fix currently. Will look into it.

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Bugs-and-Issues/issues/1011
