### ISSUE TITLE
0% damage in Pokémon battles 

### ISSUE THREAD

**Issue by Mosawer-hub** [SmashMC-Development/Bugs-and-Issues#109]
I have had this bug happen to me twice. I battle someone in warzone and I use a move that’s super effective it hits but does 0% damage I don’t have a screenshot of it since it’s not something you expect to happen and when It happens it’s kinda hard to take a screen that shows it

**Comment by HackuJacku** [comment]
@Mosawer-hub I need to know what move you're using, which Pixelmon used it and which Pixelmon it was against please.

**Comment by Mosawer-hub** [comment]
So it was a clefable both times First time it was against a conkeldurr where I used moonblast which is suppose to almost kill but did 0% And second time I used flamethrower on a Galarian darmanitan Where it did 0%

**Comment by HackuJacku** [comment]
Tested and unable to reproduce. Warzone is getting an overhaul so if this is an issue with the new version, please re-report it.
