### ISSUE TITLE
Kit permissions are weird

### ISSUE THREAD

**Issue by Keone0** [SmashMC-Development/Bugs-and-Issues#1090]
I have legend rank and have perms to claim Ace and Legend but not other kits in between. Also, do not have access to /kit list. Not sure if I'm supposed to have access to Ace or just Legend.

**Comment by Mikirae** [comment]
Believe you're supposed to have access to just Ace. I'll get that fixed. 
Which server is this on?
Also, it's /kits, not /kit list, I believe

**Comment by Superfire96** [comment]
The issue was fixed, each rank has access to just their respective kits
