### ISSUE TITLE
Ha alolan marowak breeding glitch

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1091]
**Describe the Bug**
_Snor1ax_ has been breeding ha alolan marowak male with a ditto for 4 days, is yet to recieve a ha egg, has gotten around 40 eggs, and still no ha. Has tested with everstones on either pokemon, but has not tested with normal ha cubone.

**To Reproduce**
1. Catch normal ha cubone
2. Evolve it into ha alolan marowak
3. Breed a male ha alolan marowak with a ditto 

**Servers with the Bug**
Rayquaza

**Expected behavior**
Should produce ha cubone eggs

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by ghost** [comment]
Would appreciate if you guys could test breeding normal HA cubone because I evolved mine into alolan before breeding.

**Comment by Mikirae** [comment]
This unfortunately sounds like a Pixelmon bug to me.

**Comment by Mikirae** [comment]
Just bred like 100 Regular and Alolan HA Marowaks and didn't get a single HA from any of them. Definitely a Pixelmon bug unfortunately :(

**Comment by ghost** [comment]
Thanks for the update......also did you report it...or I need to?

**Comment by Mikirae** [comment]
You can if you’d like. Otherwise I will when I wake up :)
