### ISSUE TITLE
GTS Broken

### ISSUE THREAD

**Issue by Hrlm023** [SmashMC-Development/Bugs-and-Issues#1092]
**Describe the Bug**
GTS keeps breaking whenever i put in 5 pokemon and 1 gets sold i cant put on a new listing. It happend again just now,
we got a restart but that didnt fix the problem. 10 minutes later its bugged again.

**Servers with the Bug**
Rayquaza

**Comment by Rasgnarok** [comment]
Forwarded, thank you.
