### ISSUE TITLE
Mart NPCs

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Bugs-and-Issues#1094]
**Describe the Bug**
The naturally generated mart NPCs does not function. 

**To Reproduce**
1. Go to a random generated mart with a NPC
2. Right click on them
3. You are unable to interact with them

**Servers with the Bug**
Kyogre

**Expected behavior**
The NPCs should sell different items such as TMs and other stuff.

**Additional context**
I will say, that this might be intentional. There is however an issue regarding this in response to issue #1093, where before you could buy TMs possibly hidden power, which you now cannot. A variance of move tutors at mart would really help.

**Comment by Mikirae** [comment]
So does it open a blank shop? Or it just doesn't do anything whatsoever?

**Comment by HobnobberJunior** [comment]
Nothing at all.

**Comment by Mikirae** [comment]
Weird. I'll take a look at this later this week :)

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
