### ISSUE TITLE
Galar darumaka -> normal darmanitan 

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1096]
**Describe the Bug**
Someone on rayquaza used an ice stone to evolve their galarian darumaka and it evolved into a normal darmanitan instead of the galarian darmanitan it is supposed to evolve into.

**To Reproduce**
1. Go to server
2. Get a galarian darumaka
3. Evolve it with ice stone

**Servers with the Bug**
Rayquaza, might need testing to see if this happens every time or just rarely. 

**Expected behavior**
Galarian darmanitan 

![unknown](https://user-images.githubusercontent.com/86555718/151221288-5acb1675-d2b1-4128-baa2-19ff2698ddea.png)
 
Has ice move from galar darumaka and fire move from darmanitan

**Comment by Mikirae** [comment]
This is a Pixelmon bug and we can't do anything about it, unfortunately :(
