### ISSUE TITLE
/dexquest not working

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1097]
**Describe the Bug**
When you do /dexquest the menu doesn't pop up. Doesnt say something in chat like 'u dont have permission' or 'this is an unknown command'. Just nothign happens. It was fixed for a little while after the new dexquest came out last wednesday but now its not working again.

**To Reproduce**
1. go to a server
2. type in /dexquest
3. nothing pops up. not the menu and nothign in chat

**Servers with the Bug**
All (checked myself)

**Expected behavior**
I'd expect the dexquest menu to pop up

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jantjewieger** [comment]
Also please make it so that we can use /dexquest from warzone to check what else needs to be caught

**Comment by Mikirae** [comment]
Unfortunately can't be done currently do to the issue I mentioned in your other ticket; GUIs cause it so battles aren't forced I believe.
As for the broken DexQuest, we're working on getting it fixed :)
