### ISSUE TITLE
/hunt issue

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1098]
**Describe the Bug**
pokemon on /hunt changed before timer finished
Magcargo still had about an hr left but changed to weepinbell before timer finished

**Servers with the Bug**
kyurem

**Expected behavior**
pokemon on hunt changed when timer hits 0

![2022-01-27_15 13 38](https://user-images.githubusercontent.com/83971987/151390456-b41a16da-77b0-4c49-a8af-bf38fbf82d2a.png)
![2022-01-27_15 10 01](https://user-images.githubusercontent.com/83971987/151390461-ecb67c91-15b1-44aa-af3f-d9ab84ab5434.png)

**Comment by Mikirae** [comment]
I haven't touched Hunts. Can you take a look and see if this is a config error on our end or a bug with the plugin?

**Comment by Superfire96** [comment]
I believe it is fixed, haven't seen it happening any more times after that
