### ISSUE TITLE
Reshiram e4

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#1099]
**Describe the Bug**
Barely any pokemon have made it onto the teams we are supposed to use, only 1-2 pokemon are on 3 teams and 6 on 1 of the teams

**To Reproduce**
1. Go to reshiram
2. do /ag manage
3. click on the teams
4. See that there isn't the correct amount of mons on each team

**Servers with the Bug**
reshiram, all others I have it on seem to be fine

**Expected behavior**
all 12 pokemon appear

**Screenshots**
![2022-01-27_09 18 11](https://user-images.githubusercontent.com/83245837/151400151-81c29772-69af-4929-91b5-9ce6bd02a6e8.png)
![2022-01-27_09 18 24](https://user-images.githubusercontent.com/83245837/151400171-d80a3262-378d-4f1e-8bc3-bc89e10313af.png)
![2022-01-27_09 18 30](https://user-images.githubusercontent.com/83245837/151400191-20aad267-12c2-4487-a3a1-31bf27aa4618.png)
![2022-01-27_09 18 17](https://user-images.githubusercontent.com/83245837/151400214-9e1a47cd-e182-47fc-8d9d-d6f90900e1af.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Fixed
