### ISSUE TITLE
pokehunt is still broken on Charizard

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#110]
**Describe the Bug**
When players complete a /hunt it announces in chat and lets the player know that it was completed but the player doesn't received the money

**To Reproduce**
catch requested hunt mon
see notification
player doesnt recieve cash or balls/candies

**Servers with the Bug**
Charizard ( as its there for testing purposes)

**Expected behavior**
it should give expected rewards

**Screenshots**
https://cdn.discordapp.com/attachments/812186860352045058/841918572154191872/image0.png

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Shoji007** [comment]
@HackuJacku  just wanted you let you know it was FrstEzzi that was dealing with a ticket about this. Refer to 21641 for more.

**Comment by HackuJacku** [comment]
Need to know the exactly details of the hunt please.

**Comment by Shoji007** [comment]
@FrstEzzi need you to answer this

**Comment by HackuJacku** [comment]
Should be fixed in the 8.2 update.

**Comment by HackuJacku** [comment]
Changes are now live.
