### ISSUE TITLE
Shader Bug

### ISSUE THREAD

**Issue by FrostbittenBerri** [SmashMC-Development/Bugs-and-Issues#1100]
When you use the shader "AstraLex", and look at the water in rtp it shows what looks like a texture pack for pixelmon in the water.
**To Reproduce**
1. Download and use  Recent AstraLex Shaders 
2. Use rtp and find water
3. Scroll down to 'What looks like a texture pack in the water.

**Servers with the Bug**
Rayquaza only known so far

**Expected behavior**
Its annoying when i look at water so if it is fixable i just want it removed from the water 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A on here but discord is  (っ◔◡◔)っ ♥ Asuna ♥#2814 

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A
Minecraft User: FrostbittenBerri

**Comment by Mikirae** [comment]
This is a clientside issue and we can't do anything to fix it, unfortunately. 
I've never had issues with Chocapic Shaders if you want to give those a try.
