### ISSUE TITLE
GTS Bugged

### ISSUE THREAD

**Issue by CKxgod** [SmashMC-Development/Bugs-and-Issues#1101]
**Describe the Bug**
When i try to show items on the gts list menu it flashes and closes

**To Reproduce**
1. Go to Groudon
2. /gts
3. Click on New listing
4. Click on show Items
5. See error

**Servers with the Bug**
Groudon

**Expected behavior**
i shouldve switched to showing items

**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Was this fixed after a server restart? Or is it still happening?

**Comment by Rasgnarok** [comment]
I'm going to need from both tickets a full description of what exactly is happening, how many listings you had this happen on, and when (or if) it got fixed.
