### ISSUE TITLE
Smash Rank Perms on Rayquaza

### ISSUE THREAD

**Issue by PescadoMan** [SmashMC-Development/Bugs-and-Issues#1102]
**Describe the Bug**
Smash Rank has perms on Groudon that lets them do &k in their nickname, but on Rayquaza you can't.

**Servers with the Bug**
Rayquaza

**To Reproduce**
1. Go to Rayquaza
2. Type /nick and &k to your name
3. See message saying, "You do not have permission to use the following in nickname: obfuscated."

Please provide a list of which servers have this bug.
Rayquaza

**Expected behavior**
It should and the special moving characters to your nickname.

**Screenshots**
Rayquaza:
![image](https://user-images.githubusercontent.com/84924885/151615126-3fcf5256-57c5-42bf-a189-1cd8ae8e0d51.png)

Groudon:
![image](https://user-images.githubusercontent.com/84924885/151615082-3d08c420-1711-41e9-9991-17b122ef00c5.png)

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
We have removed obfuscated formatting from being accessible via /nickname, as it can be prone to causing seizures in visually impaired players.
