### ISSUE TITLE
Friday raid dens not spawning

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1103]
**Describe the Bug**
Last week, nobody found the boss raid den that was supposed to appear at spawn. and this week there has been no den to be found either, leading me, and others, to believe that it does not spawn at all 

**To Reproduce**
1. Go to server on friday 
2. Wait for boss raid den 
3. Look for the den

**Servers with the Bug**
Rayquaza, could be all 

**Expected behavior**
Den to exist

**Comment by Mikirae** [comment]
Was there any message saying it spawned?
I've never touched Raids so I don't know if it announced typically.

**Comment by Dxhcky** [comment]
It was announced, but not once had a player been able to find it. Personally I looked across the entirety of spawn and there was no boss at all

**Comment by Mikirae** [comment]
Okay, I’ll take a look at it later

**Comment by Dxhcky** [comment]
Nothing spawned yesterday on groudon server either, meaning it is most likely a network wide issue

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
