### ISSUE TITLE
Crate Raids?

### ISSUE THREAD

**Issue by WickedDino1** [SmashMC-Development/Bugs-and-Issues#1106]
When I opened a vote crate I got pulled into a raid

1. Go to 'the /vote command'
2. Click on 'vote (and do the stuff necessary)'
3. open the crate
4. I got pulled into a raid

I only know of the rayquaza server doing this

I was gonna get an item/pokemon

N/A

N/A

**Comment by Mikirae** [comment]
That's actually incredibly weird and I've never heard of anything like it. Were you able to reproduce it? Or was it just that one freak occurrence?

**Comment by WickedDino1** [comment]
Sorry it only happened to me that once but if it happens again I will take
a screenshot and show you
