### ISSUE TITLE
GTS pokemon won't show the pokemon icon/picture

### ISSUE THREAD

**Issue by timmystain96** [SmashMC-Development/Bugs-and-Issues#1107]
**Describe the Bug**

When i type the command /gts and it opens, i click to view the pokemon/items for sale and it shows me the items but it won't show me the pokemon pictures. Instead of their icons, it shows me pink and black checkered squares. I did ask in chat if anyone else was having the same issue and only one person replied. They said theirs was fine. 

**To Reproduce**
1. Go to /gts
2. Click to view items/pokemon for sale
3. The pokemon icon/pictures wont show, instead it gives me black/pink checkered squares. 

**Servers with the Bug**
Please provide a list of which servers have this bug.

Rayquaza server

**Expected behavior**

I want to be able to see the pokemon icons without having to hover over every individual item for sale to see what each one is. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

N/A

**Comment by Mikirae** [comment]
Do you have a Texture Pack on? They occasionally cause issues with sprites.

**Comment by timmystain96** [comment]
No, I don’t have any texture packs

**Comment by Mikirae** [comment]
Sorry, never saw you reply. Is this still an issue for you? Or did it simply happen once?

**Comment by timmystain96** [comment]
I checked again yesterday and it appears to be fixed.

**Comment by Superfire96** [comment]
The issue was indeed fixed
