### ISSUE TITLE
Using buy moves or relearner in tourney

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#1108]
**Describe the Bug**
 U can use the relearner at the mart during a tourney which from what I heard isn't supposed to happen because I heard from someone saying that relearners make tourney unfair. I also heard that the devs are trying to make it that u can't use /buymoves or relearner during tourney but u still can.

**Servers with the Bug**
Groudon but also probably all servers
**Expected behavior**
When I went to the relearner during tourney I expected to not be able to use it but instead u still can.
**Screenshots**
N/A
**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
