### ISSUE TITLE
/claimspawn Bug

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1109]
**Describe the Bug**
Ok so you made the claimspawn, but removed the claim and you can still tp there.

**To Reproduce**
1. make a claim
2. /claimsetspawn
3. move the claim by resizing so that the /claimspawn is outside the claim
4. /claimspawn
5. this should end up having you tp outside the claim to where you made the claimspawn earlier

**Servers with the Bug**
prob all pixelmon servers

**Expected behavior**
ehh probably have the /claimspawn reset each time the claim gets resized

**Additional context**
Sadly I wanted to use this to make a biome warp claim, each claim can have a max of 16? sub claims so I could make 16? biome warps tho a pain to make, it would be a nice quality of life thing to make on the server...but ehh guess its too broken. only found this out when I was resizing my claim cos you know explosions dont happen near claims...and I kind of needed to bed bomb an end island into the void. BUT oh well, already was planning on spending a few claims to make public biome warps, this just saves a lot.

**Comment by Mikirae** [comment]
Hi Ras can you see if there's an update that fixes this pretty please?

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
