### ISSUE TITLE
not healing after winning in wz

### ISSUE THREAD

**Issue by IronGolem19** [SmashMC-Development/Bugs-and-Issues#111]
**Describe the Bug**
one you win in warzone your pokes dont get healed

**To Reproduce**
1. Go to warzone
2. win
3. doesnt get healed

**Servers with the Bug**
Please provide a list of which servers have this bug.
rayquaza is the only server i known that has this issue
**Expected behavior**
expected to get healed after winning
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
After battling and winning against another player, my team was healed. Please can you provide us with more information because I have been unable to reproduce.

**Comment by IronGolem19** [comment]
so if you beat someone in warzone on rayquaza your pokemon will not be healed. it might of gotten fixed from the 8.2 update

**Comment by HackuJacku** [comment]
@IronGolem19 - please test again.

**Comment by IronGolem19** [comment]
issue has been fixed with the release of 8.2 sorry for taking so long.
