### ISSUE TITLE
Bugged Spawnpoint in Warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1110]
**Describe the Bug**
Bugged Spawn location that when u spawn in you cannot move

**To Reproduce**
1. Go to warzone
2. Get spawned on the specific area
3. Be unable to move

**Servers with the Bug**
Happened on Rayquaza but may be all

**Expected behavior**
Shouldnt be stuck

**Screenshots**
https://youtu.be/-_AOGbUQR18

Its is around these coordinates
![image](https://user-images.githubusercontent.com/84816052/151707357-75169fc2-ce81-4b6a-8931-61d4c02ac6c5.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Made it spawn you in one block higher so hopefully it doesn't happen in the future.
But also just don't get stuck lol
