### ISSUE TITLE
I  wanted to suggest that in rules you should add a rule saying player made mistakes are non refundable.

### ISSUE THREAD

**Issue by HypherDeath** [SmashMC-Development/Bugs-and-Issues#1115]
I wanted to suggest then in rules you should write player made mistakes are non refundable as ive seen many players expecting a refund when they have done something themselves.

**Comment by Rasgnarok** [comment]
While this would've been better in https://github.com/SmashMC-Development/Suggestions, I can say that this proposed rule would only ever apply in hard cases of player 'mistakes'. For instance, when someone wondertrade the wrong Pokémon. When you WT, you have a second command to CONFIRM you want to wondertrade the Pokémon you entered in the first command. I think it is reasonable to say that the kind of player mistake there is absolutely unrefundable, compared to say, /pay (insert typo'd username). Good idea, but in practice, unnecessary.

**Comment by HypherDeath** [comment]
sorry for putting it here
