### ISSUE TITLE
Voting website

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1116]
**Describe the Bug**
Not sure if this is something as a server we can fix, but there is a voting website that cannot be reached. It loads for a while then pops up with the message in the screenshot.

**To Reproduce**
1. Go to https://topminecraftservers.org/server/4609
2. Try to access the website
3. Comes up with error message

**Servers with the Bug**
it's a website..

**Expected behavior**
Should be allowed to get onto the website, and vote fluently

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/151813323-e1242926-218d-4f22-9ff4-e585a32cb632.png)

**Additional context**
This isn't an individual issue, has happened with other players aswell

**Comment by Mikirae** [comment]
That's on the vote site to fix, we can't do anything about it :(
