### ISSUE TITLE
Hidden Ability Announcement

### ISSUE THREAD

**Issue by llnama** [SmashMC-Development/Bugs-and-Issues#1117]
**Describe the Bug**
I may be shooting a blank here, but after catching a Hidden Ability pokemon, there was no reaction from chat and I thought it was peculiar but maybe they just didn't care. Fast forward to today where I was chatting to a friend and he said he just caught a HA Abra. However, there was no sort of message in my chat that showed it but there was a message in his chat.

I know that the "Hatched a Hidden Ability ......" text works whenever someone hatches a HA pokemon, so is there a reason why it doesn't show when the pokemon is caught? Well either way thought I should let you know.

**To Reproduce**
1. Catch a Hidden Ability Pokemon, may take you a few days but you'll get it eventually, maybe...
2. See the message in chat of you catching a hidden ability pokemon.
3. Type in joy in chat.
4. Get a bunch of confused faces!

**Servers with the Bug**
Rayquaza, probably all.

**Expected behavior**
Should show the caught message to everyone on the server.

**Screenshots**
N/A

**Additional context**
It would be funny seeing someone getting a Hidden Ability "Truant" Durant.

**Comment by Mikirae** [comment]
Does it show other things like when people catch a shiny or defeat a boss?
Because the announcement looks fine on the backend so it might be a bug with the plugin.

**Comment by llnama** [comment]
Yeah whenever a shiny is caught or defeated and boss is defeated it shows the message.
And right now (first time seeing this) someone defeated a hidden ability. So maybe it was just a fluke that it didn't appear for me.

**Comment by llnama** [comment]
Also it sometimes breaks, so whenever something spawns, like a shiny, boss or legendary, it doesn't say who it actually spawned on, and most cases its always the same person that pops up in chat.

**Comment by llnama** [comment]
oooh its showing it now

**Comment by Mikirae** [comment]
Welp I changed nothing but glad it's working now :)
Take care :D
