### ISSUE TITLE
Bug that wont give you Vote Crate Keys after Voting.

### ISSUE THREAD

**Issue by Arctic97** [SmashMC-Development/Bugs-and-Issues#1118]
Not Getting Keys after Voting using the Vote Links.

To Reproduce:
1. I got Online
2. Used /Vote to get access to all Vote Links
3. I opened up all the Sites
4. Voted for the server on all of the 5 Websites
5. While beeing Tabbed out of the Game it Disconnected me

Expected behavior:
even tho i know that Minecraft crashes due to Issues with Tabbing out of the Game while its in Fullscreen Mode, i never had Problems with voting while beeing tabbed out (even if you get disconnected after some Time) so i just didnt care and kept on Voting.

If this should ever happen to you just Message the staff and do the steps i did Below. The Problem should be solved soon enough.

Screenshots:
Here is the Conversation/Ticket i opened up with the kindly Staff:

![image](https://user-images.githubusercontent.com/98856364/152072145-63fe1547-03a3-4f7f-91a6-96ecca38094e.png)

![image](https://user-images.githubusercontent.com/98856364/152072289-5e52eb3c-0998-44df-83e2-f15f669d1b1e.png)

![image](https://user-images.githubusercontent.com/98856364/152072370-e065c827-d30d-44a8-a152-eb72f9a1bbd1.png)

![image](https://user-images.githubusercontent.com/98856364/152072434-72ea1e7c-b781-4daf-80d4-f609a7ffa7ae.png)

![image](https://user-images.githubusercontent.com/98856364/152072526-c9d00e90-4817-4059-a55e-e1d9dafa7f76.png)

**Comment by Superfire96** [comment]
Hey Artic, sadly when issues like that occurs, it's a problem on the website's end, and nothing much that we can do about it, but if it happens again to you/anyone else, feel free to open a ticket and we will refund the keys after having verified that you actually voted
