### ISSUE TITLE
dexquest incomplete

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1119]
**Describe the Bug**
We have a dexquest that says 'catch all mons that have a mega evolution' but the list is missing a charizard

**To Reproduce**
1. go to reshiram
2. do /dexquest
3. see that charizard is not on the list

**Servers with the Bug**
Reshiram

**Expected behavior**
I'd expect charizard to be on the dexquest

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/152240879-f10c89fc-a524-4417-ba7d-a0bdbe105f6c.png)

![image](https://user-images.githubusercontent.com/87021826/152240897-a1127531-b0f8-4bb9-adbf-a63033457e19.png)

![image](https://user-images.githubusercontent.com/87021826/152240918-39642d76-1ac1-4fc1-9ebf-9ac1a9434d49.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
Dexquest was removed, not an issue anymore!!
