### ISSUE TITLE
Gym Infinite Waiting Time Glitch

### ISSUE THREAD

**Issue by SiennaAffliction** [SmashMC-Development/Bugs-and-Issues#1120]
**Describe the Bug**
A waiting screen pops up that doesn't ever go away.

**To Reproduce**
It happens way too frequently, the first time this happened I used volt switch and it froze right after the damage was dealt, the second time one of my mons got knocked out by kartana in the steel gym and I wasn't able to send in another pokemon.

**Servers with the Bug**
All of them

**Expected behavior**
Either fix the glitch or have some compensation for those who's suffered from this glitch 

**Screenshots**
Just imagine a text box saying waiting.

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
This battle hangup has an infinite amount of ways it could happen, most often a combination of network packet data and battle data. This isn't just 'the waiting bug', but rather one of million possible cases in which it happens. We would need the timestamp of your precise battle, on a specific server, to be recorded, forwarded to then dig out through logs and see IF the battle spit out an error. If it did (and sometimes it doesn't), these logs get forward to the PixelmonMod, and they release battle-fixes. It's not a SmashMC issue.
