### ISSUE TITLE
Ultranecrozium Z drop

### ISSUE THREAD

**Issue by linefax** [SmashMC-Development/Bugs-and-Issues#1121]
Hello,

i have a question about the Ultranecrozium Z drop. 
I have asked 3 Helpers and 2 Mods about the drop, but no one could tell me where you can drop it and if you can even drop it.

Thats why im asking this way to get to know the drop and if it got removed maybe.

Im playing on the Rayquaza Server. Please tell if you can drop it, if yes where please.

**Comment by WalkAway7** [comment]
You've got a 10% chance of it dropping if you defeat/capture a wild necrozma. We don't have one in any of the stores though.

**Comment by linefax** [comment]
> You've got a 10% chance of it dropping if you defeat/capture a wild necrozma. We don't have one in any of the stores though.

So capture too, that means he has it as a held item? The wiki only says he can have a solarizer/lunarizer as a held item. I just wanna be sure that when i catch him he has a chance too.

**Comment by WalkAway7** [comment]
Actually, I think it's just a drop. I think I may have mixed up the capture for the solarizer or lunarizer.

**Comment by linefax** [comment]
> Actually, I think it's just a drop. I think I may have mixed up the capture for the solarizer or lunarizer.

Alright i guess i will stay afk in a roofed forest a bit. Ye i think its only when i defeat it. Ty for your answer.
This ticket can be closed(if it works on here the same as on discord)
