### ISSUE TITLE
Pokemon stuck in my team

### ISSUE THREAD

**Issue by Alfo-bubi** [SmashMC-Development/Bugs-and-Issues#1122]
**Describe the bug** 
My Pokémon Is stuck in my team, I can't put It in the pc.

**To Reproduce**
I have no idea how to reproduce this bug (maybe from trading)

**Servers with the Bug**
I have this problem on the Zekrom server

**Screenshots**
N/A (unluckily I can't put a screenshot right now)

**Additional context**
To risolve the bug I tried reconnecting, trading my Pokémon, changing the other Pokemon. He seems like he dosen't exist in the pc: when I go on his immage with the cursor (in the Pokémon pc) and I click nothing happens. Normally It should take the Pokemon so I can put him somewhere else, but with my Pokémon this don't seems to work. I think this problem started with the trade (I got my Pokémon trading) since the old trainer didn't tell me anything he probably hadn't this bug.

**Comment by Superfire96** [comment]
Could you provide me your ign please?
