### ISSUE TITLE
i keep lagging and stuff on the server and i dunno how to make it stop lagging my screen kept flashing and 2 i couldnt move

### ISSUE THREAD

**Issue by Zioxyy** [SmashMC-Development/Bugs-and-Issues#1123]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
Can't reproduce, please check your internet connecting and submit a fully written out ticket with logs if this continues to happen. Closing, invalid format.
