### ISSUE TITLE
dosint let ne go to items in gts

### ISSUE THREAD

**Issue by oneeyeking72** [SmashMC-Development/Bugs-and-Issues#1124]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Bugs-and-Issues/issues/1126

**Comment by Rasgnarok** [comment]
I'm going to need from both tickets a full description of what exactly is happening, how many listings you had this happen on, and when (or if) it got fixed.
