### ISSUE TITLE
Wormhole Bug

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#1125]
**Describe the Bug**
Not able to use /rtp ultra or spawn wormhole using the legendaries like arceus.

**Servers with the Bug**
Rayquaza, prob all.

**Screenshots**

![Screenshot (807)](https://user-images.githubusercontent.com/25759066/152493542-76682d3d-0b42-4eca-925f-a4e521972568.png)

**Comment by Superfire96** [comment]
Fixed, you are now able to open wormholes
