### ISSUE TITLE
I can not sell items on the GTS, but i can sell pokemon no commands work

### ISSUE THREAD

**Issue by Ice7even** [SmashMC-Development/Bugs-and-Issues#1126]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Reshiram
**Expected behavior**
Youre unable to sell items EX (Rare candies)
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
![2022-02-04 (3)](https://user-images.githubusercontent.com/99053491/152614267-8c429a59-3854-494a-a37c-8f62857205f3.png)

**Comment by Rasgnarok** [comment]
Duplicate, closing.

**Comment by Rasgnarok** [comment]
I'm going to need from both tickets a full description of what exactly is happening, how many listings you had this happen on, and when (or if) it got fixed.
