### ISSUE TITLE
Welcome to Rayquaza on groudon server

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1129]
**Describe the Bug**
When someone new joins groudon, it says in chat 'welcome to rayquaza'

**To Reproduce**
1. Go to groudon
2. Have a player join for the first time 
3. See error

**Servers with the Bug**
Groudon

**Expected behavior**
Say the right server

**Screenshots**
![image](https://user-images.githubusercontent.com/86555718/152645386-5035afc1-d1e2-49d3-ba2f-3d80b34f3c93.png)

**Comment by Rasgnarok** [comment]
Fixed.
