### ISSUE TITLE
Kyogre Warzone 

### ISSUE THREAD

**Issue by CaretsPuppy** [SmashMC-Development/Bugs-and-Issues#113]
**Describe the Bug**
No pokemon is spawning in the Warzone in Kyogre.

**To Reproduce**
Go into warzone, see it's empty.

**Servers with the Bug**
Kyogre

**Expected behavior**
Warzone has pokemon

**Screenshots**
N/A

**Additional context**
Possibly after server restart, players say began roughly 3-4 hours ago.

**Comment by Rasgnarok** [comment]
This was one of the issues fixed with the update, correct? @HackuJacku

**Comment by HackuJacku** [comment]
Fixed.
