### ISSUE TITLE
Cannot join any sub servers if chat is turned off 

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1130]
**Describe the Bug**
While in the hub, you are not able to join any sub servers if you have the chat turned off in the settings 

**To Reproduce**
1. Go to hub
2. Turn off chat
3. Try to join via nether star or npcs

**Servers with the Bug**
Hub

**Expected behavior**
Should be able to join

**Screenshots**

https://user-images.githubusercontent.com/86555718/152645763-54d6eb2d-813d-4676-8bc1-c878279fdf3b.mp4

Could not upload the longer video, but its decently simple to test

**Comment by Rasgnarok** [comment]
This is an issue with our bungeecord plugin forwarding, not something we can fix ourselves. Forwarded.
