### ISSUE TITLE
WZ bug

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Bugs-and-Issues#1131]
**Describe the Bug**
So, I just tried to go to wz and when I was sent into it it seemes that the world did not load and I could not do nothing, my time ran of and I got sent back.

**To Reproduce**
1. Go to the nether (I don't know if that affected)
2. Type /wz
2. Select enter warzone
3. Buy 10 mins

**Servers with the Bug**
Rayquaza

**Expected behavior**
Go to warzone

**Screenshots**
![Captura de Ecrã (67)](https://user-images.githubusercontent.com/99098141/152658550-329bbf27-920d-473c-92ca-1097fc168591.png)

**Additional context**
'N/A'.

**Comment by RatedPG21** [comment]
Could you test this again and see if it is still a problem?

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
