### ISSUE TITLE
Not able to engage in pokemon battle in warzone

### ISSUE THREAD

**Issue by HaaahnGaming** [SmashMC-Development/Bugs-and-Issues#1132]
Sometimes when i go to warzone, im having trouble with being able to throw my pokemon out (Pressing R as standard) 
In this way we are able to engage in battle with the pokemon in warzone

However, i have been having trouble with this exact thing, being able to engage in battle.

Because when i go to press R, to throw my pokemon out. Nothing happens - The standard message "You sent out ___ " or "You retrieved ___" 

That doesn't happen. It's like the game doesn't understand that im trying to sent out my pokemon

i have tried switching to my other pokemon in my party to, because that may fix the issue - But this doesn't seem to be the case, i am completely out of control and cant do anything to fix the issue

What always fixes the issue for some time is to close minecraft - Reopen and then boom, fixed

The problem lies in the fact that this happens, just randomly, and i miss out on some pretty nice pokemon in warzone because of this

I am writing this bug report because i just missed out on Arceus, i was in warzone, got really psyched because i have masterballs, so its an easy catch.... if ofcourse i was able to engage in the battle

Please fix this issue - Because its not the first legendary pokemon i've missed out on...

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
