### ISSUE TITLE
Wrong login message

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1133]
**Describe the Bug**
Whenever someone new Joines Reshiram it says 'Welcome to Rayquaza'

**To Reproduce**
1. Go to Reshiram (if u have never joined it before)
2. It will say in chat 'Welcome Wiepie_ to SmashMC Rayquaza'

**Servers with the Bug**
Reshiram

**Expected behavior**
I'd expect it to say 'Reshiram' instead of 'rayquaza'

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
