### ISSUE TITLE
gts bug

### ISSUE THREAD

**Issue by Frattix03** [SmashMC-Development/Bugs-and-Issues#1134]
**Describe the Bug**
when i try to sell item on the gts it say you are at the limit of how many listings u can have 

**To Reproduce** 
1.Go on kyogre
2. Click on /gts
3. Scroll down to new listings
4. See error u cant sell item/pokemon 

**Servers with the Bug** kyogre 
Please provide a list of which servers have this bug. 
kyogre and probably many other

**Expected behavior**
Expected to let me sell item on the gts
**Screenshots**
![image](https://user-images.githubusercontent.com/99101164/152661366-d474f25c-695e-4633-aad7-38a5667f9fc4.png)
![image](https://user-images.githubusercontent.com/99101164/152661378-0ba2d1d4-fa5c-4fd0-88f4-2c81f0599fd0.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'. 
N/A

**Comment by M1n0j** [comment]
@Frattix03 I believe this was fixed but correct me if I am wrong

**Comment by Superfire96** [comment]
The issue was fixed
