### ISSUE TITLE
On Kyogre, whenever someone new joins the server it says welcome to Rayquaza

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#1135]
**Describe the Bug**
The welcome message on Kyogre says Welcome to Rayquaza instead of Kyogre. 
**To Reproduce**
1. Go to Kyogre
2. Have someone new join
3. "Welcome to Rayquaza"

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre
**Expected behavior**
"Welcome to Kyogre"
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://user-images.githubusercontent.com/85481519/152663246-f9fb16cf-234d-47fa-8284-0fc88d4010d4.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Was fixed
