### ISSUE TITLE
"Zygarde Rebirth" quest bug

### ISSUE THREAD

**Issue by xentulol** [SmashMC-Development/Bugs-and-Issues#1136]
So ive been playing the smashmc server since palkia and I have had a fun time. this has to be one of the only times ive experienced any bugs in the server. 

So basically I got the Zygarde's Rebirth quest and tried to complete it and every part of the quest was going smooth until I got to the making of the zygarde cube. I made a cube and the quest didnt go through to the next step, i tried to do it again but it didnt work the second time either. Can anyone help me solve this problem or help me with the next steps?

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
