### ISSUE TITLE
idk if this is standard on the server but I'm unable to use all the external moves on the Pokémon some work but things like the lightning move wont 

### ISSUE THREAD

**Issue by sancho132** [SmashMC-Development/Bugs-and-Issues#1137]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Some of the external moves are disabled, most likely all the damaging ones. You can make a suggestion if you feel like they should be enabled
https://github.com/SmashMC-Development/Suggestions/issues
