### ISSUE TITLE
I can't put my dratini in a box. I go onto my profile, open box try to put dratini in it doesn't work. I only have the dratini 

### ISSUE THREAD

**Issue by EquinoxPyro** [SmashMC-Development/Bugs-and-Issues#1139]
**Describe the Bug**
I can't put dratini into a box

**To Reproduce**
1. Go to '...' rayquaza
2. Click on '....' my dratini
3. Scroll down to '....' I can't move it into a box

**Servers with the Bug**
Please provide a list of which servers have this bug.
I only have it on rayquaza but that could be because of me having the dratini only on rayquaza

**Expected behavior**
I expect the dratini to go on the box
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
n/a
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
I have sent the dratini to others they have the same problem

**Comment by Superfire96** [comment]
I believe we already solved this in game. Closing this up
