### ISSUE TITLE
you can use /buymove in warzone

### ISSUE THREAD

**Issue by IronGolem19** [SmashMC-Development/Bugs-and-Issues#114]
**Describe the Bug**
when your in warzone you can abuse it like fissure no guard machamp, it usually gets rid of fissure when you tp
but you can /buymove in warzone to abuse it

**To Reproduce**
1. Go to warzone
2. type /buymove
3. your able to put moves on and abuse it to your advantage

**Servers with the Bug**
Please provide a list of which servers have this bug.
dialga is the only known one to have this problem so far
**Expected behavior**
expected to not be able to use /buymove
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
n/a
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by Rasgnarok** [comment]
This is no longer a problem, /buymove should be allowed. No Guard + Fissure Machamp is not even scanned properly by Warzone. It'll be addressed in the revision.
