### ISSUE TITLE
GTS is still bugged on rayquaza

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1140]
**Describe the Bug**
A player had 4 pokemon on the gts but was unable to add any others, despite the cap being 5... They then removed 2 pokemon from the gts and were still unable to add any more for some reason. 

**To Reproduce**
1. Go to rayquaza
2. Sell pokemon on the gts
3. Sometimes you will be unable to list more, despite not being at the cap (why this happens I am not sure)

**Servers with the Bug**
Rayquaza... could be all 

**Expected behavior**
Be able to sell 5 pokemon on the gts at once

**Screenshots**
N/A

**Additional context**
The player told me they weren't trying to list a pokemon when they noticed this and that they were just trying to check the stats of the pokemon in their party at once. There have been a few reports with the same issue but I am unsure of the cause.

**Comment by M1n0j** [comment]
@Dxhcky I believe this was fixed but correct me if I am wrong

**Comment by Superfire96** [comment]
Was fixed
