### ISSUE TITLE
sold my pokemon didnt get the money

### ISSUE THREAD

**Issue by Crisp321** [SmashMC-Development/Bugs-and-Issues#1141]
I sold my Pokemon they were zamazenta and niheligo and didn't get the money

**Comment by M1n0j** [comment]
@Crisp321 Can you let us know more information on the issue. How did you sell the Pokemon, What server was it and do you have the logs from when this happened?

**Comment by M1n0j** [comment]
You could've also created a ticket on our Discord using #support to get the money returned to you

**Comment by Mikirae** [comment]
Not enough information, closing this ticket.
