### ISSUE TITLE
Groudon server voting

### ISSUE THREAD

**Issue by MartoSWD4** [SmashMC-Development/Bugs-and-Issues#1142]
**Describe the Bug**
The First vote link does not give any type of reward and the Forth give but does not show it in the chat.

**To Reproduce**
{1}.
1. Go to '/vote'
2. Click on 'First vote link (https://minecraftservers.org/server/548790)'
3. Scroll down to 'Vote to this server'
4. See error when I got back to the server

{2}.
1. Go to '/vote'
2. Click on 'Forth vote link (https://minecraft-server-list.com/server/464847/vote/)'
3. Scroll down to 'Vote to this server'
4. See error when I got back to the server

**Servers with the Bug**
Please provide a list of which servers have this bug.
I dont know for another servers but I am playing on Groudon server.

**Expected behavior**
{1}.
I expect the console and website to connect and issue  commands for chat message and reward give. 

{2}.
I expect the console and website to connect and issue  commands for chat message.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
I haven't got screenshots.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
All vote sites have the same rewards as the current plugin doesn't allow for changing, and we cannot change voting sites not giving rewards sometimes as that's a bug on their end, unfortunately.
But thank you for reporting this!
