### ISSUE TITLE
Groudon /dexquest command 

### ISSUE THREAD

**Issue by MartoSWD4** [SmashMC-Development/Bugs-and-Issues#1143]
**Describe the Bug**
In the chat that message popout: " There's a dex quest active! View it with '/dexquest'! " but when I issue an /dexquest command nothing happend neither on my screen or in the chat

**To Reproduce**
1. See in 'chat'
2.Write in '/dexquest'
3. Nothing happens

**Servers with the Bug**
Please provide a list of which servers have this bug.
Groudon server

**Expected behavior**
I dont know exactly what, but something have to popout on the screen (maybe some type GUI)

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
I
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Dexquest was removed due to it causing various issues, will see if we can add it back in the future
