### ISSUE TITLE
Pheal stopped working

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1144]
**Describe the Bug**
/pheal was recently added and has been working fine, but since I got on this evening it is an 'unknown command'

**To Reproduce**
1. Go to a server 
2. Type /pheal
3. See error

**Servers with the Bug**
Groudon, probably all 

**Expected behavior**
/pheal to work

**Comment by Mikirae** [comment]
In the future, please include the error, as it would have told me that it simply was never created as an alias. 
Done for next restart though <3
