### ISSUE TITLE
Arceus Wormhole not working

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Bugs-and-Issues#1145]
**Describe the Bug**
When I try to open a wormhole with arceus it says exactly this:"Move Skills> You are unable to use Open Woemhole in this world"

**To Reproduce**
1. Trhrow arceus out
2. Select open wormhole as external move
3. Use external move
**Servers with the Bug**
Rayquaza

**Expected behavior**
Open a wormhole

![Photo](https://user-images.githubusercontent.com/99098141/153436620-7f028729-738b-4e46-b854-98d7f2b8cc5d.jpg)

**Comment by Mikirae** [comment]
Fixed for next restart :)
