### ISSUE TITLE
Fix Boss Tower!

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#1146]
**Describe the Bug**
Spawn rates of bosses are too low. Drops are pathetic and it is not being used at all.

**Servers with the Bug**
All.

**Comment by M1n0j** [comment]
@arjungangwar0 The boss tower has since received an upgrade so I do not believe this is still necessary?

**Comment by Mikirae** [comment]
Boss tower was buffed as mentioned above. Closing this
