### ISSUE TITLE
Tab Issue

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#1148]
**Describe the Bug**
Helper ranks higher than ever other rank in tab.

**To Reproduce**
Go onto a server with a helper on. 
Press Tab and see how they are higher than you. (noob)

**Servers with the Bug**
All servers

**Expected behavior**
Mod, sr-mod, admin, manager, developer and owner to rank higher

**Screenshots**
![image](https://user-images.githubusercontent.com/86004012/153722049-ac5bbcf9-7324-4a6f-8167-a867100b8dbb.png)

**Additional context**
I believe this also occurs with Builder but I am not 100% sure. I would give it a 80%

**Comment by aorosdev** [comment]
Hi Archie - I made some direct changes on the Reshiram realm so this should be fixed. When you get a chance, please check this out and let me know if it's working or if you're still having the same issue. Thanks!

**Comment by Mikirae** [comment]
LET HIM KNOW @Archie4690

**Comment by Superfire96** [comment]
> 



> Hi Archie - I made some direct changes on the Reshiram realm so this should be fixed. When you get a chance, please check this out and let me know if it's working or if you're still having the same issue. Thanks!

It's still not showing correctly

![image](https://user-images.githubusercontent.com/83550357/163578560-1e4abb38-e253-40bd-b8a4-5f494bd7f1b2.png)

**Comment by Mikirae** [comment]
I'm fairly certain it's bugged in the plugin as the prefixes are too long.
We need to make them something like [H] for it to work properly and do the
sorting, I believe. At least that's the way it looks to me

**Comment by Archie4690** [comment]
Issue has been fixed.
![image](https://user-images.githubusercontent.com/86004012/163731268-1a08976d-b353-45da-b38f-0dc93ad7d464.png)
