### ISSUE TITLE
Speed potins for wz

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Bugs-and-Issues#1149]
**Describe the Bug**
I can have speed 2 potions in warzone and helpers said they're blacklisted.

**Servers with the Bug**
Rayquaza

**Expected behavior**
The potions should go to the warzone bank.

**Screenshots**
N/A0.

**Additional context**
N/A.

**Comment by Rasgnarok** [comment]
Closing, has now been fixed.
