### ISSUE TITLE
Ghost tower bosses not giving loot drops

### ISSUE THREAD

**Issue by AmsterDaan** [SmashMC-Development/Bugs-and-Issues#115]
**Describe the Bug**
Killing a boss at wild generated ghost boss tower will not give any drops.

**To Reproduce**
Go to a boss tower, kill a pokemon

**Servers with the Bug**
Only Charizard

**Expected behavior**
Bosses are meant to drop items once being defeated there.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed on next reboot.
