### ISSUE TITLE
Infinite warzone time

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1150]
**Describe the Bug**
When i battle someone in warzone, and they disconnect, it will give me infinite warzone time.

**To Reproduce**
1. Go to Reshiram (perhaps all servers)
2. type /warzone in chat
3. go to warzone
4. Battle someone in warzone
5. The other person disconnects while in warzone
6. I get infinite warzone time

**Servers with the Bug**
Happened on Reshiram, might be all but cant check.

**Expected behavior**
I'd expect the timer to continue once the battle ends bc of a disconnect.

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/153929099-c209ae5c-b8af-4cad-90b7-1b5a93777d11.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
Looks like this got fixed at some point. Thank you for reporting :)
