### ISSUE TITLE
Catching Pokemon as you are safeplacing

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1151]
**Describe the Bug**
When you catch a pokemon while safeplacing, if you throw a master/park ball the game thinks you caught it but you are kicked out due to the safeplace. This causes the Pokemon and ball to be lost while stat catcher registers the catch

**To Reproduce**
1. Go to warzone
2. Catch a pokemon while safeplacing
3. Stat catcher registers it put it wont be in the bank

**Servers with the Bug**
All

**Expected behavior**
Should either give the pokemon in the bank or not allow you to try catch at the point you are going to safeplace

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/153935689-e360fcae-2073-4ae9-86b9-1b37f6f5841d.png)
![image](https://user-images.githubusercontent.com/84816052/153935700-74e0f4a8-cb98-4f33-ba70-540938bc7292.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Do you know if this is fixed in the latest version? I remember there being something about this, I believe. (I can refund a master ball for testing)

**Comment by Mikirae** [comment]
You can't throw PokeBalls while safeplacing now so I'm closing this and you can't stop me
