### ISSUE TITLE
Ranks + Staff Chat Colour issue

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1152]
**Describe the Bug**
Chat colour disappears when you have a rank and a staff rank (I believe it is only a Senior Mod issue)

**To Reproduce**
1. Have Senior Mod
2. Buy a Rank (I have Elite)
3. Chat colour turns to white

**Servers with the Bug**
All 

**Expected behavior**
Staff colour should stay as purple and not turn to white

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/153936729-1683fe41-6906-42d3-9253-706d7f7c7fd2.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
CAN YOU TELL ME IF IT'S FIXED????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by Dwag0n** [comment]
IT IS MIKIRAE THANK

**Comment by Mikirae** [comment]
POGGERS CHAMPION
