### ISSUE TITLE
blaziken in dungeons

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1153]
**Describe the Bug**
U cannot use Blaziken in dungeons. But blaziken is natdex so it should be allowed

**To Reproduce**
1. go to Reshiram
2. put a blaziken in ur team
3. type in chat /dungeons
4. click on any dungeon
5. it will say 'invalid team' 

**Servers with the Bug**
Happened on Reshiram but probably all i think

**Expected behavior**
I'd expect Blaziken to be allowed

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
It's staying banned because I cannot ban Megastones unfortunately.
