### ISSUE TITLE
Status Cinditions in Warzone

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#1155]
**Describe the Bug**
Status conditions are still not healing after a wild pokemon battle and we don't have full heal before player battle. So, if your pokemon gets statused by wild pokemon in warzone and someone battles you afterwards....they have a unfair advantage. 

**Servers with the Bug**
Rayquaza but probably all.

**Expected behavior**
Pokemon in your party should be fully healed including status after wild pokemon battle in warzone.

**Comment by RatedPG21** [comment]
Are you able to provide us with a video? I have had this before and the Pokémon was healed when I was battled

**Comment by ghost** [comment]
No. Didn't record it.

**Comment by ghost** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/25759066/154066483-f26eeb48-afb4-49d0-b2e3-15315506aae4.png)

**Comment by ghost** [comment]
there you go

**Comment by Mikirae** [comment]
We've got an internal ticket open about this, so I'm closing it. (Going through some older tickets. Sorry for the late reply <3)
