### ISSUE TITLE
banned items in warzone

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1156]
**Describe the Bug**
If u enter warzone with a fishing rod in ur inv it gets automatically placed into ur warzone bank. However shulker boxes do not get placed into ur warzone bank. So when u put a fishing rod or elytra in ur shulker box they will not be taken to ur warzone bank. This way u can get banned items into warzone

**To Reproduce**
1. Go to any server
2. get a shulker box
3. put elytra/fishing rod in the shulker
4. go to warzone
5. take elytra/fishing rod out of shulker
6. have banned items in warzone

**Servers with the Bug**
Reshiram and ray but probably all

**Expected behavior**
I'd expect the shulker to be banned or the banned items to be teleported out of the shulker into the warzone bank

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Disabled entering Warzone with Shulker boxes.
Thank you!
