### ISSUE TITLE
Healer in the second dungeon

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1157]
**Describe the Bug**
The first healer in the second dungeon doesn’t work properly, when you right click the npc it doesn’t do anything.
**To Reproduce**
1. Go into the medium difficultly dungeon
2. Clear the first and second stage
3. Go to the healer and try to heal your Pokémon

**Servers with the Bug**
Seen on Kyogre and Groudon

**Expected behavior**
Should be able to heal your Pokémon
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
So it just doesn’t do or say anything when you right click it?

**Comment by RatedPG21** [comment]
Yep it does nothing, can confirm it has happened to me and someone else.

**Comment by Superfire96** [comment]
For context, for me it says that i can't use the healer

![image](https://user-images.githubusercontent.com/83550357/163577856-46cb337b-5209-4758-aa10-fbb06245eb42.png)

**Comment by Mikirae** [comment]
Reported and am waiting to hear back. I can't do anything until then
unfortunately :(

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
