### ISSUE TITLE
Pokemon still rideable and in open world after Wondertrade

### ISSUE THREAD

**Issue by AethiosStrife** [SmashMC-Development/Bugs-and-Issues#1158]
**Describe the Bug**
After Fletchrinder evolved and was in open world I wonder traded it Talonflame was still in openworld and rideable even in battle after the trade.
1. Go to '...'     evolve non lead pokemon via Exp share.
2. Click on '....' wonder trade pokemon immediatly afte evolution while still on field
3. Scroll down to '....' ride pokemon 

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre but possibly more
**Expected behavior**
expected talonflame to dissapear after sending to Wondertrade
![Screenshot (10)](https://user-images.githubusercontent.com/99836195/154344095-9a3699c3-75f1-4eda-b523-b24ca453a456.png)
 in screen shot you can see i am riding talonflame but pokemon is not in my party

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
![Screenshot (10)](https://user-images.githubusercontent.com/99836195/154344192-8fce5cd5-0bda-47fd-bcee-363324bc102b.png)

**Comment by Mikirae** [comment]
This is unfortunately a rare Pixelmon bug that we're unable to fix.
Thank you for reporting, though :)

**Comment by AethiosStrife** [comment]
No problem thanks for getting back to me. I realized if I evolve a Pokemon and immediately wonder trade it then it would stay out on the field as long as I didn't warp. 

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 20, 2022 at 4:31 PM, ***@***.***> wrote:   


This is unfortunately a rare Pixelmon bug that we're unable to fix.
Thank you for reporting, though :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mikirae** [comment]
That’s the clearest explanation of the bug I’ve seen, so I’ll forward that over to the Pixelmon team. Thank you! :)
