### ISSUE TITLE
Wz Bug

### ISSUE THREAD

**Issue by PescadoMan** [SmashMC-Development/Bugs-and-Issues#1159]
**Describe the Bug**
In the wz when you defeat mons you don't get added time but if you catch them you do. Also, if you don't pick a mon before a battle in wz, it doesn't auto pick mons anymore.

**To Reproduce**
1. Go to wz
2. Fight Pokemon
3. Beat Pokemon
4. Recieve no additional time

**Servers with the Bug**
All

**Expected behavior**
Get 5 to 25 secs for beating a Pokemon.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Closing as we have a ticket on the internal Warzone tracker, but thank you for reporting :)
