### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by luke04683** [SmashMC-Development/Bugs-and-Issues#116]
**Describe the Bug**
There should be something implemented to the chat system because there are some people who simply forget the rules of what cannot be added to a chat message. Therefore a system that blocks out any prohibited words or characters etc should be implemented. I feel as if this would benefit us all.

**To Reproduce**
2. Click on '...'

**Servers with the Bug**
All servers 

**Expected behavior**
I expect if someone is to enter something against the rules then it shall not send then message into chat and show a message telling you it is invalid. For example if I were to add more than 4 or more of the same letter next to one another and send it to chat the message will not be sent and I will get an error message telling me character dragging is not allowed. I expect this for swears, spam, character dragging and any other prohibited activities in chat. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
This repository is for bugs and issues. Please open a suggestion request on the correct repository, using the appropriate format. Thanks.
