### ISSUE TITLE
Fall damage in wz

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1161]
**Describe the Bug**
There is now fall damage in warzone

**To Reproduce**
1. Go to warzone
2. jump from a cliff or something
3. take fall damage

**Servers with the Bug**
Think all but definitley on Reshiram

**Expected behavior**
I'd expect there not to be fall damage

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
This is fixed so I'm closing this and you can't stop me
