### ISSUE TITLE
Gts is bugged

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1162]
**Describe the Bug**
When u type in /gts it takes you straight to the gts system. U no longer get the option to choose between gts bank, auctionhouse, gts or things like that. Then there is no button to go back to the original menu. so all u can do is list things but not actually claim things you bought or sold. Because of this i cannot take things out my gts bank

**To Reproduce**
1. Go to Reshiram
2. Type in /gts
3. Get sent to the gts system without being able to choose from any other options
4. see no back button

**Servers with the Bug**
Reshiram but i think all

**Expected behavior**
I'd expect to see the original menu when u do /gts. That way i can claim things from my gts bank

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/154533427-e0a7a562-44aa-4ce1-a687-6cb2c259cef1.png)

**Additional context**

https://user-images.githubusercontent.com/87021826/154533738-0d445813-1cf3-462e-8b37-c4c802858814.mp4

**Comment by Mikirae** [comment]
I’m being told /gts bank will bring you there. 
We’ll look into getting the plugin fixed as this bug was brought about by the disabling of auctions.

**Comment by Superfire96** [comment]
> I’m being told /gts bank will bring you there. We’ll look into getting the plugin fixed as this bug was brought about by the disabling of auctions.

HI, is this still being worked on?

**Comment by Mikirae** [comment]
Reported it months ago and got no help, so I can't really do much. There is a workaround, so I'm closing this
