### ISSUE TITLE
Wz Move Bug

### ISSUE THREAD

**Issue by PescadoMan** [SmashMC-Development/Bugs-and-Issues#1164]
**Describe the Bug**
Block is currently bugged in pixelmon not making you able to escape even if you kill the pokemon or use teleport/u-turn/volt switch, etc, and even if they swap to another mon after you're still stuck

**To Reproduce**
1. Choose mon that has the move block
2. Switch out that mon
3. Now the other players mon is stuck until it kills mon with block

**Servers with the Bug**
All

**Expected behavior**
You should be able to escape even if you kill the pokemon or useteleport/u-turn/volt switch or if the mon with block switches out.

**Screenshots**
https://youtu.be/zzmFDgkrva8 : Pixelmon
https://replay.pokemonshowdown.com/gen8anythinggoes-1513171307-t70ercgx1d4yod2kx9bnx83n1kw1c5upw : Showdown

**Additional context**
N/A

**Comment by Mikirae** [comment]
This is a Pixelmon bug, but I can ban it from the Warzone.

**Comment by Mikirae** [comment]
Tried to block it via Warzone, but I'm having issues, unfortunately.

**Comment by Mikirae** [comment]
I can't do anything until Pixelmon fixes it on their end, if they haven't already. Closing this
