### ISSUE TITLE
Warzone not properly showing the teams after the battle has finished

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#1165]
**Describe the Bug**
When the battle in warzone finished normally with a winner, it shows both of the teams with 100% health. If the battle gets ended by the staff, it wont show any infos related to the teams, if one of the players logs out in warzone, it wont show either

**To Reproduce**
1. Go to /warzone
2. Battle someone
3. Log out / make someone end your battle

**Servers with the Bug**
Every server

**Expected behavior**
It should show the infos related to both of the teams in each case that was mentioned

**Screenshots**
Just the screenshot of my first point, showing every health % to 100% after one of the players wins
![image](https://user-images.githubusercontent.com/83550357/154560336-57bfb648-4099-455a-9b89-d82b27ed64ce.png)

**Comment by Mikirae** [comment]
I already have a ticket open for this, but thanks for reporting it cutie <3
