### ISSUE TITLE
E4 challenger challenges w different pokemon when challenging second gym

### ISSUE THREAD

**Issue by borkborkdog** [SmashMC-Development/Bugs-and-Issues#1167]
**Describe the Bug**
I have my team for elite 4 when i challenge it. When I accept an elite 4 challenge in the second gym my opponent gets my team. 

**To Reproduce**
Challenge the second elite 4 team
Your pokemon wont pop up, it'll be a different challenger's pokemon and yours will be voided

**Servers with the Bug**
Kyogre

**Expected behavior**
Player's team team gets voided and gets different player's team.

**Screenshots**
N/A

**Additional context**
I previously challenged elite 4

**Comment by borkborkdog** [comment]
Issue is resolved. If this happens to someone else dm me at Bork#4990

**Comment by piplupqueenn** [comment]
Issue not resolved, just happened on zekrom
