### ISSUE TITLE
No cancel button on gts

### ISSUE THREAD

**Issue by VikingLee03** [SmashMC-Development/Bugs-and-Issues#1168]
In the server when I type in the command /gts, it takes me to the trading page, not the page where I can click on gts bank or global trade or auction, when I'm at the trading page, there is no eject button that is suppose to be the cancel button, so I can't go back to get things I've bought.

I am not sure how this bug works, its stuck on the same bug, I closed out minecraft and even restarted my computer.

Happened in the rayquaza server

I expected it to be the first page of gts bank auction and trade.

https://cdn.discordapp.com/attachments/809082489678462996/944471802237816832/2022-02-19_00.34.26.png
N/A

**Comment by Mikirae** [comment]
You're able to do /gts bank to get to the bank. This is unfortunately a bug until Auctions gets fixed.
Closing as it's a duplicate issue :)
