### ISSUE TITLE
No white couch 

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1169]
**Describe the Bug**
At /warp mart in the decor section there are 2 red couches and no white couch

**To Reproduce**
1. Go to warp mart
2. Go into decor section
3. Scroll down to couches

**Servers with the Bug**
All

**Expected behavior**
white couch and not 2 red couches 

**Screenshots**
![Minecraft 1 12 2 20_02_2022 10_47_42](https://user-images.githubusercontent.com/86555718/154841850-dd120ce1-db36-42c7-b167-cd22d242a90c.png)

**Comment by Mikirae** [comment]
Honestly you just don't deserve a white couch imo

**Comment by Mikirae** [comment]
Done for next restart
