### ISSUE TITLE
Bugged/Glitched Shadow Parasect

### ISSUE THREAD

**Issue by Bkdevileu** [SmashMC-Development/Bugs-and-Issues#117]
**Describe the Bug**
The model for shadow Parasect is bugged/glitched. It seems the only shadow pokemon to be like this.

**To Reproduce**
Spawn shadow parasect.

**Servers with the Bug**
Giratina.

**Expected behavior**
Normal model for shadow Parasect.

**Screenshots**
![image](https://user-images.githubusercontent.com/84034504/118337826-7c9f9400-b50c-11eb-9b4f-49675f2cd5a1.png)

**Additional context**
The player had this mods on: 
![image](https://user-images.githubusercontent.com/84034504/118337926-c8ead400-b50c-11eb-8039-3ef0f8ca772f.png)

And had the Smashmc texture pack only.

**Comment by Rasgnarok** [comment]
I assume this just means the texture has to be updated. Low-priority, but will be done

**Comment by HackuJacku** [comment]
Using an outdated version of the resource pack - either update to v7.1 or use our Technic pack.
