### ISSUE TITLE
Spawn under a bridge in warzone 

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1170]
**Describe the Bug**
Someone joined warzone and spawned underneath a bridge with no escape

**To Reproduce**
Get unlucky when entering warzone probably 

**Servers with the Bug**
Groudon, not tested on others

**Expected behavior**
Dont get stuck under a bridge 

**Screenshots**
![image](https://user-images.githubusercontent.com/86555718/154946777-a58d1719-0940-4009-966a-2c97cc007064.png)

![image](https://user-images.githubusercontent.com/86555718/154946790-997a3e92-c723-4c76-b3c2-34b28065da05.png)

![Minecraft 1 12 2 21_02_2022 11_29_51](https://user-images.githubusercontent.com/86555718/154947153-3ad95aac-add1-4d13-bb1f-1ceeb56068ad.png)

**Comment by Mikirae** [comment]
I made it spawn a few blocks above. Should be good now
