### ISSUE TITLE
Warzone joining message not showing up

### ISSUE THREAD

**Issue by linefax** [SmashMC-Development/Bugs-and-Issues#1173]
**Describe the Bug**
When you are in WZ and other people join, you dont see the message "... has joined the warzone" you can only see them leaving.

**To Reproduce**
1. Go to '/wz' and wait for someone to join, you should not be able to see the joining message.

**Servers with the Bug**
Rayquaza

**Comment by RatedPG21** [comment]
This was an intended feature added recently

**Comment by Superfire96** [comment]
It has been removed intentionally, will be announced in the next changelogs
