### ISSUE TITLE
Wz joining bug

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Bugs-and-Issues#1174]
Describe the Bug
When you are in Warzone and other people join, you dont see the message that someone joined the warzone you can only see them leaving.

To Reproduce

Go to /warzone and wait, you should see when someone joins to but you don't.
Servers with the Bug
Rayquaza

**Comment by RatedPG21** [comment]
This was an intended feature added recently

**Comment by Mikirae** [comment]
Correct. This was added yesterday as a suggested feature :)
