### ISSUE TITLE
Warzone pokemon dont giving time

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Bugs-and-Issues#1175]
**Describe the Bug**
Defeating a pokemon in warzone does not give time.

**To Reproduce**
1. Go to '/warzone'
2. Defeat a pokemon

**Servers with the Bug**
Rayquaza

**Expected behavior**
Get time from defeating any pokemon in warzone.

**Additional context**
I asked helpers if it is how it's supposed to be now but they said it's a bug,

**Comment by Mikirae** [comment]
It's on the bug list. It should be fixed soon :)

**Comment by Mikirae** [comment]
Closing this as it's a duplicate, but thank you for reporting!
