### ISSUE TITLE
10000+ Hour Cooldown

### ISSUE THREAD

**Issue by borkborkdog** [SmashMC-Development/Bugs-and-Issues#1178]
**Describe the Bug**
Players have a 10000+ hour cooldown for warzone

**To Reproduce**
After server restart players have the (14000h cooldown) when trying to join wz

**Servers with the Bug**
Kyogre and Groudon so far (Most likely all of em)

**Expected behavior**
Should be able to join wz

**Screenshots**
<img width="604" alt="Screen Shot 2022-02-23 at 12 13 32 AM" src="https://user-images.githubusercontent.com/88428417/155265172-822ec7c3-4751-44b3-9a14-ca94f927269f.png">

**Comment by Mikirae** [comment]
Fixeddddddddd
