### ISSUE TITLE
Mining skill

### ISSUE THREAD

**Issue by xXbumisXx** [SmashMC-Development/Bugs-and-Issues#1179]
**Describe the Bug**
All mining skills dont work. Like vein miner and etc.

**To Reproduce**
1. Go to /skills
2. Click on mining skill (have to be allready unlocked)

**Servers with the Bug**
all

**Expected behavior**
fixed

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
