### ISSUE TITLE
Daily quest not giving out the rewards

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#1180]
**Describe the Bug**
The daily quest "Creating Magenta Houses" is not giving any rewards

**To Reproduce**
1. Any server
2. Get the quest
3. Complete it

**Servers with the Bug**
Every server

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83550357/155383374-4f4f7cb5-36a1-41a2-b7b8-defead2ea530.png)

**Comment by Mikirae** [comment]
Does this happen with all the Creating X House ones, do you know?

**Comment by jantjewieger** [comment]
Not all miki. Just sometimes

**Comment by Mikirae** [comment]
And is this with just the house ones? Or others too? Can't really find an
error in the config :(

**Comment by jantjewieger** [comment]
Others too. Saw one once with like 'craft 0 fast balls'

**Comment by Superfire96** [comment]
Fixed
