### ISSUE TITLE
Gts Sell Broken

### ISSUE THREAD

**Issue by Graydemon** [SmashMC-Development/Bugs-and-Issues#1181]
Username: Graydemon
**Describe the Bug**
When I try to sell something on the gts it does not work.

**Servers with the Bug**
Please provide a list of which servers have this bug.
Reshiram

**Comment by M1n0j** [comment]
@Graydemon I have just tested this on Reshiram and it does seem to be working

**Comment by Mikirae** [comment]
This is an intermittent issue and I have opened a ticket about it already on GTS itself, so I'll be closing this. Thank you for reporting :)
