### ISSUE TITLE
Space alter in /warp shrines doesnt work

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1182]
**Describe the Bug**
You arent able to use the space alter at /warp shrines

**To Reproduce**
Go to /warp shrines
Try to right click the alter with a red chain

**Servers with the Bug**
Rayquaza

**Expected behavior**
Should allow you to use it

https://user-images.githubusercontent.com/90443761/155835348-6ef54e00-1262-40b3-8b90-18a66822e449.mp4

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
So is this happening with everyone? I'm looking in the config for this and I don't even see anything that says the message about already using it, so I'm a bit confused. I suppose we could just try breaking it and putting it back down.

**Comment by RatedPG21** [comment]
Well it was happening with me and the player who the items belonged to, I guess we could test it again with someone else, but if it’s happening to two people I think it’s a problem with the shrine

**Comment by Mikirae** [comment]
I got busy and I guess this was glossed over. Do you know if this is still an issue?

**Comment by Superfire96** [comment]
It is still an issue, i've just tested it

**Comment by Superfire96** [comment]
Fixed
