### ISSUE TITLE
Miners Madness Not Working

### ISSUE THREAD

**Issue by OmegaNyx** [SmashMC-Development/Bugs-and-Issues#1183]
Whenever you click or try to activate miners madness it just glitches and will not take you to select the pickaxe to equip it too. The shovel feature works so thats why im writing this ticket because im assuming the pickaxe should too. Thank you!
Link To The Video: https://youtu.be/mfRirNs4NfY

**Comment by Mikirae** [comment]
We have a few tickets, on this, so I'll be closing it. Thank you :)
