### ISSUE TITLE
Gts sell issue

### ISSUE THREAD

**Issue by Katakuris** [SmashMC-Development/Bugs-and-Issues#1184]
**Describe the Bug**
When I do /gts sell nothing happens. I have had this issue for several days.

**To Reproduce**
1. I don't know what to fill in here

**Servers with the Bug**
No idea

**Expected behavior**
I Expected Just For It To Go Away After A Few Days I Guess

**Screenshots**
N/A

**Additional context**
N/A

**Comment by M1n0j** [comment]
"/gts sell" doesnt work on Groudon, Kyurem and Zekrom I have tested it on the others

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
