### ISSUE TITLE
Amulet Coin not working on Kyogre server maybe all servers idk 

### ISSUE THREAD

**Issue by TheNoSkill** [SmashMC-Development/Bugs-and-Issues#1186]
1. get coin from meowth 
2. equip it on a pokemon
3. fight trainers 
4. get the same amount of money from defeating trainers with amulet coin 
5. says it will increase the amount of coins from defeated trainers
screenshot: N/A
Other info: N/A

**Comment by Mikirae** [comment]
I do believe that we disabled Amulet Coin as it made it hard to balance out trainers. The message isn't something we can change, though.
