### ISSUE TITLE
Warzone, able to fall into the void

### ISSUE THREAD

**Issue by SlotMach1n3** [SmashMC-Development/Bugs-and-Issues#1187]
**Describe the Bug**
There is a pathway up on the mountains to then an open area to fall into the void.

**To Reproduce**
[Steps to reproduce the behavior:
https://www.youtube.com/watch?v=GFrMvGjKZqc

**Servers with the Bug**
I know this is a thing on Rayquaza, but pretty sure all the warzone maps are the same across all the servers.

**Expected behavior**
Not being able to fall off the map

**Screenshots**
![image](https://user-images.githubusercontent.com/99997669/156476633-e2c5d028-3f20-4fba-91fa-42ecb18e10fb.png)

**Additional context**
Fix as soon as possible ty

**Comment by DinglePringleUwU** [comment]
Same on Kyogre
https://github.com/SmashMC-Development/Bugs-and-Issues/issues/949

**Comment by Superfire96** [comment]
Fixed
