### ISSUE TITLE
bypass legend protection

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1189]
**Describe the Bug**
When a legendary spawns on you (in the wild, outside of warzone) there is a legend protection. That should not allow others to engage/catch the legendary. The engaging still works fine. However if a legendary spawns on me then others can throw balls at the pokemons (so throwing balls at the mons without engaging the mon). This bypasses the legend protection. And although the chance of catching it like this is very low there is still a chance to catch a mon that still has legend protection. And if u use a mball it will be a 100% catch on the legend still under legend protection.

**To Reproduce**
1. Have a legendary spawn on u outside of warzone
2. Have someone else throw a (master)ball at it
3. Other player will catch it even though legend protection is still on for the legendary

**Servers with the Bug**
All

**Expected behavior**
I'd expect them not to be able to bypass the legend protection like this

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
I believe the developer of it is no longer developing plugins, but I'll see if there's a different one out there that can fix this :)
Thank you for reporting!

**Comment by Mikirae** [comment]
This is fixed in the new plugin, so I'll be closing this. Thank you :)
