### ISSUE TITLE
/safeplace doesn't tp you to spawn

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Bugs-and-Issues#119]
**Describe the Bug**
When doing /safeplace it doesn't tp you to spawn after 5 seconds

**To Reproduce**
1. Go to rayquaza warzone and try /safeplace

**Servers with the Bug**
Rayquaza

**Expected behavior**
Sending you to spawn after 5 seconds

**Screenshots**
https://gyazo.com/e2db28177fd817921eac36db916bcd19

**Additional context**
N/A

**Comment by Sparklix** [comment]
Also after fighting your pokemon aren't healing

**Comment by Mikirae** [comment]
Are these issues fixed now?

**Comment by HackuJacku** [comment]
@Sparklix - please check after the next reboot.

**Comment by HackuJacku** [comment]
Confirmed that this is now fixed.
