### ISSUE TITLE
Second E4 on Kyogre and Zekrom giving the incorrect teams

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1191]
Describe the Bug
When someone challenges the second E4 the Elite 4s team that is in the pc gets given to the opponent. The E4 member then doesn't receive their team

To Reproduce
Challenge the second elite 4 team
Your Pokémon wont pop up, it'll be a different challenger's Pokémon and yours will be voided

Servers with the Bug
Kyogre and Zekrom

Expected behavior
Player's team team gets voided and gets different player's team.

Screenshots
https://youtu.be/Zc2VvkqudNc
https://youtu.be/hX1yk28AztA
https://youtu.be/YfS8fLcPYNo

Additional context
The E4 members had previously challenged the E4

**Comment by Rasgnarok** [comment]
Can you retest this now?

**Comment by M1n0j** [comment]
Tested on Zekrom and it seems to be working now.
Kyogre still need testing if anyone with E4 there could try test plz 😄

**Comment by borkborkdog** [comment]
Works on kyo too now :)

**Comment by Superfire96** [comment]
Fixed then
