### ISSUE TITLE
The Battle Recap is incorrectly displayed

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1192]
**Describe the Bug**
The Battle recap that appears when someone crashes/leaves in warzone is incorrect

**To Reproduce**
1. Warzone
2. Fight someone
3. They leave/crash
4. The battle recap always displays all Pokemon at 100%

**Servers with the Bug**
All

**Expected behavior**
Should show the correct amount of damage done in the battle

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/156824452-762f9ce1-33fa-493a-993e-914d082cc6b6.png)

**Additional context**

**Comment by Mikirae** [comment]
Closing this as it's fixed in the next version :uwu: :froggers:
