### ISSUE TITLE
Movement plates disappearing

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1194]
**Describe the Bug**
If you place two movement plates in an infinite loop, the plate you place will disappear 

**To Reproduce**
1. Go to a server
2. Place 2 movement plates facing eachother
3. See error

**Servers with the Bug**
All

**Expected behavior**
Plates should not disappear 

**Screenshots**

https://user-images.githubusercontent.com/86555718/157070153-a2f5f4d9-30c1-4c4c-ad63-c771f60fb067.mp4

**Comment by Mikirae** [comment]
This is unfortunately a Pixelmon bug. I just tested it in Singleplayer.
