### ISSUE TITLE
Warzone rules dont work properly

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1196]
**Describe the Bug**
I am able to bring a minimize clef into warzone. Unsure if this is a Reshiram thing or if this is just a clef thing. But i could use minimize on the clef while in warzone

**To Reproduce**
1. Get a mon(clef) with minimize
2. Go to warzone with the mon with minimize
3. be able to use minimize

**Servers with the Bug**
Reshiram but probably all

**Expected behavior**
I'd expect Minimize to be banned in warzone bc of minimize clause
**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/158268392-9244eccb-82ab-46a7-a732-0f844c4f496b.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
For some reason we had Evasion Abilities blocked but not Evasion Moves lol. Fixed on next restart. Thank you :)
