### ISSUE TITLE
Breeding Yamask always gives me a galar one, idk if its a bug, or if i have to do a certain thing

### ISSUE THREAD

**Issue by Id00d00onurmum** [SmashMC-Development/Bugs-and-Issues#1197]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
I believe this is a Pixelmon bug. You might be able to give it an Everstone as I've heard that works, but I'm not entirely sure.
