### ISSUE TITLE
Server Rollback Bug

### ISSUE THREAD

**Issue by GiffyG** [SmashMC-Development/Bugs-and-Issues#1200]
**Describe the Bug**
When server restarts, there seems to be a rollback depending on if it was a server crash or regular scheduled restart
this crashed restart seems to rollback player's currency only as it seems that players who experienced this restart lost/gained in-game currency or placed blocks but had no issues in term of Pokémon gained or lost between the crash. Compared to a scheduled restart in which all the aforementioned issues do not occur.

**To Reproduce**
1. Take note of items/placed blocks/in-currency prior to crash
2. Gain/Lose in-game currency/previously placed blocks
3. Server Crash
4. Take note of differences in items/placed blocks/in-game currency when server comes back online.

**Servers with the Bug**
Rayquaza, possibly all

**Expected behavior**
Server crash rolls back player currency/placed blocks.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Thank you for the detailed report!
Just to be sure, you're saying that money isn't lost when the server just has a regular restart? Only when it crashes unexpectedly?
Or you're saying it occurs with both?

**Comment by morrow12** [comment]
U always lose the money whenever the server restarts even if it gets manually restarted/crashes. U only lose money not items or pokemon.

**Comment by M1n0j** [comment]
Has now occurred on Zekrom too

**Comment by Mikirae** [comment]
This should now be fixed for regular restarts. Unfortunately, do to the way Minecraft works, there will always be issues with crashes, however
