### ISSUE TITLE
Kit ace usable?

### ISSUE THREAD

**Issue by Happi1223** [SmashMC-Development/Bugs-and-Issues#1201]
**Describe the Bug**

**To Reproduce**
Every rank has access to kit ace
**Servers with the Bug**
Please provide a list of which servers have this bug.
Ray but possible all
**Expected behavior**
idk i dont think it should be removed but was told to report it because I think all ranks should have access to each kit from ranks below that rank
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Thank you for reporting!
It's been fixed :)
