### ISSUE TITLE
Dynamax / Mega band randomly disappearing

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#1202]
**Describe the Bug**
When joining the server there's a chance that both of your bands will disappear, like if you never had them, upon on reloading they will show again. Kinda hard for the players to realise that until they need the bands, for example in warzone battles

**To Reproduce**
1. Having the bands
2. Join any server
3. Open your inventory
4. See if the error happened

**Servers with the Bug**
Rayquaza, couldn't test on all the other servers

**Expected behavior**
The Bands should not disappear

**Comment by Mikirae** [comment]
Ras do you know if this is a Pixelmon Bug?

**Comment by Mikirae** [comment]
Does this still happen?

**Comment by Mikirae** [comment]
HELLOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Superfire96** [comment]
SORRY, i didn't receive the notification of your response for some reason, and not really, or at least hadn't any more reports of it happening

**Comment by Mikirae** [comment]
OKAY CLOSING THANKS DAD
