### ISSUE TITLE
Shop Suggestion

### ISSUE THREAD

**Issue by Bear6336** [SmashMC-Development/Bugs-and-Issues#1203]
I think evolve stones should be added to the shops. Right now the best method I have found is farming bosses at haunted towers. I'm not sure on the prices, but I think ot wouldn't affect the economy too much and make them easier to obtain.

**Comment by Mikirae** [comment]
Please make a ticket over on our suggestions GitHub :) This one is for Bug Reports
https://github.com/SmashMC-Development/Suggestions/issues
