### ISSUE TITLE
Tournament glitch

### ISSUE THREAD

**Issue by EboyZenks** [SmashMC-Development/Bugs-and-Issues#1204]
i enterd the tournament with no one else in and then the tournament started and said the tournament ended with no winners even tho i was still in it - pip forced me to do this

**Comment by M1n0j** [comment]
From what I can see this was a change made on the 20/1/22 which can be see in #announcments I also sent a ss here so you can see
![image](https://user-images.githubusercontent.com/84816052/160295244-41c41d40-6e8f-457f-969f-6d8286dea8dc.png)

**Comment by Mikirae** [comment]
This is indeed not a bug. Thank you for reporting, but this is intended :)
