### ISSUE TITLE
Bodypress is broken 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#1205]
**Describe the Bug**
Bodypress in the new update now takes its atk power off of its atk stat instead of its defense stat 

**To Reproduce**
I used a crawdaunt and skarmory and I attacked the crawdaunt with skarmory and it did about 45% and after I boosted my defense with iron defense it did 45% again 

**Servers with the Bug**
zekrom is all I know 

**Expected behavior**
It should take its atk power off of the def stat

**Screenshots**
'N/A'.

**Additional context**
'N/A'.

**Comment by M1n0j** [comment]
This sounds more of a pixelmon bug rather than a server side one. I have made a bug report on the Pixelmon Website 
Ticket ID: 17176

**Comment by Mikirae** [comment]
This is a Pixelmon bug yes. We can't fix it unfortuantely
