### ISSUE TITLE
No Tapus in Ray WZ

### ISSUE THREAD

**Issue by Firemelon66** [SmashMC-Development/Bugs-and-Issues#1206]
**Describe the Bug**
Sice i heard on other server the tapus spawn i wanted to mention it 

**To Reproduce**
Like the Tapus didnt spawn once

**Comment by borkborkdog** [comment]
I think MIki was working on this, not sure on updates thoough.

**Comment by Mikirae** [comment]
This is fixed upon next restart on all servers. Thank you for reporting :)
