### ISSUE TITLE
Restart/Rollback Makes Recent Transactions Disappear

### ISSUE THREAD

**Issue by borkborkdog** [SmashMC-Development/Bugs-and-Issues#1208]
**Describe the Bug**
Whenever someone gets money from either or a player or the GTS right before a server reset/rollback the player loses the money that was gained. 

**To Reproduce**
1) Someone sends money to a player
2) Server restarts/rollback
3) Player checks balance and is missing the sum that they were paid

**Servers with the Bug**
Rayquaza and Zekrom 100% will test with kyo tonight

**Expected behavior**
Player doesn't lose the money

**Screenshots**
Multiple tickets (45606, 45566, 44554, 45542....)

**Additional context**
N/A

**Comment by borkborkdog** [comment]
I know this is most likely a pixelmon bug but still gonna leave it here.

**Comment by Mikirae** [comment]
The restart issue should be fixed, crashes will always be an issue unfortunately
