### ISSUE TITLE
Raid Rewards

### ISSUE THREAD

**Issue by AstroLuvsMemes** [SmashMC-Development/Bugs-and-Issues#1209]
**Describe the Bug**
Raid rewards on rayquaza seem to be different than other servers as you cant get certain items on the rayquaza server itself

**To Reproduce**
Raids on Kyurem give Z crystals and Arceus plates from 4-5 star raids
Raids on Rayquaza do not give Z crystals and Arceus plates from 4-5 star raids

**Servers with the Bug**
Rayquaza

**Expected behavior**
Rewards are different between Rayquaza and other servers

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Fixed for next restart. Thank you for reporting!
