### ISSUE TITLE
Warzone Glitch

### ISSUE THREAD

**Issue by Skeletonio000** [SmashMC-Development/Bugs-and-Issues#121]
**Describe the Bug**
If someone stands on something in warzone, they cannot be attacked

**To Reproduce**
1. Go into warzone
2. Stand on something
3. Have someone try and battle you

**Servers with the Bug**
Charizard (I haven't checked on the other servers)

**Expected behavior**
You should be able to battle someone in warzone regardless if they are standing on something or not

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Is it still happening?

**Comment by Mikirae** [comment]
Is this when they're standing inside grass or something?

**Comment by Rasgnarok** [comment]
I can't reproduce, please open a new ticket if it happens still.
