### ISSUE TITLE
Doesnt force u to empty wz bank

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1211]
**Describe the Bug**
It doesnt force u to empty ur wz bank on Reshiram. even if u have 100 mons in ur wz bank u can still enter wz.

**To Reproduce**
1. have somethign in ur wz bank
2. do /wz
3. are free to enter wz as long as u have a team that is allowed

**Servers with the Bug**
Just reshiram (i checked)

**Expected behavior**
I'd expect it to force me to empty my wz bank before i enter again

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
I must have missed it or the files didn't upload.
Thank you very much for checking and reporting. Should be fixed now :D
