### ISSUE TITLE
Missing Textures and chat preview request

### ISSUE THREAD

**Issue by DarrenC07** [SmashMC-Development/Bugs-and-Issues#1212]
**Describe the Bug**
I have certain pokemon with textures (galaxy and in game ones) that do not display correctly. First one is my galaxy calyrex shadow rider form. Both my calyrex and spectrier are galaxy but when combined, the spectrier is missing its galaxy form. The second and third pokemon aren't custom texture but belong in the game itself, and they are alter rayquaza and meta groudon. When I mega evolve the rayquaza, it loses the texture and becomes green instead. A similar issue happens with the groudon when I give it a red orb. When I try to primal evolve it, it loses its meta texture and becomes a regular primal groudon.

**To Reproduce**
For caly:
1) combine a galaxy spectrier with galaxy calyrex

For the ray:
1) Have an alter ray
2) Teach it dragon ascent
3) Mega evolve it

For the groudon:
1) Have meta groudon
2) Give it its red orb
3) primal evolve it

You can also swing by the Rayquaza server and I can demonstrate as well.

**Servers with the Bug**
I only caught these on Rayquaza since I only play there but it might be all servers.

**Expected behavior**
I only expected the galaxy caly to keep its texture and same goes for the other two.

**Screenshots**
![2022-03-30_04 29 29](https://user-images.githubusercontent.com/102655472/160789613-c4e60d9b-15a1-48af-8c75-2befee06a8f1.png)
![2022-03-30_04 29 34](https://user-images.githubusercontent.com/102655472/160789615-4239c62c-ab95-4ee9-a69d-282e76b7a3f7.png)
![2022-03-30_04 31 09](https://user-images.githubusercontent.com/102655472/160789619-125f1eab-7ffc-4b43-a3a0-ada00c4ad5b3.png)
![2022-03-30_04 32 23](https://user-images.githubusercontent.com/102655472/160789621-64aa9c5e-9140-4497-b2e6-185fb5855b60.png)
![2022-03-30_04 34 32](https://user-images.githubusercontent.com/102655472/160789623-92624265-ee22-4d99-a5eb-c9468eef83d6.png)
![2022-03-30_04 35 01](https://user-images.githubusercontent.com/102655472/160789625-012a0e72-81de-4b62-873f-ee6ab54a22f8.png)
![2022-03-30_04 40 17](https://user-images.githubusercontent.com/102655472/160789627-c360a983-d09b-4562-84d2-4f13f7f54303.png)

*The first two calyrex picture is before I updated to the latest texture pack and the last calyrex picture is after*

**Additional context**
I'm not sure if the ray and groudon are possible as it comes with the mod itself but it would be cool if the textures could be added in. As a side note too, I was wondering if it was possible to display certain in game forms in chat the same way a shadow or galaxy pokemon would. What I mean is right now when I try to show my ray and groudon in chat, they come up as the regular blue colour whereas when I show galaxy pokemon, they come up as red. If certain special textures such as alter, ashen, spirit, strike, etc. could also be made the colour red it would make it a "cooler flex" and give it more attention. This is just a small thing that doesn't really matter too much just thought would be a cool addition. I've seen people try and show alter and ashen forms before but since it came up as blue, many would ignore it in chat.

**Comment by WalkAway7** [comment]
Are you sure you've got the latest texture pack downloaded?

**Comment by DarrenC07** [comment]
Yep, I do have the latest texture downloaded as double checked before
screenshotting.

**Comment by DarrenC07** [comment]
It’s version 1.8.1 right?

**Comment by WalkAway7** [comment]
The latest version is in the discord, check #smashmc-info

**Comment by DarrenC07** [comment]
For me, the texture pack link doesn’t work but I used the technic launcher (or whatever it’s called) to install the latest version.

**Comment by Mikirae** [comment]
From what I remember, these were Pixelmon bugs. 
For the Shadow Rider/Ice Rider forms, I remember a texture artist telling me that no matter what they did on their end, they couldn't make it so that both of the mons had a texture when they were the combined form. I'll give it a bit more testing here later to see if maybe something got fixed in the most recent update, but I don't remember reading anything on it, so I'm not too hopeful.

For the Alter Ray and Meta Groudon, those are also both Pixelmon bugs that we unfortunately can't do anything about :(

**Comment by DarrenC07** [comment]
Hey no worries man I’m in absolutely no rush and just thought I’d bring those issues to light. What do you think about giving textures such as alter a different text colour when shown in chat?

**Comment by Mikirae** [comment]
If you mean the /show, I unfortunately don't think I can do that on my end,
as that's a developer thing. I can see if the developer of it would be
willing to make that change, though :)
Gotta find who it is first as I don't remember lol

**Comment by DarrenC07** [comment]
Lmao all good and thanks for the reply. I just thought it'd be a cool addition for those who hunt alter and other special textures.

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
