### ISSUE TITLE
E4 bugged (ray)

### ISSUE THREAD

**Issue by Firemelon66** [SmashMC-Development/Bugs-and-Issues#1213]
Rayquaza (may other servers too)
if someone challenges the 2nd e4 (in this scenario me) my pokemons get transfered to him like he gets my pokemons i used to battle the first e4 
Dont know how to fix it or why it happens (we tried it now i beat _dwagon with a new team and now Bighero_ got the team i used against the first 1 when i tried to beat the first time lilastrx i used an other team and people like tapls got my other team then) 
hope this is helpful

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
