### ISSUE TITLE
Tapus Dont spawn in wz

### ISSUE THREAD

**Issue by morrow12** [SmashMC-Development/Bugs-and-Issues#1214]
**Describe the Bug**
Tapus dont spawn in wz like tapu fini koko bulu lele. i belive they can spawn in wz on other servers.

Rayquaza

**Expected behavior**
Tapus to spawn in wz.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
n/a

**Comment by Mikirae** [comment]
Fixed for next restart :)
Will announce all the legends that are fixed tomorrow
