### ISSUE TITLE
1st vote link broken

### ISSUE THREAD

**Issue by Mantas9** [SmashMC-Development/Bugs-and-Issues#1215]
**Describe the Bug**
You are able to vote on the 1st voting link, but you do not get a key afterwards

**To Reproduce**
1. /vote
2. Click 1st link
3. Vote
4. Key isnt received

**Servers with the Bug**
Tested on rayquaza, but may be in the others too

**Expected behavior**
a vote key to be given to me

**Screenshots**
![image](https://user-images.githubusercontent.com/87035153/161197797-fb905d74-67c9-4edb-82a1-955dfa613810.png)
![image](https://user-images.githubusercontent.com/87035153/161197845-6de41691-1f62-4766-81cd-0e0b28f75c35.png)

**Additional context**
[latest.log](https://github.com/SmashMC-Development/Bugs-and-Issues/files/8394805/latest.log)

**Comment by Mikirae** [comment]
Does this happen every time? Or did it happen once?
