### ISSUE TITLE
Dynamax bug in warzone

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1216]
**Describe the Bug**
You can still dynamax in warzone despite the changes to it being that you couldn't. 
I was wondering around warzone, and I was just catching mons and I wasn't doing anything special, when I encountered a gligar and I saw that my dynamax option was open, and that I could click it and it would show the dynamax moves. However I did not fully click it, as I know it isn't allowed. So, I'm not too sure that it isn't a visual glitch or not. I'd like to leave the experimentation of this up to the staff instead of me so that I don't get penalized for using this bug.

**To Reproduce**
1. Enter the warzone
2. behave as normal
3. attack a wild mon (not sure whether this works on players or not)
4. see that you have the option to dynamax.

**Servers with the Bug**
Reshiram (haven't tested on any other servers)

**Expected behavior**
You should not have the option to dynamax, and should not get the moves.

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/161323124-b029c887-1c08-476c-9637-9b5cd731e9b3.png)

**Additional context**
This was made as of a result of ticket no. "45793". On that ticket is a small video, if needed.

**Comment by Mikirae** [comment]
I believe that the Battle Rules (where the Dynamax option is disabled) applies only to Player Battles, and not wild battles. If you want to Dynamax on the Gligar to assert your dominance, feel free :)
