### ISSUE TITLE
nether star broken lobby 2

### ISSUE THREAD

**Issue by Mantas9** [SmashMC-Development/Bugs-and-Issues#1217]
**Describe the Bug**
nether star does not work in lobby 2

**To Reproduce**
1. end up in lobby 2
2. right click nether star
3. See error

**Servers with the Bug**
lobby 2. Others are fine

**Expected behavior**
for the server list gui to appear

**Screenshots**
i have a video (the mic is not on purpose, im serious): 
https://www.youtube.com/watch?v=Xm6yGDSAigc
**Additional context**
N/A

**Comment by Mikirae** [comment]
I FIXED IT, THANK YOU GOOD SIR
THE MIC THOUGH LMFAO
