### ISSUE TITLE
Lose consumable held items against players in warzone

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1218]
**Describe the Bug**
If a consumable held item on a pokemon is used up during a battle against another player in warzone, the item is removed / deleted

**To Reproduce**
1. Go to warzone
2. Use consumable item, e.g focus sash
3. End battle

**Servers with the Bug**
Kyogre, could be all

**Expected behavior**
Keep item 

**Screenshots**

https://user-images.githubusercontent.com/86555718/161445522-c60971ce-f7d2-4d9f-b189-02db45e6dead.mp4

https://user-images.githubusercontent.com/86555718/161445465-abb7f1fc-9d25-4fe6-8af2-85c79a39462d.mp4

https://user-images.githubusercontent.com/86555718/161445471-63a6eb82-45da-4154-ac05-fdb10b55d424.mp4

The galvantula has a sash on that is used in battle but is not there afterwards

**Comment by Mikirae** [comment]
This is a feature, not a bug. Consumable held items are supposed to be used. If you'd like to see it changed, please fly on over to our suggestions github.
