### ISSUE TITLE
Pokemon don't spawn in bug dungeon 

### ISSUE THREAD

**Issue by TimesBlitz** [SmashMC-Development/Bugs-and-Issues#1219]
**Describe the Bug**
In the bug dungeon the Pokemon were not spawned in 

**To Reproduce**
1. Go to '/dungeon'
2. Click on 'medium'
3. enter the dungeon and 

**Servers with the Bug**
Reshiram

**Expected behavior**
some Pokemon should not spawn 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'. NA

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'. NA

**Comment by Mikirae** [comment]
Is this every time it happens? Or is it occasionally bugging out?

**Comment by TimesBlitz** [comment]
every time I had my friend try and some didn't spawn for him

**Comment by Mikirae** [comment]
That's really weird. I'll try to run it tomorrow and see if it happens for
me. Is it the first room? Or just happening throughout the dungeon?

**Comment by TimesBlitz** [comment]
throughout the dungeon

**Comment by Mikirae** [comment]
Okay, thanks for all the info :)

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
