### ISSUE TITLE
Survival some commands aren't working 

### ISSUE THREAD

**Issue by British-Commie** [SmashMC-Development/Bugs-and-Issues#122]
**Describe the Bug**
/rewards, /kits, Are not working 

**To Reproduce**
Use the relevant command
On /rewards, it just doesn't work
On /kits, everything is locked, even member

**Servers with the Bug**
Survival

**Screenshots**
![2021-05-16_12 12 02](https://user-images.githubusercontent.com/83977283/118393586-e9fc1380-b637-11eb-9779-4c3bf7bb3a06.png)
![image](https://user-images.githubusercontent.com/83977283/118393666-20d22980-b638-11eb-86c5-ba4b7125ab04.png)

**Additional context**
N/A

**Comment by British-Commie** [comment]
Just found out quests are broken too FYI

**Comment by jahangir6969** [comment]
Quest and rewards are now commands

**Comment by jahangir6969** [comment]
rewards now run the commands again.

**Comment by British-Commie** [comment]
They all Work ill close the report now
