### ISSUE TITLE
Gts isnt allowing some players to sell items on GTS

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1220]
**Describe the Bug**
Some people cannot sell items on GTS using /gts and /gts sell

**To Reproduce**
1. Go toRayquaza
2. Do /gts or /gts sell
3. Not be able to sell items

**Servers with the Bug**
Seen on Ray

**Expected behavior**
Should be able to sell items

**Screenshots**
No screenshots but when you do it nothing appears with no errors

**Additional context**
Only seems to happen for certain players. Seen with Me(M1n0j), morrrow and Firemelonworrior

**Comment by Mikirae** [comment]
So like it just doesn't open the GUI? Or what?

**Comment by M1n0j** [comment]
No GUI appears and when you click the pokeball in /gts to swap it it flashes and nothing changes

**Comment by morrow12** [comment]
Yeah happening to me alot it fixed after 5 hours

**Comment by Mikirae** [comment]
Reported it to the dev, but he's a bit busy currently unfortunately

**Comment by morrow12** [comment]
Yeah its ok fix it whenever, it isnt a major bug so take your time.

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
