### ISSUE TITLE
PVP spam

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1221]
**Describe the Bug**
when at /warp bosstower if you fall in the lava you get spammed with "You are not allowed to pvp" messages

**To Reproduce**
1. go to bosstower
2. fall in lava
3. you get spammed

**Servers with the Bug**
all servers I believe

**Expected behaviour**
shouldn't spam your whole chat out

**Screenshots**

https://user-images.githubusercontent.com/89798207/161545565-06da7177-05dc-4297-97f6-b94787019dd3.mp4

**Additional context**
N/A

**Comment by Mikirae** [comment]
Well you’re not allowed to PvP!!!!!
I think I can turn off the messages for that in chat. Thank you for reporting it :)

**Comment by Mikirae** [comment]
I forgot to say that I looked into this, and we have messages disabled and it still does it. It seems like it's a bug with the plugin unfortunately :(
