### ISSUE TITLE
Welcome message wrong

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1222]
**Describe the Bug**
Whenever a player joins reshiram for the first time, it says, "Welcome to Rayquaza"

**To Reproduce**
1. Go onto reshiram
2. new player joins
3. says welcome to Rayquaza

**Servers with the Bug**
Reshiram from what I know

**Expected behavior**
Should say welcome to reshiram

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/162544833-b8142281-8218-4e51-a91d-1d791095423e.png)

**Additional context**
N/A

**Comment by borkborkdog** [comment]
Ye happens on kyo too.

**Comment by RatedPG21** [comment]
Also zekrom ^^

**Comment by Mikirae** [comment]
And no one reported this until now? 😢 
I’ll fix it tomorrow. Thank you <3

**Comment by WalkAway7** [comment]
It's such a common issue, and it's happened before so I just automatically assumed someone had made it, especially if it was a problem server wide. But hey, I've done it now. Thanks miki <3

**Comment by Mikirae** [comment]
DONE FOR NEXT RESTART AND THANKS AGAIN
