### ISSUE TITLE
Mining Skills

### ISSUE THREAD

**Issue by JustDivinee** [SmashMC-Development/Bugs-and-Issues#1223]
In the server Reshiram there is the mining skill level 50 called Vein Miner
Wich should allow you to mine ore veins in one sweep but that does not work at all i have tried every method possible
i dont know if you guys are already up to date on this.

JustDivinee

**Comment by Mikirae** [comment]
I’ve heard a few of the skills don’t work, and unfortunately there haven’t been updates to the plugin in a while. I’ll give it a go tomorrow and see if I can find anything

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
