### ISSUE TITLE
Weird particles at crates

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1224]
**Describe the Bug**
On reshiram, there is some particles in the middle of /warp crates. They seem to have been missplaced from perhaps the "event" crate. I've also looked on other servers, and events is the only crate not having a particle aura. But only reshiram has these particles in the middle.

**To Reproduce**
1. Go to reshiram
2. do /warp crates
3. see the aura in the middle 

**Servers with the Bug**
Reshiram is the only server which has the particles, but not particles for the event crate. Every other server does not have the particles, but also doesn't have any particles for the event crate.

**Expected behavior**
the particles shouldn't be there, they should be at the event crate.

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/162636703-3e4a6fb0-e264-46bf-9fa7-c061e9542da8.png)
![image](https://user-images.githubusercontent.com/89798207/162636711-9cd9ab74-854c-4bea-b68d-6693e8041452.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
I know the cause of this, and it's fixed for the next restart. Thank you for reporting <3
