### ISSUE TITLE
Losing items in dungeon

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1225]
**Describe the Bug**
Whenever u have items in your inventory after u leave a dungeon (either by clearing it or by losing) the items will disappear. This is the case when u take items off of your pokémon for example but also when u get a reward from any /skills. The items will then disappear and also not be there again once u re-enter a dungeon (video included)

**To Reproduce**
1. Go to a dungeon
2. take one of the items off of ur mons or get a reward from /skills
3. beat/lost the dungeon
4. get teleported out
5. Lose the item

**Servers with the Bug**
All far as i know but tested on Reshi for sure

**Expected behavior**
I'd expect the items to not disappear. (get sent to dungeon bag or something upon leaving dungeon)

**Screenshots**
N/A

**Additional context**

https://user-images.githubusercontent.com/87021826/162827133-764829fd-c1c6-470c-bf98-bdb309871431.mp4

**Comment by ajdawg48** [comment]
u check ur /dungeon bag ?

**Comment by jantjewieger** [comment]
yes aj i did

**Comment by Mikirae** [comment]
I'll forward this one over

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
