### ISSUE TITLE
Focus Sash Keeps Getting Consumed

### ISSUE THREAD

**Issue by ShrunkMicrobe46** [SmashMC-Development/Bugs-and-Issues#1226]
**Describe the Bug**
When I am in a battle with an actual person they activate the sash and once im done with the battle the sash is no longer there it ended up being consumed.

**To Reproduce**
1. Put a sash on a pokemon
2. Have the pokemon with the sash get it consumed
3. Finish the battle
4. Check if the sash is still there. (may not work all the time)

**Servers with the Bug**
I only play on Zekrom, i am unaware if the other servers have this problem

**Expected behavior**
When your in a battle with an actual person the focus sash isnt supposed to get consumed you keep it.

**Screenshots**
N/A

**Additional context**
I have been through 5 sash's and im tired of it I would like this fixed because I have to buy one everytime and I use it for my team.

**Comment by Mikirae** [comment]
I've mentioned it in tickets, but this is a setting that we have enabled in the config. Please make a suggestion on the suggestions forums if you'd like to see this changed :)
I like to get multiple opinions on the subject.
