### ISSUE TITLE
Smash rank has infinite homes

### ISSUE THREAD

**Issue by EboyZenks** [SmashMC-Development/Bugs-and-Issues#1227]
Have Smash rank and you have infinite homes as a contrast to the promised 18

**Comment by jantjewieger** [comment]
Next time please follow the format provided. However, this is not a bug but intended. They changed it after reset. The issue in this case would be that the info on the rank just needs to be updated

**Comment by Mikirae** [comment]
Correct. I fixed it on the store, thanks for letting me know that was wrong.❤️ No one reported it before now
