### ISSUE TITLE
Balm mushroom still not able to sell

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1228]
**Describe the Bug**
This has been a bug since probably the start of reset. The balm mushrooms are not able to be sold to shopkeepers, despite their own use being that they can be sold to shopkeepers, they don't have any other uses. I think the last github was said it would be fixed, but never did.
*I looked, there has been 3 separate githubs, one done by me*
**To Reproduce**
1. find a balm mushroom
2. try sell them to shopkeeper
3. is unable

**Servers with the Bug**
all

**Expected behavior**
Should be able to sell the balm mushroom for however much it is worth

**Screenshots**

https://user-images.githubusercontent.com/89798207/162994310-f838aaef-99d2-4994-97fd-036276c1da41.mp4

**Additional context**
I love you miki

**Comment by Mikirae** [comment]
FIXED FOR NEXT RESTART THANK YOU LOVE YOU TOO
