### ISSUE TITLE
/ranks does not take money from your balance on survival

### ISSUE THREAD

**Issue by xHudsy** [SmashMC-Development/Bugs-and-Issues#123]
**Describe the Bug**
/ranks does not currently take money from your balance when you purchase a rank
**To Reproduce**
1. Open /ranks
2. Try to purchase a rank above your own one, only works if you have enough money
3. Does not take money from your balance and still gives rewards and title for rank

**Servers with the Bug**
Survival

**Expected behavior**
After purchasing a rank from /ranks you should recieve the rewards and title, with money being taken from your balance

**Screenshots**
https://imgur.com/a/jS2K0YJ - Lord rank visible in image, and can see I checked balance beforehand, rank is supposed to cost 5,000,000.

**Additional context**
N/A

**Comment by jahangir6969** [comment]
Fixed.
