### ISSUE TITLE
/textures doesn't seem to work

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1230]
**Describe the Bug**
On groudon, when you type /textures, the usual message pops up in chat, but you are unable to click it to redirect yourself to the download

**To Reproduce**
1. Go to groudon
2. Type /textures
3. Attempt to click the link 

**Servers with the Bug**
Groudon, possibly all 

**Expected behavior**
You should be redirected to the texture pack download

**Comment by Mikirae** [comment]
So the Hyperlink just isn't clickable? Or the link doesn't work?

**Comment by Dxhcky** [comment]
The hyperlink isn't clickable

**Comment by Mikirae** [comment]
Fixed on restart. Thank you :)
