### ISSUE TITLE
Cap of 2 for gts listings

### ISSUE THREAD

**Issue by Spiritsmashmc** [SmashMC-Development/Bugs-and-Issues#1232]
**Describe the Bug**
A player has complained of an issue about how they only have 2 listings on gts but it wont let them make another listing, they think that this has happened to some of their friends in the past aswell. As shown in the screenshots section it gives an error message in the chat after trying to list something on gts. I have looked at the gts on the respective server (zekrom) to confirm they only have 2 listings, and they do only have 2 listings.

**To Reproduce**
 If u would like to check this for yourself, if this is seen in the near future go onto the zekrom gts, and look through all listing and you should only see 2 listings for the player 'cykne'.

**Servers with the Bug**
The player is on zekrom
**Expected behavior**
I expected them to be able to have the usual 5 listings on the gts.

**Screenshots**
![attachments-46666-glitch-2022-04-17_08 56 25](https://user-images.githubusercontent.com/103875198/163704740-39bf6982-a398-4dfe-8f41-ab0742bfada1.png)

**Additional context**
Other players on zekrom were able to have more than 2 listings.

**Comment by Mikirae** [comment]
I believe that this issue is fixed after restart, and that's the only way that it gets fixed currently. Can you let me know after the server restarts?

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
