### ISSUE TITLE
Dupe Found

### ISSUE THREAD

**Issue by Happi1223** [SmashMC-Development/Bugs-and-Issues#1233]
**Describe the Bug**
Pokemon Dupe In Wz

**To Reproduce**
1. Go Warzone
2. Battle someone
3. Hub outta battle
4. Didnt test but we were in call and assume it was from joining right as they stole
5. Bing Bang Bong You now have a duped mon

**Servers with the Bug**
Ray but probably others

**Expected behavior**
Fix and maybe a key for a reward for finding the bug <3

**Screenshots**
https://prnt.sc/RLNjKRSGywfR
https://prnt.sc/H4JK_95bp1Av

**Additional context**
Probably should be fixed quickly before this gets abused as its kinda hard to track these down

**Comment by Archie4690** [comment]
Issue has been fixed.
