### ISSUE TITLE
i lost my money

### ISSUE THREAD

**Issue by babatunde8258** [SmashMC-Development/Bugs-and-Issues#1234]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Please make a ticket on the Discord so someone can reimburse your loss :)
