### ISSUE TITLE
Sinistea has no easter texture

### ISSUE THREAD

**Issue by borkborkdog** [SmashMC-Development/Bugs-and-Issues#1235]
**Describe the Bug**
Sinistea easter pokemon has texture in the party but when thrown out no texture is there. Yes I have v11 texture pack.

**To Reproduce**
Get the sinistea and throw it out. No texture

**Servers with the Bug**
Kyogre for sure

**Expected behavior**
Testure is there

**Screenshots**
<img width="445" alt="Screen Shot 2022-04-18 at 6 41 59 PM" src="https://user-images.githubusercontent.com/88428417/163888989-edd45975-254a-44f9-8fc7-e1cec9df719a.png">

**Comment by Mikirae** [comment]
Ah, I know the issue. Make a ticket. I need to change the form
