### ISSUE TITLE
/suggestion

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Bugs-and-Issues#1236]
**Describe the Bug**
When running the command /suggestion it tells the player "you do not have permission to run this command

**To Reproduce**
1 Do /suggestion

**Servers with the Bug**
All
**Expected behavior**
 Supposed to guide players into the github for suggestions

**Screenshots**
![image](https://user-images.githubusercontent.com/82547638/164128588-2b0bbb7a-512d-4876-af31-461d355031a3.png)
![image](https://user-images.githubusercontent.com/82547638/164128596-c83091e1-7d98-4b1e-916a-cd23c4301e5c.png)

**Comment by Mikirae** [comment]
Fixed for next restart!!!!!!
