### ISSUE TITLE
Dying sometimes when you go to the dungeon

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1238]
**Describe the Bug**
Started the ice dungeon, and when I tped I fell into the void and died, lost all my items. However when relogging, I got them back. 

**To Reproduce**
1. Attempt Ice dungeon
2. when tp you fall into the void and die

**Servers with the Bug**
Only happened on reshiram, but I think this is on all servers

**Expected behavior**
Should tp you into the dungeon

**Screenshots**

https://user-images.githubusercontent.com/89798207/164342685-e9b3898e-b2ac-465d-99f4-e0d17bb959b5.mp4

**Additional context**
N/A

**Comment by Mikirae** [comment]
I have heard certain reports that this happens a lot when traveling from the Nether/End dimensions, I can't seem to pinpoint anything definitive however, as it happens in the overworld sometimes too

**Comment by WalkAway7** [comment]
Yeah that would make sense, as I teleported from the Nether. I'm not sure how it decides that if it's nether or end it dies, maybe if its at a certain Y level? I was at max height at that time, as I was on the roof of the nether

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
