### ISSUE TITLE
Items in Vault not Stacking

### ISSUE THREAD

**Issue by VampireSquid90** [SmashMC-Development/Bugs-and-Issues#1239]
**Describe the Bug**
When collecting 2 or more of the same items from different sources at different times and trying to stack them in your vault, it does not work and instead the item you are trying to stack returns to the inventory. In order to stack them you have to move the items into your inventory which they also do not stack in and then drop them to the ground for you to collect them altogether in 1 stack. 

**To Reproduce**
1. Put an item such as an ore in the vault
2. Then get the same item from another source 
3. Then try to put those to items in the same slot in your vault and the item just returns to its original slot in the inventory

**Servers with the Bug**
Zekrom

**Expected behavior**
Items to stack together within the vault

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
https://gyazo.com/8eafd6e84c892c5e8dbe35a50a9cb6f5
Can you give me a clip of your issue? It's working fine for me. I also tried exiting out of the vault and adding the PokeBalls, and they still stacked just fine

**Comment by aorosdev** [comment]
Hey @VampireSquid90 - just following up on this, but can you provide us with a clip? It has been a few days, and we'd like to see what's going on from your POV, thank you!

**Comment by VampireSquid90** [comment]
https://medal.tv/games/minecraft/clips/j17D2dekWF0nz/d13370qZjkNQ?invite=cr-MSwzMnosNTI3OTc5OTgs

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by VampireSquid90** [comment]
https://medal.tv/games/minecraft/clips/j17D2dekWF0nz/d13370qZjkNQ?invite=cr-MSwzMnosNTI3OTc5OTgs

As you will see in the clip above it is only when you click and drag the item rather than use shift to quick move it
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
