### ISSUE TITLE
Player don't receive money from voting

### ISSUE THREAD

**Issue by Awlk** [SmashMC-Development/Bugs-and-Issues#124]
**Describe the Bug**
Players who have been voting did not receive any money reward (should be 1000) they have only received the key. 

**To Reproduce**
whenever you vote for the server you do not receive the money

**Servers with the Bug**
Survival

**Expected behavior**
players should be able to receive the said money amount from voting 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Awlk** [comment]
@jahangir6969

**Comment by jahangir6969** [comment]
Fixed
