### ISSUE TITLE
Armor in warzone

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#1240]
**Describe the Bug**
You shouldn’t be able to wear any armor in warzone.
**To Reproduce**
1. Go to warzone with armor on
2. Allows you in warzone

**Servers with the Bug**
Please provide a list of which servers have this bug.
All
**Expected behavior**
Warzone shouldn’t allow armor in warzone either removes it and puts it in the bank or comes up with a message saying it is not allowed.

**Comment by twizzy0** [comment]
why shouldn’t armor be allowed? it really doesn’t give advantage, and that’s going to be annoying as hell having to put my armor back on every time I wanna go back into wz.

**Comment by ajdawg48** [comment]
It never was supposed to be allowed. It’s a bug that you can even bring it in.

**Comment by aorosdev** [comment]
Interesting to hear this. I'll look into it and see what can be done. Thank you for reporting!

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
