### ISSUE TITLE
Cannot queue for Gyms 

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1241]
**Describe the Bug**
You cannot queue for the gyms despite there being a queue button
![image](https://user-images.githubusercontent.com/84816052/164814118-4946a0a0-9cbd-435e-adee-c9bb6a5a9814.png)

**To Reproduce**
1. Any server
2. do /gyms
3. open gyms section
4. go to first gym
5. Try to queue
6. Are not able to queue

**Servers with the Bug**
All

**Expected behavior**
Should be able to queue from the UI

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/164814409-2048d1d8-da2c-4c45-bd19-871c1e33e217.png)

**Additional context**
You can still challenge by going to them but you should be able to queue

**Comment by aorosdev** [comment]
I'm glad to hear that you are still able to challenge the gyms. I'll look into seeing what's causing our GUI bug. Thank you for reporting this to us!

**Comment by Mikirae** [comment]
When did this start happening?

**Comment by M1n0j** [comment]
I dont know, Limooo brought it to my attention, I never noticed as I usually just do /warp gyms to get there

**Comment by Mikirae** [comment]
I asked in the Discord, and it's because they're NPC gyms, and that's just how it does it, so it's not a bug I guess
