### ISSUE TITLE
Gyms have dynamax and not mega band

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1242]
**Describe the Bug**
The Gyms in /gyms have dynamax bands and should be using Mega (The teams have mega pokemon)

**To Reproduce**
1. Go to any server
2. Challenge the Gyms
3. They use Dynamax and not Mega

**Servers with the Bug**
All

**Expected behavior**
Should use Mega as they have Mega Pokemon

**Screenshots**
N/A

**Additional context**
N/A

**Comment by aorosdev** [comment]
Noted, thank you for this M1. I'll take a look & see what can be done!

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
