### ISSUE TITLE
pokestop missing

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1243]
**Describe the Bug**
There is a pokestop missing in spawn at /warp bosstower

**To Reproduce**
1. Go to /warp bosstower
2. see no pokestop there

**Servers with the Bug**
Reshiram

**Expected behavior**
a pokestop there

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/165126015-46213591-2f89-42bd-bad2-1eb95c2b4030.png)

**Additional context**
n/a

**Comment by Superfire96** [comment]
Fixed
