### ISSUE TITLE
Ubers in Elite 4 and Gym battles

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1245]
**Describe the Bug**
You can use ubers in E4 battles and Gym battles

**To Reproduce**
1. Go to any server
2. Challenge E4 or a Gym
3. Have ubers in our team
4. Be able challenge

**Servers with the Bug**
All

**Expected behavior**
Shouldn't be able use ubers

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/165145445-1a43128a-78fd-4a0c-98e3-4a8669ede517.png)

**Additional context**

Should be banned - Rayquaza, Mewtwo, Lugia, Ho-oh, Kyogre, Groudon, Deoxys (Base Form, Attack form, Speed form), Dialga, Palkia, Giratina (Both forms normal and origin), Shaymin-Sky, Arceus, Tornadus-Therian, Reshiram, Zekrom, Landorous (base form), Kyurem-Black, Kyurem-White, Meloetta-Pirouette, Genesect, Xerneas, Yveltal, Zygarde (50% and Complete which is via ability Power Construct), Solgaleo, Lunala, Pheromosa, Magearna, Marshadow, Naganadel, Zacian, Zamazenta, Eternatus, Urshifu-Single-Strike, Spectrier, Calyrex-Ice, Calyrex-Shadow

**Comment by Mikirae** [comment]
This caused me physical, emotional, and spiritual pain. Please tell me I fixed it or I will literally weep

**Comment by Mikirae** [comment]
PLEASE SIR I NEED TO KNOW!!!!!!!!!

**Comment by M1n0j** [comment]
Sorry, but its the same for gyms anyway so you will need to weep.

I will try E4 once someone comes online to help!!!!!

**Comment by Mikirae** [comment]
Okay I changed it again and if this one doesn't work I'm literally going to
shed three tears.

**Comment by M1n0j** [comment]
![image](https://user-images.githubusercontent.com/84816052/166069269-6dd4373d-7c6c-47bd-940e-dca6221f805f.png)
Miki, u don't need a tissue its okay buddy u fixed my issue

**Comment by Mikirae** [comment]
LET'S GOOOOOOOOOOOOOOOOOOOO
