### ISSUE TITLE
2nd Elite 4 doesnt work

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1246]
**Describe the Bug**
2nd Elite 4 doesn't work, it clears the challengers pokemon from their party.

**To Reproduce**
1. Go to Rayquaza or Reshiram
2. Challenge the 2nd Elite 4
3. Have the opponents party clear or will be given another players team

**Servers with the Bug**
Rayquaza and Reshiram

**Expected behavior**
Should let the challenger keep their team

**Screenshots**
https://youtu.be/aHvDZOB4p2A

**Additional context**
N/A

**Comment by Mikirae** [comment]
I changed a setting on Rayquaza. Can you try it and let me know if that fixes the issue?

**Comment by M1n0j** [comment]
Works on Ray did u also change it on Reshiram?

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
