### ISSUE TITLE
Weird egg hatching bug

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1247]
**Describe the Bug**
Hatched a HA smeargle and a non HA cleffa, and in chat it showed HA smeargle hatching twice.

**To Reproduce**
1. Have one HA egg, and one not HA egg
2. they both hatch at the same time, and two HA messages show up

**Servers with the Bug**
Reshiram from what I know

**Expected behavior**
Should only be one HA message

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/165624338-368924a5-924b-4017-ad47-a11dc9605048.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
I'm seeing double hatches with other plugins as well, so I'm wondering if it's something with the newest Egg Event changing. Will look into it and see if there's anything that can be done to fix it. Thanks for letting me know <3

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
