### ISSUE TITLE
Essense for tcg cards

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#1248]
**Describe the Bug**
If you die you lose all your essences that is used to make tcg cards

**To Reproduce**
1. kill a pokemon to get some essences
2. verfied you got some essences
3. suicide somewhere
4. See that your essences is gone

**Servers with the Bug**
tested on kyogre presumed all server

**Expected behavior**
your essences should stay with you like your inventory when you die

**Screenshots**
N/A

**Additional context**
(https://www.youtube.com/watch?v=HCDaqiiOcGs)

**Comment by Superfire96** [comment]
It's a pixelmon bug, nothing that we can do about it sadly
