### ISSUE TITLE
Couldn't get any more skill EXP

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#1249]
I reached lvl 599 and have 2050XP in the breeder skill and usually whenever I hatch an egg I get a message in the chat that I get XP but now I don't get it anymore no matter how many eggs I hatch.

**Comment by Mikirae** [comment]
Well the maximum level should be 250, so I guess the real bug is that you were somehow able to go past that

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
