### ISSUE TITLE
Guy threw a mball at a legendary, ends up catching pokemon standing beneath it

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Bugs-and-Issues#125]
**Describe the Bug**
Watching the video will be the clearest but the guy tried catching a lunala with throwing a masterball and he ends up catching the starmie that was standing way underneath the lunala.

**To Reproduce**
Go to warzone try to catch a flying pokemon (without engaging the flying pokemon) that is flying above another pokemon. If done right the ball catching animation goes trough and when going to the ground it should hit the pokemon on the ground and catch that pokemon. 

**Servers with the Bug**
Rayquaza

**Expected behavior**
catch the flying pokemon

**Screenshots**
https://youtu.be/wST6sXG_2lo

**Comment by Mikirae** [comment]
So we can give him back the Master Ball, but we think that something happened with colliding hitboxes. This seems more like a Pixelmon bug than a Smash bug. He can DM Mikirae#6969 on Discord with his name and server for the Master Ball.
