### ISSUE TITLE
my friend taideteos won a tournament the key didnt work we tried to type /keys but it says no keys and then we voted and still no keys

### ISSUE THREAD

**Issue by Elukkah** [SmashMC-Development/Bugs-and-Issues#1250]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by WalkAway7** [comment]
You need to fill out the proper format, otherwise the person seeing this wont know what the issue is :) ^^

**Comment by Elukkah** [comment]
on kyurem and still crates dont work

**Comment by Mikirae** [comment]
Please make a ticket in order to get help on this. The issue that caused this has been resolved :D
