### ISSUE TITLE
Unable to hatch Hisuian Growlithe

### ISSUE THREAD

**Issue by Awholemess** [SmashMC-Development/Bugs-and-Issues#1251]
**Describe the Bug**
I have an Hisiuan Growlithe breeding with a Ditto, but so far it's only produced Kantonian Growlithe.

**To Reproduce**
1. Add a Ditto and Hisuian Growlithe to a ranch block in the appropriate conditions.
2. Wait for an egg to be produced and take it.
3. Hatch the egg.
4. See Kantonian Growlithe.

**Servers with the Bug**
Rayquaza, unsure if it's occurring on other servers.

**Expected behavior**
I expected to hatch the egg and have it be a Hisuian Growlithe.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
This unfortunately sounds like a Pixelmon bug
