### ISSUE TITLE
/bm moves

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1252]
**Describe the Bug**
/bm poltergeist does NOT work for Alolan Marowak. Poltergeist is a tutor only move in the games, however tutor moves are next to impossible in pixelmon. Since other pokemon can learn the move via /bm , Alolan Marowak should too. 

**To Reproduce**
Run the command /bm poltergeist with an Alolan Marowak in your party
GUI will not allow you to teach the Alolan Marowak the move

**Servers with the Bug**
All

**Expected behavior**
For the Alolan Marowak to learn the move poltergeist from /bm poltergeist

**Screenshots**
![2022-05-02_15 23 48](https://user-images.githubusercontent.com/104792516/166312115-900eeed9-1b4a-4b8c-97d8-f73374b81aa4.png)

**Additional context**
Many staff in the past have said that since it is a tutor move anyway, this does not need to be fixed. However the fact that literally every other pokemon besides Marowak is able to bypass learning via tutor simply shows that the command doesn't recognize the marowak being Alolan. This should be fixed, as it is borderline impossible to get this move elsewhere.

**Comment by Mikirae** [comment]
This might be an issue with forms. I can test later to see if Galar/Alolan mons can't learn the proper moves, as if I had to guess, that'd be the cause

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
