### ISSUE TITLE
One of the descriptions in /poketop is spelt wrong

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1254]
**Describe the Bug**
I think there was a little bit of confusion, but when it describes who comes second, it says "mythic" crate, which doesn't exist. I think it means to say "mystic".

**To Reproduce**
1. do /poketop
2. look over the rewards
3. see the mistake

**Servers with the Bug**
Went and tested on all servers, same issue for every server. (Discovered on reshiram)

**Expected behavior**
Should say "Mystic"

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/166913464-691e3708-7566-45ed-949b-57f465755912.png)

**Additional context**
Sorry for this nitpicking of a github, but I think it might clear up some confusion. Thanks to whoever reads :)

**Comment by Superfire96** [comment]
Fixed
