### ISSUE TITLE
Catching HAs through Raids don't count toward /poketop

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1255]
**Describe the Bug**
Yesterday I caught an HA golett via a raid, and it didn't count toward me catching one on /poketop. This may be because I've already caught one before (maybe a few weeks ago) or that it was via a raid. I thought that it hadn't upadated yet, so I left. I came on today, and it still hasn't counted. 

**To Reproduce**
1. Go do a raid
2. Find HA
3. catch it
4. see that it doesn't count toward poketop

**Servers with the Bug**
Only happened on reshiram, may be on other servers though.

**Expected behavior**
Should count toward /poketop

**Screenshots**
N/A

**Additional context**
Just like to say that poketop is a really good addition, it adds a bit more of a competitive edge to the server, for people who aren't as invested in battling. :)

**Comment by DinglePringleUwU** [comment]
This is also the case on Rayquaza.

**Comment by Mikirae** [comment]
Unfortunately I don't believe the plugin is updated anymore, so there's not much that can be done. I'll look into seeing if anyone is willing to update it

**Comment by WalkAway7** [comment]
Alright, thanks for looking into it :)

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
