### ISSUE TITLE
Breeding is bugged with /skill and /poketop

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1256]
**Describe the Bug**
You can not get any breeding EXP for hatching an egg anymore.
I am at leve 0 with 0 Exp and with 10 hatched eggs. (Tho i only hatched 5)

When hatching an egg, /poketop counts that as two hatched eggs. 
Similar to the announcement bug that is explained in https://github.com/SmashMC-Development/Bugs-and-Issues/issues/1247

**To Reproduce**
1. Look your /poketop breeding score and write it down
2. Hatch a single egg
3. Look again at your /poketop breeding score. It will have raised by 2 instead of 1.

**Servers with the Bug**
All Pixelmon Servers.

**Expected behavior**
Hatched eggs should yield exp again (500 per). 
One hatched egg should count as one hatched egg in the /poketop command (This can be ignored if its not unbalanced to the total score, as everyone would still have the same amount of points)

**Screenshots**
N/A

**Comment by Mikirae** [comment]
Yup, I realized that, and I'm looking for a fix :) Thank you!

**Comment by Mikirae** [comment]
This is fixed for next restart for PokeTop :D
Skills hasn't been updated since the Egg change happened, unfortunately

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
