### ISSUE TITLE
logging in warzone

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1257]
**Describe the Bug**
When someone logs in warzone, while u were in the selection screen, u used to be able not to steal. That is fixed now. However, If someone leaves while in the selection screen u dont get the 2/3 mins of wz time added to ur timer that u should get for beating someone

**To Reproduce**
1. Go to warzone
2. engage someone in wz
3. Other person leaves while in selection screen
4. See no time added to ur timer

**Servers with the Bug**
Is on reshi for sure but probably all

**Expected behavior**
I'd expect 2/3 mins added to my wz timer

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
