### ISSUE TITLE
Body Press move not working as intended

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Bugs-and-Issues#1258]
So I've spoken with one of the mods of the Pixelmon Team, and I asked them that the move Body Press is not working. It's not calculating defense as the damage. I have tested it in a single player world and It ACTUALLY WORKS.

But apparently in the SmashMC server its not working.

I have proof of this not working
This link shows my Avalugg with Max 31 ivs on def and max 252 evs on def against a Jolly Garchomp with max 31 ivs on defense in a SINGLEPLAYER WORLD:
https://youtu.be/KzHZVslE9wk

And this link is the same avalugg against the same Garchomp in the SMASHMC server:
https://youtu.be/7cP3M6VdLyU

As you can see, the damage differs and its not working as intended
I've asked this to them and they said it must a server problem or something. Please look into this, Thank you

**Comment by morrow12** [comment]
Yeah I got told they fixed it but on smash it wasnt working

**Comment by Archie4690** [comment]
@IAmF3rdie This issue should now be solved. I will now be closing this GitHub up! Thank you for reporting this :)
