### ISSUE TITLE
Players bypassing Price Restriction

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#1261]
**Describe the Bug**
Players are bypassing price restrictions on BP and BP Breedable pokemon by putting eggs  instead of pokemon itself.

**Servers with the Bug**
Rayquaza probably all.

**Screenshots**
![Screenshot (95)](https://user-images.githubusercontent.com/25759066/168752611-a3cdb23e-fa20-4e28-b76e-df259ef09ace.png)

![Screenshot (96)](https://user-images.githubusercontent.com/25759066/168752635-7378a3f5-0f84-4446-b6a7-010c0ccb2ccc.png)

**Comment by Mikirae** [comment]
I'll have to take a look in to how that's even possible because this should cover eggs. Thank you!

**Comment by Mikirae** [comment]
I took a look and eggs seem to be fine. It looks like the real issue is that there is no separate price for breedables, so we'll need to do that :)

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
