### ISSUE TITLE
Essence message

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1262]
**Describe the Bug**
in /warp evs if you defeat a pokemon you get two messages saying that you gained 0 essence. You also get essence for the pokemon that you defeat in the wild, which can get annoying imo.

**To Reproduce**
1. go to /warp evs
2. attack any of the ev mons
3. get the messages

**Servers with the Bug**
Network

**Expected behavior**
Probably shouldn't have two of the same message

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/168897582-bd32179d-f8ae-4598-81f5-1668e40da043.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
This is a Pixelmon bug, so we can't really do anything about it unfortunately.
