### ISSUE TITLE
wz bank bug

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1263]
**Describe the Bug**
wz bank glitches when there are a ton of mons in it. usually happens when you are clicking next page on the loser's wz bank and when it does bug out...it becomes empty and the only mons u can steal if from their team. No idea the number of mons to bug it out but it has happened a few times when I wanted to steal a leg that's supposed to be on the last page.

**To Reproduce**
1. Go to wz
2. battle someone who caught a ton of mons
3. win 
4. click next page for their wz bank until it bugs out

**Servers with the Bug**
Kyurem but dunno about others

**Expected behavior**
wz bank not bugging out when I am pressing next page to see the mon i want to steal.

**Comment by Mikirae** [comment]
I have an open ticket on this issue already with the developer. Hopefully it can get fixed soon :)
I'll be closing this as we already have one open on our backend, but thank you for reporting!
