### ISSUE TITLE
lvl 150 martial skill

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1264]
**Describe the Bug**
the skill doesnt show a cooldown after it activates

**To Reproduce**
1. shoot yourself after gettin lvl 150 martial skill
2. see deflect skill activate
3. see no cooldown
4. shoot self again
5. deflect skill doesnt activate
6. ?????

**Servers with the Bug**
kyurem is the only server with lvl 150 martial skill but you should test others

**Expected behavior**
show the cooldown if there is a cooldown

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
