### ISSUE TITLE
Hatching Hidden Ability Eggs are doubling and flooding chat

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Bugs-and-Issues#1265]
Like the title says, hatching a single HA pokemon would double text in chat. So basically if you hatch one HA egg, you would get twice the message, and when you hatched 5 HA eggs, you will get 10 messages that you hatched an HA egg. Its getting really annoying tbh.

I'm not sure if this is happening in other servers, but Reshiram server is basically having this problem

**Comment by Mikirae** [comment]
Unfortunately this can only be fixed when the plugin is updated, and it's an official Pixelmon Sidemod, so I'm not sure when that will be happening. I believe I've already opened a ticket with the issue, so I'll close this one. Thank you for reporting :)
