### ISSUE TITLE
i can't throw pokeballs out my hotbar

### ISSUE THREAD

**Issue by RightMarch0072** [SmashMC-Development/Bugs-and-Issues#1267]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jantjewieger** [comment]
March, can u please follow the format provided

**Comment by Archie4690** [comment]
@RightMarch0072 Please follow the format provided. If is not answered in the near future this ticket will be closed

**Comment by Archie4690** [comment]
Purging all old GitHub Bug-Reports, Thank you for your contributions!
