### ISSUE TITLE
Warzone stalling

### ISSUE THREAD

**Issue by PacificStorm619** [SmashMC-Development/Bugs-and-Issues#1268]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
when in a battle, on final pokemon they dont choose it and the battle wont force the choice, so they can stall for an infinate amount of time

**Comment by Mikirae** [comment]
No information provided.
