### ISSUE TITLE
GTS Bug

### ISSUE THREAD

**Issue by SushiDB** [SmashMC-Development/Bugs-and-Issues#1269]
**Describe the Bug**
I bought a Gible for 10000 and I didn't show up in my inventory, I waited for a while and even disconnect and reconnect again to see if it show up but no Gible was in my inventory. I bought it because its a Enormous size too.
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Rayquaza server
**Expected behavior**
If unable to get my the Gible please return 10,000 back or more for compensation like 10x time (hehehe).
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
My name in the server is SushiDollarBill

**Comment by oLimooo** [comment]
Should be in your gts bank. /gts bank

**Comment by Archie4690** [comment]
Purging all old GitHub Suggestions, Thank you for your contributions!
