### ISSUE TITLE
/Home

### ISSUE THREAD

**Issue by SinBoiBoi** [SmashMC-Development/Bugs-and-Issues#127]
/Home PVP Bug
This bug allows you to /home while taking damage in the PVP and resource world

The easiest way to reproduce this is to just swim in lava and do /home

Survival That I know of

Typically you can not /home while taking damage or while in combat and it will take 3 seconds to tp.

**Comment by jahangir6969** [comment]
When you talking about Damage. Do you mean Player hitting you? Or mobs/fall damage and etc?

**Comment by jahangir6969** [comment]
No reply. Closing ticket down. If I get an answer for the above. I will reopen.
