### ISSUE TITLE
Modded Ores Are Dropping Incorrect Items

### ISSUE THREAD

**Issue by Sensouu** [SmashMC-Development/Bugs-and-Issues#1272]
**Describe the Bug**
This bug leads the ores to be jumped with other modded blocks, sometimes similar, IE, evo stone shards to other evo stone shards. With more experimenting and testing other blocks I could make a list, but I don't think this is intentional, lol

**To Reproduce**
Find any modded ore
Break it 
Incorrect item drop? 

**Servers with the Bug**
I play on Reshiram, not to say this couldnt exist on others 

**Expected behavior**
The ore to match the drop it is based off of

**Screenshots**
https://youtu.be/GLEIO2VexlI Give it a second to upload, but heres Firestone ore, some sort of... claw block? and some silver ore? Unshown would be water stone turning into moonstone, and dawn(?) stones turning into thunderstones. Could be a pixelmon issue, if it is I'm sorry. 

**Additional context**
Pretty silly, is it not?

**Comment by Sensouu** [comment]
extra: Exp shares are not sharing the exp ':)... I found some in a desert temple and they dont seem to be working right

**Comment by Mikirae** [comment]
Please make sure that you are on 9.0.2 :)

**Comment by Archie4690** [comment]
@Sensouu Was this resolved?

**Comment by Mikirae** [comment]
No further information gathered. Closing
