### ISSUE TITLE
Ranked Player Home Limit

### ISSUE THREAD

**Issue by BrunchBee** [SmashMC-Development/Bugs-and-Issues#1273]
**Describe the Bug**
Players with donor ranks are unable to set more than the default 3 homes. The except is Smash players, who are still able to set an unlimited number of homes. 

**To Reproduce**
1. As a ranked player, attempt to set 4 homes. 

**Servers with the Bug**
Kyogre, probably others

**Expected behavior**
I expected to be able to set 12 or so homes as a Legend player.

**Screenshots**
![03d2c68f0c8ba8cab23d7e425dea4d90](https://user-images.githubusercontent.com/106752950/173211674-1124a477-97d0-488c-8516-e1a29091ef3e.png)

![4b4f42e6820e2a80c18285aa3652631a](https://user-images.githubusercontent.com/106752950/173211676-b16d3a54-09a3-4d5c-9021-9e602acaa5ed.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
