### ISSUE TITLE
When I use my vote crate key litterally I'm an explosion of rare items

### ISSUE THREAD

**Issue by TheHumbleJames** [SmashMC-Development/Bugs-and-Issues#1274]
Glitch report, vote crate usage leads me to explode in a bunch of rare items, new players are standing around to collect them, I've seen everything from master balls, to the legendary bird orbs, to other things.

**Comment by TheHumbleJames** [comment]
This occurs on Reshiram.

**Comment by Mikirae** [comment]
This has been fixed. Thank you!
