### ISSUE TITLE
Opening the chat while in battle

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1275]
**Describe the Bug**
When you open the chat while you are in battle it automatically enters a "t", which is very annoying

**To Reproduce**
1. Go into a battle
2. press "t" to open chat
3. See chat

**Servers with the Bug**
At least Kyogre

**Expected behavior**
Empty chat to write into it without having to delete the t everytime

**Comment by ColonCrusader** [comment]
i have my chat bound to "q" and i can't open chat at all unless i press the / key

**Comment by Mikirae** [comment]
This is a Pixelmon bug, unfortunately :(
