### ISSUE TITLE
Mons not spawning regularly in ocean, instead spawning normal mob pool.

### ISSUE THREAD

**Issue by TheHumbleJames** [SmashMC-Development/Bugs-and-Issues#1276]
**Describe the Bug**
The water spawns on Reshiram are broken

**To Reproduce**
1. Go to the ocean.
2.  It's only spawning fish, squids and dolphins
3. even after murdering everything nothing

**Servers with the Bug**
At least reshiram

**Expected behavior**
Pokemon in the ocean

**Comment by Archie4690** [comment]
Hey @TheHumbleJames, I believe this issue has been resolved. Let me know if things are all good for you

**Comment by Mikirae** [comment]
This has been resolved. Thank you for reporting!
