### ISSUE TITLE
Strongholds Potentially not Spawning

### ISSUE THREAD

**Issue by ManthisYT** [SmashMC-Development/Bugs-and-Issues#1277]
I have looked for strongholds in the Groudon Server, and both times the eyes of ender lead straight down I found nothing in the area when there should have been a stronghold. I'm not sure if its bugged or if I just got unlucky with the generation but I feel like its most likely that stronghold spawns are bugged

**Comment by ManthisYT** [comment]
To clarify I went to two different locations with the eyes on opposite sides of the world

**Comment by manlybro2002** [comment]
same problem on kyurem, already done rtp about 7 times now to find a stronghold and all of em lead to a chunk with no strongholds

**Comment by ColonCrusader** [comment]
so i don't know if this is or isn't a issue because i wasn't the one who found it but on reshiram we where able to find the stronghold

**Comment by Superfire96** [comment]
They are indeed not spawning, but a warp for the end was added
