### ISSUE TITLE
Vote Crate Depth Strider III is bugged

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1279]
**Describe the Bug**
The Enchantment Book "Depth Strider III" from the vote crate is bugged. After obtaining it, it is displayed as a blank enchanted book (See SS)

**To Reproduce**
1. Get vote keys
2. Open until you get the book
3. Look at the book

**Servers with the Bug**
At least Kyogre

**Expected behavior**
Receiving a working book.

**Screenshots**
![2022-06-12_10 41 51](https://user-images.githubusercontent.com/94211853/173225006-a7db4e6b-6337-48d8-9c3d-1c3d0f92b3fc.png)

**Additional context**
This is not a visual glitch. I can not use it with the anvil.

**Comment by Superfire96** [comment]
Fixed
