### ISSUE TITLE
Valueable items for Shopkeepers are not sellable

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1280]
**Describe the Bug**
Items like Shoal Shell are not sellable. Likely goes for all the new sellable items.

**To Reproduce**
1. Take Shoal Shell
2. Go to the Mart
3. You can not sell it

**Servers with the Bug**
At least Kyogre

**Expected behavior**
Being able to sell it

**Additional context**
There is a small array of newly obtainable sellable items like Silver Leaf, Relic Silver ect.

**Comment by Mikirae** [comment]
Added Relic Copper, Relic Silver, Relic Gold, Shoal Salt, Shoal Shell, and Silver Leaf as sellable items for the next restart :)
