### ISSUE TITLE
You can not fish.

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1281]
**Describe the Bug**
Using a pixelmon fishing rod as "good rod" does not work

**To Reproduce**
1. Take a good rod
2. Try fishing in water
3. Nothing happens

**Servers with the Bug**
At least kyogre.

**Expected behavior**
Being able to fish.

**Additional context**
Using the minecraft fishing rod does work tho.

Edit: This does not work on Singleplayer either, so likely a pixelmon bug.

**Comment by Mikirae** [comment]
This is a Pixelmon bug, unfortunately. Thank you for reporting! :)
