### ISSUE TITLE
Bosstower

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1282]
**Describe the Bug**
Bosstower has no elevators and does not spawn any bosses.

**To Reproduce**
1. Go to /warp bosstower
2. No bosses spawn

**Servers with the Bug**
At least Kyogre

**Expected behavior**
Being able to fight bosses there and possibly climb it

**Comment by Dxhcky** [comment]
there is currently an issue with spawners, so that is why nothing is spawning, but it is most likely being worked on currently.

**Comment by DinglePringleUwU** [comment]
This has been fixed. There are both Bosses and Elevators available now.
I do suggest changing the Lycanroc spawns tho, as they drop a special Z-Crystal that sells for 2.500 coins. <- (No idea if this is still the case tho)

**Comment by Superfire96** [comment]
Fixed and Lycanrock was changed
