### ISSUE TITLE
Raid dens are destroyable

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1283]
**Describe the Bug**
You can destroy raid dens, even if the place has claimprotection and you are not trusted.

**To Reproduce**
1. Go to raid den
2. Claim the place
3. Let another player (Not trusted in the claim) destroy the raid den with a pickaxe

**Servers with the Bug**
At least Kyogre

**Expected behavior**
Not being able to destroy raid dens

**Comment by Superfire96** [comment]
Fixed from next restart
