### ISSUE TITLE
Move relearner in the mart is not working

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1284]
**Describe the Bug**
The NPC "Move relearner" inside the mart in the /spawn does not work

**To Reproduce**
1. Go to /warp mart
2. Use the Move relearner
3. Does not teach any moves

**Servers with the Bug**
At least Kyogre

**Expected behavior**
Being able to use it to relearn moves

**Comment by Superfire96** [comment]
Not an issue on our end. Waiting for the next pixelmon update for any news about them
