### ISSUE TITLE
cannot /warp crates on groudon

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1285]
**Describe the Bug**
If you attempt to /warp crates on groudon, you get an error saying it is unsafe due to lava

**To Reproduce**
1. Go to groudon
2. Type /warp crates
3. See error

**Servers with the Bug**
Groudon, could be others 

**Expected behavior**
teleport to /warp crates 

**Screenshots**
![image](https://user-images.githubusercontent.com/86555718/173227219-1b801173-c99d-4eaf-beec-7690dc597c68.png)

**Comment by Mikirae** [comment]
Sorry for the late reply, is this still an issue?

**Comment by Dxhcky** [comment]
I believe so but I can check again later today

**Comment by Dxhcky** [comment]
It seems to work now

**Comment by Superfire96** [comment]
This was fixed quite some time ago, forgot to close this <3
