### ISSUE TITLE
Can use /nick but no color codes/Symbols

### ISSUE THREAD

**Issue by Hiepske** [SmashMC-Development/Bugs-and-Issues#1286]
**Describe the Bug**
/nick is working i can change my name but when i try to use it with color codes it says i cant use this nickname

**To Reproduce**
1. Go to /nick
2. Type the name u want (With color codes and symbols)
3. Press enter

**Servers with the Bug**
Groudon

**Expected behavior**
expected to happen is that i could use the name i had with obfuscated, underline, bold and with the colors i want

**Screenshots**
![Base Profile Screenshot 2022 06 12 - 11 53 42 81 (2)](https://user-images.githubusercontent.com/107347455/173227754-69040f41-5be5-4df7-b16b-f528bdcaafc0.png)
![Base Profile Screenshot 2022 06 12 - 11 53 50 90 (2)](https://user-images.githubusercontent.com/107347455/173227755-0f209028-bceb-4fdc-870e-fc6afbfc13ef.png)

**Comment by Superfire96** [comment]
You can't use obfuscated in your nickname, that's the issue there

**Comment by Mikirae** [comment]
As super said, the issue is in the obfuscated part :)
