### ISSUE TITLE
sheep spawning in ultra space

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1287]
**Describe the Bug**
Sheep are spawning in ultra space on groudon, dont think they should be there 

**To Reproduce**
1. Go to ultra space
2. See error

**Servers with the Bug**
Groudon

**Expected behavior**
No sheep

**Screenshots**
![image](https://user-images.githubusercontent.com/86555718/173237580-ba78aa29-1624-4204-b6f7-70701f95598a.png)

**Comment by Dxhcky** [comment]
also squids, all non hostile mobs seem to spawn

**Comment by Mikirae** [comment]
This should be fixed :) Thank you for reporting!
