### ISSUE TITLE
Ranks commands

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Bugs-and-Issues#1288]
**Describe the Bug**
As we all know some command plug-ins aren't updated atm. Will rank players get new commands in place for the old command that isn't updated? 

**To Reproduce**
Commands such as /vaults isn't working or /resetevs (for smash ranks)

**Servers with the Bug**
All

**Expected behavior**
When doing /vaults, it opens a menu where ranks players have extra storage however not in this reset because of the update

**Comment by oLimooo** [comment]
I been seeing a lot of trackers being respond yet this one as been skipped. Is there any reason for that? I just want to know about this situation

**Comment by Mikirae** [comment]
Swear I commented on this somewhere, but yes, they'll be added back as soon as things get updated :)
Not necessarily a bug though, so I'll be closing. Hopefully they get done soon 🙏
