### ISSUE TITLE
get rid of fish spawns

### ISSUE THREAD

**Issue by Lupped** [SmashMC-Development/Bugs-and-Issues#1289]
in the ocean the fish spawns take up all of the available spawns, so there ends up being almost zero pokemon and only normal fish

**Comment by Lupped** [comment]
![Screenshot 2022-06-12 132603](https://user-images.githubusercontent.com/107329902/173245444-3c5ccb35-8682-4312-9072-3badf7e2c56d.png)
i feel like this image sums up the issue

**Comment by Mikirae** [comment]
This should be fixed :)
