### ISSUE TITLE
Shrines not resetting

### ISSUE THREAD

**Issue by Mizugorou49** [SmashMC-Development/Bugs-and-Issues#129]
**Describe the Bug**
The shrines do not reset after use and still use up the amount of money needed

**To Reproduce**
1. Use a shrine
2. Go to reset it
3. Hit confirm and itll use money but not reset

**Servers with the Bug**
Giratina, dont have money to test on other servers

**Expected behavior**
The money will be consumed while also resetting the shrine

**Screenshots**
![2021-05-20_01 11 20](https://user-images.githubusercontent.com/83819638/118922862-ba375f00-b908-11eb-8779-45f0f8f04111.png)

**Additional context**
me and Meliodas on Giratina both lost a large sum of money trying to use the ilex shrine at /warp shrines

**Comment by HackuJacku** [comment]
Fixed from next restart.
