### ISSUE TITLE
A List of bugs that I encountered whilst playing during the new reset

### ISSUE THREAD

**Issue by JohannErasure** [SmashMC-Development/Bugs-and-Issues#1290]
**Describe the Bug**
Although you might know a lot of these already ill list them anyways
1. Spawners not spawning at warp evs/training
2. Game was extremely laggy
3. Some pokemon were spawning at weird times. for example ralts would spawn throughout the day when its only supposed to be dusk and dawn
4. my rank perks did not work (keys) and my when I attempted to get vote crates I didn't get any of my rewards
5. move relearner just, does not work
6. Gts and STS not working. 
**To Reproduce**
These should be self explanatory
**Servers with the Bug**
kyogre
**Expected behavior**
1. spawners so I can actually grind my mon up
2. a smooth game
3. for them to spawn at the same times as the wiki 
4. my rank gives me what I should get as well as the vote crates
5. move relearner lets you relearn moves
6. you can use GTS and STS

**Comment by BrunchBee** [comment]
Gts and sts don't work because the plugin has not been updated I believe

**Comment by JohannErasure** [comment]
are they going to be updated? there is no way to generate money other than selling random stuff to the pokemart, which is a horrible way of generating money and econ will never be good

**Comment by ColonCrusader** [comment]
i know that the move relearner thing isn't anything they can do something about because that's a issue with the pixelmon mod its self for the version we are playing

**Comment by Superfire96** [comment]
Spawners are a problem on the pixelmon end, we can only do little about the lag, move relearner it's a problem on the pixelmon end, gts hasn't been updated to 1.16 yet. For the vote crates if you don't receive them when voting open a ticket and i'll be happy to help.
