### ISSUE TITLE
EV training bugs

### ISSUE THREAD

**Issue by Steve1231234** [SmashMC-Development/Bugs-and-Issues#1291]
**Describe the Bug**
When using a power weight, I get HP and Attack EVs when at the HP trainer. The Sp. Def trainer also was giving me random EV

**To Reproduce**
Put a power weight on a Pokémon and see EVs. 

**Servers with the Bug**
Groudon

**Expected behavior**
Only HP EVs gained

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
I believe this is unfortunately a Pixelmon bug and we can't fix it :( Thank you for reporting!
