### ISSUE TITLE
Galaxy purple block glitch same with iron shovel

### ISSUE THREAD

**Issue by DrSlapnut** [SmashMC-Development/Bugs-and-Issues#1292]
**Describe the Bug**
Galaxy look normal thrown out of pokeball but in Party its purple and black block also same with the iron shovel

**Servers with the Bug**
Kyogre

**Expected behavior**
Don't really understand this one

**Screenshots**

![2022-06-12_14 32 48](https://user-images.githubusercontent.com/107368548/173250482-bdd38e87-bbe0-48f7-aedc-0b0e783aa9e3.png)
![2022-06-12_14 42 09](https://user-images.githubusercontent.com/107368548/173250493-27daf722-c8fb-4853-88d7-f5ee6b9e42cd.png)

Sorry if SS dont work this is first time working

**Comment by DrSlapnut** [comment]
also show in the hotbar the purple block glitch and it shows im holding a iron shovel

**Comment by DrSlapnut** [comment]
![2022-06-12_14 47 45](https://user-images.githubusercontent.com/107368548/173250628-8d90bd52-bb94-49b3-82f6-92f08990e6a6.png)

Also when i throw the galaxy out my hotbar gets small and goes to like the middle left of my screen as you can see in SS above (only sometimes tho)

**Comment by Superfire96** [comment]
Hey DrSlapnut, you need to update the texturepack. Here's the link: https://download.smashmc.co/SmashTexturePackV12.zip
Or you can just find it on our discord
