### ISSUE TITLE
Vote Links

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1293]
**Describe the Bug**
Voting links 2 and 5 are the same. (see SS)

**To Reproduce**
1. Hop on any server
2. Do /vote
3. Check out the second and the fifth link.

**Servers with the Bug**
All Pixelmon Servers

**Expected behavior**
I don't know, but i think there is a link missing as it states that you can vote on one link after voting on the respective five links.

**Screenshots**
![2022-06-13_07 52 06](https://user-images.githubusercontent.com/94211853/173304878-c88bc74e-e607-4860-892b-be7870a3dbbb.png)
See the red dots for the said links.

**Comment by Mikirae** [comment]
This should be fixed now. Thank you for reporting! :)
