### ISSUE TITLE
Pokeloot not rewarding the correct items

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#1295]
**Describe the Bug**
A pokeloot coming from a pokeball did not reward what was shown in chat.

**To Reproduce**
1. Go to any poke loot
2. Right Click on the poke loot
3. Compare the items you obtain 
4. I am assuming this is only related to specific items in the loot pool not all of them

**Servers with the Bug**
Currently only see this issue on rayquaza

**Expected behavior**
Poke loot should be rewarding the correct items

**Screenshots**
Picture indicating a flying gem was found
![2022-06-13_12 26 27](https://user-images.githubusercontent.com/85075804/173362738-061395b6-13ee-4310-bc22-051f23a8ce9f.png)

Picture indicating no flying gem is in the inventory and claims a dark gem was rewarded instead
![2022-06-13_12 26 39](https://user-images.githubusercontent.com/85075804/173362947-4a1a2a07-083a-4b2b-91e8-b39dd93b095c.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by toofuriouz** [comment]
The User that experienced this issue suggested that it may have something to do with him already having a dark gem. It may be the reason why pokeloot is not rewarding properly

**Comment by Superfire96** [comment]
I believe that could have been just a visual bug on your end. Are you on 9.0.2?

**Comment by SimaoAntunes26** [comment]
No it was not, I was in 9.0.2. maybe I did not understand but why would you think that I'm not in 9.0.2/end bug?

**Comment by Superfire96** [comment]
Because if you're on an older version, the item displayed changes

**Comment by Mikirae** [comment]
I believe all instances of this have been due to mods on the client interfering with the item IDs (such as Biomes O Plenty), or being on an earlier Pixelmon version

**Comment by SimaoAntunes26** [comment]
> I believe all instances of this have been due to mods on the client interfering with the item IDs (such as Biomes O Plenty), or being on an earlier Pixelmon version

I don't know, I just installed the modpack on technic, but it keeps happening. I understood that, at least for me, it just happens with gems

**Comment by Mikirae** [comment]
That's really weird. And all other items in the game are fine?
If I had to take a guess, all of your items are shifting by one item ID, so
things like Ability Capsules would say Ability Patches
