### ISSUE TITLE
Breeding

### ISSUE THREAD

**Issue by ColonCrusader** [SmashMC-Development/Bugs-and-Issues#1296]
So there was 2 issues i wanted to address here, one more important than the other, but it seems that you have to be in the  same dimension as the pokemon breeder, as i went to ultra space for a hour with pokemon in a "madly in love with each other" on the breeder, and they hadn't advanced in breeding, and also when you claim a egg from a breeder the breeder still appears like it has an egg, but when you click on it and exit again it resets to normal

this is on reshiram, not sure about other servers

**Comment by Mikirae** [comment]
That would be a Pixelmon bug, unfortunately. Just to confirm before I make a ticket with Pixelmon, if you're in the same dimension but not at the ranch block, it progresses just fine?

**Comment by Archie4690** [comment]
@ColonCrusader The above, if you could.

**Comment by ColonCrusader** [comment]
Im sorry for not responding, i didnt see any notifications, but yes if they are not loaded they will continue in breeding stage, but only if you are in ultra space. this seems to be fixed for me as of now, but i know there are some people on reshiram experiencing abnormally long breeding times

**Comment by jantjewieger** [comment]
Closing this up as with the newest update breeding was completely redone
