### ISSUE TITLE
Main issues

### ISSUE THREAD

**Issue by IsThief** [SmashMC-Development/Bugs-and-Issues#1297]
Can you guys fix the following as soon as possible as i think these are the worst problems

main issues are: lag, spawners, raids and breeding

Ty :D

**Comment by IsThief** [comment]
Ultra space is also completely broken

**Comment by Mikirae** [comment]
In the future, please follow the actual bug report format so that it can be properly handled. We are working on fixes for lag, everything else is a Pixelmon bug.
