### ISSUE TITLE
Smash Rank Issues

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#1298]
**Describe the Bug**
These are some of the issues, I have found with Smash Rank :
1. /breed not working
2. /vaults not working
3. /textcolor not working
4. /eggsteps not working
5. /repair is not working on all the items it use to
6. /resetevs not working

**Servers with the Bug**
Rayquaza probably All.

**Additional context**
Thought I should address something other than the main issues.

**Comment by oLimooo** [comment]
/breed does work just disabled atm because there was no cooldown. 

/pokecolor doesn’t work also

**Comment by Mikirae** [comment]
/breed should be working now
Vaults are being updated
Textcolor requires us to get a plugin, so for now it is simply a red color
Looks like you have perms for Eggsteps? Let me know if it's still not working
Repair is being looked into
ResetEVs is also a plugin thing, but EVs are a bit broken atm :(

**Comment by WalkAway7** [comment]
is it that the plugin for the above features aren't updated?

**Comment by Mikirae** [comment]
Yeah, we'll basically need to get new ones entirely.

**Comment by oLimooo** [comment]
okay thanks! Also /kit scarf used to be for smash, is that not a thing anymore?

**Comment by Mikirae** [comment]
They don't even seem to be in the game :(

**Comment by oLimooo** [comment]
That's unfortunate. Sorry but I have one more question. When running /breed or /hatch we need to include our name into the command. Is there a way to remove that? I did /breed without my name and it reset my cooldown and didn't give me an egg.

**Comment by Mikirae** [comment]
I tried to make something like that, and it ended up bypassing the cooldown
even though it would say that it had a cooldown. Tried for like an hour on
that lmfao

**Comment by Superfire96** [comment]
Were fixed long time ago, closing old trackers.
