### ISSUE TITLE
Mon won't heal

### ISSUE THREAD

**Issue by DrSlapnut** [SmashMC-Development/Bugs-and-Issues#1300]
**Describe the Bug**
My Regice won't heal even after /pokeheal and his stats show 2816 HP

**To Reproduce**
not sure this part

**Servers with the Bug**
Kyogre

**Expected behavior**
Went to heal and he didn't heal

**Screenshots**
I have a video of it 

https://user-images.githubusercontent.com/107368548/173464906-b93075e4-39c5-4332-88dc-f55bfd707245.MOV

**Comment by DrSlapnut** [comment]
![image](https://user-images.githubusercontent.com/107368548/173678546-8cf4860e-c77a-4942-96db-e63d36a430e3.jpeg)

just found this one today but the Sp attack is glitched

**Comment by DrSlapnut** [comment]
![image](https://user-images.githubusercontent.com/107368548/173678833-539eaa9d-96fb-428d-8737-db61bca61747.jpeg)


it leveled up by one level and now it's -31328 Sp Attack

**Comment by Mikirae** [comment]
This is a Pixelmon bug, but if you open a ticket, someone can fix it for you. Thank you for reporting! :)
