### ISSUE TITLE
Shop missing silver Ore

### ISSUE THREAD

**Issue by OverDr1v3** [SmashMC-Development/Bugs-and-Issues#1301]
Both phyiscal mart and /Guishop are missing silver ore/ingots

**Comment by OverDr1v3** [comment]
When flying thru an unloaded chunk, you are unable to fly upwards afterwards. Really messes with traveling in the end

**Comment by Superfire96** [comment]
Ores are not sold in the shops, but i've added the Silver ingots, both to the shopkeeper and /shop
