### ISSUE TITLE
Air should not be in the drop pool

### ISSUE THREAD

**Issue by TheHumbleJames** [SmashMC-Development/Bugs-and-Issues#1303]
**Describe the Bug**
When ever getting loot from anything there is a chance that air is a drop. Whether that be killing a pokemon, picking up loot from a poke chest, or even fighting a raid

**To Reproduce**
1. Kill mon or pick up from loot chest
2. Air is in drop list
3. See error

**Servers with the Bug**
At least reshiram, but probably is occurring on others

**Expected behavior**
Air should not be a droppable item. It's almost like something is being removed from the lootpool.

**Screenshots**
![2022-06-14_20 38 44](https://user-images.githubusercontent.com/93023499/173732489-1114e16f-9997-4a0d-b1b5-e31cfa71706d.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
I believe this is now fixed :) Thank you for reporting!
