### ISSUE TITLE
Can't type in chat while in battle

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Bugs-and-Issues#1304]
Like the title says, we can't type anything if we are in battle. This will cause a lot of problems, such as no communication when you are stuck, and cant even do /endbattle to get unstuck

This is a MAJOR problem for PvP as well as you can just get stuck in wz, and cant even say it

**Comment by Mikirae** [comment]
This is a Pixelmon bug that we are unable to fix unfortunately :( Thank you for reporting though!
