### ISSUE TITLE
some mons dont evo

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1305]
**Describe the Bug**
Ive noticed that pokemon that need to know a move to evolve, wont evolve even if they know the move

**To Reproduce**
1. Get a mon like yanma that needs to know ancient power to evolve
2.lvl it up
3. See error

**Servers with the Bug**
kyurem, might be others

**Expected behavior**
pokemon evo

**Comment by Mikirae** [comment]
I checked the Pixelmon bug tracker and it looks like that's a known issue there. Thank you for reporting!
