### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1306]
**Describe the Bug**
I keep crashing sometimes when I put a pokemon in the PC

**To Reproduce**
1. put pokemon in PC'
2. See error

**Servers with the Bug**
kyurem, might be others

**Expected behavior**
stop crashing

**Additional context**
Dunno why, since all i have been doing is evolving pokemon to dex

**Comment by manlybro2002** [comment]
[crash-2022-06-15_09.50.31-client.txt](https://github.com/SmashMC-Development/Bugs-and-Issues/files/8907687/crash-2022-06-15_09.50.31-client.txt)

**Comment by Mikirae** [comment]
I believe I saw someone say that they got a crash like this when their Pokemon had glitched EVs and they tried putting it in their PC

**Comment by jantjewieger** [comment]
This was a pixelmon issue with either glitched evs or with pokerus. The glitched evs has been resolved, but for pokerus im not too sure if it has been fixed. We unfortunately cannot fix this so closing this up
