### ISSUE TITLE
Colours dont appear when using /pokecolour

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1307]
**Describe the Bug**
Colours dont appear on the pokemon when using /pokecolour and the colour codes.
**To Reproduce**
1. Use /pokecolour using the colour codes
2. Nick will change without colours

**Servers with the Bug**
Tested on Zekrom but probably all

**Expected behavior**
Should change the colour

**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This is a Pixelmon bug and I've already reported it!!!!!!!!!!!!
