### ISSUE TITLE
Grass/Apricorns dont grow in Ultra Space

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1308]
**Describe the Bug**
Grass and Apricorns do not spread/grow in ultra space

**To Reproduce**
1. Go to Ultra Space
2. Try get grass to spread to nearby dirt
3. will not spread

**Servers with the Bug**
Seen on Zekrom but probably all

**Expected behavior**
Should Spread

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Try typing /physics enable there. If it's not that, check random tick speed. If it's not *that*, then it's Pixelmon bug

**Comment by Mikirae** [comment]
WAS THIS EVER FIXED?????? I think I fixed it

**Comment by M1n0j** [comment]
Ummmm
Idk 
I'll ask around

**Comment by M1n0j** [comment]
I didnt see ur first message :P

**Comment by Mikirae** [comment]
You are bad and smelly

**Comment by Superfire96** [comment]
Was fixed long time ago, closing old trackers.?????
