### ISSUE TITLE
Loosing reputation after a /endbattle.

### ISSUE THREAD

**Issue by Octo6155** [SmashMC-Development/Bugs-and-Issues#1309]
**When a player is /endbattle ed the player with the higher rep would loose reputation and the player with the least rep will gain rep**
please fix this ASAP :)

**Comment by Mikirae** [comment]
Warzone was updated recently. Is this still an issue?

**Comment by Johann12345555** [comment]
> Warzone was updated recently. Is this still an issue?

I believe it still is an issue, I think 4 days ago I had to get my battle ended by a helper in warzone and I'd lose rep because of the "Tie" I've seen a player lose 40 rep to this before aswell because they were trying to retight someone and the battle kept ending randomly

**Comment by Johann12345555** [comment]
Update
this should be fixed it happened to me today and I didnt lose any rep

**Comment by Mikirae** [comment]
Forgot to come back to this, but this is fixed yeah. Thank you for reporting and helping :D
