### ISSUE TITLE
Vaults can be opened in warzone

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#131]
**Describe the Bug**
You can open your vaults with /vaults in /Warp warzone

**To Reproduce**
1. Go to /Warp warzone.
2. Run /vaults.
3. Select a vault.
4. Take stuff out of the vault (Could be banned items).

**Servers with the Bug**
All

**Expected behavior**
Disable the permission to use /vaults in warzone.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Fixed on all Warzones
