### ISSUE TITLE
/unbreedable command does not work

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1310]
**Describe the Bug**
/unbreedable set (slot) does not, players do not have permissions to run the command

**To Reproduce**
Do /unbreedable set (slot)

**Servers with the Bug**
ALL

**Expected behavior**
to make the pokemon unbreedable

**Screenshots**
![image](https://user-images.githubusercontent.com/104792516/173975777-3c9d3efa-f57c-423d-9c64-fbac4620eac4.png)

**Additional context**
miki made me cry again

**Comment by Mikirae** [comment]
Just stop crying big baby LLLLLLLLLLLL

**Comment by Mikirae** [comment]
You'll have perms to /unbreed after next restart!!!!!
