### ISSUE TITLE
Cannot check IVs on eggs

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1311]
**Describe the Bug**
When running /ivs (slot) on an egg, it does not show IVs. This never used to be the case

**To Reproduce**
Run /ivs on an egg

**Servers with the Bug**
ALL

**Expected behavior**
For the command to show IVs of the egg

**Screenshots**
![2022-06-15_22 28 02](https://user-images.githubusercontent.com/104792516/173978282-7ad8479b-cfa0-432d-b759-9b0ba7655011.png)

**Additional context**
Not sure if this is pixelmon related rather than server, but thought I'd report anyway

**Comment by Mikirae** [comment]
This seems to be a Pixelmon related thing. Might have to get it fixed on our end, but unsure if there's a reason they have it this way.
