### ISSUE TITLE
Items that cannot be sold

### ISSUE THREAD

**Issue by Johann12345555** [SmashMC-Development/Bugs-and-Issues#1312]
**Describe the Bug**

There are several items that have the description "Can be sold to shop keepers" that cannot be sold to the shop keepers
These items include: 
Relic Items (silver copper gold)
Shoal Shell
Shoal Salt
There might be more like this but these are the ones that I own. 

**To Reproduce**

Go to the mart and try to sell the list of items

**Servers with the Bug**

Kyogre 

**Expected behavior**

For the shopkeepers to be able to buy these things for money

**Comment by Mikirae** [comment]
These are all added for the next restart. Thank you for reporting :)
