### ISSUE TITLE
Lag/Tickspeed issue?

### ISSUE THREAD

**Issue by Johann12345555** [SmashMC-Development/Bugs-and-Issues#1313]
**Describe the Bug**

It is clear that there is some sort of tick speed issue on kyogre. Multiple things take much longer than they should be taking to do. For instance, the wiki states that berries on trees should grow like regular plants. It will take at most an hour for regular plants in minecraft to grow. I left my pc on over night for maybe 9 hours and there were only a few berries on the trees that grew. this is also seen in breeding because it takes 2 hours for an egg to produce even if the two mons are 'madly in love' 

**To Reproduce**

Plant a berry or breed two mons

**Servers with the Bug**

Kyogre

**Expected behavior**

Berries should grow much faster and eggs should come out quicker

**Comment by BGG100** [comment]
Yeah this issue is prevalent on all servers. Madly in Love pokemon breeding should take approx. 37.5 minutes, however its taking literal hours.

**Comment by Archie4690** [comment]
Hey @Johann12345555 Thank you for your bug report. Both of the issues stated above are based upon in-game ticks. Currently with the servers being freshly updated there can at times be a low tick speed at times, this causes these processes to take more time. Once the server's tick speed improves so should the other issue, so unfortunately as of right now there is nothing we can do to instantly improve this issue.
