### ISSUE TITLE
Unable to evolve pokemons at certain times

### ISSUE THREAD

**Issue by Akuenka** [SmashMC-Development/Bugs-and-Issues#1315]
**Describe the Bug**
I tried to evolve my rockruff twice to its midnight form so I evolved it both times at night and both times it just turned into a day lycanroc, i also noticed someone else in the chat was trying to evolve another pokemon that had to be evolved at night and it wouldent evolve but I dont remeber what the pokemon was 

**To Reproduce**
1. just try to evolve a rockruff at night 
2. See error

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre but im not sure if its in any other servers

**Expected behavior**
The pokemon to evolve to its midnight form instead of the time at day

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
One of the rockruffs i evolved during when it was raining so it might have been day but i doupt it since the sky was black and it was super dark but then again i havent played minecraft in a few years so i dont know
also im not sure if this problem with spefically rockruff has happend with anyone else since nobody in the chat ever says anything when I ask.

**Comment by Mikirae** [comment]
I took a look at this, and it unfortunately seems to be a Pixelmon issue. I see it on their tracker already, so I'll go ahead and close this. Thank you for reporting!
