### ISSUE TITLE
Galaxy Arceus bug

### ISSUE THREAD

**Issue by Chummsy** [SmashMC-Development/Bugs-and-Issues#1316]
**Describe the Bug**
When one owns a galaxy arceus and gives it any type of plate, the arceus changes colors to that type. BUT if you remove it the galaxy form gets removed

**To Reproduce**
1. Put a plate on a galaxy arceus as a held item
2. Remove the plate as held item
3. Galaxy form is removed

**Servers with the Bug**
Probably network

**Expected behavior**
When a plate is removed, keep the galaxy texture

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
I believe I fixed this. Please let me know if it's not fixed!
