### ISSUE TITLE
/repair bug

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1317]
**Describe the Bug**
/repair dont work on pixelmon items

**To Reproduce**
1. get a used pixelmon tool/armor
2. use /repair

**Servers with the Bug**
kyurem, dunno about others

**Expected behavior**
/repair works on pixelmon items

**Comment by Mikirae** [comment]
I'll take a look at this, but I don't know if there's a way to get it to work. Might need to get something custom. Thank you for reporting! :)

**Comment by WalkAway7** [comment]
doesnt work on reshiram either, pretty sure it's a network wide problem ^^

**Comment by Superfire96** [comment]
Fixed some time ago
