### ISSUE TITLE
Ev training broken

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1318]
**Describe the Bug**
its not giving me ny evs after defeating them. Like i tried using ralts in the Speed EV to get 252, but after fighting the npcs 3 times, the Evs for speed is still 0. Also sometimes when i defeat a single npc in the EVs it goes from 0 EVs to 252 instantly

**To Reproduce**
1. Attack EV trainer
2. defeat them
3. see that it does not give the correct amount of evs

**Servers with the Bug**
Reshiram from what I know

**Expected behavior**
should give correct amount of evs

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Pixelmon issue again :((((((
