### ISSUE TITLE
Flying on pokemon a bit broken

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1319]
**Describe the Bug**
When a lag spike hits you lose the ability to use your fly mon. Like it stops mid air and you have to bring it back into your pokeball and throw it out again to use it again 

**To Reproduce**
1. fly on pokemon 
2. when lag spike hits it dismounts you

**Servers with the Bug**
Reshiram from what I know

**Expected behavior**
Shouldn't dismount

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Pixelmon thing that we can't fix :(
