### ISSUE TITLE
Throwing out pokemon goes threw the floor. 

### ISSUE THREAD

**Issue by eboyJay69** [SmashMC-Development/Bugs-and-Issues#132]
**Describe the Bug**
When you try to throw out your Pokémon it goes threw the floor. 
**To Reproduce**
1. Throw out your pokemon
**Servers with the Bug**
Jirachi, Mew, Charizard, Kyogre, Rayquaza, Deoxys, Giratina, Palkia 

**Screenshots**
n/a
**Additional context**
Darkrai for some reason works.

**Comment by Rasgnarok** [comment]
Where is this happening, exactly?

**Comment by Mikirae** [comment]
When they throw out their Pokemon at spawn, their mons go through the floor.

**Comment by Mikirae** [comment]
This should be fixed on all servers now. Please let me know if you're still facing any issues!
