### ISSUE TITLE
Pokemon breeding a bit broken

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1320]
**Describe the Bug**
Pokemon take a abnormal amount of time to make eggs, im assuming its because for some reason you need to be in the same dimension, but j had pokemon madly in love in a breeder, went to ultra space for a hour, came back and still no egg

**To Reproduce**
1. Start breeding
2. sees that eggs are taking long

**Servers with the Bug**
Reshiram

**Expected behavior**
Should breed normally

**Screenshots**
N/A

**Additional context**
N/A

**Comment by oLimooo** [comment]
![Uploading 5908E62B-8CE9-4CC8-A877-D1435A899DD5.jpeg…]()

**Comment by oLimooo** [comment]
Oh lol rip image. Scroll a little higher up. Archie respond to this

**Comment by WalkAway7** [comment]
Ah fair enough, all these githubs I've got have been provided to me by my friends in a server, I made a channel so that they can say all the bugs lmao, they all smell and dont do github so I just said dump the issues in the channel and I'll make the github, so anything innacruate or out of date you know why

**Comment by Archie4690** [comment]
Hey @WalkAway7, this issue is to do with the server's TPS. Once the TPS is getting back to a normal, regular rate then things should improve! thank you for making a bug report, we are sure to try our best to get the TPS up as soon as possible.
