### ISSUE TITLE
cant chat in battle

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1321]
**Describe the Bug**
Sometimes, when you're in battle you cannot chat, it just doesnt let you type anything

**To Reproduce**
1. go into a battle
2. try to type
3. sometimes it doesnt work

**Servers with the Bug**
Reshiram, maybe the others

**Expected behavior**
should let you type

**Screenshots**
N/A

**Additional context**
N/A

**Comment by oLimooo** [comment]
Pretty sure this is a pixelmon issue, i believe one of the helpers told me that

**Comment by Mikirae** [comment]
This is a Pixelmon bug and it makes me the big sad :(
