### ISSUE TITLE
Decode sensoring

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1322]
**Describe the Bug**
Sensoring is working, however it stops you from doing the decode minigame in with some pokemon

**To Reproduce**
1. Certain decode puzzles show up
2. Cannot answer due to sensoring

**Servers with the Bug**
All

**Expected behavior**
SHould let you decode it

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/174164869-6061b21c-7d3b-41bd-b6b1-6baa5ec3a0a0.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
FIXED FOR NEXT RESTART THANK YOU
