### ISSUE TITLE
cross chat a bit wrong

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1323]
**Describe the Bug**
Players who are e4 does not show up in the cross chat

**To Reproduce**
1. go to a cross chat
2. an e4 member types, but you cant see that they are e4

**Servers with the Bug**
I think on all

**Expected behavior**
Should show up as e4

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/174166008-83e4b7bc-c7ce-465d-84a4-30f38fca860b.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
I believe that's just showing whatever rank they have in game right?

**Comment by WalkAway7** [comment]
Yes they have that rank in-game. However they are also an e4 member, and do not have that prefix in the cross chat channel, despite having it in game

**Comment by Mikirae** [comment]
But do they have the E4 rank in game? It should just do whatever their highest prefix is

**Comment by WalkAway7** [comment]
Yeah they do, just crashed but I'll send a science through

**Comment by WalkAway7** [comment]
Screenshot*

**Comment by WalkAway7** [comment]
![image](https://user-images.githubusercontent.com/89798207/174196013-29e0f871-d99f-4644-ab0f-35a4bc3b6124.png)
Here^

**Comment by Mikirae** [comment]
That's really weird wtf. I'll take a look

**Comment by Mikirae** [comment]
Should be fixed now. THANK YOU SIR
