### ISSUE TITLE
mrs eevee 

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1324]
**Describe the Bug**
When you defeat mrs eevee you dont get the rc

**To Reproduce**
1. go to mrs eevee
2. defeat her
3. get nothing

**Servers with the Bug**
Reshiram from what you know

**Expected behavior**
should give you rc

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/174185358-3e114850-213b-4183-b228-7826adf3a8c6.png)

**Additional context**
N/A

**Comment by Archie4690** [comment]
Heya @WalkAway7, This is currently a bug with pixelmon. hopefully, when it is fixed things should be all up and running!
