### ISSUE TITLE
Warzone Spawns are incredibly broken

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1325]
Warzone has literally only been spawning a significant amount of Arceus, Charizard, Empoleon, and Alakazam for the past hour or so>

Rayquaza server

**Comment by Archie4690** [comment]
Hey @BGG100, we are aware of this bug. if you could please open a ticket if this does occur on your server that would be great! Will be closing this up now though, thank you for the report!
