### ISSUE TITLE
DropClear Lag Spikes

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1326]
**Describe the Bug**
extreme lag occurs during drop clear

**To Reproduce**
when the scheduled dropclear commences, the server lags/freezes for an extended period of time, however it is still possible to actively communicate in chat

**Servers with the Bug**
Rayquaza that I know of, could be all

**Expected behavior**
Less lag upon DropClear

**Additional context**
Idk if anything can be done abt this. Not a massive deal and shouldn't be prioritized over other issues, but thought i would bring it to attention anyway

**Comment by Mikirae** [comment]
So this happens every time it occurs? And does it say how many entities it kills or no?

**Comment by Mikirae** [comment]
HELLOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO?

**Comment by BGG100** [comment]
SORRY I DIDNT SEE UR RESPONSE.

But yes, everytime DropClear occurs a significant lag spike follows. Literally everytime, and yes it does say how many entities were cleared. However, the value of entities doesn't seem to effect whether or not the server experiences lag, as it always happens regardless if the number is double or triple digits.

**Comment by jantjewieger** [comment]
I have not had this happen in a long time. Is this still an issue for you?

**Comment by Superfire96** [comment]
Was fixed long time ago, closing old trackers.

**Comment by Mikirae** [comment]
That's really weird. I'll look in to getting a different one or just
removing it for a bit. Guess I'll put Warzone back in and remove that one
or something
