### ISSUE TITLE
Broken galaxy textures

### ISSUE THREAD

**Issue by Chummsy** [SmashMC-Development/Bugs-and-Issues#1327]
**Describe the Bug**
Broken galaxy textures

**To Reproduce**
1. Broken textures
-Mewtwo
-Mewtwo
-Arceus
-Thunderous
-Calyrex
2. See error

**Servers with the Bug**
Most likely network wide

**Expected behavior**
Fixed galaxy texture

**Screenshots**
N/A.

**Additional context**
N/A

**Comment by Mikirae** [comment]
Arceus is fixed for next restart, the others should be fixed already :)
