### ISSUE TITLE
Dirt not turning into grass

### ISSUE THREAD

**Issue by geusbi** [SmashMC-Development/Bugs-and-Issues#1328]
Basically what's happening is: I placed dirt blocks 2 IRL days ago and I did stay close to them however they just didn't turn to grass
![dirt](https://user-images.githubusercontent.com/93953225/174429762-6f94fa98-eba6-4cc9-9a4a-fb87239df27d.png)

**Comment by Mikirae** [comment]
Is this in Ultra Space? I saw someone say they had that issue there. Also please let me know what server this is on.

**Comment by xXbumisXx** [comment]
Its in ultra space and overworld. And i think its all servers. Zekrom for sure

**Comment by Mikirae** [comment]
So grass doesn't spread at all? Does water flow?

**Comment by xXbumisXx** [comment]
in general plants dont grow, tree leafs dont go away when wood is choped and grass doesint spread. And yes water flows/sand falls

**Comment by Mikirae** [comment]
Alright that's really weird. I'll take a look into this.

**Comment by Archie4690** [comment]
Hey! This issue should have been fixed a couple days ago. Thank you for making a bug report!
