### ISSUE TITLE
end crystal bug

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1329]
**Describe the Bug**
end crystals are indestructible when inside a claim

**To Reproduce**
1. claim an end crystal
2. try to break it

**Servers with the Bug**
kyurem dunno about others

**Expected behavior**
crystals be breakable but not explode

**Comment by Mikirae** [comment]
So, this happens even when you're the one that claimed it? This could be related to me disabling explosions in claims, but that would be a bit weird
