### ISSUE TITLE
Issues with /buymove command

### ISSUE THREAD

**Issue by Unitzero007** [SmashMC-Development/Bugs-and-Issues#133]
**Describe the Bug**
Cannot afford any of the moves from the /buymove command

**To Reproduce**
1. Type /buymove (slot) (move) c
2. Try learning that move on the Pokémon you selected
3. A message saying that you cannot afford to buy the move will appear even if you have more than 2500 pokedollars.

**Servers with the Bug**
All

**Expected behavior**
You should be able to buy a move using /buymove for 2500 pokedollars.

**Screenshots**
![image](https://user-images.githubusercontent.com/83878956/118954854-bfd88780-b990-11eb-8f4a-1a5a85022724.png)

**Additional context**
I have 1.5 million pokedollars on ray, and I cannot buy any moves even with that amount of cash.

**Comment by HackuJacku** [comment]
Fixed.
