### ISSUE TITLE
Pokeball issue 

### ISSUE THREAD

**Issue by YepEchens** [SmashMC-Development/Bugs-and-Issues#1330]
**Describe the Bug**
So my bug that i have found is that when i try to make a pokeball I am unable to craft it and I even finalized with the helpers and stuff that this issue is bugged and 

**To Reproduce**
1. Have Pokeball top and iron bottom and stone button 
2. put these in order so top on top stone button and iron baser 
3. ANd you can see you cant craft 

**Servers with the Bug**
Kyogre is the server that I'm on and idk about others 

**Expected behavior**
A clea
![ss](https://user-images.githubusercontent.com/107763030/174445005-3b2e3d45-4736-42fe-97a6-7c268d6411a5.png)
r and concise description of what you expected to happen.

[](u

**Additional context**
N/A

**Comment by Mikirae** [comment]
This looks to be working for me. Please let me know :)

**Comment by Mikirae** [comment]
This seems to be working so I'm closing this ticket
