### ISSUE TITLE
wz pokemon not spawning in 

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#1332]
**Describe the Bug**
no pokemon is spawnning in wz

**To Reproduce**
1. occationally on start up pokemon does not spawn in wz not really reproducable per say

**Servers with the Bug**
saw reports from zekrom potentially other servers

**Expected behavior**
pokemon should spawn and despawn from time to time in wz
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This is fixed :) Thank you!
