### ISSUE TITLE
Cant breed more than 5 pairs of pokemon

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Bugs-and-Issues#1333]
So like the title says, I can't apparently breed more than 5 pairs (10 pokemon) total. It says in the news of SmashMC that everyone can breed 20 pairs (40 pokemon) total. I'm pretty sure this is a glitch.

So far this is happening in the Reshiram server, I'm not 100% sure about other servers though, as I don't main any other server other than Reshiram

**Comment by Mikirae** [comment]
max-cumulative-pokemon-in-ranch: 20, the setting looks to be correct
Maybe try removing them all, and then making more? I haven't heard of anyone else having this issue

**Comment by IAmF3rdie** [comment]
i thought you can have 20 pairs of pokemon (40 individual pokemon total)?

**Comment by BGG100** [comment]
Yeah you should, however its been communicated that the issue is on pixelmons end rather than the server itself. Hopefully itll receive a fix soon

**Comment by Mikirae** [comment]
It's a Pixelmon bug so I'm closing it, but it's 20 Pokemon total, not 20 pairs
