### ISSUE TITLE
I opened megastone crate keys and got 4 megastones but when i relogged i didnt have any

### ISSUE THREAD

**Issue by cactusmannn** [SmashMC-Development/Bugs-and-Issues#1335]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Please open a ticket about this issue! Not sure what happened or if it was a visual bug.
