### ISSUE TITLE
Dynamax clause

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#1336]
*Describe the Bug**
currently you can dynamax in warzone

**To Reproduce**
1. finish dynamax quest
2. go into warzone and fight any pokemon
3. gives you the option to dynamax

**Servers with the Bug**
all servers

**Expected behavior**
if we are following the natdex rules you should not be able to dynamax

**Screenshots**
![image](https://user-images.githubusercontent.com/85075804/174483695-a7507e93-9774-46f5-a654-e4329bb947f6.png)

**Additional context**
rules for nat dex:
https://www.smogon.com/dex/ss/formats/national-dex/

**Comment by Mikirae** [comment]
I'm looking in to this. Thank you for reporting!

**Comment by Superfire96** [comment]
Was fixed long time ago, closing old trackers.
