### ISSUE TITLE
Good Rods/ Super Rods Not Usable

### ISSUE THREAD

**Issue by RoaringVQ37** [SmashMC-Development/Bugs-and-Issues#1337]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Archie4690** [comment]
@RoaringVQ37 Please submit another bug report with the above information submitted.
