### ISSUE TITLE
Anvil Command

### ISSUE THREAD

**Issue by BrunchBee** [SmashMC-Development/Bugs-and-Issues#1338]
**Describe the Bug**
Legend players do not have permission to use /anvil

**To Reproduce**
1. Be a legend rank
2. Type ' /anvil '
3. See error

**Servers with the Bug**
Kyogre at least

**Expected behavior**
Being able to open the anvil menu from anywhere, similar to /craft or /ec

**Screenshots**
N/A

**Additional context**
I have no idea if Smash ranks are able to use /anvil so that should be checked as well.

**Comment by Mikirae** [comment]
It seems to be a bug with the plugin, hoping that they can get it fixed soon. Thank you for reporting! :)

**Comment by Superfire96** [comment]
Was fixed
