### ISSUE TITLE
Items that should be sellable aren't

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#1339]
**Describe the Bug**
Items that say sell to shopkeepers cannot be sold to shopkeepers 

**To Reproduce**
Try to sell an item such as shoal shells or gold relics and it doesn't appear to be sellable 
**Servers with the Bug**
All I believe 

**Expected behavior**
I should be able to sell these items 

**Screenshots**
N/A 

**Additional context**
N/A

**Comment by Mikirae** [comment]
ADDED THEM FOR NEXT RESTART
