### ISSUE TITLE
Issue with /dailies on Palkia Server

### ISSUE THREAD

**Issue by Unitzero007** [SmashMC-Development/Bugs-and-Issues#134]
**Describe the Bug**
Dailies are showcasing different items on the Palkia server. People who have claimed dailies for more than 1 week have their /dailies screens bugged out, and an error message would replay when they try to collect the next day's daily.

**To Reproduce**
1. Go to Palkia Server
2. Type /dailies
3. Click the icon of the giftbox on the right
4. If you have claimed less than 7 days of dailies on Palkia a screen with only diamonds will appear instead of the 30 days dailies.

**Servers with the Bug**
Palkia

**Expected behavior**
Dailies on Palkia should work similarly to the dailies on the other servers.

**Screenshots**
![image](https://user-images.githubusercontent.com/83878956/118955563-62910600-b991-11eb-9dde-c883c1fad239.png)

**Additional context**
I could only test the dailies bug for those who have less than 7 days of claimed dailies.

**Comment by HackuJacku** [comment]
Fixed.
