### ISSUE TITLE
Apricorns taking ages to grow

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Bugs-and-Issues#1341]
Basicaly the apricorns are taking a long time to grow and wailmer's pail does not make them grow up 1 stage (Idk if now that's supposed to happen)

1. Plant a apricorn
2. Wait...

**Servers with the Bug**
Probably all but I play on Rayquaza

**Expected behavior**
I expected them to grow faster

**Screenshots**
![Minecraft 06-18-2022_12-10-51-667_Moment](https://user-images.githubusercontent.com/99098141/174691485-fab81983-d72e-4b7d-abb8-bd5fd8b9ab09.jpg)
![2022-06-20_15 00 16](https://user-images.githubusercontent.com/99098141/174691490-910c92e1-ff7e-400a-8191-de470559ad4e.png)

**Additional context**
50h of difference between screenshots
Maybe a bug/glitch where server is slow

**Comment by Mikirae** [comment]
I haven't had the chance to really play 9.0 so I don't know much about Apricorns now. Is there NO change? Or does it change, but it's super slow?

**Comment by Johann12345555** [comment]
> I haven't had the chance to really play 9.0 so I don't know much about Apricorns now. Is there NO change? Or does it change, but it's super slow?

It changes but it's super slow, it's the same with berry trees. I've left my computer on in the server over night and I'd hardly see any berries on the 20-40 trees I've planted

**Comment by Mikirae** [comment]
That unfortunately might just be how Pixelmon works now. We’re not changing any speeds on our end :(

**Comment by SimaoAntunes26** [comment]
> That unfortunately might just be how Pixelmon works now. We’re not changing any speeds on our end :(
> […](#)
> On Jun 27, 2022, at 12:36 PM, Johann12345555 ***@***.***> wrote: ﻿ I haven't had the chance to really play 9.0 so I don't know much about Apricorns now. Is there NO change? Or does it change, but it's super slow? It changes but it's super slow, it's the same with berry trees. I've left my computer on in the server over night and I'd hardly see any berries on the 20-40 trees I've planted — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

Ok so, what I understood is that it's just how it works now in Pixelmon but that's really unfortunate cuz just doing some quick maths a apricorn tree can have 17 harvestable leaves, considering the PokeBall as an example it could make 15 pokeballs if all of them grow but as you can see the apricorns grew up 1 stage (and not all of them grew) after 50h. If it takes 100h to all of them grow it means 15 pokeballs after more than 4 days. The only option is to buy pokeballs but there's no way to make money on the servers besides voting and defeating trainers

**Comment by Superfire96** [comment]
Was fixed long time ago, closing old trackers.
