### ISSUE TITLE
Battles

### ISSUE THREAD

**Issue by DaPrince24** [SmashMC-Development/Bugs-and-Issues#1342]
I play on groudon
and there is something very annoying because in a certain period of time you can only say one message. and when enough time passes, you cant say anything. thats why its very hard to end a regular battle if people want to battle for fun or tell the other that they're stuck. i think it needs to be fixed because then you cant do /endbattle and one person has to disconnect while the other knows nothing about it. it would be great if that was fixed and you are able to talk or do commands during battle. (like before the reset) Thank you very much!

**Comment by Mikirae** [comment]
This is a Pixelmon bug, we unfortunately cannot fix it :(
