### ISSUE TITLE
White and Blue dyes do not work

### ISSUE THREAD

**Issue by OverDr1v3** [SmashMC-Development/Bugs-and-Issues#1343]
**Describe the Bug**
Bone meal and lapis are sold in the shop as dye but do not work correctly. Need to be replaced with actual blue dye and white dye. Thanks.

**Servers with the Bug**
All servers

**Screenshots**
N/A

**Additional context**
N/A

**Comment by oLimooo** [comment]
You need to put the bone meal and lapis into a crafting table

**Comment by Mikirae** [comment]
This was fixed at some point I believe. Thank you for reporting!
