### ISSUE TITLE
Vote Crate Random Non-legend Shiny Pokemon Glitch

### ISSUE THREAD

**Issue by ColonCrusader** [SmashMC-Development/Bugs-and-Issues#1344]
I opened a Vote Crate key and got the reward Random Non-Legend Shiny Pokemon, but recieved a shiny Groudon. I have tried this on other servers but didnt recieve anything like this.

Open Vote Crate Key
Get Non Legend Shiny Pokemon

This obviously isn't something that can just be reproduced as it is entirely RNG

![Bruh](https://user-images.githubusercontent.com/92840415/174816707-c2b88da7-4fbf-4dc3-9f13-5c46e0358be5.png)
![Bruhh](https://user-images.githubusercontent.com/92840415/174816732-e31df39b-e2dc-445b-94d2-d7312f345571.png)

**Comment by Mikirae** [comment]
Reported this bug to Pixelmon, and changed the Vote Crate to use reward papers. Thank you!
