### ISSUE TITLE
Quick Ball Capture rate

### ISSUE THREAD

**Issue by ColonCrusader** [SmashMC-Development/Bugs-and-Issues#1345]
So i actually went in and did the calculations using the pixelmon formula for Capture rate, and input my modifiers for the capture
so i was attempting to catch a level 13 yamper at 100% hp on the first turn with a quickball
yampers base catch rate is 255, quickball multiplier on the first turn is x5, and the status is 1 because there was no status
the hp was 100/100 so it was 1-2/3x1
this comes out to 1/3
255 x 5 x 1 is 1275
1275 x 1/3 is 424.9
so the catch chance was 424.9/255 which is a guarantee capture because if the top number is greater than 255, it is a guarantee capture, yet the yamper broke out of the quickball

i will attach the formula here
![capture rate](https://user-images.githubusercontent.com/92840415/174830303-b70969d4-6326-452f-ab27-9646ac59e7b4.png)

**Comment by Mikirae** [comment]
Well, can't argue with the math. Reported the bug to Pixelmon as we don't have control over it. Thank you! :)
