### ISSUE TITLE
money expolit

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1346]
**Describe the Bug**
/shop has cherish balls for 150
sell at mart for 250

**Servers with the Bug**
kyurem, prob other servers too

**Expected behavior**
sell price is lower than 150

**Comment by xXbumisXx** [comment]
can confirm its on all servrers

**Comment by Mikirae** [comment]
Maybe I'm crazy, but in /shop they seem to be selling for 250?

**Comment by Mikirae** [comment]
Nvm looks like someone just changed it. Thank you very much for reporting! :)
