### ISSUE TITLE
Missing TMs

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1347]
The TMs sold by the NPCs in /warp mart do not sell the full array of available TMs for each respective typing. This, coupled with the fact that raids no longer drop specific TMs aswell as move relearners currently not working, makes it quite literally impossible to get certain moves. For example, TM97 Defog is not in the flying section of the /warp mart

**Comment by Mikirae** [comment]
Hello sir that is a missing HM 
![image](https://user-images.githubusercontent.com/24925669/174947801-015624d1-e147-4150-936c-d8a913e53c70.png)

**Comment by BGG100** [comment]
pliz /buymove thak you
