### ISSUE TITLE
PokeStats & Battle Glitches

### ISSUE THREAD

**Issue by BiggyGumpIsHere** [SmashMC-Development/Bugs-and-Issues#1348]
When leveling up my Pokémon over the past couple of days the stats started to glitch out where the stats would go to the negatives and cause my Pokémon to take forever to kill something. Also, sometimes when I would fight the trainers there would be an error glitch causing it to cancel out multiple times. Please fix whenever you get the chance to.

**Comment by Mikirae** [comment]
This is a Pixelmon bug, it occurs with Pokerus (as far as I'm aware). It's fixed for their next version :)
