### ISSUE TITLE
Warzone Pokeball doesnt throw

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1349]
**Describe the Bug**
Sometimes when you miss a pokemon when you throw out your pokemon you cannot throw it for a while. Even when relogging doesn't fix the issue.

**To Reproduce**
1. Go to warzone
2. Throw a pokemon at another
3. Miss
4. Not be able to throw the pokemon out for an extended amount of time

**Servers with the Bug**
All

**Expected behavior**
Shouldnt bug out the pokemon throwing out

**Screenshots**
N/A

**Additional context**
It only happens when you miss a few times not 100% of the time

**Comment by Johann12345555** [comment]
This is a bug that makes warzone difficult to play. I've been in warzone on kyogre a lot and it is extremely difficult to hit a player. When you miss the first ball you will often have to chase the player you are trying to battle for 30 seconds before being able to try again. Elytras and thunder stone armour make this a nightmare

**Comment by Mikirae** [comment]
This should be fixed as of the latest update. Took a while for us to figure out what was up. Thank you for reporting :D
