### ISSUE TITLE
You don't get rewards from the Trivia anymore

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#135]
**Describe the Bug**
When correctly answering the Trivia, and being the first to do so, you don't get a reward.

**To Reproduce**
1. Wait for a Smash Trivia question to come up.
2. Be the first to reply correctly.
3. Check your inventory.

**Servers with the Bug**
Jirachi

**Expected behavior**
When you're the first to reply correctly to the Trivia, you're supposed to receive 3 rare candies.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Fixed, should be giving 3 RCs now.
