### ISSUE TITLE
Warzone spawns

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#1350]
**Describe the Bug**
At random times from what I’ve seen Pokémon in the warzone just don’t spawn at all. To fix it a server reboot is needed. 
**To Reproduce**
1. Go to /warzone
2. See no Pokémon are spawning

**Servers with the Bug**
Please provide a list of which servers have this bug.
All
**Expected behavior**
Pokémon are spawning as soon as players join warzone

**Comment by Mikirae** [comment]
I'm late getting to bug reports but this was being worked on for a while. It should be fixed now. Thank you :D
