### ISSUE TITLE
ALL MISSING TMs/TRs FROM /warp mart

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1351]
Bug:
Bug Buzz

Dark:
Crunch
Nasty Plot

Dragon:
Outrage

Electric:
NONE

Fairy:
Play Rough

Fighting:
Body Press
Close Combat

Fire:
Fire Blast
Blaze Kick
Flare Blitz

Flying:
Defog
Hurricane
Brave Bird

Grass:
Power Whip
Leaf Storm
Energy Ball
Seed Bomb
Leaf Blade

Ground:
Spikes
Earth Power

Normal:
NONE

Poison:
Toxic Spikes
Gunk Shot

Psychic:
Psychic Fangs
Cosmic Power
Stored Power
Zen Headbutt
Trick
Future Sight

Rock:
Power Gem

Steel:
Iron Head
Heavy Slam

Water:
Liquidation
Hydro Pump

Ice:
NONE

**Comment by BGG100** [comment]
plz add them making this list was mind numbing

**Comment by jantjewieger** [comment]
please make a suggestion on this. You made this in the bugs and issues section. Also please follow the correct format provided

**Comment by BGG100** [comment]
I assumed this was an issue rather than a suggestion, as there is literally no possible way to obtain these moves right now
