### ISSUE TITLE
Negative evs

### ISSUE THREAD

**Issue by pandam0n** [SmashMC-Development/Bugs-and-Issues#1353]
My pokemon have negative evs in groudon server.
![Screenshot 2022-06-24 003024](https://user-images.githubusercontent.com/108112317/175462532-6c1eb987-15bf-47f0-b0fd-5a84fcac0d6d.png)

**Comment by WalkAway7** [comment]
Please create a support ticket in the discord, and we cam get this fixed, @pandam0n !

**Comment by Mikirae** [comment]
Pixelmon bug. Please do what is above ^
