### ISSUE TITLE
Breeding Limit is still 10

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1355]
**Describe the Bug**
The breeding limit is still 10, despite changelogs stating it had been changed to 20

**To Reproduce**
Have 10 mons in ranch blocks
Attempt to add a 11th pair to a new ranch block
Prompted with 'You have too many Pokemon breeding right now"

**Servers with the Bug**
all

**Expected behavior**
To be able to breed 20 pokemon simultaneously 

**Additional context**
I believe miki said this was a pixelmon issue rather than server, however I wanted to report it here officially anyway

**Comment by Mikirae** [comment]
Pixelmon confirmed this is a bug on their end.
