### ISSUE TITLE
Air being in the loot pool

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1356]
**Describe the Bug**
Air is in the drop pool of pokemon

**To Reproduce**
1. Fight a pokemon
2. defeat it
3. get air

**Servers with the Bug**
reshi from what I know

**Expected behavior**
Should not have air as a drop 

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/175825207-f46f9162-05bf-47bf-954e-a6e9c83131c1.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
Lunatone flies and therefore has air

**Comment by WalkAway7** [comment]
Is it bad that I genuinely cannot tell whether this is a joke or you're telling the truth

**Comment by Mikirae** [comment]
It is a joke

**Comment by Mikirae** [comment]
"fwiw the issue is pokemon with a min: 0 have a chance of dropping air instead of dropping nothing for that roll"
So some Pokemon have drops that aren't guaranteed. That's when this happens. AKA, pixelmon bug
