### ISSUE TITLE
Wz rep randomly going down

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1357]
**Describe the Bug**
Warzone rep is going down randomly, despite not winning or losing any battles.

**To Reproduce**
1. Look at warzone rep
2. see its going down without any interaction with it

**Servers with the Bug**
Reshi from what I know

**Expected behavior**
Shouldn't go down

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/175825270-2944df05-00c7-4115-bd4c-e661b0472962.png)

**Additional context**
N/A

**Comment by Sadkeemstar112** [comment]
Its because they have a decaying system if u dont go to warzone or battle you lose reputation.

**Comment by WalkAway7** [comment]
Yes but also other players on the server I play on have had the same rep for a long time despite not going in the warzone for a while

**Comment by Sadkeemstar112** [comment]
> Yes but also other players on the server I play on have had the same rep for a long time despite not going in the warzone for a while

Its as soon as u visit warzone the system have always been like that on the other servers and Ray

**Comment by Mikirae** [comment]
I'll see if I can get this updated to be on login instead of upon enter
