### ISSUE TITLE
Cant Throw Pokemon out in Warzone

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1358]
**Describe the Bug**
Upon entering warzone you cannot throw a pokemon in your party at any pokemon/anything

**To Reproduce**
Go to warzone
Attempt to throw out pokemon
Nothing happens 

**Servers with the Bug**
Rayquaza, probably network wide

**Expected behavior**
To actually be able to throw a pokemon out

**Additional context**
As i type this, I've been in warzone for 5 minutes and have been able to throw my pokemon out ONCE. This glitch is essentially causing warzone to literally become a money drain. Multiple legends have despawned infront of me because I cannot throw anything for minutes on end.

**Comment by Mikirae** [comment]
Already have a ticket open about this with the developer. Closing because duplicate
