### ISSUE TITLE
EVs not training properly

### ISSUE THREAD

**Issue by BGG100** [SmashMC-Development/Bugs-and-Issues#1359]
**Describe the Bug**
EV trainers at /warp mart do not properly train EVs

**To Reproduce**
Go to /warp evs
Attempt to train a specific EV
Check pokemons evs to see them incorrectly distributed

**Servers with the Bug**
Rayquaza, likely server wide

**Expected behavior**
For EVs to be trained correctly

**Screenshots**
![2022-06-26_19 05 59](https://user-images.githubusercontent.com/104792516/175837235-80a1178f-45b6-4689-b17f-774af907567a.png)
In this screenshot, I placed a power band (HP power item) to speed train chansey in HP IVs. After defeating the HP EV trainer once, it gives 27 HP evs but also 24 attack evs

**Comment by Mikirae** [comment]
This is a Pixelmon bug that hasn't been fixed yet ;(
