### ISSUE TITLE
GTS is down on Darkrai

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#136]
**Describe the Bug**
GTS won't open

**To Reproduce**
1. Go to Darkrai
2. Type /gts
3. See the error (screenshot below)

**Servers with the Bug**
Darkrai

**Expected behavior**
The GTS should open upon running /gts.

**Screenshots**
![Darkrai GTS fatal error](https://user-images.githubusercontent.com/82727445/118960908-0c599e00-b964-11eb-88af-c145d0444e33.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed.
