### ISSUE TITLE
Bug with the HP ev trainer in /warp evs

### ISSUE THREAD

**Issue by LordYoshiZ** [SmashMC-Development/Bugs-and-Issues#1360]
**Describe the Bug**
The HP trainer in /warp evs give incorrect evs while holding a power weight.

**To Reproduce**
1. Have any pokemon hold a power weight
2. go to /warp evs
3. fight the hp trainer with the pokemon holding a power weight
4. check /evs # and it gives 27 HP evs and 24 attack evs

**Servers with the Bug**
-Reshiram

I can't confirm if any other servers have this bug

**Expected behavior**
What is supposed to happen is that I gain no attack evs and gain just 27 hp evs

**Screenshots**
![image](https://user-images.githubusercontent.com/108284634/175967524-e32125bc-2677-454a-8992-61e92a76292b.png)
Without pokerus
![image](https://user-images.githubusercontent.com/108284634/175967626-4ee0d6b5-2868-44a6-847f-2c4e0c4ef37f.png)
With pokerus (which for some reason is the same)

**Additional context**
N/A

**Comment by Mikirae** [comment]
This is unfortunately a Pixelmon bug :( We have to wait until they fix it
