### ISSUE TITLE
Missing texture for galarian zapdos

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#1361]
**Describe the Bug**
galarian zapdos does not has a texture

**To Reproduce**

throw out a galarian zapdos
it appears purple and black

**Servers with the Bug**

tested on kyurem potentially more server

**Expected behavior**

to properly demonstrate galarian zapdos

**Screenshots**
![image](https://user-images.githubusercontent.com/85075804/176310627-62f0187c-6a50-4e5f-8d1e-bcce70801a1e.png)
![image](https://user-images.githubusercontent.com/85075804/176310702-63e8a094-c28e-4808-92a5-265dae607845.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Not an issue on our end, we will have to wait for the Pixelmon mod to fix the issue
