### ISSUE TITLE
Steenee Wont Evolve at lvl 63 with stomp

### ISSUE THREAD

**Issue by theaney843** [SmashMC-Development/Bugs-and-Issues#1362]
**Describe the Bug**
My steenee ive had since lvl 14 hasn't evolved at lvl 63 even though it has Stomp and there are no other requirements. Ive tried restarting the server and MC and neither has worked for me.

**To Reproduce**

**Servers with the Bug**
Reshiram

**Expected behavior**
Expected to have levelled up by no later than level 50, yet that hasn't happened.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![2022-06-29_06 44 35](https://user-images.githubusercontent.com/59296930/176360650-df42fb94-9dca-4d66-b4c7-c999e1d6d9ca.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Mikirae** [comment]
Would you be able to open a ticket in the Discord and asking for help? Mine seems to be just fine
