### ISSUE TITLE
Still glitched stats

### ISSUE THREAD

**Issue by BiggyGumpIsHere** [SmashMC-Development/Bugs-and-Issues#1363]
It's been a couple of days now and some of my Pokémon stats are still glitched in the negatives and I've tried to change them, but they just never work and gets annoying since i can't level them up due to not being able to take hits or killing the Pokémon to level up so please whenever you get the chance fix this.

**Comment by Johann12345555** [comment]
Make a ticket and a sr mod+ should be able to fix it. Either this or close Minecraft completely and relaunch it

**Comment by jantjewieger** [comment]
This is unfortunately a pixelmon issue. I believe its fixed in the latest update. As Johann said, if you could please make a ticket so one of our senior mods can force fix this issue for you
