### ISSUE TITLE
Cooldown reset

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Bugs-and-Issues#1364]
**Describe the Bug**
When using /hatch and /breed incorrectly it resets the time

**To Reproduce**
Use the command incorrectly such as running /hatch on a pokemon instead of an egg. 

**Servers with the Bug**
All

**Expected behavior**
When using the command incorrectly it shouldn't reset the cooldown

**Comment by Johann12345555** [comment]
I think they tried to fix this issue but when they did, it made it to where there was no cooldown for /breed at all

**Comment by Superfire96** [comment]
Sadly there's nothing that we can do about that. If used incorrectly you will still get the cooldown
