### ISSUE TITLE
Unable to /repair Pixelmon based tools 

### ISSUE THREAD

**Issue by Awholemess** [SmashMC-Development/Bugs-and-Issues#1366]
**Describe the Bug**
Even with my legend rank and the ability to use /repair on Diamond tools, any tool made from an evolution stone can’t be repaired. 

**To Reproduce**
1. Hold a tool made of evolution stones
2. Do /repair
3. Look in chat and see the message “Can’t repair this item”

**Servers with the Bug**
Rayquaza

**Expected behavior**
I was expecting to be able to repair my tools, as the command itself suggests.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
We're aware of the issue, currently working to fix that

**Comment by Superfire96** [comment]
Fixed some time ago
