### ISSUE TITLE
Nothing happens when evolving

### ISSUE THREAD

**Issue by Jeroenvan8** [SmashMC-Development/Bugs-and-Issues#1367]
**Describe the Bug**
Whenever one of my pokemon needs to evolve it does but it walks out of the screen and just keeps doing its thing untill forever, the only way to get out of this screen is by closing the game.

**To Reproduce**
1. Evolve a pokemon
2. See it for yourself

**Servers with the Bug**
Zekrom

**Expected behavior**
It needed to evolve

**Screenshots**
'N/A'.

**Additional context**
 It would only evolve by feeding the pokemon a rare candy

**Comment by jantjewieger** [comment]
Hi Jeroen, this is a pixelmon issue and we would thus have to wait for them to fix it. While we wait for that you can always make a ticket so one of our senior mods can force evolve the mon for you!
