### ISSUE TITLE
kyurem and possibly other server warzones are bugged

### ISSUE THREAD

**Issue by twizzy0** [SmashMC-Development/Bugs-and-Issues#1368]
**Describe the Bug**

**To Reproduce**
1. go into warzone
2. catch any legendary
3. leave warzone and check the nature
4. it’ll be lax nature every single time

**Servers with the Bug**
kyurem possibly others

**Comment by Mikirae** [comment]
I tested this on the latest Warzone version and all five of the legends I caught had different natures.
