### ISSUE TITLE
buying things from store

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1369]
**Describe the Bug**
When u buy something from the store the pop-up message isn't done properly

**To Reproduce**
1. Go to the store
2. Buy something
3. see error when dono message pops up in chat

**Servers with the Bug**
Saw on Ray but could be all

**Expected behavior**
Id expect the msg to be correctly formatted :p

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/177317260-59d31957-8f98-4fad-8ba7-347bb11dd815.png)

**Additional context**
NA

**Comment by Mikirae** [comment]
Fixed, thank you :D
