### ISSUE TITLE
Staff Member Received This Spam After Joining Server

### ISSUE THREAD

**Issue by LittleBunnyFuuFuu** [SmashMC-Development/Bugs-and-Issues#137]
Once I logged into the server, it happened for every server I joined so far, I received these spam messages about activating metrics for different plugins.

To reproduce this, I just had to log into the server.

It happened on Charizard, Giratina, and Jirachi (these are the only ones I've been on today so far.)

![unknown](https://user-images.githubusercontent.com/84511353/118978947-ef15d700-b945-11eb-9111-9bf6f2282809.png)

**Comment by HackuJacku** [comment]
Fixed from next reboot.
