### ISSUE TITLE
5th voting link doesnt give crate

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1370]
**Describe the Bug**
When you vote on all 6 links you only get 5 crates. There used to be an issue that the 5th link was the same as the 2nd link, which is now fixed. However the fifth link doesnt give a crate now. all other links do give a crate

**To Reproduce**
1. do /vote ingame
2. click on all links
3. vote on all links
4. only get 5 crates bc 5th link doesnt give a reward

**Servers with the Bug**
Reshiram for sure but most likely all

**Expected behavior**
Id expect all links to give a reward

**Screenshots**
NA

**Additional context**
NA

**Comment by Mikirae** [comment]
It's fine on our end. Must be something wrong with the site which we cannot fix
