### ISSUE TITLE
Chat Sentry is not censoring properly

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#1371]
**Describe the Bug**
Chat Sentry plugin is incorrectly analyzing chat and blocking messages that do not need to be blocked.
**To Reproduce**
Type a phrase in chat that has nothing to do with a bad word and get chat blocked because of it
ie " I got a Grass block out of a grass block"
Chat sentry things you are typing "Fag" and blocks it.
**Servers with the Bug**
ALL

**Expected behavior**
Update plugin to correctly analyze the chat for intentional homophobia possibly so this doenst happen

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/177517095-c673ec6c-0ad5-48a3-9a25-b809806edb06.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Should be fixed for next restart. Thank you :D
