### ISSUE TITLE
The difficulty of earning money in the current state of the game

### ISSUE THREAD

**Issue by Johann12345555** [SmashMC-Development/Bugs-and-Issues#1372]
**Describe the Bug**

As all may know, the only way of generating currency in the game was just doing raids and selling what you got. there literally was no other way. Sure you could sell say a BP mon to a player but that players money came from doing raids and selling its items. Now, raids have hardly been active throughout the day and there is hardly any money being made. my friends and I checked around 100 raid dens at a given time and maybe one fo them had been active. If this continues it will be difficult for any new player to generate money. Before, there were other ways to make money, like STS however that has been removed. I understand that the plugin needs to be updated to be added to the server but a lot of the players believe that it will not make a return either way. Generally I feel that more mays to make money need to be added into the game. I think the raids need to be fixed at the very least and STS needs to make a return even if it needs to be nerfed. 

**To Reproduce**
I feel like this is self explanatory

**Servers with the Bug**

All servers

**Expected behavior**

Raids should work properly. players should be able to see atleast a few raid dens active when they set a home and tp there. this may seem a little op but it hasnt even earned much money for the players, which can be seen in baltop

**Comment by VerifiedKiller** [comment]
especially people who have limited homes

**Comment by Paradis4432** [comment]
inactive
