### ISSUE TITLE
/Lottery command 

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1373]
**Describe the Bug**
The command /Lottery does not work. It states that players do not have permission with every command besides "/lottery help".

**To Reproduce**
1. Do /Lottery help
2. Make an input of any listed command
3. Gets denied by missing permission

**Servers with the Bug**
At least Kyogre

**Expected behavior**
The commands should work for normal users.

**Screenshots**
![2022-07-07_16 50 27](https://user-images.githubusercontent.com/94211853/177804323-316791ba-213f-4139-aee7-a0a243a5ef6e.png)

**Comment by Mikirae** [comment]
This is fixed. Thank you :D
