### ISSUE TITLE
HP ev training gives Attack Evs as well

### ISSUE THREAD

**Issue by ApplEthAUce21** [SmashMC-Development/Bugs-and-Issues#1374]
For whatever reason skwovets grant Attack Evs this can be easily fixed using marill or Azurill for the HP ev training so people dont have to keep spending thousands on kelpsy berries to lower their attack Ev stat

**Comment by Mikirae** [comment]
This is a Pixelmon bug with using the power weight that is known by them. Thank you for reporting!
