### ISSUE TITLE
Zygarde Cells and Zygarde Cores

### ISSUE THREAD

**Issue by VerifiedKiller** [SmashMC-Development/Bugs-and-Issues#1375]
**Describe the Bug**
Zygarde Cores and Zygarde Cells are supposed to spawn on chunks not loaded in for more than 30 mins. however, whenever I try to look for them I never see any. I recently got 2 zygarde cells and 1 Zygarde Core from the events crate, but I can't use them until I have at least 50 cells. which means id have to open event crates at least 24 more times and get lucky enough to get the cells and cores

**To Reproduce**
1. Look for Cells/Cores
2. cant find them

**Servers with the Bug**
all

**Expected behavior**
Spawn in chunks loaded for less than 30 mins

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
We have it set to true in the config. This is unfortunately a Pixelmon bug. I'll report it to them. Thank you!
