### ISSUE TITLE
money disappearing

### ISSUE THREAD

**Issue by twizzy0** [SmashMC-Development/Bugs-and-Issues#1376]
so this isn’t the first time but this is the largest amount ive had disappear, usually it happens in 3-4k amount from getting times out or kicked for some reason, this time I was just sitting for latios and I check my cash and I lost 9k, went from 105k to 96k.

**Comment by twizzy0** [comment]
kyurem btw

**Comment by Mikirae** [comment]
You'd have to show us screenshots and logs in a ticket. Money wouldn't randomly vanish without something happening in between.
