### ISSUE TITLE
Boxes delete items that are in it when broken

### ISSUE THREAD

**Issue by SpikeZaharr** [SmashMC-Development/Bugs-and-Issues#1377]
**Describe the Bug**
I thought boxes worked like Shulker Boxes, but if you put any item inside of a Pixelmon box, break the box, and set it back down, your stuff has gone byebye.

**To Reproduce**
1. Buy box from Decoratives in /warp Mart
2. Find "Box" and buy it
3. Go to your claim and place the box
4. Put any item in the box (please don't test using something worth a lot)
5. Break the box
6. Pick up the box and place it back down
7. Your stuff is gone

**Servers with the Bug**
I'm only aware of this bug on Groudon but I'm sure it might be a universal bug with Pixelmon

**Expected behavior**
I thought the Box was going to work like a shulker box, where you put an item in it, and pick it up to go travelling because that's what you do with normal boxes. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Can confirm this is the case. This is a Pixelmon bug. I'll make a report on it. Thank you for reporting!
