### ISSUE TITLE
Raids are happening less and less

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Bugs-and-Issues#1378]
As the title says, Raids are appearing less and less or its not happening at all. I have at least 20 sethomes and claims or raids, and before AT LEAST 10 of them would always have a raid, but now after a week and a half of observing, its like 2 or 3 AT MOST, and 90% of the time there are no raids AT ALL

So far this is happening in Reshiram, and a lot of players have noticed it too. Im not 100% sure about other servers though (cuz i only play on reshi), but its probably happening there as well.

**Comment by Mikirae** [comment]
This seems to be a Pixelmon bug and I really can't find any way to fix it. If I had to take a guess, I'd say it's in some way related to the spawning rates being all messed up ever since 9.0.4.
