### ISSUE TITLE
Can only get left pokemon holder part

### ISSUE THREAD

**Issue by Brandon0128** [SmashMC-Development/Bugs-and-Issues#1379]
**Describe the Bug**
You can not craft the right holder part for a pokemon trading machine
**Servers with the Bug**
Please provide a list of which servers have this bug.
Smash MC

**Comment by Mikirae** [comment]
This is unfortunately a Pixelmon bug and cannot be fixed by us. I can report it to them if this isn't fixed in the latest update, though.
