### ISSUE TITLE
Unable to battle bosses at boss tower

### ISSUE THREAD

**Issue by LittleBunnyFuuFuu** [SmashMC-Development/Bugs-and-Issues#138]
When attempting to start a battle with a boss at the boss tower, no connection is made and no battle is started. 

1. Go to boss tower.
2. Wait for a boss to spawn
3. Try to engage boss

**Servers with the Bug**
Jirachi

**Expected behavior**
I expected to be able to engage the boss and battle them

**Screenshots**
N/A

**Additional context**
I checked a couple other servers and their boss towers seem to work just fine.

**Comment by Mikirae** [comment]
Was this taken care of yet?

**Comment by HackuJacku** [comment]
Fixed.
