### ISSUE TITLE
Negative stats to pokemon

### ISSUE THREAD

**Issue by BiggyGumpIsHere** [SmashMC-Development/Bugs-and-Issues#1380]
This has been a couple of weeks now and some of my Pokémon are still having negative stats. Now I understand that you must be busy with fixing everything, but please can you guys fix this bug it annoying having your Pokémon always dying and not being able to level it up and how I've already made two reports already and hasn't been fixed.

**Comment by BiggyGumpIsHere** [comment]
Never mind just saw my last post comments so ill make a ticket to try and fix the issue

**Comment by Mikirae** [comment]
Sounds good. Will be closing this up :)
