### ISSUE TITLE
Warp evs HP mon

### ISSUE THREAD

**Issue by Johann12345555** [SmashMC-Development/Bugs-and-Issues#1382]
**Describe the Bug**

When you warp evs and train with the HP trainers, they send out skwovets. these mons give 1 HP aswell as 1 ATK. the problem with this is when ur training a tanky mon or just a mon that needs HP and not Atk you're forced to head over to the mart and spend 6k+ every single time you train with evs. this can easily be fixed by swapping out those 3 trainers mons from skwovet to something like caterpie which gives only 1 HP ev

**To Reproduce**

fight the warp evs trainer

**Servers with the Bug**

all

**Expected behavior**

The trainer should be using a mon that gives only HP evs

**Comment by Mikirae** [comment]
This is not the case. The issue here is a Pixelmon bug that has already been reported (and hopefully fixed by now)
![image](https://user-images.githubusercontent.com/24925669/178422705-36e27860-c347-4c0e-9232-27567c5f3153.png)
