### ISSUE TITLE
NPC's bugged at /warp mart

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1383]
**Describe the Bug**
All of the NPC's at /warp mart are blank, and you cannot buy / sell anything at them. This is the same for all other shopkeepers I believe so there is no way to sell your items to the server. 

**To Reproduce**
1. Go to Groudon server
2. /warp mart
3. Speak to any NPC

**Servers with the Bug**
Groudon

**Expected behavior**
Should be able to buy / sell from them 

**Screenshots**

![image](https://user-images.githubusercontent.com/86555718/178141371-e212916f-aa90-463f-9c39-e66441893eb8.png)

**Comment by Sadkeemstar112** [comment]
Its all servers

**Comment by jantjewieger** [comment]
This issue is now fixed!
