### ISSUE TITLE
Can not get ancient power on piloswine to evolve

### ISSUE THREAD

**Issue by Brandon0128** [SmashMC-Development/Bugs-and-Issues#1385]
**Describe the Bug**
Can not get ancient power
**Servers with the Bug**
Please provide a list of which servers have this bug.
Smash MC

**Comment by Mikirae** [comment]
It's available in move relearners. 
![image](https://user-images.githubusercontent.com/24925669/178423117-a790d7b4-1294-4a0d-aa3e-56e4697cc21d.png)
