### ISSUE TITLE
Can't enter WZ

### ISSUE THREAD

**Issue by DrSlapnut** [SmashMC-Development/Bugs-and-Issues#1386]
**Describe the Bug**
Cant enter warzone

**To Reproduce**
1. Use the command /warzone or /wz
2. Click on "Enter Warzone"
3. Can't enter

**Servers with the Bug**
Kyogre

**Expected behavior**
To enter warzone 

**Screenshots**
https://gyazo.com/c69b56add3f2dbfe20fddb96d1b283bb

**Comment by Mikirae** [comment]
This should be fixed now, I believe :)
