### ISSUE TITLE
Vote sites not giving rewards

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Bugs-and-Issues#1387]
I vote in all 6 sites and only get 4 rewards

1. Type /vote
2. Open all sites
3. Vote in them
4. Type /ac virtualkeys and open inventory to see that only got 4 rewards

**Servers with the Bug**
I play on Ray but I honestly don't think this is server related

**Expected behavior**
Receive all voting rewards

**Additional context**
I recorded me voting in all (2 times) if needed say it cuz I could not upload the video here

**Comment by Mikirae** [comment]
Do you know if it shows six messages in chat?
And do you know if there are certain sites that consistently do not give keys?

**Comment by Mikirae** [comment]
I believe I fixed this :)
