### ISSUE TITLE
Meltdown textures dont yet exist

### ISSUE THREAD

**Issue by bendex17** [SmashMC-Development/Bugs-and-Issues#1388]
Meltdown Textures which should be spawning in warzone already dont exist yet
The complete texture line is not even in the texture pack

**To Reproduce**

1. Go to the texture pack in data
2. Click on extract all
3. Click on assets, pixelmon, textures, pokemon 
4. See that there is no meltdown Textures in current 12.5 texture pack

**Servers with the Bug**
All servers since its missing in the texture pack

**Expected behavior**
Meltdown Textures spawning in wz even if rare

**Screenshots**
N/A
**Additional context**
N/A

**Comment by Mikirae** [comment]
Not sure what you're talking about with Meltdown textures? The ones in there are the Toxic textures, which are indeed in the pack
![image](https://user-images.githubusercontent.com/24925669/178423397-06303d39-d4e2-4be4-8087-64adb7197094.png)
