### ISSUE TITLE
General issues with server

### ISSUE THREAD

**Issue by ketl0rd** [SmashMC-Development/Bugs-and-Issues#1389]
This is just a post to bring across some issues in the game that should be fixed to make the game more enjoyable for everyone. 
- Game crashing when opening PC is still occurring 
- Raid spawn rates are low, making it hard to earn money, meaning the economy of the game is not flowing very well
- Pokemon spawn rates in overworld are still messed up ie. mons not spawning at times/very limited spawns 
- Legendary pokemon are spawning in the void in warzone. 
- Battle randomly crashing in warzone 
- Spawning in the void after a winning a battle in warzone 
- /breed and /hatch commands going on cooldown if any mistake is put into the command. eg. putting in wrong slot. (this shouldn't even be a thing, getting punished for making a typing error) 
- Ranch breeding cap remains at 10, instead of the 20 breeding limit we were told a while ago. 
- Regional breeding isn't working (galarian and hisuian) 
- Nature trio (Thundurus, Landorus, Tornadus) unable to change back to original forms from therian forms
- Catching animations taking an extremely long time, this has been an issue since the start of the reset. Makes it very annoying trying to catch things in warzone while on a time limit. 
These are just some of the issues I've run into playing the game. Im 100% sure there are people with more issues to add to this who have been still playing this game consistently. Fixing these would make quality of life a lot better and would help with keeping the population of the game alive.

**Comment by jantjewieger** [comment]
Hi ket, Unfortunately most of what u are listing here are pixelmon errors and therefore things out of our control.
- Game crashing when opening PC is something I haven't seen anyone have since the latest update. If u are still encountering it it is defo a pixelmon issue though
- raid spawns rates are low bc pixelmon messed something up and mons are therefore not spawning (and that includes raid dens)
- The legendaries spawning in the void would be something to post here yes
- /breed and /hatch im also not 100% sure on whether or not that is for here or pixelmon. Unsure as to if its a plugin
- Ranch breeding was never upped to 20 ranch blocks bc that was never said. The ranch cap was at 5 before (10 mons) and in the announcement it was said it would be increased to 20 mons (and that makes 10 ranch blocks). The reason for this is because eco would too drastically be affected if people were to have more than that and just endlessly breed (which they kinda already are doing with just the 10)
- Regional breeding, im pretty sure, is a pixelmon issue
- The natural trio would also be a pixelmon thing
- The catching animations are also something that pixelmon added in the 1.16 update

**Comment by ketl0rd** [comment]
Yeah I was thinking that a lot of these issues were Pixelmon sided issues. I'll be posting updates on more issues in the comments of this post i come across
- Sandstorm ending wz battles, i believe another one would be if ferrothorn has rocky helment it also ends battles?

**Comment by Mikirae** [comment]
I tried for like 20 minutes to reproduce the ferrothorn rocky helmet thing. I couldn't make the battle end no matter what I did. That was on 9.0.4 though; did they not fix it in this version?

**Comment by ketl0rd** [comment]
Im not sure about the ferro and rocky helmet thing as i havent experienced it myself but it happened to someone else only a day or so ago. The sandstorm issue i have had occur to me multiple times since the updated

**Comment by Mikirae** [comment]
"Spawning in the void after a winning a battle in warzone"
What server does this happen on? I haven't touched the config

"/breed and /hatch commands going on cooldown if any mistake is put into the command. eg. putting in wrong slot. (this shouldn't even be a thing, getting punished for making a typing error)"
Pixelmon does not have a native cooldown that checks the successful running of the command anymore. I had to make my own cooldowns for all commands, and all it can tell is that the command was run.

"Legendary pokemon are spawning in the void in warzone."
I'll try to take a look at this when I can. Might be this weekend

All the rest of these are Pixelmon bugs, including ranch blocks being stuck at 10 even after we upped it.

**Comment by Mikirae** [comment]
I'll test Sandstorm, and see if I can reproduce the Ferrothorn thing again. But unfortunately they're Pixelmon bugs and I don't think we can do anything about them until they update :(

**Comment by ketl0rd** [comment]
The spawning in the void part happens on Rayquaza as far as im aware. Not all the time but it does happen sometimes. But yeah I've realised a lot of these issues are pixelmon sided issues which are out of your hands. Any idea when certain plugins such as GTS or regional breeding will be updated? 
Also another small bug is certain held items (might just be everstones) disappearing when being put on a mon for breeding, this just needs a relog for the item to show again but it's quite annoying

**Comment by Mikirae** [comment]
Alright, thanks for letting me know. I'll see what's different about Ray
than the others :)
GTS broke with 9.0.5 so I don't really know when that's getting updated.
What's Regional Breeding? I don't remember having a plugin called that

**Comment by ketl0rd** [comment]
I meant just being able to breed hisuian/galarian/alolan form mons. I have tried multiple different methods however no successful outcome. Just seems to not be working

**Comment by Mikirae** [comment]
Then unfortunately that would once again be a Pixelmon bug :(

**Comment by ketl0rd** [comment]
Ah yes just adding a few more things to the list lol (i believe most are pixelmon sided issues too)
- not being able to show pokemon/items in chat using commands {pokemon slot} or {item slot} 
- the aura preview section in spawn would be nice to be added back into the server as i have a lot of aura papers however i cant see what they look like before i apply them. (i know there was a section in spawn pre reset for this)

**Comment by Indorlan** [comment]
Showing ur team can be done with /show(1-6) or /showteam, Items I'm not sure how to

**Comment by ketl0rd** [comment]
Added 
- Certain moves on tutors are bugged (doesnt allow you to buy them ie. ice/thunder punch) 
- Dropping items from inventory causes them to disappear 

Also any news if raids will be made much more common/ other money make methods? Like how they were pre reset. Eco atm is terrible, no one has money to buy things or everyone is too scared to spend any money cos its hard to earn it
