### ISSUE TITLE
no shadow on aegislash

### ISSUE THREAD

**Issue by Warwickiscool** [SmashMC-Development/Bugs-and-Issues#1390]
aegislash had no shadow texture and i have a shadow aegislash

seems like all the servers have this problem

i want a shadow texture to be made

N/A

N/A

**Comment by Mikirae** [comment]
Aegislash has a texture. Please make sure you're on the latest version of our texture pack :) 
![image](https://user-images.githubusercontent.com/24925669/178892505-caf02c27-59ea-4d60-8e3d-5e5080525b26.png)
