### ISSUE TITLE
Colorcodes no longer usable on signs

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1391]
**Describe the Bug**
When you place a sign and work on the font, the colorcodes (&l, &c, &2 ect.) do not work anymore. Using "§" for colorcodes has no effect as it can't be typed in. Forcing it via crtl+v seems to work, however it afterwards gets resetted. 

**To Reproduce**
1. Place a sign
2. Make some fancy text with ampersand (&) + colorcode
3. Nothing happens

**Servers with the Bug**
At least Kyogre

**Expected behavior**
Being able to make fancy signs with colorcodes

**Additional context**
This worked prior to this wipe, while you could technically color the whole text with dye, it is not formatable anymore.

**Comment by Mikirae** [comment]
Sounds like you need a permission node for this. Not sure if that was a rank perm before but I swear it was locked behind a perm before

**Comment by DinglePringleUwU** [comment]
It surely was locked behind a rank perm.
I was not able to do it with [Trainer] rank or any other non-/buy ranks, but i was able to do it after i got [Legend] rank back then.
Sadly, i do not know if it was possible with [Mythic] or lower.

**Comment by DinglePringleUwU** [comment]
As an addendum here is a screenshot of me standing next to a few signs on my claim that i formated and colored with [Legend] Rank from December 25th 2021 (The last wipe).
You can see me writing in chat with Leg rank.

![2021-12-25_23 25 35](https://user-images.githubusercontent.com/94211853/179018980-493487f3-3459-4d8a-a5ce-9a692793833a.png)

**Comment by Paradis4432** [comment]
inactive

**Comment by Mikirae** [comment]
Fixed!!!!!!!!!!!!!!!!
