### ISSUE TITLE
Ender chest wipe

### ISSUE THREAD

**Issue by kavi212** [SmashMC-Development/Bugs-and-Issues#1392]
**Describe the Bug**
Dying in game wipes ender chest contents. I'm not sure if the method of death is relevant; but I was able to reproduce it 3/3 times via death from falling.

**To Reproduce**
1. Access ender chest via /echest and insert items.
2. Exit /echest and die 
3. Click respawn, type /echest and cry for your lost items

**Servers with the Bug**
I've only tested on Rayquaza, where it is bugged for sure.

**Expected behavior**
Ender chest should retain contents after the player dies.

**Screenshots**
Edit: Had to upload to youtube due to github's 10mb file limit: https://www.youtube.com/watch?v=2cSfVUsb0WQ

**Additional context**
N/A

**Comment by Mikirae** [comment]
Have you tried going to a physical ender chest? I heard that the items would be in there, but I'm not entirely sure if that's true.
Thank you for testing this, though! I'll see if I can get it fixed :)

**Comment by kavi212** [comment]
@Mikirae Yes, after encountering this, I made a support ticket on discord and was asked to try that. Physical ender chest was wiped; the contents are definitely being shared correctly, even after being wiped from this bug. And no prob! Let me know if there's anything else you need help testing.

**Comment by Paradis4432** [comment]
inactive
