### ISSUE TITLE
Specific Aura not working 

### ISSUE THREAD

**Issue by HelsbyJ** [SmashMC-Development/Bugs-and-Issues#1393]
The custom Auras have got set auras already on them, so you cannot choose the Aura that you would like instead of being able to choose the Aura. It is the same for Legendary and Non-Legendary
![Auras](https://user-images.githubusercontent.com/99360814/178848102-8e81e731-63e7-40b9-9320-fb9399c9fd86.png)
.

**Comment by Mikirae** [comment]
I don't think I changed that. Do you know if it was like that before reset?

**Comment by jantjewieger** [comment]
This has been fixed now!
