### ISSUE TITLE
Pokeball problem

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#1394]
**Describe the Bug**
When I use a pokeball to catch a Pokémon, it took more than 1 pokeball each time.

**Servers with the Bug**
Groudon and probably other servers too.
**Expected behavior**
I expected it to use 1 pokeball when I use a pokeball to catch a Pokémon during battle but it took more than 1 each time.
**Screenshots**
https://user-images.githubusercontent.com/93119451/179219391-de316688-e09b-4715-960c-c87a8cfa15ce.MOV
**Additional context**
N/A

**Comment by Indorlan** [comment]
What you are using in that clip is a repeat ball which does not have a 100% catch ratio but rather a 3.5x catch rate modifier if used on a pokemon that was caught once before by you, otherwise it has a 1x catch modifier.
Only Masterball and Park ball have a 100% chance of catching pokemon far as I'm aware.

**Comment by ColonCrusader** [comment]
![07F32778-5A0D-464C-86C2-FBA222BD2E83](https://user-images.githubusercontent.com/92840415/179313072-d36aa0ef-cae0-46f7-81c8-1694ae50b8cd.jpeg)

**Comment by WorkableSutoresu** [comment]
That's not what I meant by it took more than 1 pokeball guys :|
I meant that I use 1 pokeball but the game took more than 1 pokeball

**Comment by WorkableSutoresu** [comment]
Did you guys not see that the repeat ball Amount went from 954 to 951 instead of 953

**Comment by Indorlan** [comment]
I knew that... Blame m1
But Fr that seems pixelmon issue

**Comment by Mikirae** [comment]
I'm wondering if it was because it was in a Shulker Box or something. It might be pulling one from every available inventory source

**Comment by Mikirae** [comment]
Any idea on how to have this happen consistently? I tried it with PokeBags and Shulker Boxes and neither one had issues
