### ISSUE TITLE
Spawn in wz got stuck in blocks

### ISSUE THREAD

**Issue by nitrolonely69** [SmashMC-Development/Bugs-and-Issues#1395]
when i pay to go in wz it was for 8 min 30 sec but when i got tp it spawned me in lime glass block ,i cant get out from it. may i get my money back? (groudon)
![Screenshot 2022-07-17 204907](https://user-images.githubusercontent.com/109467435/179399226-45b56717-7f71-477d-946d-79bbc7f07764.png)

**Comment by nitrolonely69** [comment]
i got video but file is too big :P

**Comment by Mikirae** [comment]
Don't suppose you have a picture of the exact coordinates? 😳
