### ISSUE TITLE
new /show command can be abused

### ISSUE THREAD

**Issue by ernoooo** [SmashMC-Development/Bugs-and-Issues#1396]
**Describe the Bug**
You can also use /show1 on eggs and it shows you the IVs etc..

**To Reproduce**
1. /showx on a egg in your slot
2. shows IVs in chat

**Servers with the Bug**
Just tried it on Reshiram, don't know about the other server

**Expected behavior**
Showing IVs from eggs makes the purpose of hatching quite boring

**Screenshots**
'N/A'

**Additional context**
'N/A'

**Comment by twizzy0** [comment]
then just don’t look at the ivs tf lmao.

**Comment by DinglePringleUwU** [comment]
Same on Kyogre. Kinda spammy and defeats the purpose of /show as the shown mons are irrelevant too look at. 95% of all times its used its eggs.

**Comment by Mikirae** [comment]
Suggesting it to the dev :) Nothing I can do right now, unfortunately :(

**Comment by Paradis4432** [comment]
inactive
