### ISSUE TITLE
Killed Mega Metagross Boss, Got no items

### ISSUE THREAD

**Issue by LokeiBaoe** [SmashMC-Development/Bugs-and-Issues#1397]
I killed the boss in the sky and was in water afterwards, I never got the pop up for items, as well as the pop up to choose my mega keystone. This was the first mega boss I've killed and I didn't get anything.

1. Flew on pokemon
2. Entered battle with Mega Metagross Legendary Boss
3. Killed Boss
4. No Pop ups for Mega Keystone or items

Groudon Server

I expected to get my Mega Keystone Bracelet, as well as a Metagross Mega Stone and some other item.

N/A

N/a

**Comment by Mikirae** [comment]
This is a known pixelmon bug. Please open a ticket in the Discord and they can get your items back. Thank you for reporting!
