### ISSUE TITLE
Outdated server descriptions

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1398]
**Describe the Bug**
When in hub, if you hover over the servers, you get a description of them. It's a bit outdated, it says we are on 9.0.2, we are on 9.0.5 as of writing this

**To Reproduce**
1. get to the hub
2. hover over the server heads
3. see the issue

**Servers with the Bug**
hub

**Expected behavior**
Should be 9.0.5, instead of 9.0.2 

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/179766481-fb60d974-a30e-465e-9d9c-0bf68387dde5.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
FIXED FOR NEXT LOBBY RESTARTS. THANK YOU KIND SIR
