### ISSUE TITLE
Typo in smash games

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1399]
**Describe the Bug**
The pokemon "Budew" is mistyped as "Budewr" in the pokedex number smash game.

**To Reproduce**
1. See Screenshot

**Servers with the Bug**
All pixelmon servers

**Expected behavior**
No typo

**Screenshots**
![2022-07-19_16 43 43](https://user-images.githubusercontent.com/94211853/179780347-a7cdc9b6-1d9e-494e-b386-daac48198107.png)

**Comment by Superfire96** [comment]
Fixed
