### ISSUE TITLE
remove boss spawn msg from chat

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#140]
**Describe the Bug**
whenever a boss spawns, a message will appear in chat (for admin+) about it

**To Reproduce**
be admin+ and have a boss spawn somewhere randomly in the world

**Servers with the Bug**
all

![image](https://user-images.githubusercontent.com/82659374/118987478-94e63780-b980-11eb-8946-bf2b8f1b365c.png)

**Comment by HackuJacku** [comment]
Fixed from next reboot.
