### ISSUE TITLE
MissingNo spawns in the wild?

### ISSUE THREAD

**Issue by SpikeZaharr** [SmashMC-Development/Bugs-and-Issues#1400]
**Describe the Bug**
A wild lvl 13 MissingNo spawned in a swamp biome in the wild
**To Reproduce**
1. Go to swamp biome
2. It spawns?

**Servers with the Bug**
Please provide a list of which servers have this bug.
Groudon
**Expected behavior**
Was literally doing nothing and being chill
**Screenshots**
![2022-07-19_08 19 43](https://user-images.githubusercontent.com/93986034/179853595-659f5273-ecaa-4cdc-a3e2-3194bc4d138e.png)

**Additional context**
MissingNo is dangerous in the hands of the wrong people, using it in battle can corrupt others pokemon and mess with them.

Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Was fixed
