### ISSUE TITLE
Pokemon arent spawning on rayquaza server 

### ISSUE THREAD

**Issue by BiggyGumpIsHere** [SmashMC-Development/Bugs-and-Issues#1401]
Just recently yesterday and today Pokémon in the wild haven't been spawning and I tried to fix it by uninstalling Minecraft and the mod and even deleted the server but it still stays the same whenever you can tell me how to fix it so I can try and catch Pokémon in the wild thankyou and have a great night.

**Comment by jantjewieger** [comment]
This is unfortunately a pixelmon bug and not something we can fix on our end. If you wait a bit they will spawn eventually. Another option is to go to warzone. Closing this up as we cannot fix this issue
