### ISSUE TITLE
my items was taken in wz bank

### ISSUE THREAD

**Issue by nitrolonely69** [SmashMC-Development/Bugs-and-Issues#1402]
i had my masterballs in shellbox and was bringing them into wz then suddenly when im in its all lost after timer runs out i check my bank and it was there :P idk if this is a 
![20220722_173942](https://user-images.githubusercontent.com/109467435/180413047-b3cb18e0-9754-468e-83e2-b383c4ab8577.jpg)
bug or js not allowed - groudon server

**Comment by Paradis4432** [comment]
inactive
