### ISSUE TITLE
/shop TMs and TRs prices are wrong

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Bugs-and-Issues#1403]
As the title says, the prices for both TMs and TRs are doubled, and for some 2.5x

An example of this is the TM Fire Punch which cost only 2k in /warp mart, but cost 4k in /shop. Im pretty sure all of them are in the wrong prices, like Trick Room, Hidden Power, Thunderbolt, etc.

So far this is happening on Reshiram, but im pretty sure its happening on other servers as well.

*EDIT*
Apparently this is happening to all servers as well

**Comment by Superfire96** [comment]
Fixed
