### ISSUE TITLE
/wiki command is non-existant

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Bugs-and-Issues#1404]
As the title suggests, the usage of /wiki is not working at all, despite the changelog for SmashMC showing it SHOULD be working. Whenever I type out /wiki, it says "unknown command"

This is happening to ALL servers btw

**Comment by Mikirae** [comment]
Welp, that's really weird. I guess I either forgot to upload it, or my file transfer program hates me.
Fixed for next restart. Thank you!
