### ISSUE TITLE
fossile mushines are broken

### ISSUE THREAD

**Issue by yeeterbro205** [SmashMC-Development/Bugs-and-Issues#1405]
**Describe the Bug the fossil mushiness don't work and I got my fossil stuck in one for a bit then got it out
A clear and concise description of what the bug is. it doesn't let you make your fossil back to life

**To Reproduce**
1. Go to the fossil mushing
2. Click on it it dissent work

**Servers with the Bug**
Please provide a list of which servers have this bug. groudon is the only one i know its on

**Comment by Mikirae** [comment]
Pretty sure that the fossil machines work, but the fossil in them is invisible and you have to wait a while

**Comment by Superfire96** [comment]
This is not an issue on our end, as Mikirae said, the fossil is invisible and you have to wait a bit and then take it out
