### ISSUE TITLE
Warzone Rep Decay

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1406]
**Describe the Bug**
Some people losing more warzone rep than others/people don't lose warzone rep

**To Reproduce**
1. Any server
2. Fight in warzone
3. Gain Rep
4. Not be on and see it decay while others doesn't despite them not going to warzone

**Servers with the Bug**
Seen on Kyurem but could be all

**Expected behavior**
Everyone's rep should decay

**Screenshots**
Player has been at 1011 for the last 53hours unchanged
![image](https://user-images.githubusercontent.com/84816052/180514737-ec3fe13a-cab5-4ae0-91d0-5d1799a14152.png)

I have lost 16 in around 24hours
![image](https://user-images.githubusercontent.com/84816052/180514795-db266d5e-ef91-426e-b580-b3248869ca1a.png)

**Additional context**

**Comment by Mikirae** [comment]
I think it does days since last entering Warzone
When was the last time you were in Warzone? Should tick down after 5 days of not being in it

**Comment by M1n0j** [comment]
I had last been in warzone around 24hours before I lost the rep

**Comment by Mikirae** [comment]
I sent it to the dev!!!!
