### ISSUE TITLE
How do i ban appeal, i am banned from the discord server

### ISSUE THREAD

**Issue by CreeperGame7810** [SmashMC-Development/Bugs-and-Issues#1407]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
https://pokesmash.enjin.com/banappeal
Post it here :)
