### ISSUE TITLE
Getting stuck in Warzone

### ISSUE THREAD

**Issue by Bazza50cal** [SmashMC-Development/Bugs-and-Issues#1408]
**Describe the Bug**
A clear and concise description of what the bug is. so I spawned in warzone and within 30 seconds i fell down a hole and couldnt get out, with teleport or wait for my time to finish. which isnt good when u wanted to catch pokemon

**To Reproduce**
1. Go to warzone
2. Walk
3. fall down
4. get stuck
5.Coord . **X 54.300 Y 89.00000 Z 137. 300** 
**Servers with the Bug**
Please provide a list of which servers have this bug. just Pixelmon warzone, not sure if its all servers but at least Kyrogre

**Expected behavior**
A clear and concise description of what you expected to happen. i expected  not to get stuck with no way out 

**Screenshots**

![2022-07-22_11 10 46](https://user-images.githubusercontent.com/109873974/180619900-8c9b7e05-338e-496a-a81f-121c64807d18.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
The Warzone changed up, so this isn't an issue anymore haha.
Thank you for reporting it :) Saw it when you first posted it but don't remember if we ever got around to fixing it
