### ISSUE TITLE
Mega Evolving Rayquaza

### ISSUE THREAD

**Issue by Lakelukelake** [SmashMC-Development/Bugs-and-Issues#1410]
**Describe the Bug**
My Rayquaza while knowing Dragon Ascent cannot be evolved after clicking the mega stone between the 4 moves during combat.

**To Reproduce**
1. Enter battle with the Rayquaza knowing Dragon Ascent
2. Click on the mega stone icon in the middle of the 4 moves to choose.
3. Click on a move.
4. See that your Rayquaza is not mega evolving.

**Servers with the Bug**
Seen on Groudon but probably all.

**Expected behavior**
Rayquaza to mega evolve during battle.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Seems to be a Pixelmon bug, unfortunately. Thank you for reporting!
