### ISSUE TITLE
smashgames

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1411]
**Describe the Bug**
Some questions, from chatgames, have the answer in the description question instead of 3 underscores. I know Conkeldurr and Shinx are like that

**To Reproduce**
1. Go to any server
2. have the description chatgame of conkeldurr or shinx
3. see error

**Servers with the Bug**
all i assume

**Expected behavior**
I'd expect the name to be replaced by 3 underscores

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/180896968-6f41b507-5692-4181-8d35-44c6f6fa5789.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
I fixed it for Swadloon, Lumineon, Conkeldurr, and Shinx

**Comment by jantjewieger** [comment]
closing bc miki said fixed lol
