### ISSUE TITLE
Walk speed

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1412]
**Describe the Bug**
This is really weird.
So basically, I loaded onto pixelmon, and I noticed I was running really fast, I thought it was just my thunderstone armor, but it turns out it was just my character. So yeah I have 0 clue what could have caused it, I've relogged, still hasn't gone away.

**To Reproduce**
1. Join the server
2. your walkspeed is weird

**Servers with the Bug**
Happened on reshiram, not sure if it's on other servers

**Expected behavior**
Probably should be a normal speed xD

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/181111001-fc1666c7-2cda-40fb-9cb1-62b2704d133c.png)
Won't let me send video because too big ;-; DM me for the video please

**Additional context**
N/A

**Comment by Mikirae** [comment]
I'm pretty sure that Thunderstone armor has been bugged for like all of time with giving you speed even after you remove it

**Comment by WalkAway7** [comment]
I mean I got the same message on another server, and I don't have tstone on that server

**Comment by Mikirae** [comment]
Default walk speed is 2 tho unless I’m misremembering the picture

**Comment by WalkAway7** [comment]
I can send you the clip if you want, the walk can't be normal lmao

**Comment by Archie4690** [comment]
It is your name. It is a curse.

**Comment by Mikirae** [comment]
Is it on all servers that the walking speed is bugged? Because this
genuinely sounds like a Pixelmon thing. See if it's bugged in single player
too

**Comment by WalkAway7** [comment]
Tested on all servers, is happening to me on them. Tested on singleplayer, and I walk normally

**Comment by Mikirae** [comment]
Going to cry. Just to be sure, you're not wearing the boots? You spawn with
them on all servers

**Comment by WalkAway7** [comment]
Yes extremely sure. I can send you a clip

**Comment by Superfire96** [comment]
Fixed
