### ISSUE TITLE
Enjin ban appeal not working 

### ISSUE THREAD

**Issue by CreeperGame7810** [SmashMC-Development/Bugs-and-Issues#1413]
**Describe the Bug**
Hey, im CreeperGame7810 from the discord my social and gaming accounts
 have been hijacked from idk where, it happened already when i played roblox, and it happened again, i already made an issue that Mikirae the goat responded with a link to enjin ban appeal, i have clicked the link and it didnt lemme do anything, it just showed an unknown error

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
https://pokesmash.enjin.com/banappeal
Login or Register and then make your appeal
