### ISSUE TITLE
Catching pokemon over the void in ultra space 

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1414]
**Describe the Bug**
If you attempt to catch a pokemon over the void while in ultra space, the ball will just fall and it will not begin the catching animation / process. I believe this is due to the pokeball having to hit the ground before it is able to catch, and due to there being no ground in the void, the ball just falls for eternity, and so it never actually catches the pokemon. 

**To Reproduce**
1. Go to ultra space
2. Try to catch a pokemon over the void 
3. See error

**Servers with the Bug**
All

**Expected behavior**
Should catch despite being over the void 

**Screenshots**
N/A atm

**Comment by Mikirae** [comment]
THIS IS A PIXELMON BUG BUT I HAVE REPORTED IT
