### ISSUE TITLE
foreign characters

### ISSUE THREAD

**Issue by ColonCrusader** [SmashMC-Development/Bugs-and-Issues#1415]
the trivia questions about Flabebe counts it incorrect if you don't use foreign letters

reshiram, assuming other servers as well
![image_2022-07-31_172907445](https://user-images.githubusercontent.com/92840415/182046063-14abe0b5-9c31-441b-a17e-d5a1bcac97ac.png)

**Comment by Mikirae** [comment]
Super has fixed this for next restart. Thank you for reporting :D
