### ISSUE TITLE
non sellable items

### ISSUE THREAD

**Issue by ColonCrusader** [SmashMC-Development/Bugs-and-Issues#1416]
Porkchops where previously able to be sold, but are not anymore and im not sure why. also slowpoke tails say "sellable to shop keepers" but can not be sold.

reshiram, pretty sure the others as well

to be able to sell these items

**Comment by jantjewieger** [comment]
The slowpoke tails is up to the managers, although personally i'd also like to seem them be sellable of course, but we will not be adding the porkchops back to the list of sellable items as some people were abusing that feature

**Comment by ColonCrusader** [comment]
dang, that sucks about the porkchops, but i would really love to see solwpoke tails sellable

**Comment by Mikirae** [comment]
Super has made it so Slowpoke Tails are sellable to the shop for next restart :)
