### ISSUE TITLE
/vaults /backpack /backpacks won't work.

### ISSUE THREAD

**Issue by Badbush** [SmashMC-Development/Bugs-and-Issues#1417]
When I enter /vaults or /backpack command it says, UBackPack | You dont have permission for this.
When I enter /backpacks it brings up an extra inventory but nothing can be put into it.

**To Reproduce**

**Servers with the Bug**
Smash MC groudon

**Expected behavior**
To have extra inventory space.

**Screenshots**
![2022-08-01_13 27 33](https://user-images.githubusercontent.com/110419012/182213269-bb64876c-615d-41d8-b60d-fb86954fbe3c.png)
![2022-08-01_13 27 28](https://user-images.githubusercontent.com/110419012/182213304-b4bbd99a-948c-4fd8-8a7e-168b7de34409.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
What rank do you have? You need to be a donator rank to get them right now, I believe

**Comment by Badbush** [comment]
Oh well your Expert rank at 25% dex advertises it so...

**Comment by Superfire96** [comment]
Fixed
