### ISSUE TITLE
Impossible Pokehunts

### ISSUE THREAD

**Issue by ColonCrusader** [SmashMC-Development/Bugs-and-Issues#1418]
Some of the pokehunts are literally impossible, not like really really hard, like, actually impossible

reshiram

to be able to complete all hunts
![image_2022-08-02_143856383](https://user-images.githubusercontent.com/92840415/182449138-5aaac852-bf66-48fd-b2dc-1b4f1973b08a.png)

**Comment by Mikirae** [comment]
Does Hatenna not spawn?
I can try to make a blacklist of all Pokemon that don't spawn some time

**Comment by ColonCrusader** [comment]
Its not a issue of hattena not spawning its the fact it has a 100% female gender ratio, i can provide a list of pokemon thst have 100% gender ratio for one or the ither gender

**Comment by ColonCrusader** [comment]
Please note that i have not seen all of these pokemon bugged in pokehunt, these are just pokemon with 100% in one gender, also please note this list does not contain genderless pokemon.
NidoranMale 100% male
NidoranFemale 100% female
Nidorino 100% male
Nidoraina 100% female
Nidoking 100% male
Nidoqueen 100% female
Hitmonlee 100% male
Hitmonchan 100% male
Hitmontop 100% male
Happiny 100% female
Chansey 100% female
Blissey 100% female
Kangaskhan 100% female
Smoochum 100% female
Jynx 100% female
Tauros 100% male
miltank 100% female
Volbeat 100% male
Illumise 100% female
Latias 100% female
Latios 100% male
Wormadam 100% female
Mothim 100% male
Vespiquen 100% female
Gallade 100% male
Froslass 100% female
Cresselia 100% female
Throh 100% male
Sawk 100% male
Lilligant 100% female
Braviary 100% male
Mandibuzz 100% female
Tornadus 100% male
Landorus 100% male
Thunderus 100% male
Flabebe 100% female
Floette 100% female
Florges 100% female
Salazzle 100% female
Bounsweet 100% female
Steenee 100% female
Tsareena 100% female
Hattena 100% female
Hattrem 100% female
Hatterene 100% female
Impidimp 100% male
Morgrim 100% male
Grimmsnarl 100% male
Alcremie 100% female

**Comment by Mikirae** [comment]
These are fixed for the next restart. Thank you :D
