### ISSUE TITLE
Trading Machines

### ISSUE THREAD

**Issue by sjhaalki** [SmashMC-Development/Bugs-and-Issues#142]
**Describe the Bug**
When trying to trade pokemon with the trading machine, the other user has no pokemon inserted, even though he did and already pressed ready. Can't press ready myself since the machine doesn't register his pokemon though

**To Reproduce**
1. Go to a trading machine
2. Insert the pokemon
3. Try to press ready and see that it doesn't work
4. See that the other user is already ready, but you can't see the pokemon he inserted

**Servers with the Bug**
Darkrai

**Expected behavior**
Usually you would see both your own and the other users pokemon and would be able to press "ready" so you could trade.

**Screenshots**
![image](https://user-images.githubusercontent.com/28642699/118989121-112d4a80-b982-11eb-9e08-0d4c97861fea.png)

**Comment by Rasgnarok** [comment]
We don't have any custom handling on Trading Machines - it's a core Pixelmon mechanic. Please forward your (very) complete bug report to: https://www.pixelmonmod.com/tracker.php?p=2.
