### ISSUE TITLE
Pancham wont evolve

### ISSUE THREAD

**Issue by Orcus3** [SmashMC-Development/Bugs-and-Issues#1422]
Pancham won evolve, even when its reqiurements is met. (get to lvl 32 with a dark type in the party)

**Comment by M1n0j** [comment]
Hey @Orcus3, This is a Pixelmon bug which I have reported. (https://pixelmonmod.com/tracker.php?p=2&t=18954)
If you make a ticket on the discord we can evolve it for you!
