### ISSUE TITLE
HA rates

### ISSUE THREAD

**Issue by ColonCrusader** [SmashMC-Development/Bugs-and-Issues#1423]
So i know this isnt anything the server can control until a update comes around, but i at least think there should be a announcement on this as i have seen people asking about this

https://pixelmonmod.com/tracker.php?p=2&t=18684

**Comment by Mikirae** [comment]
The ticket is basically saying that the config option does nothing, meaning that it's the default rate, which is 1/150.

**Comment by ColonCrusader** [comment]
i personally don't feel that is entirely accurate, although i suppose i could be wrong, but after 2 weeks of 5 hours or more daily of ha hunting and checking ever single spawn, even ekans etc, and not seeing a single ha, i think they are bugged in general to not spawn
