### ISSUE TITLE
Battlepass issue

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#1424]
**Describe the Bug**
Battlepass not working correctly for Premium pass on Zekrom

**To Reproduce**
1. Go toZekrom with a store bought rank
2. open battle pass and get to lvl 10
3. see that its not accessible 

**Servers with the Bug**
Zekrom( my only store ranked server)

**Expected behavior**
Premium battle pass should be working properly for all donator ranks

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/183372512-58aafa16-4ff6-4174-a715-bed6b7ed1cb3.png)
![image](https://user-images.githubusercontent.com/82549364/183372573-ac246ea7-0217-4171-8571-bb51415754f4.png)

**Additional context**
n/a

**Comment by Superfire96** [comment]
Should be fixed, let me know!

**Comment by jantjewieger** [comment]
Can confirm this is fixed now! Closing this up
