### ISSUE TITLE
Can't use the trading machines in spawn

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1425]
**Describe the Bug**
Can't use the trading machines at spawn because it's in an admin claim

**To Reproduce**
1. Go to the pokecenter
2. try to use them
3. message shows saying that it's in an admin claim

**Servers with the Bug**
Groudon, may be on other servers however

**Expected behavior**
You should be able to use them

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/183441851-8a609323-f8b2-4817-b4dd-9f6968f7e2ff.png)
![image](https://user-images.githubusercontent.com/89798207/183441891-68d7fc28-96f0-4a36-94e3-549954472523.png)

**Additional context**
This was made as a result of ticket ID 51794.

**Comment by Superfire96** [comment]
Fixed
