### ISSUE TITLE
there are no pokemon spawning on the rayquaza server

### ISSUE THREAD

**Issue by ZjentoS** [SmashMC-Development/Bugs-and-Issues#1426]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jantjewieger** [comment]
This is unfortunately a bug on pixelmon's end and not something we can control. If you wait in the same area for a bit they will spawn eventually. Closing this up as there is nothing else we can do here
