### ISSUE TITLE
The Custom ScoreBoard is broken on Ray in Spawn and Warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#1428]
**Describe the Bug**
The custom scoreboard looks to be on default on Rayquaza spawn and warzone

**To Reproduce**
1. Go to Ray
2. Go to spawn or warzone
4. See it being wrong

**Servers with the Bug**
Seen on Ray

**Expected behavior**
Should be showing the correct info

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/184019833-3e2c8f90-8e60-4469-92bb-9f201c97f4be.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Sir did Archie ever fix this?

**Comment by Mikirae** [comment]
Screw you I am closing this and have fun in UK!!!!!!!
