### ISSUE TITLE
well, there isn't really a bug with the Pixelmon Mod. But, Probably the Server itself. everytime i break some block i can't pick one of them up. also with trees. example: I break the Logs from the Trees, the Leaves brake and give me saplings and sticks. but, sometimes i just can't pick them up and they glitch not letting me pick em up.

### ISSUE THREAD

**Issue by EmelEpiqGamer** [SmashMC-Development/Bugs-and-Issues#1429]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Sounds like a desync between the client and the server. If you relog, you should be able to pick them up just fine :)
This has been an issue in Minecraft for like as long as I've played it which is like 5 years
