### ISSUE TITLE
Buymove Bug

### ISSUE THREAD

**Issue by Blxgdenn** [SmashMC-Development/Bugs-and-Issues#143]
**Describe the Bug**
Buymove Pokemon

**To Reproduce**
Slowpoke line cannot learn teleport
Blaziken can't learn Close combat
Swampert Can't learn liquidation
When trying to teach Scale shot to garchomp it says "You cannot afford this" when I have 1.8mil

**Comment by Rasgnarok** [comment]
Duplicate, closing in favour of https://github.com/SmashMC-Development/Bugs-and-Issues/issues/133
