### ISSUE TITLE
Evolving Cubone to Alolan Marowak

### ISSUE THREAD

**Issue by Kakarott9000** [SmashMC-Development/Bugs-and-Issues#1430]
**Describe the Bug**
When I try to evolve cubone to alolan marowak with an alolan mon in party it evolves into an kanto marowak and gives it shadow bone as if its alolan
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jantjewieger** [comment]
This is unfortunately a pixelmon bug and not something we can fix. If you open a ticket one of our staff members can fix the issue for you. Closing this up as there's nothing we can do here
