### ISSUE TITLE
Sandstone not giving skills exp

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#1431]
**Describe the Bug**
when mining sandstone it snot giving skills exp

**To Reproduce**
1. Go to any server
2. try to mine sandstone
3. lament in not getting mining exp

**Servers with the Bug**
Zekrom ( mostlikely all)

**Expected behavior**
should be giving skills mining exp

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Fixed
