### ISSUE TITLE
Chat Sentry is STILL BROKEN

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#1432]
**Describe the Bug**
chat sentry is still broken flagging my messages of me typing the word fag, when i am infact not

**To Reproduce**
1. go to any server
2. type if 4 group or any f and g word on the sides of the 4 it flags as saying "Fag" ( see screenshot for message typed)

**Servers with the Bug**
ALL

**Expected behavior**
chat sentry should be better coded to actually look for the words properly rather than doing it by chains of words

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/184542903-e0af4ae8-1bb9-4314-95b1-9b4d3948f67c.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This should be fixed on next restart :)
