### ISSUE TITLE
Andesite,Granite,Diorite,other minecraft/pixelmon blocks not  giving Skill exp

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#1433]
**Describe the Bug**
 Minecraft blocks and pixelmon blocks not giving skill exp.
**To Reproduce**
1. Go to and server
2. try to mine andesite, diorite,ect... Platimun, and try smelting them and not get exp

**Servers with the Bug**
all

**Expected behavior**
should give some form of exp
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Fixed for next restart. Thank you kind sir
