### ISSUE TITLE
Server-Rayquaza For some reason the pokemon toxel will not evolve when level is reached. I have tried multiple times with other toxels it still wont work.

### ISSUE THREAD

**Issue by ZjentoS** [SmashMC-Development/Bugs-and-Issues#1434]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by M1n0j** [comment]
Hey @ZjentoS, This is a Pixelmon bug which I have reported. https://pixelmonmod.com/tracker.php?p=2&t=18953
