### ISSUE TITLE
Breeding bug

### ISSUE THREAD

**Issue by Badbush** [SmashMC-Development/Bugs-and-Issues#1435]
**Describe the Bug**
The only mons I cannot breed successfully are Scyther.

**To Reproduce**
filled up every slot in the day care except for one.  put in the male and female scyther and no option to insert materials popped up, just a red X and a red circle with a line through it.

**Servers with the Bug**
Groudon

**Expected behavior**
filled up every slot in the day care except for one.  put in the male and female scyther and no option to insert materials popped up, just a red X and a red circle with a line through it.

**Screenshots**

![2022-08-15_20 17 56](https://user-images.githubusercontent.com/110419012/184757602-fd39cb5f-b358-46ae-a69d-59e77e3ff640.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This should be fixed on next restart :)
