### ISSUE TITLE
Night vision wz

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1436]
**Describe the Bug**
With the latest update the warzone no longer gives a permanent night vision boost. With the wz map being quite big and it being very hard to light it up its getting very dark in there, especially if it's night time

**To Reproduce**
1. Go to warzone
2. Expect night vision
3. Don't get permanent night vision while in wz

**Servers with the Bug**
Reshi but I assume all?

**Expected behavior**
I'd expect there to be night vision

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
We didn't touch night vision, so I don't think it was in the other one either. I should be able to give it though

**Comment by Superfire96** [comment]
NightVision was added!!!!!!!
