### ISSUE TITLE
dexrank vault

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1437]
**Describe the Bug**
Right now the description for dex ranks says you get a vault. however, dex ranks don't give you a backpack or a vault so the description needs to be updated.

**To Reproduce**
1. collect mons
2. get to at least 25% dex
3. see description (see pic)

**Servers with the Bug**
All

**Expected behavior**
I'd expect the rank description to be correct

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/184904078-a76cbfdb-53fe-4c23-bf80-d5a0ebbfe69a.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
