### ISSUE TITLE
Crate Giving Wrong Reward that has been announced. 

### ISSUE THREAD

**Issue by eboyJay69** [SmashMC-Development/Bugs-and-Issues#1439]
**Describe the Bug**
Open a epic crate key, and received the wrong reward that it announced 

**To Reproduce**
1. Buy epic crate key
2. Open epic crate key
3. Get the reward "Non-legendary shiny convert and Non-legendary Resize"
4. Receive the non-legendary shiny convert, but receive a non-legendary pokeball change instead of the resize. 

**Servers with the Bug**
Reshiram is where I open the crate 

**Expected behavior**
Make it give the right reward

**Additional context**
Ticket 52374 has addition context.

**Comment by Archie4690** [comment]
@eboyJay69, I am really good and I have fixed this.
