### ISSUE TITLE
Porygon Not Evolving 

### ISSUE THREAD

**Issue by Kakarott9000** [SmashMC-Development/Bugs-and-Issues#1440]
**Describe the Bug**
When I try to /tradesim my porygon with the up-grade on it. It says complete but the porygon dont evolve. I just need it for my dex entry. And also snom isn't evolving either which i also need for dex
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by M1n0j** [comment]
Hey @Kakarott9000, this is unfortunately a Pixelmon Bug that we dont have control over. I have made a Pixelmon Mod Tracker bug report thing https://pixelmonmod.com/tracker.php?p=2&t=18952
