### ISSUE TITLE
Breeding skill not working

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#1441]
**Describe the Bug**
Breeding skill not giving exp upon hatching eggs

**To Reproduce**
1. any server
2. hatch egg
3. scream internally at not getting breeding exp

**Servers with the Bug**
Zekrom( possibly all)

**Expected behavior**
Eggs hatched should be giving exp for breeding skill.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Should be fixed
