### ISSUE TITLE
Wz bug getting loses in stats because of someone leaving

### ISSUE THREAD

**Issue by DerBratinaBratan** [SmashMC-Development/Bugs-and-Issues#1442]
I went in Wz to battle some ppl at a time no helper or mod was online or atleast noone did my ticket i created,
i battled some guy, we got stuck in battle (i made a ticket as i wrote above) but noone was there to unstuck us.
So we just agreed because i would have one anyways and i just cared about my stats, that he just altf4 out of the game and i will give him back his pokemon.
everything good?
no because if someone leaves a fight in wz due connection lose or closing the game, the other who wins gets a lose also
i found out about it after the 4th time i did that.
I was checking my stats and i had 4 loses tho i never lost in Wz

**Comment by Mikirae** [comment]
Thank you for the report! This has been fixed for next restart :D
