### ISSUE TITLE
you cant breed some pokemon

### ISSUE THREAD

**Issue by DerBratinaBratan** [SmashMC-Development/Bugs-and-Issues#1443]
Hello,
I have a problem with the new breedingsystem,
before i was breeding scizor and the new sneasler
now with the new update i cant breed scizor anymore and if i breed Sneasler i get the normal sneasle

**Comment by Archie4690** [comment]
Hello @DerBratinaBratan, unfortunately these bugs are not resolvable by us. It is an issue that needs to be fixed by Pixelmon itself.  Throughout the future versions of pixelmon this bug should be fixed but unfortunately you will have to be patient with this issue.

**Comment by jantjewieger** [comment]
Closing this up as its a pixelmon issue
