### ISSUE TITLE
Finding the Endportal

### ISSUE THREAD

**Issue by DerBratinaBratan** [SmashMC-Development/Bugs-and-Issues#1444]
If you use Endereyes to find the Endportal in the overworld it wont lead you to one
it just leads you into nothing

**Comment by Archie4690** [comment]
Hey @DerBratinaBratan, on the server currently the overworld does not match up to the seed. This means that eyes of ender will not link up correctly. if you want to do to the end then you can do /warp End

**Comment by Superfire96** [comment]
Closing this up as this is not something that we can fix, make sure to use the warps!
