### ISSUE TITLE
Spawns

### ISSUE THREAD

**Issue by Greninja250** [SmashMC-Development/Bugs-and-Issues#1445]
I am getting tired of waiting 20 minutes for one Pokémon to spawn. Please fix this issue because it's getting on my nerves and I'm not the only one.

**Comment by Mikirae** [comment]
We would absolutely love to fix this, and we have literally tried every possible thing, and we can't fix it. This is a Pixelmon bug that we have been going out of our way to try to get fixed. Believe us, we're as annoyed as you are.
