### ISSUE TITLE
No Pokemon are spawning

### ISSUE THREAD

**Issue by Racvel** [SmashMC-Development/Bugs-and-Issues#1446]
0 pokemon are spawning no matter what happens the only pokemon I see are trainer pokemon other ppl's pokemon and 0 wild pokemon are spawning at all no matter how long I wait

**Comment by Mikirae** [comment]
We would absolutely love to fix this, and we have literally tried every possible thing, and we can't fix it. This is a Pixelmon bug that we have been going out of our way to try to get fixed. Believe us, we're as annoyed as you are.
