### ISSUE TITLE
Small SmashGames Issue

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1447]
**Describe the Bug**
There is a small typo in the SmashGames "Who's that pokemon".
See Screenshot.

**To Reproduce**
1. Wait for this very specific Trivia to come up, or look it up in the files
2. Wait until its over
3. See that the answer is "Hariyama"" and not "Hariyama"

**Servers with the Bug**
At least Kyogre, likely all Servers.

**Expected behavior**
The answer should be without a "

**Screenshots**
![2022-08-21_16 42 44](https://user-images.githubusercontent.com/94211853/185797304-879551ad-a168-465b-bc3f-c861d593b419.png)

**Comment by Superfire96** [comment]
Fixed
