### ISSUE TITLE
Warzone End Battle Glitch

### ISSUE THREAD

**Issue by Twillight0420** [SmashMC-Development/Bugs-and-Issues#1448]
When you leave a battle with another Pokemon that spawned in Warzone, you will be sent back out of Warzone. (Don't know if the issue is only in Rayquaza but that's where it happened to me)

Video - https://youtu.be/9QtXkl12fqo

**Comment by Shoji007** [comment]
This is  affecting all servers. I just ran from a Togekiss on Zekrom and it booted me.

![image](https://user-images.githubusercontent.com/82549364/186019339-799f4fdc-23f1-4b4d-9bb4-f3cb0be135ea.png)

**Comment by Superfire96** [comment]
Was fixed
