### ISSUE TITLE
SmashGames Issue

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1449]
**Describe the Bug**
Smashgames trivia question about the 407th dex entry is faulty.
The answer "Roselia" is not true. The 407th dex entry is Roserade. 
See Screenshot.

**To Reproduce**
1. Wait for the specific question to come up
2. Insert answer: "Roserade"
3. See that set smashgame answer is "Roselia"
4. Feel Sad

**Servers with the Bug**
At least Kyogre, likely all with the plugin

**Expected behavior**
The true answer should be "Roserade".

**Screenshots**
![2022-08-22_22 23 34](https://user-images.githubusercontent.com/94211853/186012821-cb46f979-317e-4455-8733-a537c10931be.png)

**Comment by Superfire96** [comment]
Fixed
