### ISSUE TITLE
/endbattle allows u to steal in wz

### ISSUE THREAD

**Issue by br183adl** [SmashMC-Development/Bugs-and-Issues#145]
**Describe the Bug**
when endbattling in wz it gives the person a chance to steal using the command ./endbattle

**To Reproduce**
using the command ./endbattle in wz

**Servers with the Bug**
Please provide a list of which servers have this bug.
giratina could possibly be all

**Expected behavior**
so players can not steal after a staff endbattle

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
`/endbattle` determines the winner of the battle based on the number of remaining Pokémon remaining. If the remaining Pokémon are equal, the HP percentage will be a tie breaker.

Is this command still able to be used in the Warzone? If so, which servers please?

**Comment by br183adl** [comment]
okay so sorry for the late response the bug was not clear at all in this report my apologies so when a helper end battle someone that was in waiting it would let one person steal as if they had lost the battle I can check this out and test if this is still a glitch but as there has been no more reports on it I presume it is not but I will go through and test it all right now

**Comment by HackuJacku** [comment]
Fixed on reset
