### ISSUE TITLE
Max Claim Issue

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1450]
**Describe the Bug**
A Rank from the /Dex Ranks is overwriting the max amount of claims a player can have from /buy ranks.

**To Reproduce**
1. Get Smash Rank
2. Get a Dex Rank afterwards (In my case it was the "Ultra" Rank)
3. Try to make more than three claims.

**Servers with the Bug**
At least Kyogre, likely more as i heard from many players with /buy ranks that they only have 3 claims.

**Expected behavior**
To get the right amount of /claims with bought ranks.

**Additional context**
I started playing with [Trainer] Rank and got the 25% Rank afterwards
Then i i got the 50% Rank
Then i bought the Smash Rank
Then i got the 75% Rank (Ultra)
All that was roughly two months ago. After making a ticket on the DC it was suggested that the max. claims might have been overwritten by the Dex Rank. There are other players with the same issue.

**Comment by Mikirae** [comment]
Just to be clear, did you *ever* have the proper amount of claims? That will help me in figuring things out

**Comment by DinglePringleUwU** [comment]
Sorry for the late respons.
No, i never had the proper amount.
But my time-window in between getting smash rank and ultra rank was rather short, so i did not really had a chance to test this. As with other smash ranks, most have the right amount of claims.
A friend of mine does not have this issue, but they also never got above 25% Dex. They have their smash rank from the last resets.

**Comment by DinglePringleUwU** [comment]
Sorry for bumping, this issue is still a thing as of today and the max claim amount is still locked at three.

**Comment by Paradis4432** [comment]
fixed inactive

**Comment by DinglePringleUwU** [comment]
> fixed inactive

![2023-08-31_00 10 03](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/94211853/5e150e02-ffde-4a0a-9418-feb7fe79ebbc)
Checked in today on the server to see if it was fixed, its not fixed.
