### ISSUE TITLE
Cant evolve my Piloswine into Mamoswine. 

### ISSUE THREAD

**Issue by JujuTheMF** [SmashMC-Development/Bugs-and-Issues#1451]
I Just recently taught my piloswine aicent power so i could evolve it. leveled up from level 63 to 66 with no evolve while knowing the move 
![image](https://user-images.githubusercontent.com/111854696/186103152-656200ab-efad-435e-9330-832b3851a317.png)
 and as you can see in the following screenshot i went from 66 to 67 and still bnothing
 
![image](https://user-images.githubusercontent.com/111854696/186103596-283e5766-ea2e-4734-84a5-218f94e04ee5.png)

**Comment by M1n0j** [comment]
Hey @JujuTheMF, If you make a ticket on the Discord we can evolve it for you. This is an issue on our end that will be fixed soon!

**Comment by Mikirae** [comment]
This should be fixed since we've fixed up some files :)
