### ISSUE TITLE
Missing NPC

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1453]
**Describe the Bug**
Kyogre's Mart is missing a "Potion" Npc. The one that sells potions and PP Ups/Max.

**To Reproduce**
1. Go to /warp mart
2. Search for Potions NPC.
3. There is no NPC.

**Servers with the Bug**
Only Kyogre.

**Expected behavior**
Have a "Potions" NPC there like on the rest of the servers.

**Comment by Superfire96** [comment]
Added
