### ISSUE TITLE
MasterBall LootTable is bugged

### ISSUE THREAD

**Issue by misterhoo77** [SmashMC-Development/Bugs-and-Issues#1455]
I clicked on a masterball loot, it gave me "Air" and said "Your inventory is full! Air was dropped on the ground!" and then said "You found one tile.poke-chest!" instead of giving me an item

I think you should just look in the loot tables or i guess try a thousand times to open master ball loots for that to happen

smashmc

i expected me to get an item from the masterball loot

![immagine](https://user-images.githubusercontent.com/111984511/186425387-0e78a3e1-cf06-4a45-80bd-b6856aa9e14e.png)

N/A

**Comment by Superfire96** [comment]
Fixed on next restart
