### ISSUE TITLE
/dex wont work

### ISSUE THREAD

**Issue by JamingGaming** [SmashMC-Development/Bugs-and-Issues#1456]
**Describe the Bug**
whenever i do /dex nothing happens no text shows up or anthing

**To Reproduce**
idk how it happend

**Servers with the Bug**
i only have tried it on groudon

**Expected behavior**
it should allow me to see a menu and claim rewards for getting the dex complete

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
