### ISSUE TITLE
Sprites in the texture pack may be a bit messed up

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1457]
**Describe the Bug**
A player told me that their sprites were mixed up, a crystal kartarna was showing as a celesteela.

**To Reproduce**
1. Get a crystal kartarna
2. Look at it's sprite, it shows as a crystal celesteela

**Servers with the Bug**
Was discovered on kyurem. Assuming all servers since it seems to be a texture pack issue

**Expected behavior**
Should have the crystal kartarna sprite

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/186768166-e314feb7-2948-4782-899f-0bf97027b643.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
That's a funny one lmao, fixed on next restart!
