### ISSUE TITLE
Landscaping skill may be bugged?

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1459]
**Describe the Bug**
Player came to me in a ticket and asked whether the landscaping skill was bugged, they right click and nothing happens

**To Reproduce**
1. Bind landscaping to a tool
2. right click to use it
3. does't work

**Servers with the Bug**
was reported on kyogre

**Expected behavior**
Should work

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/186895432-f0026583-c9e9-41ae-936f-2e9207b78dc0.png)

**Additional context**
Player couldn't make the github, the ticket NO. is 52783

**Comment by Paradis4432** [comment]
inactive
