### ISSUE TITLE
hey i randomly glitched out of a battle with another player and not sure why so maybe it might be a glitch in the game, if it is please fix

### ISSUE THREAD

**Issue by PurpleVenom07** [SmashMC-Development/Bugs-and-Issues#1460]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Archie4690** [comment]
Hey @PurpleVenom07, I am closing this due to insufficient information in the ticket. Please open another one with the correct information.
