### ISSUE TITLE
Crafting Shulker boxes does not give you crafting exp

### ISSUE THREAD

**Issue by KeeOrahh** [SmashMC-Development/Bugs-and-Issues#1461]
**Describe the Bug**

**To Reproduce**
1. Collect shulker shells and a chest
2. Craft shulker box
3. No crafting exp given

**Servers with the Bug**
Reshiram but could be all servers?

**Expected behavior**
Crafting Shulker boxes should give crafting experience

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed on next restart!
