### ISSUE TITLE
Air where ranch block used to be in mart

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#1462]
**Describe the Bug**
There is air where the ranch block used to be in /warp mart

**To Reproduce**
1. Go to /warp mart
2. go to "breeding blocks"
3. see it's air

**Servers with the Bug**
All

**Expected behavior**
Should probably either be taken out, or be daycare blocks instead

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/187046733-2b06ab0d-4faf-4498-826a-f881b8757637.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed on next restart!!!!
