### ISSUE TITLE
Pokémon using up items

### ISSUE THREAD

**Issue by VerifiedKiller** [SmashMC-Development/Bugs-and-Issues#1463]
Not sure if this is a bug but in warzone items likes white herbs don't get used up after the battle, however when outside of the warzone they get used up. I have lost 2 white herbs and 1 power due to this.

Servers:
Groudon but probably all

**Comment by Mikirae** [comment]
We have "return-held-items: true" in the config. Is it when fighting players, or fighting Pokemon?

**Comment by VerifiedKiller** [comment]
it is when fighting pokemon.

**Comment by Mikirae** [comment]
I think that's a Pixelmon thing. I don't see an option for it anywhere.

**Comment by Paradis4432** [comment]
inactive
