### ISSUE TITLE
Bugged leg ivs

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#1464]
**Describe the Bug**
Galarian zapdos doesnt have the minimum of 3 31 iv stats

**Servers with the Bug**
Groudon

**Expected behavior**
Should have atleast 3 31 iv stats minimum, my only guess is a non legendary pokemon was edited into the zapdos

**Screenshots**
![image](https://user-images.githubusercontent.com/90443761/187398050-65cf2926-c924-4fe8-a36c-8d54b81ea897.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Two things:
First off, this is a Pixelmon bug as I tested it in Single Player

Secondly, and more importantly, look at my Grookey's IVs bro it's so good
![image](https://user-images.githubusercontent.com/24925669/188057214-866729f6-a084-4a46-afc9-5e32f3842497.png)
