### ISSUE TITLE
Crystal Calyrex has no texture when fused.

### ISSUE THREAD

**Issue by HelsbyJ** [SmashMC-Development/Bugs-and-Issues#1465]
When fusing crystal calyrex with either glastrier or spectrier, it not noly doesn't show as crystal but once you unfuse them the texture deletes and becomes just a normal calyrex with no texture.
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This is unfortunately a Pixelmon bug. Sounds like they're not storing some of the NBT data properly. I'll report it :)
Make a ticket and someone can get that sorted for you!
