### ISSUE TITLE
Legend spawn announcement

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1467]
**Describe the Bug**
The wild spawned legendaries are not being announced in the global chat in any way.

**To Reproduce**
1. Spawn wild legend
2. No text in global chat

**Servers with the Bug**
At least Kyogre. Other servers do not have this issue, can not remember which ones.

**Expected behavior**
Seeing that a leg has spawned in global chat.

**Additional context**
Happened with a Eternatus and a Suicune.

**Comment by Superfire96** [comment]
Fixed
