### ISSUE TITLE
Mega khanhaskhan ability not working

### ISSUE THREAD

**Issue by strewby** [SmashMC-Development/Bugs-and-Issues#1468]
**Describe the Bug**
When i mega evolve khankaskhan his ability doesnt change from scrappy to parental bond
**To Reproduce**
1. Go to 'pixelmon and get a khangkaskhan and megastone'
2. Click on 'mega evolve'
3. when you mega evolve it doesnt hit twice

**Servers with the Bug**
Please provide a list of which servers have this bug.
im on kyogre
**Expected behavior**
i thought it would just do what its meant
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
n/a
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by Mikirae** [comment]
I tested this and confirmed that it does in fact work :)
