### ISSUE TITLE
Warzone steal time

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1469]
**Describe the Bug**
The warzone steal time is 30 seconds. However, when i win a battle and have the option to steal something the time goes way faster than 30 seconds. This makes it so that you have more like 10 seconds to choose a mon instead of 30

**To Reproduce**
1. Go to warzone
2. Win a battle
3. See issue

**Servers with the Bug**
On reshiram but I assume all

**Expected behavior**
I'd expect the timer to actually be 30 seconds

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Sorry that it took so long to get back to you. We've been really busy lately :(
This glitch and many others were fixed :D
