### ISSUE TITLE
Players are able to /vault in warzone

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#147]
**Describe the Bug**
Players are able to join the warzone and then /vault, with that they might bring "illegal" items inside

**To Reproduce**
1. Go to a random server, /Warp warzone
2. Step on the pressure plate
3. Type /vault

**Servers with the Bug**
Should be like that on every server, couldn't test as i didn't have a team on every server

**Expected behavior**
Players should not be able to /vault

**Screenshots**
![2021-05-20_20 02 53](https://user-images.githubusercontent.com/83550357/119027313-798e2300-b9a6-11eb-9d4f-47168e0b47cb.png)

**Comment by HackuJacku** [comment]
@Superfire96 - please can you check now on all servers? Please let me know what happens on each server

**Comment by HackuJacku** [comment]
Fixed.
