### ISSUE TITLE
Random Shiny Paper

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1470]
**Describe the Bug**
I used a few Random Shiny Papers and got Luxray and Magikarp without the shiny palette. So non-shiny.
I also got shinies. The ratio was like 2 out of 8 Random Shiny papers were non-shiny.

**To Reproduce**
1. Use Random Shiny Paper
2. Get Non-Shiny Pokemon

**Servers with the Bug**
Happened on Zekrom and Groudon.

**Expected behavior**
Random Shinies to be Shiny.

**Additional context**
After the first time i double-checked if i am actually using random Shiny papers. So i made sure that this is indeed an issue and not me confusing random pokemon papers and random shiny papers.

**Comment by Mikirae** [comment]
Both of the Pokemon you listed have different palettes that might be causing it to mess up. I'll have the dev look into it :D

**Comment by DinglePringleUwU** [comment]
Addendum: Same thing happened with a "Hippopotas" 
Edit1: And with "Florges"

**Comment by Paradis4432** [comment]
inactive
