### ISSUE TITLE
Legendary Crystal spawned without the texture

### ISSUE THREAD

**Issue by JAK31208** [SmashMC-Development/Bugs-and-Issues#1471]
I was in the wz when I crystal galarian zapdos spawned, but when I ran up to it it had no texture at all. The galar zapdos texture has only been recently fixed but now the crystal form seems to be broken as well.

Youtube Link of clip of it not being crystal when I first found it

https://youtu.be/MvMYXA2O9Bg

**Comment by jantjewieger** [comment]
Are you sure you have the correct texture pack enabled? The crystal texture is in the game (I just checked). Also what does it say when u hover over the name of the zapdos?

**Comment by Mikirae** [comment]
I can confirm that this was a bug on our end. If you haven't done so already, please open a ticket and let them know that I said that they're able to give this back :)
