### ISSUE TITLE
hola, there has been no wild legend spawns on reshiram server in a good few days and idk if its just a bug with the message in chat popping up or if they just arent spawning but ye no1 on reshi has found 1 outside of wz for a few days

### ISSUE THREAD

**Issue by PurpleVenom07** [SmashMC-Development/Bugs-and-Issues#1472]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jantjewieger** [comment]
Purple pls make new github with proper format ( as I said in the dm's :p)
