### ISSUE TITLE
ever since i got veteran rank i lost perms to vaults

### ISSUE THREAD

**Issue by JamingGaming** [SmashMC-Development/Bugs-and-Issues#1473]
**Describe the Bug**
i had elite rank for a while and when i finnaly reached 50% pokedex and got veteran rank and then when i tryed opening my vault it said i didnt have perms for it even though when i had elite rank i could open vaults

**To Reproduce**
1. get elite rank by getting 25% pokedex
2. use /vaults command and notice that u indeed have a vault
3.get veteran rank by getting 50% pokedex
4.  use /vaults command and notice you dont have permisson to do so

**Servers with the Bug**
i only know that groudon has the bug 

**Expected behavior**
i expected to either still have 1 vault or to get a second with the veteran rank

**Screenshots**
n/a

**Additional context**
i left a gs ball, wishing piece,some mballs and more in there so please fix this soon

**Comment by Mikirae** [comment]
This is fixed now. Thank you for reporting it and sorry that it took so long <3
