### ISSUE TITLE
Rayquaza Fossil Room not working

### ISSUE THREAD

**Issue by TristanG545** [SmashMC-Development/Bugs-and-Issues#1474]
When doing /warp fossil and entering the fossil rooms. Upon going to clean the fossils it is not allowing this and saying i do not have permission for this.

**To Reproduce**
1. Go to '/warp fossil'
2. Click on fossil cleaner with a fossil
3. See error

Rayquaza

It should allow you to use the fossil cleaners and then put your fossils in the machine however you cannot use any of the machines

**Comment by PurpleVenom07** [comment]
Wiepie_ (admin) also tried to fix this issue but it was an error with the claim flags for the fossil cleaner

**Comment by TristanG545** [comment]
Is there any update on this yet?!

**Comment by Superfire96** [comment]
Fixed some time ago
