### ISSUE TITLE
legend spawn bug

### ISSUE THREAD

**Issue by PurpleVenom07** [SmashMC-Development/Bugs-and-Issues#1475]
when playing in the server reshiram a wild legend outside of wz hasnt spawned in around a week atleast

**To Reproduce**
1. log onto reshiram
2. play for a few hours
3. See error

**Servers with the Bug**
from what i know of reshiram but I assume it probably happens on other servers too

**Expected behaviour**
I expected legends to spawn but they didn't lol ;-;

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
