### ISSUE TITLE
Skills not working properly

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#1476]
**Describe the Bug**
Breeding skills lvl 50 doesnt lower breeding times like it is supposed to.

**To Reproduce**
1. get level 50 breeding in hopes of getting shorter breeding timers
2. Lament when not able due to still having to wait 45 mins

**Servers with the Bug**
all

**Expected behavior**
Breeding timers in the daycare should be affected by the skills mechanic to lower said timers

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/189207540-96c66ae3-c79f-46c7-a268-aa1231627629.png)
![image](https://user-images.githubusercontent.com/82549364/189210529-d94911b5-d47f-40b0-b470-622f2ca48e8d.png)
![image](https://user-images.githubusercontent.com/82549364/189210551-8ff0f725-ea48-407f-a506-f1269027bc4c.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This has been reported to the developer I believe. Just waiting on a fix for it :)

**Comment by Paradis4432** [comment]
inactive
