### ISSUE TITLE
/bag issue

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1479]
**Describe the Bug**
The /bag plugin's auto-pickup feature (Which is amazing, please dont remove it ever) tends to stack papers upon pickup.
For some reason, these stacked papers are then considered "duplicate papers" and promptly removed upon taking them out of the /bag.

**To Reproduce**
1. Get two papers of the same kind
2. Use /bag and put one of the papers into it
3. Toggle the auto-pickup feature from the /bag
4. throw paper on the ground, it gets sucked into the bag
5. Open /bag and look at the two stacked papers, take them out
6. It will be reduced to exactly one paper of that kind, removing the other(s)

**Servers with the Bug**
At least Kyogre, likely all with the plugin

**Expected behavior**
I would expect the paper to not get removed or stacked

**Screenshots**
Screenshot shows the message that comes upon taking the papers out in Step 5-6
![2022-09-11_18 35 44](https://user-images.githubusercontent.com/94211853/189539558-546b1100-ea23-4ecf-a01d-c2267a7bdfdb.png)

**Comment by Mikirae** [comment]
Okay I fixed this by completely removing vaults altogether. This shouldn't happen anymore :)
Or I prevented papers from being auto picked up. One of the two
