### ISSUE TITLE
Palkia Warzone doesnt spawn anything

### ISSUE THREAD

**Issue by Firemelon66** [SmashMC-Development/Bugs-and-Issues#148]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
They are currently spawning.
