### ISSUE TITLE
No woodcutting exp gained when breaking warped or crimson stem. Breaking soul soil does not give excavating exp. Basalt, glowstone, bone block, magma block and blackstone does not give you mining exp.

### ISSUE THREAD

**Issue by KeeOrahh** [SmashMC-Development/Bugs-and-Issues#1480]
**Describe the Bug**
Breaking either Warped or Crimson stem blocks with an axe does not give woodcutting exp
Digging Soul soil with a shovel does not give excavating exp
Mining Basalt, magma block, Blackstone, bone block, glowstone does not give mining experience.
**To Reproduce**

**Servers with the Bug**
Reshiram but it could be all servers

**Expected behavior**
Breaking either Stem blocks with an axe should give woodcutting exp
Digging Soul soil with a shovel should give excavating exp
Mining Basalt, magma block, Blackstone, bone block, glowstone should give mining experience.
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Everything fixed!
