### ISSUE TITLE
Blocks in /shop are a bit more expensive than at /warp mart

### ISSUE THREAD

**Issue by KeeOrahh** [SmashMC-Development/Bugs-and-Issues#1481]
**Describe the Bug**
Andesite, Diorite, Granite, Stone, Mossy cobblestone, prismarine, ice and snow block were the ones I found at /shop to be a bit more expensive than at /warp mart.

**To Reproduce**

**Servers with the Bug**
Reshiram but it could be all servers

**Expected behavior**
The blocks should be the same price at both /shop and /warp mart

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Fixed
