### ISSUE TITLE
Crafting Crimson, Warped or quartz related items do not give crafting experience.

### ISSUE THREAD

**Issue by KeeOrahh** [SmashMC-Development/Bugs-and-Issues#1482]
**Describe the Bug**
I crafted some building blocks out of warped and quartz blocks but I didn't get any crafting experience.

**To Reproduce**

**Servers with the Bug**
Reshiram but it could be all servers

**Expected behavior**
Crafting new items using those blocks should grant crafting experience

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Fixed!
