### ISSUE TITLE
Broke an epic lucky block and got a shiny tornadus that flew far away from me and I couldn't see it anymore.

### ISSUE THREAD

**Issue by KeeOrahh** [SmashMC-Development/Bugs-and-Issues#1483]
**Describe the Bug**
I logged onto the groudon server and collected the rare lucky block from my day 30 daily rewards. I opened it and got an epic lucky block. I opened the epic lucky block and it was a shiny tornadus but it progressively flew further away from me and I didn't have any flying pokemon or elytras to catch up to it. I had 32 render distances and ran in the direction it flew away for like 5 minutes but I couldn't find it so I gave up on it.

**To Reproduce**
1. Get rare block and break it to get an epic lucky block.
2. Get a flying pokemon from the lucky block
3. Watch it fly away

**Servers with the Bug**
Groudon but it could be all servers

**Expected behavior**
With someone who doesn't have access to the /fly command, the flying pokemon should spawn on the ground and remain there until it is caught, instead of flying further and further away from the player.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
We're looking into a fix for this :) Thank you for reporting!

**Comment by Paradis4432** [comment]
inactive
