### ISSUE TITLE
I can't /show(slot) my shiny victini that i got from my epic lucky block

### ISSUE THREAD

**Issue by KeeOrahh** [SmashMC-Development/Bugs-and-Issues#1484]
**Describe the Bug**
I went on Zekrom to collect my rare lucky block from my daily rewards and got an epic lucky block. I caught the legendary from it but I couldn't show it in chat because it said I didn't have permission. When I typed the /show command all the numbers were there except one which the legendary was in.

**To Reproduce**
1. Get rare lucky block from daily rewards
2. Get epic block and catch legendary
3. Type /show(slot) in which the legendary is in
4. You will receive a message that you do not have permission and need to contact server admins. /show(slot) will not show up in the chat aswell

**Servers with the Bug**
So far on Zekrom, kyogre but it could be all servers.

**Expected behavior**
Legendaries caught from epic lucky blocks should be able to /show(slot) without saying that the player does not have permission.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://user-images.githubusercontent.com/112224516/190382484-4e488122-7aff-4536-9d3e-502014e423d3.png)
![image](https://user-images.githubusercontent.com/112224516/190382620-6f971ad4-05cf-4bdd-90ec-4ebcdbe736b0.png)
![image](https://user-images.githubusercontent.com/112224516/190385360-c3ea9dbb-4fde-42ba-88fe-67ae2952935a.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Do you know if it's just that specific slot (In this case slot 4) or the issue happens in every slot when it has a legend in it?

**Comment by Superfire96** [comment]
Should be fixed on next restart, if it's not, let me know on the above

**Comment by Mikirae** [comment]
I believe this is fixed :)
