### ISSUE TITLE
Pokehunt is being weird

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1486]
**Describe the Bug**
The pokehunt is showing something weird when it says a new pokemon is being hunted (see screen)

**To Reproduce**
1. Go on any server
2. wait for the start of a new pokehunt
3. see error

**Servers with the Bug**
Reshiram for sure but possibly all

**Expected behavior**
I'd expect it to just show the mon

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/191719212-b408878a-9afc-4147-9d32-133063980ee3.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
Hi this is a Pixelmon bug and fixed in next version
