### ISSUE TITLE
Thunder stone ore broken

### ISSUE THREAD

**Issue by Snorrlax** [SmashMC-Development/Bugs-and-Issues#1487]
**Describe the Bug**
After a thunder storm, my base was stuck by lightning turning stone into thunder stone ore (like it is now intended in this version).

**To Reproduce**
1. Go to mountain biome
2. Wait for thunderstorm 
3. Mine any thunder stone ore
4. See ore turn into cobblestone

**Servers with the Bug**
Zekrom

**Screenshots**
N/A

**Additional context**
Made ticket #53752 with video proof and B00mhammer was in voice chat when it happened

**Comment by Paradis4432** [comment]
inactive
