### ISSUE TITLE
launching the game after an update with technic

### ISSUE THREAD

**Issue by BigChungv2** [SmashMC-Development/Bugs-and-Issues#1488]
**Describe the Bug**
I don't know if this is happening to everyone that uses technic but whenever there is an update for the modpack, my minecraft resets itself and i have to change all of my settings every time i launch after an update.

**To Reproduce**
1. update smash modpack on technic
2. launch the game
3. find minecraft to of reset all of its settings back to default

**Expected behavior**
not to reset all my minecraft settings like it used to

**Comment by Mikirae** [comment]
That's unfortunately how Technic works and we can't do anything about it :(
