### ISSUE TITLE
Anubis Egg Visual Glitch

### ISSUE THREAD

**Issue by VampireSquid90** [SmashMC-Development/Bugs-and-Issues#1490]
**Describe the Bug**
When hatching the pokemon (i used /hatch) you recieve from the battle pass i recieved a pokemon which contradicted itself with the text.

**To Reproduce**
1. Go to Battlepass
2. Click on a level that you receive an egg on
3. type /hatch

**Servers with the Bug**
Zekrom

**Expected behavior**
The text to all say the same pokemon instead of 2 pokemon.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
![2022-09-28_00 21 48](https://user-images.githubusercontent.com/73128313/192658308-efd08bd2-395b-4809-8052-df9b43d75a7d.png)

**Comment by Superfire96** [comment]
I honestly thought i had sent this message a couple of days ago, yes we are aware that it will always say Magikarp instead of the actual pokemon, but there's nothing that we can do to fix that, at least for the time being!
