### ISSUE TITLE
LuckyBlocks

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1492]
**Describe the Bug**
If I place down a Luckyblock someone else can still open it. I can then in turn not catch the mon he spawned in from opening my luckyblock. Pretty sure that ur not supposed to be able to break blocks placed down by someone else

**To Reproduce**
1. Go to any server
2. get a luckyblock
3. place it down
4. someone else can break it so see issue

**Servers with the Bug**
Tested on Kyurem but i assume all

**Expected behavior**
Id expect no one to be able to break the luckyblock i placed down

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
I think this is fixed. Can you test it for me kind sir?

**Comment by DinglePringleUwU** [comment]
I tested this on Zekrom as i had a spare lucky block.
Placed the Rare Lucky Block and a different player was able to break it.
I was not able to engage the leg afterwards, but the other player was.

**Comment by Mikirae** [comment]
The owner of the lucky block should be whoever places it. I’ll check into this. Thank you!

**Comment by jantjewieger** [comment]
Just tested this and purple was still able to break the block i placed down miki. happened on reshi so idk if its just that but yeah

**Comment by Mikirae** [comment]
So, they should be able to break it, but you should be able to catch it,
and they shouldn't be able to

**Comment by Mikirae** [comment]
Do we want it so that only the Block Placer can break it too? I can ask for
that if we want it

**Comment by jantjewieger** [comment]
The solve for this is useless when it comes to the lower luckyblocks which only give papers. I think its best if its that just the person who places it can actually break it.

P.S. the fix dont rly work as purple could still break the block. and then i couldnt catch it just him. Other ppl could just steal the block i place down this way

**Comment by Paradis4432** [comment]
inactive
