### ISSUE TITLE
New Warzone Update Didnt Reset Wins/Losses

### ISSUE THREAD

**Issue by VerifiedKiller** [SmashMC-Development/Bugs-and-Issues#1493]
wz update only resetted the reputation and not the wins/losses
![Screenshot (305)](https://user-images.githubusercontent.com/108368655/193432735-e23678bf-26a5-4c83-98d1-ae394e8af088.png)

**Comment by Mikirae** [comment]
This is being fixed soon :D Gotta wait on a bug fix and then it should be fine :)
