### ISSUE TITLE
New zacian xern fusion shiny doesnt work.

### ISSUE THREAD

**Issue by SirMorningW00d** [SmashMC-Development/Bugs-and-Issues#1494]
**Describe the Bug**
I got a shiny fusion xern/zac and the texture is so off
**To Reproduce**
1. Go to '...' get fusion zac
2. Click on '....' make shiny
4. See error look at the texture
**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**
A great looking shiny that doesnt have eyes on the wings
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://user-images.githubusercontent.com/96324089/193471920-3ee5682c-f800-4993-9643-428933a8a614.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This is fixed for the next texture pack update! Thank you for reporting it :)
