### ISSUE TITLE
Mega stone key glitch

### ISSUE THREAD

**Issue by jonathanb434** [SmashMC-Development/Bugs-and-Issues#1495]
Player opened a mega stone key he won from event, player tried to open and got the (wait for crate to finish opening) glitch and never got his stone

Not 100% chance to happen but 
Buy a mega crate key
Right click crate

**Servers with the Bug**
Rayquaza

**Expected behavior**
The animation happens then proceeds to give mega stone

**Screenshots**

**Additional context**
Ive only seen this a couple of times.

**Comment by Mikirae** [comment]
This is something that's been bugged for a while, with no real indicator on how to fix it besides restarting the server. Not much we can do on our end, unfortunately :(
