### ISSUE TITLE
Warzone Hole

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1496]
**Describe the Bug**
There is a hole in the warzone in which players can get stuck

**To Reproduce**
1. Go to Warzone
2. Navigate to the cords: X: 202 Y: 68 Z: 174 (See screenshot)
3. Jump into the hole
4. Be stuck

**Servers with the Bug**
At least Kyogre, likely all servers.

**Expected behavior**
No hole in wz to get stuck

**Screenshots**
![2022-10-03_15 55 57](https://user-images.githubusercontent.com/94211853/193600473-889be397-b871-4988-a641-416b69b3463b.png)

**Comment by Superfire96** [comment]
Fixed
