### ISSUE TITLE
Warzone Hole

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1497]
**Describe the Bug**
There is another hole in the warzone in which players can get stuck

**To Reproduce**
1. Go to Warzone
2. Navigate to the cords: X: 128 Y: 60.5 Z: 180 (See screenshot)
3. Jump into the hole
4. Be stuck

**Servers with the Bug**
At least Kyurem, likely all servers.

**Expected behavior**
No hole in wz to get stuck

**Screenshots**
![2022-10-03_20 58 06](https://user-images.githubusercontent.com/94211853/193732707-2f6eb3d2-969d-4417-a522-fe1321f39245.png)

**Comment by Superfire96** [comment]
Fixed
