### ISSUE TITLE
Basically, whenever you press "claim all" in the battle pass, it only gives u a few of the rewards

### ISSUE THREAD

**Issue by Id00d00onurmum** [SmashMC-Development/Bugs-and-Issues#1499]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
I just updated Skills like 2 (?) days ago. Was this an issue beforehand, if you know?

**Comment by Paradis4432** [comment]
inactive
