### ISSUE TITLE
Unable to use Pixelmon Machines at spawn

### ISSUE THREAD

**Issue by HackuJacku** [SmashMC-Development/Bugs-and-Issues#15]
**Describe the Bug**
Healers, PC, Trading Machines, ETC are unable to be used at `/spawn`.

**To Reproduce**
1. Go to `/spawn`.
2. Try and use the healers in the training area.

**Servers with the Bug**
All servers.

**Expected behavior**
Players are able to use the healers.

**Comment by Rasgnarok** [comment]
Fixed.
