### ISSUE TITLE
MIMKYU

### ISSUE THREAD

**Issue by ARXNWZ** [SmashMC-Development/Bugs-and-Issues#1500]
I've been in a dark forest for nearly 100 Minecraft days and mimkyu has still not spawned.

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by ARXNWZ** [comment]
reshiram has this bug

**Comment by Mikirae** [comment]
I assume this would be a Pixelmon issue, but the file looks perfectly fine on our end.
{
  "id": "Mimikyu",
  "spawnInfos": [
    {
      "spec": "species:Mimikyu",
      "stringLocationTypes": [
        "Land"
      ],
      "minLevel": 15,
      "maxLevel": 45,
      "typeID": "pokemon",
      "heldItems": [
        {
          "itemID": "pixelmon:chesto_berry",
          "percentChance": 5
        }
      ],
      "condition": {
        "times": [
          "DAWN",
          "DUSK"
        ],
        "stringBiomes": [
          "roofed",
          "evil"
        ]
      },
      "rarity": 30.0
    }
  ]
}

**Comment by ARXNWZ** [comment]
ok

**Comment by Paradis4432** [comment]
inactive
