### ISSUE TITLE
Pokemon Skin issue

### ISSUE THREAD

**Issue by Weirdo758** [SmashMC-Development/Bugs-and-Issues#1502]
**Describe the Bug**
My Eternatus has a skin issue and doesnt have its shadow skin.
**Servers with the Bug**
Smashmc - Rayquaza
**Expected behavior**
same eternatus but with its proper skin 
**Screenshots**
![Etern](https://user-images.githubusercontent.com/89357415/194717744-831433e8-e93b-4800-8218-4eb7fa8bac0c.png)

**Comment by Paradis4432** [comment]
inactive
