### ISSUE TITLE
Breeding taking less time

### ISSUE THREAD

**Issue by TommyT1TWhiler** [SmashMC-Development/Bugs-and-Issues#1504]
**Describe the Bug**
Breeding BPHA Sobble is only taking 11minutes

**To Reproduce**
1. Go to '.....'

**Servers with the Bug**
kyogre I know and probs the rest of them

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/109922955/194784597-6dbe661a-9fc3-44ff-8caa-36a8f254f393.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
