### ISSUE TITLE
WZ hole

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1505]
**Describe the Bug**
There is a hole in warzone in which players can get stuck.

**To Reproduce**
1. Go to 'Warzone'
2. Navigate to x: 240 z: 136 y: 63
3. Jump in hole if not already inside it
4. be stuck

**Servers with the Bug**
Warzone, so all

**Expected behavior**
No hole in warzone to get stuck, needs filling

**Comment by Superfire96** [comment]
Fixed
