### ISSUE TITLE
Small issue with the /bag

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1506]
**Describe the Bug**
The - otherwise perfectly working - auto-pickup feature from the /bag seems to glitch with banners.
It only picks up the first banner palette. Every other banner dropped afterwards will be transformed into the first banner that is in the /bag.

**To Reproduce**
1. Enable autopickup from /bag
2. Drop any selfmade banner
3. Pick it up via bag
4. Do the same with another palette
5. Do /bag and take a look at the banners inside

**Servers with the Bug**
All

**Expected behavior**
Distinguishing between those banners or disable banner pickup

**Comment by Paradis4432** [comment]
inactive
