### ISSUE TITLE
GTS

### ISSUE THREAD

**Issue by TommyT1TWhiler** [SmashMC-Development/Bugs-and-Issues#1508]
**Describe the Bug**
Pokemon on GTS are showing unbreedable pokemon as breeds and people are getting confused when there pokemon they thought 
were breed are actually unbreeds

**To Reproduce**

**Servers with the Bug**
seems like all the servers

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
