### ISSUE TITLE
Incorrect captured legendary name in chat!

### ISSUE THREAD

**Issue by duervo** [SmashMC-Development/Bugs-and-Issues#1509]
In warzone, when a legendary spawns it's gets described with it's sprite! But in zekrom for example! The legendary pops up after caught in chat as just an legendary even if a shadow legendary 

**To Reproduce**

**Servers with the Bug**
What I know of only Zekrom (smashmc)

**Expected behavior**
It's supposed to say in chat for example: "A shadow mewtwo has spawned somewhere in the warzone" 
**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
