### ISSUE TITLE
Deoxys GTS is disabled

### ISSUE THREAD

**Issue by KingofTheThicc** [SmashMC-Development/Bugs-and-Issues#151]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Permission issue. Fixed.
