### ISSUE TITLE
Timespace Altar Shrine not working!

### ISSUE THREAD

**Issue by duervo** [SmashMC-Development/Bugs-and-Issues#1510]
**Describe the Bug**
I'm trying to use the timespace altar shrine in spawn but the shrine is not accepting my redchain! 

**To Reproduce**

**Servers with the Bug**
Could be all servers in SmashMc if im not mistaken but it doesn't work in Zekrom!
**Expected behavior**
If you have the redchain and a Adament orb (for example) you right click the shrine with the redchain in your Hand and it's gonna activate the shrine and if you place the orb (right click it to the shrine) it summons dialga 
**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
