### ISSUE TITLE
Fairy kings cry bug

### ISSUE THREAD

**Issue by jonathanb434** [SmashMC-Development/Bugs-and-Issues#1511]
**Describe the Bug**
Zaceas has a move known as fairy kings cry 
This move is supposed to charge up 1 turn then activate the next turn, it skips the charging and gives boosts the same turn
**To Reproduce**
1.use Fairy kings cry on Zaceas
**Servers with the Bug**
Please provide a list of which servers have this bug.
Groudon and probably all others
**Expected behavior**
Turn 1 it begins to charge
Turn 2 it Gives boosts 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://user-images.githubusercontent.com/107769725/196056248-651eab33-4ab5-4416-b28f-ff95883e9c83.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
