### ISSUE TITLE
the battle towers am hyms are broke 

### ISSUE THREAD

**Issue by AUHUX** [SmashMC-Development/Bugs-and-Issues#1512]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by AUHUX** [comment]
the gyms

**Comment by AUHUX** [comment]
n battle tower

**Comment by jantjewieger** [comment]
they aren't working because they haven't been implemented yet. We are waiting on some things before we are able to release both. Closing this up
