### ISSUE TITLE
Manarisu

### ISSUE THREAD

**Issue by Twillight0420** [SmashMC-Development/Bugs-and-Issues#1513]
Manarisu's base speed is lower than what it's said to be.
https://cdn.discordapp.com/attachments/1031274379679641742/1031274500936974436/unknown.png
https://cdn.discordapp.com/attachments/1031274379679641742/1031274530305495130/unknown.png
https://cdn.discordapp.com/attachments/1031274379679641742/1031274557186789477/unknown.png
https://cdn.discordapp.com/attachments/1031274379679641742/1031274593131954267/unknown.png
https://cdn.discordapp.com/attachments/1031274379679641742/1031274694462148739/unknown.png

These show that instead of 80 base speed it's 75...

**Comment by Paradis4432** [comment]
inactive
