### ISSUE TITLE
Fishing issue

### ISSUE THREAD

**Issue by BigChungv2** [SmashMC-Development/Bugs-and-Issues#1514]
**Describe the Bug**
I dont know if this is insanely bad luck but I've been fishing in the same spot for a week when I've been online and yet to have a single !!! rarity, mentioned it in chat and a few others said they've also not been getting any !!! when fishing, both with good and super rods

**To Reproduce**
1. Go to water and fish
2. over a period of time get no !!!

**Servers with the Bug**
Kyurem but potentially others

**Expected behavior**
at least some !!! spawns

**Comment by BigChungv2** [comment]
i have only been fishing in swamp biomes, just spoken to someone now and we've tried it in ocean biomes and instantly got !!! so i dont know if its just a biome specific issue

**Comment by Paradis4432** [comment]
inactive
