### ISSUE TITLE
gts command broken on kyurem

### ISSUE THREAD

**Issue by falldamage69420** [SmashMC-Development/Bugs-and-Issues#1515]
the command /gts wont work 

1. Go to 'chat'
2. type '/gts'
3. See error

server kyurem

![gts no work](https://user-images.githubusercontent.com/116071464/196393148-c68382b6-1f33-4ded-af37-0d6f5007d43c.png)

**Comment by jantjewieger** [comment]
This issue has since been resolved. Thank you for reporting it though. Closing this up
