### ISSUE TITLE
wz waiting on wild mons

### ISSUE THREAD

**Issue by PurpleVenom07** [SmashMC-Development/Bugs-and-Issues#1516]
this happened to me twice in wz, so i was just ha hunting like normal but when i tried to leave the battle with a mon(it didnt happen on every mon) it went into waiting glitch and it didnt allow a helper to endbattle me

it only happened to me on reshi and zekrom but idk if other servers have has the issue

what normally should happen is i leave the battle with the mon

![image_2022-10-18_144527126](https://user-images.githubusercontent.com/111924025/196447496-39daa9b6-e9ab-4f1b-8907-1ea509ebe786.png)

N/A

step 1: go into wz and battle mons
step 2: leave battle with a bunch of pokemon until u get waiting

**Comment by Paradis4432** [comment]
inactive
