### ISSUE TITLE
Ultra Space Pokeloot

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1517]
**Describe the Issue**
The Pokeloot in the new ultra space despawns after right-clicking it. Set to one-time-use.

**To Reproduce**
1. Go to Ultra Space
2. Click on Beast Ball Loot (Anywhere)
3. Its one-time use

**Servers with the Issue**
All

**Expected behavior**
Make them One-Time Use for each player without them disappearing. 

**Additional context**
I do not think this is intended. Might be tho. If so, that would be kinda bad. But dont think so.

**Comment by Superfire96** [comment]
This is sadly a pixelmon bug, will hopefully be fixed in the next update
