### ISSUE TITLE
fix /checkspawns legendary

### ISSUE THREAD

**Issue by McGladiator** [SmashMC-Development/Bugs-and-Issues#1518]
**Describe the Bug**
/checkspawns legendary works fine on rayquaza pls fix it on the others

**To Reproduce**
1. Go to a server besides rayquaza
2. use /checkspawns legendary
3. get "you must be an OP or have permission to perform this action"

**Servers with the Bug**
every server except rayquaza

I don't understand why if it works fine on rayquaza it isn't working on any other server its probably just a simple permission issue please fix this. having to guess when and which legendaries are going to spawn is inconvenient and a large waste of time

**Comment by Paradis4432** [comment]
inactive
