### ISSUE TITLE
Incorrect Answer

### ISSUE THREAD

**Issue by SentimentalRotom** [SmashMC-Development/Bugs-and-Issues#1519]
**Describe the Bug**
_One of the quiz questions has incorrect answers, The answer asks, "Name and Ice/Water type" but the answers are Steel/Rock types instead._ 

**To Reproduce**
_Honestly have no idea. Just get lucky with that particular question, I suppose._

**Servers with the Bug**
_Likely all of them? First saw this in Kyurem._

**Expected behavior**
_The question is supposed to take Water/Ice Types, but it did not._ 

**Screenshots**
![2022-10-19_21 21 48](https://user-images.githubusercontent.com/116239559/196841708-654e9d69-aba8-4ef4-bfb9-452e85f5b043.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
