### ISSUE TITLE
wz error on groudon

### ISSUE THREAD

**Issue by IsTired** [SmashMC-Development/Bugs-and-Issues#1521]
**Describe the Bug**
Cannot join wz in groudon although i have a full team of lvl 100s, error gives "fusion allowance error: You may only have one fusion pokemon in the warzone"

**To Reproduce**
1. go on groudon
2. have a full team of lvl 100 pokemon dont have a fusion
3. use /wz
4. try to join
5. returns error

**Servers with the Bug**
Groudon

**Expected behavior**
should be able to join wz with a full team of lvl 100s

**Screenshots**
![image](https://user-images.githubusercontent.com/95708824/197157387-9e4b087b-3550-476d-a935-114bf5e2e6aa.png)

**Additional context**
n/a

**Comment by Superfire96** [comment]
Was fixed some time ago
