### ISSUE TITLE
Shopkeepers in need of a switcheroo

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1523]
**Describe the Bug**
The "Pokeball" and "Power Items" Shopkeepers are at the wrong place. (See Screenshot below)
There are other Shopkeepers that also need to be replaced. For Example, the "Berries" npc, which somehow climbed up some ropes.

**To Reproduce**
1. Go to the "Kyogre" Server
2. Do /Warp Mart
3. Take a look at the "Pokéballs" shopkeeper and the "Power Items" shopkeeper

**Servers with the Bug**
Only Kyogre

**Screenshot - Location of the NPC's**
![2022-10-21_22 28 32](https://user-images.githubusercontent.com/94211853/197289057-5d978c02-1ec8-4a9f-8875-af17def3b133.png)

**Comment by Superfire96** [comment]
Fixed
