### ISSUE TITLE
pokedex rewards claimed but not recieved

### ISSUE THREAD

**Issue by rej3ct-mp4** [SmashMC-Development/Bugs-and-Issues#1524]
**Describe the Bug**
After completing 25% of the pokedex when attempting to claim my rewards it stated they were claimed however they were not received.
Also happens when completing 50% of the pokedex for veteran rank.

**To Reproduce**

**Servers with the Bug**
Groudon.

**Expected behavior**
I expected to receive all my rewards when I claimed them.

**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
