### ISSUE TITLE
Pumpkin Treat not registering

### ISSUE THREAD

**Issue by SentimentalRotom** [SmashMC-Development/Bugs-and-Issues#1526]
**Describe the Bug**
One of the pumpkins used to collect rewards does not work. Specifically the one right on the skull. The treats usually sparkle green, and then the sparkles disappear if you've claimed it, but it doesn't seem to be working at all for this one specifically.

**To Reproduce**
1. Find the Skull next to the Training Building.
2. Right Click the Pumpkin Head attached to the skull in the front.
3. Realize that nothing happened.

**Servers with the Bug**
Kyurem.

**Expected behavior**
Simply, it was supposed to register as one of the many treats that I've gathered, but it does not.

**Screenshots**
 ![2022-10-26_00 49 26](https://user-images.githubusercontent.com/116239559/197945468-12e88e51-9553-4f9b-acf9-beadbc74e21b.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed, swapped the treat
