### ISSUE TITLE
Mega Stone Crate freeze

### ISSUE THREAD

**Issue by Purp1eFate** [SmashMC-Development/Bugs-and-Issues#1530]
**Describe the Bug** Freezes Mid animation
A clear and concise description of what the bug is. The crates freeze while trying to open the key with mega stone crate

**To Reproduce**
1. Go to '...' Crates
2. Click on '....' Click on mega stone crate
3. Scroll down to '....' n/a
4. See error zekrom mega stone to be given

**Servers with the Bug**  Zekrom
Please provide a list of which servers have this bug.

**Expected behavior** Mega stone to be given

**Screenshots**
![image](https://user-images.githubusercontent.com/116973418/198847086-e8fb46ad-874d-4cf3-8616-a95e2fe53568.png)

If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context** The Mega stone while opening just stops and freezes what make the animation and prevents you from opening other crates.
Add any other context about the problem here. If nothing, please add 'N/A'. N/A

**Comment by GalaxyFrost123** [comment]
The same thing is happening to me! I thought I was the only one

**Comment by Paradis4432** [comment]
inactive
