### ISSUE TITLE
Bug with 5050 shiny crate key

### ISSUE THREAD

**Issue by ThoraUwU** [SmashMC-Development/Bugs-and-Issues#1531]
Describtion of the bug: 
A 5050 shiny crate key gave me a shiny Sprigarito wich dosent ecist in either pokemon or pixelmon yet.

The bug happend to me on the Reshiram server. 

I used the key and asumed i would either get a shiny or a non shiny pokemon

screenshot:
![billede_2022-10-30_021433383](https://user-images.githubusercontent.com/116986106/198858261-c86685c9-cdaf-4736-9550-bcf94e13426b.png)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
