### ISSUE TITLE
Psyshield Bash not available in Move Relearner

### ISSUE THREAD

**Issue by SentimentalRotom** [SmashMC-Development/Bugs-and-Issues#1532]
**Describe the Bug**
When you evolve Stantler into Wyrdeer outside of Level 21, you do not gain access to Psyshield Bash, not even via the Move Relearner in /warp mart.

**To Reproduce**
1. Take a Stantler.
2. Level it up to 22 or above (with a Hisuian Pokemon in your party.
3. Let Stantler Evolve into Wyrdeer.
4. Go to the Move Tutor.
5. Realize that Wyrdeer cannot relearn Psyshield Bash.

**Servers with the Bug**
Likely everywhere, but was first found in Kyurem.

**Expected behavior**
Psyshield Bash should be an option if you level your Stantler up later on.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jantjewieger** [comment]
This is unfortunately a pixelmon issue. You will have to wait until they fix it. You can report it to them on their tracker. Closing this up
