### ISSUE TITLE
Basculegion Stat bug

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#1533]
**Describe the Bug**
Basculegion stat is supposed to be different depending on the gender and I made a BP female Basculegion but the stats on it is the same as the male Basculegion instead of having the stat of a female one.

**Servers with the Bug**
Groudon
**Expected behavior**
I checked on Pokémon showdown and the Special attack is supposed to be 328 but instead it's 284 which is supposed to be the stat of the male Basculegion.
**Screenshots**
![image](https://user-images.githubusercontent.com/93119451/198913630-59824b2f-91d7-417c-ac01-58f3db2b2a44.jpeg)
![image](https://user-images.githubusercontent.com/93119451/198913683-85712beb-0543-4e31-adf6-bcfac8aac5fb.jpeg)
![image](https://user-images.githubusercontent.com/93119451/198913711-73fa9f72-be37-43c6-8719-3155885edf32.jpeg)
**Additional context**
N/A

**Comment by jantjewieger** [comment]
I just tested this in singleplayer and this is unfortunately a pixelmon bug and therefore not something we can do something about. You will unfortunately have to wait until they fix this issue. You can report this on their forum. Closing this up
