### ISSUE TITLE
Cant claim auctions in the gts

### ISSUE THREAD

**Issue by NotMistic** [SmashMC-Development/Bugs-and-Issues#1534]
**Describe the Bug**
When I log into a server and I listed a pokemon or smthn for sale and I come back later it says It has sold and that I have stuff to claim. But when I go to claim nthn happens and nothing is there

**To Reproduce**

**Servers with the Bug**
Currently this is bugging in ray and groudon  for me. I think it depends if you listed smthn on the gts b4 hand

**Expected behavior**
For the bug to be fixed and in the mean time given the cash for the items sold.

**Screenshots**
![image](https://user-images.githubusercontent.com/117168142/199232666-80631650-36ef-4015-b4df-f16ca9567ed9.png)
![image](https://user-images.githubusercontent.com/117168142/199232695-b98ecf38-f18f-46ed-b465-5973d872f234.png)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
