### ISSUE TITLE
Can't enchant Fishing Rod

### ISSUE THREAD

**Issue by Luis-Santos96** [SmashMC-Development/Bugs-and-Issues#1537]
Since you can't enchant Pixelmon rods you can't get mending so you can't repair them

The only way is with smash rank.

Basic mechanics of the game should be free, we're not talking about changing the nature of a legendary, or its size, or make it shiny or galaxy. Is just a fishing rod!

Please fix this, or tell me how you can hunt for stuff like Battle Bond Greninja with only the duralibity of a super rod without Unbreaking III or repairing it

**Comment by Paradis4432** [comment]
inactive
