### ISSUE TITLE
glitched texture

### ISSUE THREAD

**Issue by PurpleVenom07** [SmashMC-Development/Bugs-and-Issues#1538]
shadow eternatus and shadow poipole have no texture

1. get shadow eternatus and poipole
2. make sure u have the right texture pack
3. and see the no texture

most likely all servers

to not see the skin its meant to have

![image](https://user-images.githubusercontent.com/111924025/199571726-9599ef2f-30d5-4723-89e9-622b3123b95e.png)

N/A

**Comment by Paradis4432** [comment]
inactive
