### ISSUE TITLE
A few deoxys issues

### ISSUE THREAD

**Issue by KingofTheThicc** [SmashMC-Development/Bugs-and-Issues#154]
**Describe the Bug**
We are not able to use any papers on our pokemon still, vaults cannot be opened.
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
We have a template so we can properly triage your issue. Please fill out the template.
