### ISSUE TITLE
Problem with the checkspawns command

### ISSUE THREAD

**Issue by ThoraUwU** [SmashMC-Development/Bugs-and-Issues#1541]
**Describe the Bug**
The problem was that ./checkspawns legendary didnt work on Reshriam server but did on for example the rayquaza server. so i got asked to make a ticket on this. 

**Servers with the Bug**
I expierienced it on the Reshiram server but heard that it was a problem on some of the others too. 

**Expected behavior**
I typed the command and expected it to work when i first started playing on smash servers. It didnt, but gave me a message about i need to be an OP or didnt have permission so i didnt think more of it until i discovered that it worked fine on rayquaza server. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
