### ISSUE TITLE
/pokecolor not recognized

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#1542]
**Describe the Bug**
The command /pokecolor is not recognized as a command.

**To Reproduce**
1. Go to any server
2. Have relevant in game rank
3. Type /pokecolor 

**Servers with the Bug**
I'm assuming all servers tho I only have the relevant rank on Rayquaza

**Expected behavior**
/pokecolor should enable player to color the names of their pokemon.

**Screenshots**
![Screenshot (118)](https://user-images.githubusercontent.com/45851395/200862057-afbeff35-a581-4cb2-9093-e0ae0dc2d615.png)

**Additional context**
Not highest priority issue but would be nice if this was fixed or if I was told whatever command has taken its place.

**Comment by Paradis4432** [comment]
inactive fixed
