### ISSUE TITLE
Zaceus Is Not Balanced

### ISSUE THREAD

**Issue by ACShade69** [SmashMC-Development/Bugs-and-Issues#1543]
Zaceus Z Move is Not Fair as it gets Z Geomancy Which increase al its stats by 1 plus fairy king cru normal boost without charging for a turn this is not fair what so ever as one z move and nothing will kill this pokemon

https://user-images.githubusercontent.com/117884264/200996543-cab4199b-959d-4f4f-bcca-caf5ca199676.mp4

**Comment by ACShade69** [comment]
Also its signature move is broken as it doesnt charge up

https://user-images.githubusercontent.com/117884264/201506034-d9ec3b0f-3bf8-423b-b92a-381d142d0f15.mp4

**Comment by Paradis4432** [comment]
inactive
