### ISSUE TITLE
GTS

### ISSUE THREAD

**Issue by TommyT1TWhiler** [SmashMC-Development/Bugs-and-Issues#1544]
**Describe the Bug**
Pokemon are that are Unbreedable are showing as Breedable on gts.

**To Reproduce**

**Servers with the Bug**
Reshiram 100% unsure about the others

**Expected behavior**
fix it :D

**Screenshots**

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
