### ISSUE TITLE
Warzone Bank

### ISSUE THREAD

**Issue by TommyT1TWhiler** [SmashMC-Development/Bugs-and-Issues#1545]
**Describe the Bug**
If you go to far along when looking through someones bank in warzone, you cant go back as it just deleted everything

**To Reproduce**

**Servers with the Bug**
Zekrom 100% dont know about others

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
