### ISSUE TITLE
Exclusive Crate Bug

### ISSUE THREAD

**Issue by GhostlyReign** [SmashMC-Development/Bugs-and-Issues#1546]
When i opened an exclusive crate I won a shiny luxio and was given a normal luxio with the color codes in the name not working

**To Reproduce**
1. open exclusive crate
2. win a pokemon
3. send out the pokemon
4. see error

**Servers with the Bug**
Groudon is the only one ive gotten the bug on but it might be for all servers

**Expected behavior**
I expect the pokemon to have the correct name and to be shiny

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Everything looks fine on my end
