### ISSUE TITLE
Missing No visual appearing in Bellsprouts place on zekrom's limited edition crate.

### ISSUE THREAD

**Issue by LordTaser** [SmashMC-Development/Bugs-and-Issues#1547]
**Describe the Bug**
A visual bug display's missing no's image in bellsprouts place on limited edition crates on zekrom server

**To Reproduce**
1. Go to Zekrom Server
2. Left - click on limited edition crate

**Servers with the Bug**
Zekrom

**Expected behavior**
A visual of bellsprout should have appeared instead of missing no

**Screenshots**
![image](https://user-images.githubusercontent.com/79674884/202291963-2f2e719e-a9fb-40f0-9036-4b5d233be1c3.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
Unfortunately we missed this, but thanks for letting us know about it!
