### ISSUE TITLE
out of bounds ultra space

### ISSUE THREAD

**Issue by mrfunniguy** [SmashMC-Development/Bugs-and-Issues#1548]
**Describe the Bug**
By standing close to the world border in ultra space and getting on a pokemon who is outside it you can escape the world border and explore beyond

**To Reproduce**
go to ultra space
reach the world border
stand on the border
through pokemon that can be ridden outside
mount pokemon

**Servers with the Bug**
Only tested on kyrum

**Expected behavior**
The game to push you back in bounds such as in over world
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
