### ISSUE TITLE
Deoxy Forms doesn't transfer over stats

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#1549]
**Describe the Bug**
I change the form of Deoxy from normal to defense form but the stat didn't transfer over at all.

**Servers with the Bug**

Groudon but probably other servers too

**Expected behavior**
I expect the stats from attack to get switch with defense
**Screenshots**
![image](https://user-images.githubusercontent.com/93119451/202435848-b031e11a-a6de-4bc3-8a4e-a926a1d222f0.jpeg)

![image](https://user-images.githubusercontent.com/93119451/202435911-e8f87718-156f-435d-bada-374c2b69600e.jpeg)
**Additional context**
N/A

**Comment by Mikirae** [comment]
Sorry for the long wait, but I tested this and it seems that it's fine now :)
