### ISSUE TITLE
Players are able to tp people in ultraspace

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#155]
**Describe the Bug**
Players can /tpahere in the overworld, then tp to the ultraspace and the other player can accept the tp

**To Reproduce**
1. Go to overworld, and type /tpahere name
2. Go to ultraspace
3. Make the other player accept the tp

**Servers with the Bug**
Every server (tested on Mew with 2 players, worked every time)

**Expected behavior**
Players shouldn't be able to tp in ultraspace

**Screenshots**
![2021-05-21_03 52 55](https://user-images.githubusercontent.com/83550357/119070440-4bc9ce00-b9e8-11eb-820d-1e5eeb4d0404.png)

**Comment by HackuJacku** [comment]
This is not a bug. If it's a suggestion to change something, please create a request on the appropriate repository.
