### ISSUE TITLE
Gym leader keeps on declining battle.

### ISSUE THREAD

**Issue by Marcellus1020** [SmashMC-Development/Bugs-and-Issues#1551]
When I battle the gym leader in (warp gyms) it states that something went wrong and re battle him.
Just to make it clear it has nothing to do with my Pokémon, my items, and I have the water gym badge. ( Level 70 gym) User WZ_Marcellus Sever kyrum
**To Reproduce**
1. Go to gym level 70 in warp gyms
2. Click on battle- select your team.
3. See error gym leader has declined your battle. Re challenge him.
**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyrum
**Expected behavior**
I expect to battle the level 70 gym leader.
![F8112EBA-F82A-4FF5-8B46-924524E03185](https://user-images.githubusercontent.com/118987739/203801254-01464b08-904f-4cd3-bf78-0d092278208c.png)

If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'. When I rebattle the gym leader it states the same thing. This was also happening yesterday and the day before yesterday.

**Comment by Mikirae** [comment]
Thanks for reporting this! 
It seems to work for me perfectly fine. Is this the same team that you used to battle other gyms?
![image](https://user-images.githubusercontent.com/24925669/204060285-256bb379-cbfa-417a-96df-a770494db8fd.png)
