### ISSUE TITLE
warzone bug

### ISSUE THREAD

**Issue by jgreen69** [SmashMC-Development/Bugs-and-Issues#1552]
**Describe the Bug**
the warzone bug is causing players to meet a *negotiating* message and getting sent out of wz, withou geting their money bacl

**To Reproduce**
1. Go to '/warzone'
2. enter and wait for message (if it apears)
3.  should then get disconnected

**Servers with the Bug**
rayquazza 

**Expected behavior**
tto get logged out and lose the money echanged, also can cause player to be unable to use commands

**Comment by Superfire96** [comment]
Fixed
