### ISSUE TITLE
Herbalism skill causes Reshiram crash

### ISSUE THREAD

**Issue by Mooduck101** [SmashMC-Development/Bugs-and-Issues#1554]
**Describe the Bug**
Whenever I click on the Herbalism skill in the /skills menu, an error causes me to crash and got to the lobby

**To Reproduce**
1. Open the /skills menu
2. Click on the Herbalism skill
3. You will get an error and be sent to the lobby

**Servers with the Bug**
Reshiram

**Expected behavior**
I expected to be able to see my herbalism skill in detail

**Screenshots**
![image](https://user-images.githubusercontent.com/119268732/204169886-c8a4e2db-69b8-4528-949b-b8e30ceb1703.png)

**Additional context**
Calub_Fang and Rappingman also tried this and experienced the same result.

**Comment by Superfire96** [comment]
I believe this was fixed
