### ISSUE TITLE
wz bug rayquaza

### ISSUE THREAD

**Issue by clarkkiller** [SmashMC-Development/Bugs-and-Issues#1556]
**Describe the Bug**
cant enter wz or you get kicked
**To Reproduce**
go to wz
**Servers with the Bug**
Please provide a list of which servers have this bug.
rayquaza
**Expected behavior**
fix it
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
fixed
