### ISSUE TITLE
wz bug..... again

### ISSUE THREAD

**Issue by clarkkiller** [SmashMC-Development/Bugs-and-Issues#1557]
**Describe the Bug**
wz kicking you when you enter it 
**To Reproduce**
1. Go to '...' wz

**Servers with the Bug**
Please provide a list of which servers have this bug.
rayquaza
**Expected behavior**
just fix it lol
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Fixed
