### ISSUE TITLE
wz bug thingy

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#1559]
**Describe the Bug**
Basically when winning a warzone battle, and not claiming the pokemon and i believe logging out to quickly it will delete the pokemon you had stolen that was in your bank

**To Reproduce**
1. Go to wz
2. win battle
3. Steal pokemon
4. log out right after winning and leaving warzone

**Servers with the Bug**
known its on kyurem
**Expected behavior**
pokemone gets deleted out of bank
**Screenshots**
n/a

**Additional context**
ticket 56281is where my issue happen

**Comment by Paradis4432** [comment]
inactive fixed
