### ISSUE TITLE
No Illex shrine at /warp shrines on kyogre

### ISSUE THREAD

**Issue by Skeletonio000** [SmashMC-Development/Bugs-and-Issues#156]
**Describe the Bug**
There is no illex shrine at /warp shrines on kyogre

**To Reproduce**
1. Go to ' /warp shrines ' on kyogre
2. Notice how there is no illex shrine

**Servers with the Bug**
Kyogre

**Expected behavior**
There should be an illex shrine at /warp shrines on kyogre
**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Added.

**Comment by Skeletonio000** [comment]
I see the area for the ilex shrine, but don't see the physical shrine
itself. Is this something new? Because there's no text above the shrine
area as well.

**Comment by AmsterDaan** [comment]
we had to remove the shrine itself as it has an issue where it cannot be re set, it will be re added as soon as the issue is fixed.

**Comment by Skeletonio000** [comment]
Ok, thanks.

**Comment by HackuJacku** [comment]
Fixed and added back.
