### ISSUE TITLE
Dynamax one hit KO

### ISSUE THREAD

**Issue by Melmetalgo** [SmashMC-Development/Bugs-and-Issues#1561]
Dear whoever this is,as i joined the server having some time in pixelmon with my legendary i decidet to dynamax it and dead by a lvl 11 pokemon the pokemon of mine had 429 hp even with the gigadynamax.pls fix this.

**Comment by Mikirae** [comment]
This is a Pixelmon bug, it sounds like. We can't do anything about this, unfortunately.
