### ISSUE TITLE
Issue with Galar Slowbro registering as Normal Slowbro

### ISSUE THREAD

**Issue by HelsbyJ** [SmashMC-Development/Bugs-and-Issues#1562]
When attempting to enter wz with galar slowbro it won't allow me to as the game thinks it is a regular slowbro, which is not UU.
<img width="525" alt="slowbro" src="https://user-images.githubusercontent.com/99360814/205452516-2c253320-799a-44a5-a0a5-cde6a6bdd106.PNG">
<img width="960" alt="slowbro2" src="https://user-images.githubusercontent.com/99360814/205452524-ea8bde85-1c6c-4fcf-8817-2f876af58170.PNG">
<img width="960" alt="slowbro3" src="https://user-images.githubusercontent.com/99360814/205452527-4cf97d86-0f7e-48b9-afcf-cdf08c2b9801.PNG">

**Comment by Paradis4432** [comment]
inactive
