### ISSUE TITLE
Shrines 

### ISSUE THREAD

**Issue by SevnHours** [SmashMC-Development/Bugs-and-Issues#1563]
On Groudon all shrines are missing from spawn along with a few other things from spawn like elevators and Spawner at the boss tower

![2022-12-03_12 14 46](https://user-images.githubusercontent.com/119755859/205456139-9ed7a82c-ee56-4828-be73-06de2fe5db4c.png)

**Comment by Neba2327** [comment]
There is the same problem on Kyogre

**Comment by Superfire96** [comment]
Fixed
