### ISSUE TITLE
Spawning in wz barrier

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#1564]
**Describe the Bug**
Sometimes when I go to wz, instead of spawning in a random place inside of wz barrier, I got spawned outside of wz barrier and there's nth I can do about it.

**Servers with the Bug**
Groudon 
**Expected behavior**
I expected to be spawned within wz barrier.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
