### ISSUE TITLE
The boss tower, it has been broken for the past 2 days, since the new update :(

### ISSUE THREAD

**Issue by p0mbi** [SmashMC-Development/Bugs-and-Issues#1565]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Was fixed
