### ISSUE TITLE
pokemon dont show in your pc after you catch them

### ISSUE THREAD

**Issue by CalubFang** [SmashMC-Development/Bugs-and-Issues#1566]
**Describe the Bug**
i was in ultra space and i had caught several raid pokemon and wild ones only to return to my home and find that i only had randoms ones and was missing around 30 or so of the 45-50 i caught.
**To Reproduce**
1. Go to '...' ultraspace
2. Click on '....' catch pokemon

**Servers with the Bug**
Please provide a list of which servers have this bug.
Smash MC (Reshiram)
**Expected behavior**
catch a few pokemon in the ultraspace then teleport back to my home (in normal minecraft world) check the pc and not see every pokemon i caught
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This is a Pixelmon bug. I do believe it will be fixed for the next Pixelmon version.
