### ISSUE TITLE
wz legend

### ISSUE THREAD

**Issue by PurpleVenom07** [SmashMC-Development/Bugs-and-Issues#1567]
a legend spawned in warzone and when i found it, it was uncatchable as it was in 1 of the snow globes

**To Reproduce**
1.  go to wz
2, wait for a legend to spawn in the snow globe
3. see it isnt able to be engaged in a battle

**Servers with the Bug**
happened to me on reshiram but if wz is same on all servers then it will be on all

**Expected behavior**
wont be able to engage with the legend

**Screenshots**
![image](https://user-images.githubusercontent.com/111924025/205661233-eead6f2e-b5d4-43c5-ac31-008bfcdcea87.png)

**Additional context** 
N/A

**Comment by Paradis4432** [comment]
inactive
