### ISSUE TITLE
Fusion Pokemon being hunted in /hunt

### ISSUE THREAD

**Issue by Mooduck101** [SmashMC-Development/Bugs-and-Issues#1568]
When I checked the /hunt menu earlier today, Beelesteela, a new fusion pokemon, was the target of the easy hunt

**To Reproduce**
1. Type /hunt in chat
2. check pokemon that are being hunted, one might be a fusion

**Servers with the Bug**
Reshiram

**Expected behavior**
I expected that there would not be a fusion pokemon being hunted in /hunt

**Screenshots**
![Screenshot_20221205_023048](https://user-images.githubusercontent.com/119268732/205755092-1fd6241a-0bf4-49df-a936-15d34b125a58.png)

**Comment by Superfire96** [comment]
Fixed on next restart
