### ISSUE TITLE
Missing squirtle 

### ISSUE THREAD

**Issue by xJRadx** [SmashMC-Development/Bugs-and-Issues#1569]
**Describe the Bug**
I did a raid with my friends and they all received a Squirtle and I did not 
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This is currently a Pixelmon bug. You can open a ticket in our Discord about this.
