### ISSUE TITLE
No wz Legendary spawns on Charizard server

### ISSUE THREAD

**Issue by Kalegamer07** [SmashMC-Development/Bugs-and-Issues#157]
**Describe the Bug**
In charizard there were 0 legendary spawns the last 3-4 hours. I know the spawns were nerfed bt this is a bit ridiculous.

**Servers with the Bug**
Charizard

**Expected behavior**
I thought there were at least some spawns in wz but there have been none.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
The spawn data is being recorded as it's far easier/better for us to buff it than it is to nerf it. We will continue to closely monitor all Warzone spawns.
