### ISSUE TITLE
Missing Shulkerbox

### ISSUE THREAD

**Issue by FKCyborg** [SmashMC-Development/Bugs-and-Issues#1570]
**Describe the Bug**

My shulkerbox disappeared out of nowhere while i was grinding at the BossTower.

**To Reproduce**

**Servers with the Bug**

This happened in the Rayquaza server.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**

I store all my valuable pokeballs in my shulker box. I had over a stack of Ultra Balls (thanks to my farms of black and yellow appricorns), 5 Master balls (3 I bought and 2 I got from Dyanmax Raids) and a Park Ball  (also from a Dynamax Raid). There were also other things (like pickaxes and other stuff ) but they don't really mater to me as much as the pokeballs do. Please help, I'll do anything to get them back.

**Comment by Mikirae** [comment]
Please open a ticket about this. If I had to guess, you misplaced it in a chest or something.

**Comment by Mikirae** [comment]
A ticket in our Discord*
