### ISSUE TITLE
Moves got deleted when learning moves and didnt get a choice

### ISSUE THREAD

**Issue by MaskedGodEater** [SmashMC-Development/Bugs-and-Issues#1572]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
There's not really any information described here, but this sounds like a Pixelmon bug.
