### ISSUE TITLE
Dynamax Pokemon don't show in PC when captured.

### ISSUE THREAD

**Issue by Kylo46** [SmashMC-Development/Bugs-and-Issues#1573]
**Describe the Bug**
Completed 2 Turtwig dynamax dens in the ultra forest, used a quick ball to capture one and a regular poke ball to snag the other.  When I returned to my PC to check the IV's neither pokemon was there.  This has also happened in the past but was on a different dynamax in the overworld. 

**To Reproduce**
Beat a Dynamax Den
Use any type of Pokeball
Capture said Pokemon and have the screen tell you it was captured
Check PC to find Pokemon missing

**Servers with the Bug**
Zekrom

**Expected behavior**
Would like to see the glitch fixed if it is a glitch and if I could get the Turtwigs I would appreciate that as well.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
I also have my 3 kids who play the same server and it has happened to them as well.

**Comment by Kylo46** [comment]
These screenshots were from a Golisopod 5 star den that I captured with 2 empty slots in my party.  There is no capture message and the pokemon doesn't show up in my party.

![IMG_4384](https://user-images.githubusercontent.com/120197379/206829671-a9aa1d45-fe88-45bc-9b15-8a38a5630557.jpg)
![IMG_4385](https://user-images.githubusercontent.com/120197379/206829679-0bbe5be7-a41b-47a5-8986-ac33b1ea1b54.jpg)
![IMG_4386](https://user-images.githubusercontent.com/120197379/206829697-8174cbb3-c0ba-47ac-a867-ae1820ce0961.jpg)

**Comment by Mikirae** [comment]
This is a bug with Pixelmon currently. Please open a ticket and we can get you your things back!
