### ISSUE TITLE
Hydreigon should be allowed in warzone but says its not allowed and is UUBL

### ISSUE THREAD

**Issue by 21asianboy** [SmashMC-Development/Bugs-and-Issues#1574]
Warzone is not allowing hydreigon in the warzone saying it is UUBL when it is not.

**To Reproduce**
1. have a hydreigon on your team
2. try to enter warzone
3. it will say it is not allowed because it is UUBL
**Servers with the Bug**
I don't know what other ones just zekrom specifcally.

**Expected behavior**
I expected it to work since It is allowed in the gen 8 UU nat dex ladder

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
![image](https://user-images.githubusercontent.com/83550357/206929698-38063c65-0829-4283-8256-78fb520313f2.png)

Well to me it looks like it's banned

**Comment by ajdawg48** [comment]
It was unbanned last month the page it outdated
![image](https://user-images.githubusercontent.com/82591470/206930428-74b97a3a-dccb-47cb-bd90-c38709ccf278.png)

**Comment by Mikirae** [comment]
My mans has been freed!!!!!!!!
