### ISSUE TITLE
Wz rep lose bug

### ISSUE THREAD

**Issue by CapyBaraRZ** [SmashMC-Development/Bugs-and-Issues#1576]
**Describe the Bug**
this bug lets u lose rep out of nowhere , by me it was now 2 times overnight i lost overall 48 rep ( first 32 and then 16) i went from 1057 down to 1027 and then down to 1011 ( wasnt inactive in wz so no rep reduction cuz of inactive highest was like 37h not in)
this started to happen after the server was restarted for a wz update or sth on the 10.12 (10th of dec)

**To Reproduce**
there isnt really one 

**Servers with the Bug**
from waht ik kyurem but prolly all servers

**Expected behavior**
fixing the bug and giving players there rep bag aslong its proveable 

**Screenshots**
![Screenshot_128](https://user-images.githubusercontent.com/119757851/207124702-4b0c61b1-c33d-4b40-b743-afc6267dbfd7.png)
![Screenshot (129)](https://user-images.githubusercontent.com/119757851/207124720-a733448a-2483-4b8a-b3bb-3eebbc042e1d.png)
![Screenshot (131)](https://user-images.githubusercontent.com/119757851/207124781-349a033d-8de7-44e5-9902-c6ec07d744aa.png)

**Additional context**
i hope that this gets fixed soon

**Comment by Mikirae** [comment]
Were you fighting anyone during these times? Or simply going to Warzone?

**Comment by Paradis4432** [comment]
inactive
