### ISSUE TITLE
Invisible after defeating raid den

### ISSUE THREAD

**Issue by viop1019** [SmashMC-Development/Bugs-and-Issues#1577]
**Describe the Bug**
After defeating a raid den, all entities (including chests, pokemon, users, and items) become invisible. During the fight it says "OpenGL API ERROR: 1283 (GL_STACK_OVERLOAD)" and the same but with underload immediately after.

**To Reproduce**
1. Enter a den fight
2. complete the fight
3. See error

**Servers with the Bug**
Kyurem

**Comment by Mikirae** [comment]
This is a current Pixelmon bug with Raids and Shaders. If you disable your Shaders, it'll work just fine for now :)
