### ISSUE TITLE
Throat Spray in WZ

### ISSUE THREAD

**Issue by Twillight0420** [SmashMC-Development/Bugs-and-Issues#1579]
**Describe the Bug**
Throat Spray is being used in wz and does not stay after battle.

**To Reproduce**
Battle a Pokemon and use a voice move.

**Servers with the Bug**
Pixelmon Servers (WZ)

**Expected behavior**
Should stay and not disappear

**Comment by Mikirae** [comment]
Throat Spray is a consumable item, so it gets used up during battles.
"After the Pokémon holding Throat Spray uses a sound-based move, it consumes the item and its Special Attack is raised by one stage. Throat Spray is not used if the move fails, or finishes the battle."
