### ISSUE TITLE
Cannot use "Pwiki" on deoxys server

### ISSUE THREAD

**Issue by KingofTheThicc** [SmashMC-Development/Bugs-and-Issues#158]
**Describe the Bug**
Trying to do "/pwiki (pokemon) but it doesnt work
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Deoxys
**Expected behavior**
It says that I do not have permissions for the command
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Can you provide screenshots so that we can see the error message?

**Comment by KingofTheThicc** [comment]
![2021-05-21_16 28 06](https://user-images.githubusercontent.com/84548409/119194779-9895bf00-ba51-11eb-85d6-909949bff324.png)

**Comment by HackuJacku** [comment]
@KingofTheThicc - does this occur on all servers please? Please start to full out the format correctly because the lack of information provided is meaning it is taking longer to fix (this takes 30 seconds to fix but has taken longer due to the lack of information provided).

**Comment by HackuJacku** [comment]
Fixed on Deoxys.
