### ISSUE TITLE
Warzone logout bank clear bug

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1580]
**Describe the Bug**
whenever you log out while you still have a mon in the warzone bank it totally wipes the mon from existence requiring proof in logs for you to get it back 

**To Reproduce**
1. go to warzone
2. catch a mon
3. safeplace
4. logout log back in mon will be gone

**Servers with the Bug**
Please provide a list of which servers have this bug.
as far as i know zekrom 

**Expected behavior**
expected to have the mon still in warzone bank when i logged back in

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Paradis4432** [comment]
inactive
