### ISSUE TITLE
Inconsistency in prices in shop

### ISSUE THREAD

**Issue by FadeFire** [SmashMC-Development/Bugs-and-Issues#1582]
**Describe the Bug**
Under the /shop you can find inconsistency in prices. an example of this is Ink Sacs.

under mob drops 1 Ink sac costs $50
under Dyes 1 ink sac costs $3.125 (16 for $50)

**To Reproduce**
1. Go to /shop
2. Click on mob drops/ dyes
3. See the inconsistency as listed above

**Servers with the Bug**
All realms

**Expected behavior**
Price-adjustments for affected items

**Screenshots**

![2022-12-18 (12)](https://user-images.githubusercontent.com/93608157/208316279-3291fd89-7ed3-444d-a179-d3c966faa19c.png)
3608157/208316258-63da2642-6a35-4090-9ab6-1630df63f9fa.png)
![2022-12-18 (11)](https://user-images.githubusercontent.com/93608157/208316387-c6667185-320e-4826-ab2e-76d74857019f.png)

**Comment by Superfire96** [comment]
Was fixed
