### ISSUE TITLE
Wondertrade issue

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1583]
**Describe the Bug**
Wondertrade does not correctly show the breedable status. 

**To Reproduce**
1. Take a mon that is unbreedable (Do /unbreed slot#)
2. Do /wt
3. Hover over it
4. See issue

**Servers with the Bug**
All

**Expected behavior**
Showing the status correctly

**Screenshots**
![2022-12-21_11 37 12](https://user-images.githubusercontent.com/94211853/208887732-0e4428b5-f9dc-4519-89d2-d3c1231a95fd.png)
![2022-12-21_11 37 27](https://user-images.githubusercontent.com/94211853/208887752-5aea534f-0dea-410e-bc7a-a0432f86fc51.png)

**Comment by Mikirae** [comment]
This should be fixed for next restart. Thank you :D
