### ISSUE TITLE
Fossil Room

### ISSUE THREAD

**Issue by The-Dudest** [SmashMC-Development/Bugs-and-Issues#1584]
**The last two rows in the fossil room at spawn do not close the door in Kyogre Server.**

**To Reproduce**
1. Go to 'spawn fossil room'
2. Step on 'the pressure plates in the back two rows'

**Servers with the bug**
At least kyogre. I'm not on the other ones. 

**Screenshots**
'N/A'.

**Additional context**
 First time on github. The server mods told me to do this.

**Comment by Superfire96** [comment]
Was fixed and added back the elevator for the second floor too
