### ISSUE TITLE
cant remove my gardevoirs aura and i hate its aura 

### ISSUE THREAD

**Issue by DSoulless303** [SmashMC-Development/Bugs-and-Issues#1588]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
The issue with this was fixed, /aura remove slot
