### ISSUE TITLE
/Dex does not work

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1589]
**Describe the Bug**
The /Dex command does not work on Reshiram and players are unable to claim any rewards, which results in the chat being flooded with claim notifications.

**To Reproduce**
1. Go to Reshiram
2. Type in /dex
3. Nothing happens

**Servers with the Bug**
Only Reshiram

**Expected behavior**
The gui should pop up in which players can claim their dex rewards ect.

**Additional context**
Tried out all additional commands, there is no way to open the gui otherwise

**Comment by DinglePringleUwU** [comment]
It seems like this issue has been fixed since. Unsure if this was fixed automatically or manually. If automatically then it could return. Can be closed.

**Comment by Paradis4432** [comment]
inactive
