### ISSUE TITLE
Yveltal can't learn defog on Jirachi

### ISSUE THREAD

**Issue by Ryan1595** [SmashMC-Development/Bugs-and-Issues#159]
**Describe the Bug**
Yveltal can't learn defog from /buymoves or the move tutor in /warp mart

**Servers with the Bug**
I don't know, as I don't have a Yveltal on other servers.

**Expected behavior**
That Yveltal can learn defog

**Screenshots**
N/A

**Additional context**
According to showdown and multiple pokemon wikis, it should be able to learn it

**Comment by Mikirae** [comment]
I believe this is going to be fixed by our dev soon.

**Comment by HackuJacku** [comment]
Covered as part of #133
