### ISSUE TITLE
Moltres fee not working

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Bugs-and-Issues#1590]
I wanted a moltres I filled up the orb and I went to /warp shrines to summon it, I saw that was needed 20k so I grinded the money to do it, I went there I summoned it but I did not lost the money

**Servers with the Bug**
I'm currently on kyurem but I don't know if it happens on other servers.

**Expected behavior**
Pay the 20000 coins fee.

**Screenshots**
'N/A'.

**Additional context**
 'N/A'.

**Comment by Mikirae** [comment]
This is fixed. Thank you! :D
