### ISSUE TITLE
Christmas present doesn't open

### ISSUE THREAD

**Issue by M4rconig** [SmashMC-Development/Bugs-and-Issues#1591]
**Describe the Bug**
I've been searching for all the 50 chistmas presents, but theres one that is bugged, and don't open
im on 49/50 presents, and still can't open it
im playing on zekrom server

**To Reproduce**
1.Enter on the "Zekrom" server
2. Go to he snowman behind the spawn
3. Rigth click on it
4. It will not open as it should

**Servers with the Bug**
Zekrom.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48354806/209906567-5221fd2b-eb97-42fd-b765-d9c34d651791.png)

**Additional context**
N/A.

**Comment by duervo** [comment]
That's a visual bug! all presents work perfectly fine! There must be a present you missed!

**Comment by jantjewieger** [comment]
Event is now over but I tested it and all presents were claimeable. As duervo said this could've been just a visual bug where it shows a presents with particles but in reality you had already claimed it. Closing this up
