### ISSUE TITLE
Reward claim paper not giving specific region mons

### ISSUE THREAD

**Issue by itsupmy** [SmashMC-Development/Bugs-and-Issues#1594]
**Describe the Bug**
when you redeem a specific mon paper and you specify the type per say hisuian zoroark it doesnt give it to you only the normal zoroark 

**To Reproduce**
1. get a specific mon paper
2. run / reward claim and choose your mon and its region
3. confirm
4. See you got a normal pokemon insted of the region pokemon

**Servers with the Bug**
reshiram

**Expected behavior**
given the correct form pokemon

**Screenshots**
N/A
**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
