### ISSUE TITLE
Nincada Evo

### ISSUE THREAD

**Issue by NetherGoddess** [SmashMC-Development/Bugs-and-Issues#1596]
Nincada not giving Shedinja when evolving

Evolve Nincada with an empty party slot and a reg pokeball in your inv

Reshiram

When evolving Nincada its supposed to give you Shedinja and Ninjask

N/A
 
N/A

**Comment by Mikirae** [comment]
This is unfortunately a Pixelmon bug that will hopefully be fixed next version!
