### ISSUE TITLE
Certain battlepass rewards not being given when claiming

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#1597]
**Describe the Bug**
Some of the battlepass reward items were not given to me when I claimed several levels of rewards. I claimed level 64 to 67 and only the common lucky block was given to me.

**To Reproduce**
1. Go to Rayquaza
2. Type the battlepass command (/battlepass)
3. Have level 64 to 67 to claim ig?
4. Claim and see only the common lucky block being given.

**Servers with the Bug**
Only play Rayquaza.

**Expected behavior**
I expected the rare candies, Fusion shard and assault vest to be given to me when claiming.

**Screenshots**
N/A.

**Additional context**
I did have trouble collecting rewards before this was resolved in ticket #57330 on the smash discord.

**Comment by Paradis4432** [comment]
inactive
