### ISSUE TITLE
Players have a error saying 'you have too many pokemon breeding right now'.

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Bugs-and-Issues#16]
**Describe the Bug**
Players have a error saying 'you have too many pokemon breeding right now'. 

**To Reproduce**
1. Go to Smashmc.
2. Click on darkrai.
3. start breeding.
4. After many breeding, it will state the error.

**Servers with the Bug**
Darkrai

**Expected behavior**
Players are not supposed to be limited to a few breeding stations

**Screenshots**
https://cdn.discordapp.com/attachments/832387179505254440/832387501171277824/2021-04-15_23.46.05.png

**Additional context**
N/A

**Comment by HackuJacku** [comment]
This isn't a bug, this is an intended change - see upcoming changelog tomorrow.
