### ISSUE TITLE
Sitrus berry gone after 8.2

### ISSUE THREAD

**Issue by AlphaRay01** [SmashMC-Development/Bugs-and-Issues#160]
After the new 8.2 update I noticed that the berries I had on pokemon as held items disappeared and were no where to be found. 
For example the sitrus berry on my poliwrath just disappeared when I never even removed it as held item from him.
Berries shouldn't disappear on pokemon after updates, I have only seen this bug happen on Kyogre so far but it's likely it happened on all servers.

**Comment by Mikirae** [comment]
I haven't heard of this issue. Know of anyone else who had this issue?

**Comment by AlphaRay01** [comment]
I know that DiegoKek had the same issue when he came online wanting to sell me one but realised all of his were gone as well.

**Comment by Mikirae** [comment]
So all held item Sitrus Berries are gone? Or just all Sitrus Berries in general?

**Comment by AlphaRay01** [comment]
Uh from my experience that would be all Sitrus Berries since I dont think DiegoKek had all of them on his pokemon as held items.

**Comment by Mikirae** [comment]
Will ask around and see if anyone else had those issues. Thanks for reporting it :)

**Comment by HackuJacku** [comment]
After asking around, this has only occurred in this instance and has not happened since. We're honestly unsure what occurred and unable to look into it further.
