### ISSUE TITLE
Gym bug

### ISSUE THREAD

**Issue by TommyT1TWhiler** [SmashMC-Development/Bugs-and-Issues#1600]
**Describe the Bug**
When you are battling the gyms you can do /endbattle and you leave. However the timer doesn't start so you can just rebattle the gyms.

**To Reproduce**
1. Go to /warp gyms
2. engage into a battle with one of the gyms members
3. when losing do /endbattle
4 re-engage into the battle

**Servers with the Bug**
All of the servers 

**Expected behavior**
you shouldnt be able to do /endbattle in the gyms

**Screenshots**
Dont have

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
