### ISSUE TITLE
Pursuit Bug 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#1601]
Pursuit Is Bugged 

**To Reproduce**
1. Go to pixelmon 
2. Click on pursuit
3. The pursuit effect will last for multiple turns and happens whenever the opponent switches out even if pursuit is not clicked or even if the pursuit mon is not in battle 

**Servers with the Bug**
All 

**Expected behavior**
Pursuit Should only happen once when its clicked 

**Screenshots**
 N/A

**Additional context**
I do believe its a pixelmon bug but I'm not completely sure so I would just ban it in wz till its fixed

**Comment by Paradis4432** [comment]
inactive
