### ISSUE TITLE
Keystone

### ISSUE THREAD

**Issue by UrSillyGirl** [SmashMC-Development/Bugs-and-Issues#1602]
**Describe the Bug**
I beat a mega beedrill boss and got a keystone. When I tried to use it my character did this weird glitch and there is some gray and rainbow thing coming off me that attaches to pokemon or pokeball loot.

**To Reproduce**
Beat a mega boss
Get a keystone
Try to use it
Then you/it glitches out.

**Servers with the Bug**
I only know it's on the zeckrom server rn.
**Expected behavior**
I expected to be able to use my keystone once I got it.

**Screenshots**
![idk](https://user-images.githubusercontent.com/122944213/213037778-34b91ea4-bb80-441b-887f-8f6b2396d132.png)

**Comment by Paradis4432** [comment]
inactive
