### ISSUE TITLE
/unbreed command bug

### ISSUE THREAD

**Issue by PescadoMan** [SmashMC-Development/Bugs-and-Issues#1603]
**A clear and concise description of what the bug is:**
If a person forgets to /unbreed their Pixelmons before they go into the warzone, then you lose. Once they are out, due to loss, they can /unbreed their Pixelmon.

**To Reproduce:**
Go to pixelmon
Go into warzone
Lose in warzone
/unbreed Pixelmon you forgot to unbreed

**Servers with the Bug**
All Servers

**Expected Behavior**
You shouldn't be able to because it is a player's mistake. They should have done that before going into the warzone.

**Screenshots**
N/A

**Additional Context**
I believe the command should be disabled after the player loses after the warzone until the winning player picks a Pixelmon.

**Comment by Paradis4432** [comment]
inactive
