### ISSUE TITLE
/Vote rewards not being received on Kyurem

### ISSUE THREAD

**Issue by TnGxCYCLONE** [SmashMC-Development/Bugs-and-Issues#1604]
**Describe the Bug**
This bug is plain and simple. You do /votelast and vote for the server's voting pages correct? Then afterwards, no rewards such as keys or Voting points are received.

**To Reproduce**
1. /votelast
2. select all 6 sites
3. vote for all 6 sites
4. ingame there is no chatlogs for rewards, no keys given, or points given at all.

**Servers with the Bug**
Kyurem(Seems to be the only one)

**Expected behavior**
I expected to vote for the server and receive rewards like normal. But after these new Pixelmon updates from 9.1.0-9.1.2 or Server issues may have complicated things.

**Screenshots**
N/A (Don't need to, Try it for yourself and you will see that no rewards are given)

**Additional context**
It is just ridiculous to have bought a rank on Kyurem server, for it to just be buggy all the time. Devs dont seem like they care about it as Gyms still are bugged too.

**Comment by Paradis4432** [comment]
inactive fixed

**Comment by Paradis4432** [comment]
inactive fixed
