### ISSUE TITLE
/Dex Missing Pokemon Issue

### ISSUE THREAD

**Issue by Samkillzz** [SmashMC-Development/Bugs-and-Issues#1605]
**Description of the bug**

Clicking the ''Missing Pokemon'' Option in /dex does not bring you to the list of missing pokemon.

**To Reproduce**

1. /dex
2. Click on Missing Pokemon

**Servers with the Bug**
All servers

**Expected behavior**
I expected to be able to look at my Missing Pokemon :(

![image](https://user-images.githubusercontent.com/120652662/213886744-d5cf825b-579f-4d3a-b44c-f4b834e7c020.png)

**Comment by Paradis4432** [comment]
fixed
