### ISSUE TITLE
Aegislash bug

### ISSUE THREAD

**Issue by Samkillzz** [SmashMC-Development/Bugs-and-Issues#1606]
**Describe the Bug**
Aegislash attacks using the stats it has in the defence form instead of the attack form

**To Reproduce**
(Bug was in warzone but haven't tested it outside)
1. Battle with aegislash
2. Click on attacking move
3. See that you are dealing less damage than you should be doing

**Servers with the Bug**
Zekrom (Have not tested the other servers)

**Expected behavior**
Deal my damage using the attack form stats
**Screenshots**
N/A

**Additional context**
N/A.

**Comment by jantjewieger** [comment]
This is unfortunately a pixelmon bug and thus not something we can fix. Please report it to their tracker. Closing this up
