### ISSUE TITLE
Pokemon don't naturally spawn in the raids

### ISSUE THREAD

**Issue by Samkillzz** [SmashMC-Development/Bugs-and-Issues#1607]
**Describe the Bug**
Pokemon don't spawn in the raid dens unless a wishing piece is used

**To Reproduce**
1. Go to ultra space
2. Walk for long time
3. Realize that you have went by 50 raid dens but none of them had a pokemon in them

**Servers with the Bug**
All Servers

**Expected behavior**
Find pokemon in the raids

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
