### ISSUE TITLE
/warp safari issue

### ISSUE THREAD

**Issue by arska1** [SmashMC-Development/Bugs-and-Issues#1608]
**A clear and concise description of what the bug is :** 
If a player tries to /warp safari on zekrom it brings them to a forest biome.

**To Reproduce** :
Go to pixelmon
Go into Zekrom
/warp safari

**Servers with the Bug :**
Zekrom

**Expected Behavior :**
It should warp you to a safari biome

**Screenshots :**
N/A

**Additional context :**
The cords on the safari warp is missplaced.

**Comment by Paradis4432** [comment]
inactive fixed
