### ISSUE TITLE
Skeledirge which is OU can be used in warzone

### ISSUE THREAD

**Issue by Aller12337** [SmashMC-Development/Bugs-and-Issues#1609]
**Describe the Bug**
Skeledirge pokemon can be used in warzone, but its gen9 and it shouldnt be allowed in natdex gen 8 uu

**To Reproduce**
1. Go into wz with a lvl 100 Skeledirge

**Servers with the Bug**
I'm pretty sure its all servers, but what i can confirm is that it works on Kyogre

**Expected behavior**
You shouldn't be able to use it because its an gen9 and it shouldnt be allowed in natdex gen 8 uu

**Screenshots**
N/A

**Additional context**
Its very OP and its been abused alot in warzone!

**Comment by Paradis4432** [comment]
inactive
