### ISSUE TITLE
Cramorant Shadow texture

### ISSUE THREAD

**Issue by FadeFire** [SmashMC-Development/Bugs-and-Issues#1610]
**Describe the Bug**
The base form of Cramorant doesn't have a shadow texture.

**To Reproduce**
1. Get a chisel
2. Make a cramorant statue
3. Go to "palette" and see only the shiny version being available.

**Servers with the Bug**
All

**Expected behavior**
Investigation on this, aswell as a shadow texture being added for the standard form of cramorant.

**Screenshots** First shows for standard form of cramorant, second one shows for gorging, where the texure is available.
![image](https://user-images.githubusercontent.com/93608157/214408815-93d359d9-80bf-4f7e-b9a3-376220c091f7.png)

![image](https://user-images.githubusercontent.com/93608157/214409058-d8a8973c-4f99-4f3b-8e27-a399369bd275.png)

**Comment by Paradis4432** [comment]
inactive fixed
