### ISSUE TITLE
/texture(s) link

### ISSUE THREAD

**Issue by Samkillzz** [SmashMC-Development/Bugs-and-Issues#1611]
**Describe the Bug**
The page you get to when doing /textures or /texture does not exist

**To Reproduce**
1. /textures or /texture in game
2. click the link
3. See that the page does not exist

**Servers with the Bug**
All servers

**Expected behavior**
I expected to be able to download the texture pack from the link

**Screenshots**
![image](https://user-images.githubusercontent.com/120652662/214462064-7a692eb5-0fd2-47ea-b4f7-7a48538559aa.png)

**Additional context**
Its in french, it translates to basically '' cant find the page of this webiste''

**Comment by Superfire96** [comment]
This was fixed
