### ISSUE TITLE
Raid Dens bug

### ISSUE THREAD

**Issue by Raymond-web** [SmashMC-Development/Bugs-and-Issues#1613]
**Describe the Bug**
Non of the raid dens will be active unless a wishing piece is being used

**To Reproduce**
Go and check the raid dens one by one non of them will be active

**Servers with the Bug**
kyogre(but most likely all)

**Expected behavior**
Raid dens should be active every day cycle in the game although not all dens but at least 2-3 out of 10 ig

**Screenshots**
NA

**Additional context**
NA

**Comment by Paradis4432** [comment]
inactive
