### ISSUE TITLE
Warzone Mega Charizard Bug

### ISSUE THREAD

**Issue by Samkillzz** [SmashMC-Development/Bugs-and-Issues#1615]
**Describe the Bug**
After testing a bit, I have come to realize that after mega evolving charizard into Y, switching it out and coming back in twice in the battle makes it transform into mega charizard x on the second switch.

**To Reproduce**
1. Go to Warzone
2. Battle someone
3. Mega evolve into charizard Y and switch out, then come back in, then switch out, then come back in.
4. See that your charizard is Mega X instead of the previous Mega Y

**Servers with the Bug**
Kyogre( Have not tested on all servers, but probably all of them)

**Expected behavior**
Not have my charizard do that
**Screenshots**
Clip: https://medal.tv/games/minecraft/clips/TmCnCRn9ZFNMX/d1337szrrlru?invite=cr-MSxQTTksMTYxNjQzNDUzLA

**Additional context**
While i did test out a bit, i didnt test that much and could be wrong about how it works, but i am pretty certain of myself.

**Comment by Paradis4432** [comment]
inactive
