### ISSUE TITLE
valentines vulpix

### ISSUE THREAD

**Issue by BigChungv2** [SmashMC-Development/Bugs-and-Issues#1622]
**Describe the Bug**
Made a ticket about getting valentines vulpix from crates and it being normal texture, was advised by mod to make github about it as there is no texture on the server for valentines vulpix

**To Reproduce**
get valentines vulpix, will be normal texture

**Servers with the Bug**
i guess all of them

**Expected behavior**
should be valentines texture

**Comment by Paradis4432** [comment]
inactive fixed
