### ISSUE TITLE
zoroark not turning up in battles

### ISSUE THREAD

**Issue by jordyboy50** [SmashMC-Development/Bugs-and-Issues#1624]
so i was battling in wz and zoroark was in my team 
it copied a pokemon from my team in my party but when you switch to zoroark aka the copy of the pokemon as that 
it doesnt switch and it goes away from the party in the battle
and when all your mons are dead you get stuck since the zoroark dissapeared

![image](https://user-images.githubusercontent.com/125771658/219902486-de60bed0-5a94-4e25-aa74-fb7bb827b20b.png)

**Comment by jordyboy50** [comment]
might been becuase i get /endbattled in wz tho not sure
with him and then it happened

**Comment by Paradis4432** [comment]
inactive
