### ISSUE TITLE
tried joining the tournament and it did not work

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1627]
**Describe the Bug**
tournaments not working on zekrom

**To Reproduce**
have the tournament start ask players to join and try to join

**Servers with the Bug**
Zekrom

**Expected behavior**
expected to be able to join the tournament 

**Screenshots**

![javaw_XptKyXCUS0](https://user-images.githubusercontent.com/120758795/221357253-d709612b-9503-43d8-be12-8e915cc0d68e.png)
![javaw_SuPHfsan8q](https://user-images.githubusercontent.com/120758795/221357254-f2fa8982-c319-450c-a39e-d11c031ff8a4.png)
![javaw_7Txrn16S4V](https://user-images.githubusercontent.com/120758795/221357255-37a1fb6d-7b1d-4ab5-b1ba-64cc8197de83.png)

**Comment by Superfire96** [comment]
Was fixed yesterday :c
