### ISSUE TITLE
some of my pokemon are not evolving

### ISSUE THREAD

**Issue by Evee1F** [SmashMC-Development/Bugs-and-Issues#1628]
**Describe the Bug**
my fletchinder is not evolving

**To Reproduce**
???
**Servers with the Bug**
groudon

**Expected behavior**
i was grinding lv for my froakie and used my fletchinder to grind up froakie and i was so exited for my talonflame but he never evolved.
same for my duosuion at same day.
but my froakie is now a grayninja werd right??

**Screenshots**
N

**Additional context**
N

**Comment by Evee1F** [comment]
my fletchinder is lv 50 and has not evolved.
i was grinding lv for my froakie and used my fletchinder to grind up froakie and i was so exited for my talonflame but he never evolved.
same for my duosuion at same day.
but my froakie is now a grayninja werd right??

**Comment by GlideFalcon** [comment]
I have the same problem on the rayquaza server. My rookidee is level 21 and it was supposed to evolve at lvl 18

**Comment by Paradis4432** [comment]
sorry for the late response, is this still active?

**Comment by Paradis4432** [comment]
inactive
