### ISSUE TITLE
battle tower gives waiting or no ui glitch alot

### ISSUE THREAD

**Issue by Fordlincoln3351** [SmashMC-Development/Bugs-and-Issues#1629]
i was in battle tower with a good streak and its gave me the no ui screen so i couldnt continue battle it was /endbattled but i was on a high streak and now cant battle until tomorrow is there anyway i would be able to rebattle it today?
 
its also dont this a few times once yesterday and twice today

username is Fordlincoln3351 and im on kyurem

**Comment by Paradis4432** [comment]
inactive
