### ISSUE TITLE
Votes don't Register on Kyurem Server

### ISSUE THREAD

**Issue by QuintessentialStu** [SmashMC-Development/Bugs-and-Issues#1631]
**Describe the Bug**
Votes won't register on the Kyurem server

**To Reproduce**
Vote on any and all voting sites for SmashMC
Log onto Kyurem Server
go to crates
right click on the vote crate

**Servers with the Bug**
Kyurem

**Expected behavior**
There should be messages in chat that say users got a vote crate key and $500
And users should be able to right-click on the vote crate and obtain rewards

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
It's now fixed
