### ISSUE TITLE
hi, i came back to playing on ur server after month and 3 stacks of my pokeballs change thier name and are ussles, cant even throw it, there are stackable and i tried to remove them from eq. and it didnt fix it, its realy good amount of pokeball for me

### ISSUE THREAD

**Issue by ValBreonx** [SmashMC-Development/Bugs-and-Issues#1634]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
fixed
