### ISSUE TITLE
Battle tower shop not giving items when bought

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#1635]
**Describe the Bug**
Whenever u buy smth from the battle tower shop with ur BP, it doesn't give it to u in ur inventory
**To Reproduce**
1. Go to warp battle tower 
2. Click on battle tower shop npc
3. Buy something from the shop
4. It shows that you buy it in the chat but it doesn't show up in your inventory 

**Servers with the Bug**
From what I have seen so far, it's every server.

**Screenshots**
N/A
**Additional context**
N/A

**Comment by Paradis4432** [comment]
fixed
