### ISSUE TITLE
pokemon paintings inside claims can be broken

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1636]
**Describe the Bug**
so theres a pixelmon item called the pokemon painting its 4 paintings put together and its a large painting you can put pokemon photos on anyone if they have trust or not in your claim can break them and steal them and the photos.

**To Reproduce**
1.make a pokemon painting and place it
have someone come to your claim that is not trusted
have them break them and take them 
**Servers with the Bug**
Zekrom most likely all of them

**Expected behavior**
i expected to have the painting be safe in my claim 

**Screenshots**
'N/A'.

**Additional context**
https://medal.tv/games/minecraft/clips/XIYIuS1hxEWmf/eb8J1N4p1cdz?invite=cr-MSxMNTksMTIwNzU0Nzks

**Comment by Paradis4432** [comment]
inactive
