### ISSUE TITLE
Uncommon lucky blocks saying that theyre spawning shiny floettes but only giving normal

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1637]
**Describe the Bug**
from what ive seen so far when you get a uncommon lucky block and open it and it says it spawns a shiny floette that everytime it comes out normal.

**To Reproduce**
1. Get a uncommon lucky block
2. open it get shiny floette
3. see thats its a normal red one

**Servers with the Bug**
Rayquaza (could be more)

**Expected behavior**
expected to get a shiny floette

**Screenshots**
Add any other context about the problem here. If nothing, please add 'N/A'.
![2023-03-02_17 36 24](https://user-images.githubusercontent.com/120758795/222611584-cdb805fb-39a9-4fd1-bd40-43b46204f780.png)
![2023-03-02_04 17 15](https://user-images.githubusercontent.com/120758795/222611613-77d44374-922d-48a6-aa66-9eb8cfa4d7ac.png)

**Comment by Paradis4432** [comment]
is this still active system?
