### ISSUE TITLE
WZ effects in overworld

### ISSUE THREAD

**Issue by QuintessentialStu** [SmashMC-Development/Bugs-and-Issues#1638]
**Describe the Bug**
after /end battling in wz, you are tp back to the overworld and given the effects of wz. The timer is stopped, glow is still enabled, particles and everything. Can even see wz chat when I'm back in the overworld

**To Reproduce**
fight a wild mon in wz and do /endbattle

**Servers with the Bug**
Groudon, Rayquaza, and presumably all servers

**Expected behavior**
Either I'm not able to endbattle in wz because commands are limited, or the battle ends and I'm still in wz because timer is still active

**Screenshots**
![image](https://user-images.githubusercontent.com/55354034/222871224-1c5b7d34-8a2b-4521-9a18-f637a3a7f6b3.png)
![image](https://user-images.githubusercontent.com/55354034/222871258-39beb82f-1fae-42ce-b6bf-85d46bed10fd.png)
![image](https://user-images.githubusercontent.com/55354034/222872113-edf93ccc-9a7d-4d4e-a819-73602eb161e5.png)

**Additional context**
N/A

**Comment by QuintessentialStu** [comment]
I also have a glowing effect permanently attached to me, re-logging in does not get rid of it.

**Comment by Paradis4432** [comment]
fixed
