### ISSUE TITLE
M1 L bozo (Battletower Issue)

### ISSUE THREAD

**Issue by Samkillzz** [SmashMC-Development/Bugs-and-Issues#1639]
**Describe the Bug**
battletower has no npc's on both reshi and kyogre

**To Reproduce**
1. Go to Kyogre or Reshiram
2. /Warp Battletower
3. See that the Npc's are no where to be found

**Servers with the Bug**
Reshiram and Kyogre

**Expected behavior**
Have existant Npc's

**Screenshots**
![image](https://user-images.githubusercontent.com/120652662/222939722-1b20fbe0-6917-4941-afd2-10419d09657a.png)
![image](https://user-images.githubusercontent.com/120652662/222939727-868abd60-7eae-4636-b4b8-0c446bf57127.png)

**Additional context**
L bozo M1

**Comment by Paradis4432** [comment]
inactive
