### ISSUE TITLE
I cant claim my aura key

### ISSUE THREAD

**Issue by SVSR3D** [SmashMC-Development/Bugs-and-Issues#1640]
**Describe the Bug**
So I claimed my daily rewards and it was an aura key. It shows that i have one when i do /keys, but it is not letting me claim it
**To Reproduce**
1. i go to warp crates 
2. i try and claim it
3. it says i dont have a key

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre
[latest.log](https://github.com/SmashMC-Development/Bugs-and-Issues/files/10890745/latest.log)

**Expected behavior**
I expected to be able to claim my reward.
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
System error has been the mod helping me with this

**Comment by Mikirae** [comment]
Fixed. Thank you :D
