### ISSUE TITLE
Exclusivecrate key problem

### ISSUE THREAD

**Issue by KingHerobrine16** [SmashMC-Development/Bugs-and-Issues#1641]
**Describe the Bug**
I bought a exclusive crate key on the store for 14.99. When I got back on the server and the key was added to my account I went to the crates to figure out which crate it would open, but it wouldn't open any of the special crates that are available.

**Servers with the Bug**
Groudon (only one I know of so far)

**Expected behavior**
When I bought the key I expected it to open either the crimson crate or the galaxy crate

**Screenshots**
![2023-03-05_04 03 56](https://user-images.githubusercontent.com/127015395/222951536-ebb5f6bb-156e-4d45-a329-a7a3ac0e928c.png)
![2023-03-05_04 03 59](https://user-images.githubusercontent.com/127015395/222951537-905dedd7-47d8-450e-b90f-b6f5b716794c.png)
![2023-03-05_04 03 42](https://user-images.githubusercontent.com/127015395/222951539-a2ac5a95-300e-4728-b93e-bbee73d1830f.png)
![2023-03-05_04 03 50](https://user-images.githubusercontent.com/127015395/222951541-5c5ad5a4-3fe5-4324-ad01-37228d32e5bc.png)
![2023-03-05_04 04 07](https://user-images.githubusercontent.com/127015395/222951572-4f6c2b0d-8193-4f1a-bb2a-93cf9633fbc3.png)
![2023-03-05_04 04 15](https://user-images.githubusercontent.com/127015395/222951575-cce32c14-59fa-497b-8419-c3dbf0fe31a5.png)

**Additional context**
Screenshot of buy menu
![2023-03-05_04 08 25](https://user-images.githubusercontent.com/127015395/222951699-e8589dfd-ce2a-41a9-90db-16b4354a0d95.png)

**Comment by Superfire96** [comment]
Was fixed

**Comment by KingHerobrine16** [comment]
Thank you for the help.
