### ISSUE TITLE
Reward for BingoCard completion is always the same on Rayquaza

### ISSUE THREAD

**Issue by IceSlimGuys** [SmashMC-Development/Bugs-and-Issues#1642]
**Describe the Bug**
When you fully complete your BingoCard on Rayquaza, you will **always** receive 20.000$ and a FusionShard as a reward.

**To Reproduce**
1. Log on to Rayquaza
2. Check your BingoCard
3. Catch every Pokemon on it in order to fully complete it
4. Server will always reward you with 20.000$ and a FusionShard

**Servers with the Bug**
Rayquaza only ? Helpers told me that people received different rewards each time on a different server

**Expected behavior**
Fix this issue please, i'm starting to hate those Shards

**Screenshots**
N/A

**Additional context**
Made a Ticket about that issue on Discord (#60586) and they told me to go here.
Also the classic Bingo Reward works perfectly fine, no need to investigate on that.

**Comment by Paradis4432** [comment]
fixed
