### ISSUE TITLE
Pokemon not evolving

### ISSUE THREAD

**Issue by GlideFalcon** [SmashMC-Development/Bugs-and-Issues#1644]
My Rookidee hasn't evolved
I was trying to evolve my bounsweet when I started to use rookidee because Bounsweet's hp was too low, at the end of the battle my rookidee didn't evolve even though it was level 18

I was playing on the Rayquaza server

When Rookidee gets to level 18 it should evolve

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
