### ISSUE TITLE
Rayquaza Electric Gym not giving rewards 

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1645]
**Describe the Bug**
ray's electric gym when you beat it is not giving any rewards. even shows in log that its been beat but does not show any log of any rewards sent out.

**To Reproduce**
1. go to the electric gym in ray
2 fight it
3. win
4. see that there is no rewards sent out 

**Servers with the Bug**
Rayquaza.

**Expected behavior**
expected to get the rewards from the gym. 

**Screenshots**

![image](https://user-images.githubusercontent.com/120758795/223254787-2637ed19-9753-4fed-8824-aac86621ab23.png)

**Additional context**
'N/A'.

**Comment by Paradis4432** [comment]
is this still active system?
