### ISSUE TITLE
BattleTower attempts only being at 1

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1646]
**Describe the Bug**
so i went to the battletower to test attempts and when i ran from my first attempt i was not allowed to do anymore attempts. i personally have not done any attempts in over a week.

**To Reproduce**
1. Go to BattleTower 
2. Run an attempt either loose or run
3. get sent out of the battle tower
4. no longer able to do anymore attempts for the day

**Servers with the Bug**
Zekrom, rayquaza could be more

**Expected behavior**
expected to have 2 more attmpts only got a single one for the day.

**Screenshots**
![javaw_kWfiOnTdF5](https://user-images.githubusercontent.com/120758795/223358374-bcbed702-16d4-4a78-a41a-f5d1c5cc7e18.png)

![javaw_fFFeUahn2G](https://user-images.githubusercontent.com/120758795/223358307-f7253f88-ecc3-4d1d-aa76-24bb4c6e7e3c.png)

**Additional context**
 'N/A'.

**Comment by andrewxc12** [comment]
I have also confirmed that I am having a similar issue (Dro0o: rayquaza server)

**Comment by Paradis4432** [comment]
is this still active system?
