### ISSUE TITLE
Battletower glitch with rocky helmet

### ISSUE THREAD

**Issue by andrewxc12** [SmashMC-Development/Bugs-and-Issues#1647]
**Describe the Bug**
Causing the opponents pokemon to faint by chip damage from a rocky helmet causes a glitch where the user is no longer able to proceed in the battle. 

**To Reproduce**
1. Have the opponent make a contact move onto the user's pokemon that has a rocky helmet
2. The opponents pokemon must faint from chip damage to the rocky helmet
3. After the opponents pokemon faints, any action taken by the user does not progress the battle. Any selected move will fail

**Servers with the Bug**
Rayquaza server

**Expected behavior**
The expected behavior is that if the opponents pokemon faints due to chip damage from the rocky helmet, the user should be able to proceed with the battle. 

**Screenshots**
![image](https://user-images.githubusercontent.com/62809131/223494149-ba177d4e-d1d6-401f-bffa-0dd9c944ae3a.png)

**Additional context**
'N/A'.

**Comment by Paradis4432** [comment]
inactive
