### ISSUE TITLE
i get stuck in battle but not the guy i attack, this happened when he/her was trying to catch a mon and i battled him

### ISSUE THREAD

**Issue by 0mana** [SmashMC-Development/Bugs-and-Issues#1648]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by 0mana** [comment]
yeah the title says it all, this happened in wz

**Comment by Paradis4432** [comment]
inactive, fixed
