### ISSUE TITLE
Cannot unlink

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#1649]
**Describe the Bug**
When you link your account in discord but then when you to unlink your Minecraft account to link to another discord account, you cannot unlink. When you do /discord unlink, it says that you don't have permission to do so.

**Servers with the Bug**
Every server

**Expected behavior**
Expected to unlink and be able to link to another account easily
**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
