### ISSUE TITLE
Battletower Item Glitch

### ISSUE THREAD

**Issue by andrewxc12** [SmashMC-Development/Bugs-and-Issues#1650]
**Describe the Bug**
Purchasing the fusion shards from the battletower shop gives 5 Alolan TM 3's for Psyshock.

**To Reproduce**
1. Go to battletower shop and purchase the fusion shard for 80 battle points
2. Check inventory to see Alolan TM 3's for Psyshock

**Servers with the Bug**
Rayquaza

**Expected behavior**
The expected behavior is that if I select a fusion shard for purchase from the battletower shop, I should receive the fusion shard. 

**Screenshots**
![image](https://user-images.githubusercontent.com/62809131/223848007-8a399566-ae9d-4b21-b081-ec9677634295.png)
![image](https://user-images.githubusercontent.com/62809131/223849860-30fb081b-456c-4ec1-bfd2-9c14545cce21.png)

**Additional context**

One of these logs should contain the info. 
[2023-03-07-2.log.gz](https://github.com/SmashMC-Development/Bugs-and-Issues/files/10925242/2023-03-07-2.log.gz)
[2023-03-08-1.log.gz](https://github.com/SmashMC-Development/Bugs-and-Issues/files/10925244/2023-03-08-1.log.gz)

**Comment by Paradis4432** [comment]
inactive
