### ISSUE TITLE
Some Pokemon having illegal moves in battle-tower

### ISSUE THREAD

**Issue by KUCHIHA10** [SmashMC-Development/Bugs-and-Issues#1651]
**Describe the Bug**
When I was attempting the battle tower I came across a toxapex using slack off which to my knowledge and Pokemon showdown is illegal.

**To Reproduce**
1. Go to 'warp battletower '
2. Click on 'challange tower'
3. Attempt the tower and look out for Pokemon using moves you would think are unusual for them to use like toxapex using slack off.

**Servers with the Bug**
Found on kyurem but maybe on all servers.

**Expected behavior**
I expected that the toxapex did not have the move slack off but a basic competitive move set consisting of scald,bashful bunker, toxic and recover.

**Screenshots**
![image](https://user-images.githubusercontent.com/94144051/223858388-292ea96f-9920-46e9-a015-9d5acb614e3d.png)
![image](https://user-images.githubusercontent.com/94144051/223858451-8c390ce3-62a0-4462-9724-21744b8b22bb.png)

**Comment by Mikirae** [comment]
Fixed for next restart. Thank you!
