### ISSUE TITLE
Gts visually breaking 

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1652]
**Describe the Bug**
gts recently has updated to have a bunch of spots unused.

**To Reproduce**
1. do /gts
2. see the broken visuals on it

**Servers with the Bug**
Zekrom (probably all)

**Expected behavior**
expected gts to look as it did before

**Screenshots**

![javaw_XM2BP7NoMn](https://user-images.githubusercontent.com/120758795/223993956-8ba87fc8-f73c-4e8b-8775-078186e93533.png)

**Comment by Superfire96** [comment]
It is not broken, more thing will be added in the future
