### ISSUE TITLE
Reshiram Tournament Claim

### ISSUE THREAD

**Issue by yesitsaura** [SmashMC-Development/Bugs-and-Issues#1653]
**Describe the Bug**
Tournament are on Reshiram server is unclaimed, players can place and break blocks

**To Reproduce**
Go to tournament area on Reshiram, and break/place a block

**Servers with the Bug**
Only know about Reshiram

**Expected behavior**
Claimed area so players cannot break/place blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/127437676/224121307-9c3dba70-19dc-44ae-83e4-ddea71e3b6c1.png)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
