### ISSUE TITLE
Battle tower attempts only resetting once you have completed all three

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1654]
**Describe the Bug**
so the battle tower attempts aren't resetting until you beat them all so if you do two then don't do the third one for lets say a week then when you come back you will only have 1 attempt to be able to use before you have to wait for your attempts to reset.

**To Reproduce**
1. go to the battle tower
2. do two attempts 
3. wait a day or more
4. come back to see you can only do one attempt before having to wait for your attempt reset timer.

**Servers with the Bug**
possibly all

**Expected behavior**
expected to have each try have a timer for its individual reset not having to finish all before the reset of the tries start over.

**Screenshots**
N/A'.

**Additional context**
N/A'.

**Comment by Paradis4432** [comment]
still active system?
