### ISSUE TITLE
crimson galar zapdos

### ISSUE THREAD

**Issue by PurpleVenom07** [SmashMC-Development/Bugs-and-Issues#1657]
Galarian Zapdos doesnt spawn with the crimsondawn texture even when its supposed to

**To Reproduce**
1. Go to warzone
2. make crimsondawn galarian zapdos spawn
3. catch it
4. and see it having no texture

**Servers with the Bug**
happened to me on reshiram but ive heard its happened to someone else(not sure who)

**Expected behavior**
when u catch the crimson galarian zapdos it will show no signs of having the texture even though it should have

**Screenshots**
N/A

**Additional context**
i got the texture back after making a ticket to get it fixed but since its happened twice with this specific pokemon and none of the others i caught it could be an issue that needs fixing incase others catch one and dont know that u can make a ticket to fix it

**Comment by Paradis4432** [comment]
inactive
