### ISSUE TITLE
Master ball glitch after not sold on gts

### ISSUE THREAD

**Issue by ZorgDeadshot** [SmashMC-Development/Bugs-and-Issues#1658]
**Describe the Bug**
After master ball wasnt sold on gts it gave it back as normal pokeball

**To Reproduce**

**Servers with the Bug**
smash mc 

**Expected behavior**
A refunded master ball?

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive fixed
