### ISSUE TITLE
Raid dens not allowing pokemon to be caught

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1659]
**Describe the Bug**
when you try to catch a pokemon in the raid dens  it just sits there and you cannot catch the mon.

**To Reproduce**
1. Go to a raid den
2. fight it
3. win
4. try to catch mon will not be able too.

**Servers with the Bug**
Rayquaza (possibly all)

**Expected behavior**
expected to be able to catch the pokemon or at least attempt to.

**Screenshots**
'N/A'.

**Additional context**
video file 
https://clipchamp.com/watch/WG3RR4fY5ab

**Comment by Paradis4432** [comment]
still active system?
