### ISSUE TITLE
Celebi Shrine took money with no spawn

### ISSUE THREAD

**Issue by KingofTheThicc** [SmashMC-Development/Bugs-and-Issues#166]
**Describe the Bug**
When trying to use a Celebi shrine that has been used before it prompts you to pay 30,000. I clicked and didnt know if it registered becuase a Celebi didnt spawn so I clicked it again. Then I saw two prompts in my chat that said that the shrine spawn failed and my money was gone ffor both clicks.
**To Reproduce**
1. Go to a Celebi shrine that has been used
2. Click on the shrine with the GS ball
3. Scroll to where it says confirm and click on it
4. See error and money gone with no celebi

**Servers with the Bug**
Please provide a list of which servers have this bug.
Deoxys
**Expected behavior**
I expected to pay 30,000 to get the celebi to spawn.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![2021-05-21_20 47 59_2](https://user-images.githubusercontent.com/84548409/119209911-72831580-ba77-11eb-87fe-8a200673269a.png)
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
