### ISSUE TITLE
Bingo cards

### ISSUE THREAD

**Issue by TommyT1TWhiler** [SmashMC-Development/Bugs-and-Issues#1660]
**Describe the Bug**
When you complete the entire bingo card you only receive the fusion shard as the last reward. I have done it 3 times now and only received the shard. 

**To Reproduce**

**Servers with the Bug**
All servers

**Expected behavior**
Being able to be given the rewards that are offered

**Screenshots**
![image](https://user-images.githubusercontent.com/109922955/224496917-74e7fe19-73fe-4256-bcb7-af343ed8d749.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Found the issue and fixed it :) Thank you!
