### ISSUE TITLE
Bug Gym On Rayquaza Did Not Give Me A Fusion Shard

### ISSUE THREAD

**Issue by hvincent34** [SmashMC-Development/Bugs-and-Issues#1661]
**Describe the Bug**
I beat the bug gym on rayquaza and I received all of the rewards except the fusion shard. It said in chat that I won one but it never got to my inventory.

**To Reproduce**
1. Go to 'the bug gym on rayquaza.'
2. Click on 'The "r" key on your keyboard to throw a pokemon at the gym leader, beat the gym.'

**Servers with the Bug**
Rayquaza

**Expected behavior**
I expected to get all of the rewards that it said I would get in chat after beating the gym.

**Screenshots**
![image](https://user-images.githubusercontent.com/89617598/224512634-11f22062-3f31-4cf6-9235-05a10522a881.png)
Chat after I beat the gym

![image](https://user-images.githubusercontent.com/89617598/224512639-abc619b1-31e6-447f-af5a-7eac2af72477.png)
My inventory after the gym.

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
