### ISSUE TITLE
Warzone command is not woking in zekrom

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1662]
**Describe the Bug**
when i try to type the command for warzone inside of zekrom nothing happens

**To Reproduce**
1. go to zekrom
2. do /wz
3. see nothing happens.

**Servers with the Bug**
Zekrom (possibly more)

**Expected behavior**
expected to be able to go into warzone.

**Screenshots**
 'N/A'.

**Additional context**
 'N/A'.

**Comment by Mikirae** [comment]
This has been fixed :)
