### ISSUE TITLE
tournaments not being able to be ended properly when they get stuck

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1665]
**Describe the Bug**
whenever we as helper end battle a random tournament right now its just giving random rewards and placements out to the players 
**To Reproduce**
1. have a tournament start
2. join and get stuck
3. have a helper come endbattle or kick 
4. see the fact it gives random rewards out.

**Servers with the Bug**
All

**Expected behavior**
expected as a helper to be able to endbattle the loser and have them be the loser 

**Screenshots**
 'N/A'.

**Additional context**
 'N/A'.

**Comment by Paradis4432** [comment]
fixed
