### ISSUE TITLE
./vote

### ISSUE THREAD

**Issue by TommyT1TWhiler** [SmashMC-Development/Bugs-and-Issues#1668]
**Describe the Bug**
Players aren't receiving the vote keys from /vote 

**To Reproduce**

**Servers with the Bug**
Atm only groudon

**Expected behavior**
I assume its something to do with the actual website however if not then be fixed :D

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by IceSlimGuys** [comment]
Rayquaza too !

**Comment by Mikirae** [comment]
What site is not giving the Vote Key here? I don't believe this would be on our end

**Comment by Paradis4432** [comment]
fixed
