### ISSUE TITLE
Skills not tracking on Zekrom in ultra space

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1669]
**Describe the Bug**
Logged in to play today went jumping around the ultra space noticed i was not gaining any acrobatics skill so decided to go mine and didn't get exp for skills there either.

**To Reproduce**
1. do anything with skills
2. see its not tracking any exp

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**
expecting to gain exp on skills.

**Screenshots**
 'N/A'.

**Additional context**
N/A

**Comment by Mikirae** [comment]
What block were you mining? It should work there, but potentially we don't have Ultra Blocks in the mining config.
Acrobatics is disabled there on purpose.

**Comment by SystemErrorCA** [comment]
ive been mining ultra space stone and ultra desert sandstone also acrobatics are working right now? lol

**Comment by Mikirae** [comment]
It should be not working in Ultra Space, which is what you said earlier. Is it not disabled there?

**Comment by Paradis4432** [comment]
inactive
