### ISSUE TITLE
Tournament in groudon completely broken

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1670]
**Describe the Bug**
was called to look into a tourny on groudon when i got there they had decided a winner of a battle to move the player stuck in battle forward to the next when they endbattled the loser of the rock/paper/scissors the person who won got the loss. then the other player in thr tourny got stuck in a choose mon selection screen causing me to have to kick them. then a player who was not even in the tournament got the win.
**To Reproduce**
1. go to groundon
2. ave a tourney start
3. have players get stuck 
4. then have them ended
5. next battle wont start because it cannot put the player into the battle because it registered as a loss

**Servers with the Bug**
id say all because tournaments have issues on every single server.

**Expected behavior**
expected to have the random tournament work properly

**Screenshots**
 'N/A'.

**Additional context**
 'N/A'.

**Comment by Paradis4432** [comment]
fixed
