### ISSUE TITLE
3/4 fossil rooms have 2 pressure plates that don't work

### ISSUE THREAD

**Issue by gabbermac** [SmashMC-Development/Bugs-and-Issues#1671]
**Describe the Bug**
Well, pretty self-explanitory, 2 Pressure plates in the fossil rooms do not close the door when stepped on

**To Reproduce**
1: go to the first 2 fossil rooms, or the right one in the back (left one works for some reason)
2: Step on the pressure plates, from the door go up 3 pressure plates, the third one, and the one above it will not work

**Servers with the Bug**
Kyurem (only one i'm on so far)

**Expected behavior**
Door does not close when stepped on these two pressure plates

**Screenshots**
See below
![issue](https://user-images.githubusercontent.com/127793661/224828027-3ee23780-33b3-487d-a1e7-5700954c5a5f.png)

**Additional context**
Might be the same for other servers, i'm unsure

**Comment by Paradis4432** [comment]
fixed
