### ISSUE TITLE
Not getting Vote rewards on voting sites.

### ISSUE THREAD

**Issue by VGIce** [SmashMC-Development/Bugs-and-Issues#1672]
When i vote on voting sites, sometimes it doesn't register that i voted on the server.

You vote on servers, and wait to see if you get keys or not.  I didn't for 2 websites.

Smashmc

I expected to get my $500 and vote keys

**Screenshots**
![Screen Shot 2023-03-13 at 2 46 16 PM](https://user-images.githubusercontent.com/115387310/224867938-3d6170e5-bd24-4beb-ae67-a9a06204d97e.png)
![Screen Shot 2023-03-13 at 2 48 28 PM](https://user-images.githubusercontent.com/115387310/224867940-1ffa23fc-7ddd-41ed-b5d2-b6de2d44d11a.png)
![Screen Shot 2023-03-13 at 2 45 52 PM](https://user-images.githubusercontent.com/115387310/224867943-f39afe68-c36a-4762-aab9-7916daa7e3a0.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive, fixed
