### ISSUE TITLE
voting for the server did not count

### ISSUE THREAD

**Issue by CyberFIowey** [SmashMC-Development/Bugs-and-Issues#1673]
nickname CyberFlowey
server Rayquaza

I have glossed on all 6 sites yesterday I got 6 vote points and was able to use vote crate! I did the same thing today, but I didn't get vote points and I won't be able to use vote crate

all proof
![2023-03-14_18-04-37](https://user-images.githubusercontent.com/66869211/225029840-b785b8b1-bcc5-4264-b849-80aaa5f2c20e.png)
![2023-03-14_18-04-27](https://user-images.githubusercontent.com/66869211/225029844-e0d8f2e7-cd2d-4c5f-ad07-c08120713ed8.png)
![2023-03-14_18-04-18](https://user-images.githubusercontent.com/66869211/225029846-ceaee815-743d-4922-b93b-2119feb758c0.png)
![2023-03-14_18-04-07](https://user-images.githubusercontent.com/66869211/225029849-0d90abc1-3beb-4e63-9924-ddd2aa5bf741.png)
![2023-03-14_18-03-50](https://user-images.githubusercontent.com/66869211/225029852-085de879-6b62-4ab6-97b8-15f641d71c1b.png)
![2023-03-14_18-03-27](https://user-images.githubusercontent.com/66869211/225029854-2edbaf13-da9b-4878-bdbd-a19b9ecf3d71.png)
![2023-03-14_17-58-46](https://user-images.githubusercontent.com/66869211/225029859-42207037-3045-48d3-9908-39f5d2459e0a.png)
![2023-03-14_17-57-57](https://user-images.githubusercontent.com/66869211/225029865-caf32b88-a6c1-4a33-a1b6-b2f2a41ee560.png)

**Comment by CyberFIowey** [comment]
2 vote lost 
![2023-03-15_21-52-36](https://user-images.githubusercontent.com/66869211/225414256-7254dcdd-a62f-43a4-9486-2fea531125b1.png)
![2023-03-15_21-52-55](https://user-images.githubusercontent.com/66869211/225414258-1f0f7272-4e25-46af-b99f-f5d696070916.png)
![2023-03-15_21-51-31](https://user-images.githubusercontent.com/66869211/225414252-cc816443-3b5b-48c2-8421-16c520c13db3.png)
![2023-03-15_21-52-22](https://user-images.githubusercontent.com/66869211/225414255-13152dcd-7e47-4a86-a678-792fdb72f63d.png)

**Comment by CyberFIowey** [comment]
![2023-03-15_22-15-18](https://user-images.githubusercontent.com/66869211/225414890-f3d5282d-9ddd-4b50-be87-6fc6c4a98423.png)

**Comment by CyberFIowey** [comment]
![2023-03-16_22-03-15](https://user-images.githubusercontent.com/66869211/225738750-c63ec786-890d-4bfa-829c-2d7c9fabcfa2.png)
![2023-03-16_22-02-54](https://user-images.githubusercontent.com/66869211/225738756-230c6744-f18c-4f85-b915-6276c964e9cc.png)
![2023-03-16_22-02-31](https://user-images.githubusercontent.com/66869211/225738760-3db38700-7b58-4dc6-b83d-f3592aeb3830.png)
![2023-03-16_22-02-07](https://user-images.githubusercontent.com/66869211/225738765-c88b812b-5795-4334-becc-c36f276bc6ed.png)
![2023-03-16_22-01-21](https://user-images.githubusercontent.com/66869211/225738767-b5377340-7b75-4544-b7ff-f3872199ee50.png)
![2023-03-16_22-01-13](https://user-images.githubusercontent.com/66869211/225738768-b9de1a20-7e9d-421f-8bc8-b7de19ea87bb.png)
![2023-03-16_22-01-07](https://user-images.githubusercontent.com/66869211/225738771-0e0a22ae-e14e-4f51-b708-a1e0a567ca4c.png)
![2023-03-16_22-00-42](https://user-images.githubusercontent.com/66869211/225738774-04dcc655-5625-46f2-ae1a-14acb9c39fbf.png)

**Comment by CyberFIowey** [comment]
![2023-03-18_00-34-24](https://user-images.githubusercontent.com/66869211/226036106-9263682c-a3c6-4976-8fd3-d15d19edddbd.png)
![2023-03-18_00-34-18](https://user-images.githubusercontent.com/66869211/226036122-6a2dfdad-3442-4b17-a821-80210fa893ea.png)
![2023-03-18_00-34-09](https://user-images.githubusercontent.com/66869211/226036129-d381dc9b-1306-42e5-88f5-152bc453dbe8.png)
![2023-03-18_00-33-54](https://user-images.githubusercontent.com/66869211/226036134-c707af9e-b065-48f0-b312-868e7cea27f2.png)
![2023-03-18_00-33-35](https://user-images.githubusercontent.com/66869211/226036139-67d97acb-bce7-42c0-9f9e-30e80871b6f8.png)
![2023-03-18_00-33-16](https://user-images.githubusercontent.com/66869211/226036142-eb520e60-be5a-4bd2-9fa2-bbe087f4a0b6.png)
![2023-03-18_00-32-39](https://user-images.githubusercontent.com/66869211/226036148-1029270d-fd08-436d-95be-be0b0fd40e92.png)
![2023-03-18_00-32-15](https://user-images.githubusercontent.com/66869211/226036152-d4fe6467-b386-4776-9341-7d3a009d6fdf.png)

**Comment by Paradis4432** [comment]
inactive, fixed
