### ISSUE TITLE
Pokemon not evolving

### ISSUE THREAD

**Issue by Tog-IV** [SmashMC-Development/Bugs-and-Issues#1675]
While training my Sewaddle and Trapinch I got both to the level they are supposed to evolve which is 20 for Sewaddle and 35 for Trapinch but neither are evolving. I tried to level them up further but they still wont evolve. I am playing on the Zekrom server in 9.1.3

**Comment by TakatoBunny** [comment]
I also have the same bug whenever I go out into the wild (./rtp) and my pokemons reaching required level, it would tell me that it evolved into itself which doesn't allow it to evolve to its higher stages. Zekrom server 9.1.3.

**Comment by Paradis4432** [comment]
inactive
