### ISSUE TITLE
Golisopod bosses cant be beaten in battle

### ISSUE THREAD

**Issue by honkhonk4207** [SmashMC-Development/Bugs-and-Issues#1676]
**Describe the Bug**
Golisopods bosses (every tier) cant be beaten. Battle ends without reward when they reach red HP.

**To Reproduce**
1. Go to boss tower
2. fight golisopod until 30% hp

**Servers with the Bug**
Rayquaza

**Expected behavior**
Golisopod dies and I get rewards.

**Screenshots**
video attached to this issue.

https://user-images.githubusercontent.com/127960958/225327382-b9e30be7-9bf6-4e5f-9b82-98cd7e840138.mov

**Additional context**
[N/A]

**Comment by Paradis4432** [comment]
inactive
