### ISSUE TITLE
Eggs won't hatch.

### ISSUE THREAD

**Issue by honkhonk4207** [SmashMC-Development/Bugs-and-Issues#1678]
**Describe the Bug**
Sometimes, I can run on the hatch track for 45 to 60 minutes without any eggs hatching when its supposed to take around 10 to 15 minutes using this ethod.

**To Reproduce**
1. Go to /warp hatch
2. add an egg to your party
3. run around and wait for it to hatch.
4. check if it took more than 15 minutes.

**Servers with the Bug**
Rayquaza

**Expected behavior**
an egg hatching after 15 minutes like usual or at least show the progression.

**Screenshots**
'N/A'.

**Additional context**
This bug gets fixed when the server restarts, but sometimes it takes a long time for it to restart so I can't hatch any eggs before then.

**Comment by Paradis4432** [comment]
inactive, fixed
