### ISSUE TITLE
My fusion pokemon are disfigured 

### ISSUE THREAD

**Issue by COOLDUDE7508** [SmashMC-Development/Bugs-and-Issues#1679]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Would just need to download the latest version of the texturepack
