### ISSUE TITLE
Galaxy zapdos and xurkitree are named wrong in the galaxy legend crates

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#168]
**Describe the Bug**
When previewing or obtaining a galaxy zapdos or xurkitree via / in the galaxy legend crate, the zapdos is called "Zapos" and the Xurkitree is called "Xuriktree". 

**To Reproduce**
1. Go to /warp crates
2. Click on the galaxy legend crate
3. Scroll down to Zapdos or Xurkitree
4. See that they are named "Zapos" and "Xuriktree"

**Servers with the Bug**
All

**Expected behavior**
The galaxy zapdos and xurkitree should be called 'Zapdos' and 'Xurkitree', not 'Zapos' and 'Xuriktree'.

**Screenshots**
![xuriktree](https://user-images.githubusercontent.com/82727445/119227813-14eed780-bb10-11eb-8dbb-c28f2b34621b.png)
![Galaxy zapod](https://user-images.githubusercontent.com/82727445/119227818-191af500-bb10-11eb-9063-1bd2a8ba2d91.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed in upcoming changelog.
