### ISSUE TITLE
Can not interact with /gyms in rayquaza 

### ISSUE THREAD

**Issue by Agera63** [SmashMC-Development/Bugs-and-Issues#1681]
**I try to interact with /gyms so I can challenge the Elite 4 but can not run the command, I know I deafeated all 8 gyms considering i remeber crafting a fusion shard**

**To Reproduce : I have heard that form some people this command does not work and for others it works fine (for me this command does not work on rayquaza only)**
1. Log into rayquaza server
2. Get your team that you wanna challenge gyms
3. run the command /gym OR /gyms
4. then i get the following message "An unexpected error occurred trying to execute that command" OR "I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you belive that this is a mistake" 

**Rayquaza ( tried in zek and kyo worked fine)**

**Expected behavior : expect to have a menu where i can challenge elite 4 **

![2023-03-17_16 28 53](https://user-images.githubusercontent.com/128187118/226035186-b40761d4-e11f-4307-b77f-494eb1ce0aec.png)

**have only experiensed this on rayquaza so far**

**Comment by Paradis4432** [comment]
old, fixed
