### ISSUE TITLE
/texture link is the old texture pack not the new one and doesnt work.

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1682]
**Describe the Bug**
if you do /texture in game it does not have the updated link.

**To Reproduce**
1. join any server
2. do /texture
3. click chat pop up
4. see its the 17.2 link

**Servers with the Bug**
All

**Expected behavior**
expected to have the new texture pack.

**Screenshots**
![javaw_lDTM5i3gW7](https://user-images.githubusercontent.com/120758795/226089748-d5015a10-4f2c-4584-8975-d59ece83c17e.png)

**Additional context**
 'N/A'.

**Comment by Superfire96** [comment]
Fixed some time ago
