### ISSUE TITLE
Lucky Block Pokemon Didn't spawn

### ISSUE THREAD

**Issue by khaima000** [SmashMC-Development/Bugs-and-Issues#1683]
**Describe the Bug**
I open my lucky block and the pokemon didn't spawn in-game
1. open lucky block
2. text in chat said I got the shiny pokemon
3. Shiny pokemon didn't spawn in-game
4. Find help
Rayquaza
Please provide a list of which servers have this bug.
I don't know
**Expected behavior**
I expected to get my pokemon.
**Screenshots**

If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
![image](https://user-images.githubusercontent.com/128214575/226092577-dcda129e-5738-4fef-9c29-e3693ad68bdc.png)

**Comment by Superfire96** [comment]
Fixed
