### ISSUE TITLE
Wz battles randomly crashing.

### ISSUE THREAD

**Issue by KUCHIHA10** [SmashMC-Development/Bugs-and-Issues#1687]
**Describe the Bug**
When I was in a battle in wz the battles have randomly just crashed/stopped. Both me and the player have just been teleported else where in wz it's like an endbattle happened but no staff that would be able to use the command was on.

**To Reproduce**
1. Go to 'wz'
2. Battle someone
3. continue as usual battle. 
4. Then game might randomly end and you get teleported.

**Servers with the Bug**
happened to me on kyogre and kyurem

**Expected behavior**
I expect to have a normal battle in wz to decide the victor without it ending randomly.

**Screenshots**
![image](https://user-images.githubusercontent.com/94144051/226166046-83bfef3b-0d05-45a8-aa68-9c1a3f0774d8.png)

What it says after issue occurred.
**Additional context**
I have a clip but not able to attach due to size.

**Comment by Superfire96** [comment]
Fixed some time ago
