### ISSUE TITLE
Wz battles randomly ending

### ISSUE THREAD

**Issue by Agera63** [SmashMC-Development/Bugs-and-Issues#1688]
**You fight someone and then form no where the battle ends its self**

**To Reproduce : will not work all the time**
1. Go to Kyo server
2. go wz
3. battle someone 
4. somethimes bug will happen something you will win

*so far only Kyogre**

**have a normal wz battle**

**Video : https://medal.tv/games/minecraft/clips/10m7CrPd0S6Llm/d1337bvMTdZu?invite=cr-MSxTQTMsMjQ1NTYwNTUs
               https://medal.tv/games/minecraft/clips/10lS8798Y45xHT/d1337bu93B38?invite=cr-MSw5MHgsMjQ1NTYwNTUs**
2 video that happened march 19 2023

** happened in 5 battles and only clipped 2**

**Comment by Superfire96** [comment]
Fixed some time ago
