### ISSUE TITLE
Get out of border glitch

### ISSUE THREAD

**Issue by SpiderBobPlayz** [SmashMC-Development/Bugs-and-Issues#1691]
**Describe the Bug**
You can get out of the border by throwing a pokemon outside of the border than riding it.

**To Reproduce**
1. Go to the World Border
2. Throw out your pokemon outside of the border
3. Ride the pokemon
4. Congrats your out of the border

**Servers with the Bug**
Kyogre probably more but I don't have any other rideable pokemon on the other servers so I can't test

**Expected behavior**
You get out of the border by throwing a pokemon outside of the border riding it & than you get out of the border. You don't die or anything once you get out. Also you can just walk back inside of the border.

**Screenshots**
(https://youtu.be/SkjYBh7AkXY)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive fixed
