### ISSUE TITLE
Gym doesn't give fusion shard as reward

### ISSUE THREAD

**Issue by Phoenixsans** [SmashMC-Development/Bugs-and-Issues#1692]
**Describe the Bug**
After beating a gym leader at /warp gyms, I was not given a fusion shard as a reward for beating the gym leader.

**To Reproduce**
1. Go to /warp gyms
2. Fight and beat a gym leader
3. Sometimes rewards will not be given

**Servers with the Bug**
all

**Expected behavior**
I expected to be given all the rewards, including the fusion shard.

**Screenshots**
Not a screenshot but here are videos:
https://medal.tv/games/minecraft/clips/10tCB6_Z3YgNxX/d1337X6bLGLK?invite=cr-MSwzbmYsNDA5ODA0OTAs
https://medal.tv/games/minecraft/clips/10tuc2dtIFdlFY/d1337l6oZ90r?invite=cr-MSw5ZHksNDA5ODA0OTAs

**Additional context**
For one of the battles, my inventory was full, but in the other one, I didn't receive the fusion shard even though my inventory wasn't full.

**Comment by Paradis4432** [comment]
inactive fixed
