### ISSUE TITLE
Tournament Moveset bugs

### ISSUE THREAD

**Issue by PurpleVenom07** [SmashMC-Development/Bugs-and-Issues#1693]
**Describe the Bug**
in the tournament earlier today there was a bug where me and i think other people too couldnt see any of our pokemons moves(it just had a bunch of writing about rules i think(sleep clause mod etc.)

**To Reproduce**
1. join tournament
2. hover over ur pokemon
3. see the issue

**Servers with the Bug**
happened to me on reshiram so not sure about other servers

**Expected behavior**
it will show a ton of writing instead of the pokemons movesets

**Screenshots**
![image_2023-03-21_124341277](https://user-images.githubusercontent.com/111924025/226609468-5652969f-2432-4956-a157-d336b44ef15b.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
This should be fixed!!!!!!!!
