### ISSUE TITLE
Not getting Gym reward after beating gym.

### ISSUE THREAD

**Issue by VGIce** [SmashMC-Development/Bugs-and-Issues#1694]
The bug is when you beat a gym, you may not get a reward for beating it.

**To Reproduce**
1. Go to a gym
2. beat the gym
3. see if you get the rewards or not

I experienced this on reshiram, but could be happening on other servers aswell.

I expected to get my rewards for beating the gym
![Screen Shot 2023-03-19 at 6 51 41 PM](https://user-images.githubusercontent.com/115387310/226705309-f9e363cd-ed10-4a41-bf8d-d73e4f58006c.png)

N/A

**Comment by Paradis4432** [comment]
inactive
