### ISSUE TITLE
Fake out Bug

### ISSUE THREAD

**Issue by Samkillzz** [SmashMC-Development/Bugs-and-Issues#1695]
**Describe the Bug**
Fake out doesn't flinch, 

**To Reproduce**
1. Go to Battle, wz or not, doesnt matter
2. Click on fake out
4. See that the enemy did not flinch
**Servers with the Bug**
Zekrom (Assuming all)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/120652662/226733875-2496c5a5-1ba2-4796-acd0-01b3c30709f9.png)

**Additional context**
10000000% Sure that no ability or anything got it the way, it SHOULD of had flinched

**Comment by Superfire96** [comment]
Pixelmon bug, nothing that we can really do about that
