### ISSUE TITLE
Groudon Defense EVs only has two trainers.

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1696]
**Describe the Bug**
there is only two trainers instead of three in the /warp evs defense area on groudon

**To Reproduce**
1. Go to /warp evs 
2. walk up to the defense place
3. See only two trainers

**Servers with the Bug**
groudon

**Expected behavior**
expected there to be three like the rest of the rooms 

**Screenshots**
![javaw_otoY3fQynv](https://user-images.githubusercontent.com/120758795/227006962-79349377-b77e-4d36-898d-61c4d01075f6.png)

**Additional context**
 'N/A'.

**Comment by Mikirae** [comment]
M1 fixed this :)
