### ISSUE TITLE
Delphox is saying its a fusion when being taken into warzone 

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1697]
**Describe the Bug**
When you try to take delphox into warzone it says its a fusion and not allowed in warzone.

**To Reproduce**
1.get a delphox on team
2. try to go to warzone
3. See the facts its considered a fusion

**Servers with the Bug**
possibly all

**Expected behavior**
expected it not to be considered a fusion its a normal mon

**Screenshots**

![6FC776B5-F81F-499A-A737-3A085D630D21](https://user-images.githubusercontent.com/120758795/227408032-ecebed79-6675-4269-8326-ee93985433a3.jpg)

**Additional context**
'N/A'.

**Comment by Superfire96** [comment]
Fixed some days ago
