### ISSUE TITLE
Warzone Battle 

### ISSUE THREAD

**Issue by AudolfOkami** [SmashMC-Development/Bugs-and-Issues#1698]
**Describe the Bug**
When in the warzone you can be taken out of battle by a player throwing a pokeball at you, and it makes you instantly lose the battle against the trainer.

**To Reproduce**
1. Enter battle with a Pokemon.
2. Get engaged in combat by another trainer while in the battle.

**Servers with the Bug**
I only know it happened to me and others on Zekrom.

**Expected behavior**
Other players shouldn't be able to take you out of combat with a Pokemon, and in case they are, you should be able to battle them.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
