### ISSUE TITLE
Depthfear counting for dex

### ISSUE THREAD

**Issue by RajSukhnain** [SmashMC-Development/Bugs-and-Issues#1699]
**I think that the new paradox Dragapult, DepthFear, is counting to dex therefore has decreased previous dex completion percentage.** 

**To Reproduce**
1. Dex completion percentage has been decreased.

**Servers with the Bug**
Has been on Zekrom but believe it is on all servers.

**Additional context**
VampireSquid, who has completed the pokedex to 100% has decreased down to 99.89%.

**Comment by Superfire96** [comment]
Fixed from next restart
