### ISSUE TITLE
Lucky Blocks

### ISSUE THREAD

**Issue by AudolfOkami** [SmashMC-Development/Bugs-and-Issues#1700]
**Describe the Bug**
When opening a Lucky Block it gave the message for spawning a Galarian Ponyta, but the pokemon didn't spawn. 

**To Reproduce**
1: Open a Lucky Block

**Servers with the Bug**
This happened on Zekrom.

**Expected behavior**
The pokemon should spawn.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Was fixed
