### ISSUE TITLE
Caught Pokémon disappear from PC.

### ISSUE THREAD

**Issue by PhantomLarceus** [SmashMC-Development/Bugs-and-Issues#1701]
**Describe the Bug**
I had caught at least 76 Pokémon so far and wanted to make adjustments for my team, so I went on my PC and all the Pokémon I had in there were gone (even the legendary Mew I had in my pc was gone as well). 

**To Reproduce**
1. Login to the server
2. Go to a PC
3. Right click on PC

**Servers with the Bug**
I am rayquaza server and I have never had this happen to me before until after I updated my modpack.

**Expected behavior**
I expected all my Pokémon to be in the PC where they belong and to not disappear.

**Screenshots**
N/A

**Additional context**
 I looked at all 100 boxes of my PC and all I had was just a drilbur.

**Comment by Sookie2003** [comment]
How did you fix this cause I'm having the same problem and am on the groudon server.

**Comment by PhantomLarceus** [comment]
Do /lobby1 and rejoin if that doesn't work then contact the devs
