### ISSUE TITLE
Luckyblock bug

### ISSUE THREAD

**Issue by c0RNEYY** [SmashMC-Development/Bugs-and-Issues#1702]
**Describe the Bug**
If you have a luckyblock and place it and break it(open it) then the pokemon (if you get a pokemon out of the lucky block) wont spawn and you get nothing. In chat it says that you got for example a shiny charmander even tho you didnt get it

**To Reproduce**
1: Get a luckyblock 
2: place it and break it
3: if you get a Pokemon look if it spawns 
4:if not the bug is there

**Servers with the Bug**
Reshiram for me, may be with other servers too.
**Expected behavior**
Get the pokemon i got from the luckyblock

**Screenshots**
![2023-03-28_17 23 28](https://user-images.githubusercontent.com/129408285/228872069-eabfaace-ba4a-4026-a8aa-26fe646015ca.png)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
