### ISSUE TITLE
My Beast Balls Turned to [item.pixelmon.unknown_poke_ball] in the GTS

### ISSUE THREAD

**Issue by ShinyHuntr** [SmashMC-Development/Bugs-and-Issues#1703]
**Describe the Bug**
Add a Park Ball Or Beast Ball, and there is a chance the name will become [item.pixelmon.unknown_poke_ball]

**To Reproduce**
1. Go to the Zekrom server's GTS
2. Add a Park or Beast Ball
3. See error

**Servers with the Bug**
Zekrom but maybe more.

**Expected behavior**
I expected my Beast Balls to go to the GTS like normal.

**Screenshots**
<img width="1280" alt="Screen Shot 2023-03-29 at 4 07 44 PM" src="https://user-images.githubusercontent.com/127358639/228914774-fa178d06-b5af-4a86-ab5e-7c4f72f4aba3.png">

**Additional context**
N/A

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by ShinyHuntr** [comment]
I have no clue, I have only played once within the last 2 months. The issue can probably still be tested, it just needs to be a great ball or higher.

**Comment by Paradis4432** [comment]
if it happens again feel free to make another issue
inactive
