### ISSUE TITLE
Tournament flag command not clear

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1704]
**Describe the Bug**
the tournament flag command is not clear due to the fact it says username in the message from the tournament when if you do the command plus a username you get unknown command. 
**To Reproduce**
1. join random tourny get stuck
2. see it says to do /tournament flag then username from the message from the server

**Servers with the Bug**
All

**Expected behavior**
would be nice to have the username removed to have it clear we only need to do /tournament flag so players don't think they're doing a command wrong

**Screenshots**

![WinRAR_VhDtkosAzO](https://user-images.githubusercontent.com/120758795/228928443-5ca239e2-0abc-4703-9915-2ed55f5229a2.png)

**Additional context**
'N/A'.

**Comment by Superfire96** [comment]
Fixed on next restart
