### ISSUE TITLE
Showing a pokemon is breedable when it isn't on /sts or /wt

### ISSUE THREAD

**Issue by RajSukhnain** [SmashMC-Development/Bugs-and-Issues#1705]
**When you do /sts and hover over an unbreedable pokemon it will show it as "TRUE" but when you hover over a pokemon that is actually breedable it will show as "FALSE"**

**To Reproduce**
1. Go to '/sts and hover over a breedable or unbreedable mon'
2. Hover over pokemon 'It will say in caps TRUE for an unbreedable mon and FALSE for a breedable mon'
3. When you do /gts sell it will show it correctly weather it is breedable or not

**Servers with the Bug**
Is on Reshiram however, most likely on all servers

**Expected behavior**
Shows that a breedable pokemon isn't breeedable and an unbreedable pokemon is

**Screenshots**
![image](https://user-images.githubusercontent.com/128942357/228941589-b81b32f1-4976-4f0a-bdc6-dbf6f9e08bf5.png) , 
![image](https://user-images.githubusercontent.com/128942357/228941681-38df8676-332f-473d-a388-4ca0585e0e51.png) , 
![image](https://user-images.githubusercontent.com/128942357/228941734-bbb2c467-4b46-4baa-b9f6-113419797fe1.png) , 
![image](https://user-images.githubusercontent.com/128942357/228941774-7e0befef-3378-4a5f-b3a8-2e57ac7debed.png)

**Additional context**
 'N/A'.

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
