### ISSUE TITLE
Masterball bug

### ISSUE THREAD

**Issue by Shroukieee** [SmashMC-Development/Bugs-and-Issues#1708]
**Describe the Bug**
Masterball turns into a pokeball/[item.pixelmon.unknown_poke_ball] when put in gts.

**To Reproduce**
1. Open gts
2. Sell Masterball (any amount)
3. See error

**Servers with the Bug**
Zekrom atm

**Expected behavior**
Expected to sell my Masterball. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
fixed inactive
