### ISSUE TITLE
Crimson dawns still spawning inside of warzone.

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1709]
**Describe the Bug**
crimson dawn pokemon are still spawning inside of warzone

**To Reproduce**
1. Go to 'warzone
2. have a crimson dawn legend spawn
3. see its crimson dawn

**Servers with the Bug**
All i would assume

**Expected behavior**
Expected to have the anubis palette in the warzone as that's what it says in announcements 

**Screenshots**

![notepad_nl29ddtzao](https://user-images.githubusercontent.com/120758795/229327953-84a475cc-ab7b-4ace-9d3a-b1a51e4ce8da.png)
![notepad_AEXQFGngeB](https://user-images.githubusercontent.com/120758795/229327958-925bf251-2a77-4986-a332-e2a30805389c.png)

**Additional context**
'N/A'.

**Comment by Superfire96** [comment]
Fixed
