### ISSUE TITLE
Scizor can't learn the tutor move Knock off on Jirachi

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#171]
**Describe the Bug**
Scizor can't learn the tutor move Knock off

**Servers with the Bug**
Only know the bug is on jirachi

**Expected behavior**
Scizor learns Knock off from move tutor

**Screenshots**
Proof of it being able to learn knock off previously
![2021-05-22_17 02 09](https://user-images.githubusercontent.com/83971987/119233518-7cf9e980-bb21-11eb-926b-5313fb7c18d2.png)
Proof of it not being able to learn Knock off currently
![2021-05-22_17 46 30](https://user-images.githubusercontent.com/83971987/119234405-aa489680-bb25-11eb-88f5-083fcd4dda48.png)

**Comment by HackuJacku** [comment]
Covered by #133

**Comment by manlybro2002** [comment]
![2021-05-22_18 03 58](https://user-images.githubusercontent.com/83971987/119234953-1f1cd000-bb28-11eb-8e55-4480918e7da6.png)
/buymove doesnt work for it
