### ISSUE TITLE
Random Pokemon paper giving out Fusions

### ISSUE THREAD

**Issue by Shroukieee** [SmashMC-Development/Bugs-and-Issues#1712]
**Describe the Bug**
When use a random pokemon paper there is a chance to get a Fusion out of it

**To Reproduce**
1. Get a random pokemon paper
2. Use it
3. See error

**Servers with the Bug**
I would assume all servers

**Expected behavior**
Expected to get a random non-fusion pokemon.

**Screenshots**

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
