### ISSUE TITLE
Warzone bug

### ISSUE THREAD

**Issue by subie370** [SmashMC-Development/Bugs-and-Issues#1713]
Warzone battle bug
This bug  in warzone it where if you go to challenge someone in warzone and there fighting a pokemon for example diglett i go tp challenge them and i get put into battle as i should however the other person does not and they are free to roam and use the rest of there time while im stuck on waiting
after there time is up i can take one of there pokemon

**To Reproduce**
1. Find someine in warzone trying to catch a pokemon
2. engage with them and you will be put into battle they opponent wont
3. After there time is up in warzone you get to choose there pokemon without fighting them

**Servers with the Bug**
Groundon the only one i know about

**Expected behavior**
to have a normal warzone battle 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'. N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'. N/A

**Comment by Paradis4432** [comment]
inactive fixed
