### ISSUE TITLE
Galarian Pokemons in Lucky Blocks

### ISSUE THREAD

**Issue by Aller1337** [SmashMC-Development/Bugs-and-Issues#1714]
**Galarian Pokemons in Lucky Blocks**
So if you have common lucky blocks, and you get a Galarian Pokemon out of it, then they don't spawn in.

**To Reproduce**
1. Go to any server.
2. Get a Common Lucky Block, and open them until you get a galarian pokemon.
3. Then you'll see that they don't spawn in.

**Servers with the Bug**
Every Server.

**Expected behavior**
I expected the Galarian Pokemons to spawn

**Screenshots**
'N/A'

**Additional context**
'N/A'

**Comment by Paradis4432** [comment]
inactive fixed
