### ISSUE TITLE
When getting rewarded a random Shadow pokemon, the shadow skin is not visible 

### ISSUE THREAD

**Issue by DarkGhoul9001** [SmashMC-Development/Bugs-and-Issues#1715]
**Describe the Bug**
I got rewarded a random shadow pokemon for reaching level 55 in acrobatics. I saw that it was a poipole via chat, but when I checked the PC and brought it out, the poipole just looked like a regular poipole. I have the texture pack on and up to date and other skins are visible. It is just the poipole/pokemon that does not have the skin. 

**To Reproduce**

**Servers with the Bug**
I only play on Kyurem, so as far as I know, only Kyurem. 

**Expected behavior**
I expected to get a random shadow pokemon that actually has the skin. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
