### ISSUE TITLE
Lucky Block -> Braille Block

### ISSUE THREAD

**Issue by Samkillzz** [SmashMC-Development/Bugs-and-Issues#1716]
**Describe the Bug**
Lucky Blocks obtained from the battlepass sometimes turn into Braille Blocks
**To Reproduce**
Self Explanatory
**Servers with the Bug**
I would Assume all of them

**Expected behavior**
Have the Lucky block spawn a pokemon

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
