### ISSUE TITLE
Warzone

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#1717]
**Describe the Bug**
When throwing your pokemon while running it never is accurate and always going random places. 

**To Reproduce**
1. Go to warzone
2. Run and try throwing a pokemon and see it doesn’t go the correct way most times. 

**Servers with the Bug**
Kyo but prob all 

**Expected behavior**
When I throw a Pokémon it goes forward not straight into the ground or way into the air.

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
