### ISSUE TITLE
nidoqueen will not breed

### ISSUE THREAD

**Issue by Wysey** [SmashMC-Development/Bugs-and-Issues#1718]
**Describe the Bug**
my nidoqueen will not breed not even when i use a ditto

**Servers with the Bug**
Rayquaza

**Expected behavior**
i think it's bugged

**Screenshot
![2023-04-05_17 23 09](https://user-images.githubusercontent.com/129939122/230019486-5e2bacd3-3c46-40aa-aeea-bb0b87512edd.png)
nshots**

N/a

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
