### ISSUE TITLE
/Warp boss

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#172]
**Describe the Bug**
You can't engage pokemon in /warp boss.

**To Reproduce**
1. Go to Jirachi
2. Go to /warp boss
3. Send out a pokemon
4. Nothing happens

**Servers with the Bug**
Jirachi

**Expected behavior**
When sending out a pokemon, you should be able to fight boss pokemon at /warp boss

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed.
