### ISSUE TITLE
masterballs in gts turn into normal pokeball when retrieve

### ISSUE THREAD

**Issue by Nitrolonely** [SmashMC-Development/Bugs-and-Issues#1720]
I listed 4 mball iin gts for 40k and when i retrieve it ,it convert into normal pokeball
![Screenshot 2023-04-05 215318](https://user-images.githubusercontent.com/101031577/230104430-2652bf85-64f1-4cdb-b8a8-0f9039d4043c.png)
![Screenshot 2023-04-05 215325](https://user-images.githubusercontent.com/101031577/230104453-7909f610-46a8-452b-9fb1-63e1d04f892c.png)

**Comment by Nitrolonely** [comment]
server is groudon

**Comment by Paradis4432** [comment]
fixed
