### ISSUE TITLE
Warzone mons spawning on top of the barrier 

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1724]
**Describe the Bug**
Regular mons are spawning on top of the invisible barrier on top of the warzone where no one can get them.
**To Reproduce**
1. Go to warzone
2. see that mons spawn on the invisible roof.

**Servers with the Bug**
All

**Expected behavior**
expected to have no spawns on top of the invisible roof.

**Screenshots**
![image](https://user-images.githubusercontent.com/120758795/230263250-9ea0e652-025f-4ebd-8058-21cade81a475.png)

**Additional context**
'N/A'.

**Comment by Superfire96** [comment]
Was fixed
