### ISSUE TITLE
Pokemon keep on spawning above the barrier were no one can reach them in the warzone

### ISSUE THREAD

**Issue by Wysey** [SmashMC-Development/Bugs-and-Issues#1725]
**Describe the Bug**
the pokemon are spawning above the barrier so no one can reach them

**Servers with the Bug**
the server is Rayquaza

**Expected behavior**
I think it is a glitch or a spawning bug

**Screenshots**
![2023-04-06_13 11 43](https://user-images.githubusercontent.com/129939122/230263897-38f23629-090b-43c0-b4f6-4ad4177be770.png)

**AAdditional context**
N/

**Comment by Superfire96** [comment]
Was fixed
