### ISSUE TITLE
Pokémon spawning in wz barrier

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#1726]
**Describe the Bug**
Some Pokémon's and legendaries spawn on the barrier making it impossible to catch them 

**Servers with the Bug**
Groudon and probably every server

**Expected behavior**
Spawn on the ground and not on the barrier

**Screenshots**
![image](https://user-images.githubusercontent.com/93119451/230352699-ef058872-a31e-449b-9242-67b9be33a8ac.jpeg)
**Additional context**
N/A

**Comment by Superfire96** [comment]
Was fixed
