### ISSUE TITLE
Not recieving a fusion shard while fighting a gym

### ISSUE THREAD

**Issue by CreeperGame7810** [SmashMC-Development/Bugs-and-Issues#1727]
**Describe the Bug**
After you defeat a gym leader you dont get a fusion shard sometimes even tho it says you won a fusion shard

**To Reproduce**
1. Go to the dragon gym leader
2. defeat the dragon gym leader
3. watch chat as it says you've won a fusion shard
4. check inventory

**Servers with the Bug**
Groudon (probably other servers too)
**Expected behavior**
to recieve my fusion shard

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
