### ISSUE TITLE
Electric gym doesnt give rewards

### ISSUE THREAD

**Issue by Phoenixsans** [SmashMC-Development/Bugs-and-Issues#1728]
**Describe the Bug**
the electric gym does not give rewards after being beaten. It just gives a badge and nothing else.

**To Reproduce**
1. Go to /warp gyms
2. Battle the electric gym leader
3. Beat it

**Servers with the Bug**
Occurred on rayquaza, could be on other servers

**Expected behavior**
Recieve 10k, 3 master balls, one fusion shard, and 1 dynamax candy, and 1 exp candy XL

**Screenshots**
Video: https://medal.tv/games/minecraft/clips/13qfml9dUTSaqa/d13373qnhEY2?invite=cr-MSxMOUssNDA5ODA0OTAs

**Additional context**
N/A

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
