### ISSUE TITLE
Electric Gym in Rayquaza Not Giving Rewards.

### ISSUE THREAD

**Issue by Jaffthemooses** [SmashMC-Development/Bugs-and-Issues#1729]
**Describe the Bug**
Electric Gym not giving players rewards.
**To Reproduce**
1. Warp to the gyms
2. Fight the Electric Gym
3. Win
4. Not receive the rewards

**Servers with the Bug**
Only Rayquaza I believe.
**Expected behavior**
Expected to get all rewards when gym leader beaten.

**Screenshots**

![2023-04-08](https://user-images.githubusercontent.com/130271139/230756641-5b81d0b3-e4e8-4551-9799-694495a5ba4d.png)

**Additional context**
'N/A'

**Comment by Paradis4432** [comment]
copy of another issue
