### ISSUE TITLE
Warzone issues

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#173]
**Describe the Bug**
Missing Holograms, hacked rules, no perms for /wzrules

**To Reproduce**
Holograms are missing on all serves except Rayquaza,Charizard
no perms to see /wzrules on Rayquaza
rules hacked for warzone all servers
**Servers with the Bug**
see above

**Expected behavior**
 Holograms should work on all server
 perms to see wzrules in ray should work
 warzone rules need to be fixed on all servers
 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
@Shoji007 - are any of these still an issue please? If so, which?

**Comment by Shoji007** [comment]
@HackuJacku 
/wzrules in ray still no perms
https://gyazo.com/7684fa45af6a8df8462a7eac7709529a
Warzone rules need to be written properly on all servers and not copypasted directly from the resource sheet.
and holograms are still missiong on all but ray and char still.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
