### ISSUE TITLE
Losing after opponent lost in tournament

### ISSUE THREAD

**Issue by CreeperGame7810** [SmashMC-Development/Bugs-and-Issues#1730]
**Describe the Bug**
I was fighting someone in the tournament which occured in the groudon server when his game crashed and I got the loss

**To Reproduce**
1. Wait for a tournament to take place
2. Join the tournament
3. tell your opponent to quit game without forfeiting
4. watch chat to see u get the loss

**Servers with the Bug**
Groudon, Zekrom, Rayquaza, Kyurem, Kyogre, Reshirem

**Expected behavior**
I Expected to get the win as if he left mid match i was supposed to win

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
