### ISSUE TITLE
got a scatter bug from my easter egg hunt l50 egg

### ISSUE THREAD

**Issue by subie370** [SmashMC-Development/Bugs-and-Issues#1731]
**Describe the Bug**

**To Reproduce**
1. Goto 'groundon do the easter egg hunt'
2. Click on 'get to level 50'
3. Scroll down to 'u get give the egg '
4. the egg was a scatter bug

**Servers with the Bug**
Please provide a list of which servers have this bug.
grondon is the only one i know of

**Expected behavior**
did easter egg hunt went to hatch egg from the levle 50 reward it was a scatter bug
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Archie4690** [comment]
The reward was changed to a shiny random pokemon. Not an issue.
