### ISSUE TITLE
Kyurem-white can't learn fusion flare aand Calyrex-shadow rider can't learn nasty plot

### ISSUE THREAD

**Issue by adao-2** [SmashMC-Development/Bugs-and-Issues#1738]
both kyurem-white and calyrex shadwo cannot learn certain moves and I think this is a problem for certain pokemon that can be fused together.
When I try to learn these moves ingame it will not show it to me and I have tried both the relearner and buymove command

I have only tried this in zekrom so I do not know if this is happening in other servers.

I expected to be able to learn the move but every time I try it will not learn it even at level 100

N/A

This could be happening to other pokemon as well

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
