### ISSUE TITLE
Pokemon paintings can be broken in claims

### ISSUE THREAD

**Issue by QuintessentialStu** [SmashMC-Development/Bugs-and-Issues#1739]
**Describe the Bug**
Pokemon Paintings (the 2x2 item frames for pokemon pictures) can be broken inside claims

**To Reproduce**
- make a 2x2 wall inside a claim
- Place a pokemon paining on the top left corner of the wall and place a picture into it
- Get another person without trust perms to break that painting
- It should give both the picture and the painting to the person who broke it (as they are closer to the items)

**Servers with the Bug**
Seen with Groudon, but I assume all

**Expected behavior**
Should not allow someone to break the painting as it is inside a claim and don't have trust perms

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Superfire96** [comment]
Was Fixed
