### ISSUE TITLE
StupidCom is unable to evolve any pokemon

### ISSUE THREAD

**Issue by AmsterDaan** [SmashMC-Development/Bugs-and-Issues#174]
**Describe the Bug**
a player StupidCom is unable to evolve any pokemon even if you force evo his mon in his party the animation starts but never finished the evo

**To Reproduce**
go to dialga
/evolve StupidCom slot
and the pokemon will not evolve
or ask him to level up a pokemon to evo level and the same result

**Servers with the Bug**
dialga

**Expected behavior**
he should be able to evolve his pokemon if conditions have been met

**Comment by HackuJacku** [comment]
@Rasgnarok - is this a Pixelmon bug?

**Comment by HackuJacku** [comment]
@AmsterDaan - has this occurred for any other players? Is it still occurring for this player? If so, which Pokémon is it happening to specifically please or is it all of them?

**Comment by AmsterDaan** [comment]
just this one player, and i tried it with several different pokemon in his party and even doing /evolve on them wouldn't work

**Comment by HackuJacku** [comment]
As this happened almost a month ago, there is a lack of information available to resolve. If this occurs again, please shoot me a DM.
