### ISSUE TITLE
Legendary egg keeper on every wild pokemon

### ISSUE THREAD

**Issue by Mangogo321** [SmashMC-Development/Bugs-and-Issues#1740]
**Describe the Bug**
Every wild pokemon you kill will say that its a legendary wild egg keeper.

**To Reproduce**
1. Go to wild and kill a wild pokemon

**Servers with the Bug**
every server

**Expected behavior**
it shouldnt be saying tht every pokemon is a leegndary egg keeper

**Screenshots**
<img width="532" alt="image" src="https://user-images.githubusercontent.com/130841390/232223331-3fa611b9-2472-4eb7-81c6-ebcea42e0a75.png">
shows it while killing a metapod
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Fixed :)
