### ISSUE TITLE
potion npc

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#1742]
**Describe the Bug**
no potion npc on zekrom server, making pp max alot more difficult to get 

**To Reproduce**
1. Go to zekrom /warp mart
2. see no potion npc is there

**Servers with the Bug**
zekrom

**Expected behavior**
there should be a potion npc there

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
