### ISSUE TITLE
baby legendary eggs not dropping in wz

### ISSUE THREAD

**Issue by TonyDePony2** [SmashMC-Development/Bugs-and-Issues#1744]
when you kill a leg any leg no egg drops. i've killed well over 10 legendaries in wz in the last day who can hold an egg (also 3 leg who have a 50 percent chance). and no egg has dropped. this probability is super low to be possible. Other people have also not gotten eggs when i was on and this seems unlikely.

To replicate
Go to wz an zekrom server.
Kill a legendary who can drop an egg.

Expected behavior
no eggs drop.

**Comment by morrow12** [comment]
dont think eggs drop in wz

**Comment by TonyDePony2** [comment]
Multiple people said to me they should even superfire.

Op za 22 apr. 2023 8:07 a.m. schreef morrow12 ***@***.***>:

**Comment by Superfire96** [comment]
Should be fixed, as the servers just needed a restart which happened this morning
