### ISSUE TITLE
Gyms Completly Broken

### ISSUE THREAD

**Issue by Agera63** [SmashMC-Development/Bugs-and-Issues#1745]
**Well during my gyms trial on rayquaza against AC_Shade, the battle ended and gave me a victory for some reason, after Shades removed my win and then i still advanced to the 2nd elite 4 trial after he ff to see if he can help me any other way and made my self to 3rd e4 challenge now i forfeit but idk if i am still at 3rd challenge.**

**To Reproduce : it happened randomly so idk when it will happen**
1. Go to Rayquaza
2. Use /gyms command
3. And do all the steps to challenge the gyms
4. Wait for someone to accept challenge
5. Hopefully the bug will happen during the battle (the battle will end and claim victory to 1 of 2 players)

*Rayquaza so far really**
Please provide a list of which servers have this bug.

**Battle to continue and see if the end result so either I win or I lose**

**Screenshots : did not have time to get any but Shades withnessded the hole thing with me**

**Additional context : nothing**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
