### ISSUE TITLE
Iron eclipse Prismatic Onslaught  move is bugging

### ISSUE THREAD

**Issue by KhoaHtown** [SmashMC-Development/Bugs-and-Issues#1746]
Prismatic Onslaught 
- The user utilises its control over to move at light speed and sap the life force from its opponent.
- 60 Base Power Special Psychic Move
- 100 Accuracy
- +3 Priority
- Restores 35% of HP Drained
the move of iron eclipse is bugging
calm mind doesnt work with it
the prio doesnt work as well
the prio is 3 but im still slower than an prio+1 move

**Comment by Superfire96** [comment]
Fixed on next restart

**Comment by KhoaHtown** [comment]
the buff doesn't work with that move
