### ISSUE TITLE
Stuck at Breeding Skill Level 230

### ISSUE THREAD

**Issue by realnigelululu** [SmashMC-Development/Bugs-and-Issues#1747]
**Describe the Bug**
I have been hatching eggs for quite some time and my breeding skill level have not been increasing past level 230. It has been stuck at 6250/11500 XP for some time not sure when. I tried relogging and hatched some eggs but it still did not move. I also do not know if I received my Level 230 reward. I gave my logs to a helper and he/she couldn't find it. It will be great if you could let me know what the reward is so that I can check if I did receive it.

**To Reproduce**
1. Put egg into team
2. Run at /warp hatch
3. Wait for egg to hatch
4. Egg hatched, XP bar did not increase

**Servers with the Bug**
Rayquaza

**Expected behavior**
I expected the XP bar to increase but it has been frozen.

**Screenshots**
https://user-images.githubusercontent.com/131786502/234310741-ae73636a-bd59-4dae-b697-7d067933bad7.mov

**Additional context**
I'm not so sure when I hit Level 230.

**Comment by realnigelululu** [comment]
how long will this be fixed.... i wanna play pixelmon

**Comment by D3vilEye** [comment]
**Been a week or so, we are still not getting any xp from hatching eggs on rayquaza server....**

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
