### ISSUE TITLE
Missing Rank/Color in the TAB for Master rank 

### ISSUE THREAD

**Issue by IceSlimGuys** [SmashMC-Development/Bugs-and-Issues#1748]
**Describe the Bug**
There is no Rank/Color for Master Rank in the TAB. We keep the same color as the previous rank (Ultra)

**To Reproduce**

1. Log on 
2. Catch every pokemon 
3. Enjoy the Master Rank Rewards
4. Press TAB: still the same color as Ultra Rank

**Servers with the Bug**
All of them

**Expected behavior**
Please give us a nice Rank/Color in TAB, we deserved it after all :')

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
