### ISSUE TITLE
evolution glitch

### ISSUE THREAD

**Issue by qiu1316** [SmashMC-Development/Bugs-and-Issues#1749]
when you use the exp all  item it will level up other pokemon but if you level a pokemon that wasn't in combat and still leveled up and is gunna evolve then the evolution glitches and you are frozen. after waiting for 20min it still wasn't  fixed so i logged out and logged back in but my pokemon didn't evolve and later when leveling it up it still didn't evolve so it like got evolution locked.

groudon server
https://user-images.githubusercontent.com/132033924/235047368-59a4e4ef-0d0f-4cd7-8633-e9601fa8e5d8.png

**Comment by Robolasereyes** [comment]
This is happening to me on the raquaza server as well
