### ISSUE TITLE
Shulker box dissapearing

### ISSUE THREAD

**Issue by DetectiveBoris** [SmashMC-Development/Bugs-and-Issues#1751]
**Describe the Bug**
Ok so idk if it has anything to do with the fact that I had been leaving warzone for the tournament that had started and when I had went to take the shulkers out of my warzone bank and the tournament team pop up came in as I was moving around the shulkers in my inventory then the pop up came and when i went to place back down the shulker it just disappeared.

**To Reproduce**
1. leave warzone (not sure if its main reason) 
2. before the tournament team popup comes up pick up item
3. try and place item back in inventory as the popup is coming up 
4. item disappears 

**Servers with the Bug**
 groudon is the only one that its happened to me on 

**Expected behavior**
replacing the item in inventory makes it completely disappear from the player

**Screenshots**

https://user-images.githubusercontent.com/132096705/235243609-852eef2b-b090-4de4-b400-e016323be7ae.mp4

**Additional context**
N/A

**Comment by DetectiveBoris** [comment]
Ok so idk if it has anything to do with the fact that I had been leaving warzone for the tournament that had started and when I had went to take the shulkers out of my warzone bank and the tournament team pop up came in as I was moving around the shulkers in my inventory then the pop up came and when i went to place back down the shulker it just disappeared.

**Comment by Paradis4432** [comment]
inactive
