### ISSUE TITLE
Raquaza - When having xp all active if a pokemon were to evolve but is not the one batteling a pokemon you will glitch and be stuck in place. to fix you need to log out however when you log out the pokemon dosent evolve.

### ISSUE THREAD

**Issue by Robolasereyes** [SmashMC-Development/Bugs-and-Issues#1752]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive lack of information
