### ISSUE TITLE
iron eclipse bugged move

### ISSUE THREAD

**Issue by KhoaHtown** [SmashMC-Development/Bugs-and-Issues#1754]
Prismatic Onslaught
The user utilises its control over to move at light speed and sap the life force from its opponent.
60 Base Power Special Psychic Move
100 Accuracy
+3 Priority
Restores 35% of HP Drained
 the move doesn't work with buff
 i did 6 time calm mind and doesn't have any effect on it

**Comment by KhoaHtown** [comment]
pls 
last time superfire end it when it didnt sovle

**Comment by Superfire96** [comment]
Fixed on next restart. The move was physical instead of Special, that's why it wasn't working
And last time the report was about the priority, not the same thing
