### ISSUE TITLE
Hatching eggs on Rayquaza server does not give any Breeding XP

### ISSUE THREAD

**Issue by D3vilEye** [SmashMC-Development/Bugs-and-Issues#1755]
**Describe the Bug**

**To Reproduce**
1. Go to 'Rayquaza server'
2. Click on '...'

**Servers with the Bug**
Rayquaza

**Expected behavior**
Hatching eggs does not give us any Breeding skill XP

**Screenshots**
N/A because cant upload a vid showing it.

**Additional context**
Been a week or so already, please any info or ETA on fix?

**Comment by Paradis4432** [comment]
copy of another issue
