### ISSUE TITLE
Battlepass not showing anything

### ISSUE THREAD

**Issue by Pixelbird14** [SmashMC-Development/Bugs-and-Issues#1756]
**Describe the Bug**
Nothing is shown in the battlepass when I open it, and I can't check my skills either. (reshiram) (Jaydongamer8)

![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 5_1_2023 5_08_56 PM](https://user-images.githubusercontent.com/132309802/235544075-48d8792e-6190-445a-ad72-386e682fc4a8.png)

**Comment by Gumse1** [comment]
I have the same problem

**Comment by Paradis4432** [comment]
inactive fixed
