### ISSUE TITLE
Boss Tower Not Working

### ISSUE THREAD

**Issue by CrownlessOcto** [SmashMC-Development/Bugs-and-Issues#176]
**Describe the Bug**
Cant throw out pokemon at the boss tower

**To Reproduce**
Steps to reproduce the behaviour:
1. Throw out your pokemon at any pokemon.
2. cant go into battle.
3. the only way to battle is to throw it onto a person and run up to a boss and spam the v button
4. and tada there

**Servers with the Bug**
Jirachi

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Same as #172
