### ISSUE TITLE
Vote reward lag loss?

### ISSUE THREAD

**Issue by TheNekomeowncer** [SmashMC-Development/Bugs-and-Issues#1760]
**Describe the Bug**
Voted on all 6 vote links, only got 4 keys for it, afterwards in game the chatbot still said i had two votes available, went to each website to double check and all of them were awaiting 24 hours till next vote. Server was lagging heavily when it happened so I think it just got lost in the lag

**To Reproduce**

**Servers with the Bug**
Rayquaza

**Expected behavior**
Should get all 6 vote keys

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive lack of information
