### ISSUE TITLE
Move tutor moves in /buymove

### ISSUE THREAD

**Issue by Mangogo321** [SmashMC-Development/Bugs-and-Issues#1761]
**Describe the Bug**
Move tutor moves are in /buymove for the pokemons

**To Reproduce**
1. Go to /buymove with snorlax and you will see the move tutor moves in it

**Servers with the Bug**
All

**Expected behavior**
it should not be in there as i was told

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This is not a bug and is intentional :)
