### ISSUE TITLE
Battlepass/Skills GUI Issue

### ISSUE THREAD

**Issue by FluffyBeardO** [SmashMC-Development/Bugs-and-Issues#1763]
**Describe the Bug**
After typing in /battlepass, I am unable to see any rewards I might have won from the battlepass. I have also checked out Skills and Leaderboards in the same GUI and I am unable to even open up those menus. This has been an issue for me for the past 2 weeks now.

**To Reproduce**
1. Type /battlepass
2. Unable to see anything, can switch from page 1 to 10 though
3. Click outside box to see the GUI with Skills, Battlepass, Leaderboards, Settings.
4. Click Skills (Nothing opens)
5. Click Battlepass, I only see the drives and arrow keys
6. Click Leaderboards (Nothing Opens)
7. Click Settings, my settings does not save when I relog.

**Servers with the Bug**
Rayquaza

**Expected behavior**
I expected to see rewards from my skills and battlepass, and notifications pop up from me progressing in some of my skills.

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/60242245/c45b573d-bce7-45ee-bf61-20e4f8dc2658)
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/60242245/2d6951db-09ad-4a6c-bf8d-52196ad2f959)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
fixed
