### ISSUE TITLE
Impossible Pokehunt

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1764]
**Describe the Bug**
Talorus can be the goal of a hunt - but it does not spawn anywhere

**To Reproduce**
Wait for it to be in the hunt - unreproducable otherwise

**Servers with the Pog**
At least Kyogre

**Expected behavior**
No Fusion mon in hunt

**Screenshots**
![2023-05-11_16 35 10](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/94211853/cbe9643c-2cc3-4b8b-86f4-07fdb33e472e)

**Comment by Superfire96** [comment]
Fixed
