### ISSUE TITLE
no special attack npcs on mewtwo

### ISSUE THREAD

**Issue by SystemErrorCA** [SmashMC-Development/Bugs-and-Issues#1766]
**Describe the Bug**
no special attack npcs

**To Reproduce**
1. Go to /warp evs
2. See no npcs

**Servers with the Bug**
Mewtwo

**Expected behavior**
expected to have npcs

**Screenshots**
![javaw_fKly8YybSx](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/120758795/eca8ff80-d636-4636-82df-9d04e52816c6)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Was fixed
