### ISSUE TITLE
aura crate

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#1769]
**Describe the Bug**
the aura crate doesnt give the right rewards, believe its a rare crate in disguise
**To Reproduce**
1. Go to the aura crate
2. open it
3. get wrong rewards 

**Servers with the Bug**
mewtwo is the only one i know
**Expected behavior**
it should be giving aura things, not rare crate things

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/83245837/b6988dbf-339e-4c13-9d28-245c71ab7a06)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Should be fixed
