### ISSUE TITLE
Bosstower problems

### ISSUE THREAD

**Issue by slippysayjin** [SmashMC-Development/Bugs-and-Issues#177]
**Describe the Bug**
the warp bosstower and the random bosstower of the world are only spawning grey and green bosses and i think the spawnrates of the better ones are bugged

**Servers with the Bug**
dialga

**Expected behavior**
i would like to see better spawnratios for the bosses 

**Screenshots**
N/A

**Additional context**
n/a

**Comment by HackuJacku** [comment]
This is not a bug - the bosses spawning are common and uncommon. I have seen the rarer bosses spawn at the bosstowers across the network.
