### ISSUE TITLE
Skills Didnt Provide Crate Key

### ISSUE THREAD

**Issue by ShaqTheMilkMan** [SmashMC-Development/Bugs-and-Issues#1770]
Skills Rewards Didnt Provide a Crate Key

https://github.com/SmashMC-Development/Bugs-and-Issues/assets/109303715/0946d54c-bd7f-4b5e-8157-2c9345cfe901

**Comment by Superfire96** [comment]
I can't really see which skill that is

**Comment by Superfire96** [comment]
Forgot to say that it's now fixed
