### ISSUE TITLE
gts on mewtwo

### ISSUE THREAD

**Issue by BriannaW61** [SmashMC-Development/Bugs-and-Issues#1771]
**Describe the Bug**
Its when you do /gts sometimes gts comes up empty no matter how many times you open it, but it works fine the next few minutes after.

**To Reproduce**
1. Go to /gts
2. See error

**Servers with the Bug**
Mewtwo

**Expected behavior**

Gts working lol

**Screenshots**
![2023-05-14_18 38 46](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133610591/37257222-3505-4a8f-bfd5-fd2a4149cab6)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
fixed
