### ISSUE TITLE
Kyurem valentines chest has no texture and cannot be opened

### ISSUE THREAD

**Issue by adao-2** [SmashMC-Development/Bugs-and-Issues#1772]
On kyurem the valentines chest is just a normal wooden chest with no texture and shows as needing administration trust to open it.

<img width="960" alt="javaw_20z2xhyYS9" src="https://github.com/SmashMC-Development/Bugs-and-Issues/assets/130400862/3a028e3f-a030-4d10-a4b1-d2fb02cd54d5">
 
This is on kyurem

**Comment by Superfire96** [comment]
Fixed
