### ISSUE TITLE
Pokehunt not working

### ISSUE THREAD

**Issue by rwlt** [SmashMC-Development/Bugs-and-Issues#1774]
Pokehunt is not working right now 
Its not working on groudon
To reproduce do /pokehunt
It should be showing all available pokehunts
Typing the command would only cause this message to pop up
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133784680/b11d20c8-0ab2-4a36-ad16-8ffdd1feea8e)

**Comment by Superfire96** [comment]
You should be able to /hunts
