### ISSUE TITLE
their is no fusion crate for me  

### ISSUE THREAD

**Issue by TemptingMadness** [SmashMC-Development/Bugs-and-Issues#1775]
![Screenshot (6)](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133845286/72320fd3-1f79-44c6-972b-ba2d72b8c466)
![Screenshot (7)](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133845286/a71a51d3-442e-45f9-9886-da0a7c898616)
![Screenshot (10)](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133845286/70d9ab39-d78a-47d1-ad90-be203c85b39c)
![Screenshot (9)](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133845286/e99f7bde-76f2-4dae-a264-f7a782dae8c6)

**Comment by TemptingMadness** [comment]
i am in groudon i was thinking about going to see the crates and noticed on the website they have a fusion crate key yet not a fusion crate

**Comment by Superfire96** [comment]
Fixed
