### ISSUE TITLE
Lucky Block Bug

### ISSUE THREAD

**Issue by Queen-Lilith** [SmashMC-Development/Bugs-and-Issues#1776]
I've noticed among servers that there is a common bug with lucky blocks when placing them down, sometimes when players like myself and others break them they will disappear saying they spawned the specific pokemon in the chat when the pokemon is nowhere to be found. I thought sharing this issue would be beneficial to the server as many other players as well as myself have come across this issue and we are hoping that this issue will be fixed soon.

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
