### ISSUE TITLE
Bingo Board got reset when server crashed

### ISSUE THREAD

**Issue by MoonProject1** [SmashMC-Development/Bugs-and-Issues#1777]
**Describe the Bug**
I was working on my bingo board and had everything besides 3 captures, screenshots of board and my pc attached. 
I dont have the time to go and try to recapture the pokemon again as there is only 3 hours left on my board and i was hoping i would be able to get the rewards that i would of gotten with my board as is. 

**To Reproduce**
1. Logged in this morning and began capturing pokemon
2. Server began to lag
3. Server Crashed
4. Upon logging back in bingo board was undone all captures from this morning

**Servers with the Bug**
I was on the Mewtwo server crash happened at about 11:35

**Expected behavior**
i was hoping that upon logging back in my bingo board would be filled in with the captures i found this morning

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133993039/71a2860f-d865-4f00-bd2f-12601c66a01c)

![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133993039/e50f5559-d8cb-4b67-80d2-5a3b4ee2defc)

**Additional context**
would it be possible to get the awards i could of gotten if i cashed in my bingo board as it was. Was trying to fill it out but not going to look for the last 3 captures incase its not possible to get what i should of gotten
 
my IGN: Moon_Project
or im in the discord my discord name is M00n (#1428)

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
