### ISSUE TITLE
Not getting hatching xp 

### ISSUE THREAD

**Issue by BestSparky** [SmashMC-Development/Bugs-and-Issues#1780]
**Describe the Bug**
hatching eggs is not giving any xp 

**To Reproduce**
1. Go to skills hatching to see lv 92 4200 xp 
2. hatch some eggs, ive hatched 20 
3. go back to skills and see still at lv 92 4200 xp 

**Servers with the Bug**
Please provide a list of which servers have this bug.
groudon 
**Expected behavior**
get xp 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
Na
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
copy of another issue
