### ISSUE TITLE
Hisuian Evolution - Wyrdeer Edition

### ISSUE THREAD

**Issue by FaultyWifi** [SmashMC-Development/Bugs-and-Issues#1781]
**Describe the Bug**
 The bug that I experienced is that I could not obtain a Hisuian evolution with a Hisuian evolved pokemon.

**To Reproduce**
1. Catch Stantler. I needed the Hisuian evolution Wyrdeer for Pokedex completion and I followed the guidelines provided by the pixelmon website. https://pixelmonmod.com/wiki/Wyrdeer  It states that it needs to be level 21 and have a Hisuian form in the party, so followed the guidelines and got my Stantler above the level cap.
2. Capture an evolution of a Hisuian pokemon. For this example, I used both Overqwil and Kleavor. They are both evolutions of pokemon from the Hisuian Region. I used Overqwil because it evolves specifically from the hisuian form of qwilfish and I used Kleavor since it evolves from a "typical form" Scyther.
3. Level up Stantler once more. In my case, I leveled up Stantler from level 42 to 43, meaning it was well above the level cap and contained both Overqwil and Kleavor in the party. The results are that Stantler does not evolve with these specific conditions.

**Servers with the Bug**
 The server that I discovered this bug on was Smashmc. IP: play.smashmc.co

**Expected behavior**
 The expected outcome of this action is that Stantler evolves into Wyrdeer due to meeting the conditions of its evolution.

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/134045613/433ec5d7-fee6-4c7b-aedc-e9597d9f2a28)
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/134045613/0b4e7f6a-707b-42be-be40-562698c9d376)

The first screenshot mentioned above is prior to the evolution of Stantler. The second screenshot if the result of using a rare candy on said Stantler. I have tried using the ./evofix command, and that did not work either.

**Additional context**
N/A

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
