### ISSUE TITLE
battle pass desent load

### ISSUE THREAD

**Issue by liran123g** [SmashMC-Development/Bugs-and-Issues#1783]
**Describe the Bug**
on server zekrom you cant see the battle pass like it desent load 
**To Reproduce**
I just type /battlepass and then this will happen I will show it in a screenshot

**Servers with the Bug**
as I know zekrom 
**Expected behavior**
that it will be fixed
**Screenshots**
![image](https://github.com/SmashMC-![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/134135069/91b66a26-0cd8-468f-9989-e87ca99db2b9)/Bugs-and-Issues/assets/134135069/de7289db-2f8b-4f8f-8b95-58e52641b981)

**Additional context**
pls fix it as fast as you can

**Comment by Paradis4432** [comment]
fixed
