### ISSUE TITLE
Outbreaks

### ISSUE THREAD

**Issue by RajSukhnain** [SmashMC-Development/Bugs-and-Issues#1784]
**Describe the Bug**
On the Mewtwo Server when there is an outbreak it crashes or makes people unable to join the server

**To Reproduce**
1. Server has an outbreak
2. See the result.

**Servers with the Bug**
Issue is seen on the Mewtwo server

**Expected behavior**
Whenever there is an outbreak it causes the server to crash or just kick people from the server when they are trying to join the server.

**Screenshots**
'N/A'.

**Additional context**
'N/A'.

**Comment by Paradis4432** [comment]
fixed
