### ISSUE TITLE
Cant receive BattlePass  rewards

### ISSUE THREAD

**Issue by NinjaGreg67** [SmashMC-Development/Bugs-and-Issues#1785]
**Describe the Bug**
I want to receive my BattlePass rewards on zekrom, but i cant.

**To Reproduce**
1. Go to Zekrom/Kyogre/Groudon
2. Click on Chat
3. Write /battlepass
4. You can only see one red Arrow and also CD  players or something Like this

**Servers with the Bug**
Zekrom Kyogre Groudon

**Expected behavior**
I expected that it will show me rare candies, poke balls and more stuff

**Screenshots**
https://github.com/SmashMC-Development/Bugs-and-Issues/assets/134164708/95dc8093-edbe-43ae-b05f-535d9e9bb4eb

**Additional context**
N/A

**Comment by Paradis4432** [comment]
fixed
