### ISSUE TITLE
Fusions allowed in mewtwo gyms 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#1786]
**Describe the Bug**
You are able to use fusions in the mewtwo gyms

**To Reproduce**
1. Go to a gym 
2. Battle the gym and use a fusion 
3. See error

**Servers with the Bug**
Mewtwo
**Expected behavior**
You arent supposed to use them 

**Screenshots**
![2023-05-21_10 35 24](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/93038258/24dea1ac-76e0-4374-9006-bcb87470b896)

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
