### ISSUE TITLE
being stuck on waiting with the legendary on wz

### ISSUE THREAD

**Issue by BriannaW61** [SmashMC-Development/Bugs-and-Issues#1787]
**Describe the Bug**
The same thing as waiting with a wild mon but you cant /endbattle and you're stuck until the timer runs out

**To Reproduce**
Go to Warzone
Encounter a Legendary

**Servers with the Bug**
Rayquaza, probably all
**Expected behavior**
Not be stuck

https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133610591/ca16daa8-4ec3-41a9-b5d5-90c08f4195bd

**Screenshots**

**Additional context**
N/A

**Comment by Paradis4432** [comment]
fixed
