### ISSUE TITLE
Random Tournament Glitch

### ISSUE THREAD

**Issue by LepocalypseLB** [SmashMC-Development/Bugs-and-Issues#1788]
**Describe the Bug**
-I was in a random tournament at 2pm EST on May the 21, 2023. During the beginning, the player as my opponent was experiencing a bug where they were not in the select your Pokémon screen. He had to send a Pokémon at my character to start the battle. After the battle, I win; however, instead of facing the next person, I was thrown out of the tournament and wasn't even given a key. Instead, my opponent goes the key, but I wasn't given anything.

**To Reproduce**
1. Enter a Random Tournament 
2. Battle till you get an opponent that's not in the battle select Pokémon screen. 
3. Send a Pokémon at the Player in the Pokémon select screen.
4. Person in the Pokémon Select Screen Win
(I'm not sure if this actual what caused the glitch or not, but seems to be the most likely reason)

**Servers with the Bug**
Please provide a list of which servers have this bug.
-I had this issue of Zekrom
**Expected behavior**
-I expected to be put against my next opponent, but I wasn't given my next opponent and instead was not given the chance to win, but my last opponent did get a key. Neither of us got the chance to face first place.
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
-I do, in fact, have a screenshot in the ticket I opened in the discord. Not sure how to place it in here though.
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Paradis4432** [comment]
fixed inactive
