### ISSUE TITLE
mewtwo water gyms is a flying gyms no water mons at all

### ISSUE THREAD

**Issue by Kina-San** [SmashMC-Development/Bugs-and-Issues#1789]
**Describe the Bug**
well just found out the hard way the water gym in mewtwo is a flying gym.

**To Reproduce**
1. Go to '/warps or /gyms'
2. Click on 'water gyms'

**Servers with the Bug**
Mewtwo.

**Expected behavior**
should've been water gyms but was flying gyms instead

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/37955601/730d591b-3cc0-4232-ab2e-6f30ec182c23)
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/37955601/6b5d036f-515f-48a1-825f-f93a66f27209)

**Additional context**
last screen was to show what should be the water gyms

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
