### ISSUE TITLE
Red and blue orb not working

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#179]
**Describe the Bug**
Red orb for groudon and blue orb for kyogre are not working properly in overworld and warzone, they just work against NPCs

**To Reproduce**
1. Go to server Mew
2. Get a kyogre/groudon with the respective orbs
3. Battle another player / pokemon

**Servers with the Bug**
Should be just Mew

**Expected behavior**
Red and blue orb should work against pokemons and other trainers, not only against NPCs

**Screenshots**
![2021-05-23_00 18 14](https://user-images.githubusercontent.com/83550357/119242237-8785a480-bb5c-11eb-9886-fb3e3a8d672b.png)
![kyogre](https://user-images.githubusercontent.com/83550357/119242243-8ce2ef00-bb5c-11eb-9637-6b08a21e5beb.PNG)

**Comment by HackuJacku** [comment]
Same as #203
