### ISSUE TITLE
Warzone Glitch when stealing a Pokémon after winning

### ISSUE THREAD

**Issue by SavagePlays15** [SmashMC-Development/Bugs-and-Issues#1790]
**Describe the Bug**
The bug occurs when a player wins a wz battle and then the screen where you get the option to steal the loser's Pokemon glitches out. In the video, the player was unable to select any of the Pokemon and had a timer of -733 seconds to choose from. I've also heard about players not having the option to steal anything, or they select the Pokemon they want but they don't receive it and the opposing player keeps his Pokemon despite losing. 

**To Reproduce**
I'm not sure if it can be reproduced, the player with the issue said that his opponent ff right after engaging in battle and he was a bit laggy and that happened. Now about now being able to steal a Pokemon I think it happens randomly hasn't been tested.  

**Servers with the Bug**
As far as I know, I've handled tickets in Zekrom and Ray about this issue but it could be an all-server issue

**Expected behavior**
 I expect the issue to be solved just so we don't have to deal with it in future tickets, and the players don't have a hard time waiting for the issue to be resolved.
**Screenshots**
N/A.

**Additional context**
 I attached a video that the player sent within the ticket 

https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133742800/cd66c053-c124-4b9c-88a8-da03fb21f5c5

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by SavagePlays15** [comment]
As far as I know it hasn’t been an issue anymore and I haven’t heard/seen
any tickets or anything about this issue so I would say no

**Comment by Paradis4432** [comment]
ok thank you 
fixed
