### ISSUE TITLE
Zekrom warzone teleporting players into the void after battle

### ISSUE THREAD

**Issue by xHudsy** [SmashMC-Development/Bugs-and-Issues#1791]
**Describe the Bug**
On Zekrom, when finishing a battle with a player in warzone, players are sometimes teleported into the void, resulting in warzone time being lost as players have to safeplace.

**To Reproduce**
1. Go on `/Zekrom` and enter `/wz`
2. Battle a player and win
3. Get teleported into the void

**Servers with the Bug**
Zekrom

**Expected behavior**
After winning a battle, players should be teleported elsewhere in the warzone, instead of into the void.

**Screenshots**
Video of error occuring, provided by player `Jaldin`:
https://imgur.com/a/JxW4ppk

**Additional context**
N/A

**Comment by Paradis4432** [comment]
fixed inactive
