### ISSUE TITLE
Kyogre breeding skill not gaining any exp

### ISSUE THREAD

**Issue by BaxterSk** [SmashMC-Development/Bugs-and-Issues#1792]
Recently noticed in the skills menu tab that the breeding skill doesn't get any exp , with over 10-15 hatched eggs its still at 0/50 exp , some of the players have this bug as well so its not personalised , may be because of the new day cares

rpbaxter1223

**Comment by Paradis4432** [comment]
fixed

**Comment by Paradis4432** [comment]
inactive
