### ISSUE TITLE
/skills not working

### ISSUE THREAD

**Issue by RetroIsInsane** [SmashMC-Development/Bugs-and-Issues#1794]
**Describe the Bug**
When i do what would normally produce your skill bar at the top of the screen to increase, mine does not. mine doesnt show up at all. when i do /skills i cant even open them to see my progress. they just show my inventory for a second then go back to the page where all i see is the options to open skills.
is there any way to fix this??

**Servers with the Bug**
As Far as i know none. my friends dont have this issue and its just me

**Expected behavior**
i expected to see my skills and gain the rewards for level ups

**Screenshots**
N/A (wont open to show)

**Additional context**
n/a

**Comment by Paradis4432** [comment]
inacttive fixed
