### ISSUE TITLE
/rtp bug

### ISSUE THREAD

**Issue by UniversalxDemon** [SmashMC-Development/Bugs-and-Issues#1795]
**Describe the Bug**
For some reason when i use the command /rtp or talk to the rtp npc i receive a message saying [ youre already teleporting ] and nothing else ive left the game rejoined and nothing ive shut the program down and nothing.

1. Go to '..the Zekrom server.'
2. Click on '..do /rtp ..'
3. Scroll down to '..n\a..'

**Servers with the Bug**
Zekrom

**Expected behavior**
for my player to be able to use the /rtp command or figure out whats going on.

**Screenshots**
![issuee](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/134897324/dea0757a-fa76-4ec2-b92e-b812f60ecf0c)

**Additional context**
'N/A'.

**Comment by chachemaster** [comment]
what dose n/a mean

**Comment by Paradis4432** [comment]
fixed
