### ISSUE TITLE
BattleTower not working

### ISSUE THREAD

**Issue by rwlt** [SmashMC-Development/Bugs-and-Issues#1796]
**Describe the Bug**
BattleTower is not working

**To Reproduce**
1. Go to /warp battletower
2. Click on "challenge" npc

**Servers with the Bug**
Groudon

**Expected behavior**
Should bring up the battletower challenge ui

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133784680/0f49d937-e070-41e0-97cd-18b208454bc9)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
fixed
