### ISSUE TITLE
Textures not loading.

### ISSUE THREAD

**Issue by Clunenator** [SmashMC-Development/Bugs-and-Issues#1797]
When downloading the textures off of the link, when trying to extract/unzip the folder it says cannot open file and when you try to extract it is saying its invalid, when I try to just put the folder into the texture packs as is and load it, it says resources reload failed.

**To Reproduce**
1. Go to 'Discord texture download link.'
2. Once downloading try to extract it, it should say it's invalid.
3.Try to open it and it says it cannot be opened. 
4. Try to put the folder as is into the texture packs in Minecraft 
5. See error

All servers

**Expected behavior**
File should open and should be able to load.

**Screenshots**

![Screenshot 2023-05-30 095123](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/135040762/333d0692-30a7-4a04-bf51-a71f3cb3e7b6)
![Screenshot 2023-05-30 100538](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/135040762/2618df11-189d-4b06-8946-7685f6ca855c)
![Screenshot 2023-05-30 095747](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/135040762/8b916458-edc1-4928-84e2-0716e9bec48b)

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
