### ISSUE TITLE
specific Pokemon battle-bond Greninja

### ISSUE THREAD

**Issue by PhantomFire21** [SmashMC-Development/Bugs-and-Issues#1798]
**Describe the Bug**
I think what happened was that it couldn't register the battle-bond Greninja so it gave me a normal one instead
**To Reproduce**
1. get a specific Pokemon paper
2. enter Greninja 
3. then for the form, enter battle-bond
4. it gives you a torrent Greninja

**Servers with the Bug**
kyruem and rayquaza, I'm not sure if its in others or not
**Expected behavior**
I expected to get a battle-bond Greninja
**Screenshots**
N/A
**Additional context**
N/A

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
