### ISSUE TITLE
 when i want to get into warzone it says i can't even though i have gen 1 pokemons in the error it says -Iron saber is a paradox pokemon and not allowed in warzone -Iron Rocket is a paradox pokemon and not allowed in warzone

### ISSUE THREAD

**Issue by XuKo27** [SmashMC-Development/Bugs-and-Issues#1799]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by XuKo27** [comment]
Zekrom

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
