### ISSUE TITLE
People are not able to claims galarian pokemons through specific pokemon papers

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Bugs-and-Issues#18]
**Describe the Bug**
If you have a Legend Of Choice paper or Non legend pokemon of choice paper you are not able to claim alolan pokemons

**To Reproduce**
Right click the paper in the ground and type /rewardclaim Galarian(pokemonname)

**Servers with the Bug**
All

**Expected behavior**
All players are able to claim galarian pokemons

**Comment by HackuJacku** [comment]
Passed onto @Mikirae as he knows the developer and I do not.

**Comment by HackuJacku** [comment]
Added in the next version - requires Pixelmon 8.2.

**Comment by Mikirae** [comment]
Fixed.
