### ISSUE TITLE
Wondertrade not working 

### ISSUE THREAD

**Issue by JamesAllen5424** [SmashMC-Development/Bugs-and-Issues#1801]
Wonder trade is not working on any servers 

**To Reproduce**
1. Run the command to open wonder trade
2. Then get error Saying "For further support visit the EnvyWare Ltd discord

**Servers with the Bug**
tested and found issue on all servers

**Expected behavior**
for the wonder trade GUI to come up when running command

**Screenshots**

![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/130809668/2c0e7976-fa80-4c96-8096-d53370b04c85)

**Comment by Superfire96** [comment]
This is being looked into, sadly can't update it right now as it makes the server crash

**Comment by Paradis4432** [comment]
fixed inactive
