### ISSUE TITLE
STS command

### ISSUE THREAD

**Issue by JamesAllen5424** [SmashMC-Development/Bugs-and-Issues#1802]
STS broken
When running the command to open STS nothing happens, doesn't give any message either

**To Reproduce**
1. Type /sts

**Servers with the Bug**
Tested and found sts doesn't work on all servers

**Expected behavior**
Sts GUI to open when running commant

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Same for this, needs to be updated by the dev still
