### ISSUE TITLE
some wz mons arent remaining textured

### ISSUE THREAD

**Issue by DeathViperDom** [SmashMC-Development/Bugs-and-Issues#1803]
Idk abt other servers but this was for ray, it said a corrupted galar zapdos spawned in wz but when i found it, it looked regular, then when i caught it, it was regular too? I checked in gts to see if it had a texture and it didnt. the resource pack works as i have other corrupted mons. Idk if its just galarian form mons that arent working or what.

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
