### ISSUE TITLE
Not able to redeem creator codes, first time in the server , never played in any smashmc server 

### ISSUE THREAD

**Issue by KaizuSMASHMC** [SmashMC-Development/Bugs-and-Issues#1804]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Pixelmon Mewtwo server 

**Expected behavior**
i expected to receive the creator code rewards since its my first time in the server

**Screenshots**
![Screenshot_3](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/135485023/0906c2a4-4868-4b8b-8ea8-14413b31d04c)

**Additional context - technic logs ** 
[techniclauncher_2023-06-03.log](https://github.com/SmashMC-Development/Bugs-and-Issues/files/11644656/techniclauncher_2023-06-03.log)

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
