### ISSUE TITLE
Kyogre has no gym leader :/

### ISSUE THREAD

**Issue by DavidDurham4** [SmashMC-Development/Bugs-and-Issues#1806]
**Describe the Bug**

Whenever going to the /warp gyms area, there aren't any gym leaders at the gym areas.

**To Reproduce**
1. Go to /warp gyms
2. Look at the gym leader's rooms
3. See no leader or NPC to fight

**Servers with the Bug**
The only server I know of is Kyogre

**Expected behavior**
I believe there should be gym leaders in the /warp gyms area.

**Screenshots**
I am bad and didn't take any

**Additional context**
None

**Comment by Paradis4432** [comment]
fixed inactive
