### ISSUE TITLE
Flynium Z not working with dual wingbeat

### ISSUE THREAD

**Issue by KUCHIHA10** [SmashMC-Development/Bugs-and-Issues#1807]
Description- When trying to use flynium Z on my dragonite that has dual wingbeat a flying move it does not show the option to use the flying z move.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into a battle with any pokemon.
2. Click on The z move option and try to use flynium z
3.See error as no option to use the z move shows.

**Servers with the Bug**
Kyurem but possibly all.

**Expected behaviour**
Be able to use flynium z with my dragonite that has dual wingbeat. (works with fly but not with dual wingbeat)

Uploading uncapped_MedalTVMinecraft20230608160221.mp4…

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
