### ISSUE TITLE
Pokemon evolution error

### ISSUE THREAD

**Issue by wildhunterforever** [SmashMC-Development/Bugs-and-Issues#1808]
the bug makes it that if a pokemon evolves after a fight the player stays in spectating mode and has an xp hotbar shown he cannot do anything and the pokemon will evolve but not fully because it is stuck i know this because my magicarp and geodudedid the same and i had to teleport somewhere to get out and that stops the evolution process.

**To Reproduce**
1. Go to a fight with an almost evolved pokemon.
2. evolve it after the fight (the evolution has to be with the fight xp not with stones).
3. See error

**Servers with the Bug**
smashmc

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by CrimsonDragon27** [comment]
I am having the same issues with the pokemon about to evolve but get glitched and cant move but then i get kicked and it sames to be happening a lot cant get any of my pokemon to evolve because of it

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
