### ISSUE TITLE
IronEclipse wont spawn

### ISSUE THREAD

**Issue by Zander999929** [SmashMC-Development/Bugs-and-Issues#1813]
In the ultra jungle the custom paradox pokemon "ironeclipse" does not spawn even though it is intended to. 
In the ultra space whenever you type /checkspawns it shows every other custom paradox pokemons spawn chance except iron eclipse, because ironeclipse is bugged and fails to spawn. 

**To Reproduce**
1. Go to the ultra wormhole in ultra space
2.  type /checkspawns
3. see that ironeclipse is not listed.

To my knowledge this bug is only on kyruem, but i am not sure and it could be on others
**Expected behavior**
I expect that iron eclipse will be unbotainable due to this and it will drain from the aspect of a players experience.

![](https://cdn.discordapp.com/attachments/1119771808166580295/1119772157426290778/image.png)

![](https://cdn.discordapp.com/attachments/1119771808166580295/1119773093402001478/image.png)

![](https://cdn.discordapp.com/attachments/1119771808166580295/1119773189942300672/image.png)

**Comment by Superfire96** [comment]
I'd suggest clearing an area in the ultra jungle, as it would spawn on the land

**Comment by Zander999929** [comment]
the problem is that its not even in the spawn table for the ultra jungle
otherwise it would show up under /checkspawns like all the other paradox pokemon

**Comment by OakScout12** [comment]
now I have no idea if this is related but I got this wild "lunala" but its name is pixelmon.ironelclipse the apathetic, now what should I do considering it looks like lunala. its typing is psychic fairy so I assume its supposed to be paradox espeon but like I said it looks like lunala.

**Comment by Superfire96** [comment]
I just checked all the files and everything is fine. If the names said pixelmon.ironeclipse than that was the paradox pokemon, if you didn't see the correct model is because you were missing the texturepack

**Comment by Paradis4432** [comment]
fixed inactive
