### ISSUE TITLE
random shadow pokemon wasn't shiny.

### ISSUE THREAD

**Issue by CJK45** [SmashMC-Development/Bugs-and-Issues#1814]
**Describe the Bug**
I got rewarded a random shadow pokemon and when I went to my pc to get it out it did not have a shadow pallet.  
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Doesn't really help explained like that, would need to know from where you received the random shadow pokemon, and when it happened, so that I can check the logs and make sure that it is an actual issue

**Comment by Paradis4432** [comment]
fixed inactive
