### ISSUE TITLE
Repetitive Huge Text

### ISSUE THREAD

**Issue by falzra** [SmashMC-Development/Bugs-and-Issues#1815]
When I enter my claimed area a huge text that looks like a server announcement appears on my screen. It says "How do I see where I put-" And then it cuts off.

1. Leave the claimed area
2. Enter it in anyway
3. The text appears on the screen

I have not been to other servers, this has only happened to me in Rayquaza.

I expected it to stop after I had rejoined.

N/A

This started after I was asking a friend how I could see where I placed my claim.  I also have tried reloading Minecraft and rejoining the server numerous times.

**Comment by Superfire96** [comment]
That's your claim title or something similar, can't really remember the correct name, just go to your claim options and remove that

**Comment by Paradis4432** [comment]
fixed inactive
