### ISSUE TITLE
Move Relearn Bugged

### ISSUE THREAD

**Issue by ParadoxxxGG** [SmashMC-Development/Bugs-and-Issues#1818]
When you go to relearn a move it brings you back to the screen where you choose the pokemon that you want to relearn a move.

**To Reproduce**
1. Go to Mart
2. Click on Move Relearner
3. Pick a pokemon
4. Pick a move
5. See error

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
