### ISSUE TITLE
Waiting 45m for same pokemon breeding

### ISSUE THREAD

**Issue by BriannaW61** [SmashMC-Development/Bugs-and-Issues#1819]
**Describe the Bug**
Pokemom are the same as well as OT and they take 45 to produce one egg

**To Reproduce**
1. Go to breeding machine
2. Click to breed both pokemon
3. Give them their respected items

**Servers with the Bug**
Mewtwo, could be all

**Expected behavior**
Not 45m of breeding time

**Screenshots**
![Proof](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133610591/7984456e-0dc7-4444-a25e-23855c6e6b8a)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
