### ISSUE TITLE
Illex Shrine still Broken on Kyogre

### ISSUE THREAD

**Issue by Skeletonio000** [SmashMC-Development/Bugs-and-Issues#182]
**Describe the Bug**
The Illex Shrine on kyogre still doesn't reset after you pay the fee.

**To Reproduce**
1. Go to ` /warp shrines ` on kyogre
2. Right click on the Illex Shrine
3. Click confirm to pay the fee
4. Notice how the shrine doesn't reset after you pay the fee.

**Servers with the Bug**
Kyogre

**Expected behavior**
The shrine should reset after the player pays the fee.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed.
