### ISSUE TITLE
Falling into the void after beating someone in wz

### ISSUE THREAD

**Issue by NotXoxiez** [SmashMC-Development/Bugs-and-Issues#1820]
a lot of the times that I beat someone in wz towards the middle part where there's the invisible blocks we fall into the void after winning a battled. also not the only one that has to deal with this problem 
![Screenshot_64](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/133866375/ed35cf6a-952e-4536-8157-2f4267702906)

**Comment by Paradis4432** [comment]
fixed
