### ISSUE TITLE
Cant rtp

### ISSUE THREAD

**Issue by BallerNL** [SmashMC-Development/Bugs-and-Issues#1824]
i cant rtp when i try to use the people at spawn i cant either when i try to rtp it just says you already are teleporting and i never teleport

**Comment by ItsLionX** [comment]
I cant Rtp when I try to use the people at spawn I cant either when I try to Rtp it just says you already are teleporting and I never teleport

**Comment by N0B0Z** [comment]
same

**Comment by Paradis4432** [comment]
fixed
