### ISSUE TITLE
Riolu is not evolving after max happiness

### ISSUE THREAD

**Issue by AleckAim** [SmashMC-Development/Bugs-and-Issues#1825]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
not enough info, please fill all requests
