### ISSUE TITLE
Party bug

### ISSUE THREAD

**Issue by Mobcrusher31** [SmashMC-Development/Bugs-and-Issues#1827]
**Describe the Bug**
A clear and concise description of what the bug is .My party on the left side of the screen only shows one pokemon not six

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Dxhcky** [comment]
If you press 'o' it cycles between different party layouts

**Comment by Paradis4432** [comment]
fixed inactive
