### ISSUE TITLE
not being able to rtp

### ISSUE THREAD

**Issue by N0B0Z** [SmashMC-Development/Bugs-and-Issues#1829]

**Comment by BallerNL** [comment]
same

**Comment by Paradis4432** [comment]
can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?.
when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn? 
thank you

**Comment by Paradis4432** [comment]
fixed
