### ISSUE TITLE
Missing textures on shadow Haxorus

### ISSUE THREAD

**Issue by KelpFan** [SmashMC-Development/Bugs-and-Issues#1830]
**Describe the Bug**
Shadow haxorus is missing it's texture in the latest pack and is seemingly now see through in parts of its body

**To Reproduce**

**Servers with the Bug**
Network
**Expected behavior**
There shouldn't be missing textures nor invisible parts to this pokemon. Multiple people seeing the same thing

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/139418317/91816fa7-09ef-4bab-84f0-06dca6b451a0)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
inactive
