### ISSUE TITLE
Cant rtp Again

### ISSUE THREAD

**Issue by BallerNL** [SmashMC-Development/Bugs-and-Issues#1831]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by BallerNL** [comment]
it just says already teleporting again

**Comment by gogosofie** [comment]
1. Begin in the Overworld
2. Go to chat and type '/brtp'
3. Click on 'Nether' 
4. Go to chat and type '/brtp'
5. See error

Note: Attempting to use the '/brtp' to travel between different dimensions seems to cause the issue. Player remains unable to use any '/rtp' command until server is restarted. Relogging and other warp means do not resolve the issue and are also unaffected when locked into the 'Already teleporting' bug.

**Comment by Paradis4432** [comment]
can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?.
when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn? 
thank you

**Comment by gogosofie** [comment]
It was primarily while being within the server for a while. I was however
able to reproduce this with being on the server for only a few minutes and
it being the very first command I input. It was not within spawn, and I
would select either Nether or End in /brtp

**Comment by Paradis4432** [comment]
and on what server were you?

**Comment by gogosofie** [comment]
I was able to do this on both Arceus and Kyurem while it was still up

**Comment by Paradis4432** [comment]
fixed
