### ISSUE TITLE
Can't Rtp

### ISSUE THREAD

**Issue by AdoDaPotato** [SmashMC-Development/Bugs-and-Issues#1832]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?.
when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn? 
thank you

**Comment by Paradis4432** [comment]
fixed
