### ISSUE TITLE
Pokemon Dissappearing w

### ISSUE THREAD

**Issue by NotXoxiez** [SmashMC-Development/Bugs-and-Issues#1833]
After battling people in WZ, people like myself and many others have been experiencing that when you go to steal a Pokémon from your opponent that they caught in the WZ they disappear, and we are unable to steal the Pokémon from them

Clip of proof

https://clipchamp.com/watch/jetfWYJ5OFN

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
