### ISSUE TITLE
Missingno pokemon crash game

### ISSUE THREAD

**Issue by RonhaverTov** [SmashMC-Development/Bugs-and-Issues#1834]
From no where my mew was gone and its replaced by pokemon named Missingno. 
every time when i opened my pc or just throw him it crashed me.
When i tried to give him to another person it just sayed there is no pokemon on this slot.
someone can help me please?!?!
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/139930029/729aabc5-0371-4f98-8b9f-32e81161d088)

**Comment by justwill935** [comment]
same here you know how to get rid of it

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by DaksssGG** [comment]
I have the same problem i cant do anithing with that slot....

**Comment by Paradis4432** [comment]
it should be fixed by next restart, according to other staff members
