### ISSUE TITLE
BRTP not working

### ISSUE THREAD

**Issue by raidMiner48TTV** [SmashMC-Development/Bugs-and-Issues#1836]
**Describe the Bug**
when doing /brtp and selecting the biome i want to go to it doesn't come up with a timer or teleport me
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
mewtwo server
**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?.
when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn? 
thank you

**Comment by Paradis4432** [comment]
fixed
