### ISSUE TITLE
Cant Teleport out to the wild

### ISSUE THREAD

**Issue by EmilioXY** [SmashMC-Development/Bugs-and-Issues#1837]
I cant teleport using the RTP or the biomertp command every time i try the chat says "you'er already teleporting" and then nothing happens.

**Comment by Paradis4432** [comment]
can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?.
when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn? 
thank you

**Comment by Paradis4432** [comment]
fixed
