### ISSUE TITLE
/brtp and /rtp not working

### ISSUE THREAD

**Issue by samsisam69** [SmashMC-Development/Bugs-and-Issues#1838]
So whenever i do /rtp and /brtp either nothing happens or it says im currently teleporting, pls fix this, i am not able to participate in bingo and hunts because of this and i can only catch pokemons around my home, which are mountain pokemons

**Comment by Paradis4432** [comment]
can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?.
when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn? 
thank you

**Comment by Paradis4432** [comment]
fixed
