### ISSUE TITLE
Galexy in wz thats supposed to spawn

### ISSUE THREAD

**Issue by CrownlessOcto** [SmashMC-Development/Bugs-and-Issues#184]
**Describe the Bug**
I thought galaxy cubfu wasn't supposed to spawn in wz but it did.

**To Reproduce**
Steps to reproduce the behaviour:
1. N/A as its a wz spawn

**Servers with the Bug**
Jirachi

**Expected behavior**
Not suppose to spawn

**Screenshots**
 'N/A'.

**Additional context**
BigAsianBananna has it on jirachi

**Comment by Mikirae** [comment]
This should be fixed on the server restart.
