### ISSUE TITLE
/rtp and /brtp aren't teleporting me

### ISSUE THREAD

**Issue by TheCheeseAddict** [SmashMC-Development/Bugs-and-Issues#1841]
**Describe the Bug**
When i type /rtp or /brtp it says in chat "you're already teleporting"

**To Reproduce**

**Servers with the Bug**
as far as i know groudon

**Expected behavior**
/brtp to take me to menu where i can select which biome i want to be teleported to
/rtp to teleport me somewhere random

**Screenshots**

N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?.
when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn? 
thank you

**Comment by Paradis4432** [comment]
fixed
