### ISSUE TITLE
PC Glitch With Missing Pokemon

### ISSUE THREAD

**Issue by Th3OmenTay** [SmashMC-Development/Bugs-and-Issues#1842]
My pokemon drowzee was deleted and replaced with a MISSING NO glitch in my slot 4. This happened when i was placing the drowzee in my PC and the game crashed. When i reloaded the game it was in the PC, but MISSING NO was in slot 4 on the MewTwo server. This honestly wldnt be that big of a deal since its just a drowzee, but now i cant remove the MISSING NO from my party and whenever I access my PC the game crashes now! I dont ask for any replacements, but i wld like the MISSING NO from my party removed plz so i can continue playing the game. At this time I"m new to PC and recently swapped over from console so dont know how to add screenshots yet srry!

**Comment by Th3OmenTay** [comment]
Currently completely unable to play due to this

**Comment by Paradis4432** [comment]
hello is this still active?

**Comment by Paradis4432** [comment]
inactive
