### ISSUE TITLE
I get stuck in 3rd person and am unable to move when my pixelmon try to evolve.

### ISSUE THREAD

**Issue by Venomungus** [SmashMC-Development/Bugs-and-Issues#1843]
**Describe the Bug**
When my pixelmon are about to evolve after a battle or from just gaining exp, I get put into 3rd person but I can still see the item I am holding as well as my full body holding the same item. I can still change what I hold and access my inventory as well as When I move the mouse I can see my character spinning but I cant move anywhere. The Pixelmon evolving currently is Riolu and I can see him glowing white with color particles around but all he does is walk around and no evolution happens no matter how long I wait. If I TP it usually frees me but the evolution gets canceled and now I am stuck with a level 65 Riolu who cant evolve.

**To Reproduce**
1. Meet all conditions for riolu to evolve
2. have Riolu gain enough exp to start evolving from winning a battle
3. Now you are stuck
4. You can send out pokemon or retreave them but if you retreave Riolu the evolution will be canceled.
5. If it gets canceled now you have to wait until day and raise your Riolu another 2 or 3 levels until you trigger evolution again and hope you dont get stuck.

**Servers with the Bug**
MewTwo

**Expected behavior**
Riolu should have evolved into Lucario

**Screenshots**
![pixelmon bug](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/140733491/86d26ec9-e075-4af1-ae84-3ecb56915e56)

**Additional context**
If I mount a pixelmon I get stuck in place mounted as well. There is no way out of this glitch other than reconnecting or sometimes tp away.

**Comment by Paradis4432** [comment]
any updates on this?

**Comment by Venomungus** [comment]
No, it happens randomly with different pixelmon.

**Comment by Paradis4432** [comment]
do you know of anyone else with this issue or just you?

**Comment by Venomungus** [comment]
I Haven't heard anyone say they have the same problem yet, so I assume just me

**Comment by Paradis4432** [comment]
then im gonna have to assume its an issue with your pc as i havent seen any other report about this either. you can try re-installing java (check what version you have), the launcher, forge or resetting your pc
