### ISSUE TITLE
pokemon didnt go into pc 

### ISSUE THREAD

**Issue by fragilescrab82** [SmashMC-Development/Bugs-and-Issues#1844]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by fragilescrab82** [comment]
got a legendary from lucky block adn didnt get it after threwing ball at it, it said i caught it but never went into my pc. fragilescarab82

**Comment by Paradis4432** [comment]
not enough info, please fill all requested data
