### ISSUE TITLE
Missing TR's in the /shop

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1845]
**Describe the Bug**
There are no Water-Type TRs in the /shop. TR/TMs are needed for the new Gen 9 pokemon as /buymove is not updated for those new mons yet. Every other Type is available via /shop.

**To Reproduce**
1. Go to any server'
2. Type in the command /shop
3. Head to the TR-Section
4. There are no Water-TRs available

**Servers with the Bug**
All pixelmon servers

**Expected behavior**
Water TRs buyable in /shop.

**Comment by Superfire96** [comment]
Will be fixed soon, most likely today
