### ISSUE TITLE
Unlimited Underwater Breathing

### ISSUE THREAD

**Issue by ArticJane** [SmashMC-Development/Bugs-and-Issues#1848]
**Describe the Bug**
Occasionally when jumping into water, your air does not go down, leading to the ability to swim underwater indeffinently, while other times your breath does go down, and if one relogs it fixes it so your breath does go down.

**To Reproduce**
Jump in water, on occasion when you go under the surface, your air will not go down at all. Seems random far as I can tell, reproduced it twice

**Servers with the Bug**
Please provide a list of which servers have this bug.
Groudon is the only one I've tested it on thus far

**Expected behavior**
I would expect to see the air to go down when under water

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
https://imgur.com/a/dRYsh4v

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Is there anything special that you're doing? I know you said it's random, but was wondering if maybe it's after you ride a Water Pokemon or something?

**Comment by Paradis4432** [comment]
inactive

**Comment by ArticJane** [comment]
Never saw this sorry. Now i was just jumping in and out trying to catch
pokemon at random. Not at all riding any
