### ISSUE TITLE
can't do the command rtp and brtp in smash mc in groudon 

### ISSUE THREAD

**Issue by sonic381** [SmashMC-Development/Bugs-and-Issues#1849]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
smash mc
**Expected behavior**
i cant do the rtp and brtp command and the rtp npc doesnt work for me too
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/141368887/0e173e39-4db2-4ecd-949b-73ac4bbd9355)

**Additional context**

**Comment by Mikirae** [comment]
This should be fixed tomorrow, hopefully!

**Comment by Paradis4432** [comment]
can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?.
when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn?
thank you

**Comment by Paradis4432** [comment]
fixed
