### ISSUE TITLE
Too Many AZ Floettes in WZ

### ISSUE THREAD

**Issue by CrownlessOcto** [SmashMC-Development/Bugs-and-Issues#185]
**Describe the Bug**
In WZ az Floette spawns more often than in the wild as I find one every 30 minutes unlike in the wild having a 5% chance of spawning.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to WZ
2. Run around and you will find an AZ Floette

**Servers with the Bug**
Jirachi

**Expected behaviour**
Shouldn't spawn in wz very often and should be rare

**Screenshots**
'N/A'.

**Additional context**
'N/A'.

**Comment by Mikirae** [comment]
I can honestly just disable it spawning in there to preserve the rarity.

**Comment by DragonBallBreakersRandomizer** [comment]
Yeah That be a good idea

**Comment by HackuJacku** [comment]
Unable to find any.
