### ISSUE TITLE
Treasure Hunt at Spawn on any of the servers does not work

### ISSUE THREAD

**Issue by exhaustableswag** [SmashMC-Development/Bugs-and-Issues#1850]
**Describe the Bug**
The treasure hunts at the spawns of the servers do not register and I do not receive any rewards from them.

**To Reproduce**
When a treasure chest is clicked on at spawn, no reward is received as a result for finding it.

**Servers with the Bug**
Please provide a list of which servers have this bug.
I have only tested it on Rayquaza and Mewtwo.

**Expected behavior**
I believe that there is supposed to be a reward for finding the treasure chest.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Mikirae** [comment]
This has been fixed but I guess we forgot to close this. Thank you!
