### ISSUE TITLE
Evolution bug

### ISSUE THREAD

**Issue by ManniFyGaming** [SmashMC-Development/Bugs-and-Issues#1853]
If I'm fighting and my pokemon evolves in the end of the fight, I'm stuck in a cursed screen and the pokemon isn't evolving

**To Reproduce**
1. Fight against a wild pokemon
2. Defeat it and get enough xp so your pokemon evolves
3. See error

**Servers with the Bug**
I only played rayquaza so i dont know if it's on the others too
**Expected behavior**
In the End of a fight if a pokemon evolves, it#s ending normal and evolving normal

**Screenshots**

![Screenshot 2023-08-08 235803](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/141784432/d953a062-1646-4b6a-8460-6bb449467e61)
![Screenshot 2023-08-08 235820](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/141784432/5914de99-0e97-4d1d-b3f2-4ed305d070a2)
![Screenshot 2023-08-08 235830](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/141784432/afdeec81-9baf-4df5-b1ee-ff8f200b885b)

N/A

**Comment by Mikirae** [comment]
Unfortunately, this is a Pixelmon bug :(
