### ISSUE TITLE
I cant brtp to mesa biome

### ISSUE THREAD

**Issue by Eoin010** [SmashMC-Development/Bugs-and-Issues#1854]
When I go to brtp to a mesa biome it says "teleporting in 2s. Dont move. Then I wait about 10s and then it shows a message "could not find a safe location within 101 attemps"
1. do /brtp
2. click on mesa
3. then wait a few seconds and you should see the message

Mewtwo is the one I play on.

I expected to teleport to a mesa biome

![2023-08-08_15 55 44](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/141786386/288160aa-213f-4253-812e-f1a20e8ea07c)

N/A

**Comment by Mikirae** [comment]
This should be fixed tomorrow I hope! Thank you for reporting this :)
