### ISSUE TITLE
Can't teleport

### ISSUE THREAD

**Issue by BruhDodo** [SmashMC-Development/Bugs-and-Issues#1855]
Every time I try to /brtp or /rtp it doesn't teleport me and just says "already teleporting"

**Comment by Paradis4432** [comment]
can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?.
when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn?
thank you

**Comment by StuartLimTY** [comment]
I also click on rtp or brtp and they keep saying "already teleporting"
I click on the end biome
Pls tell me how to solve this problem
Thank You.

**Comment by BruhDodo** [comment]
> can you explain if this was the first time you ran the command? ,you joined the server for the first time and ran the command? or are you already an user for a long time?. when you joined the server you ran the exact command "/brtp", to then click on what biome? was this on spawn? thank you

I was already a user for a couple weeks and when I would try to "/brtp" then click on whichever biome it would say invalid biome and then whenever I would either "/brtp" or "/rtp" it would say "already teleporting"

**Comment by Paradis4432** [comment]
on what servers were you both?

**Comment by BruhDodo** [comment]
> on what servers were you both?

I was on the rayquaza server.

**Comment by Paradis4432** [comment]
fixed
