### ISSUE TITLE
The command to show pokemon somehow broke after last reset.

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#1856]
**Describe the Bug**
The command to show pokemon in the chat seems to not work.

**To Reproduce**
1. Go to Rayquaza.
2. Have pokemon in your party.
3. Type the command [slot#] in chat # being a number from 1-6 respective to what slot you want to show. 

**Servers with the Bug**
Rayquaza was the only server where I encountered it, I tried all servers.

**Expected behavior**
The command [Slot#] is supposed to show a link in chat where if you hover over it would show information about the pokemon in the slot.

**Screenshots**
![afbeelding](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/45851395/0098f8da-d959-4b2a-baab-15abb4df8edf)
![afbeelding](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/45851395/8aab4fd6-2cc1-4996-af32-559a19597ef8)

**Additional context**
N/A.

**Comment by Indorlan** [comment]
I'd like to add that there is a difference between trying [slot1] & [slot6] and the others, when [slot1]/[slot6] is typed 
![afbeelding](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/45851395/ff31983f-2bd6-4759-8f98-b83407a59494)
![afbeelding](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/45851395/99484d0a-59cf-4607-8637-fd1853444572)

appears in chat and when any number from 2-5 is typed 
![afbeelding](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/45851395/00872172-d1e5-4033-ae15-6160766a5758) appears.
Dont mute me for spam ty those are all different commands :)

**Comment by Paradis4432** [comment]
inactive
