### ISSUE TITLE
Nothing spawned form uncommon lucky block

### ISSUE THREAD

**Issue by TheCheeseAddict** [SmashMC-Development/Bugs-and-Issues#1857]
I am in server groudon and i got an uncommon lucky block from daily rewards. I placed it down, broke it and in chat it said i "You broke an uncommon lucky block and got a shiny kammo-o" then i waited and waited and nothing appeared

**Comment by TheCheeseAddict** [comment]
i also looked in my pc if it just caught itself but nope

**Comment by Paradis4432** [comment]
do you have any evidence of this? any logs screenshoots etc

**Comment by Paradis4432** [comment]
inactive
