### ISSUE TITLE
Gym nots providing rewards 

### ISSUE THREAD

**Issue by psychoticraichu9** [SmashMC-Development/Bugs-and-Issues#1858]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by psychoticraichu9** [comment]
I'm in server Rayquaza and tried it again only for it to not pass and kept rebattling. After winning many times, it dont not go through. It was the bug gym

**Comment by psychoticraichu9** [comment]
looks like its all gyms

**Comment by Paradis4432** [comment]
fixed
