### ISSUE TITLE
Survival /buy command

### ISSUE THREAD

**Issue by BPuncake** [SmashMC-Development/Bugs-and-Issues#186]
**Describe the Bug**
Clicking on the items in the GUI for /buy doesn't do anything

**To Reproduce**
1. Go to survival
2. Type /buy
3. Try clicking on the items in the GUI

**Servers with the Bug**
Survival

**Expected behavior**
Clicking on an item in the GUI of /buy should give you a link to the corresponding store page

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed.
