### ISSUE TITLE
Cant craft some items

### ISSUE THREAD

**Issue by JesusTGoat** [SmashMC-Development/Bugs-and-Issues#1860]
**Description**
I cant craft certain items for example i tried to craft an old rod however when i placed the items in the crafting table the product box appeared empty and my friend couldnt do it either. Im not sure if its only an issue with modded items as i was able to craft a regular fishing rod instead

**Server**
Playing on Groudon server so unsure if other servers are able to or not

**Expected behavior**
When i placed all the items in i expected the old rod to appear in the crafting slot so i could click on it to make it but the slot appeared blank

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/142455134/cb83c2d0-7d24-439b-819e-ed9063ed8e71)

**Comment by Superfire96** [comment]
That is not how you craft the old rod tho, you have to add the pokeball too
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/83550357/68391dfe-10ee-4986-9c02-979ed5fb330d)

**Comment by Paradis4432** [comment]
inactive
