### ISSUE TITLE
rtp doesnt work

### ISSUE THREAD

**Issue by perolol** [SmashMC-Development/Bugs-and-Issues#1862]
so i tried to rtp using biome and when the count to teleport went down i couldnt teleport and when i tried to rtp again it just says "you're arleady teleporting!" and i cant teleport anywhere
 I was playing on the server Mewtwo

![bug](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/142794534/8d7708a7-7811-4e69-90a9-172e65b6c77b)

**Comment by Paradis4432** [comment]
what happens if you try a few times?

**Comment by Stefa2010** [comment]
it does the same for me

**Comment by Paradis4432** [comment]
what biome did you click

**Comment by perolol** [comment]
sorry i didnt respond earlier so when i try a few times it just does the same thing "you're arleady teleporting!" and to answer the question to what biome i clicked i think it was "THE END" and when it said dont move teleporting in 2 seconds it said it didnt find a  safe place to spawn and i just cant teleport anymore

**Comment by Paradis4432** [comment]
fixed
