### ISSUE TITLE
Mega evolving/Dynamax does not work outside battle anymore

### ISSUE THREAD

**Issue by jonaboy19** [SmashMC-Development/Bugs-and-Issues#1864]
**Describe the Bug**

**To Reproduce**
1. Go to mega band.'
2. Click on mega evolve icon
3.  try it
4. and it wont do anything

**Servers with the Bug**
Mewtwo

**Expected behavior**
I exptected my mons to dmax or mega evolve outside of battle.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
i cant change my eternatus back to its normal form(its in eternamax form now) and i cant mega evolve mons outside of battles(all the pokemons)

**Comment by Paradis4432** [comment]
do you have an exact time this happened so i can check the server logs?

**Comment by Paradis4432** [comment]
inactive

**Comment by jonaboy19** [comment]
oh i forgot my password. but its not possible to mega evolve/dynamax pokemons outisde battle anymore for some reason. and yes i downloaded the update to 9.1.7 for the mega evolve mod aswell. but won't do anything.
