### ISSUE TITLE
when i use /brtp it dosent work and when i use it, if i try to use /rtp after it says "alrready teleporting"

### ISSUE THREAD

**Issue by samusonic221** [SmashMC-Development/Bugs-and-Issues#1866]
when i use /brtp it dosent work and when i use it, if i try to use /rtp after it says "alrready teleporting"

**To Reproduce**
1. type /brtp and any biome in rayquaza server
2. it wont work so then try /rtp
3. it will just say already tping

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
this is a known issue, after restart it will fix itfself, a new version of RTP is being developed
