### ISSUE TITLE
RTP doesn't work

### ISSUE THREAD

**Issue by MarinaraFry** [SmashMC-Development/Bugs-and-Issues#1867]
**Describe the Bug**
I clicked on the end in biome rtp and it started saying "You're already teleporting!" whenever I would try to biome rtp or rtp after that, it is still doing it and I don't know how to fix it.

**To Reproduce**
1. Go to Biome RTP
2. Click on The End
3. It will start saying "You're already teleporting!" after you try to RTP

**Servers with the Bug**
Kyogre

**Expected behavior**
I expected to be teleported to the End biome.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
we are aware of this and working on a solution
