### ISSUE TITLE
Evolving then going Third Person

### ISSUE THREAD

**Issue by BBird14** [SmashMC-Development/Bugs-and-Issues#1869]
When I Level up a Pokemon and it starts to evolve it will put me into third person and the pokemon wont evolve. The only way for me the fix it is to disconect and log back and force the pokemon to evolve before I battle and level it up.

![2023-08-29_19 42 58](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/143566990/b70f1f49-5798-4b6b-9df4-33aab3917c48)

**Comment by Paradis4432** [comment]
already reported this to pixelmon, we cant do anything to fix it

**Comment by AncientEvils** [comment]
Now my froakie wont evolve after this happened.

**Comment by Archie4690** [comment]
@AncientEvils You should be able to open a support ticket in our discord to get any Pokémon evolved that are unable to do so :)
