### ISSUE TITLE
/rtp doesnt work

### ISSUE THREAD

**Issue by BriarRoot22** [SmashMC-Development/Bugs-and-Issues#1870]
**Describe the Bug**
says "already teleporting" when i try to /rtp

**To Reproduce**
1. Go to /brtp
2. Click on any biome
3. Scroll down to n/a
4. See error "youre already teleporting"

**Servers with the Bug**
 rayquaza server

**Expected behavior**
to be able to /rtp and a little help in the servers

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Paradis4432** [comment]
uploaded a version that should help with this
