### ISSUE TITLE
i can't take back the pokemon that i sell on the GTS

### ISSUE THREAD

**Issue by michael6699** [SmashMC-Development/Bugs-and-Issues#1873]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
please provide more information
