### ISSUE TITLE
when I click rtp it doesnt work.

### ISSUE THREAD

**Issue by JohnChoi3404** [SmashMC-Development/Bugs-and-Issues#1874]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by JohnChoi3404** [comment]
please tell me how to fix rtp to work

**Comment by Paradis4432** [comment]
if you dont fill the requirements its hard to help you, its there for a reason
