### ISSUE TITLE
Broke an Uncommon Lucky Block at my home(shiny Hakamo-o) but it didn't spawn for me. Wasn't on the map or in PC.

### ISSUE THREAD

**Issue by BrendanYO** [SmashMC-Development/Bugs-and-Issues#1876]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
fixed a while ago
