### ISSUE TITLE
Ash greninja (battlebond) wont work with specific pokemon

### ISSUE THREAD

**Issue by Ozymandias435** [SmashMC-Development/Bugs-and-Issues#1878]
When you do the command to claim a specific pokemon i put greninja for pokemon and it gave me the option of battle bond and of course i chose this. It gave me a regular greninja i tried it again with another specific pokemon and the same thing happened
![Screenshot (23)](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/146893307/b16907b7-8626-46da-8d8b-80761f90c65d)
![Screenshot (24)](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/146893307/81380193-0b36-4068-afad-7e0243710f5b)

**Comment by Paradis4432** [comment]
what server?
