### ISSUE TITLE
Pokemon won't evolve

### ISSUE THREAD

**Issue by Yasu1t** [SmashMC-Development/Bugs-and-Issues#1879]
My fuecoco won't evolve eventhough i've leveled him past level 16. I've tested with other pokemon but they do seem to evolve just as they should.

![2023-10-15_14 21 57](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/147985088/841c481c-aab1-4d63-9a95-ecdfba8be2c3)

**Comment by Paradis4432** [comment]
has this been solved in the recent updates? in what server is this?
