### ISSUE TITLE
Phione spawning as a legendary in warzone

### ISSUE THREAD

**Issue by Ryan1595** [SmashMC-Development/Bugs-and-Issues#188]
**Describe the Bug**
Phione will spawn in warzone, and it counts as a legend spawn. When Phione spawns it prompt the "A Wild Phione has spawned in warzone!"

**To Reproduce**
Just check the game files lol

**Servers with the Bug**
I have only seen this on Jirachi, could be on other servers.

**Expected behavior**
Phione should spawn as a normal poke, not a legendary.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Has this always been a thing? We haven't really changed anything with that.

**Comment by Ryan1595** [comment]
I think so, I remember seeing it like a month ago.

**Comment by Mikirae** [comment]
Ah, that'll be something that's fixed on the rewrite then. Thank you! :)
