### ISSUE TITLE
Warzone bug

### ISSUE THREAD

**Issue by Kiritsiku** [SmashMC-Development/Bugs-and-Issues#1880]
When you get an egg from warzone and someone attacks you before you click "take" it dissapears

**To Reproduce**
1. Go to Warzone
2. fight a palkia or another that gives and egg
3. when an egg shows up don't click anything and let someone engage in a battle
4. then lose the game and let the other person pick a pokemon on your team

**Servers with the Bug**
Mewtwo on Smashmc have this

**Expected behavior**
I Killed a palkia in warzone and got an egg. before i could click take someone else engaged in a battle with me so the screen dissapeared. it does not come up in logs either

**Screenshots**
N/A

**Additional context**
When you check this out and it does exactly what is described, could i please be returned my rightful palkia egg, I can show logs of me fighting it aswell.

**Comment by Paradis4432** [comment]
unable to recreate and i havent heard of anyone else with this issue, maybe it was a lag problem or a 1 time thing, if it happens again feel free to dm at Paradis#4432
