### ISSUE TITLE
Drop in frame rate causing me to have to leave the game and close the application so it goes away briefly; Needs to be fixed

### ISSUE THREAD

**Issue by Sucas2938** [SmashMC-Development/Bugs-and-Issues#1881]
**Describe the Bug**
After playing for a bit, it gets very choppy and drops frames. A lot of times, this will also cause me to be stuck in battles or evolutions and have to manually close application. My hardware and connection speed are more than adequate so please let me know if there are settings I should specifically change, appreciate it!
-The_All_Knowing

**To Reproduce**
1. Arceus Server
2. Play until drop in frames occurs and continue to play through it; it progressively gets worse; unknown trigger

**Servers with the Bug**
Which ones I've tried this far: Arceus

It may occur on other servers but am in too deep to switch lol

**Expected behavior**
Seemless experience, really love the server and honestly is my favorite thus far in regards to Pixelmon servers - none the less, bravo!

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
if its an fps drop then theres not much the server can do, i recommend disabling antimalware if you are on windows, use optifine and optimization mods, or open task manager and see whats at 100%

**Comment by Paradis4432** [comment]
if its a specific location thats lagging you let me know where and ill check it out
