### ISSUE TITLE
Missingno

### ISSUE THREAD

**Issue by RSFOX** [SmashMC-Development/Bugs-and-Issues#1882]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
in the future try to fill all the values, this is a pixelmon bug and theres nothing we can do to fix it for now
