### ISSUE TITLE
I can't place block like how you can't place blocks on someone else's owned land but everywhere

### ISSUE THREAD

**Issue by SirOof99** [SmashMC-Development/Bugs-and-Issues#1883]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
do you get a message, what server, can you make a video?
