### ISSUE TITLE
Cosmic Virus not being able to spawn

### ISSUE THREAD

**Issue by arska1** [SmashMC-Development/Bugs-and-Issues#1885]
**Describe the Bug**
Cosmic Virus's spawning weren't found..

**To Reproduce**
/wiki CosmicVirus and then pressing "spawning" just leaves a blank list of biomes,
secondly, when typing "/checkspawns" (above Y:230 and on crying obsidian, it doesnt show in the list of possible pokemons)
all of this is on the groudon server ( copied from a ticket made by a player )

**Servers with the Bug**
All

**Expected behavior**
There should be a spawning biome set

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/9020309/25d17136-6717-4865-ac97-d6f9335c97c5)

**Additional context**
-

**Comment by Paradis4432** [comment]
thank you, reporting

**Comment by Paradis4432** [comment]
its not meant to spawn there, its missing an update
