### ISSUE TITLE
Pokemon wont evolve and I go into different point of view and get stuck and cant move.

### ISSUE THREAD

**Issue by omlewis20** [SmashMC-Development/Bugs-and-Issues#1886]
**Describe the Bug**
Anytime I battle and a pokemon is evolving it gets stuck and my point of view changes. I cant move when this happens. 

**To Reproduce**
1. /rtp to any location
2. Battle until one of your pokemon is ready to evolve.
3. See Error

**Servers with the Bug**
Pixelmon SMASHMC Groudon Server

**Expected behavior**
For my pokemon to evolve.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by omlewis20** [comment]
<img width="2240" alt="Screen Shot 2023-10-22 at 6 33 55 PM" src="https://github.com/SmashMC-Development/Bugs-and-Issues/assets/148727417/23722484-f02d-44e4-86a2-078bd572aa2d">

**Comment by Paradis4432** [comment]
this is a pixelmon bug, we already reported it but theres no response
to "fix" this you can relog
