### ISSUE TITLE
Ability Capsule not working

### ISSUE THREAD

**Issue by JBxSky** [SmashMC-Development/Bugs-and-Issues#1888]
**Describe the Bug**
Ability capsule not working on any pokemon 

**Servers with the Bug**
Groudon

**Expected behavior**
Pokemon's ability switching to the one that is available.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Paradis4432** [comment]
this got reported in a ticket and is being fixed
