### ISSUE TITLE
Scroll problem with Defeat x wild pokemon x/x

### ISSUE THREAD

**Issue by Pumamon** [SmashMC-Development/Bugs-and-Issues#1893]
**Describe the Bug**
Scroll quest where you have to defeat wild pokemon doesn't work.

**To Reproduce**
1. Go to inventory
2. Hover over scroll with Defeat wild pokemon x/x
3. Defeat a wild pokemon
4. Scroll doesn't update count of defeated wild pokemon

**Servers with the Bug**
Only tried on Groudon so unsure of others.

**Expected behavior**
When you have a scroll with quest/perk Defeat wild pokemon x/x it won't update progress on defeating wild pokemon for that quest/perk on the scroll so you are unable to complete scroll. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
yea we are aware of this and working on a solution
