### ISSUE TITLE
Issues with items from /shop

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1895]
**Describe the Bug**
I have seen that the "Destinity Knot" was replaced with the original "Destiny Knot" in the shop again. I thought this was a way to prevent it from being used as a way to store money that can't be seen by the means of /bal ect. while keeping original Destiny Knots and Everstones sellable.
_Anyways_, seems like it was a typo. In this case it might be a good idea to fix the "Ever Stone" too. The original name is "Everstone". This is important because it makes the items neither sell, nor stackable with the original Everstone item.

**To Reproduce**
1. Go to any Server
2. Type in /shop
3. Navigate to "Breeding Items"
4. Take a look at the Everstone, buy one, try to stack with natural ones or try to sell to shopkeepers. Does not work cause wrong itemname.

**Servers with the Bug**
All pixelmon realms

**Expected behavior**
See Description

**Comment by Paradis4432** [comment]
fixed by super by next restart. thank you for the report
