### ISSUE TITLE
Defeat # Wold Pokemon Scroll

### ISSUE THREAD

**Issue by aquathump** [SmashMC-Development/Bugs-and-Issues#1896]
**Describe the Bug**
The counter for defeating wild pokemon doesn't change when defeating wild pokemon

**To Reproduce**
1. Go to inventory
2. Hover over Scroll
3. Defeat # Wild Pokemon #/#
4. Defeat wild pokemon
5. No change in count

**Servers with the Bug**
Only seems to happen in Groudon

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
fixed with the latest update
