### ISSUE TITLE
Cant find Bullet punch 

### ISSUE THREAD

**Issue by PoGipoo** [SmashMC-Development/Bugs-and-Issues#1897]
**Describe the Bug**
i need an ability called bullet punch and i see that i cant find it in the shop or npc's even the relearner cant find it and i used it on a pokemon that could learn it before 
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
rayquaza
**Expected behavior**
for someone making getting this not so rare ability obtainable 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
n/a
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by Paradis4432** [comment]
i dont understand what the problem is here
