### ISSUE TITLE
Mining skills still not working

### ISSUE THREAD

**Issue by LucaronLoL** [SmashMC-Development/Bugs-and-Issues#1899]
As already written in earlier bug reports the mining skills don't seem to be working.
No haste buff after rightclicking with a pickaxe and no veinmining while crouching.

try to use the mining skills.

**Servers with the Bug**
i am on Groudon but it probably affects other servers as well.

**Expected behavior**
get a haste buff and mine multiple ores at once 

**Additional context**
i already read in an older ticket that aparently there hasn't been an update in quite a while to the plugin but it's still annoying.

**Comment by Paradis4432** [comment]
are you the only one with this issue? i havent seen any other reports about this

**Comment by LucaronLoL** [comment]
you can read a lot of people asking how to activate the mining ability and from what ive seen not a lot of people focus on mining since pokeballs are so cheap to buy

**Comment by Paradis4432** [comment]
hm ill look into it thanks
