### ISSUE TITLE
Missing move tutors at /Warp mart

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#190]
**Describe the Bug**
The Move tutors NPCs are not at /Warp mart

**To Reproduce**
1. Go to /server mew
2. Go to /warp mart
3. See error

**Servers with the Bug**
Mew

**Expected behavior**
Move tutors should be there

**Screenshots**
![2021-05-24_21 40 59](https://user-images.githubusercontent.com/83550357/119402787-ba0adb00-bcdd-11eb-9e85-c366b7defdb6.png)

**Comment by HackuJacku** [comment]
Use `/buymoves` as tutors are messed up in Pixelmon
