### ISSUE TITLE
My luxio isnt evolving

### ISSUE THREAD

**Issue by UnsoundWolf** [SmashMC-Development/Bugs-and-Issues#1900]
I was leveling up my luxio when I hit level 30 it didnt evolve or do anything and I do not have a everstone on the pokemons hold

**To Reproduce**
Go to mcsmash get a luxio
lvl it to 30

McSmash
**Expected behavior**
My Luxio evolving when it hit lvl 30
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/151830871/cc81b2cf-e270-4446-8998-27df10441b1e)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
relog and run /evofix
