### ISSUE TITLE
Issue with items from /shop

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1901]
**Describe the Bug**
You can not use the Ultra Ball from the /shop to craft a good rod. Same goes for the normal Pokéball from /shop for the old rod.
It works with balls from any other source tho. 

**To Reproduce**
1. Go to any server
2. Get materials for a good rod/old rod
3. Make sure you get the ball from /shop
4. Try to craft the respective rod with it

**Servers with the Bug**
All pixelmon servers.

**Expected behavior**
Being able to craft items with the balls from /shop.

**Comment by Paradis4432** [comment]
we are looking into this but we need to wait for the developer's response. thank you for the report
