### ISSUE TITLE
God Lucky Blocks

### ISSUE THREAD

**Issue by Darth225** [SmashMC-Development/Bugs-and-Issues#1902]
**Describe the Bug**
When opening a God Lucky Block if one player is to close they can catch from the block. But it also makes so none of the other mons can be caught
**To Reproduce**
1. Place God Lucky Block
2. Break with another player within 20 blocks
3. Mons will spawn with no special texture
4. Player close will be able to catch one mon, and other two will be uncatchable

**Servers with the Bug**
Please provide a list of which servers have this bug.
I would assume All servers, but Groudon
**Expected behavior**
Hoping the bug gets fixed for the people who buy the $100 God Block
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Paradis4432** [comment]
we will look into it, thank you
