### ISSUE TITLE
the grass gym leader wont show up for me

### ISSUE THREAD

**Issue by danny98o9** [SmashMC-Development/Bugs-and-Issues#1905]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
gyms are not fully functional, we are working on it
