### ISSUE TITLE
"Delete All" option went missing

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1906]
**Describe the Bug**
The option to delete all items after a wild battle went missing after the update to 9.1.10.

**To Reproduce**
1. Go an any server
2. Defeat wild pokemon
3. No option to delete items

**Servers with the Bug**
All

**Expected behavior**
Option to delete items for lag-decrease/quality of life

**Screenshots**
![2023-12-14_08 53 30](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/94211853/0eef6ab4-c090-4a7c-8c94-c3c33fecdfdb)

**Comment by Paradis4432** [comment]
thats not something we can really change, up to pixelmon

**Comment by DinglePringleUwU** [comment]
As additional information - even tho this is closed now - i would like to add that this has been changed back!
