### ISSUE TITLE
Daycare doesn't like to work for me. 

### ISSUE THREAD

**Issue by Jessister** [SmashMC-Development/Bugs-and-Issues#1907]
![Screenshot 2023-12-16 212111](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/154036032/73db9a99-ba56-492b-82ce-640d941f3d72)

My daycare doesn't like to work. Like, I'll have the materials, but it won't let me put them into the daycare. Also, often even though the egg will say completed, the daycare won't let me receive it, whenever I hit the check mark to get the egg it just kicks me out. No idea if anyone else is having this problem or how to replicate it for others. I am on the SmashMc Pixelmon server, specifically the mewtwo one.

**Comment by Paradis4432** [comment]
do you know if this is an issue everyone is having or just you?
