### ISSUE TITLE
Bosstower

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#1908]
**Describe the Bug**
The NPC in the bosstower in Mewtwo on the top level says that there should be spawning grass pokemon but there are fire bosses spawning

**To Reproduce**
1. Go to Mewtwo
2. do /warp bosstower
3. go to the top floor
4. See issue

**Servers with the Bug**
Mewtwo

**Expected behavior**
Expect grass mons to spawn

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
reported and will fix tonight, thanks
