### ISSUE TITLE
prices arent accurate on the in game store

### ISSUE THREAD

**Issue by xiles777** [SmashMC-Development/Bugs-and-Issues#1909]
prices do not match what is advertised
the elite rank says it is 1500 coins but then says 2500 when clicked on

**Servers with the Bug**
mewtwo/smash.mc

**Expected behavior**
i expected the rank to be 1500 coins like advertised 

**Screenshots**
![1 ss](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/154869034/9427e099-f730-4da1-a679-0d8ea47690af)
![2 ss](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/154869034/004a6311-542d-4f78-ac48-5bd7c3655932)

**Additional context**
n/a

**Comment by Paradis4432** [comment]
fixed, thank you for the report
