### ISSUE TITLE
Broken shopkeepers on Charizard

### ISSUE THREAD

**Issue by krossuu** [SmashMC-Development/Bugs-and-Issues#191]
**Describe the Bug**
Some of the shopkeepers at /warp mart are currently broken on charizard

**To Reproduce**
n/a

**Servers with the Bug**
The only one i know of rn is Charizard

**Expected behavior**
I expect the shopkeepers to be working soon 

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Mikirae** [comment]
Would need to know more about how they're broken. They look fine for me. Please let me know if they're still broken.

**Comment by krossuu** [comment]
Hi! The shopkeepers are working fine now, not sure why three of them weren't accessible at the moment, ty :)

**Comment by Mikirae** [comment]
Okay glad it's working now :)
