### ISSUE TITLE
Missingno stuck in my party

### ISSUE THREAD

**Issue by Jessister** [SmashMC-Development/Bugs-and-Issues#1910]
**Describe the Bug**
![Screenshot 2024-01-01 180126](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/154036032/6ae7bac2-8094-4f42-bf8f-e55ac84b815a)

When I tried to put my bayleef into my pc, in it's place left a missingno. Panicking, I put the rest of my pokemon in my pc and got a second missingno where my pink primate was. 
I cannot move the missingnos, they won't go in the pc or swap with a different spot in the party, even when another pokemon is around.
The missingno deleted my bayleef when i tried to just put him back in it's spot. 

![Screenshot 2024-01-01 180411](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/154036032/b3a1a6f1-9639-401c-b4f9-7192480d148c)

I have no idea how this has happened, or if others have experienced it before me, as no one has responded when I tried to ask about it in the pokemon mewtwo server. 

Weird game glitches have been happening today too that went away after just restarting my game. Unsure if related
![Screenshot 2024-01-01 175927](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/154036032/2ca56e01-8c46-4703-a534-7e797fd5152f)
![Screenshot 2024-01-01 160205](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/154036032/260625c0-faac-4533-946d-a70e9d0e9c5a)
![Screenshot 2024-01-01 160226](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/154036032/594f3b26-966e-4c33-b0fa-5d60acece704)

Missingno crashes my game when sent out into battle with the following error message:
 The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error

The game also saved the server before crashes so I am stuck with the missingnos. 

They also just don't show up as pokemon in your party, as here's when I went into a battle with a regular pumpkaboo as a test. 
![Screenshot 2024-01-01 180826](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/154036032/3538c32d-a860-4d02-b8d6-01138bb9bd72)

I think that is everything, i'm just very bewildered.

**Comment by Paradis4432** [comment]
missingno is a pixelmon bug that fixes itself on server restart
