### ISSUE TITLE
Hourglass Bug 

### ISSUE THREAD

**Issue by FebreezyBri** [SmashMC-Development/Bugs-and-Issues#1911]
**Describe the Bug**
Hourglasses sometimes wont work or they're bugging the daycare machine, It wont show the timer and makes the player have to restart the breeding all over again.

**To Reproduce**
1. Go to Daycare Machine
2. Click on the pokemon you put in with an hourglass
3. See the timer is broken

**Servers with the Bug**
Groudon, havent seen all of them

**Expected behavior**
The timer will dissapear and you will have to restart the breeding process

**Screenshots**
![Screenshot_20240107_050232](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/121701479/13fed688-c307-4a8a-b2ca-4f6a161a1acd)

**Additional context**
It also does not let you use the hourglass sometimes.

**Comment by Paradis4432** [comment]
theres not much we can do here, since this is more of a pixelmon bug
