### ISSUE TITLE
No premium Battle pass upon purchase of "Elite Rank"

### ISSUE THREAD

**Issue by SalmonSlammer47** [SmashMC-Development/Bugs-and-Issues#1912]
I just purchased the Elite rank for $2,500 Smash Coins and got most of my rewards other than the premium battle pass being unlocked. I tried logging off and logging back in but to no avail. This happened on the Zekrom server around 3:20AM central US time.

Username: SalmonSlammer47

**Comment by Paradis4432** [comment]
do you konw of anyone else with this issue? has this fixed itself?
