### ISSUE TITLE
Lucky Block Spawn Issue

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1913]
**Describe the Bug**
Shiny Male Nidorans dont spawn from lucky blocks. Likely due to their male pattern. 

**To Reproduce**
1. Open an Uncommon Lucky Block
2. Get a "Shiny Nidoran Male"
3. It does not spawn

**Servers with the Bug**
All

**Expected behavior**
The Shiny should spawn.

**Additional context**
Spawn issues with patterned pokemon were always kinda there. Unsure if fixable at all, tried searching for similar reported issues but couldnt find any.

**Comment by Paradis4432** [comment]
yea we are aware of it and working on a solution
