### ISSUE TITLE
Biome rtp broken in mushroom biome

### ISSUE THREAD

**Issue by Elcactus777** [SmashMC-Development/Bugs-and-Issues#1917]
**Describe the Bug**
whenever you try to rtp to a mushroom biome, it says that the game couldnt find a safe location. Even if you try a dozen of times, it never works
**To Reproduce**
do /brtp and choose the mushroom biome
**Servers with the Bug**
Groudon
**Expected behavior**
I expected to get teleported there.
**Screenshots**
linked with the bug report
![BUGimage](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/159814486/3bff726f-1cc2-48f1-9bb2-3aba4c6ab157)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
we add a safe location so you dont teleport into a wall or lava, its mostly luck
