### ISSUE TITLE
Vaults not working on Kyogre Serever

### ISSUE THREAD

**Issue by GameOverMR** [SmashMC-Development/Bugs-and-Issues#1918]
When I got the expert rank I earned access to the /vaults command to store stuff in a personal box. However when I put stuff in it yesterday but wanted to access stuff from it today it would not open. I did the right command, /vaults, but when I submitted I got no error message nor did the box open. Now I cannot access 8 lucky eggs, 3 masterballs, and 100+ rare candies.

**Comment by Paradis4432** [comment]
was this fixed? otherwise please open a ticket
