### ISSUE TITLE
Warzone

### ISSUE THREAD

**Issue by AlphaKimi1** [SmashMC-Development/Bugs-and-Issues#1919]
Hey i play on groundon server and i was in warzone. Some player have battled me and i lost, but when i got back in normalwolrd i got this screan wich i cant get around, cant even move, cant do thing.
![Mc](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/160523781/1d921afd-dcda-4f22-b228-d0417c36549a)
https://gyazo.com/0c3c5e88e306c47934aee72bdf6ddf44

I think one of this sc works for u. Thank you. See you soon.

**Comment by Paradis4432** [comment]
sorry for the late response, will report. thank you
