### ISSUE TITLE
bubbles

### ISSUE THREAD

**Issue by frenchtoast5796** [SmashMC-Development/Bugs-and-Issues#1920]
**Describe the Bug**

**To Reproduce**
1. Go to the ocean and lose your bubbles
2. Click on your pokemon that gives you inf bubbles and give rare candys and get on it
3. look down and you will se the last bubble pop animation
4. you will have inf water breathing without any pokemon

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
pixelmon bug, not much we can do
