### ISSUE TITLE
Day Care UI Misaligned 

### ISSUE THREAD

**Issue by RaccsX** [SmashMC-Development/Bugs-and-Issues#1922]
**Describe the Bug**
Not a major issue. Daycare UI doesn't align properly and gets in the way of clicking around.

**To Reproduce**
1. Click on a Day Care block
2. See error: The pink Chansey Day Care border for the UI doesn't align with the rest of the UI

**Servers with the Bug**
MewTwo

**Expected behavior**
The border is supposed to surround the UI without getting in the way

**Screenshots**
![Screenshot 2024-03-05 002057](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/162281065/6ff4a54d-28cf-478b-9952-eac1b4ef2c74)
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/162281065/e85aa641-3afb-4ad6-b36e-df8466717a7b)
(I'm not sure if this worked, it just shows up as text on my end)

**Comment by Paradis4432** [comment]
this was fixed
