### ISSUE TITLE
shiny isnt shiny

### ISSUE THREAD

**Issue by Hxxity** [SmashMC-Development/Bugs-and-Issues#1923]
**Describe the Bug**
the level up reward for level 55 battler is a free random shiny, however it wasn't a shiny

**To Reproduce**
reach level 55?

**Servers with the Bug**
I only play groudon

**Expected behavior**
to get a shiny pokemon

**Screenshots**
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/163022134/d63a1a9e-5308-4411-a874-0a8c1e1e23ec)
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/163022134/47ab6b32-b0a4-42b4-ba34-d187f7538135)

EDIT: NOTHING IS WRONG I CANT READ

**Comment by Paradis4432** [comment]
we'll review this, thank you

**Comment by Paradis4432** [comment]
why do you think you should get a shiny?

**Comment by Hxxity** [comment]
because im an idiot and cannot read im sorry

**Comment by Hxxity** [comment]
i mightve been sleep deprived and didnt notice it said shadow instead of shiny, my bad

**Comment by Paradis4432** [comment]
you are not! no problem
