### ISSUE TITLE
Essence Bottles not showing up

### ISSUE THREAD

**Issue by RaccsX** [SmashMC-Development/Bugs-and-Issues#1924]
**Describe the Bug**
The Essence bottles no longer show up as an inventory item but does when dropped.

**To Reproduce**
1. Acquire an essence bottle or click on a TCG npc
2. Hover over the blank spots where the essence bottles should be and the item itself is still there, just no png

**Servers with the Bug**
MewTwo

**Expected behavior**
There should be a png of the essence bottle(s)

**Screenshots**
(edited because of wrong screenshot)
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
can you check if this is still an issue i think it was fixed
