### ISSUE TITLE
brtp not working

### ISSUE THREAD

**Issue by Tabzee1987** [SmashMC-Development/Bugs-and-Issues#1925]
**Describe the Bug**
it wont let me brtp anywhere it says cant find a safe place to teleport you everywhere

**To Reproduce**

**Servers with the Bug**
groudon

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
this is not a bug, it means the biome you want is not close enough, or corrupted by lava, blocks or something else, either explore and try again or move somewhere else and try again
