### ISSUE TITLE
only 24/25 treasure hunt in spawn

### ISSUE THREAD

**Issue by CharlieJTom** [SmashMC-Development/Bugs-and-Issues#1926]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
explain please or im gonna have to close this
