### ISSUE TITLE
boss tower

### ISSUE THREAD

**Issue by blackdemonknight** [SmashMC-Development/Bugs-and-Issues#1927]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by blackdemonknight** [comment]
the yellow room the boss pokemons are underneath the floors and unable to battle them

**Comment by Paradis4432** [comment]
what server
