### ISSUE TITLE
Did not receive listed dex rewards for 50 percent completion

### ISSUE THREAD

**Issue by im-t3x** [SmashMC-Development/Bugs-and-Issues#1928]
**Describe the Bug**
when claiming 50 percent Dex rewards, did not receive: 

Veteran status,
2 fusion shards,
1 hopper vault.

I did receive masterballs and great balls.

**To Reproduce**
claim dex rewards
**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre
**Expected behavior**
To receive all dex rewards as listed. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
reported thank you
