### ISSUE TITLE
water and else pokimon

### ISSUE THREAD

**Issue by bobobobobobbobobobboobobobob** [SmashMC-Development/Bugs-and-Issues#1929]
**Describe the Bug**
Pokémon's like lapras and gyarados, that look like they can float on water and move fast on it, move really slow and drown in the water, gyarados is suppose to fly i think, and it doesn't even float on water?

**To Reproduce**
1. Go to an ocean
2. get  your water type that looks like it can swim fast Pokémon
3. enter the ocean when your riding the pokemon

**Servers with the Bug**
groudon in smash mc server, mayby other ones too, i didn't check.

**Expected behavior**
the lapras/other water/gyarados Pokémon will float on the water and move very fast in water.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
groudon was having some issues 13 hours ago, can you check if its happening now?
