### ISSUE TITLE
warzone problem

### ISSUE THREAD

**Issue by morrow12** [SmashMC-Development/Bugs-and-Issues#193]
there is a problem with warzone
there seems that there is alot of pokemon in the warzone
way to much
i keep on crashing even with a really good pc
now i cant go into wz
alot of people crash there too
what im here to say is to make wz less laggy by reducing the amout of pokemon there
before 8.2 i never had this problem.... like this whole update ruined the server like the battle gui is so delayed and its easy to missclick

**Comment by Mikirae** [comment]
Is this still an issue? I believe Hacko adjusted the spawn rates in Warzone.

**Comment by HackuJacku** [comment]
No response in over a month.
