### ISSUE TITLE
battle bond greninja on specific Pokémon paper

### ISSUE THREAD

**Issue by fhtghj** [SmashMC-Development/Bugs-and-Issues#1930]
when i went to get a battle bond greninja it came out with torment and not battle bond

**Comment by Paradis4432** [comment]
please explain what you mean
what server is this?

**Comment by Phoenixsans** [comment]
You can't get battle bond greninja from specific pokemon paper. The only way to obtain a bb greninja is either by fishing it up in a swamp or catching the alter one which can spawn on land during dawn/dusk in ultra jungles.
https://pixelmonmod.com/wiki/Greninja#Alter%20Ash
https://pixelmonmod.com/wiki/Ash-Greninja

**Comment by Paradis4432** [comment]
server?
