### ISSUE TITLE
pokemon wont evolve

### ISSUE THREAD

**Issue by ggestersa** [SmashMC-Development/Bugs-and-Issues#1931]
charmander reached evolution level, said something along the lines of "charmander evolved into charmander" and now it wont ask me to evolve when i level it up. reached level 36, still wont evolve into charmeleon or charizard.

i tried restarting and leveling up but it still wont evolve
**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
try /evofix
