### ISSUE TITLE
biome bug

### ISSUE THREAD

**Issue by ujsref** [SmashMC-Development/Bugs-and-Issues#1933]
it wont let me do a biome rtp

**To Reproduce**

**Servers with the Bug**
idk i tried on raquaza

it to give me the screen of brtp

**Screenshots**N/A
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
lack of context, missing requirements
