### ISSUE TITLE
Battle error

### ISSUE THREAD

**Issue by Kty4D** [SmashMC-Development/Bugs-and-Issues#1934]
**Describe the Bug**
 
This bug does not allow you to progress with the scrolls in your inventory as defeating  a wild pokemon will not count.

**To Reproduce**

1. Go fight a wild pokemon
2. Defeat the wild pokemon
3. See error in chat

**Servers with the Bug**

Kyogre

**Expected behavior**

I expect to not get a battle error after defeating a wild pokemon so I can have my scrolls progressed.

**Screenshots**

![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/170587517/1d90dfaa-1f07-4016-96fb-313deae7f975)

**Additional context**
 
N/A

**Comment by Paradis4432** [comment]
should be fixed
