### ISSUE TITLE
bugged evolution

### ISSUE THREAD

**Issue by necrowsigi** [SmashMC-Development/Bugs-and-Issues#1937]
**Describe the Bug**
when trading karrablast and shelmet the shelmet succesfully evolved yet the karrablast didnt evolve
**To Reproduce**
1. Go to trade machine
2. Click on trade shelmet and karrablast
4. See error shelmet elvoving yet karrablast not elvoving

**Servers with the Bug**
Please provide a list of which servers have this bug. groudon so far unknown for other servers

**Expected behavior**
A clear and concise description of what you expected to happen. karrablast is supposed to evolve into escavalier

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Paradis4432** [comment]
server?

**Comment by necrowsigi** [comment]
> server?

the bug is on the groudon server as far as im aware im not sure if the other servers are experiencing the same bug or no

**Comment by Paradis4432** [comment]
fixed
