### ISSUE TITLE
Pokemon not spawning

### ISSUE THREAD

**Issue by Ethanthekilla** [SmashMC-Development/Bugs-and-Issues#1938]
**Describe the Bug**
Pokemon wont spawn even after a hour of waiting while in diffrent servers on smash mc they spawn quick in like 1 minute on rayquaza it takes me and other people a hour or more.
 
**To Reproduce**

**Servers with the Bug** 
Please provide a list of which servers have this bug.
just rayquaza on smashmc
**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
we need more information than that, where were you etc
