### ISSUE TITLE
Darmanitan zen mode isnt working in warzone

### ISSUE THREAD

**Issue by cjlowndes2001** [SmashMC-Development/Bugs-and-Issues#194]
Describe the bug-
Darmanitan isnt zen moding in warzone even when lower than half

Server with the bug - 
Mew

Expected behaviour - 
Zen mode should activate when its lower than half hp on darmanitan

**Comment by Mikirae** [comment]
Honestly unsure why this wouldn't work. We don't block that form. Does it work outside of Warzone?

**Comment by HackuJacku** [comment]
Same as #299
