### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jjii-web** [SmashMC-Development/Bugs-and-Issues#1940]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jjii-web** [comment]
i put my fusion shard in the shulker box and i close when i open to get a item the fusio  shard disapeared

**Comment by Paradis4432** [comment]
please open a ticket so admins can handle this
