### ISSUE TITLE
Rowlet Evolution Bug

### ISSUE THREAD

**Issue by AsianCacti** [SmashMC-Development/Bugs-and-Issues#1941]
**Describe the Bug**
Rowlet not evolving at expected evolution levels.
**To Reproduce**
1. Go to Rowlet, Dartrix
2. Level it up to level 17, 34
3. See Rowlet, Dartrix not evolve

**Servers with the Bug**
Groudon

**Expected behavior**
I expected Rowlet to evolve into Dartrix once it hit level 17 and I also expected Dartrix to evolve at level 34

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Rowlet did not evolve at level 17, but it evolved at level 33 and did not evolve into Decidueye at level 34

**Comment by Paradis4432** [comment]
did you try /evofix?
