### ISSUE TITLE
pokemon wont pop out

### ISSUE THREAD

**Issue by Chromium2312** [SmashMC-Development/Bugs-and-Issues#1942]
i have a gardevoir that i bought and its not coming out of the ball
its full health but is refusing to come out

**Comment by Paradis4432** [comment]
do you have the R key set to something else? check settings

**Comment by Chromium2312** [comment]
> do you have the R key set to something else? check settings

no r is only set to throw pokemon out

**Comment by Paradis4432** [comment]
is it red in the settings?

**Comment by Chromium2312** [comment]
no i think its a problem with the gardevoir its self

**Comment by Paradis4432** [comment]
please open a ticket in the discord and ping me so i can help you ing.
thanks

**Comment by Chromium2312** [comment]
who are you on the discord so i can ping you

**Comment by Paradis4432** [comment]
.paradis
i have dev rank
