### ISSUE TITLE
bug breed

### ISSUE THREAD

**Issue by awes0me-m4n** [SmashMC-Development/Bugs-and-Issues#1946]
When I click the green checkmark when I'm breeding it doesn't end the breeding I often have to click dozens of times.

**Servers with the Bug**
Please provide a list of which servers have this bug.
I only play on rayquaza
**Expected behavior**
The two pokemon i breed with into my pc and my egg also into my pc
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
I cant take ss on my pc
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
sorry for the delay, if this is still an issue please open a ticket
