### ISSUE TITLE
Texture packs

### ISSUE THREAD

**Issue by Mikey68501** [SmashMC-Development/Bugs-and-Issues#1947]
**Describe the Bug**
when i type /texture in game and download from the link it doesnt work. it says the file has been corrupted or damaged. 

**To Reproduce**
1. Go to /textures
2. Click on link
3. wait for it to download and open it

**Servers with the Bug**
Kyogre possibly all

**Expected behavior**
I would like to see my anubis pokemon as well as my fusions :(

**Screenshots**
N/a

**Additional context**
 'N/A'.

**Comment by Paradis4432** [comment]
when you download the zip and place it in the resourcepack folder you dont need to unzip the file 
just leave the zip in the resource pack folder

**Comment by Mikey68501** [comment]
> when you download the zip and place it in the resourcepack folder you dont need to unzip the file just leave the zip in the resource pack folder

youre the best! i got it working

**Comment by Paradis4432** [comment]
np
