### ISSUE TITLE
Elite 4 bug possibly 

### ISSUE THREAD

**Issue by konecting** [SmashMC-Development/Bugs-and-Issues#1948]
**Describe the Bug**
i have beaten all the gyms last being electric so now i can face the elite 4 and the first gym being "iron dragon"  but when i go to challenge that gym i get a message saying i need to beat the 4th/torch one before i can challenge the iron dragon. so when i go look at the torch it says i have to beat the 3 before it first being the iron dragon. so im not sure if i am missing something before i can challenge the gym or if this is an issue. 
**To Reproduce**
1. Go to '...' /gyms 
2. Click on '....' elite 4 
3. Scroll down to '....' iron dragon

**Servers with the Bug**
Please provide a list of which servers have this bug.
groudon that i know of (the one im on )
**Expected behavior**
to challenge the first Elite 4 
**Screenshots**
If applicable, 
![E4 issue ](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/174390334/6d32db00-2603-43c8-bde6-660fc8e771ee)
add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by Paradis4432** [comment]
noted, working on it
