### ISSUE TITLE
ghost gym

### ISSUE THREAD

**Issue by Kic0513** [SmashMC-Development/Bugs-and-Issues#1949]
**Describe the Bug**
i would start the ghost gym and then i would use shadow force on their pokemon then would kick me out of the battle and i tried to wait another 3 hours to start the fight again and the same problem happend but this time in chat report this error if needed

**To Reproduce**
1. Go to 'gyms'
2. Click on 'ghost gym'
3. Scroll down to start the battle'

**Comment by Paradis4432** [comment]
server?
