### ISSUE TITLE
Bugged warzone spawns

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Bugs-and-Issues#195]
**Describe the Bug**
On charizards warzone only pokemon from th biome are spawning not the regular pokemon that normally spawned in warzone

**To Reproduce**
1. Go to charizards warzone
2. sit there for a while
3. see the bugged spawns

**Servers with the Bug**
Charizard

**Expected behavior**
pokemon from the entire pokedex should be spawning

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Unsure what the issue was here but I'm here right now and all of them are spawning as normal :)
