### ISSUE TITLE
rtp bug

### ISSUE THREAD

**Issue by sebellow** [SmashMC-Development/Bugs-and-Issues#1950]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by sebellow** [comment]
hello everytime i try to rtp it says that im already teleporting ( wich im not) i currently only know that the zacian server has this bug  . it would be nice ifthis bug would be fixed asap   N/A pictures. N/A additional context

**Comment by Paradis4432** [comment]
this is an issue that fixes itself on restart, we are working on proper fix
