### ISSUE TITLE
when i do /craft and when i click something like a sign for expeple it dosnt craft even when i use the crafting table

### ISSUE THREAD

**Issue by Shoto68** [SmashMC-Development/Bugs-and-Issues#1951]
![2024-07-09_23 47 14](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/175157154/4e962b1b-0c73-4f34-9987-7eab8725532a)
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
not a bug
