### ISSUE TITLE
When fighting steel gym I do one move and it immediately kicks me up. /Gmys click on steel gyms fight steel gym one move and it crashes Kyogre server

### ISSUE THREAD

**Issue by bballerz23** [SmashMC-Development/Bugs-and-Issues#1952]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Emildadib** [comment]
almost the same thing happened to me but on the groudon server and it was the electric gym

**Comment by Paradis4432** [comment]
we are working on this
