### ISSUE TITLE
vote

### ISSUE THREAD

**Issue by TrippyJordyn1** [SmashMC-Development/Bugs-and-Issues#1955]
**Describe the Bug**
I voted today and it didn't give me my rewards or keys

**Servers with the Bug**
groudon is the server I'm in

**Expected behavior**
I was hoping to get my crate keys.
**Screenshots**
![Screenshot_16-7-2024_12449_minecraft-mp com](https://github.com/user-attachments/assets/b0f3028c-5515-47f8-9863-89148649e32a)

**Comment by Paradis4432** [comment]
this is an issue we are facing on certain ips, please open a ticket in the discord server for proper support
