### ISSUE TITLE
hidden abilities not showing  on pokemon/ transferring  over when breeding 

### ISSUE THREAD

**Issue by kingslamzz** [SmashMC-Development/Bugs-and-Issues#1956]
I caught a hidden ability muk which has the ability "poison touch". when I caught it, the announcement did not pop up in chat nor did it even say it was an hidden ability Pokémon, but on the wiki and google it can be clarified that "poison touch is the hidden ability so nor does my muk even have the hidden ability symbol when breeding its as if it doesn't even have the hidden ability because it never transfers PLEASE FIX THIS IT IS DEEPLY AFFECTING MY WZ TEAM

**Comment by Paradis4432** [comment]
please open a ticket for better support
