### ISSUE TITLE
items not holding. When i switch itemor try to drop them from my inventory, they dont drop. i cant use the "Random Pokemon" because of this issue

### ISSUE THREAD

**Issue by fafkoo0077** [SmashMC-Development/Bugs-and-Issues#1959]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
not enought context
