### ISSUE TITLE
Gmax pokemon always

### ISSUE THREAD

**Issue by Mizugorou49** [SmashMC-Development/Bugs-and-Issues#196]
**Describe the Bug**
When you catch a pokemon that has the ability to gmax, it will always have the gmax factor on it

**To Reproduce**
1. find a mon that can gmax in wild
2. catch the mon
3. Gmax factor is on it

**Servers with the Bug**
Giratina, Dialga and possibly the others

**Expected behavior**
The pokemon should not be able to gmax when freshly caught

**Screenshots**
N/A

**Comment by Mikirae** [comment]
This is a Pixelmon bug and we can't fix it unfortunately :(
