### ISSUE TITLE
vote

### ISSUE THREAD

**Issue by LuckyBlock208** [SmashMC-Development/Bugs-and-Issues#1960]
is the vote system being down or somthing i vote for this site https://minecraftservers.org/vote/548790 so many time now no reward and in the votegui it the last section it said 5 days but in the next section it say i am able to vote but i already vote the server pla fix the issue pls
![z5655885606605_6ef4d46c1871469df916f5f6dc13ef9e](https://github.com/user-attachments/assets/cea5ecf4-1725-424b-aa57-a6918d7542df)
![z5655885606605_6ef4d46c1871469df916f5f6dc13ef9e](https://github.com/user-attachments/assets/6a697b8d-8662-4bc8-8bce-113e49c7a9a3)

**Comment by Paradis4432** [comment]
should be fixed
