### ISSUE TITLE
Shiny Triple Choice

### ISSUE THREAD

**Issue by Patrick-CodeX** [SmashMC-Development/Bugs-and-Issues#1961]
**Describe the Bug**
When I right click, nothing happens. 
**To Reproduce**
No idea

**Servers with the Bug**
Rayquaza

**Expected behavior**
Suppose to let me choose 3 shinnies. 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
not enough context, cant replicate
