### ISSUE TITLE
Pixelmon Anvil Crafting does not work!

### ISSUE THREAD

**Issue by Patrick-CodeX** [SmashMC-Development/Bugs-and-Issues#1962]
**Describe the Bug**
I go into the crafting table, put 8 iron ingots, left the middle right slot empty, and for some reason it does make the anvil. 

**To Reproduce**
No Idea

**Servers with the Bug**
Rayquaza

**Expected behavior**
To make an anvil. 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
not a bug
