### ISSUE TITLE
No Pokemon spawned when Lucky Block broke

### ISSUE THREAD

**Issue by thequirkyquokka** [SmashMC-Development/Bugs-and-Issues#1965]
**Describe the Bug**
Opened a Lucky Block and no Pokemon spawned. Chat said that a shiny hakamo-o spawned but one did not.

**To Reproduce**
1. Left click on lucky block
2. Block disappears, comment appears in chat, but no Pokemon spawned

**Servers with the Bug**
SmashMC

**Expected behavior**
Expected to see a shiny hakamo-o appear :) 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Paradis4432** [comment]
we will look into this
