### ISSUE TITLE
i cant use the /rewardclaim comand!

### ISSUE THREAD

**Issue by mille591** [SmashMC-Development/Bugs-and-Issues#1967]
**Describe the Bug**
i cant use the /rewardclaim comand it just says comand not found or incomplete comand  and i dont know why. Do you know why or how to fix it?

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
please use the github for technical issues, for the rest open a ticket for helper's support
