### ISSUE TITLE
my map aint showing the pokemon

### ISSUE THREAD

**Issue by FIREbl0de02** [SmashMC-Development/Bugs-and-Issues#1969]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by FIREbl0de02** [comment]
my map got big into a rectangle and then the pokemon dissopeard

**Comment by FIREbl0de02** [comment]
the pokemon on the map is just arrows

**Comment by Paradis4432** [comment]
i have no clue what you are talking about, fill the requested information, its there for a reason
