### ISSUE TITLE
Rustsd Sword/shield

### ISSUE THREAD

**Issue by Firemelon66** [SmashMC-Development/Bugs-and-Issues#197]
I just wanted to ask if its a bug that zacian and zamazenta doesnt have their sword/shield as held item in wz or if its planned that way cause if not i would wish to put the items pls in the mart like the dns splicer and also the item to fuse calyrex cause the spawnrates of that mons are really low. Or could you make the spawnrates higher of legends or the times shorter from the spawns

**Comment by Mikirae** [comment]
This is more of a suggestion than a bug. Please make a suggestion post on our GitHub :)
