### ISSUE TITLE
pokemon kangaskahn wont let me take out of party and put it in the box

### ISSUE THREAD

**Issue by FIREbl0de02** [SmashMC-Development/Bugs-and-Issues#1973]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
not enough context
