### ISSUE TITLE
False HA Indicator on GTS

### ISSUE THREAD

**Issue by Slaaaine** [SmashMC-Development/Bugs-and-Issues#1974]
**Describe the Bug**
False HA indicator for Lapras on gts. Lapras's ability Water Absorb isn't the HA of it but on the GTS, Water Absorb is indicated as the HA. This also shows for checking the lapras on the choosing gui of the gts for selling pokes. 

**To Reproduce**
1. Go to 'GTS'
2. Click on 'Sell Pokemon'

**Servers with the Bug**
Groudon is the server i found this on

**Expected behavior**
Its not its HA so I expect the HA indicator to not be displayed for water absorb.

**Screenshots**
![image](https://github.com/user-attachments/assets/55a051d6-10b1-46b8-a586-b9107f8713b5)

**Additional context**
N/A

**Comment by Paradis4432** [comment]
uh will look into it thanks

**Comment by Slaaaine** [comment]
recently found out about a swift swim omastar as well shown as HA
