### ISSUE TITLE
Store and daycare bug

### ISSUE THREAD

**Issue by Ch7arly** [SmashMC-Development/Bugs-and-Issues#1977]
i cant buy on /store when i click on the item nothing happens and in the daycare the bottons do not appear

**To Reproduce**
1. Go to /store
2. Click on any item
3. Scroll down to nothing
4. See error bug any crafting

**Servers with the Bug**
groudon

**Expected behavior**
buy

**Screenshots**
N/A

**Additional context**
When o try to buy mycraft table bugs to and i cant craft anything

**Comment by Paradis4432** [comment]
not enough information
