### ISSUE TITLE
MissingNo

### ISSUE THREAD

**Issue by Rykard17** [SmashMC-Development/Bugs-and-Issues#1978]
**Describe the Bug**

**To Reproduce**
1. Go to Pc
2. Click on Yungoos
3. Swapped on team
4. MissingNo 

**Servers with the Bug**
Arceus

**Expected behavior**
I swapped a Pokemon from the PC, but "MissingNo" appeared and now I cant delete, release or trade. Help please, username: Rykard17, server Arceus. 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![Captura de pantalla 2024-09-30 045540](https://github.com/user-attachments/assets/20e8b4a6-bb6e-4316-b0e7-89ca37a92686)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
wait for server restart, nothing we can do to fix
