### ISSUE TITLE
a

### ISSUE THREAD

**Issue by LuckyMonkey7745** [SmashMC-Development/Bugs-and-Issues#1979]
**Describe the Bug**
I bought a few TMs from /warp moves, to put on my basculegion, but it said basculegion could not learn those moves. I was able to put those exact ones on the same basculegion when i did /buymove.

**To Reproduce**
1. Go to '/warp moves'
2. Click on 'the TM sellers'
3. Scroll down to 'ex. Ice Beam'
4. give to basculegion
5. it will not equip.

**Servers with the Bug**
Please provide a list of which servers have this bug.
ive only tried on the Kyogre server

**Expected behavior**
The moves will not equip via TM but will via /buymoves.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
Cant add screenshot currently

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by Paradis4432** [comment]
i believe this was fixed
