### ISSUE TITLE
Weakness Policy Bug

### ISSUE THREAD

**Issue by MFlorizzle** [SmashMC-Development/Bugs-and-Issues#1980]
**Describe the Bug**
I was in a random battle tournament and I used scald (water type) on a metagross holding the Weakness Policy item. Scald resulted in a 30% burn chance to proc. At the end of the turn the metagross was hurt by the burn and it caused it to proc the weakness policy. This shouldn't happen but the game treats it as a fire type move evidently. 

**To Reproduce**
1. Enter a battle with a water type that learns scald against a pokemon not weak to water type moves. Ensure the opposing mon is holding weakness policy.
2. Click scald until a burn occurs.
3. Notice the opposing mon obtains +2 in attack and sp. attack

**Servers with the Bug**
Kyogre

**Expected behavior**
The weakness policy should not proc

**Screenshots**
NA

**Additional context**
NA

**Comment by Paradis4432** [comment]
we have reported this to the pixelmon team but unfortunately we cant fix it
