### ISSUE TITLE
not getting shiny from linking

### ISSUE THREAD

**Issue by ewasdsarfas2w** [SmashMC-Development/Bugs-and-Issues#1981]
**Describe the Bug**
Not getting the shiny after you link and not getting the /kit discord

**To Reproduce**
1. Go to discord
2. click on the Linking channel
3. type the code from Minecraft
4. go to Minecraft and not get the kit or the shiny

**Servers with the Bug**
Groudon

**Expected behavior**
the shiny appearing in my not-full party

**Screenshots**
N/A
**Additional context**
N/A

**Comment by Paradis4432** [comment]
i believe this was fixed, for ing support open a ticket
