### ISSUE TITLE
MissingNo

### ISSUE THREAD

**Issue by Kingdra184** [SmashMC-Development/Bugs-and-Issues#1983]
![2024-11-11_00 51 19](https://github.com/user-attachments/assets/95aeecec-8a4b-43f8-918b-68897abc71a9)
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
wait for server restart , nothing we can do
