### ISSUE TITLE
warzone

### ISSUE THREAD

**Issue by MagnusVR5775** [SmashMC-Development/Bugs-and-Issues#1985]
**Describe the Bug**
so i was in the warzone and a lengdary brid spawned and when presst R to get in battle i cuntent troh my pokeball so i dident catch it
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug. it was on the raqarzer sever

**Expected behavior**
A clear and concise description of what you expected to happen. i wuld like to get a lengadry or som monney because that brid cut have given me a lot off monney

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
not enough information
