### ISSUE TITLE
Smash MC menu under party

### ISSUE THREAD

**Issue by Dan-Pallone-II** [SmashMC-Development/Bugs-and-Issues#1986]
**Describe the Bug**
I'm not sure if this is a bug or a change in behavior, but I'd like to report it and know what happened and if possible, have it fixed.
**To Reproduce**
1. Go to ' I have an item in my inventory called Smash MC menu I put it in the last slot Number 9 and I activate it It brings up a menu One of the items in the menu is called party stats'
2. Click on ' Party stats and then I review the Mon in my inventory'
3. The previous behavior. would show all the stats for all of my Pokemon and eggs. currently it seems very random. if it's not showing stats, it just gives the name of the man and the level If this was intended, I apologize. if this is now an option that needs to be turned on to show the previous stats, please let me know where to go. if this is a bug and it is broken please restore it to its original use.

As a workaround. I use the command line./sts And review my Pokemon.

**Servers with the Bug**
I only use one server and that's Grodon

My username is.: miazma1

**Comment by Paradis4432** [comment]
we are gonna look into it thank you
