### ISSUE TITLE
I got MissingNo on my team and can't get rid of it

### ISSUE THREAD

**Issue by Exverer** [SmashMC-Development/Bugs-and-Issues#1988]
**Describe the Bug**
i casually try to organize my pc and suddenly missingNo just appear on my party out of nowhere and i can't get rid of it in anyway(i try to put it in pc and release it but it still cameback to my party)

**To Reproduce**
1. I open my pc
2. organize my pc
3. missingNo appear

**Servers with the Bug**
Zacian Server

**Expected behavior**
i just want it fix or get rid of this missingNo for me

**Screenshots**
![สกรีนช็อต 2024-12-05 154120](https://github.com/user-attachments/assets/6fc30698-12c4-47e2-9153-7989419d4bf4)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
missing no is an issue on pixelmon and theres nothing we can do to fix it atm
