### ISSUE TITLE
After the missingNo

### ISSUE THREAD

**Issue by Exverer** [SmashMC-Development/Bugs-and-Issues#1989]
**Describe the Bug**
Now that i caught a new pokemon it appear on party instead of missingNo but i still can't get rid of it

**To Reproduce**
1. Caught a pokemon
2. appear on party instead of MissingNo
3. try to get or it
4. won't be able to get rid of it
**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**
just fix the entire thing please

**Screenshots**
![Uploading สกรีนช็อต 2024-12-05 154808.png…]()

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
missing no is an issue on pixelmon and theres nothing we can do to fix it atm
