### ISSUE TITLE
Too many Flying spawns in warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#199]
**Describe the Bug**
Loads of pokemon are spawning in the air in warzone.
**To Reproduce**
1. Go to warzone on darkrai
2. Have a few people (around 5) in there
3. Look in the air and see loads of flying pokemon

**Servers with the Bug**
Known Server = Darkrai

**Expected behavior**
Not have loads of flying pokemon in the sky.

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/119575536-20abf980-bdaf-11eb-8b46-3213cc9792d3.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
I don't believe it's currently possible for us to adjust the total amount of flying Pokemon per world. This has been an issue with Pixelmon for a while now I believe.

**Comment by Mikirae** [comment]
I unfortunately don't believe that there's anything that can be done about this one. Perhaps an additional spec for the Warzone rewrite? :)
