### ISSUE TITLE
Item disappearing

### ISSUE THREAD

**Issue by Froyosmile** [SmashMC-Development/Bugs-and-Issues#1990]
when i was buiilding a redstone thing the amythist i set down and the sticky pistons just got deleted as i placed it, i bought both from the shop so that may have somethinbg to do with it but im not sure:c

**Comment by Froyosmile** [comment]
some how they reapeared in my invetory after a while i was writing 0_0

**Comment by Froyosmile** [comment]
they still disapeared:(

**Comment by Froyosmile** [comment]
imsorry i just crashed sorry:( it works now

**Comment by Paradis4432** [comment]
re send a message here if it happens again
