### ISSUE TITLE
Pokeball Change Paper Issue

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#1992]
**Describe the Bug**
Premier Balls are missing within the **Pokeball change papers** (both leg and nonleg) if the pokemon was caught with a Repeat Ball.
Furthermore, depending on what ball the pokemon is currently in, some other balls are missing within the GUI.

**To Reproduce**
1. Catch any Pokemon with a repeat ball
2. Try to use the paper on it
3. Check for missing balls
4. Repeat the steps 1-3 with a quick ball
5. Balls are missing

**Servers with the Bug**
All smashmc Realms.

**Expected behavior**
Pokeball change paper showing all the balls in the GUI.

**Screenshots**
Screenshots of the GUI. The ball used to catch is highlighted within the screenshot.
![2024-12-29_23 50 47](https://github.com/user-attachments/assets/b4e83476-a4ec-4e89-bf05-b7edb4ba670a)

**Additional context**
Maybe the newly added secret balls prevent this from happening due to missing space within the GUI.

**Comment by DinglePringleUwU** [comment]
Addendum: Here is a screenshot with the newest texture pack v.27 with the same issue.
![2024-12-30_01 08 52](https://github.com/user-attachments/assets/ace1dd35-35d6-4834-bfe6-38832bba83f7)

**Comment by Paradis4432** [comment]
we are gonna look into it, thank you
