### ISSUE TITLE
deleting grass in spawn

### ISSUE THREAD

**Issue by covertcc** [SmashMC-Development/Bugs-and-Issues#1993]
**i was messing around in spawn with a chair and then boom a lot of grass got deleted and it scared me super bad then i tried it again and it worked again basically it deletes grass and maybe more**

**To Reproduce**
1.'from what i know you need a chair and what you are going to do is place it over and over inside a grass'
2. 'then when it disappears from your hand walk away and place it in another grass'
3. 'now it should get ride of a lot of grass if it doesnt work the first time try again till it does'

**Servers with the Bug**
so far i only know groudon has it.

**Screenshots**
N/A 

**Additional context**
N/A 'sorry this is my first time reporting a bug i hope you understand i didnt mean to break the grass at spawn'

**Comment by covertcc** [comment]
if you want to see what i mean you can join groudon as im in it right now

**Comment by Paradis4432** [comment]
thats fine its just grass
