### ISSUE TITLE
Missing items in EV training area on Giratina

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#2]
**Describe the Bug**
 Power anklet is missing from EV training area on Giratina
**To Reproduce**
See proof

**Servers with the Bug**
Giratina

**Expected behavior**
place new frame and anklet and see who broke it

**Screenshots**
https://gyazo.com/eb86073d8122f852d4c8a2e8e8cb7e08

**Additional context**
none

**Comment by HackuJacku** [comment]
Fixed - players are also not able to place bikes in admin claims.
