### ISSUE TITLE
GD is blocking players sitting on Pixelmon chairs

### ISSUE THREAD

**Issue by HackuJacku** [SmashMC-Development/Bugs-and-Issues#20]
**Describe the Bug**
You can't sit on the chairs in /warp musicalchairs due to the admin claim not allowing it

**To Reproduce**
1. Go to /warp musicalchairs and try to sit in a chair.

**Servers with the Bug**
Darkrai, Dialga and Mew.

**Expected behavior**
The admin claim should allow you to sit on a chair

**Comment by Mikirae** [comment]
Pretty sure this got fixed yeah?

**Comment by Rasgnarok** [comment]
No, it's fixed now though.
