### ISSUE TITLE
no keys when voting 

### ISSUE THREAD

**Issue by boopchan** [SmashMC-Development/Bugs-and-Issues#200]
**Describe the Bug**
dont get my vote keys when i vote 

**To Reproduce**
1. log onto the server
2. do /vote and vote all 5 times
3. get back onto the game and do /keys
4. there are no keys 

**Servers with the Bug**
charizard

**Expected behavior**
i would get my vote keys in like 5 mins after voting

**Screenshots**
N/A

**Additional context**
refer to ticket 23358

**Comment by HackuJacku** [comment]
Same as #202 - please create a ticket for your keys
