### ISSUE TITLE
No keys when voting

### ISSUE THREAD

**Issue by RedFoz** [SmashMC-Development/Bugs-and-Issues#201]
**Describe the Bug**
Dont get the keys after voting

**To Reproduce**
1. log onto the server
2. do /vote and vote all 5 times
3. get back onto the game and do /keys
4. there are no keys

**Servers with the Bug**
Charizard

**Expected behavior**
i would get my vote keys in like 5 mins after voting

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Same as #202 - please create a ticket for your keys
