### ISSUE TITLE
Primal Groudon Doesn't Work In Warzone

### ISSUE THREAD

**Issue by NotSplushy** [SmashMC-Development/Bugs-and-Issues#203]
**Describe the Bug**
I have red orb on my groudon but when I attack someone in warzone it doesn't change to primal. It only works outside of warzone.

**To Reproduce**

**Servers with the Bug**
Jirachi and I don't know about any other servers

**Expected behavior**
My Groudon to turn into primal during battle.

**Screenshots**
https://prnt.sc/13g156s 

**Additional context**
Made a ticket already and a helper tested it with me. Works outside of wz but when I went in wz it didn't work.

**Comment by HackuJacku** [comment]
@NotSplushy - please fill the format out (reproducing the issue is the most important part).

**Comment by Unitzero007** [comment]
I think this is more of a pixelmon issue, the Primal Transformations are cancelled out by the Dynamax Band, so if your opponent is dmaxing your primal orbs are useless.

**Comment by Mikirae** [comment]
> I think this is more of a pixelmon issue, the Primal Transformations are cancelled out by the Dynamax Band, so if your opponent is dmaxing your primal orbs are useless.

Is this if they have the Dynamax band at all? Or simply use it during the battle?

**Comment by NotSplushy** [comment]
Just Dynamax. Mega band works

**Comment by Mikirae** [comment]
Yeah this unfortunately seems like a Pixelmon thing that we really won't be able to do anything about :(
