### ISSUE TITLE
command allowing players to safeplace while moving in warzone

### ISSUE THREAD

**Issue by Blxgdenn** [SmashMC-Development/Bugs-and-Issues#204]
**Describe the Bug**
if you type /reg then tab it brings up a command that allows players to safeplace in warzone while moving

type /reg in warzone

**Servers with the Bug**
All servers

**Expected behavior**
shouldn't be able to safeplace while moving

![image](https://user-images.githubusercontent.com/83072886/119688466-e9395d80-be3f-11eb-81b2-1106c496dd3a.png)

this is the full command

https://user-images.githubusercontent.com/83072886/119692893-b5f8cd80-be43-11eb-9b88-295968ba4909.mp4

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Looks to be a permission issue. I can take a look at this tomorrow. :)

**Comment by HackuJacku** [comment]
@Mikirae - Warzone (RegionalPokémonStealy) handles `/safeplace`, it has for a couple of versions - it's an issue with the code itself. This will be addressed in the Warzone re-write.

**Comment by HackuJacku** [comment]
We're started developed of the next version of Warzone, this issue will be fixed in the new version being worked on. We won't be fixing the current Warzone plugin due to it having too many issues and not being worthwhile in comparison.
