### ISSUE TITLE
Boss Tower In Hiding

### ISSUE THREAD

**Issue by LittleBunnyFuuFuu** [SmashMC-Development/Bugs-and-Issues#205]
**Describe the Bug**
The warps to boss tower currently don't work.

**To Reproduce**
1. type  /warp bosstower
2. "Could not warp to a safe location nearby. To force a warp, us ethe "-f" flag"

**Servers with the Bug**
Jirachi

**Expected behavior**
Be warped to boss tower.

**Screenshots**
 'N/A'.

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
Fixed.
