### ISSUE TITLE
Eeveelutions not being able to learn the move "celebrate"

### ISSUE THREAD

**Issue by Ryan1595** [SmashMC-Development/Bugs-and-Issues#206]
**Describe the Bug**
Eeveelutions cannot learn celebrate from the move tutor or /buymoves
**To Reproduce**
1. Go to mart and try to learn the move, it says "Cannot learn"
2. /buymoves with a glacion, and it will not show up

**Servers with the Bug**
Only tested on Jirachi
**Expected behavior**
Eeveelutions should learn Celebrate

**Screenshots**
N/A

**Additional context**
On the wiki it says that it is a "tournament move" or an "event move"

**Comment by Mikirae** [comment]
This isn't a bug. Only Eevee learns Celebrate.
https://bulbapedia.bulbagarden.net/wiki/Glaceon_(Pok%C3%A9mon)
