### ISSUE TITLE
/fly bug

### ISSUE THREAD

**Issue by Ryan1595** [SmashMC-Development/Bugs-and-Issues#208]
**Describe the Bug**
When you fly using an elytra while the /fly command is active, you take collision damage.

**To Reproduce**
1. /fly
2. fly high 
3. fall and activate elytra
4. hit the ground and take damage

**Servers with the Bug**
Only tested on Jirachi

**Expected behavior**
No damage should be taken, as without /fly you don't take damage

**Screenshots**
N/A

**Additional context**
This was tested in spawn

**Comment by HackuJacku** [comment]
@Rasgnarok - any ideas about how this could be fixed please? Would it be a GD thing?

**Comment by HackuJacku** [comment]
After looking into, this is not a bug. It's a feature. Flying too high in Ultra Space will damage the player.
