### ISSUE TITLE
Fall damage bug in Rayquaza

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#209]
**Describe the Bug** 
Fall damage is enabled in the wold in Rayquaza (/rtp )

**To Reproduce**
1. /rtp to somewhere random
2. fall and take damage

**Servers with the Bug**
Rayquaza

**Expected behavior**
no fall damage like other servers

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
@Shoji007 when you right click with a stick on the area where you're able to take fall damage, that's the chat message you receive please?

**Comment by Shoji007** [comment]
https://gyazo.com/c8746630e4c487c24e1c3f824e4f7d81 @HackuJacku

**Comment by HackuJacku** [comment]
After talking about this, this is not a bug. It's a feature. Fall damage is suppose to be enabled in non-claimed areas such as these.
