### ISSUE TITLE
People able to 1 shot raid bosses/do ridiculous amounts of damage when coming late to the raid

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#21]
**Describe the Bug**
People being able to 1 shot raid bosses.
**To Reproduce**
Known suspected moves:
Punishment/Judgement on Arceus, 
Zap Cannon on who ever can use it.
**Servers with the Bug**
All

**Expected behavior**
Disable Punishment on Arceus during raid battles

**Screenshots**
https://cdn.discordapp.com/attachments/832763594298621952/832763684152672257/Screenshot_327.png

**Additional context**

**Comment by HackuJacku** [comment]
Which Pokémon was this against please? Need to know information like that.

**Comment by Unitzero007** [comment]
> Which Pokémon was this against please? Need to know information like that.

In the screenshot shoji sent it was Medicham.
I know what happened lol, the Mega Medicham simply missed a High Jump Kick and killed itself, its not the fault of the Player's pokemon. Also, if you just press protect vs mega medicham when it does a High Jump Kick it will automatically crash down and fall and lose half of its hp.

**Comment by HackuJacku** [comment]
We're replacing all the Raid Bosses. If this is an issue with the new bosses, please create a new report; providing information such as the moves used by the boss, the (Pokémon) boss, ETC.
