### ISSUE TITLE
Warzone /Safeplace bug

### ISSUE THREAD

**Issue by Dnesh3126** [SmashMC-Development/Bugs-and-Issues#210]
**Describe the Bug**
If you do /safeplace in warzone, then move(so that it cancelled the Teleport) as long as you type /safeplace before initial 5 second timer is up you will be immediately Teleported out. 

**To Reproduce**
1. Go to 'Mew warzone' 
2. Click on '/safeplace'
3. Scroll down to 'Do what I said in the description '

**Servers with the Bug**
All- assuming that all of them use the same /safeplace mechanic 

**Expected behavior**
Get Teleported out easier and can make it impossible for people to fight you in warzone as you will be able to get out of warzone before they attack you

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Addressed in the up-coming Warzone re-write.
