### ISSUE TITLE
/hunt not working on the Rayquaza Server

### ISSUE THREAD

**Issue by Unitzero007** [SmashMC-Development/Bugs-and-Issues#211]
**Describe the Bug**
The command /hunt is not working on Rayquaza Server, both the command /hunt, and the reminder in chat that asks you to check out /hunt.

**To Reproduce**
1. Go to the Rayquaza Server on smashmc
2. Type /hunt
3. You will get an error that says that the command does not exist. or "Unknown Command"

**Servers with the Bug**
Only Tested in Rayquaza and Palkia.
It woks on Palkia, but not Rayquaza

**Expected behavior**
/hunt should bring you to a menu of huntable pokemon
A reminder in chat should exist that, every so often, reminds people to check out /hunt

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Hunts are disabled temporary as they're causing the server to crash or not boot from time to time.
