### ISSUE TITLE
Tourneys dont start

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Bugs-and-Issues#212]
**Describe the Bug**
Tourneys wont start automatically and have to be manually started

**To Reproduce**
1. Go to any server
2. wait for another tourney

**Servers with the Bug**
All pixelmon servers

**Expected behavior**
Tourneys should start automatically every three hours

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
This should be fixed on Rayquaza from now. I have trigger a manual tournament so the next one should occur in 3 hours.

**Comment by Mikirae** [comment]
I'll be uploading another fixed global.conf to the servers that will fix this issue. The issue before is that sponge overwrote itself on account of it's terrible.

**Comment by HackuJacku** [comment]
Fixed from the next reboot.
