### ISSUE TITLE
SmashTrivia on jirachi, wrong color and name

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#214]
**Describe the Bug**
SmashTriva on jirachi it's called just "Trivia" and with the wrong colors too

**To Reproduce**
1. Go to /server jirachi
2. Wait for the trivia
3. See error

**Servers with the Bug**
Jirachi

**Expected behavior**
Should be as all the other servers

**Screenshots**
Trivia on Jirachi
![trivj](https://user-images.githubusercontent.com/83550357/119876390-237e2a00-bf28-11eb-8714-737294125d9d.png)
SmashTrivia on another random server
![trivm](https://user-images.githubusercontent.com/83550357/119876449-32fd7300-bf28-11eb-8f1c-3c4fa92735cf.png)

**Comment by HackuJacku** [comment]
Same as #163
