### ISSUE TITLE
GTS not working

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#217]
**Describe the Bug**
When trying to list something, pokemon or item on the gts, it doesn't work. Also doesn't work when trying to take off something.

**To Reproduce**
1. Go to /server darkrai
2. Type /gts
3. Try to add anything

**Servers with the Bug**
Darkrai

**Expected behavior**
Players should be able to list / take off things on gts

**Screenshots**
![2021-05-28_00 42 54](https://user-images.githubusercontent.com/83550357/119906172-00ff0780-bf4e-11eb-901e-7e7ed7efc982.png)
![2021-05-28_00 42 57](https://user-images.githubusercontent.com/83550357/119906193-09efd900-bf4e-11eb-9488-3d57b2d09cf5.png)

It will just say "processing your request"

**Comment by Mikirae** [comment]
Is this issue still occurring?

**Comment by Superfire96** [comment]
Yes it is

**Comment by HackuJacku** [comment]
Fixed.
