### ISSUE TITLE
receiving incorrect crate item

### ISSUE THREAD

**Issue by IronGolem19** [SmashMC-Development/Bugs-and-Issues#219]
**Describe the Bug**
when you receive a random legendary 1v boost its gives you a +10 legendary iv boost
**To Reproduce**
1. Go to legendary crate
2. receive random legendary iv boost
3. given a +10 boost instead

**Servers with the Bug**
Please provide a list of which servers have this bug.
possible on all servers only confirmed on rayquaza
**Expected behavior**
expected to receive the correct crate item
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
@IronGolem19 - is this still occurring please? @Mikirae tells me it should be fixed. Can you also provide a screenshot of what exactly it says in chat please?

**Comment by IronGolem19** [comment]
so i checked everywhere i could not find a screenshot of it saying it. And the issue has been fixed.
