### ISSUE TITLE
primal groudon and kyogre wont work

### ISSUE THREAD

**Issue by unfiltxred** [SmashMC-Development/Bugs-and-Issues#220]
When i try to primal my groudon/kyogre when i engage something with the respective orbs equipped it just doesnt primal and remains a normal kyogre/groudon.

**To Reproduce**
put an orb on a groudon/kyogre
engage something
it wont work

**Servers with the Bug**
ive only tried on dialga cuz i only play on there

**Expected behavior**
i expected it to revert to primal form like it used to

**Screenshots**
n/a

**Additional context**
n/a

**Comment by HackuJacku** [comment]
Same as #203
