### ISSUE TITLE
/Birthday not working

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#221]
**Describe the Bug**
When a player run the command /birthday it will say that the player hasn't the permission to use that command.

**To Reproduce**
1. Go to /server Deoxys
2. Write /birthday
3. See error

**Servers with the Bug**
Deoxys

**Expected behavior**
Players should be able to set their Birthday

**Screenshots**
![2021-05-28_16 03 38](https://user-images.githubusercontent.com/83550357/119996404-03ee0c80-bfcf-11eb-85cb-8b587ab1081b.png)
![fwafa](https://user-images.githubusercontent.com/83550357/119996519-22540800-bfcf-11eb-9507-d7f8ba395203.png)

**Comment by HackuJacku** [comment]
Fixed.
