### ISSUE TITLE
The, once again, Illusive Boss tower

### ISSUE THREAD

**Issue by LittleBunnyFuuFuu** [SmashMC-Development/Bugs-and-Issues#222]
**Describe the Bug**
Unable to warp to boss tower

**To Reproduce**
1. type ./warp boss tower
2. get hit with the big NOPE

**Servers with the Bug**
Jirachi

**Expected behavior**
To be warped to boss tower.

**Screenshots**
'N/A'.

**Additional context**
 'N/A'.

**Comment by HackuJacku** [comment]
Although I know what you mean, please state exactly what the issue is in the future. Fixed now.
