### ISSUE TITLE
Auto Glow not working on Mew

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#223]
**Describe the Bug**
Auto glow not working in mew warzone.

**To Reproduce**
1. Go to mew warzone with no glow.
2. Once your in warzone open your inventory and once the time reaches 0 you will have no glow

**Servers with the Bug**
Mew
**Expected behavior**
You should have your glow on automatically and it should stay on.

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/120008651-12d6be00-bfd3-11eb-81ff-711eb9f7048f.png)

**Additional context**
In the image you can see me and the guy on the middle left dont have glows. Everyone else who has a glow from /dex claim keeps their glow on

**Comment by HackuJacku** [comment]
Addressed in the Warzone rewrite. This is an issue with glows in general, there is little we can do.
