### ISSUE TITLE
Fire spread on

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Bugs-and-Issues#224]
**Describe the Bug**
Fire spread is on in dialga

**To Reproduce**
1. light a flamable block on fire
2. put other flamable blocks near the fire
3. See the fire spreading

**Servers with the Bug**
only tested on dialga

**Expected behavior**
Fire spread should be off

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
@DiegoKek - this is per world. Please can you provide me with the world you're in and how exactly you got to it. E.G: there are multiple overworlds.

**Comment by DiegoKek** [comment]
how do i do that?

**Comment by HackuJacku** [comment]
Are you in Ultra Space? Did you do `/rtp`? ETC

**Comment by DiegoKek** [comment]
i tped to a player, but then rtp'd and it also worked

**Comment by Mikirae** [comment]
This has been fixed :)
