### ISSUE TITLE
sts values are lower

### ISSUE THREAD

**Issue by Jumbleds** [SmashMC-Development/Bugs-and-Issues#226]
**Describe the Bug**
When I went into Jirachi, I looked at the sts price for legends and they were alot lower than other servers (e.g Darkrai)

**To Reproduce**
1. Go to Jirachi Server
2. Type /sts
3. Hover over a legendary and see sts price
4. Go to another server (e.g Darkrai) and hover over a legendary there and check its sts price

**Servers with the Bug**
Jirachi, and possibly other servers but I haven't checked.

**Expected behavior**
Jirachi's sts prices should be the same as every other server.

**Screenshots**
![2021-05-28_12 58 33](https://user-images.githubusercontent.com/84808660/120019935-0e9ca780-bfb7-11eb-8daa-923356c3ec17.png)
![2021-05-28_12 59 00](https://user-images.githubusercontent.com/84808660/120019956-152b1f00-bfb7-11eb-94ba-afb942eec7d0.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
The STS prices will be getting an overhaul so this will be addressed when that occurs.
