### ISSUE TITLE
Sts cooldown broke

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Bugs-and-Issues#227]
**Describe the Bug**
The remaining time on sts cooldown is bugged

**To Reproduce**
1. Go to deoxys
2. use /sts
3. see the cooldown

**Servers with the bug**
tested on deoxys

**Expected behavior**
Sts cooldown should be shown

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Does it show the wrong cooldown or is there no cooldown?

**Comment by DiegoKek** [comment]
it shows some random symbols

**Comment by HackuJacku** [comment]
The cooldown isn't broken, it's just not parsing the formatting codes correctly. Re-loading the UI will refresh the value shown. I've passed this onto the developer though.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
