### ISSUE TITLE
Votes on survival do not give any rewards

### ISSUE THREAD

**Issue by Awlk** [SmashMC-Development/Bugs-and-Issues#228]
**Describe the Bug**
When ever a player votes they don't get any keys/money this used to happen once in a while but its not working at all now

**To Reproduce**
not sure what the exact issue can be for this but the rewards might have to be setup again?

**Servers with the Bug**
Survival

**Expected behavior**
Players should receive 1 vote key and 1000 dollars in game on every vote

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Can you test this and see if it works now? :D

**Comment by Awlk** [comment]
tested it, we now both receive the key and money!! thanks a lot!

**Comment by Mikirae** [comment]
Ayyyye awesome. Thank you :D
