### ISSUE TITLE
Golisopod endbattles you everytime you get it under half health in bosstower

### ISSUE THREAD

**Issue by Jasha1112** [SmashMC-Development/Bugs-and-Issues#229]
**Describe the Bug**
When you fight a Golisopod in bosstower and you dmage it under half health it automatically ends your battle with the pokemon

**To Reproduce**
1. Go to /warp bosstower
2. Fight a Golisopod
3. Damage it under half Health
4. Get kicked from the fight

**Servers with the Bug**
Every Server

**Expected behavior**
Golisopods Ability now Working in Bosstower or changing it for another Pokemon

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
This appears to be a Pixelmon Bug.
