### ISSUE TITLE
Legendary Crate Wrong Items

### ISSUE THREAD

**Issue by HackuJacku** [SmashMC-Development/Bugs-and-Issues#23]
**Issue:** Legend crate reward +10 IV boost and random IV boost are swapped

**Server(s):** All Pixelmon.

**Reproduce:** Buy and see that they are swapped

**Behaviour:** Should receive correct reward

**Comment by HackuJacku** [comment]
What exactly are the names of the items being won please?

**Comment by Sparklix** [comment]
![2021-05-15_16 04 40](https://user-images.githubusercontent.com/77632744/118364091-4ce99e00-b597-11eb-9b77-68e3bd0c5c19.png)
![2021-05-15_16 04 37](https://user-images.githubusercontent.com/77632744/118364094-4d823480-b597-11eb-8afe-040a3f3a0856.png)

**Comment by HackuJacku** [comment]
Fixed for 8.2. Also fixed the Random Legendary IV Boost, Legendary Shiny Convert and Legendary Nature Change reward.

**Comment by HackuJacku** [comment]
Changes are now live.
