### ISSUE TITLE
Chickens Spawning, unable to be cleared with auto clear

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#230]
**Describe the Bug**
Right now on Charizard Server, there's chickens spawning in ./warp training4.  The server auto clear does not clear them and they are continue to spawn more and more. 

Just head over to Charizard Server and ./warp training4.

**Servers with the Bug**
Server: Charizard, SmashMC

**Screenshots**
![image](https://user-images.githubusercontent.com/77503363/120069151-fe6bf180-c0b6-11eb-98a5-3733b8b437fd.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
This is fixed. Thank you!
