### ISSUE TITLE
Broken quest.

### ISSUE THREAD

**Issue by alextaylor03** [SmashMC-Development/Bugs-and-Issues#231]
‘defeat 3 fire type pokemon’ doesn’t work as i’ve killed 30.

Deoxys

i expected to be able to continue with my dmax quests 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
@alextaylor03 - there is no quest to "defeat 3 Fire type Pixelmon". Are talking about the "Defeat a Pokemon" quest?

**Comment by HackuJacku** [comment]
Closing due to no response. If this is still an issue, please create a new report.
