### ISSUE TITLE
Nightmare quests give the wrong items

### ISSUE THREAD

**Issue by Awlk** [SmashMC-Development/Bugs-and-Issues#232]
**Describe the Bug**
the quests where they should give nightmare gear they give unenchanted diamond gear instead

**To Reproduce**
if you go to /quests select nightmare quests, once completed the riddles 1 2 3 and 5 I believe (the ones that give nightmare gear) they give unenchanted diamond gear instead nightmare gear

**Servers with the Bug**
Survival

**Expected behavior**
The quests should give the right items from unenchanted gear to nightmare gear

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
Issue now resolved
