### ISSUE TITLE
TOO... MANY... CHICKENS!

### ISSUE THREAD

**Issue by Jumbleds** [SmashMC-Development/Bugs-and-Issues#235]
**Describe the Bug**
Basically, chickens are spawning in administrator claims in Charizard.

**To Reproduce**
1. Go to Charizard Server
2. Drop down a floor from spawn
3. See the mass amount of chickens spawning

**Servers with the Bug**
Charizard

**Expected behavior**
Chickens shouldn't be spawning there.

**Screenshots**
![2021-05-29_18 55 32](https://user-images.githubusercontent.com/84808660/120087109-4db02300-c0b3-11eb-9681-4427b23d3deb.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
Lmao. Fixed, thank you! :D
