### ISSUE TITLE
Random leg iv boosts giving low boosts at high ivs 

### ISSUE THREAD

**Issue by shandoghood** [SmashMC-Development/Bugs-and-Issues#236]
This may just be my personal misfortune making this suggestion but I want to address random iv boosts, a few times now I have purchased random iv boosts to maybe top off some of my higher iv legends (can apply to non leg as well) but I’ve found out that in quite a few situations I am getting so terribly unlucky and at on point only jumped from 93% to 94% I know it states in the name “random” but having that randomness apply to max iv slots seems kind of un impactful especially when buying one of these can run you upto half a mil atleast on ray, just some food for thought not a critical issue jsut would want to hear some other opinions 

This can apply to all servers 

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Now fixed - please create a #support ticket if you were impacted/need help.
