### ISSUE TITLE
throwing snowball on a player's Pokémon cause indefinite Pokémon battle loading screen

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#237]
**Describe the Bug**
throwing snowball on a player's Pokémon could cause indefinite Pokémon battle loading screen

**To Reproduce**
1. have a snowball in your hands
2. throw it at other players' Pokémon
3. once he is in the screen no matter how many times you click decline a battle it will keep coming back

**Servers with the Bug**
all pixelmon server on smash mc

**Expected behavior**
snowball should not have any interactions with Pokémon

**Screenshots**
a link to the video: https://www.youtube.com/watch?v=va2K6cr8ixQ

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
We'll need to test it in a Forge-only setup, please make sure you've also reported it directly to Pixelmon: https://www.pixelmonmod.com/tracker.php?p=2.

**Comment by HackuJacku** [comment]
Unable to reproduce on both a SP world and the network.
