### ISSUE TITLE
a full fainted team in wz

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#239]
**Describe the Bug**
Bring a fully fainted wz team into warzone can lead to no one be able to battle you

**To Reproduce**
1. make your whole team fainted
2. /warp warzone
3. at this point any trainer throwing a pokeball at you will just bounce off

**Servers with the Bug**
tested on jirachi and charizard believe is for all smash mc pixelmon server

**Expected behavior**
you get sent out of wz when your team fainted so you should not be able to join wz when your team is already fainted

**Screenshots**
video link to one player throwing a pokeball at me : https://www.youtube.com/watch?v=OLCl_EUItTo

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
This will be forwarded to the master ticket related to Warzone, thank you!
