### ISSUE TITLE
Water Glitch in ray WZ

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#242]
**Describe the Bug**
Whenever you throw a pokemon out, you can place water on it and the water will be there for the player. You can swim in it, still and possibly run away from wz battles with it

**To Reproduce**
Go to rayquaza server, go to the warzone throw out a pokemon and place water on the pokemon. It will then have a water bubble that will only be for the player who is doing the bug

**Servers with the Bug**
Rayquaza seems to be the only one with it, could not replicate on: Charizard, mew, or darkrai.

**Expected behavior**
Allows you to swim in water that in invisible to other playersA

**Screenshots**
![image](https://user-images.githubusercontent.com/83245837/120273050-39168b00-c26b-11eb-8fef-10b280b23b5c.png)
![image](https://user-images.githubusercontent.com/83245837/120273072-42075c80-c26b-11eb-8fec-b7c04173d7f1.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
I think this is a GD issue. Should we just deny item-use on buckets in Warzone? @Rasgnarok

**Comment by HackuJacku** [comment]
Fixed on reset
