### ISSUE TITLE
(move) shopkeeper selling same move for different price

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#243]
**Describe the Bug**
the move shopkeeper at /warp mart is selling the same move for different price because it is the same move but is tagged as a move from different region

**To Reproduce**
1. Go to /warp mart
2. Click on any move shopkeeper
3. you will see multiple of the same move is being sold also at different price

**Servers with the Bug**
Palkia, mew

**Expected behavior**
only one of each move is sold instead of duplicate

**Screenshots**
https://imgur.com/mfDORiF
https://imgur.com/uBa6pBK
https://imgur.com/uBa6pBK

**Additional context**
N/A

**Comment by Mikirae** [comment]
Took forever but I think I got them all :) Thank you and this should be good on restart.
