### ISSUE TITLE
Achievement in Event world {in Pictionary}

### ISSUE THREAD

**Issue by eboyJay69** [SmashMC-Development/Bugs-and-Issues#244]
**Describe the Bug**
You can get the Achievement [Acquire Hardware] from kyogre in the event world. 

**To Reproduce**
Someone dropped iron ingot in ./warp Pictionary and it gave me the achievement Acquire hardware. 

**Servers with the Bug**
It was on Kyogre 

**Screenshots**
n/a

**Comment by HackuJacku** [comment]
Fixed.
