### ISSUE TITLE
Healers and pcs are broken in Rayquaza training area

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Bugs-and-Issues#247]
**Describe the Bug**
When you right click healers and pcs in Rayquaza training area they dont work

**Servers with the Bug**
Rayquaza

**Expected behavior**
Healers and pcs usable again on Rayquaza

**Comment by HackuJacku** [comment]
@Lun17 - you'll need to provide us with more details. E.g: any chat errors? If so, what? ETC

**Comment by Lun17** [comment]
No errors, you just right click on them and they don't work. When you click
the pc the pc boxes don't open
When you click the healers nothing happens

Il mer 2 giu 2021, 11:16 HackoJacko ***@***.***> ha scritto:

**Comment by HackuJacku** [comment]
@Lun17 - can you check now please?

**Comment by HackuJacku** [comment]
Fixed on next reboot.
