### ISSUE TITLE
ranch blocks doesnt work normally

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#248]
**Describe the Bug**

after you put a male and a female pokemon in a ranch block sometimes 1 pokemon wont show up and when you right click on the other pokemon it says it doesn't love anyone. /unlock has been tried but in vain. These glitched ranchblock has started to spread.

**To Reproduce**
1. cant really reproduce with a certain way
2. if a breeder was working normally and suddenly one pokemon is missing
3. walk up to it and right click that pokemon it will says the pokemon doesnt love anyone eventhough with the correct pokemon with different gender

**Servers with the Bug**
most pixelmon sever on smash mc

**Expected behavior**
ranch block should produce egg in a regular intervals if the correct pokemon was placed inside the ranch block

**Screenshots**
https://imgur.com/CaDZPNh
https://imgur.com/fs2eALe
https://imgur.com/e84wNLQ
https://imgur.com/iLBA8HZ
https://imgur.com/5TaQOSK

**Additional context**
N/A

**Comment by Mikirae** [comment]
Did you ever get around to testing this in Single Player? I think you or someone else said that they were going to.

**Comment by toofuriouz** [comment]
Still waiting for it to happen but i have seen a couple more ticket about it today

**Comment by toofuriouz** [comment]
Update still wasnt able to recreate in single player world

**Comment by Mikirae** [comment]
That's really weird. I don't know what exactly we have on the server that would be preventing things from working properly
