### ISSUE TITLE
Grookey 'Tree Top' Spawn may be bugged

### ISSUE THREAD

**Issue by mnky-frt** [SmashMC-Development/Bugs-and-Issues#249]
**Describe the Bug**
I was looking over the wiki to try and figure out where Grookey spawns so I could possibly try to hunt for its hidden ability. On the Grookey wiki, it says that it spawns in Jungles and it's spawn location is on Tree Tops: https://pixelmonmod.com/wiki/Grookey. However, in the Tree Top section of the Spawn location wiki, Grookey does not appear on the list: https://pixelmonmod.com/wiki/Spawn_location. From my understanding, I was told that in order to spawn Tree Top pokemon you need to place leaves so they can spawn on them. But from my experience, I have seen barely any Grookeys.

I've had my suspicions that the spawn was bugged because I have been hunting for Grookey in general for about two weeks now and have only come across about 5 or so of them in total (probably about 15 hours or so of actual in game time). Also, when I was looking for HA Snivy, it says that the spawn rate for Snivy is 1.96%. For Grookey, it is also 1.96%. However, I have come across many more Snivy than Grookey and was able to find its HA in a reasonable amount of time. Additionally, Snivy would pop up from the rustle particles in the ground but for some reason Grookey does not even though they have the same spawn rate.

If possible, could you look into the spawn for Grookey to make sure that everything is working properly? I could be just extremely unlucky trying to get them to spawn but I feel like their spawn may be bugged at this point.

**To Reproduce**
1. Find any Jungle Biome and you will notice the Grookey is rarely spawning at all
2. Walk across the rustle particles and Grookey will still not appear
3. Find a biome with Snivy in it (Forest Hills, Roofed Forest, etc...) and you will notice more Snivy spawning even though they have the same spawn rate
4. Walking across the rustle particles will also allow you to encounter a Snivy from time to time.

**Servers with the Bug**
Palkia, but could be server wide but I don't know for sure

**Expected behavior**
I believe that Grookey should be spawning more often than it is. As well as spawning from the rustle particles on the ground.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by mnky-frt** [comment]
If you want to check on the platforms we made in ultra space I have the coords here:
Jungle M Ultra space: -6572 200 7609
ForestHills Ultra space: -7138 163 7075

**Comment by Mikirae** [comment]
{
  "id": "Grookey",
  "spawnInfos": [
    {
      "spec": {
        "name": "Grookey"
      },
      "stringLocationTypes": [
        "Tree Top"
      ],
      "minLevel": 10,
      "maxLevel": 15,
      "typeID": "pokemon",
      "condition": {
        "times": [
          "NIGHT"
        ],
        "stringBiomes": [
          "jungles"
        ]
      },
      "rarity": 5.0
    }
  ]
}

Looks fine, just a bit rare :)
