### ISSUE TITLE
Rustle battles not occuring in Warzone

### ISSUE THREAD

**Issue by HackuJacku** [SmashMC-Development/Bugs-and-Issues#25]
**Bug:** Random battles no longer happen in warzone 

**Server:** Kyogre for sure (Might be all don’t have Pokémon to test with)

**Reproduce:** Go into warzone wait awhile won’t get put into a random battle with another player

**Behavior:** While in warzone should be put into random battles against other players

**Comment by HackuJacku** [comment]
I've tested this multiple times and seems to work for me. Need more information please.

**Comment by LifelessDingus** [comment]
This is definitely still an issue. I haven't had a random battle on Rayquaza since I was a player. Granted I also didn't go there as frequently since the beginning of my staff days but still. I was on Rayquaza earlier yesterday and day before and nothing regarding random battles.

**Comment by HackuJacku** [comment]
Removing plugin due to it causing multiple issues. Will be re-added back fixed.
