### ISSUE TITLE
knock off and defog move is bugged

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#250]
**Describe the Bug**
Currently there is no way of putting defog or knock off on any pokemon that can learn such move via tm, re, move tutor, unless it is an egg move

**To Reproduce**
1. go to /warp mart
2. try teaching your pokemon defog or knock off 
3. 

**Servers with the Bug**
all server

**Expected behavior**
skarmory can learn defog through tm

**Screenshots**
https://imgur.com/vrjalka

**Additional context**
N/A

**Comment by Mikirae** [comment]
This is something that needs to be fixed via stat files I believe. Can you get me all the Pokemon that should learn defog or knock off via Move Tutor? :D

**Comment by toofuriouz** [comment]
Will do tmr

**Comment by HackuJacku** [comment]
Added to the master ticket.

**Comment by HackuJacku** [comment]
@toofuriouz - I need a list of exact Pokémon please.

**Comment by toofuriouz** [comment]
Ok

**Comment by HackuJacku** [comment]
Been provided with full list. Will be address in upcoming changelog.
