### ISSUE TITLE
Can't put anything up on Charizard GTS

### ISSUE THREAD

**Issue by zoominlp** [SmashMC-Development/Bugs-and-Issues#251]
**Describe the Bug**
The bug automatically kicks you out of the gts GUI when you try to click on item or pokemon option

**To Reproduce**
1. Go to /gts
2. Click on sell goods
3. Select item or pokemon option
4. GUI closes

**Servers with the Bug**
Charizard

**Expected behavior**
The gts GUI doesn't automatically close 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
This is an unfortunate bug that we really can't do anything about and is fixed on restart :(
