### ISSUE TITLE
Battles skills faulty for rayquaza

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#252]
**Describe the problem**
the developer skills is showing as no. 1 for all categories lv 9001 

**To Reproduce**
1. Go to rayquaza
2. Do /skills and check leaderboard
3. The first player lv is 9001

**Servers with the Bug**
Rayquaza

**Expected behavior**
the battle level of the developer shouldnt be shown?

**Screenshots**
https://imgur.com/DkEZbns
https://imgur.com/hLirNUx
https://imgur.com/Ztv6lnN
https://imgur.com/yAlxQhA

**Additional information**
N/A

**Comment by HackuJacku** [comment]
This isn't an issue. He was them for testing purposes.
