### ISSUE TITLE
Unlimited speed boost in wz

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#253]
**Describe the Bug**
If u right click on the floor with a boost pad in war zone it gives you a speed boost

**To Reproduce**
1. Go into warzone
2. Right click the floor with boost pad while runninh
3. It shows u dont have permission to build here but you will still get the speed boost

**Servers with the Bug**
Tested in jirachi but probably all pixelmon sever

**Expected behavior**
This is just like block glitching so the speed boost is expected but the item should be banned from warzone 

**Screenshots**
https://youtu.be/PlRkTh7zwqU

**Additional context**
N/A

**Comment by Mikirae** [comment]
Can we just block right clicking of the item in general?

**Comment by toofuriouz** [comment]
Maybe but in that case people cant use the lens to check ivs and ability

**Comment by Mikirae** [comment]
This has been fixed on all servers now :)
