### ISSUE TITLE
Primal Evolution

### ISSUE THREAD

**Issue by Spigii** [SmashMC-Development/Bugs-and-Issues#254]
**Describe the Bug**
Couldnt make Kyogre prima outside of battle
(Not tested in battle)

**To Reproduce**
1. Give kyogre Blue Orb
2. try doing mega (how you normally do, outside of battles)
3. No Option to mega in screen

**Servers with the Issue
Dialga
**Expected behavior**
We should be able to mega it outside oder battlw

**Screenshots**
 'N/A'.

**Additional context**
 'N/A'.

**Comment by HackuJacku** [comment]
Potentially fixed on reset
