### ISSUE TITLE
Use loose Power herb in Npc house

### ISSUE THREAD

**Issue by Jasha1112** [SmashMC-Development/Bugs-and-Issues#257]
so when you use Geomancy in Npchouse you use the Power Herb after the battle

go to /warp Npchouse
fight one of the trainers 
use Geomancy on Xerneas with a power herb equipped
defeat the trainer

Giratina

you not loosing Powerherb after the battle

**ScreenshN/A

Sho and Olimoo saw it happening

**Comment by Mikirae** [comment]
This is a feature of Pixelmon; if you use a consumable item against an NPC or a Pokemon, it will use it.
