### ISSUE TITLE
/textures is outdated

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#258]
**Describe the Bug**
Currently /textures will bring you to a link that directs you to textures pack version 5.1 while we are already at 7.1

**To Reproduce**
1. Go to any server on smash mc
2. Type /textures and click on it

**Servers with the Bug**
All pixelmon server on smash mc

**Expected behavior**
direct you to a link for the right texture pack file 

**Screenshots**
https://imgur.com/EvXFhmK
https://imgur.com/UZnG8N4

**Additional context**
 'N/A'.

**Comment by Mikirae** [comment]
Fixed on next restart :)
