### ISSUE TITLE
Advancements seeable on servers

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#259]
**Describe the Bug**
Able to see people getting advancements in chat

**To Reproduce**
watch someone get an achievment

**Servers with the Bug**
Giratina/all

**Expected behavior**
make it not be a thing

**Screenshots**
https://gyazo.com/09a6d098297b9fb4789e73ce646446be

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
@Shoji007 - need the world names please

**Comment by Mikirae** [comment]
BOI WE NEED THE WORLD NAMES

**Comment by Shoji007** [comment]
GIRATINA 
PALKIA
DIALGA
MEW
JIRACHI
KYOGRE
CHARIZARD
RAYQUAZA
DARKRAI
DEOXYS 
@Mikirae  ya numpty i said Giratina/all on the ticket

**Comment by Mikirae** [comment]
> GIRATINA
> PALKIA
> DIALGA
> MEW
> JIRACHI
> KYOGRE
> CHARIZARD
> RAYQUAZA
> DARKRAI
> DEOXYS
> @Mikirae ya numpty i said Giratina/all on the ticket

WORLDS NOT SERVERS! Like spawn, survival, nether, end, ultra, etc

**Comment by Shoji007** [comment]
Werll my guess is Warzone, Ultraspace, and overworld as i have had people get achievements in all those worlds

**Comment by HackuJacku** [comment]
This does not occur on every server. Please provide the exact server and exact worlds (spawn, survival, nether, end, ultra, etc) where this occurs.

**Comment by Shoji007** [comment]
![image](https://user-images.githubusercontent.com/82549364/122657987-e889a380-d12d-11eb-8a6a-44f3943d6f54.png)
 @HackuJacku  i finally caught someone getting an achievement. Its in the Safari world. dialga i believe. but best to check all just to make sure

**Comment by Shoji007** [comment]
![image](https://user-images.githubusercontent.com/82549364/122667211-4393b880-d177-11eb-868f-332dc11793c1.png)
 @HackuJacku  Giratina Safari world as well

**Comment by HackuJacku** [comment]
Fixed this for all the safari worlds listed. If there are any more of these messages for specific worlds, please state which ones and the server.
