### ISSUE TITLE
Warzone legendary spawning

### ISSUE THREAD

**Issue by HackuJacku** [SmashMC-Development/Bugs-and-Issues#26]
**Bug:** Legendaries spawning in impossible places

**Server:** All Pixelmon server.

**Expected Behavior:** shouldn’t be able to spawn there

![image](https://user-images.githubusercontent.com/18508413/115098592-c191d400-9f28-11eb-9b3b-5b9b26e3be8f.png)

**Comment by AmsterDaan** [comment]
handled added barrier blocks to the areas in question to stop the pokemon from spawning there, so ticket closed due to being fixed
