### ISSUE TITLE
a different version of block glitch in wz 

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#260]
**Describe the Bug**
block glitching in wz with incense

**To Reproduce**
1. Go to warzone
2. place an incense down jump on it
3. but since incense isnt really treated as a block so the items stays there and u can tower up without the normal type of block glitches technique u need

**Servers with the Bug**
all smash mc pixelmon server

**Expected behavior**
such item shouldn't be able to stack in air anywhere

**Screenshots**
https://www.youtube.com/watch?v=M8xuDohz2ok

**Additional context**
N/A

**Comment by Mikirae** [comment]
Sounds like another thing that can get solved when we block the right clicking of items in Warzone

**Comment by Mikirae** [comment]
This is now fixed on all servers. Thank you for the report! :)
