### ISSUE TITLE
dexquest doesn't work

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Bugs-and-Issues#261]
**Describe the Bug**
/Dexquest doesn't work for the whole server
**To Reproduce**
1. Go to giratina
2. type in /dexquest
3 see error

**Servers with the Bug**
giratina

**Expected behavior**
Supposed to work, instead gives a error

**Screenshots**
N/a

**Additional context**
N/a

**Comment by Mikirae** [comment]
This has been fixed cutie
