### ISSUE TITLE
nether portal not working

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#262]
**Describe the Bug**
nether portal doesnt work

**To Reproduce**
1. step on a nether portal
2. it wont teleport u into the other dimension

**Servers with the Bug**
tested on rayquaza jirachi and giratina

**Expected behavior**
suppose to be teleported into the nether

**Screenshots**
https://youtu.be/xLgVvVuheCA

**Additional context**
N/A

**Comment by HackuJacku** [comment]
#264
