### ISSUE TITLE
Alolan HA maroark dont breed with dittos 

### ISSUE THREAD

**Issue by slippysayjin** [SmashMC-Development/Bugs-and-Issues#263]
**Describe the Bug**
i am trying to get a bp alolan maroark with the HA i only have a Male alolan one and trying to get a female with the ditto but for the longest time now its only giving me normal cubbones 

**Servers with the Bug**
Dialga

**Expected behavior**
I would just like to have the HA Alolan Maroark 

**Screenshots**
N/A

**Additional context**
 'N/A'.

**Comment by Mikirae** [comment]
This sounds like a Pixelmon Bug unfortunately
