### ISSUE TITLE
broken texture for galaxy regice

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#265]
**Describe the Bug**
part of the galaxy texture of regice is not working properly

**To Reproduce**
1. throw out the pokemon
2. you will see part of the regice is not there

**Servers with the Bug**
tested on jirachi

**Expected behavior**
it should show the full texture

**Screenshots**
https://imgur.com/1j60U2M

**Additional context**
N/A

**Comment by Mikirae** [comment]
We need to get a new version of this made to fit the new models

**Comment by HackuJacku** [comment]
As Regice was given an emission (an additional layer) in 8.2, this texture will need to re-done when we next work on custom textures. Until this texture is fixed, I'll leave this open.

**Comment by HackuJacku** [comment]
Fixed on reset
