### ISSUE TITLE
Teleport on porygon2

### ISSUE THREAD

**Issue by vitorcardz** [SmashMC-Development/Bugs-and-Issues#267]
**Describe the Bug**
Im not being able to make porygon2 to learn teleport by any way, should be able to learn throught move transfer if im not wrong.

**Servers with the Bug**
Mew

**Comment by vitorcardz** [comment]
![image](https://user-images.githubusercontent.com/85424387/120911686-2217d480-c681-11eb-99c0-a178b66edcf4.png)
![image](https://user-images.githubusercontent.com/85424387/120911696-2fcd5a00-c681-11eb-85ce-da326d78ba29.png)

**Comment by HackuJacku** [comment]
Added to the master ticket.
