### ISSUE TITLE
bingo bug

### ISSUE THREAD

**Issue by sketchy6** [SmashMC-Development/Bugs-and-Issues#269]
**Describe the Bug**
I catch pokemon but he did count in bingo paper

**Servers with the Bug**
palkia

**Expected behavior**

**Screenshots**
![Screenshot_23](https://user-images.githubusercontent.com/85434448/120918894-739d7f00-c6d4-11eb-9f11-6c638123492c.png)
![Screenshot_22](https://user-images.githubusercontent.com/85434448/120918896-74361580-c6d4-11eb-857a-9ebbfe987107.png)

**Comment by HackuJacku** [comment]
Fixed from the next reboot.
