### ISSUE TITLE
Bingo rewards bug

### ISSUE THREAD

**Issue by P-Sach** [SmashMC-Development/Bugs-and-Issues#270]
**Describe the Bug**
Both 3x3 and 5x5 bingo cards are giving only 1rc as a reward.

**To Reproduce**
1. Go to 'bingo card'
2. Click on 'the card'
3. Scroll down to 'the rewards in the bingo card '
4. It will show only 1 rc as reward and if u complete the card will give 1 rc ;-;

**Servers with the Bug**
Rayquaza

**Expected behavior**
I expected bingo cards to give nice rewards as i saw in siruds video.

**Screenshots**
 'N/A'.

**Additional context**
'N/A'.

**Comment by jahangir6969** [comment]
Rewards pool has now been fixed.
