### ISSUE TITLE
pearl cannot be sold in smash mc server

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#273]
**Describe the Bug**
pearl cannot be sold in the smashmc server but is able to in a single player word with the exact same mod

**To Reproduce**
1. Go to /warp mart or any mart in the wild for a shopkeeper
2. talk to the shopkeeper and go to sell an item
3. pearl cannot be found on the sell list

**Servers with the Bug**
tested on jirachi and dialga possibly all server

**Expected behavior**
pearl should be able to be sold at 500 a piece

**Screenshots**
single player world:
https://imgur.com/c4KjfFp

smashmc server:
https://imgur.com/eck8C77

**Additional context**
N/A

**Comment by Mikirae** [comment]
Were they able to be sold in the past?

**Comment by toofuriouz** [comment]
I am not sure about this. Was brought up in a ticket so i tried it in single player world

**Comment by HackuJacku** [comment]
Fixed on reset
