### ISSUE TITLE
Hover the word to type does not give any reward

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#274]
**Describe the Bug**
On the survival server the "hover the word to type", where the winner who types/unscrambles the word the fastest wins, is giving no reward. In the past, the reward was $200. 

**To Reproduce** 
1. Go to Survival
2. Click on hover the word to type (when it pops up)
3. Type the word
4. See error that $200 is not given

**Servers with the Bug**
Survival

**Expected behavior**
Players are expected to receive $200 after winning. 

**Screenshots**
NA

**Additional context**
NA

**Comment by jahangir6969** [comment]
Issue now fixed.
