### ISSUE TITLE
Charizard Ground Gym

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#275]
**Describe the Bug**
On Charizard, the ground gym, which is level 40, doesn't allow challengers to send in a challenge if their pokemon are above level 40, even when the team is perfectly legal according to all rules, including the natural evolution clause.

**To Reproduce**
1. Go to Charizard.
2. Challenge the ground gym via /gyms, with a team of pokemon that are level 41+, even if they are legal (examples: Gliscor, greninja, feraligatr, ..).
4. "Failed to join the queue! Too high level: 40". See screenshot below.

**Servers with the Bug**
Charizard.

**Expected behavior**
You should be able to challenge the ground gym with pokemon of any level, as long as they are legal by the gym rules. This as the gym battle should have it's rules set so that the pokemon will be level 40 for the battle. 

**Screenshots**
![image](https://user-images.githubusercontent.com/82727445/121000549-a2762c80-c78a-11eb-8d13-71d8652754d6.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
Can you tell me if it's fixed now? :)

**Comment by HackuJacku** [comment]
Confirmed with @oLimooo that this is now fixed.
