### ISSUE TITLE
Warzone Rules 

### ISSUE THREAD

**Issue by Blxgdenn** [SmashMC-Development/Bugs-and-Issues#277]
**Describe the Bug**
Isn’t a bug, the /Wzrules need changing

The /Wzrules need to be changed so that it is made clear that using them timer to stall another playing out spitefully is against the rules, was a ticket made about this issue but because the rule isn’t clear no action could be taken 

Needs to be changed on all servers

**Comment by HackuJacku** [comment]
Fixed on reset
