### ISSUE TITLE
Palkia crates preview

### ISSUE THREAD

**Issue by Ryan1595** [SmashMC-Development/Bugs-and-Issues#278]
**Describe the Bug**
I am unable to preview the vote or epic crates on specifically palkia

**To Reproduce**
1. Go to palkia
2. Click on vote and epic crates
3. unable to preview

**Servers with the Bug**
Please provide a list of which servers have this bug.
Only palkia
**Expected behavior**
Be able to preview
**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
This should be fixed for all crates on there. Can you please let me know? :)

**Comment by HackuJacku** [comment]
Confirmed that this is now fixed - thanks.
