### ISSUE TITLE
Leg Shiny Convert Disapears

### ISSUE THREAD

**Issue by Byzle** [SmashMC-Development/Bugs-and-Issues#279]
**Describe the Bug**
If you have two legendary shiny converts stacked in your inventory and try to use them, it will use both of the Shiny convert papers
**To Reproduce**
1. Hold the paper in your hand and right click it on the ground as they are stacked
2. Click on the pokemon that you want to become shiny
3. Now it should use both of the papers

**Servers with the Bug**
Darkrai is the only know server

**Expected behavior**
When trying to use the one paper both should be removed from your inventory

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
I can't reproduce this. The only thing I saw was that, one of the times, it just moved the paper over in my inventory. My guess is that either the paper was never in your inventory (common visual bug) or that it got moved over to a different part of your inventory.
