### ISSUE TITLE
Aura Crate wrong items

### ISSUE THREAD

**Issue by HackuJacku** [SmashMC-Development/Bugs-and-Issues#28]
**What's the bug?** When opening a aura crate it gives the wrong reward (legendary choice of aura)

**Server(s):** All Pixelmon.

**How to reproduce:** Get the reward of getting a legendary choice of aura

**Expected behavior:** Player is supposed to be give a legendary choice of aura but instead is given a non-legendary custom aura

**Comment by HackuJacku** [comment]
Tested on Rayquaza and it worked fine. Would need further information as everything appears correct.

**Comment by Sparklix** [comment]
@HackuJacku tested and works fine, gives right paper
