### ISSUE TITLE
Cosmetic crate

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#280]
**Describe the Bug**
Every server has already the cosmetics crate with the preview and the possibility to open it

**To Reproduce**
1. Go to a random server
2. Go to /warp crates
3. See the cosmetic crate

**Servers with the Bug**
Every server but not Mew

**Expected behavior**
The cosmetic crate shouldn't be out yet

**Screenshots**
![2021-06-08_01 52 53](https://user-images.githubusercontent.com/83550357/121107309-fa9f4400-c807-11eb-8fc2-d3fb992c585d.png)
![2021-06-08_01 53 10](https://user-images.githubusercontent.com/83550357/121107315-fc690780-c807-11eb-83d8-cb931f3835e9.png)

**Comment by HackuJacku** [comment]
Not a bug, intended. I've fixed being unable to preview the crate on Mew though.
