### ISSUE TITLE
Infinite pig spawner

### ISSUE THREAD

**Issue by British-Commie** [SmashMC-Development/Bugs-and-Issues#281]
**Describe the Bug**
The ability to get infinite PIG spawners
**To Reproduce**
1. place the Log furniture item on a wood-block
2. the log furniture then looks like a normal block of wood 
3.place Any spawner on top of the Log turned  Wood-Block
4.the log turns into a pig spawner

**Servers with the Bug**
Survival

**Expected behavior**
Log turns into a normal-looking block and then into a Pig spawner

**Screenshots**

**Additional context**
only turns into a pig spawner

**Comment by British-Commie** [comment]
Correction it duplicates any block but it can only make pig spawners

**Comment by jahangir6969** [comment]
Please try again and see if it happens. I have disabled the recipe that causing this.

**Comment by jahangir6969** [comment]
This issue now resolved.
