### ISSUE TITLE
Charizard GTS System Down

### ISSUE THREAD

**Issue by LilLuxy** [SmashMC-Development/Bugs-and-Issues#282]
**Describe the Bug**
A clear and concise description of what the bug is. Players are unable to put up either Pokemon or Items, and when clicking on either option in the Sell A Good option of the GTS are kicked out of the screen entirely. 

**To Reproduce**
1. Type /GTS
2. Click on the Sell A Good Option
3. Click either Items or Pokemon
4. Are Kicked from the GTS screen

**Servers with the Bug**
Please provide a list of which servers have this bug. Charizard

**Expected behavior**
A clear and concise description of what you expected to happen. For players to be able to list sellable items and Pokemon.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'. N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'. N/A

**Comment by HackuJacku** [comment]
@LilLuxy - this is working as intended for me?

**Comment by HackuJacku** [comment]
Just confirmed with the players of Charizard and they've all said it's working as intended/fine.
