### ISSUE TITLE
Kyogre warzone not spawning pokemon

### ISSUE THREAD

**Issue by Refsamaha** [SmashMC-Development/Bugs-and-Issues#283]
**Describe the Bug**
The Kygore Warzone is not spawning in any pokemon, I have checked all of warzone and not one pokemon has spawned. 

**To Reproduce**

Visit the Kygore Warzone

**Servers with the Bug**
Please provide a list of which servers have this bug:

Kyogre

**Expected behavior**
 
I was expecting pokemon to spawn in warzone. However none have spawned.

**Screenshots**

![image](https://user-images.githubusercontent.com/85337608/121344213-5802c600-c8d8-11eb-8146-6a2147c2e1d6.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed.
