### ISSUE TITLE
Regice Galaxy Texture Glitch

### ISSUE THREAD

**Issue by asjdk** [SmashMC-Development/Bugs-and-Issues#284]
**Describe the Bug**

**To Reproduce**
1. Go to 'Warzone'
2. Catch a galaxy textured Regice
3. Go back to base
4. Take out the Regice from pc

**Servers with the Bug**
Please provide a list of which servers have this bug.
Mew
**Expected behavior**
A Galaxy Texture Regice without holes in it.
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://user-images.githubusercontent.com/85635546/121389023-f82d0f00-c919-11eb-9e8a-e18e901e82f0.png)
![image](https://user-images.githubusercontent.com/85635546/121389109-1266ed00-c91a-11eb-9313-ea7440afba3b.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
References #265
