### ISSUE TITLE
shinys not showing in chat

### ISSUE THREAD

**Issue by LeNoope** [SmashMC-Development/Bugs-and-Issues#285]
**Describe the Bug**
not showing in chat when someone catches a shiny

**To Reproduce**
1. Go to deoxys
2. catch a shiny 
3. look in chat

**Servers with the Bug**
Deoxys

**Expected behavior**
it should come up in chat when someone catches a shiny and show the ivs of the shiny  pokemon that was caught 

**Screenshots**
i have a clip

**Additional context**
N/A

https://user-images.githubusercontent.com/84600550/121426997-1cb1d700-c96c-11eb-8845-af60c0b99ca4.mp4

**Comment by Mikirae** [comment]
This is now fixed on all servers once they restart :)

**Comment by LeNoope** [comment]
hey i just caught a shiny and its still not working
