### ISSUE TITLE
new cosmetic skins isnt working properly

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#287]
**Describe the Bug**
the new cosmetics skins isnt going into the right position of the body party

**To Reproduce**
1. get one of the wing cosmetic put it on
2. it leaves the body

**Servers with the Bug**
probbaly all pixelmon server

**Expected behavior**
wing should be on the back of the body

**Screenshots**
https://cdn.discordapp.com/attachments/852737344851148830/852737576330854470/image0.jpg

**Additional context**
N/A

**Comment by HackuJacku** [comment]
What version of the resource pack are you using?

**Comment by toofuriouz** [comment]
Sorry i didnt ask that question during the ticket

**Comment by HackuJacku** [comment]
Outdated texture pack version - use the latest.
