### ISSUE TITLE
you can tp people into warzone

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#288]
**Describe the Bug**
people can be tped into warzone without knowing

**To Reproduce**
1. use /tpahere and the /warpwarzone and walk over the pressure plate
2. the other person click it
3. gets tp into warzone which bypass all the requirement

**Servers with the Bug**
tested on jirachi probably all pixelmon server

**Expected behavior**
people cant be tped into warzone

**Screenshots**
https://youtu.be/J90xrV215Yk

**Additional context**
N/A

**Comment by Mikirae** [comment]
Pokemon should only be counted if they are caught or papered :)

**Comment by Mikirae** [comment]
WRONG TICKET

**Comment by HackuJacku** [comment]
Fixed in Warzone 2.0.
