### ISSUE TITLE
open worm hole in wz

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#289]
**Describe the Bug**
opening worm hole with pokemon in wz

1. Go to warzone
2. throw the pokemon out with wormhole ability
3. create a worm hole if the wormhole is spawn close to the ground people can jump into ultraspace

**Servers with the Bug**
tested on jirachi possible all pixelmon server

**Expected behavior**
the only way to leave warzone should be /safeplace

**Screenshots**
https://imgur.com/JYpeqHR

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Working on a fix.

**Comment by HackuJacku** [comment]
Fixed from next restart.
