### ISSUE TITLE
claimblocks decreasing

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#29]
What's the bug? for some players, their amount of claimblocks decreases over time (instead of increasing) and it even goes into the negative

Server(s): reported on jirachi and giratina, but likely all servers

How to reproduce: no idea (see tickets 14884 and 17887)

Expected behavior: claimblocks should always increase over time, not decrease (and especially not go into negative)

**Comment by Mikirae** [comment]
I believe that this is now fixed but I could be wrong. I think it wasn't that they decreased over time, it was that sometimes, when ranking up, LuckPerms would mess up Meta Data and delete all of their accrued claim blocks.
