### ISSUE TITLE
Pokedex count not increasing after trading/gifting

### ISSUE THREAD

**Issue by HydraSerenity** [SmashMC-Development/Bugs-and-Issues#290]
**Pokedex Count Not Increasing After Trading/Gifting**
If i trade someone a pokemon or receive one, the pokedex count does not increase.

**To Reproduce**
1. trade or /gift another player
2. Check pokedex

**Servers with the Bug**
Charizard

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HydraSerenity** [comment]
Buying from GTS also does not count onto the pokedex

**Comment by Mikirae** [comment]
Pretty sure we have it set to the setting where you need to catch or get Pokemon from papers :)
