### ISSUE TITLE
Lily Pad Bug Jirachi Warzone

### ISSUE THREAD

**Issue by LilLuxy** [SmashMC-Development/Bugs-and-Issues#291]
**Describe the Bug**
A clear and concise description of what the bug is. When you go to warzone you can place lily pads on top of the pools of water in order to be able to stand on top of it.

**To Reproduce**
1. Go to /warp warzone
2. Find a body of water
3. Place lily pads on top
4. Stand on top of them to stand on water

**Servers with the Bug**
Jirachi 

**Expected behavior**
For the lily pads to despawn instantly after attempting to place in warzone.

**Screenshots**
![image](https://user-images.githubusercontent.com/85566557/121644332-e2763180-ca60-11eb-8e5d-d96a73c091cd.png)
![image](https://user-images.githubusercontent.com/85566557/121644369-eb670300-ca60-11eb-8190-557fa2058678.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'. N/A

**Comment by Mikirae** [comment]
So, do they stay there permanently? Or if you went back later would they be gone?

**Comment by HackuJacku** [comment]
Fixed on reset
