### ISSUE TITLE
weavile 

### ISSUE THREAD

**Issue by StrictlyIQ9** [SmashMC-Development/Bugs-and-Issues#293]
**Describe the Bug**
A clear and concise description of what the bug.
Weavile cant learn knock off 
**To Reproduce**
tried to teach weavile knock off and found out i couldnt learn it

**Servers with the Bug**
Please provide a list of which servers have this bug.
all
**Expected behavior**
weavile should be able to learn it 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Added to master ticket.
