### ISSUE TITLE
House Dupelicate

### ISSUE THREAD

**Issue by Kelurious** [SmashMC-Development/Bugs-and-Issues#295]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**
 that the house  suddenly got duped. Add some screenshots of the duped house. After that u can say whatever.  that My friends house has been duped and both of u claim that i don't want the duped house there
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'. https://cdn.discordapp.com/attachments/839130613579251762/853172027610365962/2021-06-12_15.06.05.png https://cdn.discordapp.com/attachments/839130613579251762/853172027610365962/2021-06-12_15.06.05.png
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
I don't want anyone to duped house so

**Comment by HackuJacku** [comment]
Unable to reproduce sadly. This is the first time this has occurred so it might be a one-off thing. Without being unable to reproduce, it's hard to tell.
