### ISSUE TITLE
Buymove

### ISSUE THREAD

**Issue by Blxgdenn** [SmashMC-Development/Bugs-and-Issues#296]
**Describe the Bug**
Scolipede can't learn aqua tail on /buymove 
**To Reproduce**

**Servers with the Bug**
All servers

**Expected behavior**
Should be able to learn aqua tail

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Added to master ticket.
