### ISSUE TITLE
can /heal in warp pvp anytime in survival server

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#297]
**Describe the Bug**

Anyone who has perms to /heal in the survival server can do so at anytime including in warp pvp. This is an issue as someone could abuse it and not be killed. 

**To Reproduce**
1. Go to /warp pvp.
2. In chat, type /heal
3. type /heal multiple times

**Servers with the Bug**
Survival

**Expected behavior**
In the past, /heal had a cool down timer. 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
n/a

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by jahangir6969** [comment]
This is now fixed.
