### ISSUE TITLE
/ec working in wz

### ISSUE THREAD

**Issue by br183adl** [SmashMC-Development/Bugs-and-Issues#298]
**Describe the Bug**
being able to use the command /ec in wz to bring illegal items in

**To Reproduce**
1.go to warzone
2. use the command /ec
3. u can bring any items out of it into wz
**Servers with the Bug**
all

**Expected behavior**
/ec to be disabled in the warzone

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
@br183adl - server?

**Comment by br183adl** [comment]
all sorry was just editing it

**Comment by HackuJacku** [comment]
@br183adl - please can you check now on all servers? Please let me know what happens on each server

**Comment by br183adl** [comment]
still works on every server

**Comment by HackuJacku** [comment]
@br183adl - what happens now please?

**Comment by HackuJacku** [comment]
Confirmed that this is now fixed.
