### ISSUE TITLE
Zen mode does not activate when galarian daramitan goes below 50% HP

### ISSUE THREAD

**Issue by karan-shishoo** [SmashMC-Development/Bugs-and-Issues#299]
Issue
My galarian daramitan with the Zen Mode ability does not trigger its ability

Background
I got a male HA galarian daramuka recently. Spent some time breeding it with a ditto to get female HA one which I used to continue breeding to get good natures/EV's. I started training up the first BP one I got. I did only evolve it at level 100, and took to for testing. So far in either player battles, trainer battles or wild battles it never goes into zen mode (even after substitute -> bellydrum). Given I can use more than one move does mean that atleast in the code it does not have gorilla tactics but I am not exactly sure what else to do. I have a video displaying this but I cant attach it here due to its size, I have shared that in the discord issues already.

my account name is \_pyromacer_ and this is on the Rayquaza server

**Comment by toofuriouz** [comment]
seems like if the darm is bred before version 8.2 it can turn into zen mode 
https://imgur.com/ewMIWiP
test it on rayquaza

**Comment by karan-shishoo** [comment]
Not exactly sure how I can test it before 7.2 since I only joined in the past week or so, lucked out on grabbing a HA galar daramuka and was disappointed when my galar Darmanitan did not go zenmode when ive seen zen mode galar Darmanitans before. Listed it as an issue since its not exactly working as intended

**Comment by HackuJacku** [comment]
Potentially fixed on reset
