### ISSUE TITLE
Darkrai: Warzone, Pokemon still spawning inside ice mountains

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Bugs-and-Issues#3]
**Describe the Bug**
Warzone: Pokemons still spawning in places unreachable 

**To Reproduce**
1. Go to 'Darkrai warzone and check the inside ice part'

**Servers with the Bug**
Please provide a list of which servers have this bug.
Darkrai

**Expected behavior**
Pokemon shouldn't spawn inside the ice mountains

**Screenshots**
https://gyazo.com/bc2d336c40200f74ad14d296d16f988a
![bc2d336c40200f74ad14d296d16f988a](https://user-images.githubusercontent.com/77632744/114855270-0eb95d00-9de6-11eb-9936-4da827c3ea8e.png)

**Additional context**

**Comment by Sparklix** [comment]
![image](https://user-images.githubusercontent.com/77632744/114859048-838e9600-9dea-11eb-830f-903b7efc2055.png)

**Comment by HackuJacku** [comment]
Filled this location in with blocks. Please let me know if there are any more locations like this via a new issue.
