### ISSUE TITLE
kyogre statue head collapsed

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#30]
Bug: the head of the kyogre statue in /warp tourney has collapsed (the concrete powder fell down)
Server(s): giratina, darkrai
Reproduce: go to /warp tourney (its on the far right when u enter)
Behavior: statue should be complete, not collapsed
![image](https://user-images.githubusercontent.com/82659374/115118746-0eb38b80-9fa5-11eb-9c59-01d24a8dd2f8.png)

**Comment by HackuJacku** [comment]
Re-pasted the statue - fixed.
