### ISSUE TITLE
Fishious Rend on Dracovish keeps failing to hit

### ISSUE THREAD

**Issue by mnky-frt** [SmashMC-Development/Bugs-and-Issues#300]
**Describe the Bug**
I've been using Dracovish's move Fishious Rend and I've noticed that the move randomly will fail to hit for some reason. I've tried using it with a choice scarf and a choice band and with both items it randomly will just say that it used the move and it failed. Seems to usually fail when the other player switches out their pokemon. However some times it will fail regardless of what either player does.

**To Reproduce**
1. Get a Dracocvish
2. Teach it Fishious Rend
3. Put a choice scarf or choice band on it
4. Use the move Fishious Rend and it will fail randomly for some reason

**Servers with the Bug**
I'm on Palkia but I don't know if other servers have this issue

**Expected behavior**
The move should not fail. I've looked on the pixelmon wiki and the actual pokemon wiki and no where does it say that it should fail

**Screenshots**
![image](https://user-images.githubusercontent.com/85257491/121978936-39c51c00-cd57-11eb-8e6e-3526ca2e2d17.png)
![image](https://user-images.githubusercontent.com/85257491/121979159-a9d3a200-cd57-11eb-9d1f-3d451e4280ec.png)
![image](https://user-images.githubusercontent.com/85257491/121979197-bd7f0880-cd57-11eb-900a-db67d5e0c302.png)

**Additional context**
N/A

**Comment by mnky-frt** [comment]
first two screenshots are a player switching their pokemon into the fishious rend move and it failing
last screen shot is the move failing without the above case happening

**Comment by mnky-frt** [comment]
also after further investigating this, it seems that the move will usually fail if dracovish moves after the other pokemon. i know the move is supposed to do more damage if it moves first but the move should still hit regardless of dracovish's speed

**Comment by Mikirae** [comment]
This is unfortunately a Pixelmon bug so we can’t do anything really.
