### ISSUE TITLE
Zombie greninja is unobtainable

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#301]
**Describe the Bug**
When you try to change your greninja into a zombie version, the process will fail even if all requirements are met. This leaves you with a regular greninja.

**To Reproduce**
1. Get a Greninja.
2. Meet all the requirements for changing a pokemon into it's zombie version. You need: night time, a full moon, a light level of 12 at the pokemon's location, no blocks being placed over the pokemon, a pokemon with an existing zombie texture and a jack o lantern. Click on the pokemon with the jack o lantern to obtain a zombie version when all conditions mentioned are met.
3. You're left with a regular greninja, where it should of became zombie.

**Servers with the Bug**
All.

**Expected behavior**
When all requirements are met, the greninja should turn into a zombie version.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Is it possible for you to test this in single player at all? This sounds like a Pixelmon bug.

**Comment by AmsterDaan** [comment]
Tested and works fine, so issue can be closed.
![image](https://user-images.githubusercontent.com/82483448/122653888-b1bc8900-d13f-11eb-9df2-1586598ff1e9.png)
