### ISSUE TITLE
block generation glitch

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#302]
**Describe the Bug**
blocks can be create out of thin air with red stone, sticky piston, slime block, and ice block
could be something to do with grief protection cause is with ice block

**To Reproduce**
1. build the same set up shown in video
2. turn it on
3. it will create 5 blocks that looks like stone block but it when you break it nothing happen

**Servers with the Bug**
tested in rayquaza
testing in single player world without mod (the problem did not occur)

**Expected behavior**
no blocks should be created there

**Screenshots**
https://youtu.be/Ij5mQmb1Rgk

**Comment by HackuJacku** [comment]
Fixed on reset
