### ISSUE TITLE
/safeplace doesnt tp you away from wz

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Bugs-and-Issues#303]
**Describe the Bug**
/safeplace doesnt work

**To Reproduce**
1. Go to warzone
2. write /safeplace
3. wait 5 seconds

**Servers with the Bug**
tested on kyogre

**Expected behavior**
/safeplace should tp you to spawn

**Screenshots**
N/A

**Additional context**
RaZ3xUber found this bug, not me

**Comment by HackuJacku** [comment]
@DiegoKek - please check after the next reboot.

**Comment by Mikirae** [comment]
@DiegoKek :)

**Comment by HackuJacku** [comment]
Confirmed by @DiegoKek that this is fixed.
