### ISSUE TITLE
How to force a warzone "waiting" glitch.

### ISSUE THREAD

**Issue by ujmki10** [SmashMC-Development/Bugs-and-Issues#304]
Once one of your Pokémon dies you just sit their at the party selection screen. This can only be done once a pokemon has died and not off a general switch where the system has an option to click a move for you.

**Comment by Mikirae** [comment]
If you suspect someone of doing this, please put in the ticket that you believe they're faking the waiting glitch and we can request a screenshot from them as well.

**Comment by HackuJacku** [comment]
Fixed in next version of Pixelmon.
