### ISSUE TITLE
Players can open gates and doors in Musical chairs

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#305]
**Describe the Bug**
Players can open the gates and press buttons to open the iron doors in musical chairs

**To Reproduce**
1. Go to /warp musicalchairs
2. Click on the gates/buttons near the doors
3. See error

**Servers with the Bug**
Mew, Dialga, Darkrai

**Expected behavior**
Players shouldn't be able to open the gates or the doors, as they can just get back in the game, or go behind the dj console

**Comment by HackuJacku** [comment]
This should now be fixed, @Superfire96. Please can you double check and let me know?

**Comment by Superfire96** [comment]
After checking, players can still open gates and doors

**Comment by HackuJacku** [comment]
@Rasgnarok, could you take a look at this please?

**Comment by HackuJacku** [comment]
Unable to resolve due to setup of GD. Will require a fresh start/newly configured setup.
