### ISSUE TITLE
Players are able to safeplace in warzone while battling a pokemon

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#306]
**Describe the Bug**
Players are able to safeplace in warzone while battling a pokemon

**To Reproduce**
1. Go to /Warp warzone
2. Engage a pokemon
3. Type /safeplace

**Servers with the Bug**
Darkrai and Palkia

**Expected behavior**
Players shouldn't be able to safeplace while battling a pokemon in warzone

**Screenshots**
N/a

**Additional context**
Video of it happening
https://user-images.githubusercontent.com/83550357/122580987-d983f200-d056-11eb-8c19-caee16202ac4.mp4

**Comment by HackuJacku** [comment]
Same as #112
