### ISSUE TITLE
Players are able to safeplace while moving in warzone

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#307]
**Describe the Bug**
Players are able to safeplace while doing anything in warzone

**To Reproduce**
1. Go to /Warp warzone
2. Type /safeplace
3. Keep moving

**Servers with the Bug**
Charizard

**Expected behavior**
Players shouldn't be able to move while safeplacing

**Video proof**
https://user-images.githubusercontent.com/83550357/122599983-72bf0280-d06f-11eb-8930-debe536572b8.mp4

**Comment by Mikirae** [comment]
This is a pretty big bug but unfortunately, until the rewrite is finished, there's nothing that we can really do about it :(
