### ISSUE TITLE
Weavile Can’t Learn Knock Off and Pursuit

### ISSUE THREAD

**Issue by DeathSZN** [SmashMC-Development/Bugs-and-Issues#309]
**Describe the Bug**

My weavile can’t learn knock off and pursuit from move tutor and transfer tutor

**To Reproduce**
1. Go to '...' /warp mart
2. Click on '....' transfer tutor and move tutor 
3. Scroll down to '....' the move pursuit and the move knock off
4. See error - it would then say it can’t learn the moves it’s intended to learn (pursuit and knock off)

**Servers with the Bug**
Please provide a list of which servers have this bug.

Kyogre server

**Expected behavior**

weavile should be able to learn pursuit and knock off. May need for the tourney coming up. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Added to master ticket.
