### ISSUE TITLE
/warp tourney griefed

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#31]
**Describe the Bug**
/warp tourney got griefed

**To Reproduce**
go to /warp tourney

**Servers with the Bug**
Darkrai

**Expected behavior**
it should not be griefed
![image](https://user-images.githubusercontent.com/82659374/115118973-643c6800-9fa6-11eb-9c86-a85f7a9d89bf.png)

**Comment by Rasgnarok** [comment]
Has this been fixed yet?

**Comment by Bruhbert1999** [comment]
nope. didnt wanna do it when i reported, since i found it odd that an admin claim was griefed, so didnt wanna touch it

**Comment by Rasgnarok** [comment]
Fixed. Not sure how it was possible for players to grief it, but all of it is claimed by GD under admin land. Block-break is disabled. No AS trace either.
