### ISSUE TITLE
/textures command needs updating

### ISSUE THREAD

**Issue by YeetusV2** [SmashMC-Development/Bugs-and-Issues#311]
**Describe the Bug**

**To Reproduce**
1. Go to The SmashMC Charizard server
2. Click on /textures link
3. Scroll down to the link
4. See the error in drop box

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Updated from next reboot.
