### ISSUE TITLE
Warzone ultrabeast spawn announcement

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#312]
**Describe the Bug**
When the ultrabeast Buzzwole spawns in warzone, it will not say the name in chat but just %pokemon%

**To Reproduce**
1. Go to server mew
2. Wait for the buzzwole to spawn
3. See error, it will not say buzzwole in chat

**Servers with the Bug**
Mew

**Expected behavior**
The broadcast in chat should say "buzzwole"

**Screenshots**
![ub](https://user-images.githubusercontent.com/83550357/122659865-4fce4480-d17c-11eb-92e3-c380e9d16fb7.png)

**Comment by HackuJacku** [comment]
Fixed from next reboot.
