### ISSUE TITLE
Giratina warzone pressure plate not working

### ISSUE THREAD

**Issue by LilLuxy** [SmashMC-Development/Bugs-and-Issues#313]
**Describe the Bug**
Giratina warzone pressure plate isn't registering players and isn't letting anyone inside the warzone.

**To Reproduce**
1. Go to /warp warzone
2. Step on the pressure plate
3.wait for teleport into warzone
4. Isn't warped to to the plate not registering players

**Servers with the Bug**
Giratina

**Expected behavior**
A player is warped into the warzone.

**Screenshots**

https://user-images.githubusercontent.com/85566557/122670619-f58bae80-d190-11eb-9b14-ad3deb51d38f.mov

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'. N/A

**Comment by HackuJacku** [comment]
Fixed.
