### ISSUE TITLE
Charizard X Wings Glitch

### ISSUE THREAD

**Issue by Blxgdenn** [SmashMC-Development/Bugs-and-Issues#314]
**Describe the Bug**
Charizard X Wings show in floor instead of on player

**To Reproduce**
Equip the Charizard X wings in anywhere outside spawn

**Servers with the Bug**
Was only Shown on Rayquaza, couldn't find anyone else with the wings

**Expected behavior**
should be shown on player model

**Screenshots**
![Screenshot_390](https://user-images.githubusercontent.com/83072886/122685379-e0e7fe80-d202-11eb-97e0-7a8de87cc218.png)

**Comment by HackuJacku** [comment]
Potentially fixed on reset
