### ISSUE TITLE
Flame body not working as intended

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#315]
**Describe the Bug**
flame body does not reduce your egg step but it reduce hatch time

**To Reproduce**
1. /eggsteps a egg mark down the steps
2. /eggsteps the egg again with a pokemon with flame body on your team
3. although the /eggsteps doesn't work i have 2 magikarp egg with zero steps invested to do timer count on the hatch time. 
4. the egg paired with a flamebody pokemon take less time to hatch

**Servers with the Bug**\
possible all server tested on jirachi

**Expected behavior**
the eggsteps should indicate the differences

**Screenshots**
**showing eggsteps** : https://youtu.be/pV7IAyLKISw
**flamebody hatch timer (2m18s)** : https://youtu.be/LEQwc-ZbYFc
**normal hatch timer (3m50s)** : https://youtu.be/WBvM714RlMI

**Additional context**
N/A

**Comment by HackuJacku** [comment]
This is not a bug, it is working as intended. The value displayed appears strange but it's still correct - speaking to the developer as we speak. However, Flame Body makes 1 step act as 2 so the value is technically x/2.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
