### ISSUE TITLE
chat legend and shiny announcments 

### ISSUE THREAD

**Issue by LeNoope** [SmashMC-Development/Bugs-and-Issues#316]
**Describe the Bug**
when a legendary spawns in wz it doesn't say which legend it it it just say %legend% and doesnt specify if it galaxy, shadow or normal also when a shiny is caught it doesnt announce in chat 

**To Reproduce**
1. Go to deoxys
2. wait for a legend to spawn in wz 
3. See error

1. go to deoxys 
2. catch a shiny
3. see error

**Servers with the Bug**
deoxys

**Expected behavior**
i expect for it to say in chat what legend or ultra beast spawns in and if it is galaxy or shadow

**Screenshots**
![2021-06-20_22 09 40](https://user-images.githubusercontent.com/84600550/122688851-8789ca80-d216-11eb-813e-c1a86dffd617.png)

**Comment by HackuJacku** [comment]
Fixed on next reboot.
