### ISSUE TITLE
Emperor tag doesn't show in discord when player talks trough mc chat

### ISSUE THREAD

**Issue by Awlk** [SmashMC-Development/Bugs-and-Issues#317]
**Describe the Bug**
When a player talks in the mc chat their rank, name and chat shows in discord, the emperor tag does not show trough discord

**To Reproduce**
If a player with the emperor tag talks in game chat It will now show as "emperor" if you look in discord 

**Servers with the Bug**
Survival

**Expected behavior**
Players who bought the emperor tag will now see the same tag in discord when they talk

**Screenshots**

**Additional context**
N/A

**Comment by jahangir6969** [comment]
Issue is now resolved.
