### ISSUE TITLE
Water Flow, Furnace Animations

### ISSUE THREAD

**Issue by Hounrawr** [SmashMC-Development/Bugs-and-Issues#318]
**Describe the Bug**
While in my claimed zone, all water is still. I can scoop out the bottom layers of water and still have 3 layers of water above it without it flowing down. I can put a bucket of water on the ceiling and it will just stay there in a 1x1 block area.

Furnaces aren't showing any fire animations to show that it is cooking the materials, still cooks them but you have no clue if they are done are not, and since you cant leave the chunk they are in without stopping them you have no clue when it is completed unless you individually hit ever single furnace.

**To Reproduce**
1. Claim an area
2. Fill a bucket with water
3. Place water so it can spread out (like normal)
4. Look at how water doesn't spread.

**Servers with the Bug**
Mew

**Expected behavior**
I expected the water to actually flow like it should in Minecraft

**Screenshots**
![204510970_955228608652561_8107986325784633063_n](https://user-images.githubusercontent.com/69549833/122843923-874d0600-d2ce-11eb-8ac8-5fa84e86c656.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed on reset
