### ISSUE TITLE
cannot fight pokemon on their own claim

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#319]
**Describe the Bug**
trying to attack a pokemon in my own claim but it just show i sent out a pokemon and did not actually engage it, however if i unclaim the area i can attack the pokemon

**To Reproduce**
1. throw a pokemon in your claim
2. if it didnt work unlcaim your area
3. should be able to engage the pokemon now

**Servers with the Bug**
tested on dialga

**Expected behavior**
Players should be able to engage pokemon in your claim

**Screenshots**
https://youtu.be/oIydG5TNANA

**Additional context**
N/A

**Comment by Shoji007** [comment]
This is happening on all servers now @HackuJacku

**Comment by Shoji007** [comment]
Servers that are currently suffering from the issue are mew/darkrai/palkia/dialga

**Comment by HackuJacku** [comment]
Superfire has confirmed that this is no longer an issue.
