### ISSUE TITLE
the modpack is broken,please fix.

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#320]
**Describe the Bug**
people are not getting required mods/resource pack in newest version of texture pack

**To Reproduce**
Download newest version of modpack and see that reauth/ resource pack is missing

**Servers with the Bug**
the technic launcher

**Expected behavior**
it should have these things in order to give players rewards for getting our modpack!
should look like this:
![image](https://user-images.githubusercontent.com/82549364/122950499-1d6e4400-d342-11eb-9126-f77c52eeff33.png)

![image](https://user-images.githubusercontent.com/82549364/122950372-029bcf80-d342-11eb-9a81-23ff56a8a6a6.png)

**Screenshots**
people who download the newest version get this:
![image](https://user-images.githubusercontent.com/82549364/122950646-3d9e0300-d342-11eb-9ccc-1142d8b01a9d.png)
![image](https://user-images.githubusercontent.com/82549364/122950691-468ed480-d342-11eb-88c3-ba5fb82ca9d9.png)

**Additional context**
@HackuJacku if this can be quick fixed or if there's another way to fix this please let me know!

**Comment by HackuJacku** [comment]
The latest version of the Modpack includes the latest version of the resource pack, as seen below. Please provide me with the Modpack version being used - the version I'm using is 1.1.1

![image](https://user-images.githubusercontent.com/18508413/123074962-ad2df400-d40f-11eb-9917-30042e3875fb.png)

**Comment by HackuJacku** [comment]
I deleted my version of the SmashMC Pixelmon Pack and re-downloaded it. It downloaded the Resource Pack correctly. 

![image](https://user-images.githubusercontent.com/18508413/123075991-9f2ca300-d410-11eb-989c-d31eacaf2ed1.png)

**Comment by Shoji007** [comment]
Its not only the texture pack that is broken. As stated in the screenshots above I had someone install the modpack just before I made this report and share their screen and certain mods AND the resourcepack was missing so they couldn’t get the/modpack rewards as stated in the popup ingame becausr they apparently didn’t have the modpack even though he clearly did as I had the player launch it via technic launcher. Is there a certain bug in the modpack that would cause failure of certain mods to download? @HackuJacku

**Comment by HackuJacku** [comment]
Re-download Technic because as I have just shown, it downloads it correctly. This is the first time hearing about this so it's sounding like a specific player issue, not modpack issue.

**Comment by Shoji007** [comment]
I’ll see if I can get ahold of the player.
