### ISSUE TITLE
Rayquaza Boss Tower barely spawning any bosses

### ISSUE THREAD

**Issue by Jumbleds** [SmashMC-Development/Bugs-and-Issues#321]
**Describe the Bug**
Rayquaza boss tower is slowly spawning bosses in bosstower slower than other servers

**To Reproduce**
1. Go to Rayquaza server
2. Go to boss tower
3. Go into the boss tower to any of the floors

**Servers with the Bug**
Rayquaza

**Expected behavior**
Bosses should be spawning faster.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Slightly increased the rates.
