### ISSUE TITLE
Arceus can't learn whirlpool

### ISSUE THREAD

**Issue by IsThief** [SmashMC-Development/Bugs-and-Issues#322]
**Describe the Bug**
I'm on char and I'm trying to learn whirlpool but he can't, I would like the move to be added to /buymove

**To Reproduce**
1. Go to '/warp mart'
2. Click on ' water tm shop keeper and buy whirlpool'
3. Try to teach it

**Servers with the Bug**
Please provide a list of which servers have this bug.
Charizard (all server I think)
**Expected behavior**
Arceus to be able to learn whirlpool
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Added to master ticket.
