### ISSUE TITLE
Breeding Skill not on Darkrai

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#323]
**Describe the Bug**
Darkrai doesnt have the Breeding Skill

**To Reproduce**
1. Go to Darkrai
2. Type /skills
3. Cannot see Breeding skill

**Servers with the Bug**
Darkrai

**Expected behavior**
Having Breeding Skill available

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/123499155-7aad1280-d62c-11eb-857c-f18b010f772f.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed.
