### ISSUE TITLE
/ag disqualify does not work as intended (Gyms)

### ISSUE THREAD

**Issue by Unitzero007** [SmashMC-Development/Bugs-and-Issues#324]
**Describe the Bug**
During gym battles, when a problem occurs (such as a waiting glitch) Gym Leaders are able to disqualify the challenger (with /ag disqualify) and redo the battle. Unfortunately, /ag disqualify does not let the challenger redo the battle, instead it counts as a loss for the challenger and they will have to wait for 12 hours to challenge the gym again.

**To Reproduce**
1. Accept a gym challenge
2. Fight a challenger
3. Type /ag disqualify in the middle of a battle
4. Challenger loses and is forced to wait for 12 hours

**Servers with the Bug**
tested on Rayquaza (potentially all)

**Expected behavior**
/ag disqualify is supposed to only disqualify the participant, not make them lose.

**Screenshots**
![image](https://user-images.githubusercontent.com/83878956/123504064-9a265880-d689-11eb-9095-b045455c1994.png)

**Additional context**
players affected so far by the 12 hour cd because of this bug (Rayquaza Server): domcas02, lucaseo101

**Comment by HackuJacku** [comment]
Intended feature - disqualification is the same as losing as it's cheating. It should be used for such.
