### ISSUE TITLE
Scizor cant learn knock off

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Bugs-and-Issues#325]
**Describe the Bug**
Scizor cant learn knock off, if i go to the warp mart scizor should learn knock off
**To Reproduce**
1. Go to '...' warp mart or ./buymove
2. Click on '....' On the move tutor 
3. Scroll down to '....' knock off
4. See error scizor cant learn knock off but it should

**Servers with the Bug**
Please provide a list of which servers have this bug.
Rayquaza but i think its all servers
**Expected behavior**
Scizor should be able to learn knock off. It even says on smogon that its the "best set" for it
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
https://www.smogon.com/dex/sm/pokemon/scizor/

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
Added to master ticket.
