### ISSUE TITLE
Cant redeem galarian forms

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Bugs-and-Issues#326]
**Describe the Bug**
When you try to redeem a galarian pokemon it says galarian is not a valid form

**To Reproduce**
1. Get a specific pokemon paper
2. Try to claim a galarian form
3. See error

**Servers with the Bug**
Tested on giratina and kyogre

**Expected behavior**
Specific papers should let you redeem galarian forms

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
@DiegoKek - `/rewardclaim Moltres galarian` worked perfectly fine for me, tested it on multiple Pokémon. I have the same permission as you do in this instance.
