### ISSUE TITLE
Cant use /rewardclaim darmanitan galarian, gives out the error "galarian is not a valid form"

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Bugs-and-Issues#328]
**Describe the Bug**
Cant redeem galarian darmanitan from specific pokemon paper

**To Reproduce**
1. Get a specific pokemon paper
2. use the command "/rewardclaim darmanitan galarian
3. See error

**Servers with the Bug**
Tested on kyogre and giratina, but seems to be network wide

**Expected behavior**
You should be able to redeem galarian darmanitans

**Screenshots**
N/A

**Additional context**
Multiple people have faced this issue today, it also seems to have started today

**Comment by HackuJacku** [comment]
Fixed in next version.
