### ISSUE TITLE
Jirachi gts

### ISSUE THREAD

**Issue by FrstEzzi** [SmashMC-Development/Bugs-and-Issues#329]
**Describe the Bug**
Jirachi gts isn't working atm there is nothing on there and you cant put things up either
**To Reproduce**
1. Go to 'gts'
2. Click on 'sell a good'
3. sell anything
4. all it says is processing your request
![Screenshot 2021-06-26 222707](https://user-images.githubusercontent.com/84062773/123531855-aa602700-d6cd-11eb-80b3-8f4ebd2a42c1.png)

**Comment by HackuJacku** [comment]
Same as #332
