### ISSUE TITLE
x-ray glitch

### ISSUE THREAD

**Issue by RedOlimpus** [SmashMC-Development/Bugs-and-Issues#330]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by RedOlimpus** [comment]
1. Got to a pokemon
2. battle it
3. move the camera through a block with wasd
Servers: all
I expected to simply just stop the camera
Screenshots: N/A
I don't think you have control over it I just wanted to point it out.

**Comment by Mikirae** [comment]
This is a Pixelmon Bug and has existed for a while unfortunately :( Thank you for reporting it!

**Comment by RedOlimpus** [comment]
Yeah No problem
