### ISSUE TITLE
Cant attack pokemon in claims

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#331]
**Describe the Bug**
In all of my claims I cannot battle pokemon no matter what I try to do. It doesn't help if I relog or restart minecraft.

**Servers with the Bug**
Deoxys

**Expected behavior**
To engage in a battle with the pokemon I threw my ball at.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Dxhcky** [comment]
I cant attack players pokemon either

**Comment by HackuJacku** [comment]
Not a bug.
