### ISSUE TITLE
Jirachi GTS can't be accessed

### ISSUE THREAD

**Issue by Bkdevileu** [SmashMC-Development/Bugs-and-Issues#332]
Everytime someone does /gts it gives a fatal error

**To Reproduce**
Do /gts

Just Jirachi

**Expected behavior**
Being able to access GTS

![image](https://user-images.githubusercontent.com/84034504/123551483-da5d0800-d769-11eb-99fc-64f29f336aeb.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed.
