### ISSUE TITLE
Shadow Hypno skin is bugged

### ISSUE THREAD

**Issue by Bkdevileu** [SmashMC-Development/Bugs-and-Issues#333]
**Describe the Bug**
Hypno shadow skin is missing parts of the pokemon

**To Reproduce**
Have the latest texture pack and pixelmon mod

**Servers with the Bug**
All

**Expected behavior**
Normal Shadow skin with all the pokemon parts

**Screenshots**
![image](https://user-images.githubusercontent.com/84034504/123551765-0cbb3500-d76b-11eb-80a9-d1dd6d4e6494.png)

**Additional context**
Probably has to do with the new models (the same happens with drowzee but I don't have screenshots)

**Comment by HackuJacku** [comment]
Fixed on reset
