### ISSUE TITLE
Cosmetics

### ISSUE THREAD

**Issue by Tentamtene** [SmashMC-Development/Bugs-and-Issues#334]
**Describe the Bug**
If you have cosmetics on and you turn quickly you will see the cosmetics on your screen because it didn't react fast enough. 
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
This happened on Mew but may be on more servers. 
**Expected behavior**
The cosmetics would move with you, like elytra. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
This maybe happenens only with wing because they are wider.

**Comment by HackuJacku** [comment]
Not a bug. This is to do with your connection to the server, along with how we handle our cosmetics so you can still wear armor and such.
