### ISSUE TITLE
Warzone ./safeplace bug in Charizard

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#335]
**Describe the Bug**
In Charizard Server, people are able to type ./safeplace while running. Or they can move around after typing ./safeplace.
People are also able to ./safeplace while fighting any wild mon in warzone.

**To Reproduce**
1. Go to wz / fight any wild mon
2. Type ./safeplace in wz
3. Start running around within that 3 seconds
4. Able to safeplace

**Servers with the Bug**
Charizard

**Expected behavior**
In Charizard Server, people are able to type ./safeplace while running. Or they can move around after typing ./safeplace.
People are also able to ./safeplace while fighting any wild mon in warzone.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Same as #307
