### ISSUE TITLE
Flying on pokemon bug in charizard

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#336]
**Describe the Bug**
apparently when i was just casually flying on my pokemon for less than 10 seconds, the server kicks me out for saying flying is not enabled

**To Reproduce**
1. Throw out a flying pokemon(eg zapdos)
2. Fly on it
3. Server kicks me out

**Servers with the Bug**
Charizard

**Expected behavior**
I wanted to fly on my zapdos, but I haven't flew on it for less than a min or 2, the server kicks me out

**Screenshots**
![unknown](https://user-images.githubusercontent.com/77503363/123628982-49a82a00-d846-11eb-86f8-030416495937.png)

Additional evidence in discord: 
Ticket #28300 opened in #28300-charizard-server-big
**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed from next reboot.
