### ISSUE TITLE
Gym leader bug

### ISSUE THREAD

**Issue by galactic4204315** [SmashMC-Development/Bugs-and-Issues#337]
Was fighting rock gym and noticed this, multiple gym leaders were all merged together dont knwo if glitch or not. 
Server giratina.
![20210628_144722](https://user-images.githubusercontent.com/84818844/123652614-59af1200-d824-11eb-8ee6-d868fe2391a6.jpg)

**Comment by HackuJacku** [comment]
Speaking to Waterdude but please follow the correct, provided format in the future.

**Comment by HackuJacku** [comment]
Waterdude is aware and it's already on his internal tracker for AquaGyms. I'll close this issue as a result.
