### ISSUE TITLE
Healers / Pc not working in charizard spawn

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#338]
**Describe the Bug**
Players are not able to use healers and PCs in spawn on charizard

**To Reproduce**
1. Go to /server charizard
2. Drop down the spawn
3. Try to use an healer or a pc

**Servers with the Bug**
Charizard

**Expected behavior**
Players should be able to use them

**Screenshots**
https://user-images.githubusercontent.com/83550357/123662874-25dce800-d836-11eb-827e-c09e18cc1005.mp4

**Comment by HackuJacku** [comment]
Potentially fixed after the next reboot. Will need to check but if not, I need to give an override permission.

**Comment by HackuJacku** [comment]
Fixed.
