### ISSUE TITLE
getting kicked for flying on a pokemon

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#339]
**Describe the Bug**
get kicked for flying with a pokemon anywhere

**To Reproduce**
1. throw out a pokemon that can fly
2. ride on it and fly
3. get send back to hub

**Servers with the Bug**
tested on charizard

**Expected behavior**
player should be able to fly with their pokemon

**Screenshots**
https://imgur.com/O7VA8Ec

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed from next reboot.
