### ISSUE TITLE
No glows in warzone

### ISSUE THREAD

**Issue by Sslooshyy** [SmashMC-Development/Bugs-and-Issues#34]
**Describe the Bug**
Some players don't have a glow in warzone, they dont unequip it they just go to warzone and it isn't on
**To Reproduce**
1. go to kyogre's warzone

**Servers with the Bug**
Please provide a list of which servers have this bug.
kyogre, I don't know about the others since I can't go to warzone on the other servers
**Expected behavior**
Players should have glow turned on automatically in warzone

![image](https://user-images.githubusercontent.com/82677325/115143500-b9639280-a015-11eb-978a-7489f4e2659d.png)

**Comment by HackuJacku** [comment]
Same as #51 - will be address in the Warzone re-write.
