### ISSUE TITLE
Safeplace Glitch

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#340]
**Describe the Bug**
People can safe place while running

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Warzone
2. do /safe place
3. it will say safe placing in 3 seconds so start running
4. U safeplace

**Servers with the Bug**
Jirachi

**Expected behaviour**
It should cancel the safe place instead of letting u safe place

**Screenshots**
'N/A'.

**Additional content**
Please make the safe place timer 5 seconds again as I can't fight anyone in wz when I hop on.

**Comment by DragonBallBreakersRandomizer** [comment]
https://user-images.githubusercontent.com/84050975/124064006-fed31180-da01-11eb-98fa-34172b741c56.mp4

**Comment by HackuJacku** [comment]
Same as #204 - please read the comments.
