### ISSUE TITLE
None of the npcs at the market place at spawn work in Survival

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#341]
**Describe the Bug**
The NPCs at the marketplace at spawn no longer do anything when you right-click. They all say they have various functions like auction house, spawners, etc. 

**To Reproduce**
1. Go to /spawn
2. fly to the npcs
3. right click all of them

**Servers with the Bug**
Survival

**Expected behavior**
In the past, players were able to right click the NPCs and each would sell what is written above their heads. For example, one has "spawners" across it's head and if you would right click it, it would sell you spawners. 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
https://gyazo.com/42caf870909077eb351352538c64dbb3

Tested as an default player and working fine.
