### ISSUE TITLE
bug that cause you to have no pokemon in your party

### ISSUE THREAD

**Issue by toofuriouz** [SmashMC-Development/Bugs-and-Issues#342]
**Describe the Bug**
a way to walk around with no pokemon using the missingno glitch 
or 
crash your game

**To Reproduce**
1. open your pc
2. right click really quick to get rid of your pokemon on your party to the pc until a missingno pops out
3. remove all your party member leaving only the missingno out
4. then if u move the missingno to a different party slot will get rid of it leaving no pokemon in your party
5. or if u try to spectate the stats of the missingno which will crash your game

**Servers with the Bug**
tested on darkrai

**Expected behavior**
no missingno should apear with u put your pokemon into your pc

**Screenshots**
Part 1: https://youtu.be/Eb7fsdM6tIs
Part 2: https://youtu.be/ME8wgpY4x7A
crash: https://youtu.be/hFPNWK8XeJI

**Additional context**
N/A

**Comment by Mikirae** [comment]
This appears to be a Pixelmon Bug. Thank you for reporting! :)
