### ISSUE TITLE
/buyclaimblocks Broken

### ISSUE THREAD

**Issue by Ryan1595** [SmashMC-Development/Bugs-and-Issues#343]
**Describe the Bug**
Whenever a large quantity of claim blocks is purchase, it deducts the money from your account without giving you the blocks

**To Reproduce**
1. Go to Any server
2. /buymoves 10,000
3.  It will keep your claim blocks the same while taking the money

**Servers with the Bug**
Only tested on Kyogre and Dialga
**Expected behavior**
Get claim blocks

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

![2021-07-01_19 12 26](https://user-images.githubusercontent.com/84028511/124202943-32b14400-daa1-11eb-9729-335cf2286c14.png)
![2021-07-01_18 44 06](https://user-images.githubusercontent.com/84028511/124202945-3349da80-daa1-11eb-855a-e7a0d49b968f.png)

**Additional context**
It worked when I only bought like 3 claim blocks, idk why bulk would have something to do with it.

**Comment by Mikirae** [comment]
Does this work when you purchase a smaller amount of claim blocks?

**Comment by HackuJacku** [comment]
Potentially fixed on reset
