### ISSUE TITLE
Combat quest #2 in Survival gives blank enchanted book instead of sharpness 4

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#344]
**Describe the Bug**
In the Survival server, in /q, combat quest #2 does not give a Sharpness 4 book. Instead, it gives a blank enchantment book.

**To Reproduce**
1. Go to Survival Server
2. Type /q
3. Find combat quest 2
4. Kill someone like Awlk a bunch of times to complete the quest 
4. See error that you are given a blank enchantment book instead of Sharpness 4

**Servers with the Bug**
Survival

**Expected behavior**
The quest says it will give a Sharpness 4 book not a blank enchanted book. Players are having to make tickets because of this.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
n/a

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
This is now fixed.
