### ISSUE TITLE
Villagers are not working.

### ISSUE THREAD

**Issue by Awlk** [SmashMC-Development/Bugs-and-Issues#345]
**Describe the Bug**
Villagers don't replant crops (can break) and are also not breeding for some reason

**To Reproduce**
1. Get a villager near farm land
2. make it break the crops you will see that they don't replant anything

1. place 2 villagers next to each other with enough beds
2. Give them bread to breed.
3. you will see that the process is or taking extremely long or it is indeed bugged.

**Servers with the Bug**
Survival

**Expected behavior**
Villagers should be able to breed and place crops again

**Screenshots**
'N/A'.

**Additional context**
I have tried most basic tricks to see if they still work and they don't work at all from what I have seen.

**Comment by jahangir6969** [comment]
No clue. What breaking this at the moment.

**Comment by jahangir6969** [comment]
Updated Paper and Claims api/plugin. Still an issue.

**Comment by jahangir6969** [comment]
The issue can be finally closed. As I have found the issue and place in an fix.
