### ISSUE TITLE
Gts not showing up items / pokemons

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#346]
**Describe the Bug**
If you type /gts and go to the browser section, it will not show any pokemons or items.

**To Reproduce**
1. Go to /server mew
2. Type /gts
3. Click on "Browser"

**Servers with the Bug**
Mew

**Expected behavior**
Gts should show items and pokemons

**Screenshots**
![image](https://user-images.githubusercontent.com/83550357/124361297-adf43080-dc2e-11eb-8399-ef142024cbc1.png)

**Comment by Mikirae** [comment]
Is this still occurring?

**Comment by Superfire96** [comment]
> Is this still occurring?

Sorry for the late reply, and yes, it's still a problem

**Comment by Mikirae** [comment]
F I X E D
