### ISSUE TITLE
Glastier does not get galaxy texture when merging with galaxy calyrex, even with a galaxy glastier.

### ISSUE THREAD

**Issue by Refsamaha** [SmashMC-Development/Bugs-and-Issues#347]
**Describe the Bug**
Galaxy calyrex merge with glastrier does not give the glastrier a galaxy texture, even when I use both pokemon galaxy. 

**To Reproduce**
Try merging a galaxy calyrex with a regular or galaxy calyrex.

**Servers with the Bug**
Jirachi, and probably the rest

**Expected behavior**
I expected to get both pokemon in galaxy texture

**Screenshots**

![2021-07-03_11 45 19](https://user-images.githubusercontent.com/85337608/124364215-d5c6a280-dbf4-11eb-8f9b-36e38efb9817.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Issue with Pixelmon itself, not a texture issue. Will speak to the appropriate people.

**Comment by HackuJacku** [comment]
Forwarded to Pixelmon: https://pixelmonmod.com/tracker.php?p=2&t=16262
