### ISSUE TITLE
In the Survival server can easily tp away from battle in warp pvp by doing /home

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#348]
**Describe the Bug**
In the Survival server you can easily tp away from battle in warp pvp by doing /home. 

**To Reproduce**
1. Go to /warp pvp
2. Click on a player and go into combat
3. Do /home
4. See how you can just leave whenever

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival

**Expected behavior**
It could be like warzone or something where you are unable to type a command to leave or there is a penalty if you log out. Like combat-log thing but only in the pvp world?

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
n/a
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
Fixed.
