### ISSUE TITLE
Unable to primal my groudon

### ISSUE THREAD

**Issue by TotalMadLad6969** [SmashMC-Development/Bugs-and-Issues#349]
**Describe the Bug**
For some reason my Groudon wont go primal, ive tried everything and even went to the discord in serach of help, I met with Wiepie_ there and after going thought a couple things and sending my groudon to him to test it out, i was told to come here, he said that it worked fine with his but for some reason it didnt work for me. I wouldnt think there'd be anything wrong with my groudon as i bought it with the speficic legendary and spent irl money to get him. Anyways i was told to come here for help so sorry about this and thanks in advance

**To Reproduce**
Im not sure u can, Wiepie_ said it worked fine for his pokemon so it seems to be a thing with only my groudon

**Servers with the Bug**
Im currently on Rayquaza

**Expected behavior**
I thoght he'd go primal

**Screenshots**
I dont have screenshots as theres not really anything to screenshot

**Comment by DragonBallBreakersRandomizer** [comment]
If u have a dynamax band it wont work, Idk if u don't have any band on tho but I think u need mega band. try with a mega band. Also u cant go primal outside of battle

**Comment by HackuJacku** [comment]
As same #254
