### ISSUE TITLE
Falling blocks brokey

### ISSUE THREAD

**Issue by Mantas9** [SmashMC-Development/Bugs-and-Issues#351]
Falling blocks stop falling after doing so for a while

1. stack alot of concrete powder/sand/grave;/etc
2. go to the bottom
3. break the bottom block

Deoxys server

The falling blocks to fall

![2021-07-07_23 07 25](https://user-images.githubusercontent.com/87035153/124822160-3a2c8d80-df78-11eb-83d0-df264eb3f0b3.png)

**Comment by HackuJacku** [comment]
Fixed on reset
