### ISSUE TITLE
Victini can’t learn glaciate

### ISSUE THREAD

**Issue by Monkeybanditt** [SmashMC-Development/Bugs-and-Issues#352]
**Describe the Bug**
Victini is unable to learn Glaciate; it should be able to learn glaciate through buymove; it is an event move

**To Reproduce**
Go to mart/move relearner/move tutor/buymove and see that glaciate is nowhere to be found

**Servers with the Bug**
Please provide a list of which servers have this bug.
At least Rayquaza, most likely all servers however.
**Expected behavior**
Victini should be able to learn glaciate at least through /buymove—it is an event move that victini is able to learn on showdown. Can look on smogon and see it says victini should be able to learn glaciate.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Added to master ticket.
