### ISSUE TITLE
GTS not working

### ISSUE THREAD

**Issue by Srostron82** [SmashMC-Development/Bugs-and-Issues#353]
**GTS not working.  Most of the options are blank and stash gives a timed out error**

**To Reproduce**
1. Go to 'mew server'
2. Type /gts
3. Click on stash or listings

**Servers with the Bug**
Mew

**Expected behavior**
See items for sale in listings and see items that sold or concluded in stash.

**Screenshots**
![IMG_20210707_175132982_HDR](https://user-images.githubusercontent.com/87099722/124836883-c24b6c80-df51-11eb-9d56-257e3b1efc35.jpg)
![IMG_20210707_175139231_HDR](https://user-images.githubusercontent.com/87099722/124836888-c5465d00-df51-11eb-977e-d8738b908a6f.jpg)

**Additional context**
This has been going on for days

**Comment by HackuJacku** [comment]
Fixed
