### ISSUE TITLE
is:issue is:open on giratina the npchouse trainers are glitched dosent let us battle it says can only be battled once by a player 

### ISSUE THREAD

**Issue by fellafine** [SmashMC-Development/Bugs-and-Issues#354]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by AmsterDaan** [comment]
this issue was fixed on the day of npc house, so i will be closing this.
