### ISSUE TITLE
Cant party up on minigames

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#355]
**Describe the Bug**
Me nad my friends cant party up in minigames

**To Reproduce**
1. Go to minigames
2. try to party up
3. then it don't work

**Servers with the Bug**
Minigames

**Expected behavior**
should be able to party up.

**Screenshots**
'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
@CrownlessOcto - What happens when you try and create a party?

**Comment by DragonBallBreakersRandomizer** [comment]
when we try to party up sometimes it just wont let us in the party or even accept or join

**Comment by HackuJacku** [comment]
Unable to reproduce. If this occurs in the future, please provide a detailed method to reproduce along with errors/messages.
