### ISSUE TITLE
Charizard GTS broken

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#356]
**Describe the Bug**
Charizard GTS isnt working

**To Reproduce**
1. Go to Charizard
2. Type /gts
3.  See error

**Servers with the Bug**
Charizard

**Expected behavior**
GTS should work

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/125117892-c8268680-e0e6-11eb-9848-add626e2cd0d.png)

**Additional context**

**Comment by HackuJacku** [comment]
Fixed.
