### ISSUE TITLE
In the Survival server doing /discord only brings you to the discord website not pokesmash discord

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#357]
**Describe the Bug**
/discord doesn't give players the pokesmash discord in the Survival server

**To Reproduce**
1. Go to Survival
2. Type /discord
3. Click the link
4. See error that it does not take you to SmashMC discord

**Servers with the Bug**
Please provide a list of which servers have this bug.
I don't know if other servers are experiencing this but Survival is. 

**Expected behavior**
/discord is expected to give players the SmashMC discord

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
n/a
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by jahangir6969** [comment]
![image](https://user-images.githubusercontent.com/59332632/126034637-00944f22-c7fd-487e-b430-6c440afb0dff.png)

Fixed.
