### ISSUE TITLE
Pokemon that should be able to learn "Pursuit" cant learn the move.

### ISSUE THREAD

**Issue by sameluyangelu** [SmashMC-Development/Bugs-and-Issues#358]
**Describe the Bug**
When you go to the rightside move tutor at "Warp Mart" with a pokemon that can learn "Pursuit" it says that it is unable to learn "Pursuit"

**To Reproduce**
1. Go to "Warp Mart" then the Rightside Move tutor to the left of the Move Relearner.
2. Click on the rightside move tutor and then click on a pokemon who can learn pursuit. (ex. Tyranitar or Weavile)
3. Scroll down to where it shows the move "Pursuit"
4. See error where it says "cant learn"

**Servers with the Bug**
Please provide a list of which servers have this bug. I only checked Jirachi and Kyogre but I believe every server has this bug.

**Expected behavior**
A clear and concise description of what you expected to happen. I expected for Tyranitar and other pokemon to be able to learn pursuit.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
<img width="1065" alt="Screen Shot 2021-07-10 at 10 27 49 AM" src="https://user-images.githubusercontent.com/87235881/125166530-10d35380-e16a-11eb-8f58-de18f0ecff28.png">

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Added to master ticket.
