### ISSUE TITLE
npc speaking Spanish!

### ISSUE THREAD

**Issue by br183adl** [SmashMC-Development/Bugs-and-Issues#359]
**Describe the Bug**
npc at mart is in Spanish
**To Reproduce**
go to mart 
click on the npc "evo stones" it displays a spanish text
**Servers with the Bug**
palkia

**Expected behavior**
translated to English

**Screenshots**
![2021-07-10_23 42 42](https://user-images.githubusercontent.com/84156993/125178046-f5536180-e1d8-11eb-8030-86c35c6e9707.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
¡Nooo! ¡Lo arreglaré lo antes posible!

**Comment by br183adl** [comment]
had to pull out the translate to understand that miki lol

**Comment by HackuJacku** [comment]
Fixed on reset
