### ISSUE TITLE
Vein Miner Dupe Glitch

### ISSUE THREAD

**Issue by AmsterDaan** [SmashMC-Development/Bugs-and-Issues#36]
**Describe the Bug**
When you use vein miner on an ore block that is inside a claim, that block then gets duplicated

**To Reproduce**
Use ore miner in a claim on and ore to see results

**Servers with the Bug**
All servers as issue with the /skill

**Expected behaviour**
This should not be happening where items can be duped, you should only get one ore when said block is mined

https://user-images.githubusercontent.com/82483448/115233704-23f8f900-a110-11eb-92c2-80bb4da51122.mp4

**Comment by HackuJacku** [comment]
Moved to @Waterdude's internal tracker.
