### ISSUE TITLE
/sts in warzone 

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#360]
**Describe the Bug**
People can use /sts in warzone

**To Reproduce**
1. Go to Mew
2. Enter warzone
3. Do /sts
4. The UI appears and you can sts mons

**Servers with the Bug**
Mew

**Expected behavior**
You shouldnt be able sts mons in warzone

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/125178834-4a46a600-e1e0-11eb-87b9-70a272c26a56.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
