### ISSUE TITLE
Darkrai Safeplace not taking you back to spawn

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#361]
**Describe the Bug**

**To Reproduce**
1. Go to Darkrai
2.  Enter warzone and do /safeplace
3. Be teleported to random area

**Servers with the Bug**
Darkrai

**Expected behavior**
Be teleported back to spawn

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/125178878-a9a4b600-e1e0-11eb-9c10-b3424c53988a.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
