### ISSUE TITLE
blissey not learning teleport

### ISSUE THREAD

**Issue by slippysayjin** [SmashMC-Development/Bugs-and-Issues#363]
**Describe the Bug**
blissey doesnt learn teleport with /buymove or any other type of method 

**To Reproduce**
1. /buymove teleport 
2. try to choose blissey/chancey
3. fails

**Servers with the Bug**
Dialga but probably something around all servers
**Expected behavior**
i would like to see blissey learning teleport cuz of world cup

**Screenshots**
 'N/A'.

**Additional context**
 'N/A'.

**Comment by HackuJacku** [comment]
Not a bug, intended mechanic. Blissy learns Teleport through a transfered-move chansey.
