### ISSUE TITLE
Milcery /pwiki evolution info 

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#364]
The /pwiki info on milcery evolution is unnecessarily 'long'

1. Go to /pwiki milcery
2. Click on evolution
3. See bug

**Servers with the Bug**
Rayquaza, charizard, mew, dialga and palkia are servers I have checked. All had the 'issue' so I assume all other servers do. 

**Expected behavior**
I expected the info to be too long and it was.

**Screenshots**
![2021-07-11_21 39 56](https://user-images.githubusercontent.com/45851395/125208058-96512380-e290-11eb-803a-b06cfe89b5a9.png)
![2021-07-11_21 39 59](https://user-images.githubusercontent.com/45851395/125208065-a1a44f00-e290-11eb-8416-7c2a0faee0ed.png)

Helper who told me to report here when I made ticket said It's probably caused by milcery having colour variations.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
