### ISSUE TITLE
Losing Hunger in Darkrai Spawn

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#366]
**Describe the Bug**
You losing Hunger in Darkrai Spawn

**To Reproduce**
1. Go to Darkrai
2. Go to Spawn 
3. See Hunger Loss

**Servers with the Bug**
Darkrai

**Expected behavior**
Shouldnt lose hunger in spawn

**Screenshots**
![Inked2021-07-11_22 23 42_LI](https://user-images.githubusercontent.com/84816052/125210342-24300d00-e297-11eb-9420-c0b75e943ebc.jpg)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
@M1n0j - can you test this now please?

**Comment by M1n0j** [comment]
Ya seems to be fixed now. Thanks!
