### ISSUE TITLE
Galaxy crate giving the wrong legend

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#367]
**Describe the Bug**
If you open a galaxy crate and win a galaxy galarian moltres, it will give you a galaxy zygarde instead

**To Reproduce**
1. Go to /server mew
2. Open the galaxy crates until you get a galaxy galarian moltres
3. See error

**Servers with the Bug**
Mew

**Expected behavior**
It should give the Galaxy galarian moltres, not the galaxy zygarde

**Screenshots**
![2021-07-13_01 03 18](https://user-images.githubusercontent.com/83550357/125370689-51f08100-e37f-11eb-9255-85f545d1befd.png)

**Comment by Mikirae** [comment]
Fixed for next restart :)
