### ISSUE TITLE
Galexy zacian,calreyx, horses,  dosent show up in crate

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#369]
**Describe the Bug**
Galexy zacian dosent pop up in galexy crate on jirachi.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to /warp crates
2. Click on galaxy crate
3. click on all pages and zacian and the calreyx trio doesn't pop up (IDK if its actually gonna pop up)
4. And it doesn't pop up.

**Servers with the Bug**
Jirachi.

**Expected behavior**
Galexy zacian suppose to pop up.

**Screenshots**
I'N/A'.

**Additional context**
Can u check if its in the actual crate.

**Comment by HackuJacku** [comment]
Fixed, will be live soon.
