### ISSUE TITLE
Afk money

### ISSUE THREAD

**Issue by EnderGAmer417** [SmashMC-Development/Bugs-and-Issues#370]
So i went afk on a move  pad 2 hours later i come back and wake up with 668k then i but a 7k golden hourglass and all my money went away i did have 7k before the afk

**To reproduce
Go afk on a movement pad contraption 
Wait 2 hours
Get money
Buy something
All money goes away
Server mew,
Expected behavior still have money

**Comment by EnderGAmer417** [comment]
*buy a golden hourglass

**Comment by EnderGAmer417** [comment]
![20210714_123906](https://user-images.githubusercontent.com/87420686/125603683-784b0d11-23b3-40a7-831d-b5d9872a9496.jpg)

Bam proof

**Comment by EnderGAmer417** [comment]
So what do I do since i lost 688k?

**Comment by HackuJacku** [comment]
Not a bug, please create a ticket on our Discord.
