### ISSUE TITLE
Players are able to /nsuicide in warzone

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#371]
**Describe the Bug**
Players can easily get out of the warzone by using /nsuicide

**To Reproduce**
1. Go to /Warp warzone
2. Step on the pressure plate
3. Type /nsuicide

**Servers with the Bug**
Mew, kyogre, Jirachi, Deoxys, Darkrai, Palkia, Giratina, Dialga

**Expected behavior**
Players shouldn't be able to do the command and get out

**Screenshots**
https://user-images.githubusercontent.com/83550357/125717299-c174b432-affd-422a-8f90-24f12b90662b.mp4

**Comment by HackuJacku** [comment]
Fixed.
