### ISSUE TITLE
Players not receiving +10 boosts from Epic crates

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#372]
**Describe the Bug**
When a player opens the epic crate and wins a +10 boost or more than one, he will not receive it in his inventory

**To Reproduce**
1. Go to /Warp crates
2. Click on Epic crates to open them
3. Open until you receive the boosts

**Servers with the Bug**
Charizard, Rayquaza, Jirachi, Kyogre, these are the known ones for now

**Expected behavior**
Players should receive the papers from the crates

**Comment by Superfire96** [comment]
Update on this it isn't that the problem, the broadcast is saying the wrong thing in chat

**Comment by Mikirae** [comment]
Fixed on restart <3
