### ISSUE TITLE
Honedge evolves into mew

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#373]
**Describe the Bug**
My friend said in minigames, honedge evolves into mew

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to minigames
2. Go in-game
3. evolve honedge
4. U be a mew

**Servers with the Bug**
Minigames.

**Expected behavior**
u should be a doublade

**Screenshots**
'N/A'.

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
Fixed.
