### ISSUE TITLE
Raid Bosses healing themselves

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#374]
**Describe the Bug**
The raid bosses keep healing over and over due to them using a berry.
The Bosses are Snorlax, Sandaconda, Appletun, Kingler and Grimsnarl.

**To Reproduce**
1. Go to one of the raid bosses
2. Get it low 
3. It will heal

**Servers with the Bug**
Seen on Mew, Darkrai, Dialga, Kyogre and Jirachi. Probably all, but they just had different mons

**Expected behavior**
It shouldnt replenish its berry everytime its low 

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/126010375-e0a27ece-e84e-4873-b57c-2bb04d726eed.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
