### ISSUE TITLE
Your able use Natures Madness on raid boss

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#375]
**Describe the Bug**
You can use Nature Madness on the raid boss. This makes it too easy to kill as u make it go straight to 50% and get loads on damage.

**To Reproduce**
1. Go to a raid boss
2. Use natures madness
3. Get loads of damage and make it 50%

**Servers with the Bug**
All Pixelmon ones

**Expected behavior**
Shouldnt be able to use it as its too overpowered

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/126012848-0f7cf811-b92e-4d70-aa24-30a216d2abd7.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed.
