### ISSUE TITLE
Unable to list items / pokemons on Gts

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#378]
**Describe the Bug**
Players are unable to list items or pokemons in gts, when they click on "item" or "pokemon" it will just close the gui

**To Reproduce**
1. Type /gts
2. Click on "Sell a good"
3. Click Items or Pokemon

**Servers with the Bug**
Mew

**Expected behavior**
Players should be able to list items and pokemons on the gts

**Screenshots**
https://user-images.githubusercontent.com/83550357/126184583-d6f588be-8e03-4c87-96f2-0bc0850c11b6.mp4

**Comment by Mikirae** [comment]
This is currently fixed but keeps occurring because GTS hates us.
