### ISSUE TITLE
sts os broken in giratina

### ISSUE THREAD

**Issue by biggabage1** [SmashMC-Development/Bugs-and-Issues#379]
The sts prices ong giratina a way to low for legs it is 5k now
**To Reproduce**
1. /sts
2. random leg in your box 
3. sts price is 5k for legs 

**Servers with the Bug**
giratina so far i know of 
to sell for the price of 15 to 20k 

![image](https://user-images.githubusercontent.com/87669389/126210537-43a2ff0b-460d-494d-b265-cac9b2940385.png)
![image](https://user-images.githubusercontent.com/87669389/126210615-c33d4582-df8b-41d4-8714-f9e8926d762d.png)

If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by HackuJacku** [comment]
Fixed from next reboot.
