### ISSUE TITLE
Dungeons not working

### ISSUE THREAD

**Issue by Refsamaha** [SmashMC-Development/Bugs-and-Issues#380]
**Describe the Bug**
The challenge pokemon are disappearing and not allowing you to challenge them

**To Reproduce**
Try battling a challenging pokemon

**Servers with the Bug**
Charizard

**Expected behavior**
Expected to be able to challenge and battle the challenge pokemon 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Is this still occurring? This is the first I've heard of it.

**Comment by HackuJacku** [comment]
Fixed on reset
