### ISSUE TITLE
Chest Pet glitch Survival

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#381]
**Describe the Bug**
On the Survival server, the chest pet is deleting items as opposed to storing. 
**To Reproduce**
1. Get a chest pet
2. Place items in the chest pet
3. Exit out of the chest pet
4. Open the chest pet and see error that items are deleted

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival
**Expected behavior**
The chest pet is supposed to store items like a chest not delete them. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
https://youtu.be/67gsvrwsgBM

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by jahangir6969** [comment]
Can this be tested again.

**Comment by piplupqueenn** [comment]
> Can this be tested again.

https://youtu.be/RVUMp0UxX3A

**Comment by jahangir6969** [comment]
Old pet. Need replacing out with the new pets. Anyone with old pets will need to log an ticket to get one of the new pets.
