### ISSUE TITLE
Welcome message Mew but on the wrong server.

### ISSUE THREAD

**Issue by GalacticDamien** [SmashMC-Development/Bugs-and-Issues#382]
The Bug:
On the Charizard server today (07/22/2021) a welcoming message from the wrong server appeared. The welcoming message from Mew appeared instead of the Charizard one.

Servers with the Bug:
As far as I know only Charizard, however its possible other servers have this as well.

Expected behavior:
A welcome to charizard message rather than a welcome to mew message.

Screenshots:
See attachments

Additional context
N/A
![Welcome to mew](https://user-images.githubusercontent.com/87820179/126661492-abc0f7ba-7243-4361-ab40-3f70a071dc9a.png)

**Comment by Ryan1595** [comment]
This is happening on jirachi too
![2021-07-22_12 51 24](https://user-images.githubusercontent.com/84028511/126685841-131b9d0a-96d7-4867-bf85-790106b89385.png)

**Comment by HackuJacku** [comment]
Fixed.
