### ISSUE TITLE
Money dissapearing

### ISSUE THREAD

**Issue by 02Senpai** [SmashMC-Development/Bugs-and-Issues#383]
**Describe the Bug**
When i log into the game, my money from the hunt for Fearow disappeared.

**To Reproduce**

**Servers with the Bug**
Charizard

**Expected behavior**
I expected for my money to not dissaper-

**Screenshots**
N/A

**Additional context**
The money from the hunt was there for a few minutes. But after i logged out due to a lag in the game and re logged back in the server i had the same amount of money as when i didn't get payed for the hunt for Fearow.

**Comment by Superfire96** [comment]
Fixing the description of that, Once a player completes the hunt they receive the money, but once they log out, the money just disappear, happened on darkrai too

**Comment by Mikirae** [comment]
Fixed in the next server restart :)
