### ISSUE TITLE
Wrong sts price of eternatus

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#384]
**Describe the Bug**
When you try to sts a eternatus the money given are different from all the other legends

**To Reproduce**
1. Get the eternatus
2. Type /sts
3. Go over it or sell it

**Servers with the Bug**
Mew, Giratina

**Expected behavior**
I believe it should be like all the other legends

**Screenshots**
![image](https://user-images.githubusercontent.com/83550357/126818721-528cd80c-691c-4cd8-a27c-15f714dc7f1d.png)

**Comment by Superfire96** [comment]
Correcting the above, the issue happens with Zacian and Zamazenta too

**Comment by HackuJacku** [comment]
Fixed on reset
