### ISSUE TITLE
Boss Raid

### ISSUE THREAD

**Issue by dmed3** [SmashMC-Development/Bugs-and-Issues#385]
**Describe the Bug**
The 5pm boss raid (Grimmsnarl) spawned and multiple members in our server (Palkia) are attempting to fight it but it's moves are doing no damage to any of our pokemon and will heal to full health no matter how much damage it takes

**To Reproduce**
1. Go to Palkia
2. Throw Pokemon at the Boss Grimmsnarl
3. Attack

**Servers with the Bug**
Palkia

**Expected behavior**
Boss attacks us and deals damage as well as takes damage

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A 

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
Same as #374
