### ISSUE TITLE
Warzone battling after safeplace

### ISSUE THREAD

**Issue by adrian64536** [SmashMC-Development/Bugs-and-Issues#386]
[](https://youtu.be/rwkC9mcCZVA)**being battled by someone who has already ./safeplace, seems like they safeplace then throw their pokemon before or after they teleport and still engage in battle after the battle you then cannot steal pokemon as they are outside of warzone.**

**To Reproduce**
1. Go to warzone safe place just before a battle
2. Click on battle the person and finish
3. 3. cant steal pokemon

**Servers with the Bug**
i only know of this being on Dialga but thats the only server i play

**Expected behavior**
not being able to steal after battle

**Screenshots**
linked a video in which it happened
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Same as #112
