### ISSUE TITLE
Crates on Deoxys can't be opened and can't see the preview

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#387]
**Describe the Bug**
If you go to /Warp crates on Deoxys, you can clearly see that the crates do not even have the particles, when you right click or left click, nothing happens

**To Reproduce**
1. Go to /Warp crates
2. Click on any of the crates
3. See error

**Servers with the Bug**
Deoxys

**Expected behavior**
Players should be able to open and see the preview of the crates

**Screenshots**
![2021-07-24_02 54 21](https://user-images.githubusercontent.com/83550357/126852970-cdb247db-dbac-460b-9398-7f5294239f2c.png)

**Comment by Dxhcky** [comment]
Also no keys in /keys and no keys received from tournaments. All keys owned before this issue cannot be found

**Comment by HackuJacku** [comment]
Fixed.
