### ISSUE TITLE
Smeargle cannot Sketch "Magic Coat"

### ISSUE THREAD

**Issue by Left4HalfLife** [SmashMC-Development/Bugs-and-Issues#388]
**Describe the Bug**
Smeargle cannot use Sketch to copy Magic Coat.
According to: https://bulbapedia.bulbagarden.net/wiki/Sketch_(move)
![image](https://user-images.githubusercontent.com/23146177/126862214-48ebb393-900c-4e7f-bf66-e0e5b071a996.png)

Sketch is unaffected by Magic Coat.

**To Reproduce**
1. Pokemon uses Magic Coat
2. Smeargle uses Sketch
3. Magic Coat reflects the attack
4. Smeargle does not learn it, and is forced to struggle

**Servers with the Bug**
Pixelmon Jirachi
I assume it applies everywhere, as the same outcome occurs when tested in singleplayer.

**Expected behavior**
Sketch should copy Magic Coat for Smeargle to learn it permanently, and not get bounced back.

**Screenshots**
![image](https://user-images.githubusercontent.com/23146177/126862209-e2436bea-89bd-4231-9db1-bdb549dc493f.png)

**Additional context**
I was unable to think of any workaround to Sketch Magic Coat. There are workarounds for others such as Taunt using Mental Herb, but Taunt works as intended as Sketch is a status move. Magic Coat however should not bounce back Sketch.

**Comment by HackuJacku** [comment]
Reported to Pixelmon: https://pixelmonmod.com/tracker.php?p=2&t=16261
