### ISSUE TITLE
/craft in wz

### ISSUE THREAD

**Issue by Sslooshyy** [SmashMC-Development/Bugs-and-Issues#39]
**Describe the Bug**
/craft isn't disabled in wz on Darkrai

**To Reproduce**
Go to Darkrai's warzone and try to do /craft

**Servers with the Bug**
Darkrai

**Expected behavior**
/craft should be disabled

**Screenshots**

**Additional context**

**Comment by Shoji007** [comment]
@HackuJacku can confirm blocked on all servers now <3
