### ISSUE TITLE
First Aid Frustration (In WZ) 

### ISSUE THREAD

**Issue by FLalejandro** [SmashMC-Development/Bugs-and-Issues#390]
**Opening Note:** 

Before I start this off, I would like to claim that I was confused as to whether or not to make this a suggestion or report it as a bug. Ultimately, since it is inconvenient for players, I decided to report it as a bug. I am making this post due to my own observations and experience with the First Aid ability in the Warzone. 

**Description:**

The First Aid ability (Obtained through leveling up the Battling skill in /skills) is a feature that I have observed to cause more frustration rather than relief to players, especially in the warzone. While this problem stems from the much bigger issue of battles undergoing the infamous waiting glitch, this feature compounds frustration. 

First Aid is an ability that revives dead pokemon at the end of a battle. The following is a list of ways to activate this ability:
- Running From a Battle
- Losing a Battle
- Winning a Battle
- Forcefully Ending a Battle via Commands

Since this ability can be triggered by ending a battle through a command, this means that warzone battles where staff have to forcefully end a match due to waiting glitch will always trigger this ability, instantly reviving dead pokemon. Because of this, staff now have to enforce the rule to "sack dead pokemon" to resume the fight as fairly as possible. This now becomes an issue because of the RNG nature of pokemon. Players who have abilities that can negatively affect the attacker (such as Flame Body, Static, Aftermath, Iron Barbs, Tangling Hair, Effect Spore, etc) are immediately put in an advantageous position, as they now have a chance to "hax" the attacker who is FORCED to attack the pokemon that has to be sacked, thus initiating a chance for an ability (or item such as a rocky helmet) to proc and cause additional damage to the attacker during the sacking process. I will elaborate on this in the additional context section. 

**How To Reproduce This Behavior:**

1. Engage in a Warzone Battle, have both parties faint a couple of pokemon. 
2. Unexpected error occurs, which results in the infamous waiting glitch that plagues the server (I do not know the cause of this, I just know it happens when a pokemon faints, or when a pokemon is switching out.)
3. Follow the typical procedure to unstuck (Make a discord ticket and have a staff member end the battle)
4. First Aid ability procs, reviving all fainted mons
5. Proceed to sack dead pokemon (which is the standard procedure)
6. Continue the battle until it's over, if a waiting glitch occurs again, repeat steps 3-5. 

**Servers with the Bug**

I believe this is an issue that affects every Pixelmon server, however, the only server I am 100% confident that this affects is Kyogre. 

**Expected Behavior**

The expected behavior is that once a warzone battle is forcefully ended (via a command), First Aid will trigger and revive the dead mons for both parties. The players will then proceed to sack dead pokemon as instructed by staff (This is the usual procedure)

**Screenshots**

N/A

**Additional context**

I have two scenarios that actually took place on the Kyogre server which I will briefly explain. 

The First Scenario: 
An unfriendly warzone match between StuffedEmpanada (myself), and lebarnez.  
Lebarnez knocks out a Hippowdon, an essential mon to StuffedEmpanada's team as it sets up the sand. 
5 Turns of Sand continue, until it eventually ends, leaving StuffedEmpanada's Sand Rush Excadrill without the doubled speed. 
Excadrill KOs one of Lebarnez's mons, and the waiting glitch strikes. Both players sack dead mons, but since Hippowdon was reintroduced into the battle, the sand is back up for 8 more turns, allowing Excadrill to deal more damage with its doubled speed. 
StuffedEmpanada wins the battle due to Excadrill being able to abuse the reincarnated Hippowdon's sandstorm. 
*In this scenario, StuffedEmpanada clearly has a massive advantage due to the activation of the First Aid ability, as his sweeping mon now had less pokemon to deal with, and more sand turns to abuse.

The Second Scenario: 
An unfriendly warzone match between Yateezo and CarpalRobin8049. 
CarpalRobin8049 and Yateezo battle, knock a couple of mons out, and then are forced into a waiting glitch. 
Helper ends the stuck battle, thus triggering the First Aid ability.
Carpal uses a healthy Rillaboom to attack a dead Volcarona (which had to be sacked).
Upon contact, Rillaboom is burned by the already dead Volcarona's Flame Body ability, ultimately crippling a heavy-hitting Rillaboom during the sacking process. 
With Rillaboom burned, its damage is cut in half, Yateezo has a massive advantage now that Carpal can't dish out large chunks of damage with the Rillaboom. 
Yateezo wins the battle, and Carpal loses a mon. 
*In this scenario, a revived Volcarona's Flame Body ability changed the entire tide of the battle, when it wasn't supposed to be alive in the first place.

**Possible Solutions:** 

1. Fix the Waiting glitch - This will prevent the need for warzone battles to be ended forcefully via a command and saves everyone the frustration (players can continue seamless battles, and staff doesn't have to respond to tickets for stuck warzone battles). 
2. Disable the First Aid ability in Warzone - This will eliminate the sacking process and make it so that players can just continue the battle by sending out the mons they already had sent out. 
3. Remove the First Aid ability completely - If option 2 isn't possible, removing the First Aid ability will help solve this issue. First Aid has almost no benefit, as the revived mons only come back with a sliver of HP, still making them somewhat useless until the player heals.

**Comment by HackuJacku** [comment]
Being able to use First Aid in the Warzone was a bug. It's now fixed from the next reboot.
