### ISSUE TITLE
Received enchanted book without enchants from combat quest

### ISSUE THREAD

**Issue by Awlk** [SmashMC-Development/Bugs-and-Issues#391]
**Describe the Bug**
Combat quests give an enchanted book but without enchants.

**To Reproduce**
1. go to the combat quest tab in /quest
2. complete the quests that should give you enchanted books
3. look at the book your received, they don't have any enchantments

**Servers with the Bug**
Survival

**Expected behavior**
The books should have the proper enchantments on them

**Screenshots**
N/A

**Additional context**
Not sure if there is already a bug reported of this.

**Comment by jahangir6969** [comment]
@Awlk Need the quest number please.

**Comment by jahangir6969** [comment]
Issue has now been fixed.
