### ISSUE TITLE
vault in warzone

### ISSUE THREAD

**Issue by br183adl** [SmashMC-Development/Bugs-and-Issues#392]
**Describe the Bug**
you can open vaults in warzone as the command /vaults is not allowed but the command /vault still works

**To Reproduce**
1. got to warzone
2. use the command /vault
3. you will be able to bring illegal items in warzone

**Servers with the Bug**
kyogre, giratina these our the servers that I have access to vaults on I do not know the rest
**Expected behavior**
/vault command to be not allowed to be used
**Screenshots**
![2021-07-26_15 39 51](https://user-images.githubusercontent.com/84156993/127008034-91f42572-f621-43ae-b2c9-1e8f6db70498.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
