### ISSUE TITLE
No Vote Keys?

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#393]
**Describe the Bug**
It seems when people vote they do not always get a vote key

**To Reproduce**
1. /vote
2. Vote on site
3. Sometimes dont get key

**Servers with the Bug**
It seems several servers have this probel

**Expected behavior**
I expect a message to pop up in chat stating I have a key and when I check /keys for there to be a key.

**Screenshots**
N/A.

**Additional context**
N/A.

**Comment by HackuJacku** [comment]
Please provide us with all the information required - which server?

**Comment by Indorlan** [comment]
> Please provide us with all the information required - which server?

I voted on Rayquaza today, but I got msg from a player who apparently voted on 5 different servers and never got a key.

**Comment by HackuJacku** [comment]
After testing this myself and getting multiple other players to test this, we confirmed that everything is fine.
