### ISSUE TITLE
Darmanatan Zen mode dont work!!!

### ISSUE THREAD

**Issue by gusiong** [SmashMC-Development/Bugs-and-Issues#394]
**Describe the Bug**

**To Reproduce**
1. Go to 'fight a player'
2. Click on 'make your poke half heath or less'
3. Scroll down to 'ant zen mode did not work'

**Servers with the Bug**
Please provide a list of which servers have this bug.
im in dialga but i tink all server have this bug

**Expected behavior**
i expected to happen is the zen mode will work and my attack and speed boost
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![Screenshot (1147)](https://user-images.githubusercontent.com/75510544/127122432-374a49cd-edb7-4059-953a-c4d24b19f47e.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
i tink this is not the server but its the pixelmon bug

**Comment by gusiong** [comment]
hi

**Comment by HackuJacku** [comment]
Same as #299
