### ISSUE TITLE
wrong sts price

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#395]
**Describe the Bug**
The Bug is that the sts prices are wrong on Dialga. If u try to sts a legend it will go for 4K and if u try to sts an ultra beast it will go for around 2K. Now apparantly the prices on giratina were like this as well but they got changed according to the changelog.

**To Reproduce**
1. Have a legend/ultra beast in ur inventory
2. type /sts in chat
3. hover over the pokemon to look at their sts price
4. It wil show the sts price of the legend/ultra beast is super low.

**Servers with the Bug**
Dialga

**Expected behavior**
What was supposed to happen is when u try to /sts a legend/ultra beast is that a legend should go for like 12/15K and an ultra beast should go for around 6/8K. It was like this before but at some point it got changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/127205342-789f9d24-3590-4b53-893d-bafdb27fcd91.png)
![image](https://user-images.githubusercontent.com/87021826/127205394-8c39aa36-3709-48a2-9e72-1249a8f5e410.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed on reset
