### ISSUE TITLE
Dcgey has a duplication inventory glitch on Survival

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#396]
**Describe the Bug**
Whenever Dcgey logs back into the server, their inventory reverts back to the same specific items. Additionally, if she decides to put the items in her current inventory into a chest, for example, netherite armor, and she relogs, she gets 2 sets of netherite armor as the one from her inventory before relogging is still in the chest AND she has another set from her inventory reverting again after reloading (sorry this if this is a bit confusing)

**To Reproduce**
1. For Dcgey, she logs on and puts all items from her inv into a chest
2. Then she logs off
3. When she logs back on, all the items she had just put into a chest reappear in her inventory (her inventory reverts back to the same specific items each time she relogs)
4. Additionally, when she checks the chest she put her items in before logging off, the items are still in the chest, therefore they are duplicated. She could potentially make sets of netherite armor with this glitch if she wanted to. 

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival (only Dcgey has it as far as I know)

**Expected behavior**
When you make changes to your inventory, it is expected that the changes save. Her changes do not save upon relogging and her inventory reverts back to the same items. 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
https://youtu.be/6f-UbCdGIrY

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
Sorry if this was a bit confusing I can prob explain it better in a vc

**Comment by jahangir6969** [comment]
@piplupqueenn Please see if this still happens.

**Comment by piplupqueenn** [comment]
she'll test it tomorrow

**Comment by piplupqueenn** [comment]
This is fixed! Thank you Khan!!
