### ISSUE TITLE
My Xurkitree cant learn the move Tail Glow

### ISSUE THREAD

**Issue by GodGreninja** [SmashMC-Development/Bugs-and-Issues#397]
**Describe the Bug**
My Xurkitree on the mew server can't learn the move Tail Glow
**To Reproduce**
1. Go to '/warp mart'
2. Click on 'The move tutor or /buymove'
3. Scroll down to 'Where the moves start with T's (Like Tail Glow)'

**Servers with the Bug**
Please provide a list of which servers have this bug.
Mew

**Expected behavior**
Tail Glow added to the move tutor on the mew server
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by DragonBallBreakersRandomizer** [comment]
Weird, in SW and Sh it cant learn tail glow but in usul u can :https://pokemondb.net/pokedex/xurkitree

**Comment by GodGreninja** [comment]
Is this going to get fixed?

**Comment by HackuJacku** [comment]
Added to master ticket.

> Is this going to get fixed?
There is 55 issues open currently You need to be patient in the future.
