### ISSUE TITLE
The gts on charizard won’t let me sell things 

### ISSUE THREAD

**Issue by kvoid5166** [SmashMC-Development/Bugs-and-Issues#398]
@**Describe the Bug**
The gts on charizard won’t let me sell a pokemon or item
**To Reproduce**
1. I /gts
2. Click on sell a good and click on pokemon or item then it went to the movement  screen  

**Servers with the Bug**
Please provide a list of which servers have this bug.
Charizard
**Expected behavior**
The gts Sell won’t Work on charizard 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Unable to reproduce and does not occur.
