### ISSUE TITLE
Struggle after DMAX Move on Gar-Darmanitan

### ISSUE THREAD

**Issue by GoldenRage** [SmashMC-Development/Bugs-and-Issues#399]
**Describe the Bug**
If u DMAX and do Max. Hailstorm on the Gar-Darmanitan it going instant on Struggle with full PPs. 

**To Reproduce**
1. Get into a fight with DMAX and DMAX the Gar-Darmanitan .
2. Click on 'Max. Hailstorm' -> u need Icicle crash on it  
3. Attack the enemys Pokemon
4. See error u only got struggle left

**Servers with the Bug**
Only tested on Charizard Server

**Expected behavior**

**Screenshots**
N/A 

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Potentially fixed on reset
