### ISSUE TITLE
Players are able to enter warzone with no guard fissure Machamp

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Bugs-and-Issues#4]
**Describe the Bug**
People are able to enter warzone with no guard fissure Machamp

**To Reproduce**
1. Go to Warzone with a no guard fissure machamp

**Servers with the Bug**
Jirachi

**Expected behavior**
You should not be able to enter warzone with no guard fissure Machamp

**Comment by Adainish** [comment]
Should be fixed per next version

**Comment by HackuJacku** [comment]
@Lun17 - we've updated our Warzone plugin recently. Is this still occurring please?

**Comment by Lun17** [comment]
Can confirm it's fixed

Il ven 30 apr 2021, 19:56 HackoJacko ***@***.***> ha scritto:
