### ISSUE TITLE
/Warp hatch on Jirachi

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#400]
**Describe the Bug**
The warp location is in spawn for some reason.

**To Reproduce**
1. Go to Jirachi server
2. type /warp hatch
3. Proceed to be amazed

**Servers with the Bug**
JIrachi

**Expected behavior**
Well apparently Jirachi doesnt have Hatch so I assume same should happen as on charizard. Message saying it doesnt exist.

**Screenshots**
![2021-07-30_20 16 28](https://user-images.githubusercontent.com/45851395/127695483-8c34f5a6-0117-475e-bb2b-8a34322cb44e.png)

**Additional context**
N/A.

**Comment by HackuJacku** [comment]
Removed the warp until added.
