### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by DreadAqua** [SmashMC-Development/Bugs-and-Issues#401]
Usually, when you enter a village, you have the option to get quests from the villagers, and even if you don't get the quests right away you can wait for a few daylight cycles to get the quests. But in my recent experiences, no matter how long you wait (2+ hours for me) you won't get a single quest from the villagers. I have gone to multiple different villages to see if that was the issue, but they all seemed to have the same result. Please fix this bug as it makes the player experiences significantly more frustrating, especially with the newly added Dynamax feature.

**To Reproduce**
1. Go to a village on the Charizard server
2. Wait for as many daylight cycles as you want
3. Watch as you don't get a single quest

**Servers with the Bug**
Charizard

**Expected behavior**
I expect the villagers to give at least one quest after a few daylight cycles, like in singleplayer mode.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Not a bug. NPCs don't always give a quest, it's a percentage chance - RNG.
