### ISSUE TITLE
Rank upgrade didnt work

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#404]
**Describe the Bug**
This is to log a that rank upgrades might be bugged.

**To Reproduce**
1. Go to 'Palkia'
2. try to upgrade your rank to expert
3. and
4. it won't work and say something like theirs nothing to claim.

**Servers with the Bug**
Palkia I think.

**Expected behavior**
suppose to get rank upgrade.

**Screenshots**
.
![image](https://user-images.githubusercontent.com/84050975/127767977-8e849e5f-9b34-48ac-97ec-10d9a91db9a0.png)

**Additional context**
additional context is in ticket 31872.

**Comment by HackuJacku** [comment]
Unable to find the exact issue. We're working on replacing this plugin for a new, better version which fixes many issues.
