### ISSUE TITLE
Helper rank glitch my claiming ability

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#405]
**Describe the Bug**
When I got helper it said I can only have up to 3 claims, I can still tp to claims but if I delete one, its gone and I cant reclaim

**To Reproduce**
1. Go to Jirachi (server with bug)
2. Have helper, legend, master
3. try to make more than 3 claims
4. Cant make more than 3

**Servers with the Bug**
Jirachi.

**Expected behavior**
suppose to make more claims as much as my ranks allow.

**Screenshots**
https://media.discordapp.net/attachments/871260391462821999/871286448958099498/unknown.png?width=1074&height=104

**Additional context**
I have legend, master, gym leader on Jirachi.

**Comment by HackuJacku** [comment]
DM an admin/manager.
