### ISSUE TITLE
Glow not working in warzone

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#406]
**Describe the Bug**
When entering warzone without a glow already on they will be put on but with a 1 min timer after which the glow is removed.
Though it seems on some servers the timer does reset to 1 min and the glows do not dissapear.

**To Reproduce**
1. remove glow
2. /warp warzone
3. look at inv and see the timer for glow going down and not always reset.

**Servers with the Bug**
Rayquaza (on other servers players said a timer started but sometimes it reset and sometimes it didnt) 

**Expected behavior**
When entering warzone the glow should stay on while there and not turn off after a minute.

**Screenshots**
![2021-08-01_19 40 08](https://user-images.githubusercontent.com/45851395/127780390-87a4c040-c37a-4078-9f41-d74762fdabd6.png)
![2021-08-01_19 39 32](https://user-images.githubusercontent.com/45851395/127780394-d41786c5-033b-47ae-8e9f-d84b2453a80c.png)

**Additional context**
N/A.

**Comment by HackuJacku** [comment]
Unable to fix due to a vanilla glitch.
