### ISSUE TITLE
Claim update on survival causes farms to stop working and become lag machines

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#407]
**Describe the Bug**
The new claim update is causing the sheep not to burn the same and is causing lag. 
**To Reproduce**
See video 

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival
**Expected behavior**
Sheep are expected to burn and not stay there. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
https://youtu.be/5lAL-ZD3YJQ

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
Animal damage are now allowed in claims again.
