### ISSUE TITLE
When selling a Pokémon on GTS for a fixed price, there is a chance that you either don't receive money if said Pokémon was sold, or that you can't reclaim said Pokémon from the GTS Stash if it wasn't sold.

### ISSUE THREAD

**Issue by Siruppus** [SmashMC-Development/Bugs-and-Issues#408]
**Describe the Bug**
When you sell a Pokémon for a fixed price, there is apparently a chance that you either don't receive the money if said Pokémon was sold, or that you can't reclaim said Pokémon from the GTS Stash if it wasn't sold. The GTS Stash appears to be completely empty. It looks like the Pokémon was somehow deleted in GTS or you somehow didn't receive any coins in your account from a possible succesful sale.

**To Reproduce**
I honestly have no idea how this happened. It is a bug that I encountered accidentally. I'll describe every step I can remember. 
1. Type /gts in chat.
2. Put a Pokémon for sale (in this case a Moltres) on GTS and lower the minimum price. Set the duration time of the offer to 1 full day (24 hours).
3. You get an error that it has to be sold for at least the original minimum price (in this case 40.000 coins).
4. Put the same Pokémon for sale again, but don't lower the minimum price. Set the duration time of the offer to 1 full day.
5. A while later (a couple of hours in my case), put a second Pokémon up for sale (in this case a Palkia). Don't lower the minimum price (if I remember correctly) (in this case 35.000 coins). Set the duration time of the offer to 2 full days (48 hours).
6. You have now 2 active listings, in this case one for a Moltres for 24 hours and one for a Palkia for 48 hours.
7. Don't log in to Minecraft or SmashMC for a couple of days (preferably 3 days).
7. After these days, log in again. The two Pokémon you put up for sale can't be found anymore in GTS, not even in the GTS Stash for items that weren't sold in the restricted time. You also haven't received any money from possible succesful sales. These Pokémon can't be claimed from the GTS Stash, nor can't they be found in your party or PC. It seems like GTS either somehow deleted these Pokémon from existence or didn't put any coins in your account from a possible succesful sale.

**Servers with the Bug**
Currently this bug has only been encountered on the Charizard server.

**Expected behavior**
When I put these two Pokémon up for sale, I either expected to receive coins from succesful sales or the ability to reclaim unsold Pokémon from the GTS Stash. Neither of those two happened. I never had any issues with GTS before.

**Screenshots**
Moltres and Palkia can't be claimed in GTS.
![No Moltres or Palkia to claim in GTS](https://user-images.githubusercontent.com/88326766/127866942-e7371463-015a-4a8f-83a0-2e759b50f11f.png)
Account didn't receive any coins. The two Pokémon can't be found in your party as well.
![No received money](https://user-images.githubusercontent.com/88326766/127866956-a5096e36-5cdd-4fb8-9fec-18b6f1f65c41.png)
Both Palkia and Moltres can't be found in your PC or party.
![Palkia can't be found in PC](https://user-images.githubusercontent.com/88326766/127866971-1c5efc8e-2f41-440c-afb0-835ee577e06f.png)
![Moltres can't be found in PC](https://user-images.githubusercontent.com/88326766/127866976-7dc76de4-a128-4bb6-a448-ed1de087a45b.png)

**Additional context**
I made a ticket about this on the official Discord server of SmashMC. They are currently helping me further with the issue.

Edit: My problem was quickly dealt with and I got my lost Pokémon given back to me after sharing logs with a helper and the admin via the Discord ticket. Apparently during those days I was gone, a backup had to be restored as the entire database was corrupted. So it is possible some Pokémon were lost due to the corrupted database.

**Comment by Mikirae** [comment]
If I had to take a guess as to what happened here:
You said you haven't logged in in a few days, and that's about when I needed to restore a backup as the entire database corrupted. It was nearly 24 hours old so some Pokemon were definitely lost. You can definitely mention this in your ticket and the people in the Discord will assist you! :)

**Comment by HackuJacku** [comment]
Hi, please create a ticket if you lost anything :)
