### ISSUE TITLE
The sheep farm lag in Survival is still happening as some farms are still bugged

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#409]
**Describe the Bug**
Some of the sheep farms are still lag machines as some of the sheep aren't properly burning. 
**To Reproduce**
See wrayolis farm below

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival
**Expected behavior**
The sheep are expected to burn. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
https://youtu.be/tZ6yzy63tJc

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
Resolved. In correct perm.
