### ISSUE TITLE
Sell wand doesn't work with new claim update Survival

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#410]
**Describe the Bug**
When trying to use sell wand it goes into claim inspection mode instead of selling. 
**To Reproduce**
1. Go to chest full of sellable items
2. Hold a sell wand
3. Right click the chest with the sell wand

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival

**Expected behavior**
The sell wand is expected to sell all sellable items in a chest. 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
https://youtu.be/m00eTbyaW0c

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by jahangir6969** [comment]
@piplupqueenn can you try again please?

**Comment by piplupqueenn** [comment]
It just acts as a normal stick now it still doesn't sell.

**Comment by jahangir6969** [comment]
Not an issue with GD. The issue is when the stick/sellwand. Going into game mode c and back will break the sell wands as it. it does this as stop anyone with perms stop them duping them.
