### ISSUE TITLE
missing perms 

### ISSUE THREAD

**Issue by Awlk** [SmashMC-Development/Bugs-and-Issues#411]
**Describe the Bug**
Admin role don't have permission to use worldedit 

**To Reproduce**

**Servers with the Bug**
Survival

**Expected behavior**
Having permission again to use world edit

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
DM a manager.
