### ISSUE TITLE
Shadow Gliscor Normal Texture

### ISSUE THREAD

**Issue by Azpic** [SmashMC-Development/Bugs-and-Issues#412]
Shadow Gliscor Texture not working i have reloaded the texture pack restarted my game reinstalled latest versions of both the pack and texture pack
![Screenshot_1](https://user-images.githubusercontent.com/88426858/128145861-8e50f350-2b62-4f45-b31c-76c3baa2cdc9.png)

**Comment by HackuJacku** [comment]
Gliscor does not have a shadow texture. Please also follow the format provided in the future.
