### ISSUE TITLE
overdrive bug

### ISSUE THREAD

**Issue by theZhaZha** [SmashMC-Development/Bugs-and-Issues#413]
overdrive was supposed to be a sound based move, but it isnt in the game.
sound based moves bypass substitutes, but overdrive didnt bypass it. Throat chop makes the opponent not able to use sound based moves, but u can still use overdrive

**To Reproduce**
1. go battle
2. player 1 uses substitute/throat chop
3. player 2 uses overdrive
4. u dont bypass it/u can still use it

**Servers with the Bug**
pixelmon bug i think

**Expected behavior**
already mentioned

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed from next reboot.
