### ISSUE TITLE
Quest are not working for some people on Charizard

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#414]
**Describe the Bug**
Half the people on char say the quest don't work them.

**To Reproduce**
1. Go to 'Charizard
2. go to a village
3. Afk for awhile'
4. No quest

**Servers with the Bug**
Charizard

**Expected behavior**
everyone should be able to do the quest

**Screenshots**
![image](https://user-images.githubusercontent.com/84050975/128782874-e6e44e45-6855-4216-bd58-ac944540ecaf.png)
![image](https://user-images.githubusercontent.com/84050975/128782909-542e854c-0e6f-4d5e-8940-49b047eed1a8.png)

**Additional context**
Ticket 32654 .

**Comment by NightKnight-l** [comment]
I also tried visiting multiple villages multiple times and also haven’t seen any quests.

**Comment by HackuJacku** [comment]
Quests are not disabled. Some villages no longer function as villages due to their data being messed up in the Pixelmon 8.2 update, I am unable to fix this. This causes random locations to act like a village. 

NPCs are still able to spawn and have quests however.
