### ISSUE TITLE
Ultra Portals Glitch

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#415]
**Describe the Bug**
I can not open a US portal in Darkrai over world.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Darkrai
2. rtp
3. Throw out a lunala and try to make a portal
4. It won't let me make a portal

**Servers with the Bug**
Darkrai, I haven't tested it on other servers.

**Expected behavior**
Suppose to make a portal in the overworld to go to us.

**Screenshots**
![image](https://user-images.githubusercontent.com/84050975/128965655-02f9a0a5-2482-4cd8-9b49-d05d7871608b.png).

**Additional context**
Go to these quards incase, 
![image](https://user-images.githubusercontent.com/84050975/128965869-6d0be12c-523a-4044-9e90-9e87036d64db.png)
.

**Comment by DragonBallBreakersRandomizer** [comment]
Giratina too (ticket 32780)

**Comment by HackuJacku** [comment]
fixed
