### ISSUE TITLE
dungeon healer glitch

### ISSUE THREAD

**Issue by Tentamtene** [SmashMC-Development/Bugs-and-Issues#416]
**Describe the Bug**

**To Reproduce**
1. Go to /dungeons to the healer room
2. Click on healer
4. See error healer won't heal your party, if you try click again it will say your party has already been healed

**Servers with the Bug**
Please provide a list of which servers have this bug.
Mew
**Expected behavior**
Healer will heal your whole party
![glitch121](https://user-images.githubusercontent.com/86587039/129030063-6b59c355-955e-4aca-bc5b-8be4b579faab.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed on reset
