### ISSUE TITLE
Dungeon

### ISSUE THREAD

**Issue by YaBoiBlackGoku** [SmashMC-Development/Bugs-and-Issues#417]
**Describe the Bug**
I started a dungeon and when I was teleported I wasn't teleported to the dungeon I was tp'd to a mountain with nothing in my inventory and could not use commands

**To Reproduce**
1. do /dungeon
2. start dungeon
3. for me I was not teleported to the dungeon 

**Servers with the Bug**
Please provide a list of which servers have this bug.
Charizard

**Expected behavior**
Just a bug fix

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
<img width="1432" alt="Screen Shot 2021-08-11 at 11 36 23 AM" src="https://user-images.githubusercontent.com/88472520/129069854-69832c1d-f98f-4a81-a71b-800c06de63a0.png">

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
After the timer for the dungeon was over I was teleported back to spawn but I waited for 20 minutes

**Comment by HackuJacku** [comment]
Fixed on reset
