### ISSUE TITLE
Items disappearing from my inventory.

### ISSUE THREAD

**Issue by Dcgey** [SmashMC-Development/Bugs-and-Issues#419]
My trident randomly disappeared from my inventory whilst playing on my survival minecraft server on SmashMC, the issue has been resolved thanks to the staff team.

N/A, there are no Screenshots etc to go with this report sadly nor is there anything I can do to recreate this glitch / bug, my apologies.

**Comment by jahangir6969** [comment]
if you are unable to tell me the steps on how you lost your trident. there not much I can do to try to resolve the issue. So it does not happened again or it does not happened to other players. if you do found out what causes the bug that causes you to lose your trident. please open this ticket again or open an new ticket.
