### ISSUE TITLE
you can send pictures in certain discord chats

### ISSUE THREAD

**Issue by juanm7** [SmashMC-Development/Bugs-and-Issues#42]
**Describe the Bug**
you can send a picture in certain discord server chats

**To Reproduce**
1. Go to dialga, palkia, mew, survival, giratina, and darkrai discord channels
2. Click on the picture icon
3. Select a picture
4. you can see that it sends

**Servers with the Bug**
Please provide a list of which servers have this bug.
dialga discord channel, palkia discord channel, mew discord channel, survival discord channel, giratina discord channel, and darkrai discord channel, 
**Expected behavior**
remove the option to send pictures in these disc channels
**Screenshots**
![285CA5BB-03B6-4388-B2CF-FBC972E45465](https://user-images.githubusercontent.com/82734127/115652916-2fa91300-a2fc-11eb-87a5-10658b2cd7ef.png)
![90EB25FE-E8C1-4419-B762-BEC16D595F98](https://user-images.githubusercontent.com/82734127/115652919-3172d680-a2fc-11eb-8d3c-6fdfc68cf645.png)
![8E3E24B0-8982-4FC1-9162-DA6E27F2C0FC](https://user-images.githubusercontent.com/82734127/115652920-32a40380-a2fc-11eb-81b6-2d1d23465506.png)
![BF4DB5BC-02BC-4EAC-8CD7-F3CEE8786368](https://user-images.githubusercontent.com/82734127/115652921-33d53080-a2fc-11eb-8488-1bfc39404d6d.png)
![84579809-92FD-4C94-ACA9-8D7AECA68149](https://user-images.githubusercontent.com/82734127/115652926-346dc700-a2fc-11eb-89c8-7487f6aa81be.png)
![8A086158-7E55-4DBC-A041-AAF855825915](https://user-images.githubusercontent.com/82734127/115652933-359ef400-a2fc-11eb-81d0-6c3ed861578a.png)

**Additional context**

**Comment by HackuJacku** [comment]
@juanm7 - is this still possible please?

**Comment by Shoji007** [comment]
this is still possible in all the chats mentioned. it is also possible to send gifs this way as well via phone and pc

**Comment by Rasgnarok** [comment]
This is still possible because staff have permission to embed. I assume I can remove it, closing ticket.
