### ISSUE TITLE
Training skills 

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Bugs-and-Issues#420]
Ok so the bug is that some people dont get the xp boost from the training level like myself im 130+ and my friend who is 110 he gets 3.5k from each pokemon at ./training4 while im the higher level gets 1,2k xp avarage.
**To Reproduce**
1. Go to ./training1-4
2. Click on ko a pokemon 
3. Scroll down to see if u get the boosted xp
4. See error If u dont well then its broken

**Servers with the Bug**
Please provide a list of which servers have this bug.
Rayquaza but i dont know it can be other servers
**Expected behavior**
Well u should get the boosted xp but u dont it works for some and others it dont work for.
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
Made a ticket about it if its still there when they closed the ticket but a level 70 something got 2,5k xp and i got 1,2k
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
Fixed on reset
