### ISSUE TITLE
On Survival all ranks are deleting and getting set to Member 

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#421]
**Describe the Bug**
On Survival all ranks are deleting and getting set to Member. People including me have lost commands from ranks. 
**To Reproduce**
1. Go to Survival
2. See Member rank on everyone
**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival
**Expected behavior**
Ranks and commands should be the same as they were. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
Additionally, my Mod and Event-host perms are also gone as those ranks are gone. Also now everyone's names are gone.

**Comment by piplupqueenn** [comment]
> **Describe the Bug**
> A clear and concise description of what the bug is.
> On Survival all ranks are deleting and getting set to Member. People including me have lost commands from ranks.
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to Survival
> 2. See Member rank on everyone
>    **Servers with the Bug**
>    Please provide a list of which servers have this bug.
>    Survival
>    **Expected behavior**
>    A clear and concise description of what you expected to happen.
>    Ranks and commands should be the same as they were.
>    **Screenshots**
>    If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
> 
> **Additional context**
> Add any other context about the problem here. If nothing, please add 'N/A'.
> Additionally, my Mod and Event-host perms are also gone as those ranks are gone. Also now everyone's names are gone.


> **Describe the Bug**
> A clear and concise description of what the bug is.
> On Survival all ranks are deleting and getting set to Member. People including me have lost commands from ranks.
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to Survival
> 2. See Member rank on everyone
>    **Servers with the Bug**
>    Please provide a list of which servers have this bug.
>    Survival
>    **Expected behavior**
>    A clear and concise description of what you expected to happen.
>    Ranks and commands should be the same as they were.
>    **Screenshots**
>    If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
> 
> **Additional context**
> Add any other context about the problem here. If nothing, please add 'N/A'.
> Additionally, my Mod and Event-host perms are also gone as those ranks are gone. Also now everyone's names are gone.

Now all commands are gone

**Comment by jahangir6969** [comment]
Issue resolved. The issue was with the box. That @Mikirae resolved and I just taken the few files needed from LP and restore them back.
