### ISSUE TITLE
going into a jail when ur not supposed to

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#422]
**Describe the Bug**
if u go to /warp crates and hop on a pokemon that can fly. And then fly into the ceiling and then hop off then u can hop into a jail.

**To Reproduce**
1. go to /warp crates
2. hop on a pokemon that can fly
3. fly into the ceiling so that ur character is halfway into the ceiling but ur poke remains underneith the ceiling
4. Hop off while underneath a jail
5. u will be in a jail without being supposed to be there

**Servers with the Bug**
all servers

**Expected behavior**
Expected is not being able to go into a jail unless u have been jailed by a staff member

**Screenshots**
![proof](https://user-images.githubusercontent.com/87021826/129494172-460834fa-b97c-4e06-a27f-49cf9944ae81.PNG)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Unable to fix currently. Fixed in the future however.
