### ISSUE TITLE
Genesect Cant Learn Shift Gears

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#423]
**Describe the Bug**
Genesect Cant Learn Shift Gears and I've tried to find a way but it wont let me. Even tho on bulbapedia it says its a event move, it should still learn it

**To Reproduce**
1. Go to Server
2. Get a genesect
3. Go to /buymone (slot)
4. Gearshift wont popup

**Servers with the Bug**
I tried this on Jirachi.

**Expected behavior**
Genesect can learn gearshift.

**Screenshots**
'N/A'.

**Additional context**
https://bulbapedia.bulbagarden.net/wiki/Shift_Gear_(move).

**Comment by HackuJacku** [comment]
Added to master ticket.
