### ISSUE TITLE
Kyogre GTS isnt working

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#425]
**Describe the Bug**
Gts isn't working on Kyogre

**To Reproduce**
1. Go to Kyogre
2. type in /gts
3. See error

**Servers with the Bug**
Only Kyogre as far as i know

**Expected behavior**
what's supposed to happen is u are supposed to see the gts screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/129934428-3c8e3598-d462-4f59-a1f9-ba81ba61ef0f.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed from next reboot.
