### ISSUE TITLE
Shooting Star Quest unable to complete - Jirachi

### ISSUE THREAD

**Issue by NabilIssa22** [SmashMC-Development/Bugs-and-Issues#426]
After completing the requirements for the Shooting Star quest on the Jirachi server and going back to talk to the professor, I am unable to click thank you and accept the dynamax band. Clicking on thank you changes nothing, I've tried relogging and resetting Minecraft but the issue persists.

**Comment by NabilIssa22** [comment]
https://user-images.githubusercontent.com/89154926/129943115-fb1b3125-9000-4db9-b0d9-7b9de4c0763c.mp4

**Comment by NabilIssa22** [comment]
update: i think the npc is glithced, it gave me another quest while i still have the shooting star quest active which was to craft 5 level balls and i completed it but i can't give the npc the level balls to complete the quest
the same npc villager as the shooting star quest
![Screenshot (4)](https://user-images.githubusercontent.com/89154926/129944093-5228f7f5-8743-49f5-97e9-a6454246bdbd.png)

**Comment by HackuJacku** [comment]
Pixelmon bug. Please create a support ticket to be given the band itself.
