### ISSUE TITLE
lvl 150 mining skill doesnt work

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#427]
**Describe the Bug**
Explosive mining still causes the explosion but there is no damage to blocks

**Servers with the Bug**
Jirachi

**Expected behavior**
Explosion damages blocks

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed on reset
