### ISSUE TITLE
SmashTrivia not popping up

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#428]
**Describe the Bug**
SmashTrivia it's not working completely, doesn't even show up in chat

**To Reproduce**
1. Go to one of the servers i'll list under
2. Wait some minutes
3. See error

**Servers with the Bug**
Rayquaza, Mew, Jirachi, Deoxys, Palkia, Giratina, Dialga

**Expected behavior**
The SmashTrivia should work

**Comment by HackuJacku** [comment]
Fixed from next reboot.
