### ISSUE TITLE
Aqua Skills Vein Miner

### ISSUE THREAD

**Issue by Blxgdenn** [SmashMC-Development/Bugs-and-Issues#43]
**Describe the Bug**
When using vien miner skill, xp is not dropped from blocks that would usually give xp

**To Reproduce**
Use Vien miner on a block that gives xp

**Servers with the Bug**
Only seen this issue on Charizard

https://user-images.githubusercontent.com/83072886/115869643-14422300-a436-11eb-99c9-4e166c49077f.mp4

 but may be on other server due to it being a plugin

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by HackuJacku** [comment]
@Waterdude - does this sound like a bug or an intended feature? `redstone_ore` and `minecraft:lit_redstone_ore` are included in the list of args for the ability.

**Comment by HackuJacku** [comment]
Disabled the Vein Miner ability until it is fixed in AquaSkills.
