### ISSUE TITLE
Crashed well in warzone

### ISSUE THREAD

**Issue by Gaazz** [SmashMC-Development/Bugs-and-Issues#430]
**Describe the Bug**

I was in the warzone fighting a wild machoke. Caught it then I crashed but apparently, Andyque battled me at the same time which when I logged back in I was missing a pokemon they took. I have the log here, Doesn't show anywhere that I was battled.

**To Reproduce**

Honestly don't know how to reproduce it. Caught a pokemon then I crashed but was forced into a battle at the same time which I was forced to lose since I wasn't connected.

**Servers with the Bug**
Please provide a list of which servers have this bug.

Charizard

**Expected behavior**

Actually, be able to battle someone and have a chance without being forced to forfeit due to crash.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

![image](https://user-images.githubusercontent.com/37854778/130333361-ae1704e0-5ae9-4f73-8c60-7f689e7dd78c.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

[crash-2021-08-21_15.20.07-client.txt](https://github.com/SmashMC-Development/Bugs-and-Issues/files/7026116/crash-2021-08-21_15.20.07-client.txt)
[techniclauncher_2021-08-21.log](https://github.com/SmashMC-Development/Bugs-and-Issues/files/7026118/techniclauncher_2021-08-21.log)

**Comment by HackuJacku** [comment]
Please create a support ticket. This is not a bug,

**Comment by Gaazz** [comment]
Hey, sorry I was told by two support members in my ticket to make a bug report and they sent me that link to post it there.
