### ISSUE TITLE
/gyms visual issue

### ISSUE THREAD

**Issue by GalacticDamien** [SmashMC-Development/Bugs-and-Issues#431]
When using /gyms you can see that the Firegym and Normalgym have the same head multiple times in it.

1. Go to /gyms
2. Click on player gyms
3. Press either Firegym or Normalgym

I'm only aware of Charizard having this issue.

What I expect to happen is that the repeated heads get removed so it only shows 1 head per gymleader

**Screenshots**
![normalgym](https://user-images.githubusercontent.com/87820179/130337057-d211a766-7713-4e91-ae54-5e1eef631734.png)
![firegym](https://user-images.githubusercontent.com/87820179/130337058-11fe4b23-4765-45fc-9968-94c324d94adb.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed.
