### ISSUE TITLE
gymchat does not work

### ISSUE THREAD

**Issue by GalacticDamien** [SmashMC-Development/Bugs-and-Issues#432]
When you type in /gymchat it will show you ''No such channel''

**To Reproduce**
1. type /gymchat (message) in chat

**Servers with the Bug**
As far as I know only Charizard, but im only gymleader on there

**Expected behavior**
I expected my message to be sent to only the other gymleaders on the server.

**Screenshots**
![gymchat](https://user-images.githubusercontent.com/87820179/130337088-1cf7c035-6be6-4106-98f9-94f4764750be.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Not fixing as being removed/no one uses.
