### ISSUE TITLE
Wz /endbattle bug

### ISSUE THREAD

**Issue by DaKremit** [SmashMC-Development/Bugs-and-Issues#433]
**Describe the Bug**
Sometimes when I endbattle in the warzone with people, one of them gets booted and the other player gets to steal

**To Reproduce**
/endbattle (name)

**Servers with the Bug**
all of them

**Expected behavior**
i expected the battle to just end not for a player to get booted and stolen from

**Comment by HackuJacku** [comment]
Unable to reproduce - issue on client's end, not server's.
