### ISSUE TITLE
Npcs not giving money

### ISSUE THREAD

**Issue by AkiiMalice** [SmashMC-Development/Bugs-and-Issues#434]
**Describe the Bug**
The npcs arent giving money when i defeat them ( no not the ones that dont give money)

**To Reproduce**

**Servers with the Bug**
Charizard

**Expected behavior**
I expected it to give me money but it didnt

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Not a bug. Please read the Changelogs channel in our Discord.
