### ISSUE TITLE
No Red dye in the mart

### ISSUE THREAD

**Issue by Noctuel** [SmashMC-Development/Bugs-and-Issues#435]
**Describe the Bug**

We can't buy red dye in the mart

**Servers with the Bug**

At least Charizard

**Expected behavior**

Propose Red Dye to the player via the building block seller

**Screenshots**

N/A

**Additional context**

N/A

**Comment by HackuJacku** [comment]
Not a bug, suggestion. Please post on the correct repository in the future.
