### ISSUE TITLE
Disqualifying in Gyms not working (GYMS)

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#437]
**Describe the Bug**
If you disqualify someone from a Gym battle they get a 12 hour waiting timer.
**To Reproduce**
1. Go to Any Server
2. Challenge a Gym
3. Get Disqualified
4. Have a 12hour waiting time

**Servers with the Bug**
All

**Expected behavior**
Shouldnt have a 12hour timer.

**Screenshots**
https://youtu.be/mTSUk3gATAg

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Not a bug, intended feature - disqualification is the same as losing/it's negative.
