### ISSUE TITLE
Dhelmise cant learn Synthesis 

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#439]
**Describe the Bug**
Dhelmise cant learn Synthesis 

**To Reproduce**
1. Go to any server
2. Try learn Synthesis from /buymove and tutors
3. Says it cant learn

**Servers with the Bug**
All

**Expected behavior**
Should be able learn Synthesis. but due to pixelmon being in Gen 8 it cannot

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/130863716-21b69827-ed1b-4de5-bbb7-a9f422fb9219.png)
![image](https://user-images.githubusercontent.com/84816052/130863784-efc77b16-8e96-4269-aacb-23bd68d3cece.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Added to master ticket - use `/buymoves`
