### ISSUE TITLE
Dragonite cant learn Heal Bell

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#440]
**Describe the Bug**
Dragonite cant learn heal bell

**To Reproduce**
1. Go to any server
2. Try learn heal bell via /buymove or tutor move
3. Wont be able learn

**Servers with the Bug**
All

**Expected behavior**
Should be able learn heal bell

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/131158193-0d8509eb-3ec1-4568-9df2-cd379dcfbe95.png)
![2021-08-27_17 05 57](https://user-images.githubusercontent.com/84816052/131158207-81a1b2d1-22bb-4c44-a3e1-83238876fc1f.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Added to Master ticket - use `/buymoves`.
