### ISSUE TITLE
Buyclaim disabled

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#441]
/buyclaim disabled

Try and type /buyclaim

Survival

Should be able to buy claim blocks for 5 per block

N/A

**Comment by jahangir6969** [comment]
try to work out this issue. bit stuck on what causing it to be disable as it show it enabled on server side.

**Comment by jahangir6969** [comment]
Found the issue and resolved. To buy an block it will cost 150 and to sell it to the server it will cost 15
