### ISSUE TITLE
Venusaur unable to mega evolve

### ISSUE THREAD

**Issue by bboah** [SmashMC-Development/Bugs-and-Issues#443]
My venusaur is unable to mega evolve, it will do the animation but just wont evolve, I have a mega band equipped, and I can mega evolve my other pokemon, this one seems to not be working.

Umm you can just try to mega evolve my venusaur and it wont mega evolve.

it only seems to be this one pokemon that cant mega evolve 

**Expected behavior**
my pokemon to mega evolve

**Screenshots**
![Screenshot (153)](https://user-images.githubusercontent.com/89810111/131404094-e45e1251-7a4d-4f2e-942e-332c73fcbd26.png)

![Screenshot (154)](https://user-images.githubusercontent.com/89810111/131404229-0ba8c31d-a544-4b51-8556-c11cb5583ff5.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Potentially fixed on reset
