### ISSUE TITLE
when evolving g darumaka with ice stone i got fire darm and the fire darm learnt icicle crash

### ISSUE THREAD

**Issue by fellafine** [SmashMC-Development/Bugs-and-Issues#445]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Potentially fixed on reset
