### ISSUE TITLE
Nether Star not working in Lobby1

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#446]
**Describe the Bug**
Right click the Netherstar in Lobby 1 and u get an error message
**To Reproduce**
1. Join lobby 1
2. Right click the Netherstar
3. See error message and no GUI

**Servers with the Bug**
Lobby 1

**Expected behavior**
Should Open GUI and no Error message

**Screenshots**
![2021-09-01_21 03 31](https://user-images.githubusercontent.com/84816052/131737159-4bbd2d87-5a46-4a12-8b18-33d60e09440e.png)

**Additional context**
N/A

**Comment by jahangir6969** [comment]
Issue has been fixed.
