### ISSUE TITLE
Fall Damage in claims on Charizard

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#447]
**Describe the Bug**
If u jump off a pokemon while in the air u take fall damage if u land in a claim u own or are trusted in.

**To Reproduce**
1. Go to Charizard
2. Do /rtp and Fly up on a pokemon while in a claim u own or have trust in.
3. Jump off 
4. Fall to your death

**Servers with the Bug**
Charizard

**Expected behavior**
Shouldnt die of fall damage in claims

**Screenshots**
https://youtu.be/ZsWnt29ON7Q

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by M1n0j** [comment]
this was also tested in a Claim that is set to with subdivide

**Comment by HackuJacku** [comment]
Fixed on reset
