### ISSUE TITLE
Finished the dynamax band mission and it's not letting me claim it (done this 3 times already)

### ISSUE THREAD

**Issue by Choobyy** [SmashMC-Development/Bugs-and-Issues#448]
**Describe the Bug**
I recently got the Purple dynamax band mission, ive done everything it's asked me to do and then when i go to turn it in, it doesn't let me claim my dynamax band. I have video proof and all, please help..
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Rayquaza
**Expected behavior**
I expect to be given my dynamax band as I know gym-leaders are given this privelege due to the fact that theyre gym leaders. I did not earn that privelege, but I did work for it and completed ALL missions.
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![dmax](https://user-images.githubusercontent.com/89907322/131762389-bbcf0e53-bfdb-480a-97b0-9e37fdf660f6.png)
![dmax2](https://user-images.githubusercontent.com/89907322/131762394-67155f6d-fea9-49ae-8733-16e58c41815f.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
In addition, I do have video proof the files are too big apparently, i can either send them through discord or screenshare to prove, but being able to solve this for me would be greatly appreciated as i spent near 2 weeks finding this mission after attempting it the first time.

**Comment by Choobyy** [comment]
Also, i was told to come here to deal with my issue since i was banned from the smash discord 7-8 months ago. So i CAN NOT make a ticket.

**Comment by HackuJacku** [comment]
Potentially fixed on reset
