### ISSUE TITLE
Galarian Darmanitan ability bug

### ISSUE THREAD

**Issue by Restlezzz** [SmashMC-Development/Bugs-and-Issues#449]
**Describe the Bug**
Gorrilla Tactics not working properly on Darmanitan Galarian

**To Reproduce**
1. Battle with Galar darmanitan without choiced item
2. Select a move
3. You still can pick 3 other moves when you are supped to be locked to a move
4. Done

**Servers with the Bug**
All

**Expected behavior**
Galar Darmanitans are supposed to be choice locked because of its ability 
**Screenshots**
N/A
**Additional context**
N/A

**Comment by HackuJacku** [comment]
Potentially fixed on reset
