### ISSUE TITLE
Raid boss

### ISSUE THREAD

**Issue by Sslooshyy** [SmashMC-Development/Bugs-and-Issues#45]
**Describe the Bug**
The raid boss died in 5 seconds and the top player delt 29k damage with no ohko moves or anything out of the ordinary on his team
**To Reproduce**
Go to kyogre and wait for a raid boss
The player used flash cannon but I don't know if that has anything to do with it
**Servers with the Bug**
Kyogre
**Expected behavior**
You aren't supposed to one hit a raid boss

**Comment by HackuJacku** [comment]
Same as #21
