### ISSUE TITLE
Galar Corsola Cant Learn Wilo - Wisp form /buymove

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#450]
**Describe the Bug**
Galar Corsola cant learn wilo wisp from /buymove.

**To Reproduce**
1. Go to A server
2. Type /buymore Wilo Wisp
3. Hover over corsola
4. Cant Learn

**Servers with the Bug**
Jirachi (I cant test on other servers)

**Expected behavior**
corsola should learn will wisp

**Screenshots**
![image](https://user-images.githubusercontent.com/84050975/131823804-b0842fb9-7d8d-4589-82db-849df71c9bab.png)
![image](https://user-images.githubusercontent.com/84050975/131823889-bb8cafc0-7856-4feb-9b59-d6e66b9fdb48.png)

**Additional context**
Galar btw.

**Comment by HackuJacku** [comment]
Added to master ticket.
