### ISSUE TITLE
gts broken

### ISSUE THREAD

**Issue by br183adl** [SmashMC-Development/Bugs-and-Issues#451]
**Describe the Bug**
gts wont let you sell a pokemon

**To Reproduce**
1. use the command /gts
2. click sell a good
3. click pokemon
4. gts closes out

**Servers with the Bug**
rayquaza

**Expected behavior**
made so you can sell pokemon
**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed on reset
