### ISSUE TITLE
GTS not working

### ISSUE THREAD

**Issue by Srostron82** [SmashMC-Development/Bugs-and-Issues#452]
**Describe the Bug**
GTS is not working.  All areas are empty and stash gives an error.  If you try to add an item it gives an error.

**To Reproduce**
1. Go to /gts
2. Click on browser or view your listings
3. Nothing shows

1. Go to /GTS
2. Clock on sell a good
3. Click items or Pokemon
4. Select something to sell
5. Click confirm
6. Get error message

1. Go to /GTS
2. Click stash
3. Get fetch timed out error

**Servers with the Bug**
Mew

**Expected behavior**
When using GTS expect to see items for sale, my listings, see items that sold out did not sell in time limit, and be able to put items up for sale

**Screenshots**
![IMG_20210903_123905684_HDR](https://user-images.githubusercontent.com/87099722/132041210-92825317-5d63-490c-99a5-6dc3dfe0d322.jpg)
![IMG_20210903_123941466_HDR](https://user-images.githubusercontent.com/87099722/132041237-aef9b3be-cf85-4bad-88d9-b5699a382e83.jpg)
![IMG_20210903_124130447](https://user-images.githubusercontent.com/87099722/132041255-2d190029-505f-4020-a4d1-3b058ce19666.jpg)

**Comment by PretaxHP** [comment]
Same thing is happening for everyone

**Comment by HackuJacku** [comment]
Fixed on reset
