### ISSUE TITLE
Client crashing after catching in warzone

### ISSUE THREAD

**Issue by ehhhkody** [SmashMC-Development/Bugs-and-Issues#453]
**Describe the Bug**

When you have caught a pokemon, if someone battles you one the catch animation, you disconnect and they are able to take a pokemon from you without battling.

**To Reproduce**

1. Engage with a pokemon in warzone.
2. Catch the pokemon.
3. On catch animation someone battles you.
4. You disconnect and the client closes.

**Servers with the Bug**

I play on the Mew server.

**Comment by HackuJacku** [comment]
Potentially fixed on reset
