### ISSUE TITLE
Shadow tag doesn't work on Charizard

### ISSUE THREAD

**Issue by Kalegamer07** [SmashMC-Development/Bugs-and-Issues#456]
When Mega Gengar for example is in battle the opponent can switch out even though the Gengar has the ability Shadow Tag.

1. Go in wz and battle someone without using the shadow tag pokemon 
2. Switch your pokemon into Mega Gengar (it needs to be mega or mega in the turn after)
3. After the Gengar mega-evolves let the opponent switch into a other pokemon.
4. Opponent is able to switch while shadow tag in action.

**Servers with the Bug**
I know Charizard has this bug other servers N/A

**Expected behavior**
The opponent should not be able to switch if a Pokemon with Shadow Tag is in the battle. (for example Mega Gengar)

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Kalegamer07** [comment]
I'm not sure if this is only the case inside of warzone but I do know that this bug appears inside of warzone. (So also check if this is a complete server glitch)

**Comment by HackuJacku** [comment]
Potentially fixed on reset
