### ISSUE TITLE
legend rank but no more than 3 sethomes

### ISSUE THREAD

**Issue by fancyjumpin** [SmashMC-Development/Bugs-and-Issues#457]
**Describe the Bug**
i have purchased legend rank and im a pro in game and i have 3 homes made already, multiple thousand claim blocks available.  

**To Reproduce**
1. Go to new area and /sethome (town1) in my case
2. Click on N/A
3. Scroll down to N/A
4. See error : "you cannot set anymore homes you have hit your limit of 3 homes"

**Servers with the Bug**
jarachi

**Expected behavior**
i expect to get the total of 12 set homes it says with buying legend rank

**Screenshots**
N/A

**Additional context**
also being pro rank says access to 4 homes and im both legend and pro and it only says 3 homes in total

**Comment by HackuJacku** [comment]
Fixed on reset
