### ISSUE TITLE
Tournament Glitch

### ISSUE THREAD

**Issue by Thavlius** [SmashMC-Development/Bugs-and-Issues#458]
The glitch i'm talking about is a glitch that apen when you are in tourney and the other player that is supose to be in ball against you is in wz or other area where you can't get warped then the would never had been done so your pokemons will stay the same level and you would still be able to to battle with your under leveled or over leveled pokemons witch makes the battle unfair and that ruins the whole tournament witch is sad.

To Reproduce
1. join the tournament
2. go in warzone during tournament
3. And then u don't get to battle
4. There you go you have under or higher leveled pokemons

Servers with the Bug
I only play charizard so i only know that one

**Expected behavior**
i would suggest to always put a fonction that always put the pokemons at level 50

**Screenshots**
![image](https://user-images.githubusercontent.com/90204387/132237923-f4c4bbf9-d670-499c-9414-66a2fb7181e3.png)
that is a pickture took in tournament

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed on reset
