### ISSUE TITLE
Dungeon

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#459]
**Describe the Bug**
In the dungeon theirs some bugs, 

**To Reproduce**
1.U can use mega lucario and use uber megas.
2. u can fly in the dungeon
3. shiny bosses show in chat as engaged in battle
4. some items don't pop into  your invintory
**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**
These should be fixed

**Screenshots**
![image](https://user-images.githubusercontent.com/84050975/132267330-26e7821c-d4aa-4e0d-8ac2-b979047faeb9.png)
![image](https://user-images.githubusercontent.com/84050975/132267337-2b3525db-759d-4d58-ac8e-29b7f5843c1a.png)
![image](https://user-images.githubusercontent.com/84050975/132267581-e21631bb-0d5a-48e1-a926-5cf9d14317c7.png)
![image](https://user-images.githubusercontent.com/84050975/132267589-77ad3556-8280-45c7-ac8a-5fa600cb424d.png)

**Additional context**
'N/A'.

**Comment by Mikirae** [comment]
Did you check the pouch to see if the items were in there? Because they should appear in /dungeons pouch

The other stuff I'll check into. What server did this all happen on? I swear that I fixed the engaging shiny things before at the very least

Sorry I didn't reply earlier but I've been a busy boi <3

**Comment by DragonBallBreakersRandomizer** [comment]
> Did you check the pouch to see if the items were in there? Because they should appear in /dungeons pouch
> I didn't think this is a command
> The other stuff I'll check into. What server did this all happen on? I swear that I fixed the engaging shiny things before at the very least
> Jirachi, Its happens on some servers also but I cant remember which
> Sorry I didn't reply earlier but I've been a busy boi <3

**Comment by HackuJacku** [comment]
Fixed on reset
