### ISSUE TITLE
Charizard GTS cannot add Items/pokemon

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#460]
**Describe the Bug**
Cannot add listings to GTS

**To Reproduce**
1. Go to Chairzard
2. Do /gts
3. Try to sell an item or pokemon

**Servers with the Bug**
Charizard

**Expected behavior**
Should be able list items and pokemon

**Screenshots**
https://www.youtube.com/watch?v=Zjq9AM6x2Pc

**Additional context**
N/A

**Comment by Mikirae** [comment]
It looks to be fine right now
