### ISSUE TITLE
Dracovish Fisheous rend bug

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#461]
**Describe the Bug**
When you use fisheous rend, usually if you go last it still has 80 Bp, but in pixelmon it fails if moves last
**To Reproduce**
1. I don’t know how to fix this probably a bug in the code

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by DragonBallBreakersRandomizer** [comment]
Thats a pixelmon bug, Not server, report it to the official pixelmon bug tracker

**Comment by jahangir6969** [comment]
This has been fixed in 8.3 pixelmon.
