### ISSUE TITLE
raids are too hard

### ISSUE THREAD

**Issue by RicarloFrancis** [SmashMC-Development/Bugs-and-Issues#462]
FIX THE BOSS RAIDS
Mf has leftovers, if 5 ppl attack at once with super effective moves it does 1/10-1/12th of his hp MAX and leftovers heals that up like its nothing, fix this issue pls

**Comment by DragonBallBreakersRandomizer** [comment]
ngl it forces the whole server to work together

**Comment by HackuJacku** [comment]
Not a bug - post on the correct repository please. I will look into the held items though.
