### ISSUE TITLE
Challenges don't come through to leaders.

### ISSUE THREAD

**Issue by GalacticDamien** [SmashMC-Development/Bugs-and-Issues#463]
**Describe the Bug**
Whenever someone tries to challenge the gyms with /gyms it doesn't come through to the leader. When I am asked to accept the challenge it tells me I have none.

**To Reproduce**
1. /gyms
2. Playergyms
3. Gym you want to challenge
4. ''Join queue''
5. Nothing happens

**Servers with the Bug**
Charizard

**Expected behavior**
I expected that I would be challenged for a gymchallenges, however the plugin told me there were no challenges

**Screenshots**
![github](https://user-images.githubusercontent.com/87820179/132995134-c53e8bfc-2ffa-42a4-9c9a-9fdbcf966d74.png)

**Additional context**
As far as I know this was the case with the flying gym, Electric gym seems to be working perfectly fine. About any of the others I don't know because I haven't been challenged for these yet.

**Comment by HackuJacku** [comment]
Fixed on reset.
