### ISSUE TITLE
gym challenge bug

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#464]
**Describe the Bug**
You can accept your own gym challenges

**To Reproduce**
1. /gym or /gyms
2. join player queue
3. gym leader does accepts own challenge
4. pick mons from pc
5. stuck on team select menu

**Servers with the Bug**
Jirachi

**Expected behavior**
probably unable to accept your won challenge

![2021-09-13_20 30 00](https://user-images.githubusercontent.com/83971987/133144968-f01cbd50-c274-4cdf-80db-5af97eb96a9b.png)

**Comment by HackuJacku** [comment]
Potentially fixed
