### ISSUE TITLE
Shroomish cannot learn Spore

### ISSUE THREAD

**Issue by BigDiabetus** [SmashMC-Development/Bugs-and-Issues#467]
Despite shroomish being able to learn spore it cannot in the Smash MC server which greatly reduces its viability for being a great catch mon. 
Also pokemon with poison heal take damage from poison damage while out of battle which is not how that's intended. This is a big annoyance since if you want to run pokemon with poison heal you have to heal your team every battle you use them or they will faint by themselves while you walk.

**Comment by HackuJacku** [comment]
Added to master ticket.
