### ISSUE TITLE
Bingo Card reward not given to player, no compensation from mods/helpers either :(

### ISSUE THREAD

**Issue by forsakenspace1** [SmashMC-Development/Bugs-and-Issues#469]
**5x5 Bingo Card Reward Bug**
Item reward for fully completing a 5x5 Bingo Card not given to the 

player upon completing the card but the Pokécoins were added to the player's account 

**To Reproduce**
1. Catch all 25 Pokémon in a 5x5 Bingo card
2. Right click on Bingo card in item hotbar
3. Click on claim full reward on right side of menu
4. Only coin reward is received, not item reward

**Servers with the Bug**
SmashMC Mew Server

**Expected behavior**
Item reward to be given to player

**Screenshots**
https://imgur.com/a/4dWdjWt 
![bingo card](https://user-images.githubusercontent.com/90857689/133647598-9ca662d0-0220-4fc0-8c1e-b6703de00962.jpg)

**Additional context**
I grinded for 6 hours a day per week to finish this bingo card and after opening a ticket with the Helpers on discord, they told me they couldn't give me the item because I was not recording at the time. I don't usually record while playing and my device would not be able to anyways. I am really upset with this issue. No compensation also for my hard work gone

**Comment by HackuJacku** [comment]
Fixed. Please create a ticket in our Discord and we'll exchange the Master Ball for the Rusted Shield.
