### ISSUE TITLE
Lucario able to learn an egg move through the move tutor

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Bugs-and-Issues#47]
**Describe the Bug**
Lucario can learn an egg move through the move tutor 

**To Reproduce**
1. Go at the /warp mart second tutor with green hairs
3. Scroll down to the last moves, there's bullet punch and Lucario can learn it even if it's an egg move

**Servers with the Bug**
Everyone

**Expected behavior**
Lucario not being able to learn an egg move through the tutor

**Screenshots**
https://media.discordapp.net/attachments/828947882107207700/835483019275272222/unknown.png?width=886&height=498

**Comment by HackuJacku** [comment]
@Lun17 - this is a bug with the mod itself, it's already been reported and fixed in 8.2.
