### ISSUE TITLE
Warzone

### ISSUE THREAD

**Issue by ItsY4BoyJedi** [SmashMC-Development/Bugs-and-Issues#470]
**Describe the Bug**
There spawned 2 pokemon that i needed in warzone, Verry lucky u might say but no they weren't found not bc they despawned bc they where outside the barrier of warzone. 18:30 Europe time there spawned a Palkia and Latias and they where gone. 

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Giritina

**Expected behavior**
That the pokemon where found and captured so i could or catch them or buy them.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
Fixed in new Warzone version being developed.
