### ISSUE TITLE
Bingo Cards Reverted to maps

### ISSUE THREAD

**Issue by ViverrineOrb1** [SmashMC-Development/Bugs-and-Issues#471]
I right clicked my 5x5 and 3x3 bingo cards and they became regular maps

**To Reproduce**
1. have a bingo card in hand
2. right click on it
3. should turn into normal map named map #0

**Servers with the Bug**
I'm on the raquaza server

**Expected behavior**
i would just like the bingo cards back and hope that this gets fixed if its a server issue and not a client side issue

**Screenshots**
the screenshots will be of the maps in my hot-bar
![2021-09-19_14 00 06](https://user-images.githubusercontent.com/91027260/133937966-80945e7b-6d9e-4995-8dd4-af517d15fe37.png)
.
**Additional context**
n/a

**Comment by HackuJacku** [comment]
Potentially fixed on reset
