### ISSUE TITLE
Boats Won't Break

### ISSUE THREAD

**Issue by rawri16** [SmashMC-Development/Bugs-and-Issues#472]
When a player places a boat in water or on land, the boat cannot be broken. No matter if its empty handed, or with a tool, the boat remains unbroken.

**To Reproduce**
1. make a boat.
2. right click the boat on land or water.
3. try to break the boat by left clicking.
4. the boat doesn't break.

**Servers with the Bug**
Giratina

**Expected behavior**
I expected that left clicking the boat would make the boat rock then break, then go back to my inventory.

**Screenshots**
https://imgur.com/a/cmonpI3

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed on reset.
