### ISSUE TITLE
Breloom and shedninja

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#473]
**Describe the Bug**
Their is no way for breloom to learn spore with buymore and shedninja cant learn sword dance anyway (I did the evo thing and it doesn't work), can u add these options for them in /buymove

**To Reproduce**
1. Go to server
2. do /buy move (sword dance for shedninja), Spore for breloom)
3. nothing
**Servers with the Bug**
All ( I did it on jirachi)

**Expected behavior**
these mons should learn it

**Screenshots**
![image](https://user-images.githubusercontent.com/84050975/133960289-f0603dcc-d6b6-4618-9821-d021d3209303.png)
![image](https://user-images.githubusercontent.com/84050975/133960309-4650484c-4c9f-4a3b-b758-48dd408a1a27.png)
![image](https://user-images.githubusercontent.com/84050975/133960371-26c389b8-450a-4dd3-bbda-a7203259efde.png)

**Additional context**
makes getting shadow pokemon for these mons annoying as shadow shedninja cant learn sword dance and shadow breloom cant learn spore

**Comment by HackuJacku** [comment]
Potentially fixed on reset
