### ISSUE TITLE
Mon taking damage just by sending it out

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#474]
**Describe the Bug**
Whenever i sent out my pokemon, some of them takes damage just by existing on the field and not in battle.

**To Reproduce**
1. Just send out the pokemon

**Servers with the Bug**
Charizard

**Expected behavior**

**Screenshots**
N/A

**Additional context**
N/A

https://user-images.githubusercontent.com/77503363/134122687-0990eba0-e33d-482d-b6fe-bd2866308115.mp4

**Comment by HackuJacku** [comment]
Fixed on reset
