### ISSUE TITLE
Encountered Fatal Error Message while fighting wild mon in wz

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#475]
**Describe the Bug**
Received a Fatal Error Message in Charizard MC while fighting wild mon in wz

**To Reproduce**
N/A

**Servers with the Bug**
Charizard

**Expected behavior**
When i received that error message, it kicked me back to hub.

**Screenshots**
![image](https://user-images.githubusercontent.com/77503363/134315862-c45f9a68-a50a-463c-9d07-f78be5c0eb43.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
You'll need to provide exact steps to reproduce. This is a battle bug, they're very specific.
