### ISSUE TITLE
GTS is not working. Displaying empty listings for everyone

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#476]
**Describe the Bug**
GTS is not working. Displaying empty listings for everyone

**To Reproduce**
1. do /gts
2. go to browse items
3. the gts shows empty listings. No items on it

**Servers with the Bug**
Charizard

**Expected behavior**
gts will be empty

**Screenshots**
![image](https://user-images.githubusercontent.com/77503363/134324827-248c6d89-5f30-4634-891c-9181bb46e656.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
This seems to be fixed :)
