### ISSUE TITLE
Chat Color not Working with {item}

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#479]
**Describe the Bug**
When you show an item in chat if you have a chat color all text turns white.

**To Reproduce**
1. Go to Any Server
2. Turn on a chat color
3. Type in chat normally and see the color
4. Try show an Item and the chat color turns white.

**Servers with the Bug**
All

**Expected behavior**
Chat color should stay colored and not turn white

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/134740194-536ddbda-31ec-482e-8bc8-822659849d93.png)
![image](https://user-images.githubusercontent.com/84816052/134740229-689dafe8-d5f5-48cd-974c-39e7fa1f577e.png)
![image](https://user-images.githubusercontent.com/84816052/134740251-3c0afccc-51fc-4194-a8dd-49dc8f13a202.png)
**Additional context**
N/A

**Comment by HackuJacku** [comment]
Potentially fixed on reset
