### ISSUE TITLE
Double "Aqua" glows in /glowmenu

### ISSUE THREAD

**Issue by CaretsPuppy** [SmashMC-Development/Bugs-and-Issues#48]
**Describe the Bug**
There are two "Aqua" glows in /glowmenu, should there not be one blue one aqua?

**To Reproduce**
1. Go to '/glowmenu'
2. Hover over the colors
3. Look at names/icons
4. See two "Aqua" glows

**Servers with the Bug**
All

**Expected behavior**
Not two of the same named glows

**Screenshots**
Attached

**Additional context**
It just confuses players a lot, as two of the glows are basically the same, but when applied different? (??)
![aqua1](https://user-images.githubusercontent.com/82612312/115973062-3b8a1480-a54a-11eb-84ea-1062158b8e71.png)
![aqua2](https://user-images.githubusercontent.com/82612312/115973065-3dec6e80-a54a-11eb-9e72-e129c6fbf1a0.png)

**Comment by HackuJacku** [comment]
Fixed from next reboot - the wool colour appears the same but the title and lore are different. Also fixed a typo.
