### ISSUE TITLE
Rainbow texture for Milotic missing

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#480]
**Describe the Bug**
The rainbow texture for milotic is not showing after I used the rainbow wing on it.

**To Reproduce**
1. Throw out milotic
2. take the rainbow wing and right click the milotic
3. Now the milotic should appear with its rainbow texture but it doesn't

**Servers with the Bug**
Rayquaza

**Expected behavior**
I expect the milotic to appear with the rainbow texture after right clicking with the rainbow wing

**Screenshots**
![2021-09-25_17 42 38](https://user-images.githubusercontent.com/45851395/134777516-5693acfa-12e1-4d8f-92ff-496aee0e7d95.png)
![2021-09-25_17 42 46](https://user-images.githubusercontent.com/45851395/134777522-6ba6e711-6af8-4622-9763-5b291f0a812c.png)

**Additional context**
N/A.

**Comment by HackuJacku** [comment]
Shiny overrides CT. This is not a bug.
