### ISSUE TITLE
Grass blocks unable to spread to dirt blocks

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#481]
**Describe the Bug**
Grass blocks are unable to spread grass to dirt blocks turning them into grass blocks. 
Might be because grass spread is disabled or something.

**To Reproduce**
1. Create a platform full of dirt
2. Place grass blocks around it so that it can spread
3. Finally it doesn't spread even tho it has sufficient light

**Servers with the Bug**
Charizard

**Expected behavior**
The dirt blocks does not change into grass blocks even tho we had some placed near the dirt blocks.

**Screenshots**
![image](https://user-images.githubusercontent.com/77503363/134798123-c27982f6-4be3-4455-8cc1-2f0a44c92171.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed on reset
