### ISSUE TITLE
/skills disabled on charizard server

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#482]
**Describe the Bug**
On Charizard ./skills is still disabled. Why? On other servers, /skills is working perfectly fine

**To Reproduce**
1. Do ./skills
2. Suppose to show breeding, catching, fighting, killing, mining skills
3. See error

**Servers with the Bug**
Charizard

**Expected behavior**
Be able to see all my ./skills levels for breeding, catching, fighting, killing, mining skills

**Screenshots**
N/A

**Additional context**
N/A

**Comment by SilentOfChaos** [comment]
And also npc trainers on charizard not giving players the money.

**Comment by HackuJacku** [comment]
Fixed on reset.
