### ISSUE TITLE
Won't give keys after voting.

### ISSUE THREAD

**Issue by kurumagaming** [SmashMC-Development/Bugs-and-Issues#483]
**Describe the Bug**
After I vote it will tell me thanks for voting. When I enter the game it will not tell me a key has entered my key bag. I check and there is no key.

**To Reproduce**
1. Go to /vote
2. Click on Voting website
3. Vote and return to game

**Servers with the Bug**
Charizard

**Expected behavior**
I expected to get a key.

**Screenshots**

![image](https://user-images.githubusercontent.com/91842341/135763715-9300daf1-8afb-492d-a4c5-ca8adb3dad2f.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed on reset
