### ISSUE TITLE
Dailies quest bugged.

### ISSUE THREAD

**Issue by SoulessTears** [SmashMC-Development/Bugs-and-Issues#484]
**Describe the Bug**
Dailies quest which:
1.Catch 5 grass
2.Def 10 ground
3.Def 20 poke
Have few times the def 20 poke doesnt make any counts.

**To Reproduce**
I was just clearing dailies, follow which i need to do. Doesnt really has steps cause i just flew randomly till i met target poke.

**Servers with the Bug**
I was playin in server charizard.

**Expected behavior**
Was expecting the def 20 poke starts to count.

**Screenshots**
![123](https://user-images.githubusercontent.com/92185568/136624844-e0dbe5e6-2a42-46b7-9c55-3bb0636cf059.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed on reset
