### ISSUE TITLE
Chest Pets on Survival Eat Your Items

### ISSUE THREAD

**Issue by blaze6571** [SmashMC-Development/Bugs-and-Issues#485]
**Describe the Bug**
The Chest Pets on the Survival server will eat anything after the third item placed in them.
**To Reproduce**
Go to Survival server.
Open your chest pet. (Requires a specific rank)
Fill it with items.
Close the chest pet.
Reopen the chest pet.

**Servers with the Bug**
Survival
**Expected behavior**
When using the the chest pet, placing four or more items inside will cause the 4th item and everything after that to disappear when you reopen the chest pet.

**Screenshots**
![2021-10-13_09 36 27](https://user-images.githubusercontent.com/92552677/137402377-91d278c0-2f97-45ef-812d-372d22cbd1e8.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
This issue was resolved. seems like it was not closed down but you will need to get an new chest pet if your current one is still losing items.
