### ISSUE TITLE
Fix HA galarian darmanitan

### ISSUE THREAD

**Issue by Keone0** [SmashMC-Development/Bugs-and-Issues#486]
**Describe the Bug**
HA gdarm doesnt work, it never changes forms

**To Reproduce**
Use gdarm and see it doesnt work lol

**Servers with the Bug**
Prolly all

**Expected behavior**
Gdarm changes formes

**Screenshots**
NA

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Reported to Pixelmon.
