### ISSUE TITLE
Only 7 ranch blocks per

### ISSUE THREAD

**Issue by AliA234** [SmashMC-Development/Bugs-and-Issues#489]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Please fill out the format correctly, we have no what what the issue is. Think this is a suggestion so please post on the correct repo.
