### ISSUE TITLE
Staff has no tags / perms in lobby 3.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#49]
**Describe the Bug**
When you log onto lobby 3, staff doesn't have perms nor tags on said lobby. Lobby 1 and lobby 2 are good, so the issues lies solely in lobby3.

**To Reproduce**
1. Go to 'Lobby3'
2. Click on tab, staff shows as a player (no tags)

**Servers with the Bug**
Lobby3 in the hub

**Expected behavior**
Staff should have their respected tags in all lobbies of the hub.

**Screenshots**
![lobby 3 bug](https://user-images.githubusercontent.com/82727445/115973547-1f8c7000-a556-11eb-86dc-ec3e5efcf760.png)

**Comment by HackuJacku** [comment]
@LifelessDingus - I tested this yesterday and it seemed to be fine. Please can you check again and let me know?

**Comment by LifelessDingus** [comment]
Forgot to officially mention here: all good now, thanks! Report can be closed :)
