### ISSUE TITLE
Fall damage and PVP enabled

### ISSUE THREAD

**Issue by mnky-frt** [SmashMC-Development/Bugs-and-Issues#490]
**Describe the Bug**
title

**To Reproduce**
fall
have a player hit you

**Servers with the Bug**
reshiram

**Expected behavior**
before reset was not enabled

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
Fall damage is meant to be enabled, except at spawn. As for PVP, it is now disabled.
