### ISSUE TITLE
Rustles mod not enabled

### ISSUE THREAD

**Issue by mnky-frt** [SmashMC-Development/Bugs-and-Issues#491]
**Describe the Bug**
The sidemod 'Rustles' doesnt seem to be working: https://pixelmonmod.com/wiki/Rustles
Before reset it would have the text show up that a pokemon is nearby and particles would come up so you could catch it

**To Reproduce**
Wait in an area, the rustles text will not show up

**Servers with the Bug**
Reshiram, maybe all servers

**Expected behavior**
Rustles mod should be enabled, like it was before the reset

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
https://pixelmonmod.com/wiki/Rustles

**Comment by HackuJacku** [comment]
Rustles was removed on the reset.

**Comment by mnky-frt** [comment]
is there a reason why it was removed??

**Comment by mnky-frt** [comment]
> Rustles was removed on the reset.
