### ISSUE TITLE
didnt receive random non legend shiny

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#493]
**Describe the Bug**
When using vote crate keys on Reshiram i didnt get my reward of non legend random shiny.

**To Reproduce**
1. Go to warp crates
2. Click on vote crate
3. get non legend random shiny reward
4. non get non legend random shiny rewaerd

**Servers with the Bug**
Reshiram, possibly all

**Expected behavior**
Vote crates should give proper rewards

**Screenshots**
https://gyazo.com/b105f3a90b4d25742df8d67b648cea3a
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by mnky-frt** [comment]
This also happened to me

**Comment by jahangir6969** [comment]
![image](https://user-images.githubusercontent.com/59332632/148695342-84b3733c-b291-4874-8801-71ac22998df5.png)
![image](https://user-images.githubusercontent.com/59332632/148695347-1bff6605-056e-4054-9226-c687a370de87.png)

I have tested and have had a look in the backend and it seems to be giving out shiny pokemon. If it still not working please create an new issue or ticket on the discord and I will try to look more into it.
