### ISSUE TITLE
Megastone key not working

### ISSUE THREAD

**Issue by sirbarongallop** [SmashMC-Development/Bugs-and-Issues#494]
I used a vote key and got a mega stone key. 
 
**To Reproduce**
1. Go to 'Vote key'
2. Click on 'Vote'
3. Scroll down to 'get megastone key'
4. Try to use megastone key

**Servers with the Bug**
I was using Groudon.
**Expected behavior**
I expected to open the megastone crate

**Screenshots**
![2021-10-22_23 50 39](https://user-images.githubusercontent.com/93023060/138541730-87733ed8-822f-4d34-bceb-d6b230031048.png)
![2021-10-22_23 52 24](https://user-images.githubusercontent.com/93023060/138541732-34780e30-36c5-4a5f-8559-6f4bc5962191.png)

**Additional context**
N/A

**Comment by sirbarongallop** [comment]
Please dm me when fixed sirbarongallop#2156

**Comment by br183adl** [comment]
**Fixed this**
