### ISSUE TITLE
Schematica

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#495]
**Describe the Bug**
Can't join servers with Schematica 
**To Reproduce**
Try to join any server while using the Schematica modpack and it won't allow you to join.
**Servers with the Bug**
All pixelmon servers

**Expected behavior**
You should be able to join the server using schematica as it is allowed on the server.

**Comment by Rasgnarok** [comment]
Schematica is no longer allowed online.
