### ISSUE TITLE
Can't open Ultra portal

### ISSUE THREAD

**Issue by met21** [SmashMC-Development/Bugs-and-Issues#496]
**Describe the Bug**
When using the ability to open portals, the response "You are unable to use Open Wormhole in this world!"

**To Reproduce**
Try opening a portal.

**Servers with the Bug**
Zekrom as far as I'm aware

**Expected behavior**
It should open a portal in the air, does not.

**Screenshots**
![image](https://user-images.githubusercontent.com/84492278/138541828-6e89c083-e2d2-4f4e-972d-2f63160412d4.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed from the next reboot.
