### ISSUE TITLE
loss of money upon server restart and vote rewards not registering 

### ISSUE THREAD

**Issue by ElChulo076** [SmashMC-Development/Bugs-and-Issues#497]
**Describe the Bug**
It appears that I and a couple others upon restart in Zekrom lost all the money we had previously. 
Server restart was maybe 20 minutes ago and I had over 3k somewhere around 3000 to 3250. Also vote rewards for money don't appear to be registering I landed on the mythical 10,000 and it looks like it didn't register as at the time i still had around 1000

**To Reproduce**

**Servers with the Bug**
Appears only so far on Zekrom

**Expected behavior**

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Fixed vote rewards not applying properly. However, I can't speak for the client desync @HackuJacku

**Comment by HackuJacku** [comment]
FIxed
