### ISSUE TITLE
Enderchest Outside Reshiram Boss Tower isn't working

### ISSUE THREAD

**Issue by TheHumbleJames** [SmashMC-Development/Bugs-and-Issues#498]
**Describe the Bug**
The ender chest outside Reshiram boss tower doesn't open.

**To Reproduce**
1. Go to boss tower
2. Click on ender chest
3. See error

**Servers with the Bug**
Reshiram

**Expected behavior**
The ender chest to be usuable

**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
