### ISSUE TITLE
Didn't receive money

### ISSUE THREAD

**Issue by eYeek** [SmashMC-Development/Bugs-and-Issues#499]
**Describe the Bug**
/modpack gave me 4k but I didn't receive the money

**To Reproduce**
1. Go on technic launcher
2. Do /modpack
3. Get money

**Servers with the Bug**
All im assuming

**Expected behavior**
Get my money

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Fixed, thank you for your report!
