### ISSUE TITLE
Pokemon not sending out in /spawn (and area around)

### ISSUE THREAD

**Issue by CaretsPuppy** [SmashMC-Development/Bugs-and-Issues#5]
**Describe the Bug**
Pokeball going straight into ground and pokemon not being released from ball when R is pressed.

**To Reproduce**
1. Go to '/spawn, /warp mart, /warp heal etc'
2. Click on 'R'
3. Select either pokemon from your party and attempt to release using 'R'
4. See that the pokemon in these areas are not being sent out, rather pokeball goes through the ground

**Servers with the Bug**
Darkrai only (tested them all)

**Expected behavior**
When R is pressed the selected pokemon should release from their pokeball.

**Screenshots**
Not applicable, just shows "(name) has been sent out" without it being sent out

**Additional context**
Not sure why it's only spawn and the areas surrounding it causing this issue, other servers seem to be fine with it.

**Comment by HackuJacku** [comment]
Fixed now.
