### ISSUE TITLE
Healers at /warp training1-4 and /Warp evs do not work on Rayquaza

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#50]
**Describe the Bug**
The healers at /warp training1-4 and /warp evs cannot be used.

**To Reproduce**
1. Go to '/warp evs or /warp training1-4'
2. Right click the healers to use them
4. Nothing happens

**Servers with the Bug**
Rayquaza (tested all servers, they're all good besides Rayquaza)

**Expected behavior**
When you right click the healers at these public warps (/warp evs & /Warp training1, /Warp training2, /Warp training3 and /Warp training4), they should heal your pokemon.

**Screenshots**
![broken healer](https://user-images.githubusercontent.com/82727445/115974663-78600680-a55e-11eb-9efe-3fd699bb7cb2.png)

**Comment by HackuJacku** [comment]
@Rasgnarok - will you be able to take a look at this for me please as you're working in the GD setup?

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Bugs-and-Issues/issues/35

**Comment by Rasgnarok** [comment]
Not a GD issue, it's clear. Looks to be Wing's plugins.

**Comment by Rasgnarok** [comment]
Fixed with SMD-1.0.8.jar
