### ISSUE TITLE
skill advancements not hiding

### ISSUE THREAD

**Issue by myballsaresweaty** [SmashMC-Development/Bugs-and-Issues#501]
**Describe the Bug**
so basically if you want a skill to not show above the hotbar, there's an option in the /skills menu, only it isn't working. when i disable it, it just immediately turns back on when i close the menu. it's really annoying because it plays the xp sound every time you gain skill xp, which is every time you break wood or stone, craft, or jump. if you can't fix this could you at least remove the sound

**To Reproduce**
1. do /skills
2. go to any skill, acrobatics is the most annoying
3. the first option is "showing above hotbar" which should be toggleable but always turns back on after closing the menu

**Servers with the Bug**
i dunno probably all of them, i'm on zekrom

**Expected behavior**
you should be able to toggle whether the skill appears whenever you get xp for it

**Screenshots**
![image](https://user-images.githubusercontent.com/93023893/138542450-9cd7e70c-e2ec-4313-b5f8-57b807ba5bd3.png)

**Additional context**
n/a

**Comment by Superfire96** [comment]
Fixed
