### ISSUE TITLE
Ultra Space generation Issues

### ISSUE THREAD

**Issue by DaedricWaffles** [SmashMC-Development/Bugs-and-Issues#502]
**Describe the Bug**
Ultra space multiple biome generation issues and end city generation issues

**To Reproduce**
1. Go to Ultra space, go to ForestHills or Jungle [Current observed issue biomes] or a End City
2. Look around

**Servers with the Bug**
Presumably its on all servers

**Expected behavior**
Usual generation.

**Screenshots**

**Additional context**
The biomes Jungle/JungleM/ForestHills have invisible generated multiblocks such as Mossrocks and etc. that spawn as a invisible block.
Mball loot treet grotto spawns make other entities drop, this has happend in all versions so ignore it.*

End Cities generate with all of its banners, ladder,chest broken and on the ground.

![asdasassaas](https://user-images.githubusercontent.com/93023375/138542489-b9d2eaf9-71ce-4785-b72f-a95e766c4e4c.png)
![asdfasdasd](https://user-images.githubusercontent.com/93023375/138542490-bfd1b453-1105-42d1-b3dc-d173b072da82.png)

**Comment by DaedricWaffles** [comment]
The invis generation in forest hills is 90% the berry plants.

**Comment by ColonCrusader** [comment]
Also, don’t know if it’s intended, but everywhere I go in ultra space there is mail boxes randomly on the ground

**Comment by HackuJacku** [comment]
Vanilla generation issue.
