### ISSUE TITLE
HP EV training area drops items on death

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#503]
**Describe the Bug**
In groudon server, the pokemons drops items on death.

**To Reproduce**
1. Go to ./warp ev
2. Kill mons in HP Area
3. it drops items

**Servers with the Bug**
Groudon

**Expected behavior**

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jantjewieger** [comment]
Also an issue on reshiram

**Comment by Mikirae** [comment]
Is this with just HP or all of them?

**Comment by br183adl** [comment]
fixed the groudon spawner waiting for a response on the reshiram

**Comment by HackuJacku** [comment]
Confirmed fix
