### ISSUE TITLE
GTS minimum pricing for all Poke 10K

### ISSUE THREAD

**Issue by DaedricWaffles** [SmashMC-Development/Bugs-and-Issues#504]
**Describe the Bug**
GTS has standard Minimum price of 10K on all pokemon

**To Reproduce**
1. Go to /gts
2. Click on Wichever pokemon
3. Look at the minimum price

**Servers with the Bug**
Presumably all servers

**Expected behavior**
Variable minimum pricing on all pokemon.

**Screenshots**
![asdfasdfasddfssdf](https://user-images.githubusercontent.com/93023375/138542942-f22e634e-376d-4bae-b288-388873cc6247.png)

**Additional context**
Can not be decreased in the menu obviously due to it's set Minimum pricing.

**Comment by HackuJacku** [comment]
Not a bug, intended.
