### ISSUE TITLE
Mon unbreedable and unreadable after sent to other player

### ISSUE THREAD

**Issue by Keone0** [SmashMC-Development/Bugs-and-Issues#506]
**Describe the Bug**
Sent friend a mon and now it is unreadable and unbreedable

**To Reproduce**
/pokesell user slot
try to sell mon
see untradable 
**Servers with the Bug**
Ray might be others

**Expected behavior**
Be tradable and breedable

**Comment by HackuJacku** [comment]
Fixed. Please create a ticket if you need pokémon made tradeable or breedable.
