### ISSUE TITLE
Gts visual glitch

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#507]
**Describe the Bug**
When on kyogre and looking at selling a pokemon on gts for all pokemon it says Breedable: False but they can be bred. So just a visual glitch with gts
**To Reproduce**
1. Do /gts
2. Hover over a pokemon and will say Breedable: False even though you can breed them

**Servers with the Bug**
Kyogre from what I know

**Expected behavior**
Should say true for breedable pokemon and false for unbreeds

**Comment by HackuJacku** [comment]
Forward to the developer. Please keep an eye on #changelog in our Discord to see when this is fixed.
