### ISSUE TITLE
Unbreed command

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#508]
**Describe the Bug**
The /unbreed command does not exist 

**To Reproduce**
1. Try and run the command /unbreed and says Unknown command

**Servers with the Bug**
Kyogre all I know of

**Expected behavior**
Should change the pokemon between unbreedable and breedable

**Comment by HackuJacku** [comment]
It was removed. If a Pokémon is unbreedable, it's been made that by the server or a manager on purpose.
