### ISSUE TITLE
glow turns itself off in wz

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#51]
**Describe the Bug**
when u go to wz, ur glow automatically gets turned on. but after a minute or so, it just turns itself off

**To Reproduce**
go to wz (glows gets automatically equiped), chill for a while, then see ur glow suddenly being dissapeared

**Servers with the Bug**
was reported on kyogre

**Expected behavior**
glow should stay on as long as ur in wz

**Comment by HackuJacku** [comment]
Same as #75 - will be addressed in the re-write of Warzone.
