### ISSUE TITLE
./sts is not working 

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#510]
**Describe the Bug**
/sts is not working 

**To Reproduce**
1. go to groudon
2. type ./sts
3. and it wont work

**Servers with the Bug**
Groudon

**Expected behavior**

**Screenshots**
n/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Intended. It was removed to a duplication glitch which is out of our hands, will be added back along with a new GTS once fixed.
