### ISSUE TITLE
Bottle Caps

### ISSUE THREAD

**Issue by uglyemo** [SmashMC-Development/Bugs-and-Issues#512]
**Describe the Bug**
Not a bug but I was suggested by a mod that I report this, you could get BP of any mon too easily, ruins your IVS Boost in-game because this is the same thing except free, The items are "Silver Bottle Cap" and "Gold bottle cap" you can get them from the new raids that where added. Suggest you remove this because itll ruin your server and everyone will have BP of whatever they want lol.

**Comment by Rasgnarok** [comment]
It's now removed, thanks.
