### ISSUE TITLE
Zekrom has rayquaza E4

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#514]
When trying to test the e4 mechanic it said that zekrom has rayquazas e4 types 
To Reproduce**
1. Go to /gyms
2. Click on e4 
3. Scroll down to it’ll show rAyquazas gym types 

**Servers with the Bug**
All I know of is zekrom having this problem 

**Expected behavior**
For zekrom to have zekroms types 

**Screenshots**

**Additional context**

**Comment by HackuJacku** [comment]
Fixed
