### ISSUE TITLE
E4 members have the tag on every server 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#515]
**Describe the Bug**
I have the E4 tag on every server

**To Reproduce**
When I type it’ll show the elite four tag 

**Servers with the Bug**
All

**Expected behavior**
I should only have e4 on gira I believe 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Intended - DM Ras
