### ISSUE TITLE
You can spam /rtp

### ISSUE THREAD

**Issue by Itslyr1cal** [SmashMC-Development/Bugs-and-Issues#516]
there in no cooldown on the command /rtp
it basically means you can teleport around the map with no cooldown
**To Reproduce**
do /rtp
copy it
paste it
and spam

every server
zekrom, rayquaza, groudon, kyogre, reshiram, kyurem

**Expected behavior**
i was expected to see a cooldown but i was able to just spam /rtp
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
Fixed after the next reboot.
