### ISSUE TITLE
/skills broken

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#519]
**Describe the Bug**
/skills command doesnt work

**To Reproduce**
/skills in chat

**Servers with the Bug**
Reshiram for sure(probably all)
**Expected behavior**
skills menu should pop up

**Screenshots**
NA

**Additional context**
NA

**Comment by Mikirae** [comment]
I put it in for next restart. I think when I was updating the file I forgot to upload it after deleting. Sorry about that and thank you for reporting! :)
