### ISSUE TITLE
external moves potentially being disabled

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#52]
**Describe the Bug**
look into whether or not forage/headbutt are enabled or not, cause u need either or to get galarica twigs (which u need to craft a galarica cuff, to evolve galarian slowpoke)

(ras asked me to report this)

**Comment by HackuJacku** [comment]
@Bruhbert1999 - Enabled Forage. Headbutt was already enabled according to the plugin. Can you check this after the next reboot please?

**Comment by HackuJacku** [comment]
Tested and Forage is working.
