### ISSUE TITLE
no cooldown for rtp

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#520]
**Describe the Bug**
I can do /rtp as many times as i want with no cooldown

**To Reproduce**
/rtp

**Servers with the Bug**
Reshiram (probably all)

**Expected behavior**
i expected a cooldown on /rtp

**Screenshots**
NA

**Additional context**
NA

**Comment by HackuJacku** [comment]
Added after the next restart.
