### ISSUE TITLE
/warp training not working on zekrom

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#521]
**Describe the Bug**
not being able to use /warp training on zekrom server

**To Reproduce**
1. Go to zekrom.
2. try /warp training.
3. You can get to it
**Servers with the Bug**
tested on all servers, only zekrom is bugged

**Expected behavior**
you get teleported to the training are

**Screenshots**
![2021-10-23_09 00 09](https://user-images.githubusercontent.com/83245837/138561544-e7a1ae85-0fd6-4be8-80e8-da7efccabbe9.png)

**Comment by HackuJacku** [comment]
Fixed.
