### ISSUE TITLE
Gym NPC Battle Errors

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#522]
**Describe the Bug**
Whenever someone tries to fight a gym npc they get kicked out and pulled back in battle the when choosing a move.

**To Reproduce**
1. engage a gym npc
2. Try and select a move

**Servers with the Bug**
All servers as far as I'm aware.

**Expected behavior**
What should happen is that choosing a move should not kick the player out and pull them back in.

**Screenshots**
![image](https://user-images.githubusercontent.com/45851395/138563430-3936cf66-2be4-4987-a791-6763aa54c71d.png)

**Additional context**
N/A.

**Comment by ColonCrusader** [comment]
I have the same issue with gyms on reshiram, I tried to battle a gym leader and couldn’t even engage

**Comment by HackuJacku** [comment]
Pixelmon Battle Glitch. Forwarded to Pixelmon.
