### ISSUE TITLE
Issues with commands

### ISSUE THREAD

**Issue by Restlezzz** [SmashMC-Development/Bugs-and-Issues#523]
**Describe the Bug**
Unable to use /pokeheal, /redeem gui, /pokenick and /link

**To Reproduce**

**Servers with the Bug**
all

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
In what world were you in?

**Comment by HackuJacku** [comment]
Fixed
