### ISSUE TITLE
unable to force battle people in warzone

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#524]
**Describe the Bug**
When you throw your pokeball at someone to attack them it doesn't force you into battle
**To Reproduce**
1. Go to 'Warzone
try to throw your pokeball at someone to attack them
4. see your unable to force into a battle

**Servers with the Bug**im only able to test on kyurem, so kyurem for sure don't know bout the ret
**Expected behavior**Force you and other player to battle, not let them run away

**Screenshots**
not able to get a screenshot at this time

**Comment by HackuJacku** [comment]
Fixed
