### ISSUE TITLE
wrong spawnpoint?

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#525]
**Describe the Bug**
Whenever the server is restarted it teleports you back to spawn instead of where you where when the restart happened.

**To Reproduce**
-Go anywhere in any of the worlds
- Let a manager restart the server
- Get teleported to spawn automaticcaly regardless of where you were.

**Servers with the Bug**
Reshiram (but probably all)

**Expected behavior**
What is expected is to be teleported back to where you where when the server restarted. (underground in my mineshaft for example)

**Screenshots**
NA

**Additional context**
NA

**Comment by HackuJacku** [comment]
Fixed
