### ISSUE TITLE
Tournament crashes server

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#526]
**Describe the Bug**
Whenever a tournament starts, regardless of how many players are in the tournament, it crashes the server

**To Reproduce**
-Let a tournament create
-Join said tournament
-once tournament starts the server crashes

**Servers with the Bug**
Reshiram

**Expected behavior**
A tournament is supposed to start that doesnt crash the server

**Screenshots**
NA

**Additional context**
NA

**Comment by HackuJacku** [comment]
Fixed
