### ISSUE TITLE
Cant force battle players in warzone

### ISSUE THREAD

**Issue by CardStatue** [SmashMC-Development/Bugs-and-Issues#527]
**Describe the Bug**
When i try to battle a player in warzone I  cant force battle them
**To Reproduce**
1. Go to '...Warzone'
2. Click on '...Warzone.'
3. Try to battle a player

**Servers with the Bug**
Please provide a list of which servers have this bug.
Rayquaza, Kyurem , Reshi
**Expected behavior**
A clear and concise description of what you expected to happen. To battle the player

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
