### ISSUE TITLE
Starter Selection Glitch

### ISSUE THREAD

**Issue by Domodonuts** [SmashMC-Development/Bugs-and-Issues#528]
**Describe the Bug**
The starter selection screen is glitching out each time I enter the Groudon server. I moved the mouse towards the starter pokeball or the park ball icon and clicked one. They would stay on my mouse and drag towards another part of the screen. After clicking another time the starters would appear and the screen would kick me out then go back into the selection. This occurs for both custom and normal starter selections. It refuses to let me choose a starter as I get kicked out and reenter the selection screens. This prevents me from logging out of the sever and forcing a restart on my computer. 

**To Reproduce**
1. Go to 'the item selection nether star on the menu.'
2. Click on 'the sever selection item to open the sever selection menu. '
3. Scroll down to 'the Groudon sever.'
4. Click on 'Groudon sever to enter.'
5. Move to 'the starter selection pokeball for normal starters or the park ball for custom starters.'
6. Click on 'either the pokeball or park ball icon'
7. see error

**Servers with the Bug**
So far the only server I have entered is Groudon with this issue.

**Expected behavior**
I expected the starter selection to appear with a list of the starters for either the normal gen 1-8 Pokemon or the custom starters with hand selected Pokemon. This was how it appeared when I first arrived on the server or other pixelmon servers.

**Screenshots**
N/A

**Additional context**
On my third attempt to log into the server starter selection did not appear. I noticed a professor oak npc in the spawn. After walking up to him I interacted with the npc. After I clicked the pokeball and park ball icons and the same issue occured. Both icons dragged to my curser. Then the screen started to glitch out and force me to enter the menu and exist the menus. My screen froze once again and I had to force a restart on my computer. I hope this issue has not occurred with anyone else.

**Comment by Domodonuts** [comment]
My apologize this is my first time using GitHub for issues posts I meant to keep this open.

**Comment by HackuJacku** [comment]
This is sadly related to your connection to the server. We're unable to do much but if closing your Minecraft and rejoining will bypass the starter selection screen, you can use the Professor Oak NPC to claim your starter.
