### ISSUE TITLE
Gym Bug

### ISSUE THREAD

**Issue by kirito353** [SmashMC-Development/Bugs-and-Issues#529]
**Describe the Bug**
When I go in a Gym with teleport pads I can't fight the trainers they say to report the bug

**To Reproduce**
1. Go to a Gym With move pads
2. Battle a Trainer
3. Use a Move

**Servers with the Bug**
Groudon

**Expected behavior**
To battle the Gym in Question

**Screenshots**
N/A Can't Screenshot in battle

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Pixelmon battle glitch. Forwarded to Pixelmon
