### ISSUE TITLE
Server restart takes money

### ISSUE THREAD

**Issue by Nutpopper** [SmashMC-Development/Bugs-and-Issues#531]
When the server have to restart because of lag some player have lost a lot of money after logging back in
This happened on the groudon server and a few people have been affected by it and I wish mods and admin will fix this

**Comment by ColonCrusader** [comment]
Also happens on reshiram, its a issue of doing tournaments, it crashes the server of anyone participates, and there is money loss in the boot, in the mean time while they fix this bug, I recommend leaving the server whenever a tourney pops up, as you won’t lose money. Hope this helps, at least a little bit!

**Comment by Rasgnarok** [comment]
Being looked into, closing as it will be solved.
