### ISSUE TITLE
 clicking mining skill kicks out of server

### ISSUE THREAD

**Issue by Its-JER** [SmashMC-Development/Bugs-and-Issues#532]
**Describe the Bug**
Not sure if this is for everyone but when I click on mining skill in the /skill menu it kicks me out of the kyurem server.

**To Reproduce**
1. enter /skills in chat
2. Click on Skills and abilities
3. Click Mining
4. see error

**Servers with the Bug**
Kyurem

**Expected behavior**
To see the skill level and abilities for the mining skill 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
