### ISSUE TITLE
You can Fly in warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#533]
**Describe the Bug**
You can fly in warzone

**To Reproduce**
1. Go to any server
2. do /fly
3. go to warzone
4. You can still fly it doesnt get disabled when going to warzone 

**Servers with the Bug**
Kyurem - Prob all

**Expected behavior**
Shouldnt be able to fly

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed from next reboot.
