### ISSUE TITLE
Cant use End Portals in /warp portals

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#534]
**Describe the Bug**
Cant use the End Portal in /warp portals

**To Reproduce**
1. Go to /warp portals
2. Go into the end portal
3. Nothing Happens

**Servers with the Bug**
Kyurem - Possibly all

**Expected behavior**
Should be able use the portal to go to the end

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/138570944-d61de604-3709-47ac-9a51-838d53fc3061.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by ColonCrusader** [comment]
Can confirm also on reshiram, I have the same issue

**Comment by HackuJacku** [comment]
Fixed from next reboot
