### ISSUE TITLE
Pokemons in warzone

### ISSUE THREAD

**Issue by Jonjuul** [SmashMC-Development/Bugs-and-Issues#535]
**Describe the Bug**
It is when u catch a pokemon in Warzone u dont get the pokemons in ur box after the timer has run out 
![Skærmbillede 2021-10-23 225010](https://user-images.githubusercontent.com/93057140/138571205-76821fa6-3597-4e28-898b-87f39dfbb346.png)

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
