### ISSUE TITLE
Color with Staff bug after purchase of rank 

### ISSUE THREAD

**Issue by eboyJay69** [SmashMC-Development/Bugs-and-Issues#536]
**Describe the Bug**
I am Sr mod so my chat color should be pink and also my ign when I type, but when I got mythic rank it changed into a white color. 

**To Reproduce**
1. Get Sr mod
2. Wiepie bought me mythic 
3. Type in chat 

**Servers with the Bug**
This was on Reshiram

**Expected behavior**
I would want the ign to go back to pink as well at the chat color

**Screenshots**
![image](https://user-images.githubusercontent.com/84190150/138571592-ceb8f1b2-5e2e-4116-8852-d45083c8bc87.png)

**Comment by Rasgnarok** [comment]
Hard to test without you online, but I removed the latent ranks in an effort to see if it is being overwritten. Can you please login and tell me what you see?

**Comment by eboyJay69** [comment]
![image](https://user-images.githubusercontent.com/84190150/147321141-19e8fdae-cd36-4512-b1bc-62ecaa4d7831.png)
it is still white text for me

**Comment by Superfire96** [comment]
Fixed
