### ISSUE TITLE
Raid Dens being too broken

### ISSUE THREAD

**Issue by Leamyyy** [SmashMC-Development/Bugs-and-Issues#537]
**Describe the Bug**

With a 4 man party of wishing piece spamming you can get a lot of master balls, like a lot, we got 24 in total in 15 mins
The problem is the 4/5 star dens also give wishing pieces so they are infinite.

**To Reproduce**
Steps to reproduce the behavior: Just do a raid den

**Servers with the Bug**
Please provide a list of which servers have this bug.

All servers

**Expected behavior**

I expect Wishing Pieces to be nerfed/removed and the master ball drop rate to be reduced

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Removed wishing pieces from raid loot. I have also nurfed Master/Park Balls
