### ISSUE TITLE
Rubber banding Glitch

### ISSUE THREAD

**Issue by ColonCrusader** [SmashMC-Development/Bugs-and-Issues#538]
**Describe  Bug**
I was walking in /warp mart between 2 stairs to go into one of the shops, then mid jump my character froze up and started shaking, I tried to /tpa somewhere else and it started glitching out really bad
**To Reproduce**
So, I haven’t been able to recreate it, apart from just initially getting it, in which it acts like that if you tpa away from spawn and back in, it’s no longer a confined area, I haven’t been able to recreate it, but it repeatedly did it until I completely restarted Minecraft 

**Servers with the Bug**
Reshiram, as far as I’m aware

**Expected behavior**
I would run jump, and land and turn left into #the block shop

**Screenshots** 

> I couldn’t add them for some reason, I don’t know why

**Additional context**
As far as I’m aware, only me and one or person have gotten this glitch

**Comment by ColonCrusader** [comment]
https://user-images.githubusercontent.com/92840415/138572105-4ad8b269-7765-4012-b51d-8bbdf0b9d087.MOV

**Comment by ColonCrusader** [comment]
There we go

**Comment by ColonCrusader** [comment]
https://user-images.githubusercontent.com/92840415/138572183-d7e73bc7-6389-4874-9b44-c5cdae7ece66.mov
And here is the first part

**Comment by Rasgnarok** [comment]
This looks like client desync, best advice I can give you is a restart of your client, or perhaps a better connection. It happens when there's not enough updates back and forth from the server to the client.
