### ISSUE TITLE
Galar zap spawning as normal zap

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#539]
**Describe the Bug**
galar zap spawned, but it was a normal zapdos.

**Servers with the Bug**
reshiram from what i know

**Expected behavior**
galar zap should have spawned

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/138572395-c687353a-40b2-4e2a-a8c5-d870da36512c.png)

**Comment by HackuJacku** [comment]
Fixed
