### ISSUE TITLE
Safeplace not working

### ISSUE THREAD

**Issue by Asunaaaaaaa** [SmashMC-Development/Bugs-and-Issues#54]
**Describe the Bug**
Safeplace doesn't work on Rayquaza 

**To Reproduce**
go into ray wz,

**Servers with the Bug**
Rayquaza, unsure of others

**Expected behavior**
safeplace should teleport players out of warzone after 5 seconds

**Screenshots**
![image](https://user-images.githubusercontent.com/83178527/116001834-88bfc200-a5ee-11eb-879a-577bb4e0f8e4.png)

**Comment by HackuJacku** [comment]
See #32
