### ISSUE TITLE
No heart in front of my name

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#540]
**Describe the Bug**
I have no heart in front of my name when im married to someone

**To Reproduce**
/marry someone

**Servers with the Bug**
Reshiram (probably all)

**Expected behavior**
I expect a heart in front of my name 

**Screenshots**
NA

**Additional context**
NA

**Comment by Rasgnarok** [comment]
Fixed for next restart.
