### ISSUE TITLE
/sts command isn't working.

### ISSUE THREAD

**Issue by TheHumbleJames** [SmashMC-Development/Bugs-and-Issues#541]
**Describe the Bug**
/sts command not work

**To Reproduce**
1. type /sts or use menu
2. no command exsist

**Servers with the Bug**
Specifically for me Reshiram

**Expected behavior**
Sts I believe is supposed to show available kits.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Same as #510
