### ISSUE TITLE
paying player issue

### ISSUE THREAD

**Issue by Ryan1595** [SmashMC-Development/Bugs-and-Issues#543]
**Describe the Bug**
When doing /pay coins *username* the chat said "paid %player% "x" coins" instead of saying their username

**To Reproduce**

pay someone on a server (kyurem)

**Servers with the Bug**
Please provide a list of which servers have this bug.

Only tested on kyurem

**Expected behavior**

say the name of the player

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

![2021-10-23_18 37 51](https://user-images.githubusercontent.com/84028511/138574660-8f8ff544-95dd-4230-8547-1c27bf93c584.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
