### ISSUE TITLE
NPC Quests are unavailable.

### ISSUE THREAD

**Issue by TheHumbleJames** [SmashMC-Development/Bugs-and-Issues#549]
**Describe the Bug**
I've spent hours with NPC in villages and none of them give quests. This makes things like the Dynamax band unavailable to players.

**To Reproduce**
1. Go to a village
2. Sit around and wait for quests to appear.
3. quests never appear

**Servers with the Bug**
Currently at least Reshiram, but I confirmed with players on other servers and they're having the same issue.

**Expected behavior**
I expect to be able to get NPC quests so I can achieve a Dynamax band and a few other things that are quest exclusive.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
