### ISSUE TITLE
Weird shrine glitch

### ISSUE THREAD

**Issue by sirbarongallop** [SmashMC-Development/Bugs-and-Issues#550]
I have max articuno orb and 50k cash I can't use shrine

**To Reproduce**
1 Get max "Orb of Frozen Souls and 50k cash"
2. Go to 'Articuno shrine'
3. Click on 'Shrine'

**Servers with the Bug**
I tried on groudon.

**Expected behavior**
I expected to fight articuno

**Screenshots**
![Screenshot_37](https://user-images.githubusercontent.com/93023060/138583477-c5851c58-2845-4f27-9352-2382529acbd9.png)
**Additional context**
N/A

**Comment by HackuJacku** [comment]
fixed
