### ISSUE TITLE
sts is not working

### ISSUE THREAD

**Issue by pangus00JR** [SmashMC-Development/Bugs-and-Issues#552]
**Describe the Bug**
cant do the /sts command on kyogre

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
This was removed due to a duplication bug. When a fix is available, it'll be readded.
