### ISSUE TITLE
./warp portals - The end portal is not working

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#556]
**Describe the Bug**
Do ./warp portals and go to the end portal. It doesnt tp u to the end at all. It just does nothing

**To Reproduce**
1. Go to ./warp portals
2. Go to the End portal
3. it does nothing

**Servers with the Bug**
Groudon

**Expected behavior**
Suppose to bring you to the end.

**Screenshots**
![image](https://user-images.githubusercontent.com/77503363/138589509-9783908e-f472-41cf-b1c8-c414b6594d4a.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
fixed from next reboot
