### ISSUE TITLE
/link not working

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#557]
**Describe the Bug**
/link is not working, it says its an unknown command.

**To Reproduce**
1. type /link
2. comes up with error

**Servers with the Bug**
all 

**Expected behavior**
should let the player link their account

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/138589986-8d8da45d-5ecb-4adf-8f71-04230a8a0f00.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
This was removed, please read the changelogs as it was stated there.
