### ISSUE TITLE
Randomteleport works in warzone

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Bugs-and-Issues#56]
**Describe the Bug**
/randomteleport (still) works in warzone

**To Reproduce**
Go to warzone and run the command /randomteleport

**Servers with the Bug**
Giratina (but pretty sure it's all servers)

**Expected behavior**
When try to randomteleport in warzone, give a error message

**Comment by HackuJacku** [comment]
@Sparklix please can you check all servers and let me know?

**Comment by Sparklix** [comment]
> @Sparklix please can you check all servers and let me know?

@HackuJacku Deoxys, Darkrai, Jirachi, kyogre, palkia, dialga, mew RANDOMTELEPORT WORKS

Rayquaza & charizard doesn't

**Comment by Shoji007** [comment]
@HackuJacku  can confirm blocked on all servers now <3

**Comment by Sparklix** [comment]
Darkrai, mew and giratina are blocked, testing others tomorrow morning
