### ISSUE TITLE
Money transfers over between servers

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#560]
**Describe the Bug**
I have the same amount of money on all servers and they transfer over.
I have tried buying something on reshiram and that also affects my money on rayquaza

**To Reproduce**
earn money
Spend it
Money also goes down or up on other servers

**Servers with the Bug**
I would assume all of them since it affects different servers but for sure reshiram and rayquaza

**Expected behavior**
I expect my money on reshiram to stay on reshiram and not affect my money on rayquaza and vice versa

**Screenshots**
NA

**Additional context**
NA

**Comment by HackuJacku** [comment]
After looking, this does not occur. Checked on multiple servers, with multiple players.
