### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by ErikUnderscoreJansen** [SmashMC-Development/Bugs-and-Issues#561]
So sometimes when i move items to my hot bar and then use them i dont have them anymore

1. Wait for a few minutes when you have logged on
2. Go to Your inventory
3. Drag An item to your hot bar
4. Exit Your inventory
5. Look in a chest and then the item will be back where it was in the first place

As far as i know all pixelmon servers have this bug

If you drag something to your hot bar you wont be able to use it 

N/A

It very Irritating if you want to build and you drag the block to you hot bar and it is not actually there and if you do it in a chest it will be in the right spot.

**Comment by HackuJacku** [comment]
Sadly we're unable to do anything about this as it's related to your connection.
