### ISSUE TITLE
/ec not working

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#566]
**Describe the Bug**
/ec or /enderchest not working for smods

**To Reproduce**
need to check /ec for someones account (idk a scam or something)
type /ec
says i dont have permission as a smod

**Servers with the Bug**
Reshiram (i expect all)

**Expected behavior**
I would expect to be able to see someones enderchest when i need to check that

**Screenshots**
NA

**Additional context**
NA

**Comment by HackuJacku** [comment]
Fixed
