### ISSUE TITLE
skills being bugged

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#567]
**Describe the Bug**
The skills are messed up. For starters i don't get any skills from mining. Secondly, when i excavate dirt somehow my herbalism skill goes up. These are just the ones i know. dont know if others are messed up (i know woodcutting works fine for me)

**To Reproduce**
mine anything that is mineable with a pickaxe
Get no skill levels

Use a shovel on dirt or gravel
Get levels in herbalism instead of excavation

**Servers with the Bug**
Reshiram (but would think all)

**Expected behavior**
I would expect to get levels in mining and excavation

**Screenshots**
NA

**Additional context**
NA

**Comment by Its-JER** [comment]
Same on kyurem

**Comment by Superfire96** [comment]
Fixed
