### ISSUE TITLE
Currently stuck in a battle, apparently the battle isn't registered as the helper can't end it.

### ISSUE THREAD

**Issue by Stormdragon32** [SmashMC-Development/Bugs-and-Issues#568]
**Describe the Bug**
I am currently stuck in a battle. I tried to do /hub but that didn't work, and I tried restarting both minecraft and forge, that didn't work either. I currently cannot join the groudon server without being locked in this battle. 

**To Reproduce**
I'm not sure where to go.
I challenged an NPC on the top of a building then got the notif after trying to move.
In this case I'm not sure if its reproducable. 

**Servers with the Bug**
Specifically groudon for me. 

**Expected behavior**
Battle locks even through reconnecting and disconnecting. 

**Screenshots**
![image](https://user-images.githubusercontent.com/93093091/138605631-2170357a-35a8-4a60-8ac6-1538fa7603b9.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Pixelmon Battle Bug, forwarded to them.
