### ISSUE TITLE
/rtp

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#569]
**Describe the Bug**
Your able to /rtp drowned to get to drowned world
**To Reproduce**
1. got to any server and do /rtp drowned
4. See that you can get there even tho your not supposed to be able to 

**Servers with the Bug**
every server from what I can see

**Expected behavior**
shouldn't be able to get here, and your able to capture the special pokemon

**Screenshots**
![2021-10-24_12 16 02](https://user-images.githubusercontent.com/83245837/138607195-566c7f5a-86ee-44a7-a9e3-2367fc14cd3a.png)
this includes every other world to tp to , and shows you can capture the pokemon
**Additional context**
this was tested on kyurem, so if you want to take away my pokemon that I caught signs superdwagon_

**Comment by Superfire96** [comment]
Fixed
