### ISSUE TITLE
custom aura papers can give another color than whats stated

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#57]
**Describe the Bug**
some papers for aura dont give the color thats stated on the paper, but thats due to the type of said aura (cloud is always white, dragon breath is always pink/purple.....)

**To Reproduce**
get a custom aura paper (so particle_select, not particle) and get the wrong color from it

**Servers with the Bug**
all 

**Expected behavior**
set the color to always match the type (so smt like "pink cloud" should be impossible to get) if that type only can have 1 color

(ill check out all the aura types tmrw for the colors and edit my msg accordingly then)

![image](https://user-images.githubusercontent.com/82659374/116125955-60a39200-a6c6-11eb-990a-3cd2d9c20779.png)

**Comment by HackuJacku** [comment]
Moved in the 8.2 update version.

**Comment by HackuJacku** [comment]
Changes are now live.
