### ISSUE TITLE
Ranks extra sethome

### ISSUE THREAD

**Issue by LilBotss** [SmashMC-Development/Bugs-and-Issues#573]
Ranks extra /sethome command does not work

**To Reproduce**
1. Have a rank, at least Ace rank
2. Have the one sethome from the server set
3. Do another /sethome
4. See the error

**Servers with the Bug**
Smashmc

**Expected behavior**
Being able to use the extra sethomes

**Screenshots**
![Uploading AD7787D4-5021-44BD-B1A1-6360780A56A9.jpeg…]()

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
