### ISSUE TITLE
Warzone pokemon's evolutions not registered in dex

### ISSUE THREAD

**Issue by Spacioo** [SmashMC-Development/Bugs-and-Issues#575]
**Describe the Bug**
Pokemons from warzone dont bring their dex data when evolved. For example, i caught a pawniard in WZ (i got pawniard's dex data), then evolved it into bisharp, but i didn't get bisharp's dex data. I still have it, logged off, closed the game, came back, moved it between PC and team slots, made it fight, but it won't register its data. Also, given that i didn't get the data, the dex % didn't increase. 
That bug happened to me with at least 10 pokemons, all from warzone, but not the others.

**To Reproduce**
"For example, i caught a pawniard in WZ (i got pawniard's dex data), then evolved it into bisharp, but i didn't get bisharp's dex data. I still have it, logged off, closed the game, came back, moved it between PC and team slots, made it fight, but it won't register its data."

**Servers with the Bug**
Reshiram, but possibly all

**Expected behavior**
Should get registered in dex

**Screenshots**
![image](https://user-images.githubusercontent.com/93030907/138616893-b2269262-323d-40d4-8f4b-0142a1afea35.png)
![image](https://user-images.githubusercontent.com/93030907/138616900-c4bb4d0b-ce13-4200-a143-ff65d92bf2ec.png)

**Additional context**
Every pokemon caught in WZ has no Original Trainer for some reason. May be linked.

**Comment by HackuJacku** [comment]
Same bug as #699
