### ISSUE TITLE
warzone pokemon

### ISSUE THREAD

**Issue by gusiong** [SmashMC-Development/Bugs-and-Issues#576]
**Describe the Bug**
the bug is if you catch a Pokémon in warzone it there is no original trainer its blank 

**To Reproduce**
1. Go to 'warzone'
2. catch 'pokemon'
3. get the pokemon 'get the pokemon in pc'
4. look the the stats the ot bellow it its blank in normal it will say your name if you catch it

**Servers with the Bug**
idk if other server have this 

**Expected behavior**
to have my name in ot

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
