### ISSUE TITLE
Warzone bug

### ISSUE THREAD

**Issue by AyanamiBestWaifu** [SmashMC-Development/Bugs-and-Issues#579]
**Describe the Bug**
Rayquaza Warzone you cant force battle players and you have a normal pokeball throw distance 
**To Reproduce**
1. Go to 'Rayquaza'
4. go to warzone and try to force battle a player

**Servers with the Bug**
I can only check rayquaza since I only have mons there
**Expected behavior**
You should be able to force players to battle in the warzone
**Screenshots**
N/A
**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed in next version.
