### ISSUE TITLE
Players unable to engage with Pokémon (not in claim)

### ISSUE THREAD

**Issue by Bryceisright** [SmashMC-Development/Bugs-and-Issues#58]
Players are running into an issue, after leaving warzone they’re unable to engage in battle with any Pokémon wether they’re in warzone or not.  

To fix this issue-
Go to warzone with the person, have them battle you then have them forfeit, after that, steal a pokemon from them and tell them to go to /warp heal or /warp eevee. When you’re there, tell the person to trade you the rest of their team and then go heal the team. After this, trade the team back and have them test it.

To assist helpers rectify this issue it would be helpful if they where all given a team of 75+ Pokémon on every server so if they’re required to go into warzone and help the player with said issue they don’t need to ask for hand outs or have they could have the  command /ignorewz to bypass the level cap.

I.E ticket 19965

**Comment by HackuJacku** [comment]
@Bryceisright - Please follow the format provided in the future, which server is this?

**Comment by HackuJacku** [comment]
@Rasgnarok - will you be able to take a look at this for me please as you're working in the GD setup?

**Comment by Rasgnarok** [comment]
It doesn't strike me as a GD issue though. It's as if Warzone was soft locking them. Any changes recently

**Comment by Bryceisright** [comment]
Sorry so far I’ve only run into this on charizard.

**Comment by Rasgnarok** [comment]
I fixed this a week ago, forgot to close.
