### ISSUE TITLE
Players flying in wz

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#580]
**Describe the Bug**
people with /fly cna fly while in wz
**To Reproduce**
1. Go to warzone
2. idk what to do, but I see people with smash/legend rank dlying
3, 

**Servers with the Bug**
only can test on kyurem but saw RestlessSoul flying in wz

**Expected behavior**
To not fly while in wz

**Screenshots**
n/a
**Additional context**
n/a

**Comment by HackuJacku** [comment]
Fixed in next version.
