### ISSUE TITLE
==Warzone==

### ISSUE THREAD

**Issue by EboyZenks** [SmashMC-Development/Bugs-and-Issues#581]
So in the new warzone you have a limit of 1 minute and you have to catch pokemon to keep that timer refilling however you spend more time catching the pokemon so you end up loosing time and the 1 minute is just not enough time so i reckon the warzone should just have a daily timer that you allowed to use and its maximum 10 mins in wz at a time with a daily limit of 90 minutes in warzone and a 30 minute cool down in between the 10 minute period and also the remove of movement pads was not needed some players need to use them to hatch eggs as they have other 'more important' things to do also you should add gliding with elytra to the acrobatics' skill thanks for reading - EboyZenks

**Comment by HackuJacku** [comment]
Not a bug, intended feature.
