### ISSUE TITLE
Multiple Shiny Charmander Starters

### ISSUE THREAD

**Issue by OverlordRah** [SmashMC-Development/Bugs-and-Issues#582]
**Describe the Bug**
I lagged out, and had to go to the professor to collect my starter instead of through the pop-up when jumping on a new server. I selected the Shiny Charmander as a starter, and when I didn't get it at first, I clicked several times, thinking I was lagging. When I finally got the window to close, I had five different shiny charmanders. 

**To Reproduce**
1. Start new character on Zekrom server
2. Close the window instead of selecting a starter pokemon
3. Re-log in, and go to the professor to get a starter pokemon
4. Select pokemon, and left click multiple times rapidly
5. right click the pokemon
6. You should have multiple starters.

**Servers with the Bug**
Only tested on Zekrom

**Expected behavior**
Multiple starter pokemon

**Screenshots**
![image](https://user-images.githubusercontent.com/93118666/138653699-7b67ab55-bcb7-49ee-884f-4b68f4a845c9.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Forwarded to the developer

**Comment by HackuJacku** [comment]
Fixed
