### ISSUE TITLE
Bought Elite rank claims

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#583]
**Describe the Bug**
The elite rank does not give the additional homes it says it does.

**To Reproduce**
1. Buy Elite rank
2. Try to make a home (/Sethome)
3. It still show only 1 home available

**Servers with the Bug**
Kyurem, I assume other servers too.

**Expected behavior**
Elite rank should allow you to set 3 homes.

**Screenshots**
![image](https://user-images.githubusercontent.com/45851395/138659468-b825733d-f634-4eb4-8432-bccb3a63eed9.png)
![image](https://user-images.githubusercontent.com/45851395/138659482-4d8057be-61c6-46d0-89a1-047af938dc49.png)

**Additional context**
N/A.

**Comment by Superfire96** [comment]
Fixed
