### ISSUE TITLE
Sts 

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#585]
**Describe the Bug**
Really need sts to come back as there is very little ways to actually make money with pokemon

**Servers with the Bug**
Pretty sure all

**Expected behavior**
For /sts to allow the player to sts there Pokémon for money
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
#510
