### ISSUE TITLE
cannot do /balance

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#586]
**Describe the Bug**
/bal coins doesnt work on players that arent online. Would be usefull to have this if i need to refund money :)

**To Reproduce**
Another player needs to go offline
do /bal eboyjay69 (for example)
says i can't do this for players that aren't online

**Servers with the Bug**
Reshiram (but i would assume all)

**Expected behavior**
I would expect to be shown their balance if i need to refund money

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/138676519-ab2d46b0-2a55-4001-946b-b2312c080c37.png)
(the 6.5k is my own money)

**Additional context**
NA

**Comment by HackuJacku** [comment]
Fixed from next reboot.
