### ISSUE TITLE
cant refund money

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#587]
**Describe the Bug**
/eco give doesnt work. I'm not sure if i have the wrong command in the document but its not working

**To Reproduce**
type in /eco give (ign) coins 45000
get a response saying the command is typed in wrong?

**Servers with the Bug**
Reshiram but i think all

**Expected behavior**
I would expect to be able to give money to players that need it refunded

**Screenshots**
NA

**Additional context**
NA

**Comment by HackuJacku** [comment]
Fixed
