### ISSUE TITLE
Mods+ tp to players in wz

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#588]
**Describe the Bug**
Not sure if a bug really but when trying to tp to a player in wz it says I cant because of different dimensions.

**To Reproduce**
1. Have a player be in warzone
2. Have access to /tp as mod+ and use it with the ign of player in wz
3. When trying to tp you will see a message saying you can not tp because of different dimensions

**Servers with the Bug**
This is a problem on all servers.

**Expected behavior**
Before the reset mods+ were able to tp to people in wz.

**Screenshots**
![Screenshot (708)](https://user-images.githubusercontent.com/45851395/138682896-ba840abf-38cb-4deb-9167-77f6df222072.png)

**Additional context**
N/A.

**Comment by HackuJacku** [comment]
Use `/teleport`.
