### ISSUE TITLE
end portal not working

### ISSUE THREAD

**Issue by yamiboy1** [SmashMC-Development/Bugs-and-Issues#589]
**Describe the Bug**

**To Reproduce**
1. step in portal
2. portal dont work
3. no end exploring

**Servers with the Bug**
rayquaza (dont know about the other servers).
**Expected behavior**
it should send me to the end.

**Screenshots**
'N/A'

**Additional context**
'N/A'

**Comment by HackuJacku** [comment]
Fixed from next reboot
