### ISSUE TITLE
Liquids not Spreading

### ISSUE THREAD

**Issue by Bryceisright** [SmashMC-Development/Bugs-and-Issues#59]
**Bug**
Currently having issues with placing water/lava as it’s not spreading and when they throw their Pokémon at wild Pokémon it’s going through the Pokémon and into the ground.

**Servers with the Bug**
Dialga

**Screenshots**

https://cdn.discordapp.com/attachments/836525665448493056/836540256265699328/2021-04-27_11-50-34.mp4

**Comment by Rasgnarok** [comment]
@HackuJacku Collision is broken on Dialga. Have we touched wilderness flags?

**Comment by Bryceisright** [comment]
Just a little update, this server is now having issues where no one can PvP in warzone.

**Comment by Rasgnarok** [comment]
Fixed, GD was just desyncing because of massive lag.
