### ISSUE TITLE
Fell in a hole in warzone

### ISSUE THREAD

**Issue by Bigchamp123** [SmashMC-Development/Bugs-and-Issues#590]
**Describe the Bug**
North of the warzone, left of the bridge, there is a 2x2 hole that players can fall into 

**To Reproduce**
1. Go to 'The bridge north of warzone, then walk to the left of it, you will see it.'
2. Jump in hole
3. See error

**Servers with the Bug**
Zekrom
**Expected behavior**
I didn't expect to fall into a hole tbh 

**Screenshots**

![2021-10-25_14 17 54](https://user-images.githubusercontent.com/51046123/138711811-f1884ed6-0e5d-4bca-a4b7-4755abeef886.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
This could be anywhere in the Warzone so you'll need to provide exact coordinates please.

**Comment by M1n0j** [comment]
Coordinates are -212, 84, -1.3 on Zekrom

**Comment by HackuJacku** [comment]
Fixed
