### ISSUE TITLE
Banned items in warzone

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#591]
**Describe the Bug**
It seems like people are able to use items and their effects in warzone that are supposed to be banned as far as I am aware.

**To Reproduce**
1. get a set of thunderstone armor or a moonstone shovel for example
2. type the /Warzone command and you are able to go to wz

**Servers with the Bug**
This problem was discovered on reshiram but it might extend to other servers.

**Expected behavior**
As far as I am aware it should not be possible to enter wz with any of the evo stone items or potions.

**Screenshots**
N/A.

**Additional context**
N/A.

**Comment by Rasgnarok** [comment]
Fixed potions being used inside Warzone, are thunderstone or moonstone still giving benefits inside Warzone? I need this re-tested.

**Comment by M1n0j** [comment]
Amours are still give their benefits currently

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
