### ISSUE TITLE
Elite rank homes

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#593]
**Describe the Bug**
It seems buying the elite rank does not give the right amount of homes available.

**To Reproduce**
1. Upgrade to/Buy the elite rank
2. go on a server 
3. /Sethome <name>
4. /sethome <name> again in a different place
5. See error

**Servers with the Bug**
Kyurem was the server it was discovered on, not sure about others.

**Expected behavior**
I expect to be able to make 3 homes when buying or upgrading to the elite rank

**Screenshots**
![image](https://user-images.githubusercontent.com/45851395/138715191-e53abd89-967c-4cf9-8959-044bab4e2ee2.png)
![image](https://user-images.githubusercontent.com/45851395/138715209-f451164a-0fff-4cad-9057-5ba2f3dc9c37.png)

**Additional context**
N/A.

**Comment by Superfire96** [comment]
The issue was solved
