### ISSUE TITLE
Water not flowing on claims

### ISSUE THREAD

**Issue by Awholemess** [SmashMC-Development/Bugs-and-Issues#594]
**Describe the Bug**
I have noticed that when I place water on my claim, it stays where I placed it, and I doesn't flow anywhere. I've seen other people having the same problem.

**To Reproduce**
1. Go to your claim
2. Place a bucket of water down anywhere in said claim
3. Watch it stay stationary

**Servers with the Bug**
Rayquaza

**Expected behavior**
I expected water to flow like water.

**Comment by Superfire96** [comment]
Fixed
