### ISSUE TITLE
Move Tutor errors

### ISSUE THREAD

**Issue by Bigchamp123** [SmashMC-Development/Bugs-and-Issues#596]
**Describe the Bug**
Alot of pokemon are unable to learn specific moves, for example, genesect is unable to learn iron head, and Urshifu is unable to learn Surging Strikes 

**To Reproduce**
1. Go to 'Move Tutor, or /buymoves with Urshifu in party'
2. Click on 'Urshifu Icon'
3. Scroll down to 'all of the pages'
4. See Surging strikes not being there

**Servers with the Bug**
Zekrom

**Expected behavior**
Be able to learn all moves that each pokemon is able to learn apart from Egg moves
**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Closing, ticket is no longer up to date thanks to latest fixes to stat files.
