### ISSUE TITLE
T stone in wz

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#597]
**Describe the Bug**
You can bring t stone in wz

**To Reproduce**
1. Go to wz
2. Bring t stone 
3. You can bring it in 

**Servers with the Bug**
Zekrom but possibly all

**Expected behavior**
No t stone in wz

**Screenshots**
'N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed in next version.
