### ISSUE TITLE
Zekrom gyms aren’t working 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#598]
**Describe the Bug**
when I do /gyms I cannot tp or challenge it 

**To Reproduce**
1. Go to /gyms
2. Click on gyms
3. Scroll down to ground gym and click join que or tp to gym 
4. See error where you cannot challenge the gym 

**Servers with the Bug**
Zekrom 

**Expected behavior**
I should be able to challenge the gym 

**Screenshots**
n/a

**Additional context**
n/a

**Comment by HackuJacku** [comment]
Not a bug. You need to go to the gyms yourself.
