### ISSUE TITLE
I don’t have e4 commands 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#599]
**Describe the Bug**
I cannot do /ag manage or any commands as e4 

**To Reproduce**
1. As an e4 do /ag manage 
2.it will say you must have a role in a gym or e4 to use this command

**Servers with the Bug**
Zekrom 

**Expected behavior**
I should be able to use gym commands

**Screenshots**
N/a I can’t sc for some reason 

**Additional context**
n/a

**Comment by HackuJacku** [comment]
Speak to Ras directly, @Brushyboi
