### ISSUE TITLE
Able to battle on the ship

### ISSUE THREAD

**Issue by Daddyricardo** [SmashMC-Development/Bugs-and-Issues#60]
**Describe the Bug**
Your able to battle on the ship.

**To Reproduce**
1. Go to '/warp warzone'
2. Battle another player

**Servers with the Bug**
Jirachi unsure of others

**Expected behavior**
You should not be able to battle others

**Screenshots**

**Additional context**

**Comment by HackuJacku** [comment]
@Daddyricardo - please can you check the other servers and let me know?

**Comment by Daddyricardo** [comment]
Checked them out all seem fine.

**Comment by HackuJacku** [comment]
@Daddyricardo - please can you check now and let me know the rule?

**Comment by Daddyricardo** [comment]
Ill be able to do this in like 2 hours a bit busy right now.

**Comment by HackuJacku** [comment]
@Daddyricardo - did you manage to check this please?

**Comment by Rasgnarok** [comment]
You can't send out Pokemon anymore, there was just no claim at Jirachi's Warzone ship. Fixed.
