### ISSUE TITLE
Did not get pokemon on gts that I payed for. Date: 10/25/21

### ISSUE THREAD

**Issue by Silv3rSyth3** [SmashMC-Development/Bugs-and-Issues#601]
**Describe the Bug**
A clear and concise description of what the bug is. I bought a moltres off of gts for 15000 pokedaollars. AT the exact moment after I bought I forgot to claim it. But Later when I tried to claim it would not let me.

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug. Rayquaza server

**Expected behavior**
I thought it would send it to my PC as it did before the update 8.3.1
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'. It was a moltres and it was 15000.

**Comment by HackuJacku** [comment]
Switched to Waterdude's GTS
