### ISSUE TITLE
Warzone bank duplicated some of my previously taken out mons

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Bugs-and-Issues#603]
So today I went into warzone for 10 minutes and caught some pokémon, when I came out, opened my warzone bank and the terrakion that I caught yesterday (and took out) was again in there together with some other pokémon.

**To Reproduce**
Truthfully, I don't know what caused my warzone bank to duplicate/bring back previous mons that I already took out.

Yesterday: Went into warzone, caught a few mons (including a 94% terrakion), when coming out I took all mons out my warzone bank.

Today: Went into warzone, caught some mons (no legendaries) and when coming out, I noticed terrakion was back into my warzone bank.

**Servers with the Bug**
Kyurem

**Expected behavior**
Show the mons you caught, not being able to take out the same mon twice.

**Screenshots**
In the screenshot you can see that I already had levelled the Terrakion to level 100, but the iv's are exactly the same.
![80b4ca95688893b5fca0034e7123b3d8](https://user-images.githubusercontent.com/77632744/138821216-94b346e4-122f-4700-a683-41af9a731534.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
