### ISSUE TITLE
cant see tm sellers in mart

### ISSUE THREAD

**Issue by HypherDeath** [SmashMC-Development/Bugs-and-Issues#604]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
[
![image](https://user-images.githubusercontent.com/93186000/138836024-55dbfa91-ac06-4710-b5ec-86ff5b09563e.png)
](url)

**Comment by Superfire96** [comment]
There aren't tm sellers at the moment
