### ISSUE TITLE
Skills not giving exp when mining ores

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#605]
**Describe the Bug**
when strip mining i am nor receiving exp when mining redstone/iron/gold/diamonds/bauxite or any pixelmon related ores, only coal and stone and granite/andesite/diorite give exp 
**To Reproduce**
1. Go mining
2. try mining the ores mentioned above
3. get no exp form ores

**Servers with the Bug**
Rayquaza ( possibly others)
**Expected behavior**
all ores should give some form of mining skill exp

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Fixed
