### ISSUE TITLE
Catch combos

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#606]
**Describe the Bug**
The catch combo is way too convenient for players and should be nerfed or disabled on all servers.

**To Reproduce**
1. Catch a pokemon
2. Catch again until catch combo reaches around 50s
3. the pokemon you catch at this point are way too high ivs

**Servers with the Bug**
Rayquaza still, I think we should have all servers checked for this though on Reshi it is disabled.

**Expected behavior**
N/A.

**Screenshots**
N/A.

**Additional context**
N/A.

**Comment by Superfire96** [comment]
That's more a suggestion and not a bug
