### ISSUE TITLE
Roggenrola

### ISSUE THREAD

**Issue by Spacioo** [SmashMC-Development/Bugs-and-Issues#607]
**Describe the Bug**
Roggenrolas don't hold everstones anymore

**To Reproduce**
Use thief on wild roggenrolas, or catch them and check the item they hold (or if they hold nothing)

**Servers with the Bug**
Reshiram

**Expected behavior**
Should be holding it 50% of the time

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
I caught like 40 of them to be sure before making ticket. It was working just 12 hours ago

**Comment by HackuJacku** [comment]
Not a bug, intentionally removed.
