### ISSUE TITLE
Raid den catching pokemon 

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#608]
When you try to catch a pokemon it can take ages to do the catching animation. It has taken more than 5 minutes just to catch a raid pokemon before

**Servers with the Bug**
groudon

**Expected behavior**
try to catch a raid den pokemon and there's a high chance it'll take ages to catch

**Comment by Superfire96** [comment]
It has to do with the server/your lag sadly
