### ISSUE TITLE
Nether problems spreading

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#61]
**Describe the Bug**
Internal Server error crash to hub upon entering the nether and Unexpected error in running this command:null upon exit

**To Reproduce**
1. >try to go into nether 
>get sent to hub
>getback on server and be in nether
>try to leave nether
>get command error

**Servers with the Bug**
Giratina ( not sure of others)

**Expected behavior**
should just teleport into the nether like normal minecraft logic when going through portal

**Screenshots**
https://gyazo.com/f0c743910e26163d5b91d00e5485afcf

https://gyazo.com/41a73439fdf6e45d77e0b6bcf1af84d5

**Additional context**

**Comment by HackuJacku** [comment]
@Shoji007 - when this next occurs, please provide me with the following information:
- Username of the player who had this issue.
- Server it occurred on.
- Exact time when it occurred.
- Error message the player receives in the chat.

**Comment by Rasgnarok** [comment]
This was a warzone related bug when switching dimensions. See #pixelmon chat in Management for more details. According to Waterdude, related to the party bug. Closing as it should not be reproducing anymore. Please re-open with logs if it happens again.
