### ISSUE TITLE
Pokedex Glitchy

### ISSUE THREAD

**Issue by xSire** [SmashMC-Development/Bugs-and-Issues#611]
**Describe the Bug**
pokedex is kinda broken
**catch a pokemon is wz dont get dex **
1. Go to 'wz'
2. Catch a pokemon
3. Evolve it and dont get dex

**Servers with the Bug**
Kyreum(maybe all ?)

**Expected behavior**
to be able to get dex 

**Screenshots**
NA
**Additional context**
NA

**Comment by HackuJacku** [comment]
Reported to the developer and already working on a fix. Please keep an eye on #changelog in our Discord.
