### ISSUE TITLE
Master rank bug

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#612]
**Describe the Bug**
People just got their rank back on Ray and it seems like someone maybe more got the master rank back which I assume is not meant to be a thing.

**To Reproduce**
1. get master rank before reset
2. when paid ranks are returned to people someone got his master rank from before reset too

**Servers with the Bug**
Rayquaza so far but may be other servers too

**Expected behavior**
Dex ranks should not be given to players like paid ranks?

**Screenshots**
![Screenshot (723)](https://user-images.githubusercontent.com/45851395/138938411-007a7376-1932-4631-880d-65e872c86383.png)

**Additional context**
N/A.

**Comment by HackuJacku** [comment]
Fixed
