### ISSUE TITLE
no vaults in /vault

### ISSUE THREAD

**Issue by Awholemess** [SmashMC-Development/Bugs-and-Issues#613]
**Describe the Bug**
Those who have permission to use /vault are all saying there are no vaults appearing when the command is used.

**To Reproduce**
1. Type in /vault
2. see the lack of vaults

**Servers with the Bug**
Rayquaza

**Expected behavior**
I expected to have at least one vault, as the command implies

**Comment by HackuJacku** [comment]
After being granted access to a vault, you need to relog. This isn't a bug.
