### ISSUE TITLE
/nick does not work with minecraft color/formatting codes currently

### ISSUE THREAD

**Issue by xHudsy** [SmashMC-Development/Bugs-and-Issues#614]
**Describe the Bug**
Smash rank is unable to use formatting and color codes
Mythic and legend ranks are unable to use color codes

**To Reproduce**
1. Attempt to change nickname using a formatting code/color. For example: /nick &lHudsy
2. See error message, nickname does not change

**Servers with the Bug**
Kyogre

**Expected behavior**
Using a command such as /nick &lHudsy should change the nickname of the player to be bold if they have smash rank, and a command such as /nick &1Hudsy should change the nickname of the player to be dark blue if they have mythic, legend or smash rank

**Screenshots**
https://imgur.com/a/YCVCnRw - Command typed
https://imgur.com/a/CNJeVCo - Error message

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Colours should be fixed, what about formatting please?

**Comment by xHudsy** [comment]
Colors are fixed!
https://imgur.com/a/NnMHezI - Colors working fine
Smash rank still does not have access to formatting, I'll send the new error message that occurs.
https://imgur.com/a/NSzveV6 - Command typed
https://imgur.com/a/4kfSfsS - Error message

**Comment by Superfire96** [comment]
Fixed
