### ISSUE TITLE
Daily rewards were bugged

### ISSUE THREAD

**Issue by Leamyyy** [SmashMC-Development/Bugs-and-Issues#615]
**Describe the Bug**

I crafted a cauldron for 16 dusk ball and 1500$ and I got neither.

**To Reproduce**
Steps to reproduce the behavior: I crafted a cauldron for the daily quest.

**Servers with the Bug**
Please provide a list of which servers have this bug.

I think all, but this happend on Ray

**Expected behavior**

I hope it got fixed, I already got the stuff from Wiepie.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Do you by any chance remember the name of the quest?

**Comment by Leamyyy** [comment]
This was a bug half a year ago, it has been fixed by Hacko a long time ago lol
