### ISSUE TITLE
Cant use Staff Chat in warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#617]
**Describe the Bug**
Cant do Staff Chat

**To Reproduce**
1. Go to warzone
2. Type /sc (msg)
3. Wont allow you to

**Servers with the Bug**
Tested on Kyurem prob all

**Expected behavior**
Should be able use it for Moderation reasons

**Screenshots**
![2021-10-26_22 48 15](https://user-images.githubusercontent.com/84816052/138967309-aba8a7a4-54c4-4683-8bbb-2dad3074214d.png)
![2021-10-26_22 48 19](https://user-images.githubusercontent.com/84816052/138967314-68eb4687-8f8d-4431-a72a-e0610e17c686.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
