### ISSUE TITLE
Gyms are broken! Giving non existent items!

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#618]
**Describe the Bug**
Gyms arent giving out items, and items that dont exist ingame. and not giving badges for badge case. ( fire gym is where bug starts as the ground gym was just fine)

**To Reproduce**
1. Go to /warp gyms
2. fight fire gym
3. see screenshot below for items given
4. dont get items cause they dont exist

**Servers with the Bug**
Rayquaza (Possibly all)

**Expected behavior**
should give  proper items and badges.

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/138970322-d9bc25ca-fd90-4293-a98f-5155759bdf95.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
