### ISSUE TITLE
Skills not working on Rayquaza

### ISSUE THREAD

**Issue by Marianamystery** [SmashMC-Development/Bugs-and-Issues#619]
**Describe the Bug**
Some of the skills on Rayquaza aren't working, the two I've noticed so far are the crafting and mining skills, though there might be others.

**To Reproduce**
(Crafting)
1. Type the '/skills' command
2. Click on 'Skills and Abilities' and then 'Crafting'
3. Select the first ability to 'Store/summon crafting bench'
4. Read the steps listed there, and exit the skills window to try the steps, find out that it just opens the crafting menu normally instead of storing the crafting bench as advertised.
(Mining)
1. Type the '/skills' command
2. Click on 'Skills and Abilities' and then 'Mining'
3. Select the first ability of 'Miners Madness'
4. Read the steps listed there, and exit the skills window to right click with the pickaxe, find out that it does nothing, it doesn't give you speed nor haste that it should.

**Servers with the Bug**
Rayquaza.

**Expected behavior**
The crafting table to be stored so it could be summoned, and the veins of ore to be mined.

**Screenshots**
'N/A'.

**Additional context**
I don't know how to fix the skills, so can someone look into it and see what is needed to fix it?

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
