### ISSUE TITLE
Glows Needs to be updated

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Bugs-and-Issues#62]
**Describe the Bug**
The are some glows that are duped for say.

**To Reproduce**
1. Go to /glow
2. hover over the glows
3.  You can see some glows are the same as others

**Servers with the Bug**
all

**Expected behavior**
All ranks in games are supposed to have different glows rewards. Meaning there should be a different glow from getting idol, rogue, expert, professor, and master. 

**Screenshots**
![image](https://user-images.githubusercontent.com/82547638/116324652-1e418a00-a786-11eb-994c-39910c6f704c.png)
![image](https://user-images.githubusercontent.com/82547638/116324671-27325b80-a786-11eb-9528-5fe9de3d9849.png)

**Additional context**
Players should be getting a different glow, for each rank upgrade in game(imo). IT keeps players grinding for those glows and being duped glows seems to destroy that

**Comment by HackuJacku** [comment]
Same issue as #48
