### ISSUE TITLE
Nidoran (male) doesn't evolve into Nidorino

### ISSUE THREAD

**Issue by Awholemess** [SmashMC-Development/Bugs-and-Issues#621]
**Describe the Bug**
I'm trying to fill my dex, and when my Nidoran got to the level it evolves at, and it said "Nidoran (male) evolved into Nidoran (male)"
**To Reproduce**
1. Level up Nidoran (male)
2. Watch it not evolve, but the game registers it as evolved

**Servers with the Bug**
Rayquaza

**Expected behavior**
I expected my Nidoran evolve into Nidorino.

**Comment by Mikirae** [comment]
This is a Pixelmon bug. Please open a ticket and someone can help you force evolve it :)
