### ISSUE TITLE
Dex claim not giving proper rewards

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#622]
**Describe the Bug**
Got 15% dex and didnt get ranch block mentioned in rewards

**To Reproduce**
1. get 15% dex 
2. claim rewards only to realize you cant get ranch block
3. make github ticket

**Servers with the Bug**
Rayquaza ( not sure about other servers

**Expected behavior**
should get ranch block from rewards.

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/138984108-1f7b2b98-febd-4fc4-8801-d06ea84d2052.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Fixed. Thank you :)
