### ISSUE TITLE
Skills not giving proper rewards at milestone levels

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#623]
**Describe the Bug**
Got lvl 60 barbarian and said it gave me two random pokemon papers but it gave me to specific ones instead.

**To Reproduce**
1. get lvl 60 barb
2. see rewards as 2 random mons
3. open inv to see specific mon papers

**Servers with the Bug**
Rayquaza ( possibly all)

**Expected behavior**
skills need to give proper rewards

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/138984332-203f826b-d336-4415-813b-fdcbea41a81a.png)
![image](https://user-images.githubusercontent.com/82549364/138984372-a58c10e7-06d6-41c9-b21d-136404fff6a8.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Fixed for next restart. Thank you! :)
