### ISSUE TITLE
Groudon pressure plate not working and glitchy

### ISSUE THREAD

**Issue by Tridemo** [SmashMC-Development/Bugs-and-Issues#624]
**Describe the Bug**
When stepping on the groudon pressure plate it gives you a missing no. which then immediatly crashes your game

**To Reproduce**
1. Go inside the groudon
2. Step on the pressure plate
3. See if it bugged out

**Servers with the Bug**
Groudon Server

**Expected behavior**
Upon stepping on the pressure plate i shouldve gotten a shint groudon

**Screenshots**
N/A

**Additional context**
It might not be repeatable as this feels more like a one time bug, but you can try to repeat it

**Comment by Tridemo** [comment]
*shiny

**Comment by Mikirae** [comment]
What pressure plate are you talking about?

**Comment by ghost** [comment]
lol the one in sirud's video

**Comment by Mikirae** [comment]
The only thing that one does is say "Get trolled noob" when you step on it. Lol
