### ISSUE TITLE
Galar Farfetch'd won't evolve

### ISSUE THREAD

**Issue by Bkdevileu** [SmashMC-Development/Bugs-and-Issues#625]
The conditions to evolve the farfetch'd are: Leek as held item and crit 3 times in a battle but it won't evolve after you do that; ex: used slash + leek for 100% crit, attacked 3 times getting 3 crits and it didn't evolve once the battle was done

**To Reproduce**
Crit 3 times with leek equiped, finish battle and it won't evolve

**Servers with the Bug**
Atleast Kyurem, probably all others as well, should be a Pixelmon mod bug

**Expected behavior**
Evolve after reaching the requirements

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
