### ISSUE TITLE
Picking up items and Placing blocks

### ISSUE THREAD

**Issue by Jack69Inches** [SmashMC-Development/Bugs-and-Issues#626]
**Describe the Bug**
When i drop something out of my inventory and go to pick up something different it wont allow me to and i cannot place blocks
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre

**Expected behavior**
Being able to pick up items and place blocks
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
You will need to provide the exact steps to reproduce this, as required in the format above instead of editing a single line.

**Comment by Superfire96** [comment]
I'm pretty sure a simple relog would have fixed your issue, closing this up
