### ISSUE TITLE
Just a skill level up description wrongly inputted in system

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Bugs-and-Issues#627]
**Describe the Bug**
Level 15 skill got a missing word or character in it.

**To Reproduce**

**Servers with the Bug**
Groudon

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77503363/139071752-796a0952-16ac-450e-9b88-e40678e18cda.png)

**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
