### ISSUE TITLE
no move relearners

### ISSUE THREAD

**Issue by descry13** [SmashMC-Development/Bugs-and-Issues#628]
i beleive move relearners should be added back to the game as /buymove is over expensive and does not contain certain moves that can be learnt by the pokemon for example with galar zapdos it cant learn thunderous kick , i guarentee the majority of people will agree with me on the move relearner coming back .

also when battle bond greninjas kill a pokemon in battle they dont transform this is a bug

**Comment by HackuJacku** [comment]
This is a suggestion, please create a suggestion rather than a bug report.
