### ISSUE TITLE
/discord and /link dont work

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#629]
**Describe the Bug**
When trying to use the /discord and /link commands it seems the command is broken.

**To Reproduce**
1. Go to any server
2. Use either /discord or /link
3. Unknown command error appears

**Servers with the Bug**
All servers.

**Expected behavior**
/discord should take you to a page with an invite to the discord server and /link should bring you to the messages with the bot where you need to send the link code.

**Screenshots**
![Screenshot (744)](https://user-images.githubusercontent.com/45851395/139088602-e0031ad1-3256-40f5-ad90-3feaeca2ecd0.png)

**Additional context**
N/A.

**Comment by HackuJacku** [comment]
#557
