### ISSUE TITLE
Pokebank duplication glitch

### ISSUE THREAD

**Issue by Bama09** [SmashMC-Development/Bugs-and-Issues#63]
**Describe the Bug**
Open up Pokebank and it dupes his pokemon every time, when he adds a pokemon to his bank it literally disappears but when he takes it out it duplicates in his inventory and stays in the pokebank

**To Reproduce**
1. Opens up pokebank
2. Click on the pokemon he wants and drags it in his inventory
3. profit
4. ?

**Servers with the Bug**
Please provide a list of which servers have this bug.
All of them
**Expected behavior**
Fix the bug or the market will crash
**Screenshots**
https://gyazo.com/0d51652bb8352d86003a9b37fce1fa39
**Additional context**

**Comment by HackuJacku** [comment]
@Bama09 - please can you test this again? I spoke to @Mikirae and he said that he was unable to reproduce it after we updated a plugin associated to PokeBank.

**Comment by Bama09** [comment]
i ask the dude about it and his pokemon disappeared that he dupe so i think
its fixed

**Comment by HackuJacku** [comment]
@Bama09 - if there are still issues, please re-open the issue and post here.
