### ISSUE TITLE
Pc misword

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#630]
**Describe the Bug**
Wording is incorrect on Gifting PC when achieving level 10in skills

**To Reproduce**
Get to level 10 in skill e.g. Mining look at what the massage says
**Servers with the Bug**
Kyurem minimum, pretty sure it is on all servers

**Expected behavior**
Say "PC" instead of "C"
**Screenshots**
![image](https://user-images.githubusercontent.com/86004012/139091052-500ff400-32e9-4aad-a433-226bd8ea8925.png)

**Comment by jahangir6969** [comment]
I have had a look and it seems to be now fixed. If this is still a issue please let me know.
