### ISSUE TITLE
Raid Dens glitched 

### ISSUE THREAD

**Issue by Awholemess** [SmashMC-Development/Bugs-and-Issues#631]
**Describe the Bug**
When I click on any Pokémon den that has light coming out of it, it says that there’s nothing in the den. I seem to be the only one having the issue. I have tried relogging, /hub, even using my own wishing pieces to trigger the den, but nothing has worked.

**Servers with the Bug**
Rayquaza

**Expected behavior**
If there is a den that has a raid in it, I should be able to battle in said raid. 
![image](https://user-images.githubusercontent.com/93045551/139094433-f3b632fb-da5f-4e26-bd3d-aae35a7af963.jpg)

**Comment by Superfire96** [comment]
I believe that might have been just an issue on your end, most likely a visual bug. Eitherway it should be fixed
