### ISSUE TITLE
Bad lag on Ray

### ISSUE THREAD

**Issue by Awholemess** [SmashMC-Development/Bugs-and-Issues#632]
**Describe the Bug**
Every minute or so, there is a severe lag spike for everyone that lasts about 15-30 seconds.

**To Reproduce**
1. Go on Ray
2. Wait a few minutes
3. Experience the lag

**Servers with the Bug**
Rayquaza

**Expected behavior**
Staff has reset the server multiple times, but it never fixes it.

**Comment by HackuJacku** [comment]
Being looked into.
