### ISSUE TITLE
Payed for wz and wasnt teleported but given timer

### ISSUE THREAD

**Issue by AbleChaos** [SmashMC-Development/Bugs-and-Issues#633]
**Paid for wz not teleported but given timer**

**To Reproduce**
1. Go to 'zekrom 
2. Click on '/wz '
3. Scroll down to 'not teleported
4. See error given timer without teleport

**Servers with the Bug**
Zekrom maybe others

**Expected behavior**
Teleport to wz

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed in next version of Warzone.
