### ISSUE TITLE
Server lagging a lot

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#634]
**Describe the Bug**
Reshiram has been lagging allot, and as far as im aware so are all the other pixelmon servers.

**To Reproduce**
Steps 
Join server, and it's laggy

**Servers with bug**
All pixelmon ones.
**Expected behavior**
Needs to be unlagged if possible :D

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Being looked into.
