### ISSUE TITLE
Player Entering Warzone and not being teleported to Warzone

### ISSUE THREAD

**Issue by Grunt064** [SmashMC-Development/Bugs-and-Issues#635]
**Describe the Bug**
Player pays for time in warzone, but does not get teleported to warzone instead to spawn or random location. 

**To Reproduce**
1. /warzone
2. Pay for time

**Servers with the Bug**
Currently only Zekrom

**Expected behavior**
Teleported into warzone

**Screenshots**
![image](https://user-images.githubusercontent.com/89787272/139133749-8b46b773-57df-419b-a7e7-a0a4d28a1669.png)

![image](https://user-images.githubusercontent.com/89787272/139133796-580ccd4d-6cfd-4485-9f64-aaedebb54cda.png)

**Additional context**
Has happened as this bug report only 3 times to 1 player.

**Comment by HackuJacku** [comment]
Tested, unable to reproduce.
