### ISSUE TITLE
Wz log

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#637]
**Describe the Bug**
when the opponent logs in warzone when fighting you don't get to steal
**To Reproduce**
1. Go to wz
2.  fight someone
3. have them /hub

**Servers with the Bug**
only tested on kyurem

**Expected behavior**
your able to steal from them,
**Screenshots**
n/a

**Additional context**
haven't been able to test with myself, only happened with a  ticket

**Comment by HackuJacku** [comment]
Fixed from next reboot.
