### ISSUE TITLE
Groudon Training Level 20-40 Pokemon dont spawn

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#638]
**Describe the Bug**
Pokemon dont spawn in Level 20-40 area

**To Reproduce**
1. Go to Groudon
2. Go to Level 20-40 Training area
3. Nothing Spawns

**Servers with the Bug**
Groudon

**Expected behavior**
Pokemon should spawn

**Screenshots**
![2021-10-27_22 37 08](https://user-images.githubusercontent.com/84816052/139151390-2f9fe5c0-2bea-482a-ba17-c63aa3e6fc0f.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
