### ISSUE TITLE
You can bring thunderstone and shulker boxes to warzone (idk if its intentional)

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#639]
**Describe the Bug**
You can bring thunderstone and shulker boxes to warzone. You can also bring Potions apparently.

**To Reproduce**
1.  Put the items in your inventory
2.  Go to warzone
3. Keep items and they dont get put in the bag

**Servers with the Bug**
Tested on Kyurem prob all

**Expected behavior**
Shouldnt be able bring these items

**Screenshots**
![2021-10-27_19 22 10](https://user-images.githubusercontent.com/84816052/139151942-f8b50dfd-ff80-46c5-886a-a3bcfdb7c2dd.png)

![2021-10-26_22 48 01](https://user-images.githubusercontent.com/84816052/139151965-d254afcd-d5e2-407a-8d87-cd5e192961b6.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Intentional, they provide you with zero benefits :P
