### ISSUE TITLE
Moltres spawns instead of Galarian Moltres in warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#640]
**Describe the Bug**
Moltres spawns instead of Galarian Moltres in warzone

**To Reproduce**
1. Go to warzone
2. Wait for a Galarian Moltres to spawn
3. Spawns a Moltres instead

**Servers with the Bug**
Seen on Kyurem possibly all

**Expected behavior**
Should spawn Galarian Moltres 

**Screenshots**
![2021-10-27_16 30 19](https://user-images.githubusercontent.com/84816052/139152309-3e62fb2f-b8a2-4ea8-be69-586fecb6048a.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Dwag0n** [comment]
to add onto this, it also doesnt spawn galarian zapdos or galaraian articuno, and has the normal birds instead have no screenshots atm will return once I get some

**Comment by HackuJacku** [comment]
Fixed in next version.
