### ISSUE TITLE
Pokemon appear on Journey Maps

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#641]
**Describe the Bug**
Pokemon appear on Journey Maps

**To Reproduce**
1. Go to any server
2. Look at Journey Map
3. See Pokemon

**Servers with the Bug**
All

**Expected behavior**
Shouldn't be able see Pokemon as it is like having radar 

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/139152562-31f63165-1a74-4b5f-82dc-cff7870e12a2.png)
![image](https://user-images.githubusercontent.com/84816052/139152600-957579b0-fc9a-467b-81be-db3771535ff7.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Nothing on our end that we can do to fix it, players will have to deactivate them. Or if found out they are using it, will be counted as a pixel radar
