### ISSUE TITLE
Cannot show Pokemon in chat

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#642]
**Describe the Bug**
Cannot show Pokemon in chat

**To Reproduce**
1. Go to Rayquaza
2. Try show a pokemon
3. Doesnt work

**Servers with the Bug**
Rayquaza

**Expected behavior**
Should be able show pokemon

**Screenshots**
![2021-10-27_23 12 07](https://user-images.githubusercontent.com/84816052/139154812-dbe264e2-b59e-4c38-979f-16b03d0cce62.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Works fine.
