### ISSUE TITLE
Cant put items on GTS

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#643]
**Describe the Bug**
Cannot put items for sale on GTS

**To Reproduce**
1. Go to any server
2. Do /gts
3. Try list an item
4. Pulls up your pokemon instead of items

**Servers with the Bug**
All

**Expected behavior**
Should be able list items

**Screenshots**
![2021-10-27_23 48 13](https://user-images.githubusercontent.com/84816052/139158290-c5f5b0f4-5488-48a6-b935-5059fdeb7e94.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by M1n0j** [comment]
https://www.youtube.com/watch?v=NyFVm2yzwNQ

**Comment by HackuJacku** [comment]
Switched to Waterdude's GTS
