### ISSUE TITLE
Wild Gym Battle Error

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#644]
**Describe the Bug**
Cannot Battle Gyms and it gives error message

**To Reproduce**
1. Go to any server
2. Try Battle any wild spawning Gym
3. See error

**Servers with the Bug**
Tested on Kyurem prob all

**Expected behavior**
Should be able battle the wild Gyms

**Screenshots**
https://studio.youtube.com/video/Dbn48rog58A/edit

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Pixemon battle glitch. Forwarded onto Pixelmon.
