### ISSUE TITLE
You can still Fly in warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#645]
**Describe the Bug**
You can still fly in warzone if u have a rank that allows u to

**To Reproduce**
1. Go to warzone
2. Have a rank that allows you to fly
3. Be able to fly around warzone

**Servers with the Bug**
All

**Expected behavior**
You shouldnt be able fly

**Screenshots**
https://www.youtube.com/watch?v=5wkHOVNKRck

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed in next version.
