### ISSUE TITLE
ThunderStone does provide you with benefits in warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#646]
**Describe the Bug**
ThunderStone provides benefits in warzone

**To Reproduce**
1. Go to warzone
2. Wear Thunderstone
3. Go way faster than normal

**Servers with the Bug**
Tested on Kyurem possibly all

**Expected behavior**
Shouldn't go way faster

**Screenshots**
https://www.youtube.com/watch?v=e5iD8YHz63I

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed in next version.
