### ISSUE TITLE
Pokeball throw is too slow to fight people in warzone when running

### ISSUE THREAD

**Issue by CharonXXIII** [SmashMC-Development/Bugs-and-Issues#647]
**Your poke ball can't throw long enough to hit a person if they're running, so it's very hard to hit people with in War zone Pokémon**
So when I'm in warzone 

**To Reproduce**
1. Go to 'war zone or any place you can throw a poke ball
2. Throw out your poke ball, and you'll see that the throw distance isn't the best 
3. try throwing your Pokémon while running in the warzone or outside warzone

**Servers with the Bug**
Groudon, could be others too.

**Expected behavior**
Well it should be a lot faster due to it being too slow to actually hit a running player

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed in next version.
