### ISSUE TITLE
Mining skill Magnet Field Not Working

### ISSUE THREAD

**Issue by DaedricWaffles** [SmashMC-Development/Bugs-and-Issues#648]
**Describe the Bug**
The Ability in Mining skill called " Magnet Field " does not work.
I've used the Ability plenty of times in the old Dialga server but on this one it does not seem to work.

It is not disabled in my Skill tab just to be clear.

**To Reproduce**
1. Get to Mining level 75? or 100 and left click the block straight under you.
2. This should in theory trigger the ability.

**Servers with the Bug**
Reshiram but might be in all servers.

**Expected behavior**
The magnet field to trigger and magnetise the items to me.

**Screenshots**
/

**Additional context**
/

DaedricWaffles

**Comment by Mikirae** [comment]
Had this issue with a different mining skill as well, whatever the first one is. Will report this to the dev :)

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
