### ISSUE TITLE
TNT can go off and damage all the realms

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#65]
**Describe the Bug**
TNT can explode and damage the world (every realm unless stated otherwise in servers)

**To Reproduce**
1. Set TNT on the ground.
2. Activate it by sending it off
3. It will explode and damage the realms

**Servers with the Bug**
Rayquaza (only the nether), Jirachi, Deoxys, Darkrai, Giratina, Palkia, Dialga and Mew (on all realms)

**Expected behavior**
TNT shouldn't go off and damage the world

**Screenshots**
/

**Additional context**
/

**Comment by Rasgnarok** [comment]
Did you test this for yourself, or on a normal player?

**Comment by LifelessDingus** [comment]
I tested this myself on all servers but Rayquaza and Charizard (Limo tested there for me as I don't have access to creative on those two servers). I made sure I wasn't overriding claims though.

**Comment by LifelessDingus** [comment]
The initial report came from a player though. Sorry forgot to mention that in the last comment.

**Comment by Rasgnarok** [comment]
Fixed on all servers
