### ISSUE TITLE
Afk

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#650]
**Describe the Bug**
Anyone can /afk

**To Reproduce**
do /afk U dont need a rank or anything 

**Servers with the Bug**
zekrom 

**Expected behavior**
I shouldn’t /afk

**Screenshots**
n/a 

**Additional context**
N/a

**Comment by Superfire96** [comment]
I don't see any issue with them being able to /afk, it is working as intended
