### ISSUE TITLE
Some problems with /claimflag

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#651]
**Describe the Bug**
tested Snow trail from snowman - doesn't work inside the claim, trail is created outside claim
water isn't flowing even though water flow is enabled, water flows outside the claim.

**To Reproduce**
1. create claim
2. put down water bucket, create snowman
3. same thing that is described should happen

**Servers with the Bug**
only tested on kyurem

**Expected behavior**
water flows when its enabled in the claim
snowman trail is made when its enabled in the claim

![2021-10-28_21 50 19](https://user-images.githubusercontent.com/83971987/139334143-9457a5be-fbad-4fae-8c3c-0dc0e8d5b2d7.png)
![2021-10-28_21 49 32](https://user-images.githubusercontent.com/83971987/139334159-31ed3fb1-503f-4816-829e-a15525589ff6.png)

**Comment by Superfire96** [comment]
It is an old issue that should be now fixed
