### ISSUE TITLE
Gym leaders missing on rayquaza

### ISSUE THREAD

**Issue by DragonBoyz12** [SmashMC-Development/Bugs-and-Issues#652]
Hello Hacko my name is DragonBoyz i play on rayquaza and I noticed today that the electric, Steel and dragon gym leaders are missing. i need the electric as that is the gym I am on and I feel this is an inconvenience to players who do the gyms . So please try and fix this as fast as you can so that i can battle the elite 4 :)  

From DragonBoyz

**Comment by Mikirae** [comment]
Respawned them all. Thank you! :)
