### ISSUE TITLE
Ha from eggs

### ISSUE THREAD

**Issue by CardStatue** [SmashMC-Development/Bugs-and-Issues#653]
**Describe the Bug**
When someone has a ha and they send you a egg after they breed and you can /hatch it and sometimes you get to become the Ot and sometimes nothing shows up on the ha. Once they hatch it they can breed it and get a ha with them being the ot

**To Reproduce**
1. Breed a ha 
2. Send the egg to someone else
3. Hatch it and see if you get to be the ot or no name for the ot
4. You can breed it and get a ha with you being the ot

**Servers with the Bug**
Rayquaza
**Expected behavior**
Eco broken

**Screenshots**

**Additional context**
 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
