### ISSUE TITLE
Caught Pokémon not crossed off on /dex

### ISSUE THREAD

**Issue by Its-JER** [SmashMC-Development/Bugs-and-Issues#654]
**Describe the Bug**
Caught Pokémon not crossed off on the Missing Pokémon list on the /dex command 

**To Reproduce**
1. type /dex
2. Click Missing Pokémon
3. See error

**Servers with the Bug**
Kyurem (most likely all)

**Expected behavior**
Caught Pokémon would have an X over or say caught when hovered above

**Screenshots**
File attached
![2021-10-28_22 15 01](https://user-images.githubusercontent.com/93055693/139362602-40c72536-a733-44e1-8bbb-689d751539c7.png)
![Inked2021-10-28_22 17 21_LI](https://user-images.githubusercontent.com/93055693/139362727-39198df7-12c1-4c5e-8f44-feabfe633175.jpg)

**Comment by Mikirae** [comment]
I'll report this. Thank you! :)

**Comment by HackuJacku** [comment]
Forwarded to the developer.

**Comment by HackuJacku** [comment]
Fixed
