### ISSUE TITLE
Raid dens

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#655]
**Describe the Bug**
you can move raid dens with the warlock lvl 10 ability 

**To Reproduce**
1. Go to a raid den
2. use the spell to move an entity 
3.  see that you moved it

**Servers with the Bug**
all

**Expected behavior**
you cant move the den

**Screenshots**
![2021-10-28_20 29 37](https://user-images.githubusercontent.com/83245837/139364229-dc0b54af-8f63-4877-9f0c-891285206415.png)
![2021-10-28_20 29 58](https://user-images.githubusercontent.com/83245837/139364258-a9a3efe8-403b-4177-83ed-3eea92e9b475.png)
(you can see it moved

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
This ability is being removed. Thank you! :)
