### ISSUE TITLE
Desert Fishing/Omega Shards

### ISSUE THREAD

**Issue by Bigchamp123** [SmashMC-Development/Bugs-and-Issues#657]
**Describe the Bug**
The loot table is non-existant, if you do /checkspawns fishing while fishing, you'll see that it is always Macargo 50% and Torkoal 50%, meaning there is a 0% chance to get an item, and therefore no Omega shards. 

**To Reproduce**
1. Go to 'Lava in desert'
2. Click on 'Fishing rod and start fishing'
3. type in chat '/checkspawns fishing' while fishing
4. See error and no regular chance of 15% loot 

**Servers with the Bug**
Zekrom

**Expected behavior**
A chance of an item 

**Screenshots**

![2021-10-29_15 45 47](https://user-images.githubusercontent.com/51046123/139455578-cf6334e5-4f08-4584-9155-9c29cb275cb3.png)

**Comment by Mikirae** [comment]
I think this is a Pixelmon bug and it doesn't show items from fishing anymore. Just tried on a fresh server and had the same issue.
