### ISSUE TITLE
Acrobatics afk abuse

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#658]
**Describe the Bug**
AFKable Acro skills 

**To Reproduce**
Go to ultra-space, hold jump

**Servers with the Bug**
All

**Expected behavior**
Probably not gain xp

**Screenshots**
N/A

**Additional context**
nop

**Comment by Mikirae** [comment]
Will look into a way to fix this. Thank you :)

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
