### ISSUE TITLE
Dailies dont show

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#659]
**Describe the Bug**
Some dailies dont provide a description of what needs to be done

**To Reproduce**
go to a server
type /dailies
hover over the ideas
Some dont provide u with instructions on how to complete it.

**Servers with the Bug**
Reshiram (i think all)

**Expected behavior**
I would expect some instructions on how to complete it once i hover over it.

**Screenshots**
![2021-10-29_17 51 28](https://user-images.githubusercontent.com/87021826/139465463-ea615f35-f573-4113-9700-412853dfab27.png)

**Additional context**
NA

**Comment by Mikirae** [comment]
Currently asking the dev. Thank you!

**Comment by Superfire96** [comment]
Fixed, let me know which ones are still not showing
