### ISSUE TITLE
Players are able to wondertrade pokemons that are in ranch blocks, the player who gets it will find it stuck inside of a ranch block

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Bugs-and-Issues#66]
**Describe the Bug**
Players are able to wondertrade pokemons inside ranch blocks, when another player receive the pokemon it will be stuck inside of a ranch block 

**To Reproduce**
1. Put a pokemon in a ranch block
2. Wondertrade it 
3. Player who receive it will find it stuck

**Servers with the Bug**
All

**Expected behavior**
Pokemon wondertraded are not stuck or are not able to being traded

**Comment by Rasgnarok** [comment]
This really should not be possible if you were using the Forge version @HackuJacku . I can just swap them tonight if you'd like.

**Comment by HackuJacku** [comment]
@Rasgnarok - if you're happy to, would be amazing. Just looked myself, we're currently using Simon's GUI version.

**Comment by HackuJacku** [comment]
Fixed when we update to 8.2.

**Comment by HackuJacku** [comment]
Changes are now live.
