### ISSUE TITLE
weird money glitch

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#660]
**Describe the Bug**
Whenever u get money on for example kyogre (idk like 200K) and then go to a server u have never played on like reshiram you will start with the money amount that you had on a previous server. People have started to join Reshiram and already have 250K. made another github once where i said money transfers over but that turned out to be wrong but maybe this is what happened then.

**To Reproduce**
Play on a random server and earn a lot of money.
Go to another server you have never played on
You will start with the money amount that you had on the previous server.

**Servers with the Bug**
Every single one

**Expected behavior**
Start with 0 money

**Screenshots**
NA

**Additional context**
NA

**Comment by Mikirae** [comment]
This was a bug that was since fixed. If you're joined the server, you will still have that amount of money and there's nothing we can do except prevent it in the future unfortunately :(
