### ISSUE TITLE
Vote party count resets when the server does

### ISSUE THREAD

**Issue by mnky-frt** [SmashMC-Development/Bugs-and-Issues#661]
**Describe the Bug**
I was on Reshiram the other day and we had about 80 votes left for the vote party and then the scheduled restart happened. When I got back into the server the vote party was back at 300. With the time I've spent on the server, I've only been in 1 vote party despite seeing people vote all the time. I think this glitch is why there have been very little vote parties.

**To Reproduce**
Just look at vote count before reset then look at it afterwards. It will be back at 300

**Servers with the Bug**
Reshiram, may be others

**Expected behavior**
Vote party count should not reset when server does

**Screenshots**
N/A

**Additional context**
Before reset I dont think it worked like this which is why I'm reporting this bug

**Comment by Mikirae** [comment]
Will see if I can get in contact with the developer about this. Thank you for reporting!

**Comment by HackuJacku** [comment]
Forwarded to the developer.

**Comment by HackuJacku** [comment]
Fixed.
