### ISSUE TITLE
Plants don't grow in claims

### ISSUE THREAD

**Issue by Elibats** [SmashMC-Development/Bugs-and-Issues#662]
Pumpkins, melons and berries don't grow in my claim and the water doesn't flow.

**Steps to reproduce the behavior:**
1. Go to your claim or create a new one
2. Plant pumpkins or melons
3. Wait a bit
4. They don't grow

**Server:**
Kyurem but may also affect other servers

**Expected behaviour:**
They should grow

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Elibats** [comment]
NB Apricorn plants grow and work as they're intended inside the same claim

**Comment by Superfire96** [comment]
The issue should be fixed
