### ISSUE TITLE
Galarian Birds not being galarian when spawned in warzone.

### ISSUE THREAD

**Issue by Frittz** [SmashMC-Development/Bugs-and-Issues#663]
**Describe the Bug**
Articuno, Zapdos and Moltres being spawned in warzone in galarian form but they aren't galarian.

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Duplicate issue, will be closing but this is being worked on! :)
