### ISSUE TITLE
someone set reshiram warzone on fire

### ISSUE THREAD

**Issue by unfiltxred** [SmashMC-Development/Bugs-and-Issues#664]
so i found out recently by accident that it is possible to set claimed places like wz on fire with the weird wizard gem thing and didnt tell anyone
it appears another player found this out and made a huge fire trail in warzone
pls fix ;-;
![image](https://user-images.githubusercontent.com/71754649/139495071-22b0709f-ab79-473a-b287-a6204f8f0dd7.png)

**Comment by Mikirae** [comment]
This should be fixed after restart. Thank you for the report :)
