### ISSUE TITLE
money loss on move learner

### ISSUE THREAD

**Issue by HamzaHassan8993** [SmashMC-Development/Bugs-and-Issues#665]
**Describe the Bug**
mony is deducted for move learner on pressing confirm which when you don't learn the move the money is lost

**To Reproduce**
1. Go to move learner
2. select any mon
3. select any move which is not known to the mon
4. press confirm
5. then stop teaching this move and exit
6. the money is deducted even if did not learn the move

**Servers with the Bug**
Rashiram may be other

**Expected behavior**
if cancled money should be returned or tm of the move be given
 be given.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Is this with /buymoves? (That NPC in the spawn opens this menu)

**Comment by Rasgnarok** [comment]
Closing, ticket is no longer up to date thanks to latest fixes to stat files.

**Comment by HamzaHassan8993** [comment]
That issue has been resolved
