### ISSUE TITLE
missing poke stop at spawn

### ISSUE THREAD

**Issue by ColonCrusader** [SmashMC-Development/Bugs-and-Issues#666]
**Describe the Bug**
at /warp bosstower there appears to be a spot where there is no poke stop where there should be one
**To Reproduce**
1. go to /warp boss
2. walk down stairs to turn
3. look at stop location
4. there isn't one there

**Servers with the Bug**
i know on reshiram, but not sure about other servers

**Expected behavior**
i expected to collect the poke stop, but it wasn't there
![thumbnail_image (2)](https://user-images.githubusercontent.com/92840415/139510551-c01d4aaa-3dab-43f5-babd-fb1e2fcdaf5b.jpg)
![thumbnail_image (1)](https://user-images.githubusercontent.com/92840415/139510553-54238aec-8a2b-4e4a-ae9d-573d52b8bfbf.jpg)

**Comment by Mikirae** [comment]
Fixed. Thank you :)

**Comment by ColonCrusader** [comment]
Appreciate it, thank you!
