### ISSUE TITLE
In a claim when no one has claimed the area

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Bugs-and-Issues#667]
**Describe the Bug**
The message "You don't have permission to build in this persons claim" stays on my screen with a random persons name the entire time I'm on groudon no matter how far away I go, do /rtp, go to spawn or even go to my own frickin claim. Restarting my computer and minecraft does not fix it.

**To Reproduce**
N/A (Dont know what caused this, wasn't in anyones claim when I logged off)
I was on Reshiram then logged onto Groudon and suddenly the message "You don't have permission to build in (insert name here)'s claim" popped up and will not go away

**Servers with the Bug**
Only experiencing this on Groudon

**Expected behavior**
"You do not have permission to build in this person's claim" message stays on the entire time im in Groudon.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![IMG_2730](https://user-images.githubusercontent.com/93420175/139521834-c80a29b8-0101-4f89-8988-a25e4bd09357.jpg)
![IMG_2729](https://user-images.githubusercontent.com/93420175/139521842-d0491958-8cb9-43e1-b26e-e861c0a66700.jpg)

**Additional context**
After leaving my claim the message disappears temporarily then comes right back :/

**Comment by Mikirae** [comment]
Ironically, I'm actually having the exact same issue right now. 
![image](https://user-images.githubusercontent.com/24925669/139558610-b1786c7d-cdef-424a-ad2b-e4721273d9d8.png)

I'll contact the developer and see if we can get it fixed :)

**Comment by MarissaSins** [comment]
Oh wow lol, I wasn't sure if I was the only one experiencing this or not. Thank you :D!

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
