### ISSUE TITLE
Buymoves not working on some moves

### ISSUE THREAD

**Issue by Restlezzz** [SmashMC-Development/Bugs-and-Issues#668]
**Describe the Bug**
A lot of Pokemons are unable to learn Knock-off such as Weavile, Conkeldurr, Ferrothorn, Clefable, Bisharp.
Sucker punch is also not available for Pokemon such as Bisharp. 
Pokemon such as Zapdos, Peliper, Dragonite, Hydreigon are unable to learn Defog. 
Unable to learn Heal-bell on Clefable and Dragonite when they should. 
Alolan Marowak and other mons such as Golurk and Deciduiye can't learn Poltergeist.
Rotom are unable to learn pain split. 
**To Reproduce**
1. Go to '/buymoves'

**Servers with the Bug**
Kyurem, but I assume all the server has this issue.

**Expected behavior**
/buymoves unable to get moves in pokemon movepool.
**Screenshots**
[https://gyazo.com/c5f827c7387d52d4dbae4a7d8c34c6ac](url)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Will report this. Thank you!

**Comment by HackuJacku** [comment]
Added to master ticket.
