### ISSUE TITLE
No Pixelmon loot in lootable containers.

### ISSUE THREAD

**Issue by DaedricWaffles** [SmashMC-Development/Bugs-and-Issues#669]
**Describe the Bug**
No Pixelmon loot in lootable containers.

**To Reproduce**
1. Go to any looatable container ex. Dungeons, mineshaft,....
2. Open the container, it will only hold Minecraft Vanilla loot.

**Servers with the Bug**
Reshiram

**Expected behavior**
Was looking for Pokeloot like Tidal and Clear bells and stumbled upon this issue.

**Comment by HackuJacku** [comment]
Intended.
