### ISSUE TITLE
Ev area bugged

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#67]
**Describe the Bug**
Unable to use the pcs and heal stations at /warp evs. 

**To Reproduce**
Go to /warp evs on rayquaza and try to use the heal stations or pcs it won’t work

**Servers with the Bug**
Rayquaza

**Expected behavior**
The pcs and heal stations work so u can heal/switch your Pokémon

**Comment by HackuJacku** [comment]
Same issue as #15
