### ISSUE TITLE
Chunks not loading

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#670]
**Describe the Bug**
Whenever I go to Mart and tp back to my build, the same chunk doesn't load and I have to relog in order to fix it.

**To Reproduce**
1. Go to my house
2. Go to mart
3. Tp back (using /back)
4. Occasionally the chunks won't load and you have to relog in order to fix  

**Servers with the Bug**
Groudon

**Expected behavior**
Chunks to be loaded

**Screenshots**
![Minecraft 1 12 2 30_10_2021 09_47_54 - Copy](https://user-images.githubusercontent.com/86555718/139526700-842933b9-af2a-4ffe-904e-850d8186b910.png)

**Comment by DaedricWaffles** [comment]
Try pressing F3+A, this reloads the chunks without having to relog.

**Comment by Mikirae** [comment]
As the other person said, F3 A fixes this. It's unfortunately a Minecraft/lag bug that we can't fix. That's a sick looking house though

**Comment by Dxhcky** [comment]
Ah okay thank you, although I don't have the function buttons on my keyboard so it's easier to just relog
