### ISSUE TITLE
Vaults

### ISSUE THREAD

**Issue by DragonBoyz12** [SmashMC-Development/Bugs-and-Issues#672]
my user is DragonBoyz and i play on ray i have expart rank but my vaults dont show up and i would like to put my legend papers in there but i cant it would be very appriciative if i can get my vaults so i stop taking so much room in chests and invantory

**Comment by Mikirae** [comment]
Just making sure on this, have you tried relogging? Most people had to relog before getting theirs.

**Comment by Mikirae** [comment]
Found the issue and hopefully fixed it. Let me know if it's fixed when you next log in please? :)

**Comment by DragonBoyz12** [comment]
nope i still cant get the vaults and i dont see any and have relogged

**Comment by Mikirae** [comment]
I believe that we actually need to wait for a server restart. After the server restarts tonight, mind telling me if you still need the vaults? :)

**Comment by DragonBoyz12** [comment]
sure

**Comment by DragonBoyz12** [comment]
sorry to say this miki but no its not back i still dont have vaults

**Comment by DragonBoyz12** [comment]
unless there were no resets last night

**Comment by HackuJacku** [comment]
Fixed.
