### ISSUE TITLE
wz bugs!

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#673]
**Describe the Bug**
1. The pokeballs thrown out in wz don't go in a straight line. It makes it hard to engage other players in battle.
2. Once you engage players in battle, the gui sometimes give them option to decline battle.
3.  Galarian Birds are spawning as normal.

**Servers with the Bug**
Groudon.

**Comment by Mikirae** [comment]
I've reported all three of these to the dev. Thank you :)

**Comment by ghost** [comment]
Found 1 more. After battle with wild pokemon in wz pokemon are healed but status conditions are not.

**Comment by HackuJacku** [comment]
Fixed in next version.
