### ISSUE TITLE
Dosent work to Right-click the crates

### ISSUE THREAD

**Issue by Xwiftzee** [SmashMC-Development/Bugs-and-Issues#674]
**Describe the Bug**
So when i go to the crates in-game when i right-click them to check the possible rewards u can get then it just shows nothing

**To Reproduce**
1. Go to /warp crates
2. Right-click one of the crates
3. Nothing happens

**Servers with the Bug**
Kyurem

**Expected behavior**
I expected it to show me the possible rewards i could get from the crate

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
I see the issue and will get to work on fixing it. Thank you for the report! :)

**Comment by Mikirae** [comment]
Fixed!
