### ISSUE TITLE
No move relearner at mart anymore 

### ISSUE THREAD

**Issue by RenExiled** [SmashMC-Development/Bugs-and-Issues#675]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Not sure what server this is as you didn't put it, but I checked earlier and they're all back :)

**Comment by ghost** [comment]
I can't find them anywhere at mart. Where are they located at spawn?

**Comment by Mikirae** [comment]
Wait that’s my fault. I thought you were talking about the Move Tutor. For the Relearner, make a suggestion on the Suggestions GitHub please :D

**Comment by ghost** [comment]
already did :)
