### ISSUE TITLE
Battles Resulting in Critical Error

### ISSUE THREAD

**Issue by TheHumbleJames** [SmashMC-Development/Bugs-and-Issues#676]
[latest.log](https://github.com/SmashMC-Development/Bugs-and-Issues/files/7447927/latest.log
[2021-10-30-5.log.gz](https://github.com/SmashMC-Development/Bugs-and-Issues/files/7447928/2021-10-30-5.log.gz)
)
Over the last couple minutes in Reshiram, every battle I engaged in ended up being a critical error. Ras told me to report it here. After the third restart, I could finally battle normally.

**Comment by HackuJacku** [comment]
Pixelmon battle glitch, forwarded to Pixelmon.
