### ISSUE TITLE
Modpack Rewards Not Redeemings

### ISSUE THREAD

**Issue by JackDietz** [SmashMC-Development/Bugs-and-Issues#677]
**Describe the Bug**
After Downloading the Modpack through Technic and playing it through the modpack, it still does not redeem the modpack rewards, when I type /modpack it says I don't have it even though I have installed what it asked me to

**To Reproduce**
1.  Do /modpack and download the pack through technic
2. Through technic launcher, play the Pixelmon Modpack
3. Enter the SmashMC server and enter a Pixelmon server
4. Do /Modpack

**Servers with the Bug**
Kyurem, I have only played this server

**Expected behavior**
When downloading the modpack, I expected to either immedietly get the rewards upon login or do /modpack to redeem them

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
 N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Could you please show me what it says/said when you do /modpack so that we can get this fixed? :)

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
