### ISSUE TITLE
Sweet scent does NOT work

### ISSUE THREAD

**Issue by JohannErasure** [SmashMC-Development/Bugs-and-Issues#678]
**Describe the Bug**
Sweet scent only encounters zubats no matter the biome you are in

**To Reproduce**
Sweet scent in any biome

**Servers with the Bug**
Not sure if all of em do but kyogre does

**Expected behavior**
to sweet scent the mon that's supposed to spawn for that biome, for example slowpoke should have 100% sweet scent chance in beach but a zubat comes up instead
**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
It matters the time of the day, i've just tested it and it is working correctly
