### ISSUE TITLE
Apricons not growing

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#679]
**Describe the Bug**
Apricons are not growing on their own.

**Servers with the Bug**
Groudon

**Comment by Mikirae** [comment]
Is this inside of a claim or outside?

**Comment by ghost** [comment]
it is inside the claim

**Comment by Bkdevileu** [comment]
From what I tested, they seem only to grow when you're near them, once you leave the claim/go offline they stop growing

**Comment by ghost** [comment]
ye I was in ultraspace fishing all the time....and they were right next to me....still not growing

**Comment by Superfire96** [comment]
Looks like they are properly growing now
