### ISSUE TITLE
Warzone spawns

### ISSUE THREAD

**Issue by Bryceisright** [SmashMC-Development/Bugs-and-Issues#68]
**Describe the Bug**
Warzone legendaries seem to be spawning at an increased rate and regularly spawning out side barrier blocks

**To Reproduce**
Sit in warzone

**Servers with the Bug**
Palkia 

**Expected behavior**
Warzone shouldn’t be spawning 15+ legendaries in an hour with only 2 people in warzone.

**Additional context**
It might just be good luck.

**Comment by HackuJacku** [comment]
@Bryceisright - I've tried to fill as many spots I can find but please can you screenshot areas where the legendaries spawn in the future? I've also decreased the Warzone rates slightly.
