### ISSUE TITLE
Zekrom cant learn Ddance

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#680]
**Describe the Bug**
Zekrom Cant Learn Ddance

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to warp mart
2. Try to learn ddance with buymove

**Servers with the Bug**
Kyruem

**Expected behavior**
Zekrom can learn ddance

**Screenshots**
'N/A'.

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
Added to master ticket.
