### ISSUE TITLE
/Kit Smash

### ISSUE THREAD

**Issue by ehhhkody** [SmashMC-Development/Bugs-and-Issues#681]
**Describe the Bug**
/Kit Smash is supposed to reward:
Smash Kit (daily cooldown) 
15x Rare Candies!
32x Ultra Balls!
64x Great Balls!
96x PokéBalls!

I recently purchased the rank and am only recieving
4x Rare Candies!
16x Ultra Balls
24x Great Balls
32x PokéBalls!

**To Reproduce**
Purchase Smash rank directly
Claim your daily kit

**Servers with the Bug**
Zekrom

**Expected behavior**
I expect to get the kit as advertised

**Screenshots**
N/A

**Additional context**
N/A

**Comment by DaedricWaffles** [comment]
Same here, Since wipe I haven't gotten full kit daily a single time.

**Comment by ghost** [comment]
This is a problem on Groudon too. Moreover, paid ranks holders are not getting priority when the servers are full.
![Screenshot (461)](https://user-images.githubusercontent.com/25759066/139592986-46dc06f0-1f7b-486e-a122-03d033c014b6.png)
.

**Comment by Mikirae** [comment]
I believe the kits got changed, but I could also be stupid. Will talk it over with the other managers when they're available. Please be patient with us :)
As for the priority, I think that's currently a bug with the plugin. I'll have Khan look into it

**Comment by ehhhkody** [comment]
> I believe the kits got changed, but I could also be stupid. Will talk it over with the other managers when they're available. Please be patient with us :) As for the priority, I think that's currently a bug with the plugin. I'll have Khan look into it

Haven't heard anything, but the kits are still wrong.

**Comment by Superfire96** [comment]
Indeed that's the kit, can be seen in the announcement

![image](https://user-images.githubusercontent.com/83550357/163593168-7e6f58c5-5a2d-4ceb-84ba-0ed779c0d4e0.png)
