### ISSUE TITLE
/pwiki broken

### ISSUE THREAD

**Issue by Awholemess** [SmashMC-Development/Bugs-and-Issues#682]
**Describe the Bug**
when I type in the command /pwiki to see how to evolve a certain pokemon, it doesn't show up in chat, and afterwards, my player can't move.

**To Reproduce**
1. Type in /pwiki (pokemon)
2. Wait for the command to attempt to execute
3. Try and move your character around after nothing shows up.

**Servers with the Bug**
Rayquaza

**Expected behavior**
I expected to get information on the pokemon, not for my character to not be able to move.

**Comment by Mikirae** [comment]
I'm having trouble reproducing this. Is it every time, or did it just happen once?
![image](https://user-images.githubusercontent.com/24925669/139642690-8ba0cf6d-2c91-46a1-9656-51bce96d94e6.png)

**Comment by Awholemess** [comment]
It was happening with the Whismur line. I didn’t try it with anything else.

**Comment by Superfire96** [comment]
Was fixed
