### ISSUE TITLE
Smash Rank not getting priority queue when server is full

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#683]
**Describe the Bug**
Smash rank is not getting priority queue when server is full.

**Servers with the Bug**
Groudon

**Screenshots**
![Screenshot (461)](https://user-images.githubusercontent.com/25759066/139623252-646e3b12-2ba7-42e7-b9cd-8fc16fc8dff5.png)

**Comment by Bkdevileu** [comment]
Paid ranks never had prio queue, only staff have prio queue

**Comment by ghost** [comment]
According to Ras and Miki, it was mythic+ earlier and now they have changed it to legend+. I am smash and it is not working for me. Moreover, check the screenshot
![Screenshot (464)](https://user-images.githubusercontent.com/25759066/139717448-847cd621-cb71-4038-8944-69516c3d6364.png)
.

**Comment by Mikirae** [comment]
We're currently working on getting this fixed :)

Question, do you go to the front of the queue and are unable to join the full server, or are you just put to the back of the queue?

Also, what did it do prior to reset? Push you to the front, or just allow you to join the full server?

**Comment by ghost** [comment]
I had legend rank before the reset. Pretty sure never waited in line expect during restarts but I am not sure.

**Comment by HackuJacku** [comment]
This is not a bug, you're misunderstanding what exactly the difference. Smash players can join the server WHEN it is full but they  do not bypass the queue. If they are in position 1 of the queue and the server is full, they'll be able to join. This is not a bug. All ranks have had to wait in the queue, only staff have ever had queue priority.
