### ISSUE TITLE
Players placing boats all over spawn

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#684]
**Describe the Bug**
Players are able to place boats at spawn. I don't know how but I have added a screenshot.

**Servers with the Bug**
Groudon

**Screenshots**
![Screenshot (462)](https://user-images.githubusercontent.com/25759066/139623752-e2128b4c-8b35-4495-b789-2e4082e078d2.png)

**Comment by Mikirae** [comment]
They shouldn't be able to put them down anymore. Thank you for the report! :)
