### ISSUE TITLE
Vote crate money rolls don't add to balance

### ISSUE THREAD

**Issue by met21** [SmashMC-Development/Bugs-and-Issues#685]
**Describe the Bug**
Vote crate didn't add any money to my balance, I expected it to go up.

**To Reproduce**
1. Vote
2. Get crates
3. Roll money 
4. See that your balance remains unchanged

**Servers with the Bug**
I'm assuming all

**Expected behavior**
To receive moneys

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
From what I can tell, it's working just fine on our end. Just rolled a billion crates and got all the money.

**Comment by HackuJacku** [comment]
Not a bug, working fine.
