### ISSUE TITLE
Fix boss drops!

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#686]
**Describe the Bug**
Most of the boss drops are things you can't sell at mart like fossils, berries etc. For a server that is trying to base it's economy on items, it is pitiful. We were told that it was fixed but doesn't seem like it. Please take a look into this. (This doesn't include Raid Boss, they are fine after the nerf)

**Servers with the Bug**
I play on Groudon but assuming it applies for all.

**Comment by Mikirae** [comment]
Starting off here by saying that not everything will be able to be sold. Like berries can be farmed infinitely so they're never going to be sold to the shop. If you'd like to see them removed, please make a ticket in suggestions rather than here :)

**Comment by ghost** [comment]
You have completely misunderstood the point I was trying to make and have closed the thread prematurely. Like I said if you would have read carefully, "majority of the drops are not sellable". Since, selling items is the main method of making money of the server, you should really look into into it.
