### ISSUE TITLE
No move relearner at /warp mart on the server rayquaza and I’ve looked everywhere nothing is there

### ISSUE THREAD

**Issue by RenExiled** [SmashMC-Development/Bugs-and-Issues#687]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by RenExiled** [comment]
And I DO NOT MEAN /BM OR THE BUY MOVE PERSON

**Comment by Superfire96** [comment]
Move relearner was added some time ago, fixed
