### ISSUE TITLE
Smelting Ability Twinned Smelt Broken.

### ISSUE THREAD

**Issue by DaedricWaffles** [SmashMC-Development/Bugs-and-Issues#688]
**Describe the Bug**
Smelting Ability Twinned Smelt doesn't do anything eventhough it says it triggered.

**To Reproduce**
1. Unlock Twinned Smelt Ablitity [Lvl 100]
2. Smelt Items..
3. Take the smelted items out
4. Ability tiggers but has no effect.

**Servers with the Bug**
Reshiram [Possibly others]

**Expected behavior**
Double the Smelted output [The skill displays this behaviour]

**Comment by Mikirae** [comment]
I'll report this to the dev, thank you!

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
