### ISSUE TITLE
Galar zapdos 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#689]
**Describe the Bug**
galar zapdos in wz spawns a regular zapdos 

**To Reproduce**
1. Wait for a galar zapdos to spawn in wz then it will be a regular Zappos when u find it 

**Servers with the Bug**
zekrom 

**Expected behavior**
to find a regular zapdos

**Screenshots**
n/a

**Additional context**
n/a

**Comment by HackuJacku** [comment]
Fixed in next version.
