### ISSUE TITLE
Gym Server Crash

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#69]
**Describe the Bug**
Trying to join a npc gym on charizard will close the server.

**To Reproduce**
Try to join the Dark gym on char
see server close
deal with angry players
wait for server to start again

**Servers with the Bug**
Charizard(will test other servers as this is part of a testi am doing for hunger and will comment if there are any more

**Expected behavior**
server shouldn't crash upon a npc gym join

**Screenshots**
N/A

**Additional context**

**Comment by HackuJacku** [comment]
@Shoji007 - I attempted to reproduce this and the server did not crash. I spent around 5 minutes here before leaving.

**Comment by HackuJacku** [comment]
@Shoji007 - we tested this together and could not reproduce. If it occurs, please re-open the ticket.
