### ISSUE TITLE
Status effect 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#690]
**Describe the Bug**
status effects don’t get healed in wz

**To Reproduce**
1. When u kill a Pokémon u don’t get ur status effects healed 

**Servers with the Bug**
zekrom

**Expected behavior**
status effects should get healed 

**Screenshots**
n/a

**Additional context**
n/a

**Comment by HackuJacku** [comment]
Fixed in the next version of Warzone.
