### ISSUE TITLE
Warlock skill

### ISSUE THREAD

**Issue by BoolinHeavy** [SmashMC-Development/Bugs-and-Issues#691]
**Describe the Bug**
When clicking on the skill for warlock, you will be disconnected from the respective server, and set back to hub
**To Reproduce**
1. Go to /skills
2. Click on skills and abilties
3. Click warlock

**Servers with the Bug**
Please provide a list of which servers have this bug.
All servers

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
