### ISSUE TITLE
Possible dupe bug

### ISSUE THREAD

**Issue by Grunt064** [SmashMC-Development/Bugs-and-Issues#692]
**Describe the Bug**
At times players are getting the same legendary more than once when catching in Warzone. They catch a Legend and it is sent to their PC and their Warzone Bank. So they are able to retrieve both legends.  

**To Reproduce**
1. Go to Warzone
2. Catch Legend
3. Sent to PC and Warzone Bank
4. Get both Pokes

**Servers with the Bug**
All

**Expected behavior**
Only able to retrieve one Legend from Bank

**Screenshots**
![image](https://user-images.githubusercontent.com/89787272/139743256-fb82d8f7-7ae3-4465-8833-a0a003af99b6.png)
![image](https://user-images.githubusercontent.com/89787272/139743439-241623af-9589-4504-9bc1-e3a60c83c1f9.png)

![IMG_1720](https://user-images.githubusercontent.com/89787272/139743634-1cdab77f-b655-420a-8e44-96090eab32f7.jpg)
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed in next version
