### ISSUE TITLE
Pokemon spawning like in warzone

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#693]
**Describe the Bug**
Normal spawning pokemon where spawning at the levels of pokemon that would spawn in warzone, and this was in the overworld.

**To Reproduce**
this just happend, there wasnt any steps to go with it.

**Servers with the Bug**
Reshiram from what i know.

**Expected behavior**
they shouldnt spawn that higher level.

**Screenshots**
![Screenshot (157)](https://user-images.githubusercontent.com/89798207/139745148-b40bc2ff-2295-4eb4-bd60-f049b594ad96.png)
![Screenshot (156)](https://user-images.githubusercontent.com/89798207/139745180-c81767d8-8ec8-4acd-aa3f-c11048f51c6b.png)
![Screenshot (158)](https://user-images.githubusercontent.com/89798207/139745195-e932a858-d56d-440b-9236-2400e1bb2d7d.png)

**Additional context**
i was in a friend base, that was hollowed out, not sure if that correlates.

**Comment by Mikirae** [comment]
Had you visited Warzone recently?

**Comment by RatedPG21** [comment]
Pretty sure he meant that Pokémon were spawning at around the same level that they would in warzone, you see the lvl 100 camerupt, they shouldn’t be spawning at that lvl

I think that’s what he means :)

**Comment by WalkAway7** [comment]
I hadn't been to warzone before this, at all, but ad I said. It may be because there were a few other people around me aswel, and I don't think this is meant to happen

**Comment by WalkAway7** [comment]
UPDATE: I have just been to the place where I saw these pokemon, and they are still the same level, and these chunks haven't been loaded for a long time.

**Comment by DaedricWaffles** [comment]
Hey, That's my hole

Lol didnt know it was broken lol

**Comment by HackuJacku** [comment]
Not a bug, Pixelmon feature.
