### ISSUE TITLE
TNT Damage is on

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#695]
**Describe the Bug**
Players bases / claims can be greifed by TNT cannons

**To Reproduce**
1. Go to someones claim
2. use a tnt cannon to move tnt into the claim
3. It goes boom and damage is done

**Servers with the Bug**
Seen on Zekrom possibly all

**Expected behavior**
TNT damage shouldnt be on

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
Fixed for next restart.
