### ISSUE TITLE
Pvp Enabled. bug or feature? Grief Defender commands related.

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#696]
**Describe the Bug**
Not sure if bug or feature.... but people can enable pvp on their claims. one has to be the owner of the claim in order to do it.

**To Reproduce**
1. Go to your claim
2. type in /claimflagdefinition Minecraft:user pvp true/false
3. enjoy the slaughter/and turn it off whenever

**Servers with the Bug**
Rayquaza.... mostlikely all since its a GD issue or feature

**Expected behavior**
A Decision on if its a bug that needs fixed or a feature due to Leamy saying its not allowed on claims.(this was spoken about in Rayquaza VC and miki and Tillul in dms on discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/139822856-3552fdff-35fe-4f41-9054-3ff0400919c5.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Not a bug.
