### ISSUE TITLE
Tournament bug

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#698]
**Describe the Bug**
The tournament does not give a team when you start and no award when you win.

**To Reproduce**
1. go in server and wait for tourney to start
2. Join the tournament and see no team given 
3. When you win you don't get a key either

**Servers with the Bug**
Rayquaza

**Expected behavior**
The tournament should give a team to use when starting it and a reward when winning the tournament.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
At the moment tournament are decided with rock paper scissors by messaging staff.

**Comment by HackuJacku** [comment]
Fixed
