### ISSUE TITLE
no ot on warzone mons

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#699]
**Describe the Bug**
warzone pokemon dont have an ot

**To Reproduce**
1.  go to warzone
2. catch pokemon
3. when you come out they dont have an OT

**Servers with the Bug**
reshiram from all i know

**Expected behavior**
they shoudl have an OT

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/139839356-38be5860-0de6-4d0c-b1b5-ee0446e898f0.png)
![image](https://user-images.githubusercontent.com/89798207/139839368-28005908-15fd-406f-8980-e0f047fe1bad.png)
![image](https://user-images.githubusercontent.com/89798207/139839379-6f44297a-9378-4407-9043-82b4401af716.png)

**Additional context**
i also caught a urshifu using an mball but its in a pokeball for some reason

**Comment by HackuJacku** [comment]
Fixed in next version.
