### ISSUE TITLE
Missing elevator

### ISSUE THREAD

**Issue by Bryceisright** [SmashMC-Development/Bugs-and-Issues#70]
**Describe the Bug**
The elevator block has been replaced by stone bricks.

**Servers with the Bug**
Dialga 

**Expected behavior**
You should be able to go to the top floor of mart but cannot without flying.

**Screenshots**

![4BECC92F-24F7-4386-B53E-4DD77D8BEC78](https://user-images.githubusercontent.com/83260769/116809758-0fdae000-ab83-11eb-8c2d-6747a9c81bd1.png)

**Comment by HackuJacku** [comment]
Fixed.
