### ISSUE TITLE
Female Battle bond greninja

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Bugs-and-Issues#701]
**Describe the Bug**
A clear and concise description of what the bug is. Female battle bond greninja (Can´t be)

**To Reproduce**
Go to a swamp catch a female greninja and it can be a battle bond but on the wiki it says 100% male ratio, We tried to breed the greninjas but it says they dont get along we tried with 2 bb grens so its only the gender thats the bug.
**Servers with the Bug**
Rayquaza dont know about the other servers never seen anything like this

**Expected behavior**
Should be male 100% and 0% chance for a female so its impossible but its a bug.
**Screenshots**
![image](https://user-images.githubusercontent.com/86523809/139861525-27992579-c440-43b9-97e2-9520cdbbefe1.png)
https://medal.tv/clips/70116250/d1337fmciVvi?invite=cr-MSxsQkIsNzkxMTI3Nyw 

**Additional context**
No :)

**Comment by HackuJacku** [comment]
Shouldn't be female but provides no benefit so not worried.
