### ISSUE TITLE
Battle Bond More common

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Bugs-and-Issues#703]
**Describe the Bug**
A clear and concise description of what the bug is. I feel like Battle bond greninjas are less common rn people seem to get them faster than before.

**To Reproduce**
Go to swamp catch greninjas, but it seems that battle bond greninjas have a higher chance to spawn.
**Servers with the Bug**
Battle bond greninjas have a higher chance to spawn it seems from fishing, more people are getting them from fishing then it was before dont know if the chance have changed but they seem less rare.

**Expected behavior**
Battle bond greninjas should be more rare but im not sure

**Screenshots**
https://pixelmonmod.com/wiki/Fishing

**Additional context**
Nope

**Comment by HackuJacku** [comment]
Nothing has changed with their spawning, not a bug. Please create a suggestion instead
