### ISSUE TITLE
Flying mons falling through leaves

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Bugs-and-Issues#705]
**Describe the Bug**
Flying pokemon fall through leaf blocks in cold taiga & cold taiga hill 

**To Reproduce**
1. Go to ultra space. 
2. Make a platform of leaves.
3. Wait for flying mons to spawn especially fletchling.
4. Walk close to them and see them fall through the leaves.

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre

**Expected behavior**
Usually they do not fall through leaves.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
I have not tried other biomes, but I would quess it is the same problem there

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
