### ISSUE TITLE
Warlock skill

### ISSUE THREAD

**Issue by FadeFire** [SmashMC-Development/Bugs-and-Issues#706]
**Describe the Bug**
Whenever i click the Warlock skill symbol it kicks me back to the lobby
**To Reproduce**
1. Go to '/skills'
2. Click on 'The Warlock Skill/The endereye'
3. See error

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre
**Expected behavior**
-
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
-
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
-

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
