### ISSUE TITLE
Crafting ability Possibly broken.

### ISSUE THREAD

**Issue by DaedricWaffles** [SmashMC-Development/Bugs-and-Issues#707]
**Describe the Bug**
Hello I spent a good majority of a few days grinding a skill to unlock, upon unlocking the ability I find that It does not work and or I am to dumb to use It

Ability In question is from the "Crafting Skill" [Lvl150 Ability] Equivalent Exchange.

The Ability states that I need to Activate It by left clicking materials on a craft table, Ive tried a good 50 different materials and nothing activates the ability or does anything with the crafting table.

**To Reproduce**
1. Get to Crafting Skill 150
2. Do as the ability description describes.
3. Nothing happens

**Servers with the Bug**
Reshiram but most likely everywhere

**Expected behavior**
I'm not sure I just wanna use it tbh..I played ProjectE alot and It's cool but I presume this is different.

**Screenshots**
![dfsgssfdsdf](https://user-images.githubusercontent.com/93023375/139963453-13ea044b-a9ed-45be-a990-9bd833c6284b.png)

Big Hole Guy,

**Comment by DaedricWaffles** [comment]
After further testing I found that 6 items can be used in this, For a Lvl 150 and top tier ability that's a bit of a middle finger...

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
