### ISSUE TITLE
Cant force battle in Warzone

### ISSUE THREAD

**Issue by AyanamiBestWaifu** [SmashMC-Development/Bugs-and-Issues#708]
**Describe the Bug**
Same as last time cant force battle in warzone again
**To Reproduce**
1. Go to rayquaza
2. Click on Warzone
3. See error

**Servers with the Bug**
I can only go rayquaza warzone so thats all I know
**Expected behavior**
you should be able to force battle in warzone

**Screenshots**
N/A
**Additional context**
When this is fixed can you guys also make it so you have increased pokeball throwing range again

**Comment by HackuJacku** [comment]
Fixed in next version.
