### ISSUE TITLE
GTS doesn't give money to the user once they sell something

### ISSUE THREAD

**Issue by mnky-frt** [SmashMC-Development/Bugs-and-Issues#709]
**Describe the Bug**
A friend of mine tested this yesterday because I was selling my unused Poipoles on GTS and I wasn't getting any money from them at all when they were sold. I checked the claimed trades and timed out trades and nothing is there

So basically, when you buy something on GTS that person spends the coins to buy it but the user who puts it up does not get those coins. Idk where they are going but from the testing I've done I have not gotten any of my money back when I actually sold something on GTS

**To Reproduce**
1. do /gts
2. Put a pokemon up on gts for any amount
3. Have someone buy the pokemon
4. They will have spent their coins but you do not get any of them that were spent on the pokemon you sold

**Servers with the Bug**
Reshiram, maybe all

**Expected behavior**
User who sells the pokemon should get the coins that were used to buy it

**Screenshots**
N/A but if needed I can screenshot the whole process on buying/selling on gts

**Additional context**
N/A

**Comment by ghost** [comment]
I think you have to claim the coins from stash in gts, not sure though.

**Comment by mnky-frt** [comment]
> I think you have to claim the coins from stash in gts, not sure though.

I've tried looking in the 'Claim Trades' and 'Timed out trades' nothing is there

**Comment by Restlezzz** [comment]
This is true gts doesn't work. If someone buys the listing you posted, the listing is just gonna vanish without you receiving the money.

**Comment by HackuJacku** [comment]
Replaced GTS with Waterdude's version.
