### ISSUE TITLE
Manectite won't drop from crate

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Bugs-and-Issues#71]
**Describe the Bug**
When you win a Manectite from the megastone crate it will not drop into the inventory of the player

**To Reproduce**
1. Go to /warp crates
2. Click on Megastone crate
3.  Win Manectite, item will be not given to the player 

**Servers with the Bug**
Charizard, potentially all 

**Expected behavior**
Manectite is correctly given into players inventory

**Comment by HackuJacku** [comment]
@Lun17 - tested on both Charizard and Deoxys, works fine. All servers use the same config so I can confirm this not an issue.
