### ISSUE TITLE
Cant Sell Balm Mushrooms At mart

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#711]
Issue: So I can not sell Balm Mushrooms At warp mart and idk if its on purpose but the description says I can sell them the shop keepers
Whats Suppose to happen: I should be able to sell them to shop keepers

Server with issue: Kyruem, but idk on the others

**Comment by Superfire96** [comment]
Was fixed
