### ISSUE TITLE
Kyogre Bugs

### ISSUE THREAD

**Issue by Rh1Ys3** [SmashMC-Development/Bugs-and-Issues#713]
**Describe the Bug**
First bug: Not able to force battle in warzone
Second bug: Players can fly in warzone
Third bug: Pokeballs with pokemon inside of them dont travel at the rapid speed the server used to have making it harder to force battles when the inability to force battles in warzone bug is fixed
Fourth bug: No ability to use any form of commands in warzone such as /msg
Fifth bug: Status conditions are left on pokemons even after battles
Sixth bug: Gym trainers are not at their respective gyms

**To Reproduce**
First bug: Go in warzone and attempt to attack someone
Second bug: If rank permissions permit attempt to fly in warzone
Third bug: Go in warzone and throw the pokeball out
Fourth bug: Attempt to direct msg using /msg in the warzone
Fifth bug: Recieve a status condition such as poison from a pokemon and warzone and kill the wild pokemon and the status condition will still be there. Do the same with a pvp battle as the same bug occurs.
Sixth bug: Warp to the gyms and see that the gym trainers aren't there

**Servers with the Bug**
Kyogre

**Expected behavior**
First bug: Battles should be able to be forced in warzone
Second bug: Players shouldn't be able to fly in the warzone
Third bug: Players should be able to "snipe" others in warzone with balls that travel high speeds and longer distances like before the reset
Fourth bug: Players should be able to use a small assortment of commands such as /msg in the warzone
Fifth bug: Status conditions shouldn't be left on player pokemons after battle
Sixth bug: Gym trainers should be at the gyms so we can be able to attempt to defeat the gyms

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
Every bug mentioned is now fixed
