### ISSUE TITLE
Helper and smash issue

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#716]
**Describe the Bug**
So I have helper and smash and I can only have 3 claims and 3 houses

**To Reproduce**
1. Go to any server
2. have helper and smash
3. try to make more then 3 homes
4. u cant

**Servers with the Bug**
Groudon, Kyreum

**Expected behavior**
Shouldnt smash give more homes?

**Screenshots**
'N/A'.

**Additional context**
'N/A'.

**Comment by Shoji007** [comment]
Last i was staff i didnt get any extra homes or claims for being a staff member.... but smash should indeed give extra homes giving you 15 in total( as stated on the shop since its 12 additional)the weight issue of ranks here is what's conflicting.

**Comment by Bkdevileu** [comment]
Staff ranks kinda override the paid ranks leading to this, happened to me as well, you need to ask a manager to fix it ^_^

**Comment by Superfire96** [comment]
Was fixed
