### ISSUE TITLE
/link in game does not work

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#718]
**Describe the Bug**
/link is an unknown command 
**To Reproduce**
1. Go to any server
2. type /link
3.  See error

**Servers with the Bug**
Please provide a list of which servers have this bug.
all servers
**Expected behavior**
In the past, /link linked discord accounts with in game accounts. As far as I know there is currently no way to do that.
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
#557
