### ISSUE TITLE
Pokemons Ability changes once leaving warzone after catching it

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#719]
**Describe the Bug**
When u exit warzone the pokemons ability that u caught can change

**To Reproduce**
1. Go to warzone
2. Catch 4-5 Pokemon with 3 Abilities
3. Leave warzone
4. Check their abililties

**Servers with the Bug**
All
**Expected behavior**
The ability shouldnt change

**Screenshots**
https://youtu.be/VfCj7mc-aV8
https://www.youtube.com/watch?v=ciBPV39U1NA
**Additional context**
Can also change HAs abilities that are caught in warzone

**Comment by HackuJacku** [comment]
With the new version, what happens now please? I can't reproduce

**Comment by HackuJacku** [comment]
Fixed
