### ISSUE TITLE
Dialga chalice bugging out

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Bugs-and-Issues#72]
**Describe the Bug**
I was watching a guy put his last plate in the chalice at /warp shrines -> the azure flute didn't spawn and suddenly there are 2 random plates in (yet all the lights where still around him, see screenshot)

**To Reproduce**
Go to /warp shrines -> put all plates in

**Servers with the Bug**
Dialga

**Expected behavior**
Spawn the azure flute after all plates got put in

**Screenshots**
https://gyazo.com/2c18cc84dd35756521d62d7575a3a7ed

**Comment by Rasgnarok** [comment]
Does this still happen as of 8.2? Shrines have a different check now.

**Comment by Rasgnarok** [comment]
Just tested, looks fine for me. Flute spawned properly. Fixed by 8.2
