### ISSUE TITLE
Votes not registering when I'm not on pixelmon

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Bugs-and-Issues#720]
**Describe the Bug**
So this is the second time now that I voted BEFORE logging onto pixelmon, I was able to vote on 4 of the 5 sites, I still had to wait another 40min for the 5th site. After successfully voting on the 4 sites (reference below) I logged on and had 0/4 of my vote keys. I then waited for the 5th site (reference below) to reset and I voted while I had pixelmon OPEN. It worked just fine and I received my 1 key.

Sites that did not give keys WHILE LOGGED OFF - 
1. https://minecraftservers.org/server/548790
2. https://topminecraftservers.org/server/4609
3. https://pixelmonservers.com/server/LWblHaxC/smashmc
4. https://minecraft-server-list.com/server/464847/vote/

Site that gave key WHILE LOGGED ON -
1. https://minecraft-mp.com/server/211360/vote/

**To Reproduce**
1. Vote on any of the sites while logged off of pixelmon
2. Once all sites say you cannot vote again because you voted today log onto pixelmon
3. Go to vote crate and attempt to use votes like normal
4. Message pops up claiming you do not have any vote keys

**Servers with the Bug**
I only play on groudon so I am not sure if this happens on other serves

**Expected behavior**
Anytime you vote while logged off of pixelmon your votes will not count.

**Screenshots**
![vote](https://user-images.githubusercontent.com/93420175/140465994-eada734e-b531-41cd-9a7a-16fbd2675d4f.PNG)
![vote2](https://user-images.githubusercontent.com/93420175/140465996-f6272640-113d-436b-96b9-5411a3e0dea6.PNG)

**Additional context**
Screenshot one is from when I voted on the 4 sites while logged off of pixelmon, then logged on after I had voted to use my keys.
Screenshot two is from when I voted on the 5TH site while logged in and received my key.

**Comment by HackuJacku** [comment]
Fixed
