### ISSUE TITLE
You can Teleport People into warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#722]
**Describe the Bug**
You can Teleport People into warzone

**To Reproduce**
1. Go to any server
2. Use /tpahere before going to warzone or in warzone
3. Once inside the other person clicks accept
4. The person is now in warzone without paying

**Servers with the Bug**
All

**Expected behavior**
Shouldnt be able tp people to warzone

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
You may also be able to do this with /tpa

**Comment by HackuJacku** [comment]
Next version makes this useless, fixed.
