### ISSUE TITLE
You can set a Home in warzone

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#723]
**Describe the Bug**
You can set a Home in warzone

**To Reproduce**
1. Go to warzone
2. Do /sethome name
3. You can now go to warzone via /home name

**Servers with the Bug**
All

**Expected behavior**
Shouldn't be able set a home in warzone

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/140564139-4b8fd2ef-72e5-4cd3-ae42-e9b2bcc57397.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Next version makes these homes useless so fixed.
