### ISSUE TITLE
Warzone bug i found

### ISSUE THREAD

**Issue by DragonBoyz12** [SmashMC-Development/Bugs-and-Issues#724]
hello to all reading this I found a bug today. I went into warzone on ray for catching mons and legendry's but when I went to the warzone bank to get my rods I noticed I only had 5 that were in my inventory. I put my rods in a shulker before going to warzone as they were taking to much space. after I left I looked in the shulker and saw the rods still in there. thinking it may be a bug I went back in after cooldown and checked the shulker and there were the rods all sitting there I took one out and as I new they were banned In warzone I threw it just to be sure It was letting me throw the rod. I then made a ticket were superfire told me to make this github. I did go back in for one minute to throw the rod at wild pokemon and it did pull them.

I would advise that you ban shulkers so that this wont happen, as I am worried that if a player finds it out they will abuse it and use it to get people into battles

From:
DragonBoyz :)

**Comment by DragonBoyz12** [comment]
Describe the bug:
when you put rods in a shulker and bring the shulker to wz, you can use the rods to pull pokemon

How to reproduce:
1: take shulker with rods to wz
2: take rods out of shulker
3: throw rods around 

Expected behavior:
rods shouldn't be able to be taken to wz at all

Screenshots:
N/A

**Comment by Rasgnarok** [comment]
Fixed, shulker boxes are no longer allowed in Warzone.
