### ISSUE TITLE
Battle Error

### ISSUE THREAD

**Issue by TAJGAMING** [SmashMC-Development/Bugs-and-Issues#725]
**Describe the Bug**

**To Reproduce**
1. Go to -689 X 66 Y -971 Z cornins
2. Click on a traner

**Servers with the Bug**
Please provide a list of which servers have this bug.
sorry my english it not good

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Pixelmon battle bug, forwarded to them.
