### ISSUE TITLE
Raid den/Fossil machiene pokemon not counting towards bingo card

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Bugs-and-Issues#727]
**Describe the Bug**
Say you need a pokemon for your bingo card like MineJr, you find the raid den and you successfully catch it. For some reason even after successfully catching it, the pokemon does not get crossed off the bingo card.

I have also just run into this issue with my Arctozolt. I did a raid den for it, to no surprise it didn't count so I said okay fine maybe I just have to make the fossil for it. Just made the fossil, claimed it from the fossil machine WITH the bingo card in my hot bar and boom, still not crossed off my bingo card.

**To Reproduce**

OPTION 1 - 

1. Obtain any bingo card and find a raid den for said pokemon on the list
2. Successfully beat and catch the raid den pokemon (with the bingo card in your hot bar)
3. Open bingo card and see that the pokemon is not crossed off the list

OPTION 2 - 

1. Obtain any bingo card and find the fossil for said pokemon on the list
2. Successfully clean and put the fossil in the fossil machine and claim it with a pokeball (with bingo card in your hot bar)
3. Open bingo card and see that the pokemon is not crossed off the list

**Servers with the Bug**
I only play on groudon but I assume this affects all servers

**Expected behavior**
After catching a pokemon from a raid den/fossil machine that is needed for a bingo card, it does not count for some reason.

**Screenshots**
![bingo](https://user-images.githubusercontent.com/93420175/140620169-5b6a5144-341f-4a7d-8540-083d262e9c9b.png)
![fossil](https://user-images.githubusercontent.com/93420175/140620170-772b3ef1-2d74-4192-8099-61bd87c8815e.png)

**Additional context**
I attached the photos of my Arctozolt and bingo card showing that I "do not have it" apparently.

**Comment by HackuJacku** [comment]
Fixed in next version.
