### ISSUE TITLE
Kicked in Ice Dungeon

### ISSUE THREAD

**Issue by FroppyBloppy** [SmashMC-Development/Bugs-and-Issues#728]
**Describe the Bug**
So basically I was clearing the Ice Dungeon. After a while i had to fight an Alolan Ninetales in order to procede. Fight starts normally, until the swap pokemon screen suddenly comes up. I am forced to swap. As i click the new pokemon to send in the battlefield, i get kicked from the server, without any error issure showing up, losing my Daily dungeon try and my life orb put on my infernape (don't ask me about that, all i know is that as i log in again i'm sent to spawn and my infernape has no life orb... i even tried relogging, nothing happened). 

**Servers with the Bug**
As for now, apparently i'm the first one to have experienced this on the Rayquaza server!

Thanks for reading, hope that this will help in any way :)

**Comment by Superfire96** [comment]
Should be fixed
