### ISSUE TITLE
Warzone broken again

### ISSUE THREAD

**Issue by Epsteinj8056** [SmashMC-Development/Bugs-and-Issues#729]
**Describe the Bug**
Pokeball collision with players in wz does not force battle, and throwing the ball at the ground clips into the void. This makes it
impossible to battle in the wz

**To Reproduce**
go to warzone

**Servers with the Bug**
zekrom

**Expected behavior**
be able to battle in warzone

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Confirmed fix a couple of weeks ago.
