### ISSUE TITLE
Warzone: Band of person engaging decides if mega or dmax is possible in battle

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Bugs-and-Issues#73]
**Describe the Bug**
The band that the person engages is wearing will disable the band of the opponent if it's a different band. For example Hacko (wearing dynamax band) engages Ras (wearing a mega band) in a battle. Ras will not be able to Mega her pokemon even before Hacko tries to dynamax. **This goes both ways**

**To Reproduce**
1. Go into warzone with 2 players 1 wearing a dynamax band and the other wearing a mega band.
2. One of the 2 players engages the other and lets the other try using their band first, it will not work

**Servers with the Bug**
Palkia (might be other servers too)

**Expected behavior**
As for now, both Dmaxing and Mega in the same battle doesn't work. But it shouldn't be that the engager his band decides the possibilities in the battle. 

**Screenshots**
https://youtu.be/Hb8THHPkzIY

**Comment by HackuJacku** [comment]
@Sparklix - this is not possible to do. You can either make the world Dynamax only or Mega only. I've looked into it myself and been told that it's not possible and if it was, it would cause a lot of issues :(
