### ISSUE TITLE
Warzone Issue

### ISSUE THREAD

**Issue by CodeRRed08** [SmashMC-Development/Bugs-and-Issues#730]
**Describe the Bug**
Legendary pokemon are spawning in the warzone and are clearly seen in the chat. However, most are unable to be found. I haven't seen a legendary despawn in the chat since the restart earlier today. 

**To Reproduce**
1. Go to warzone
2. Wait for legendary to spawn (This happened to me for Arceus thrice, btw)
3. Try finding legendary
4. See error (no despawn notification in the chat)

**Servers with the Bug**
Groudon

**Expected behavior**
It was expected of legendaries to appear within the warzone boundaries, but it was almost impossible to find a single one since the server restart.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
I've confirmed that all Legendaries have spawned inside the Warzone, it's impossible for stuff to spawn outside. The matter of them being unable to be found is not a bug as using the debug tools I have available, all are able to be found.
