### ISSUE TITLE
Mega boss spawned as a NORMAL pokemon

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Bugs-and-Issues#732]
**Describe the Bug**
So on friday night I was flying around in extreme hills and encountered what I thought was a mega slowbro. It was completely normal tho, wasn't a different color, wasn't crazy large like the bosses, didn't have a boss tag and chat never said a mega slowbro had spawned on someone. 

Since I was doubting myself I thought it was just a galar slowbro or something. I encountered it in battle and everything went like a regular pokemon encounter, I was able to catch it as well. After catching it I hovered over the slowbro and was then able to CONFIRM it was a mega because under its form it listed MEGA. 

I feel really stupid for not taking a picture of the slowbro before battling it, I was just so confused and didn't think to screenshot anything till after I caught it.

To be clear, after catching it the slowbro had returned to its normal form and was not carrying a megastone or any item.

**To Reproduce**
I literally have no idea how to reproduce this since I was just exploring the extreme hills for thunder stone shards. So my best bet for you is to just go off and chop down some trees or something and pray the bug happens to you.

**Servers with the Bug**
I only play on groudon but this could be server wide.

**Expected behavior**
You find a normal mega boss in the wild and are able to catch it and interact with it as if it were a normal pokemon.

**Screenshots**
![A540DBA6-AE12-4610-BCF9-95BA7164126B](https://user-images.githubusercontent.com/93420175/140633752-3d67fc7a-98c9-4268-885a-93c0c4a21f9c.jpg)

**Additional context**
I only have this one picture of the mega slowbro unfortunately. I genuinely thought I was mixing up the mega with its galar form or something because I did not expect it to actually be a normal mega boss. But as you can see the form clearly states it was a MEGA slowbro.

**Comment by Superfire96** [comment]
I'm guessing it was fixed, as i have never seen anything like that after this
