### ISSUE TITLE
Still very difficult to engage ppl in battle in wz.

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#733]
**Describe the Bug**
It is still very difficult to engage people in battle in warzone. Ball speed has increased a little but not helping much. Moreover, when you do hit the player hitbox, you are not forced into battle most of the time.

**Servers with the Bug**
Groudon.

**Screenshots**
https://youtu.be/yUnjc7nExhE

**Comment by ghost** [comment]
Btw this is just the part where I got frustrated and started recording. I was chasing him for solid 2 minutes before that.

**Comment by HackuJacku** [comment]
@arjungangwar0 believe this is now fixed but would like confirmation please

**Comment by ghost** [comment]
@HackuJacku Ye the issue seem to be fixed now. Really appreciate the quick bug fixes. Keep up the good work. 

On a side note, I have noticed that it is difficult to engage flying legends in battle once they fly up. Throwing pokeballs straight up to towards them doesn't work like it use to before.
