### ISSUE TITLE
Status conditions are not healed after warzone battle ends.

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#734]
**Describe the Bug**
Status condidtions like burn, poison etc are not healed after battle is over in wz.

**Servers with the Bug**
Groudon

**Screenshots**
![Screenshot (478)](https://user-images.githubusercontent.com/25759066/140640070-60f2f2ea-b539-4032-91bb-4e3c0a4f4fa2.png)

**Comment by HackuJacku** [comment]
Fixed in the next version of Warzone.
