### ISSUE TITLE
Kyogre Bugs Pt.2

### ISSUE THREAD

**Issue by Rh1Ys3** [SmashMC-Development/Bugs-and-Issues#735]
**Describe the Bug**
Bug 1: Still can't force battles in the warzone
Bug 2: Once pokemon are thrown out of their balls they drop through the blocks and fall into the void
Bug 3: Flying is still able to be done in warzone
Bug 4: GTS is unresponsive

**To Reproduce**
Bug 1: Throw pokeball at a players hitbox and a battle wont be forced
Bug 2: Throw pokeball out in warzone and watch it go through the blocs
Bug 3: Rapid tap space bar and players will be able to glide around although not necessarily flying
Bug 4: Open GTS and click on anything in the GUI and it doesn't work

**Servers with the Bug**
Kyogre

**Expected behavior**
Bug 1: Warzone battles should be able to even happen
Bug 2: Once pokeballs hit the ground a pokemon should come out
Bug 3: No flying whatsoever should be able to be reproduced without an elytra
BUg 4: GTS should be responsive

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Closing, ticket contains several bugs that are unrelated. Every bug should be one ticket.
