### ISSUE TITLE
Kyurem has 2 Steel Gyms

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#736]
**Describe the Bug**
Kyurem has 2 steel gyms

**To Reproduce**
1. Go to Kyurem
2. Do /gyms
3. See 2 steel gyms (1 should be dragon)

**Servers with the Bug**
Kyurem

**Expected behavior**
The 2nd has gym should be dragon

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/140653796-79b76a78-94c5-481a-aa4d-6dc7f93c4ae6.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
