### ISSUE TITLE
All the Gym Rooms are incorrect to the leader typings on the server

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#737]
**Describe the Bug**
All the Gym Rooms are incorrect to the leader typings on the server

**To Reproduce**
1. Go to '.any server
2. Do /gyms and look at typings and go to the gym rooms and the typings are incorrect

**Servers with the Bug**
All expect Rayquaza

**Expected behavior**
Gym Rooms should be the same as the typings

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/140654581-a593256d-2287-480c-aaa2-59456131e0e5.png)
![image](https://user-images.githubusercontent.com/84816052/140654590-6940f042-5e35-44cc-84d6-b2c7fc274a37.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
