### ISSUE TITLE
Gyms in /Gym doesnt work

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#738]
**Describe the Bug**
All gyms in /gyms doesnt work. Also no NPCs are there

**To Reproduce**
1. go to any server and do /gyms
2. Try battle a gym leader
3. doesnt let you

**Servers with the Bug**
ALL except Rayquaza

**Expected behavior**
Should be able battle them and there should be NPCs standing there

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/140654774-b9c1759d-4960-4dc2-9f6a-de536ada6049.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
