### ISSUE TITLE
Wrong command on sign!

### ISSUE THREAD

**Issue by CaretsPuppy** [SmashMC-Development/Bugs-and-Issues#74]
**Describe the Bug**
Sign showing command /warp bosshouse is wrong, should be /warp boss (?) (Seems like it's outdated, I could potentially go in and change this if allowed)

**To Reproduce**
Look at the sign.

**Servers with the Bug**
All

**Expected behavior**
Correct command displayed.

**Screenshots**
N/A
![Jre1 8 0_271 Screenshot 2021 05 03 - 12 30 07 32](https://user-images.githubusercontent.com/82612312/116870923-54aa5980-ac0b-11eb-8b80-060473c6550e.png)

**Additional context**
Re-check if signs are up to date please, there could be more we're unaware of.

**Comment by AmsterDaan** [comment]
Fixed the signs so issue is closed
