### ISSUE TITLE
/pay isn't working

### ISSUE THREAD

**Issue by met21** [SmashMC-Development/Bugs-and-Issues#743]
**Describe the Bug**
/pay is broken, returns the syntax prompt when you attempt to pay another player.

**To Reproduce**
1. Type in the /pay command, i.e. /pay coins [username] [amt]
2. Receive the syntax prompt

**Servers with the Bug**
Zekrom, presumably all.

**Expected behavior**
I'd expect the command to pay the other user coins

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
