### ISSUE TITLE
Umbreon not leveling past level 71

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#744]
**Describe the Bug**
Umbreon not leveling past level 71, not by battle, not with rare candies and not with exp candies. Disabled leveling was also turned on and off so this shouldnt be the cause of it.

**To Reproduce**
1. Have ab umbreon
2. level it up to level 71
3. See that it wont level anymore

**Servers with the Bug**
Rayquaza

**Expected behavior**
It should level past 71.

**Screenshots**
N/A.

**Additional context**
Player who experienced the bug and owns the umbreon in question is entr.

**Comment by M1n0j** [comment]
i think this may be something to do with tournaments as when I was on Reshiram the lvl cap for Tournament was lv71
![image](https://user-images.githubusercontent.com/84816052/140951763-6a13fc64-396a-4da6-bc04-09f24de61192.png)

**Comment by Superfire96** [comment]
Was fixed
