### ISSUE TITLE
Pokémon stuck on level 71

### ISSUE THREAD

**Issue by rainssssss** [SmashMC-Development/Bugs-and-Issues#749]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Groudon
**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
The bug is that all my Pokémon's and others are stuck and locked on level 71 (They are not level capped).

**Comment by rainssssss** [comment]
ign: rwainbow
server: groudon

**Comment by Superfire96** [comment]
Was fixed
