### ISSUE TITLE
Warzone Glow Issue

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#75]
**Describe the Bug**
When you go to /Warp warzone , you have the glow on, but after a like a minute or two, it will disappear, making players hard to find.

**To Reproduce**
1. Go to /Warp warzone and wait for a minute or two, the glow will disappear

**Servers with the Bug**
Mew

**Expected behavior**
The glow should stay active for all the time the player is in warzone.

**Additional context**
Sometimes even in other servers the glow disappear, i've had reports from players that someone else hadn't the glow, but it's not for everyone

**Comment by CaretsPuppy** [comment]
Charizard too, seems to happen less often across other servers (all) too.

**Comment by HackuJacku** [comment]
Warzone is getting a complete re-write from the ground up. These issues should be fixed in these versions. For the moment though, I am unable to do anything in regards to fixing this due to how glows are currently handled.
