### ISSUE TITLE
Apricorns wont grow and wailmer pail not working

### ISSUE THREAD

**Issue by Snorrlax** [SmashMC-Development/Bugs-and-Issues#750]
**Describe the Bug**
I Have a small apricorn farm that I planted and about 1/3 of the apricorns wont grow. Ive sat in the chunk with them for 30+ minutes, tried using wailmer pail and that item doesnt work, and even tried replanting new ones

**To Reproduce**
1. Go to _Snorrlax_'s home on Zekrom at x:-16382, z: 11903, y:70
2. Walk to where apricons are
3. See apricorns not growing

**Servers with the Bug**
I am on Zekrom

**Expected behavior**
When planted, apricorns are supposed to grow

**Screenshots**
N/A

**Additional context**
Thanks

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
