### ISSUE TITLE
Tournament bug?

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#751]
**Describe the Bug**
When you join tourney and u get the mons the now have an OT. Bc they have an OT now they will count towards dex if you hadn't dexed them already

**To Reproduce**
do /tournament join
receive some mons
it counts towards dex

**Servers with the Bug**
Reshiram, but probably all

**Expected behavior**
shouldnt count towards dex

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/140950426-6261e929-52c5-4139-8cb7-b5b345030ca1.png)

**Additional context**
NA

**Comment by HackuJacku** [comment]
Fixed in upcoming version
