### ISSUE TITLE
Pokemone will not level past 95

### ISSUE THREAD

**Issue by tuddsfn** [SmashMC-Development/Bugs-and-Issues#752]
**Describe the Bug**
My Decidueye will not level past 95

**To Reproduce**
Tried re-logging, waiting a bit, etc.
Battles, rare candies, trading, locking and unlocking leveling, etc, does not work.

**Servers with the Bug**
Reshiram

**Expected behavior**
Battling/using rare candies expected to level to 100

**Screenshots**
N/A

**Additional context**
Been happening for the past 2ish days

**Comment by Superfire96** [comment]
Was already fixed
