### ISSUE TITLE
When ever i try to join the server automatically get kicked out it ses "connection lost" or something along the lines that. I've tried to join other servers like hypixel it perfectly works but I don't know why it does not let me in. 

### ISSUE THREAD

**Issue by Slashasdasd** [SmashMC-Development/Bugs-and-Issues#753]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
@Slashasdasd - you'll need to create a #support ticket on our Discord and provide us the logs.
