### ISSUE TITLE
Pokemon wont level up past 71

### ISSUE THREAD

**Issue by Drew5645** [SmashMC-Development/Bugs-and-Issues#754]
**Describe the Bug**
Pokemon wont level past 71... leveling is enable, rare candies do not work, and pokemon stop gaining xp. 

**To Reproduce**

**Servers with the Bug**
Reshiram

**Expected behavior**
Pokemon to level up to level 100

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
IGN is Devilrising45

**Comment by Mikirae** [comment]
This has been fixed already :)
