### ISSUE TITLE
/buymove issue

### ISSUE THREAD

**Issue by ehhhkody** [SmashMC-Development/Bugs-and-Issues#756]
**Describe the Bug**
/buymoves doesn't include some pokemons move pools.
example: Dragapult can learn flamethrower, and you can use a tr to do so but it's not listed under buy move.

Clefable has a large list of moves, one of them is flamethrower.

**To Reproduce**
/buymove
look for a move that you want and its not listed

**Servers with the Bug**
Zekrom

**Expected behavior**
Pokemons move pool should be listed, i understand egg moves remaining as egg moves.

Would also be nice to have a tm shop that sold tms, the current shop only has an npc that brings you to the /buymove menu.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Added to the master ticket.
