### ISSUE TITLE
Legend spawning mechanics in Warzone

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#757]
**Describe the Bug**
Most of the time I have been in wz, it has been extremely difficult to find legends and that is assuming that they are even in wz. I think most of the time legends are not spawning in wz. Most legends you can just despawn without anyone finding them which you can probably check in server logs. I have been to wz a lot and tons of legends have spawned while I was there...but I have only evert caught 3. And believe me I searched the enitre wz (courtesy of /fly working before). I don't think that the new mechanics of legends not spawning around player is working. Please take a look into it, as it costs a lot to go wz and players are not getting much in return.

**Which servers does this apply to?**
I play on Groudon but I think it applies for all.

**Additional context**
I think legends should spawn around players in wz for it would be easier to find them.

**Comment by ghost** [comment]
Here is a proof of the bug...2 legs spawned in wz couldn't find them....this is not isolated event.....I have tested it and spent over 250k+ on wz
https://youtu.be/9vESx1ExBc4

**Comment by ghost** [comment]
Also I have not seen shinies or shadow pokemon spawning in warzone. Don't know if it is a bug or not.

**Comment by HackuJacku** [comment]
Spent a great deal of time checking but I confirmed everything spawned within the bounds of the Warzone. Outside of the Warzone isn't classed as valid spawning which means both the Warzone spawner and Pixelmon spawner can't spawn anything.

I also spent over 3 hours with the Warzone debugger open, every Legendary and Shiny spawned within the Warzone. Shiny Pokémon are less common than prior reset, but this is intended.

**Comment by ghost** [comment]
Maybe the bounds are not properly defined because you can clearly see in the video that the legends that spawned cannot be seen in the warzone. Moreover, you can check chat logs. You will find the number of legends that are just despawning is very high. I think this needs further investigation.

**Comment by HackuJacku** [comment]
They are and I have have said, I have checked. Out of 143 Legendaries which spawned on Rayquaza over a 24 hour period, all were within the Warzone. Same with other servers. It's categorically impossible for stuff to spawn outside, this isn't the old Warzone.

**Comment by ghost** [comment]
This was before the latest changelog. Now legends seem to be spawning properly(not glitched).

**Comment by ghost** [comment]
Alright I have tested it in Groudon warzone. Legends seem to be spawning properly and near player. It is also easier to engage players in battle. Really appreciate the quick bug fixes. Keep up the good work. Thank You.
