### ISSUE TITLE
/menu text needs to be changed for gyms

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#759]
**Describe the Bug**
When you look at /menu and go to gyms and hover over them it says "PLEASE EDIT THIS LATER" so I think it wasn't edited
It also tells you to click to begin challenging but it doesnt work.
It also says that the gyms are lvl 100 but they work from level 30 to level 40 and go up in difficulty every gym (Goes up in levels of 10)

**To Reproduce**
1. Do /menu
2. Click on Gym and Elite 4
3. Hover over Gyms
4. See text
5. try clicking it
6. Nothing Happens

**Servers with the Bug**
All

**Expected behavior**
Shouldnt have those mistakes

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/141152949-954793a0-7809-4145-953f-76c2d853ce7a.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Fixed for next restart.
