### ISSUE TITLE
Auction issue

### ISSUE THREAD

**Issue by Superfire96** [SmashMC-Development/Bugs-and-Issues#76]
**Describe the Bug**
Players can start the auction on their pokemons, but other players are not able to bid, It says "you don't have permissions!"

**To Reproduce**
1. Go to the server and make someone start an auction
2. Click on the name of the pokemon to try to increase the bid

**Servers with the Bug**
Mew

**Expected behavior**
Players should be able to click on the name of the pokemon that is in auction and increase the bid by 500

**Screenshots**
![2021-05-03_18 37 58](https://user-images.githubusercontent.com/83550357/116905311-1890ec00-ac3f-11eb-8ea3-a5a9571886c1.png)

**Comment by HackuJacku** [comment]
Note for @HackuJacku: Permission issue.

**Comment by HackuJacku** [comment]
Players now have permission to bid.
