### ISSUE TITLE
/breeding

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#760]
**Describe the Bug**

The /breeding command for legend rank+ is supposed to notify you when your Pokémon have provided an egg but it doesn’t. Instead the command brings you to the /breedingwiki GUI 
**To Reproduce**
1. Do /breeding 
2. Brings you to breedingwiki GUI and has no option to notify you when your eggs are done

**Servers with the Bug**
Kyo but assuming all 

**Expected behavior**
After doing /breeding it should notify you when yours eggs are ready

**Comment by Mikirae** [comment]
My menu is breaking things I cry. I'll look into this tonight :)

**Comment by HackuJacku** [comment]
Fixed from the next reboot
