### ISSUE TITLE
Wz hole

### ISSUE THREAD

**Issue by AbleChaos** [SmashMC-Development/Bugs-and-Issues#761]
**stuck in 1x2 hole in wz**

**To Reproduce**
1. Go to 'wz'
2. go to cords -91.7000/ 66.00000/ -16.300'
3. Scroll down 
4. Fall in hole

**Servers with the Bug**
Zekrom most likely all

**Expected behavior**
dont have a hole in your map

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Archie4690** [comment]
This has been solved.
