### ISSUE TITLE
NPC letting a Quest move to step 2

### ISSUE THREAD

**Issue by something482** [SmashMC-Development/Bugs-and-Issues#762]
**Describe the Bug**
So I was able to get the dynamax quest on the Zekrom server. However, after completing step 1, including getting the prompt about the wishing piece glowing, I was not able to talk to the npc to confirm i completed step 1 and move on to the next step. This feels like a huge issue, and since ive noticed this, i have noticed that no npc will give or receive the end of a quest. This is also with the same NPC in the same village, I can confirm this because it was a NPC in a village less than 10 blocks from my home set

**To Reproduce**
1. Get a quest from an NPC
2. Finish Quest
3. Try to talk to the NPC

**Servers with the Bug**
Zekrom

**Expected behavior**
I expected the NPC to continue into the prompt to move me into phase 2 of the quest

**Screenshots**
N/A

**Additional context**
I'm losing faith in this server fast, after the numerous WZ problems, now to this, it feels like multiple things are being gatekept by bugs, WZ is again, a completely separate issue, but this might be my last straw if it is not fixed soon

**Comment by ehhhkody** [comment]
I am in the same situation on the Zekrom server. Unable to continue quest.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
