### ISSUE TITLE
Cant say Cofagrigus in chat

### ISSUE THREAD

**Issue by SasukeMK2** [SmashMC-Development/Bugs-and-Issues#763]
If you type the name Cofagrigus in chat (I needed to for a question asked by the server) you get a warning saying not to type inappropriate words in chat

I assume it is on all servers but I was on reshiram when it happened.

I think just allow players to say Cofagrigus? No one in the history of no one is going to call a person that word but disguise it as a pokemon name lmao

N/A

N/A

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
