### ISSUE TITLE
Mart and Training area glitched on Zekrom

### ISSUE THREAD

**Issue by Snorrlax** [SmashMC-Development/Bugs-and-Issues#764]
**Describe the Bug**
On Zekrom server when ever I get close to Mart or Training at spawn, or /warp there the game glitches and i get a death marker.

**To Reproduce**
1. Go to spawn and walk to mart or training areas

**Servers with the Bug**
Zekrom

**Expected behavior**
Graphics in game glitch out and I die, but dont get death message.

**Screenshots**
NA

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Does this happen to anyone else? I never have seen/heard of this issue before.

**Comment by Snorrlax** [comment]
It stop happening the next day. Not sure what happened

**Comment by HackuJacku** [comment]
Going to close as it's not occurring anymore, never heard of this happening.
