### ISSUE TITLE
Can use bot in general

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Bugs-and-Issues#765]
**Describe the Bug**
You can do - - to access the Yggdrasil bot in general on discord should only work in bot-spam

**To Reproduce**
1. Go to general 
2. type one of the commands like —8 ball

**Servers with the Bug**
General chat in discord 

**Expected behavior**
Shouldn’t be able to use bot in general

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
