### ISSUE TITLE
Survival Spawners

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#766]
**Describe the Bug**
Spawners not working

**To Reproduce**
tp to someone's base with spawners, e.g. /homes Archie4690 and look at spawners, notice how they do nothing?!?

**Servers with the Bug**
Survival B)

**Expected behavior**
Spawn sheep

**Screenshots**
![image](https://user-images.githubusercontent.com/86004012/141339929-7170e3d1-08a1-488c-b4e0-6411dd8c0d6f.png)

Piplopp also had the same issue

**Comment by jahangir6969** [comment]
spawner do work. they do not spawn in the air at the moment.

**Comment by jahangir6969** [comment]
Issue is with the spawner plugin itself. I have contact the dev about it.

**Comment by jahangir6969** [comment]
not an issue it's just how the 1.17.1 mechanics works.
