### ISSUE TITLE
Survival Votes not working.

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#767]
**Describe the Bug**
Survival vote keys are not handed out. 

**To Reproduce**
1. /vote
2. Vote
3. Try and find where you get ur key
4. 
**Servers with the Bug**
Survival

**Expected behavior**
A vote key to be placed into your inventory

**Screenshots**
N/A

**Additional context**
M1n0j also experienced this.

**Comment by jahangir6969** [comment]
Fixed.
