### ISSUE TITLE
Problem with evolving Galarian Darumaka into Galarian Darmanitan 

### ISSUE THREAD

**Issue by KUCHIHA10** [SmashMC-Development/Bugs-and-Issues#768]
**Describe the Bug**
When I evolved my Galarian Darumaka with an Ice stone it has evolved into a standard form Darmanitan 
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyurem
**Expected behavior**
I have expected to have my Galarian Darumaka evolve into a  Galarian Darmanitan 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Sadly it's a pixelmon bug and not much that we can do, if it happens you can always open a ticket and we can fix the evolution for you!
