### ISSUE TITLE
Hacko asked me to report this when an egg hatches and it has an ha

### ISSUE THREAD

**Issue by eboyJay69** [SmashMC-Development/Bugs-and-Issues#769]
**Describe the Bug**
Hacko asked me to report this when an egg hatches and it has an ha

**To Reproduce**
1. hatch an egg
2. have the hidden ability pop up in chat

**Servers with the Bug**
I think its on all servers, but it popped up on reshiram

**Expected behavior**
Hacko asked me to report it
**Screenshots**
![image](https://user-images.githubusercontent.com/84190150/141376959-3215e812-f0ba-4171-82e7-bc47c64e3aa5.png)

**Comment by HackuJacku** [comment]
Fixed
