### ISSUE TITLE
Tournament Bug

### ISSUE THREAD

**Issue by IronGolem19** [SmashMC-Development/Bugs-and-Issues#77]
**Describe the Bug**
Able To keep Tourney Pokemon

**To Reproduce**
1. Go to a pc
2. Click on your tourney pokes and drag them into your pc
3. disconnect so ur disqualified from the tournament
4. if you check your pc it will be in there

**Servers with the Bug**
so far only deoxys

**Expected behavior**
To have the pokes removed after you disqualify from the tournament

**Screenshots**
sorry dont have screen shots with proof

**Additional context**

**Comment by Sparklix** [comment]
This is possible in all servers, yet the rules clearly state you're not allowed to. Eventually they're not possible to do anything with the pokemon

**Comment by HackuJacku** [comment]
Fixed
