### ISSUE TITLE
Healer in the Ice Dungeon

### ISSUE THREAD

**Issue by FroppyBloppy** [SmashMC-Development/Bugs-and-Issues#770]
I beat the first 2 rooms of the ice dungeon, as i get to the healer, the message "I have healed all your Pokemon" appear, but it actually didn't heal anything ^^''

This bug happened to me in the Rayquaza Server

![immagine_2021-11-12_125534](https://user-images.githubusercontent.com/93840896/141463334-8dbf8f8b-06b9-4c8a-af30-5ca9f131c5de.png)

**Comment by Mikirae** [comment]
Do you know if this is a consistent issue? This is the first time I'm hearing of it and it worked fine when I did it.

**Comment by FroppyBloppy** [comment]
Yup, still happens to me everytime I try the ice dungeon, happened 4 times
^^" now I stopped trying it because I'm breeding

Il mer 17 nov 2021, 03:30 Mikirae ***@***.***> ha scritto:

**Comment by Mikirae** [comment]
Huh that's strange. I'll take another look into it. Thank you! :)

**Comment by FroppyBloppy** [comment]
Cool, thanks :) if you want, I can try another run tomorrow, to see if it
still happens ^^"

Il mer 17 nov 2021, 03:34 Mikirae ***@***.***> ha scritto:

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
