### ISSUE TITLE
gyms broken

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#771]
**Describe the Bug**
You can use legends in gyms. there is a max of 2 but they can be any legendary. I know of a player (K33my) who used a zacian in the gyms. As far as i know its just the zacian bc it wouldn accept my reshiram. but didnt have time to further test bc i had work. secondly there is no level cap on any of the mons (u can use all normal pokemon in the first gym for example (its supposed to have a lvl 30 cap)). This bug is for all gyms on all servers

**To Reproduce**
go to rayquaza
type in /gyms
choose any gym
choose ur team
include a zacian (or any mon that negates the level cap)

**Servers with the Bug**
all servers all gyms (quickly tested this but had to go bc of work)

**Expected behavior**
Zacian to be banned and a level cap applicable to the gyms.

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/141492503-f688e747-cd43-46cb-9fa8-8fdec66a2f0b.png)

**Additional context**
NA

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
