### ISSUE TITLE
Discord reactions

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#772]
**Describe the Bug**
you can react with different emojis on the auto roles channel than the ones that give you a role

**To Reproduce**
1. Go to discord auto roles channel
2.  see the reactions

**Servers with the Bug**
Discord

**Expected behavior**
shouldnt be able to react with the emojis

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/141518941-50858786-02c1-48fb-accd-10d21f2fe470.png)
![image](https://user-images.githubusercontent.com/89798207/141518986-b66dc860-e4e5-4888-a33d-0d81f3a6a0e6.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
