### ISSUE TITLE
Wz Bugging out

### ISSUE THREAD

**Issue by Massivelist5419** [SmashMC-Development/Bugs-and-Issues#774]
So Bassicly whenever i go into wz i try to cach pokemon. But when i enter and try to chach a pokemon it doesnt work, for instance i tried to cach a charzard on 12% hp. I used 32 ultra balls (give or take) and even 1 master ball but i wasnt able to cach it and ive busted 50k to go to the warzone. I bassickly lost 50k because i cant cach pokemon. Even when it does work wich is only with park balls it doesnt go into my pc!!!!

**Comment by HackuJacku** [comment]
Believe this is fixed. If not, create a new issue which uses the format - I need to reproduce the issue to fix it.
