### ISSUE TITLE
Ultra beast spawn rates either too high or people are finding ways to force spawn them

### ISSUE THREAD

**Issue by Chungers01** [SmashMC-Development/Bugs-and-Issues#775]
There this random group of people who suddenly got on and wayyyy too many ultra beasts spawned in very short period of time.  At least like 20 kartanas spawned on them in less than 2 hours.  Staff might want to check if there's a way to force spawn ultra beasts more.

[](url[2021-11-11-3.log.gz](https://github.com/SmashMC-Development/Bugs-and-Issues/files/7530615/2021-11-11-3.log.gz))

**Comment by Superfire96** [comment]
Was fixed, the spawn rates were too high
