### ISSUE TITLE
Ultra Best Spawn Rates are too High

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#776]
**Describe the Bug**
Ultra Best Spawn Rates are too High

**To Reproduce**
1. Go to Ultra Space
2. Be in a biome where they can spawn
3. They spawn WAY too often

**Servers with the Bug**
Mainly seen on Rayquaza but probably all

**Expected behavior**
SHouldnt spawn as often

**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by M1n0j** [comment]
![image](https://user-images.githubusercontent.com/84816052/141600476-ec3a0cf4-a9a3-4e43-b548-e57220dbdabf.png)
![image](https://user-images.githubusercontent.com/84816052/141600483-b52e4872-b2b7-4130-a29a-cc3a0458b251.png)
![image](https://user-images.githubusercontent.com/84816052/141600512-0077e10c-a947-40d2-b7c5-64c101274a5c.png)

**Comment by Superfire96** [comment]
Was fixed
