### ISSUE TITLE
Egg group bug

### ISSUE THREAD

**Issue by ehhhkody** [SmashMC-Development/Bugs-and-Issues#778]
**Describe the Bug**
Some pokemon that share egg groups can't breed.

**To Reproduce**
Tried to breed Greninja with Golduck both sharing Water 1 egg group, they cannot breed.

**Servers with the Bug**
Zekrom

**Expected behavior**
They share an egg group and should be able to breed.

**Additional context**
Haven't checked any other yet, but I'm sure if there is one there are going to be multiple.

**Comment by Superfire96** [comment]
The issue is fixed, i've just tested it and it is working correctly
