### ISSUE TITLE
Baltop not updating + more!

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#779]
**Describe the Bug**
Baltop is not updating. But this causes other problems. I had 500k but baltop was showing the I had 300k. So, when the server got restarted, I lost 200k and was back to 300k. I made a ticket about this too.

**Servers with the Bug**
Groudon.

**Comment by ghost** [comment]
![Screenshot (535)](https://user-images.githubusercontent.com/25759066/141649022-ef0698b9-13cd-4e50-a361-b6cb8de2dc10.png)
you can clearly see my bal and baltop difference

**Comment by ghost** [comment]
I think if the server restarts without it updating the baltop, you lose money.

**Comment by HackuJacku** [comment]
@arjungangwar0 - I believe this is now fixed but would need confirmation please.

**Comment by ghost** [comment]
Yes my balance was fixed. But, I made this report because I thought it was a general problem happening to everyone.

**Comment by HackuJacku** [comment]
Great to hear! Will close this now, sorry for any issues experienced... :/
