### ISSUE TITLE
Mega Slowbro

### ISSUE THREAD

**Issue by Blxgdenn** [SmashMC-Development/Bugs-and-Issues#78]
**Mega Slowbro Glitch**
https://user-images.githubusercontent.com/83072886/117001437-437c4e00-acda-11eb-862a-cf722d12342d.mov
When Slowbro Mega evolves, it keeps its regenerator ability as well. This glitch Doesnt give mega slowbro the right ability after mega evolving

**To Reproduce**
All you need to do is mega evolve the slowbro and it keeps whatever ability it had before mega evolving and isnt given the right ability
**Servers with the Bug**
Only been tested on Dialga

**Expected behavior**
Mega Slowbro should have the weak amour ability but keeps its orignal ability pre mega

**Screenshots**
![image](https://user-images.githubusercontent.com/83072886/117001406-38292280-acda-11eb-8c95-7e6dca3ef2eb.png)

**Additional context**

https://user-images.githubusercontent.com/83072886/117002422-72df8a80-acdb-11eb-9cee-1afa67522557.mov

**Comment by Blxgdenn** [comment]
Appologies for some reason it sent the wrong screenshot

**Comment by HackuJacku** [comment]
@Rasgnarok - are you able to confirm that this is fixed in 8.2 please? I remember hearing that it was but the changelog I have does not mention it :/

**Comment by HackuJacku** [comment]
Fixed in 8.2 - confirmed with Waterdude.
