### ISSUE TITLE
people are able to attack players while safeplacing therefor preventing them from doing a safeplace teleport.

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#780]
**Describe the Bug**
People able to attack you while safeplacing in warzone.

**To Reproduce**
1. Go to warzone
2. start safeplacing
3. get attacked
4. suffer a loss due to not being able to safeplace

**Servers with the Bug**
RAyquaza ( maybe all)

**Expected behavior**
safeplace-ing shouldnt be cancelable in any form if its to be adherent to the current rules of warzone. as it makes the person who is being forced to leave the warzone to be more vulnerable due to not being able to move to dodge a ball.

**Screenshots**
n/a

**Additional context**
revise the rules if this is in error.

**Comment by ghost** [comment]
it is suppose to happen pretty sure...otherwise ppl will just come wz with throws, catch legs and safeplace.

**Comment by ajdawg48** [comment]
yea don’t think this is a bug that’s just how warzone works. Worked like this also before reset back when the old warzone wasn’t completely filled with bugs

**Comment by HackuJacku** [comment]
Not a bug, this is an intended mechanic.
