### ISSUE TITLE
Can't sell balm mushroom

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#781]
**Describe the Bug**
The balm mushroom cannot be sold to shopkeepers, even though its description says that this is it's whole purpose.

**To Reproduce**
1 go to mart
2. try to sell it
3. doesn't come up with the option to sell it

**Servers with the Bug**
All, but only tested on reshiram

**Expected behavior**
should be able to sell it

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/141648742-4ca2f062-135e-4190-82a7-18365996971a.png)
![image](https://user-images.githubusercontent.com/89798207/141648753-57147d10-b780-4fd2-b757-fa217da5de29.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
I fixed this one in a new ticket 🐸
