### ISSUE TITLE
Galarian Darmanitan has incorrect moves on buymoves

### ISSUE THREAD

**Issue by KUCHIHA10** [SmashMC-Development/Bugs-and-Issues#782]
When I done /buymoves for my Galarian Darmanitan it did not consist of ice type moves it should be able to learn and other moves like Iron Head.

1. Go to 'warp mart and buymove NPC or /buymoves and chose Galarian Darmanitan Then u will see that he is missing those moves'

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyurem

I expected to be able to buy Iron head but there was missing moves.
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
Added to the master ticket.
