### ISSUE TITLE
Rotom's Moves

### ISSUE THREAD

**Issue by HmmWho** [SmashMC-Development/Bugs-and-Issues#783]
Describe the Bug
I have tried learning the move "Defog" on rotom, I have tried imprinting the move and it hasn't worked. I also try ./BM Defog also doesnt work.

To Reproduce

Servers with the Bug
I was on Rayquaza at the time, but it is probably across all servers.

Expected behavior
You could just BM the move or imprint it by a blank TR

Screenshots
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
Additional context
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
Added to the master ticket.
