### ISSUE TITLE
Server shutdown rerolls balance 

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Bugs-and-Issues#784]
**Describe the Bug**
This bug started around nov 9th-10th shortly after the error of peoples balances being reset to 0 was fixed.

I paid a my friend money for a pokemon. Server went down a bit after that. Logged back on, and I got all the money I paid him back and he lost the money I had paid him. I still had the pokemon we traded however so ONLY the balance is being rerolled.

Today I experienced losing the money myself. I was paid 30k 6 minutes before the server randomly closed. After logging back in my balanced dropped from 97k back to 67k like I was never paid.

**To Reproduce**
1. Pay someone any amount of money like say 5k.
2. Person confirms they received the 5k and their balance went up.
3. Close/Restart the server.
4. Server goes back online and both players log back on.
5. Player that paid 5k checks balance and has the paid 5k back.
6. Player that received 5k checks balance and now is missing the paid 5k.

**Servers with the Bug**
I only play on groudon so this could be every server or only groudon. 

**Expected behavior**
Anytime the server has to reroll for being closed/restarted any transactions made with coins will be reverted back to **ATLEAST** (cannot confirm exact time but can confirm I lost money from 6min before the server closed) 5-10 minutes before the transaction was made

**Screenshots**
![Screenshot 2021-11-13 140341](https://user-images.githubusercontent.com/93420175/141659021-bd6b8739-1090-4f9c-b66a-5b13739bcf92.png)
![Screenshot 2021-11-13 153628](https://user-images.githubusercontent.com/93420175/141659024-7df3612e-098d-4fc0-8d82-89c1959daa4e.png)

**Additional context**
Screenshot one is when I was paid. 
Screenshot two is the server being closed. 
I do not have a screenshot of my balance before server was closed so I cannot 100% prove I lost 30k but here is my full log from that day. Important info starts at 13:09

[techniclauncher_2021-11-13.log](https://github.com/SmashMC-Development/Bugs-and-Issues/files/7532749/techniclauncher_2021-11-13.log)

**Comment by HackuJacku** [comment]
Fixed - please create a ticket if you are missing money.
