### ISSUE TITLE
Level 40-60 training area spawn underleved pokemon.

### ISSUE THREAD

**Issue by Moosemilk0704** [SmashMC-Development/Bugs-and-Issues#785]
The level 40-60 training area is spawning pokemon from the level 20-40 training area.

**Comment by HackuJacku** [comment]
Which server is this, @Moosemilk0704? Follow the format provided in the future because it includes everything we require to fix bugs, such as the server.

**Comment by Moosemilk0704** [comment]
Well I have only played on Kyogre and Groudon, and they both had the issue.
So I think it's on all servers.

**Comment by HackuJacku** [comment]
@Moosemilk0704 - I only found that Groudon had this issue, I've fixed this though. Kyogre was fine.

**Comment by Moosemilk0704** [comment]
Cool, thanks!
