### ISSUE TITLE
Aura crate bug

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#786]
**Describe the Bug**
Got a random leg paper and a random aura leg paper when it said I got a
![2021-11-14_12 19 17](https://user-images.githubusercontent.com/83971987/141681167-4fb0f156-5f35-479f-bcbc-4fc6b5dd2e56.png)

**Servers with the Bug**
Kyurem

**Expected behavior**
spec mon with aura

**Additional context**
I'll still keep these papers, just saying there is a bug

**Comment by HackuJacku** [comment]
Fixed
