### ISSUE TITLE
Trivia

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#787]
**Describe the Bug**
When answering trivia, certain pokemon have words in them that can be seen as 'not allowed', and so you can answer them. pokemon such as sharpedo, and cofagrigus.

**To Reproduce**
1. Attempt to answer trivia
2. get censored

**Servers with the Bug**
all pixelmon servers

**Expected behavior**
maybe another way around it?

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/141689902-1c221bb3-6821-40ff-a6db-72e10f150a46.png)

**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
