### ISSUE TITLE
e4 teams issue

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#788]
Just checked e4 teams on kyurem but can't edit teams, says it is locked by admin.

**Comment by Dwag0n** [comment]
checked zekrom and says same thing 

![2021-11-14_10 07 04](https://user-images.githubusercontent.com/83245837/141690844-607c92d1-b445-4f6c-b945-256f21c0746c.png)

**Comment by HackuJacku** [comment]
Fixed
