### ISSUE TITLE
Increase the time you get when you select your team in wz 

### ISSUE THREAD

**Issue by GETREK1** [SmashMC-Development/Bugs-and-Issues#789]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by GETREK1** [comment]
A lot of ppl have been losing their Pokémon  in wz (including me) because they don’t get enough time to select their team which leads to them not being able to have a proper battle

**Comment by HackuJacku** [comment]
This is a suggestion, not a bug. Next time please create it under the correct repository and edit the format.

However, I've increase the selection time to 20 seconds from the next reboot - an additional 5 seconds.
