### ISSUE TITLE
players dont have access to /aura remove slot

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#79]
**Describe the Bug**
players do not have access to _/aura remove slot_ to remove an aura from a poke, even tho the paper says they can use that command

**To Reproduce**
put an aura on a poke and try to remove it as a normal player

**Servers with the Bug**
all

**Expected behavior**
players should have access to it

![image](https://user-images.githubusercontent.com/82659374/117053493-52362580-ad19-11eb-8baa-cb044b6beea1.png)

**Comment by HackuJacku** [comment]
Note for @HackuJacku: Permission issue.

**Comment by HackuJacku** [comment]
Players now have permission to use this.
