### ISSUE TITLE
meltan bug

### ISSUE THREAD

**Issue by TommyTaco29** [SmashMC-Development/Bugs-and-Issues#790]
so my meltan was defently spawning as we could hear it and i smelted like 80 stacks of ores but it wasnt see able but i could here it

**To Reproduce**

**Servers with the Bug** Groundon
Please provide a list of which servers have this bug.

**Expected behavior**
to spawn a meltan and let me try catch it
**Screenshots**
![image](https://user-images.githubusercontent.com/94329419/141705746-6bea6f87-dfec-4007-bfbc-70fd0c8de5a3.png)

If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'. its just bugged please help

**Comment by Superfire96** [comment]
I believe the issue is fixed, i've seen people catching meltans
