### ISSUE TITLE
CAn see peoples achievements in chat while in drowned dimension.

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#791]
**Describe the Bug**
get an achievement in drowned dimension and let everyone see it
**To Reproduce**
1. Go to drowned dimension
2. get achievement
3. have others see it in chat

**Servers with the Bug**
Rayquaza (all)

**Expected behavior**
not seeing achievements would be nice

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/141741133-7843827c-8ece-4e90-9bf9-95f2d97d0bd9.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Shoji007** [comment]
![image](https://user-images.githubusercontent.com/82549364/141754785-45a830c3-a27a-4383-87a2-3ccdad34c075.png)
****

**Comment by HackuJacku** [comment]
Fixed
