### ISSUE TITLE
RTP not working, survival

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#792]
**Describe the Bug**
Command RTP is not working.

**To Reproduce**
Go to the server, try and run the command /rtp notice how it does not work, or does not appear

**Servers with the Bug**
survival

**Expected behavior**
Teleport you to a random location.

**Screenshots**
N/A

**Additional context**
Can run the command /randomtp:rtp but makes you pay and does not work 100% of the time.

**Comment by jahangir6969** [comment]
Fixed. Has an 4hour cooldown time
