### ISSUE TITLE
GUI survival

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#793]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Archie4690** [comment]
Forgot to edit it, Steps to reproduce swear i did write all of the stuff. To reproduce:
1. Go on survival 2. open your inventory 3. try and open the quick craft menu, the book to the right of your armour slots. 4. Try and click on that to craft someone and see how it is unsuccessful.
![image](https://user-images.githubusercontent.com/86004012/141811646-05f64c5f-850f-4002-ae85-3a87b61edf57.png)

**Comment by jahangir6969** [comment]
@Archie4690 Able to test this one again please?

**Comment by Archie4690** [comment]
Does not work still. The same issue remains.

**Comment by Archie4690** [comment]
idk man
