### ISSUE TITLE
Pokemon caught and wasnt in the pc in groudon

### ISSUE THREAD

**Issue by Daredevil2001393** [SmashMC-Development/Bugs-and-Issues#795]
in groudon i caught a mon and it didnt give it to me out of the warzone i just want it refunded.
IGN: Daredevil2001
Server: Groudon
![image](https://user-images.githubusercontent.com/94395951/141834409-54916d79-ea59-409e-a874-594106a98e34.png)

**Comment by Dxhcky** [comment]
Is it in your warzone bank

**Comment by Superfire96** [comment]
It's an issue with the StatsCatcher plugin, in order to receive the pokemon you would have to catch it before your timer runs out, now due to us having the statsCatcher, it will show you the stats even tho you didn't actually catch the pokemon
