### ISSUE TITLE
Warzone timer and Pokemon catching

### ISSUE THREAD

**Issue by Sensouu** [SmashMC-Development/Bugs-and-Issues#796]
**Describe the Bug**

This bug occurs when your timer is almost out in the Warzone area, if you encounter a Pokemon, and capture it around the 1 second mark before you teleport, it will display you captured it, but it won't be in your Warzone box or add time, since it happened "outside" of Warzone, despite encountering it and throwing a Pokeball before time ran out. 
When this bug occurs you'll be stuck in a battle against and uncatchable Pokemon, and the Pokemon you "caught" no longer exists.  

**To Reproduce**
1. Go to Warzone
2. Encounter a Pokemon 
3. Throw a Pokeball while timer is at 1~3 seconds

**Servers with the Bug**
This bug took place on Reshiram, as I don't play on the other servers I'm not sure if this bug exists on them

**Expected behavior**
Since I clicked my original Warzone masterball before the time ran out, I figured it should have gone into the Warzone box, if it wasn't for the ball's shaking animation I would have been alright, I think

**Screenshots**
https://cdn.discordapp.com/attachments/798728264276901919/909890593843453952/IMG_8897.jpg  Image displays a battle continuing with a Stoutland, side bar says I've already captured it.
https://media.discordapp.net/attachments/798728264276901919/909883133736943697/IMG_8898.jpg?width=1270&height=953 Image shows Stoutland breaking out of a Masterball.

**Additional context**
Seems like it's an present issue with other servers too, seen by this user in Groudon with a Melmetal. https://github.com/SmashMC-Development/Bugs-and-Issues/issues/795

**Comment by HackuJacku** [comment]
@Sensouu when you say "the display", you're talking about the message from StatsCatcher?
