### ISSUE TITLE
Warzone capture stuck battling after captured

### ISSUE THREAD

**Issue by Daredevil2001393** [SmashMC-Development/Bugs-and-Issues#797]
**I was in warzone and captured a mon and it was near the end of my time in the warzone and i captured it whilst leaving and it said i captured but when i left the warzone i was stuck in a battle with it and i thought i didnt capture it so i threw master balls at it and none of them would capture it.**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**I just thought it would go into my warzone loot but it wasnt there.**

**
![image](https://user-images.githubusercontent.com/94395951/141851539-f634e9c2-1f39-4515-bfcd-f9570c50d36f.png)
**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**yeah i just want my mon idk if you can spawn one on me with random ivs because im unsure if they were any good.**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
