### ISSUE TITLE
Smash legend access to Ace kit

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#798]
**Describe the Bug**
Seems I as a smash rank player have access to ace kit

**To Reproduce**
1. Buy smash
2. type /kit ace
3. See the kit added to your inv

**Servers with the Bug**
Rayquaza

**Expected behavior**
I assume only kits of ranks you paid for should be accessible to you.

**Screenshots**
N/A.

**Additional context**
N/A.

**Comment by Superfire96** [comment]
Fixed
