### ISSUE TITLE
players are unable to claim alolan/galarian pokes from specific pokemon papers

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#80]
**Describe the Bug**
when u have a paper for a specific (or even random) pokemon, u are unable to get alolan or galarian forms from it. only way to do it is to make a ticket and ask an admin (like no joke, half the admin tickets are about this)

**To Reproduce**
get a specific paper and try to claim an alolan/galarian poke from it

**Servers with the Bug**
all

**Expected behavior**
players should be able to get alolan/galarian pokemon from such papers themselves, without having to rely on admins

**Comment by HackuJacku** [comment]
Forwarded to @Mikirae due to knowing the developer. I believe this is added in the 8.2 version though.

**Comment by HackuJacku** [comment]
Confirmed with Miki that both are added in the next build for 8.2. If it is not added, please reopen the issue.
