### ISSUE TITLE
E4 Team Selection

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#801]
**Describe the Bug**
The Pokemon for E4 on Reshiram are missing

**To Reproduce**
1. Go to Reshiram
2. Open ag manager
3. Try select team
4. No Pokemon

**Servers with the Bug**
Reshiram

**Expected behavior**
Should have Pokemon

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/142061973-3696b4d9-f712-4cee-8871-421b2d0691b9.png)
![image](https://user-images.githubusercontent.com/84816052/142061994-6e442e9c-c29b-45eb-8a62-02219dbd2658.png)
![image](https://user-images.githubusercontent.com/84816052/142062003-353de5c5-b02e-4a25-8ac2-863403c8430d.png)
![image](https://user-images.githubusercontent.com/84816052/142062017-3ce60b9b-7ea3-486d-a1b7-ad1d08d2ab49.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Was fixed, same as the other tracker
