### ISSUE TITLE
Legend Rank Doesn't Have Scarfs

### ISSUE THREAD

**Issue by Keone0** [SmashMC-Development/Bugs-and-Issues#802]
**Describe the Bug**
Legend rank does not have permission to equip any of the scarfs in /scarf.

**To Reproduce**
1. Have legend rank
2. Type /scarf in chat
3. See you do not have access

**Servers with the Bug**
Only know of it on Ray, might be others

**Expected behavior**
Have access to the scarfs listed on server website

**Screenshots**
NA

**Additional context**
NA

**Comment by Mikirae** [comment]
Unfortunately scarves are a one-time item that are given with the purchase of legend rank, not a perk.

**Comment by HackuJacku** [comment]
As Miki said, this is not a bug. They're one-time items. If you should have them but do not, create a ticket please.
