### ISSUE TITLE
Breeding alolan

### ISSUE THREAD

**Issue by Reblieble** [SmashMC-Development/Bugs-and-Issues#804]
**Describe the Bug**
Breeding alolan Gravelers, from the eggs i get normal Geodudes.

**To Reproduce**

**Servers with the Bug**
I am playing on Zekrom

**Expected behavior**
That this bug get solved so i can get alolen BP Geodudes

**Screenshots**
N/A

**Additional context**
Ask it to the discord from the server and saying to make an github about it because its an bug atm.

**Comment by Mikirae** [comment]
So this is currently a Pixelmon bug and we can't do anything about it unfortunately. I was informed that the way to fix this is to give your Pokemon an Ever Stone, I believe. Let me know if that works please :)

**Comment by Superfire96** [comment]
The way to fix it it's giving them an everstone, if it doesn't work, breeding them in the ultraspace should fix the issue
