### ISSUE TITLE
Skills not working!

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#805]
**Describe the Bug**
I have noticed that 2 skills are not working properly :-
1. **Double Yolk of Breeding Skill** : The extra egg you get from double yolk does not take into account the items parents are holding like destiny knots and everstone. Moreover, pretty sure HA is not passed in double yolk egg. So, the additional egg you get is always useless. 
2. **Miners Madness of Mining Skill** : Right clicking with your pickaxe has no effect.

**Comment by Mikirae** [comment]
Will report both of these not working. Thank you!

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
