### ISSUE TITLE
Armors in Warzone

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#806]
**Describe the Bug**
Armors are giving effects in warzone.

**Servers with the Bug**
Groudon.

**Expected behavior**
Armor should not have any effect in warzone.

**Screenshots**
https://youtu.be/AfIM6dQ8TmE

**Comment by HackuJacku** [comment]
@arjungangwar0 - please provide a specific list of which ones are

**Comment by ghost** [comment]
I can confirm thunder stone armor and dawn stone armor gives effect in wz.

**Comment by HackuJacku** [comment]
Fixed in next Warzone version.
