### ISSUE TITLE
Sts

### ISSUE THREAD

**Issue by AnticIsALPHA** [SmashMC-Development/Bugs-and-Issues#807]
Please add sts back as it was a way to get rid of dex pokemon breeding pokemon and legends for some ingame money

**Comment by RatedPG21** [comment]
Sts isn’t in our staff team power to add back, it is a seperate plugin that needs to be updated by its owner to this version of pixelmon, also I hear they are added a new form of gts where you can sell your Pokémon and items to the server, so kinda like sts, we just gotta be patient :)

**Comment by HackuJacku** [comment]
We're not adding the old STS plugin back due to duplication issues. We'll be beta testing a new GTS, Auction House and STS plugin on Zekrom over the weekend, then putting it on the rest of the servers.
