### ISSUE TITLE
Cannot Steal when someone leaves

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#808]
**Describe the Bug**
When someone leaves or disconnects in warzone you cannot steal from them

**To Reproduce**
1. Go to any server
2. fight in warzone
3. have the other person leave
4. Cannot steal

**Servers with the Bug**
All

**Expected behavior**
Should be able steal as them leaving can be seen as them forfeiting 

**Screenshots**
https://youtu.be/aDuKxSzTxzs

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
