### ISSUE TITLE
Reshiram Gyms

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#809]
**Describe the Bug**
There is 2 Water type gym rooms on Reshiram, 1 should be Grass
There is also no NPCs in any room

**To Reproduce**
1. Go to Reshiram
2. do /warp gyms
3. See Issues

**Servers with the Bug**
Reshiram

**Expected behavior**
Should be correct rooms and NPCs in each

**Screenshots**
https://youtu.be/6lRWfdXUH_E

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
