### ISSUE TITLE
Groudon Gyms

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#810]
**Describe the Bug**
There is 2 level 50 Gyms one should be level 80 and the level 80 should be level 90.

**To Reproduce**
1. Go to Groudon
2. Do /warp Gyms
3. See issues

**Servers with the Bug**
Groudon

**Expected behavior**
Should be correct levels

**Screenshots**
https://www.youtube.com/watch?v=DpbJdA5rxNk

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
