### ISSUE TITLE
Zekrom Gyms

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#811]
**Describe the Bug**
There is 2 level 50 Gyms one should be level 80 and the level 80 should be level 90.

**To Reproduce**
1. Go to Zekrom
2. Do /warp Gyms
3. See issues

**Servers with the Bug**
Zekrom

**Expected behavior**
Should be correct levels

**Screenshots**
https://youtu.be/6BB_npjQb7s

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
