### ISSUE TITLE
Kyurem Gyms

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#812]
**Describe the Bug**
There is 2 level 80 Gyms one should be level 90

**To Reproduce**
1. Go to Kyurem
2. Do /warp gyms
3. See issues

**Servers with the Bug**
Kyurem

**Expected behavior**
Should be correct levels

**Screenshots**
https://youtu.be/4IJwf33AJbM

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
