### ISSUE TITLE
Warzone spawns and Despawns

### ISSUE THREAD

**Issue by TheCatalyst525** [SmashMC-Development/Bugs-and-Issues#813]
Whenever in the WZ a legendary will spawn. They Either visible or not. Next thing they spawn for 20-30 seconds and that is pathetic compared to the previous warzone. Also where is the spawns for shinny or shadow pokemon in warzone. It is sad that a beautiful place is so bleh. Please help fix this. It really feels sad in there. I love this server. Everyone has worked so hard to make it amazing.

**Comment by HackuJacku** [comment]
Change the spawning position from the next restart. However, the previous system spawned Pokémon around the player whereas the new one spawns it around the full area - this is intended for distribution and is important. This custom system is more aggressive compared to the old Warzone. The changes made significantly improve the distribution however. 

In the future, follow the format provided. It's provided by default for a reason.
