### ISSUE TITLE
Crate keys after tourneys

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#815]
**Describe the Bug**
keys not being given after winner of tourney

**To Reproduce**
Get good and win a tourney, get sad and not get a key. Key isn't automatically given

**Servers with the Bug**
Primarily Rayquaza and Groudon, possibly other servers but 

**Expected behavior**
Give key automatically

**Screenshots**
No real point lmao

**Additional context**
Unsure if occurs on other servers, 100% on ray and groudon

**Comment by PeachGamer1463** [comment]
When i join a tournament, it was two people in the tournament but when it started, i immediately won and did not even entered the battle

**Comment by HackuJacku** [comment]
Fixed
