### ISSUE TITLE
E4 Bug

### ISSUE THREAD

**Issue by Monkeybanditt** [SmashMC-Development/Bugs-and-Issues#817]
**Describe the Bug**
The Bug/fighting E4 on ray only has 11 mons: it is missing a mega lopunny.
**To Reproduce**
1. Go to Rayquaza server
2. /ag manage
3. Find and click on the bug/fighting gym
4. See it only has 11 mons, the missing mon being a mega lopunny. Compare to the bug/fighting E4 pokepaste located within the Rayquaza E4 discord channel.

**Servers with the Bug**
Only Rayquaza

**Expected behavior**
The bug/fighting E4 on Ray should have Mega lopunny among its selection of 12 mons.

**Additional context**
To solve the issue, take the mega lopunny set from the paste located within the Rayquaza E4 discord channel and import it into the server.

**Comment by Superfire96** [comment]
Fixed
