### ISSUE TITLE
Dailies not working

### ISSUE THREAD

**Issue by Pajamapants1200** [SmashMC-Development/Bugs-and-Issues#818]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
@Pajamapants1200 - you need to provide more information than you currently have - fill in the format.

**Comment by Pajamapants1200** [comment]
I play on rayquaza. Yesterday I did a daily, but it didn’t work I ignored it. I thought it’s probably a one time glitch. Today though the same thing happened to me. I do the quest but gain no reward. The quest today was called creating brown houses. You had to smelt 1 brown terracotta, I did it and expected to get my reward  but never received it. You can see in the photo that I have everything from the quest in my inventory. 
![DB8E3A11-5AED-4F98-97B3-575EB391A3D2](https://user-images.githubusercontent.com/94767543/142744392-30b89aec-4357-491e-b9db-002984670c9f.jpeg)

**Comment by Pajamapants1200** [comment]
I don’t know if the new ones that just changed will work but I’ll try them.

**Comment by Superfire96** [comment]
Fixed
