### ISSUE TITLE
Vein miner does not work

### ISSUE THREAD

**Issue by Sugpussz** [SmashMC-Development/Bugs-and-Issues#820]
**Describe the Bug**
When you hit level 50 in miner skill you get the ability to use vein miner where you crouch and get the whole vein in one mine. It simply does not work

**To Reproduce**

1. Go to Skills
2. Click on Level 50 ability
You will see with it activated it does not work 

**Servers with the Bug**
Kyogre 

**Expected behavior**
You should crouch and mine the whole vein.
**Screenshots**
na

**Additional context**
na

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
