### ISSUE TITLE
Hole in Ray Warzone

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#821]
**Describe the Bug**
a hole you can get stuck in inside the rayquaza warzone

**To Reproduce**
1. Go to warzone and to these coords given below
2. be stuck and lose your time in warzone cause of it.

**Servers with the Bug**
rayquaza ( possibly all )(not going to check cause i dont have warzone teams on all servers yet)

**Expected behavior**
no holes to get stuck in pls

**Screenshots**
![image](https://user-images.githubusercontent.com/82549364/142754642-b58002fa-e184-4d1d-a453-e467bcf938f3.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Superfire96** [comment]
Solved
