### ISSUE TITLE
Kyurem e4 issue

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#822]
**Describe the Bug**
Wrong hidden power ivs for manectric in bug/electric elite team.

**To Reproduce**
1. /ag manage
2. check bug/electric mons
3. manectric ivs are for dragon type hidden power

**Servers with the Bug**
kyurem

**Expected behavior**
ivs should be for ice type hidden power

**Comment by HackuJacku** [comment]
Fixed
