### ISSUE TITLE
Genderless pokemon with genders in pokehunt

### ISSUE THREAD

**Issue by Leamyyy** [SmashMC-Development/Bugs-and-Issues#823]
**Describe the Bug**

Genderless pokemon can appear in the gender tab on PokeHunt.

**To Reproduce**

Ehh, type /hunt and see the female bronzor being required.

**Servers with the Bug**

All servers

**Expected behavior**

Remove genderless pokemon from the hunts that require a gender

**Screenshots**
![2021-11-22_00 01 41](https://user-images.githubusercontent.com/93057830/142782484-81769464-d612-47a9-8236-3d4e4c0e3c78.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Forwarded to the developer - will close so please keep an eye on #changelogs in Discord.

**Comment by HackuJacku** [comment]
Forwarded to the developer
