### ISSUE TITLE
V8 Texture Pack broken for Shadow Pokemon

### ISSUE THREAD

**Issue by AlreadyaNoobz** [SmashMC-Development/Bugs-and-Issues#824]
**Describe the Bug**
Bought a random Shadow Legendary got mew however it had no texture change to it.

**To Reproduce**
have a shadow pokemon with V8 of the texture pack and check if it works.

**Servers with the Bug**
Im on Rayquaza

**Expected behavior**
go through all pokemon that have texture changes just to make sure they work.

**Screenshots**
![image](https://user-images.githubusercontent.com/94809890/142783759-82aaa01a-898e-45e0-9011-2a2dfc30da03.png)
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Added a converter to replace all old-shadow ID Pokémon with new ID ones. This is now fixed.
