### ISSUE TITLE
Reshiram gyms only have one leader

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#826]
**Describe the Bug**
reshiram only has one gym in warp gyms

**To Reproduce**
1. Go to warp gyms 
See that there is only 1 gym leader 

**Servers with the Bug**
Reshiram

**Expected behavior**
all the gyms to be there 

**Screenshots**
n/a

**Additional context**
n/a

**Comment by HackuJacku** [comment]
Fixed
