### ISSUE TITLE
I got a item that dosent make sense

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#827]
**Describe the Bug**
I got a badge from ultra space loot and ngl that doesn't make sense and why would we need that.

**To Reproduce**
I cant describe how to reproduce
**Servers with the Bug**
Each server
**Expected behavior**
Not get a badge from loot and only from gyms

**Screenshots**
![image](https://user-images.githubusercontent.com/84050975/142807485-afc69311-179a-45a8-924f-e2458cb9a477.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
This is now fixed and I don't know why it was in there either lol
