### ISSUE TITLE
Eggs on GTS

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#829]
**Describe the Bug**
I don't if it is a bug or not but people are able to put eggs on GTS and GTS gives you no information about them.

**Servers with the Bug**
Groudon.

**Expected behavior**
Either eggs should not be allowed or GTS should give information about it.

**Screenshots*
![Screenshot (622)](https://user-images.githubusercontent.com/25759066/142828538-ddf4ae37-591b-4da1-8c3a-9546c7d76eba.png)
*

**Comment by Rasgnarok** [comment]
This is how it should work, you can sell eggs, but you cannot tell what they are either. Eggs themselves aren't a problem as a sale, but using GTS to know what the egg is isn't okay either.

**Comment by ghost** [comment]
Agreed but you can't really monitor if someone is selling breedable BP or BP HA eggs for cheap. So, maybe just remove eggs from GTS.
