### ISSUE TITLE
lvl190 catcher gives wrong reward

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#83]
**Describe the Bug**
when u reach lvl190 in the catcher skill, u should get 3x specific pokemon papers, but u only get 1.

**To Reproduce**
get to lvl190 catcher, receive the (wrong) rewards

**Servers with the Bug**
all

**Expected behavior**
u should get 3 papers, not 1

**Comment by HackuJacku** [comment]
Fixed from the next reboot - I tested it on Rayquaza and works fine now.
