### ISSUE TITLE
Pixelhunt giving all plates

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#830]
**Describe the Bug**
When doing the pixelhunt (hard difficulty), you get one of ALL the arceus plates. I believe this should have been less.

**To Reproduce**
1. Complete the 'hard difficulty' pixelhunt
2. get rewarded with ALL of the arceus plates
3. 
**Servers with the Bug**
All pixelmon servers, i believe.

**Expected behavior**
should be way less.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
