### ISSUE TITLE
Floating Hunt Particles 

### ISSUE THREAD

**Issue by Sensouu** [SmashMC-Development/Bugs-and-Issues#831]
**Describe the Bug**
A little visual error where the aura around hunt Pokemon is just... around nothing? It's the best way to explain it. This aura is for Hoothoot, as its the only Pokémon that was a hunt that spawned around me, could possible be for others, it's the most noticeable with flying Pokemon though. 

**To Reproduce**
1. Get a flying/fish Pokémon
2. Look for the flying/fish Pokémon
3. The aura should be by itself, no Pokémon in it. (In theory, I'm not actually sure how to recreate it)

**Servers with the Bug**
I only play on Reshiram, but I'd guess any server with hunts active can have this happen. 

**Expected behavior**
The aura to be attached to a Pokémon, or disappear when the Pokemon despawns. 

**Screenshots**
![image](https://user-images.githubusercontent.com/93282314/142942907-61f07ca4-f1ab-42f4-94c9-f6bb2ff5a5b1.png)
Around the Amaura Pixel art's mouth
https://cdn.discordapp.com/attachments/526879084534562829/912455864542183484/IMG_8937.jpg
On the tree next to -"my jaw" HP. And just North East of there on another tree

**Additional context**
Looks a little silly when it's such a common Pokémon, littering my plot with fire, I think it's kinda goofy for the time being, hehe.

**Comment by HackuJacku** [comment]
Fixed
