### ISSUE TITLE
Can't get out of warp pvp on survival

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#834]
**Describe the Bug**
On the survival server, there is no command to get out of /warp pvp. 
**To Reproduce**
1. Go to /warp pvp
2. try to leave
3. See error 

**Servers with the Bug**
Please provide a list of which servers have this bug.
Survival
**Expected behavior**
It is expected that there is a command to leave /warp pvp. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
