### ISSUE TITLE
Poketracker bugged

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Bugs-and-Issues#835]
**Describe the Bug**
When looking under the recent bosses and recent shinies tab it shows up the last 3 ultra beasts on both tabs

**To Reproduce**
1. do /poketracker
2. look at last 3 spawned ultra beasts
3. then look at last 3 bosses and shinies and see it's the same 3 ultra beasts

**Servers with the Bug**
I'm on groudon but since its a command this is prob every server

**Expected behavior**
When looking at the poketracker the shinies/bosses tab will show the ultrabeasts tab

**Screenshots**
![Screenshot 2021-11-23 125057](https://user-images.githubusercontent.com/93420175/143078533-2336fd26-fc4a-4937-ae50-64b66c357f03.png)
![Screenshot 2021-11-23 125115](https://user-images.githubusercontent.com/93420175/143078546-5c869503-3e3f-466c-ab04-99cb4a1b35ec.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
