### ISSUE TITLE
GTS Minimum price is whack

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Bugs-and-Issues#836]
**Describe the Bug**
The GTS minimum price is really weird depending on what you're selling. I went to go sell a 64 stack of pokeballs for like maybe 1k-2k but apparently the minimum for pokeballs is 19k?? Yet when I go to sell my legendary latias it says its minimum is only 2k?? Like this is absolutely broken. I am unsure if this is a typo or just an oversight when setting prices but geeeeez, def need to get this looked at.

**To Reproduce**
1. Open GTS and go to list an item
2. Check every listing category and see the minimums for each category are very different.

**Servers with the Bug**
Every server that has the GTS

**Expected behavior**
GTS categories are not exactly fine tuned and the prices vary greatly 

**Screenshots**
![Screenshot 2021-11-23 131621](https://user-images.githubusercontent.com/93420175/143084821-d7095a4f-ba82-4447-aadb-1f4ae680e253.png)
![Screenshot 2021-11-23 131648](https://user-images.githubusercontent.com/93420175/143084833-5aee59bd-10b8-4478-a26d-ee89919defbf.png)

**Additional context**
Screenshots are comparing the stack of 64 regular pokeballs minimum price to my legendary latias minimum price.

Also, you guys might want to add that pokemon CANNOT be listed if they have a held item. If you look at my latias I can sell her and her mega stone for a whopping 2k. That's seriously messed up. Plus people might forget to take a held item off and that will cause lots of complications further down the road.

**Comment by Rasgnarok** [comment]
Closing, duplicate.
