### ISSUE TITLE
Battle tower 50:50 crate key reward does not give you the key

### ISSUE THREAD

**Issue by andydandy2173** [SmashMC-Development/Bugs-and-Issues#837]
**Describe the Bug**
Battle tower 50:50 crate key reward does not give you the key
**To Reproduce**
1. Go to battle tower
2. Click on traders
3. Scroll down to 50:50 shiny key
4. Buy it

**Servers with the Bug**
rayquaza at least, idk others
**Expected behavior**
Trader gives crate key

**Screenshots**
'N/A'.

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
Fixed from next reboot
