### ISSUE TITLE
Miner's madness skill dosn't work

### ISSUE THREAD

**Issue by yellowgiraffe05** [SmashMC-Development/Bugs-and-Issues#838]
**Describe the Bug**
When i have my pickaxe in my hand and mine, im trying to use the miner's madness skill but it dosn't work...i don't get the mining speed boost.

**To Reproduce**
1. Equip ur pickaxe and try to use ur right click skill.
2. U will see nothing happens.

**Servers with the Bug**
Zekrom

**Expected behavior**
I expected to get mine faster but nothing happened

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
