### ISSUE TITLE
Not Receiving Capture Pokemon In Warzone

### ISSUE THREAD

**Issue by Scooby-Dooby** [SmashMC-Development/Bugs-and-Issues#839]
**Describe the Bug**
Captured a pokemon in warzone then says the pokemon broke free

**Servers with the Bug**
Groudon

**Expected behavior**
I expected my pokemon to be in either the pc or wz bank

**Additional context**
N/A

![Screenshot_2021-11-23_164754](https://user-images.githubusercontent.com/94941115/143152348-5862f37c-97d1-4255-8d51-56857fb0704b.png)
![Cut the cap](https://user-images.githubusercontent.com/94941115/143152359-e14bfc98-5d2a-49d7-baea-787f6ecc12b0.png)

**Comment by HackuJacku** [comment]
This is a bug with StatsCatcher, not Warzone. You technically didn't catch the Pokémon.
