### ISSUE TITLE
NewVote crate reward order

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#84]
**Describe the Bug**
In the NewVote crates, there's a mythical reward in between legendary rewards, which is visually speaking displeasing.

**To Reproduce**
1. Go to /warp crates
2. Left click on the NewVote crate
3. On Page 1, the Mythical reward 'rare crate key' is on the second spot. It's in between legendary rewards, meaning it's not placed in the correct order.

**Servers with the Bug**
All.

**Expected behavior**
The rewards should be listed in order of rarity. 

**Screenshots**
![newvote mystc](https://user-images.githubusercontent.com/82727445/117176131-d2b75d80-adcf-11eb-9058-3b3c30dac6fa.png)
![newvote legendary](https://user-images.githubusercontent.com/82727445/117176151-d8ad3e80-adcf-11eb-9fc4-ef08a10fc77a.png)

**Comment by HackuJacku** [comment]
Note for @HackuJacku: Rare Crate Key is suppose to be a Legendary, not Mythical reward.

**Comment by LifelessDingus** [comment]
Then the bug is that the reward says it's mythical, rather than legendary. Do you want me to make a new report for it?

**Comment by HackuJacku** [comment]
@LifelessDingus - No, I've put a note for myself so I remember what exactly the issue is. I'll be fixing this evening.

**Comment by HackuJacku** [comment]
Fixed the text from next reboot - confirmed on Rayquaza.
