### ISSUE TITLE
Endbattle not working in wilderness

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#840]
**Describe the Bug**
/Endbattle seems to only be working for paid ranks on certain servers

**To Reproduce**
1. Go on server
2. Engage in battle outside of wz
3. When not having a paid rank try and use /endbattle
4. See that you do not have permissions unless a paid rank

**Servers with the Bug**
Rayquaza and Kyogre

**Expected behavior**
/endbattle should be available to players outside of wz

**Screenshots**
N/A.

**Additional context**
Might used to troll when everyone has access since ending a raid ends it for everyone.

**Comment by HackuJacku** [comment]
Fixed
