### ISSUE TITLE
Gts Auction bid refund bug

### ISSUE THREAD

**Issue by Sketch7788** [SmashMC-Development/Bugs-and-Issues#841]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Sketch7788** [comment]
I made a bid on the gts auction. I logged off, when I relogged somebody had surpassed my bid. However my money wasn't refunded even though it did say in chat that it would refund me.

**Comment by HackuJacku** [comment]
Fixed. Please also complete the format in the future, @Sketch7788 as it provides us with the essential information required to fix issues.

**Comment by Sketch7788** [comment]
Oh I was under the impression that it was complete sorry.  Sent from Mail for Windows From: HackoJackoSent: Saturday, 27 November 2021 13:52To: SmashMC-Development/Bugs-and-IssuesCc: Sketch7788; MentionSubject: Re: [SmashMC-Development/Bugs-and-Issues] Gts Auction bid refund bug (Issue #841) Fixed. Please also complete the format in the future, @Sketch7788 as it provides us with the essential information required to fix issues.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
