### ISSUE TITLE
Breeding issues

### ISSUE THREAD

**Issue by SenpaiCantAim** [SmashMC-Development/Bugs-and-Issues#842]
The issue is that whenever i breed a slowpoke i always get a gala one from the egg, i breed a normal one with an everstone with a ditto however i always get a gala slowpoke, its said by other staff this is a bug. Not sure if its for every mon with a gala/ alolan form but least for slowpoke it is.

**Comment by Its-JER** [comment]
Yeah can confirm hatched like 10 eggs, parents are regular slowpoke (holding everstone) and a totodile. Somehow they all came out galarian slowpokes. Server: Kyruem

**Comment by Superfire96** [comment]
Breeding them in the ultraspace will fix the issue
