### ISSUE TITLE
Bingo Card Issue

### ISSUE THREAD

**Issue by Daeroee** [SmashMC-Development/Bugs-and-Issues#843]
Hello, I created a ticket, however, got sent here by a member of staff on the Discord server. I won a Bingo ticket from a vote crate and apparently I am unable to receive baby pokémon unless it's via Warzone but the moderator said how they don't think it'd count towards the catch bingo due to the warzone bank. I used raids to try and catch a Leafon but it didn't work and ended up using a masterball for nothing lol. Either way, I'm a bit confused on catching some of these pokémon?

**Servers with the Bug**
I'm not sure? I'm on Groudon though

**Expected behavior**
I just expected to receive a bingo card with catchable pokémon I suppose?

**Screenshots**
![unknown (1)](https://user-images.githubusercontent.com/95001413/143326468-2328fe13-4743-425e-a80a-9ea52a8b0ddc.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed in next version.
