### ISSUE TITLE
Not able to steal if opponent /hub or disconnect

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#845]
**Describe the Bug**
Not able to steal if opponent /hubs or disconnects. It just says battle crashed 

**To Reproduce**
1. Go Warzone.
2. Engage player in battle.
3. Ask them kindly to /hub or disconnect :)
4. It says battled crashed. No option to steal.

**Servers with the Bug**
Groudon.

**Expected behavior**
It should let you steal as it says in the latest changelog.

**Comment by HackuJacku** [comment]
Fixed in next Warzone version.
