### ISSUE TITLE
Dungeon Bugs

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#846]
**Describe the Bug**
1. Waiting glitch in dungeon battles is really annoying as you don't get the rewards and lose the time you spent there. Moreover, you can't attempt the dungeon again that day. 
2.  Healers are not working at Medium and Hard Dungeon. It says you don't have the permission.

**Servers with the Bug**
Groudon.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
