### ISSUE TITLE
giftcard on store description

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#847]
**Describe the Bug**
When i try to buy a gift card from the store it says to enter a server (i can put my email in but just the description says put in a server)

**To Reproduce**
go to smashMC store
buy a giftcard
go to screen where u put in ur email

**Servers with the Bug**
store

**Expected behavior**
expect it to say something like 'please put in ur email'

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/143434838-b1c225c6-e052-46fe-93e5-0962e1e0accf.png)

**Additional context**
NA

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
