### ISSUE TITLE
Dungeons delete Z crystals

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Bugs-and-Issues#848]
**Describe the Bug**

**To Reproduce**
1. Go to Any dungeon
2. Click on enter
3. Enter the dungeon 
4. Z crystal will get deleted from the mon after the first battle

**Servers with the Bug**
Rayquaza prob all servers

**Expected behavior**
The Z crystals should stay and not get deleted

**Screenshots**
No

**Additional context**
No

**Comment by Mikirae** [comment]
Aren’t they in your dungeon pouch?

**Comment by Superfire96** [comment]
They do not get deleted, the items that are not allowed will go in your /dungeon bag
