### ISSUE TITLE
/dungeon bag not working

### ISSUE THREAD

**Issue by br183adl** [SmashMC-Development/Bugs-and-Issues#849]
**Describe the Bug**
dungeon bag is not working and the command does not exist
**To Reproduce**
1. Go on a server bring an illegal item to dungeon
2. should be removed and placed in your dungeon bag
3. when out of dungeon attempt to use ''/dungeon bag''
4. says the command does not exist

**Servers with the Bug**
all servers

**Expected behavior**
for the dungeon bag to be accessible 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
`/dungeon bag`
