### ISSUE TITLE
NewVote Icon for depth strider reward is wrong

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Bugs-and-Issues#85]
**Describe the Bug**
In the NewVote crates, there's an uncommon reward for a Depth strider III Enchanted book. The icon for this reward is a picture of new running boots. The other book rewards have an echanted book as their icon, so this one should also be a book (unless this was done purposely)

**To Reproduce**
1. Go to /warp crates
2. Left click on the NewVote crate to preview the rewards
3. Go to page 2
4. See the uncommon reward, which gives a book but has new running boots as its icon

**Servers with the Bug**
All.

**Expected behavior**
The icon for the Depth strider III enchanted book reward in the NewVote crate should be a book, not new running boots.

**Screenshots**
![newvote depth strider](https://user-images.githubusercontent.com/82727445/117176902-b10aa600-add0-11eb-90d1-3393fa7c07f7.png)

**Comment by HackuJacku** [comment]
Changed to an enchanted book.
