### ISSUE TITLE
Tourney a weird guy ngl

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#850]
**Describe the Bug**
A random tourney started after server reset, tried to /tournament reroll and claimed it was not random. Also did not give me a random team

**To Reproduce**
Go to rayquaza (may be other servers)
Join tournament
Attempt to /tournament reroll

**Servers with the Bug**
Rayquaza at a minimum
**Expected behavior**
Completely reroll your team.

**Screenshots**
![image](https://user-images.githubusercontent.com/86004012/143499689-1ed685fe-808a-4b06-8a2e-16685d98ad93.png)
![image](https://user-images.githubusercontent.com/86004012/143499674-35c6c75f-c148-47e0-915d-70c5b6c38664.png)

**Additional context**
N/A

**Comment by Archie4690** [comment]
Was not aware rayquaza tournaments are bugged at the moment.

**Comment by HackuJacku** [comment]
Fixed
