### ISSUE TITLE
GTS acting weird

### ISSUE THREAD

**Issue by Leamyyy** [SmashMC-Development/Bugs-and-Issues#851]
**Describe the Bug**

So I tried to put up a battle perfect Deino on GTS, but then it capped out at 20k. Which is extremely low for a bp mon and aspecially a bp sudo legend. So maybe there's a bug with this?

**To Reproduce**

I just put up a unbreed bp deino on GTS

**Servers with the Bug**

Rayquaza but i think all are affected

**Expected behavior**

Maybe raise the maximum price for bps

**Screenshots**
![2021-11-26_00 02 13](https://user-images.githubusercontent.com/93057830/143506478-a4c23895-5126-4fc8-8ce3-f3f9f31931c2.png)

**Additional context**
This does not just apply to Deino btw, I think it's not non ha bp mons

**Comment by ghost** [comment]
Ye, GTS is allowing 20k maximum for BPs and 40k maximum for BP HAs which is way too low in my opinion.

**Comment by AngryRedHead101** [comment]
Any BP is worth 80k and up, BP Ha's can go now for 120k-300k

**Comment by HackuJacku** [comment]
Same as #836
