### ISSUE TITLE
Battle Bugs/ things that shouldnt happen

### ISSUE THREAD

**Issue by SenpaiCantAim** [SmashMC-Development/Bugs-and-Issues#852]
When you battle in either warzone or in the normal world you are unable to either use Z-Moves or Mega evolution when a player has Dmax, this is very unfair in terms of battlling and needs to be sorted.

**Comment by HackuJacku** [comment]
Not a bug, this is a feature of Pixelmon. If the opponent dynamaxes, you can dynamax. Same with Z-Crystals and Megas.
