### ISSUE TITLE
Received a random legendary via skill level but did not receive it

### ISSUE THREAD

**Issue by g0ggleb0x** [SmashMC-Development/Bugs-and-Issues#853]
**Describe the Bug**
I had just gotten to skill level 250 in breeding and a message in chat said I had earned a random legendary, except I didn't get any paper for it or a new legendary in my pc or party. My inventory had lots of space and it was no where on the floor around me.

**To Reproduce**
I'm not sure if this is a reoccurring issue or if it can be reproduced as 250 is a high level and I'm nowhere near it in my other skills. I've never heard of it happening to anyone else.

**Servers with the Bug**
It happened on Zekrom, I don't know about the other servers as I don't play them often enough to have high skills.

**Expected behavior**
I only want to receive the reward I should have gotten, a random legendary paper.

**Screenshots**
![image](https://user-images.githubusercontent.com/95084242/143582569-5a1e2522-51a0-4ce0-a68d-51d494d6b1b2.png)
![image](https://user-images.githubusercontent.com/95084242/143582683-bba9d555-4095-44be-a0bb-c1e09a06b5e9.png)

**Comment by HackuJacku** [comment]
Fixed - please create a ticket if you need the Pokémon.
