### ISSUE TITLE
You can use ubers in Gym battles

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#855]
**Describe the Bug**
You are able use some legends like Shadow Callyrex, Mega Rayquaza and Zacian in Gym battles

**To Reproduce**
1. Go to /gyms
2. Fight a gym
3. Be able to battle with illegal legends

**Servers with the Bug**
Seen on Kyurem but prob all

**Expected behavior**
Shouldnt be able use those Pokemon

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/143665122-4be97d4d-19b7-4e92-9ab7-68c5cf0ca092.png)
![image](https://user-images.githubusercontent.com/84816052/143665137-91dc95a8-6d24-4d3f-af2d-caa4446ed125.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by M1n0j** [comment]
As far as I know its all the typings on all servers

**Comment by M1n0j** [comment]
This is due to the Gym being set to allow 2 legends, and is not restricted to 2 nat dex legends
Should be banned - Rayquaza, Mewtwo, Lugia, Ho-oh, Kyogre, Groudon, Deoxys (Base Form, Attack form, Speed form), Dialga, Palkia, Giratina (Both forms normal and origin), Shaymin-Sky, Arceus, Tornadus-Therian, Reshiram, Zekrom, Landorous (base form), Kyurem-Black, Kyurem-White, Meloetta-Pirouette, Genesect, Xerneas, Yveltal, Zygarde (50% and Complete which is via ability Power Construct), Solgaleo, Lunala, Pheromosa, Magearna, Marshadow, Naganadel, Zacian, Zamazenta, Eternatus, Urshifu-Single-Strike, Spectrier, Calyrex-Ice, Calyrex-Shadow

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
