### ISSUE TITLE
Pokestop on rayquaza

### ISSUE THREAD

**Issue by DragonBoyz12** [SmashMC-Development/Bugs-and-Issues#856]
Describe the problem: Rayquaza is missing one of the pokestops

expected behavior: to have a pokestop to collect pokeballs and other items from

Screenshots:
 
![Screenshot 2021-11-26 185625](https://user-images.githubusercontent.com/93355923/143666013-bb4946bf-ee8d-4202-930c-c32eb4fd09b0.png)

**Comment by Superfire96** [comment]
Fixed
