### ISSUE TITLE
Gets a timer on the elite 4 battles when disqualified 

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Bugs-and-Issues#857]
**Describe the Bug**
Timer when u get disqualified by w8ing glitch

**To Reproduce**
1. ./gyms join the que
2. wait for them to accept, get a w8ing glitch 
3. they diqualify u and then u get the 12 hour timer and cant battle them again
4. Will see the Join que coldown 

**Servers with the Bug**
Rayquaza but can be on other servers

**Expected behavior**
Should battle the elite 4 member instantly after with no coldown

**Screenshots**
![image](https://user-images.githubusercontent.com/86523809/143676716-1a2a0a59-0230-49b5-9bfe-19e26b0c7dfa.png)

**Comment by HackuJacku** [comment]
@Sadkeemstar112 - who did you battle please?

**Comment by HackuJacku** [comment]
Intended - you're disquieted.
> (of a person) declared ineligible for an office, activity, or competition because of an offence or infringement.
