### ISSUE TITLE
Dynamax glitch

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#858]
**Describe the Bug**
You can flinch a dynamax Pokémon 

**To Reproduce**
1.Dynamax a Pokémon
2.Use a move that causes it to flinch (icicle crash flinched my clefable)

**Servers with the Bug**
Groudon, maybe all

**Expected behavior**
Dynamax Pokémon can’t  be flinched
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Forwarded to PixelmonMod.
