### ISSUE TITLE
Knock off glitch 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#859]
**Describe the Bug**
knock off fails if the opponent does not have an item for raid dens 

**To Reproduce**
1. Go to a raid den use a poke that has knock off 

**Servers with the Bug**
zekrom 

**Expected behavior**
it should hit just with 65 power instead of 110 

**Screenshots**
N/a 

**Additional context**
I am unsure if it also happens In Regular battles

**Comment by HackuJacku** [comment]
Forwarded to PixelmonMod.
