### ISSUE TITLE
/firstspawn is not blocked in wz

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#86]
**Describe the Bug**
u can use /firstspawn (which does the exact same as /spawn) to instantly warp out of wz.

**To Reproduce**
get to wz, try the command

**Servers with the Bug**
tested on kyo and mew, but probs everywhere

**Expected behavior**
that command should be blocked in wz

**Comment by HackuJacku** [comment]
@Bruhbert1999 - please can you check every server and let me know the outcome? Keep in mind: you override GD flags currently.

**Comment by Shoji007** [comment]
@HackuJacku ive tested this on all servers and its still works only on Darkrai

**Comment by Rasgnarok** [comment]
Fixed
