### ISSUE TITLE
Zapdos buymove 

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#860]
**Describe the Bug**
Zapdos can’t learn heTeave and hurricane in /buymove

**To Reproduce**
1. Go to /buymove
2. Click zapdos and they aren’t there

**Servers with the Bug**
Zekrom

**Expected behavior**
Heatwave and hurricane should be there 

**Screenshots**
n/a 

**Additional context**
n/a

**Comment by HackuJacku** [comment]
Added to master.
