### ISSUE TITLE
Problem with battling npc's in naturally generated gyms

### ISSUE THREAD

**Issue by Al3xq** [SmashMC-Development/Bugs-and-Issues#861]
**Describe the Bug**
I am trying to battle a npc in a naturally generated gym on the kyogre server. When i try battle him i can get into the battle but when i try to use a move i get put out of the battle. When i get put out of the battle the gets send in the chat: "A Battle error has occured! Check the console for details and report this bug to the Pixelmon developers."

**To Reproduce**

**Servers with the Bug**
I know that the kyogre server has this cause its the one i play on

**Expected behavior**
I expected to just challenge the npc and fight him but i cant

**Screenshots**
![image](https://user-images.githubusercontent.com/95141702/143690613-a36a5505-f482-40a1-b966-9b27ec804a73.png)
![image](https://user-images.githubusercontent.com/95141702/143690555-f400424e-67c3-4e44-84d9-86208885cfa8.png)
Look at the chat: "A Battle error has occured! Check the console for details and report this bug to the Pixelmon developers."

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
@Al3xq - please provide the coordinates of the gym. I'll also need expect reproduction steps (e.g: what moves you and the NPC picked).

**Comment by Al3xq** [comment]
@HackuJacku i had found another gym and it had the same problem. And it seems like any move that i use is getting me kicked out of the battle with the same message as before: "A Battle error has occured! Check the console for details and report this bug to the Pixelmon developers."

**Comment by Al3xq** [comment]
Btw the cordinates to one gym are: 7214.353/64/2134.101

**Comment by Bkdevileu** [comment]
Same happened to me a few patches ago (before reset)

**Comment by HackuJacku** [comment]
Pixelmon battle glitch. Forwarded to Pixelmon.
