### ISSUE TITLE
2nd Elite 4 bugged

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Bugs-and-Issues#862]
**Describe the Bug**
Cant battle the 2nd elite 4

**To Reproduce**
It does not let me chose my pokemon and i have 0 pokemons in my party after that

**Servers with the Bug**
Rayquaza prob all servers

**Expected behavior**
Should select the mons to battle

**Screenshots**
https://medal.tv/games/minecraft/clips/73245310/d1337nKt7CGA?invite=cr-MSxpQmssNzkxMTI3Nyw 
**Additional context**
No

**Comment by M1n0j** [comment]
Elite 4s Perspective https://youtu.be/NMFpiU2TRTY

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
