### ISSUE TITLE
Weird Duplication Bug.

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#863]
**Describe the Bug**
Ok I don't know how this happened but I will try my best to explain it. A player was able to come warzone with 5 pokemon. The first time I battled him, I was shown only 5 pokemon in his party to steal from. The second time the guy entered the wz, he caught a eternatus first and then I battled him. Him having only 5 pokemon in his party, the eternatus got duplicated, 1 in his party and 1 in his wz bank. Proof his attached below. You can see he was able to use lvl 89 eternatus in our battle and both eternatus have same stat.

**Servers with the Bug**
Groudon.

**Screenshots**

https://user-images.githubusercontent.com/25759066/143718442-d3dd637e-2971-4f55-8e35-6afd4fa1c40c.mp4

https://user-images.githubusercontent.com/25759066/143718444-61d16e91-15e7-4221-8bff-df61da32be99.mp4

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
