### ISSUE TITLE
Losing held items again pokemon in warzone

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#864]
**Describe the Bug**
When you battle a pokemon in wz and you use your held item, it is deleted from the pokemon

**To Reproduce**
1. Go to warzone
2.Battle a mon using a pokemon holding a berry
3. make the pokemon use the berry
4. no berry

**Servers with the Bug**
groudon

**Expected behavior**
keep berry/other held items

**Comment by HackuJacku** [comment]
@Dxhcky - what held items is this used for? All of them or consumable ones like Focus Sash?

**Comment by Dxhcky** [comment]
All consumable held items such as a focus sash, berries or a power herb

**Comment by HackuJacku** [comment]
This isn't a bug, that's an intended feature of Pixelmon.
