### ISSUE TITLE
Warzone Stealing Bug

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#865]
**Describe the Bug**
In the steal menu, once you go forward, it doesn't allow you go back to previous pages and see all the pokemons in wz bank of the player.

**Servers with the Bug**
Groudon.

**Expected behavior**
Should allow you to go back to previous pages.

**Screenshots**

https://user-images.githubusercontent.com/25759066/143731629-d0c6bdc2-1f9e-472a-8b2e-1cdb5c78cbbb.mp4

**Additional context**
N/A

**Comment by Superfire96** [comment]
Fixed
