### ISSUE TITLE
Golden Hourglasses 

### ISSUE THREAD

**Issue by DragonBoyz12** [SmashMC-Development/Bugs-and-Issues#866]
Describe the Bug
when using a golden hourglass it only boosted one mon when it should boost both

1.use a golden hourglasses on a breeding machine
2. wait and when the boost kicks in it only boosts one mon

Servers with the Bug
only tested on Rayquaza 

Expected behavior
it is supposed to boost both mons by one breeding level but it only boosts one

**Screenshots**
![Screenshot 2021-11-28 045902](https://user-images.githubusercontent.com/93355923/143768833-bccf7975-9622-4a58-9f04-5443643be345.png)
in the photo it shows the Trapinch at purple breeding level but the Snom is at white even when they were both put in at the same time

**Comment by ghost** [comment]
Both the pokemons are at different stages of breeding because both pokemon have different level of suitability with the environment. Pretty sure it is not a bug.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
