### ISSUE TITLE
i didn't receive a random non legandary shiny pokemon

### ISSUE THREAD

**Issue by Sreehan123** [SmashMC-Development/Bugs-and-Issues#867]
**Describe the Bug**
I didn't receive a  random non-legendary shiny pokemon from a vote crate

**To Reproduce**
1. i opened a vote crate
2. receive random non-legendary shiny pokemon
3. don't receive

**Servers with the Bug**
Rayquaza

**Expected behavior**
receive random non-legendary shiny pokemon

**Screenshots**
![image](https://user-images.githubusercontent.com/95187785/143784062-e0c67646-99c9-4a40-b1b5-cc0fdf1ab825.png)
![image](https://user-images.githubusercontent.com/95187785/143784073-9c08593d-a906-4add-864f-fc19233e5785.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
This is not broken. The random Shiny is put directly into your party and if your party is full, your PC.
