### ISSUE TITLE
Warzone glitch

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#868]
**Describe the Bug**
If someone closes their minecraft while on the team selection screen, you are stuck and your timer goes down.

**To Reproduce**
1. Go to warzone
2. Battle someone
3. Select your team and have them alt f4
4. Stuck with timer going down
**Servers with the Bug**
Groudon

**Expected behavior**
I'm not sure but maybe get an automatic win or something? All i know is this shouldnt happen 

**Screenshots**

![Minecraft 1 12 2 28_11_2021 20_25_00](https://user-images.githubusercontent.com/86555718/143784715-cd323037-933f-4c0f-904e-aeca5f072281.png)

In this screenshot you see my timer going down and the guy i battled just isnt there as he alt f4 when i attacked him

**Comment by HackuJacku** [comment]
Fixed in next Warzone version.
