### ISSUE TITLE
Another warzone glitch

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#869]
**Describe the Bug**
If someone battles you as you battle a wild pokemon, they become glitched, or if you and someone else both battle the same person t the same time, one of you will be glitched. this glitch is being stuck on the selection screen with your time frozen until you either alt f4 or get a mod to kick you and give you back what you lost.

**To Reproduce**
1. Go to warzone
2. Have two people attack the poor victim at the same time
2. One of the people (possibly the person who attacked last) will be stuck in the screen as shown in my screenshot

**Servers with the Bug**
Groudon

**Expected behavior**
Don't get stuck

**Screenshots**
![Minecraft 1 12 2 28_11_2021 20_32_11](https://user-images.githubusercontent.com/86555718/143785437-f65c08c5-5b5e-476c-8afe-18de88d8eb14.png)

Similar to the other glitch but this time your timer is frozen

**Comment by Rasgnarok** [comment]
This is a Pixelmon bug, should be forwarded to the https://pixelmonmod.com/tracker.php?p=2 itself, IF reproducible outside of Warzone.
