### ISSUE TITLE
Zygarde from the galaxy skin crate is bugged

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Bugs-and-Issues#87]
**Describe the Bug**
After getting a complete zygarde from the galaxy skin crate and relogged, the zygarde turned into a 10% one (dog form) 
Currently when i check it looks like 0% form instead of the dog in box/party

**Servers with the Bug**
Jirachi (could be all)

**Expected behavior**
Zygarde reimans complete form

**Screenshots**
https://media.discordapp.net/attachments/839546046111154187/839546797927563284/5f580df486e17d47c64188db64f70c5d.png?width=1025&height=23
https://media.discordapp.net/attachments/839546046111154187/839546147742941184/unknown.png?width=796&height=498

**Comment by HackuJacku** [comment]
@Rasgnarok - is this an intended mechanic of Pixelmon? If so, would it be possible to get it changed please?

**Comment by Rasgnarok** [comment]
@HackuJacku It honestly would need to be reported to Pixelmon as a bug: https://www.pixelmonmod.com/tracker.php?p=2. Only then will we know, so can you forward that issue to the mod's tracker, @Lun17 ?
