### ISSUE TITLE
eeveelution scarfs/other cosmetics? are taken off when closing minecraft

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Bugs-and-Issues#870]
**Describe the Bug**
I got elite rank recently so I was excited to use my vaporeon scarf, I had it on the whole time and then logged off and closed minecraft to go get dinner. After logging back on my vaporeon scarf was taken off and I had to put it back on. Tested this out multiple times and confirmed that logging off completely clears any cosmetics i had on (atleast the eeveelution scarfs)

Also I'm experiencing a bug where I cannot see my friend that is wearing an eeveelution scarf and they can't see mine but others can? I can also see other peoples scarfs just not his. I use technic and he doesn't so its not our launcher causing the issue. And its not that we dont have a texture pack on because when I F5 I see it on me and I can see certain peoples scarfs.

**To Reproduce**
Steps to reproduce the behavior of bug 1:
1. Put on any eeveelution scarf using /redeem gui. 
2. Confirm its on then completely close minecraft.
3. Log back on and see that its been removed and you need to re equip it.

Steps to reproduce the behavior of bug 2:
1. I have no idea, we had pipplop and eboyjay get on and test it out and we had very confusing results. 

**Servers with the Bug**
I only play on groudon but it could be other servers.

**Expected behavior**
Bug 1 - When logging on and off minecraft any eeveelution equipped will be removed and you'll need to reselect it
Bug 2 - Some people can't see other peoples eeveelution scarfs for some odd reason.

**Screenshots**
![Screenshot 2021-11-27 230600](https://user-images.githubusercontent.com/93420175/143793463-2fa8ae8e-6f4b-4b43-bd9c-29c1809c96ba.png)
![Screenshot 2021-11-27 230614](https://user-images.githubusercontent.com/93420175/143793465-8c1ad818-cb71-4d5c-8038-11bf02623e7d.png)

**Additional context**
Screenshot one my friend is also wearing the vaporeon scarf but I cannot see it.
Screenshot two I am wearing the vaporeon scarf but he cannot see it.

**Comment by HackuJacku** [comment]
Sadly unable to fix, issue within Pixelmon.
