### ISSUE TITLE
/Textures Link Error

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#873]
**Describe the Bug**
When you do /textures and click the link provided it gives you an error site

**To Reproduce**
1. Go to any server
2. do /textures
3. click the link and open the site

**Servers with the Bug**
All

**Expected behavior**
Should provide correct link that does error

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/143908926-8424e7c7-f83f-4e29-8558-27cb41353f6a.png)
![image](https://user-images.githubusercontent.com/84816052/143908952-c475f2a0-f2cb-4fbd-97d0-6a218f7b347b.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
The link should now work.
