### ISSUE TITLE
Can't see history of #tracker

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#874]
**Describe the Bug**
User Archie4690#6969 cannot see message history of #tracker in main smash discord.

**To Reproduce**
_Be me :P_
have ranks below. 
Not be able to see history

**Servers with the Bug**
Discord

**Expected behavior**
Be able to see history

**Screenshots**
Below
![image](https://user-images.githubusercontent.com/86004012/143909188-d5ce848d-344f-4d6b-b804-4751cf58ca52.png)

**Comment by Archie4690** [comment]
![image](https://user-images.githubusercontent.com/86004012/143909259-e5870536-62dd-46f4-afe6-2a5e357bf9da.png)

Forgot to add to main bug report ^^^

**Comment by HackuJacku** [comment]
Fixed
