### ISSUE TITLE
Yamask G Evolve issue

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#875]
**Describe the Bug**
When trying to evolve galar Yamask (evolving whilst in a desert temple), It keeps on cancelling the animation, (like a gui waiting glitch). I saw this a while back, but just thought it was a one off, as we got it to work.

**To Reproduce**
1. Try to evolve yamask g
2. Gets stuck canceling the animation

**Servers with the Bug**
All pixelmon servers i believe 

**Expected behavior**
should evovle fluidly

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Snorrlax** [comment]
Same thing happened to me on Zekrom, I put in a ticket on discord and they were able to replace my Yamask-G for a Runefrigas

**Comment by Rasgnarok** [comment]
This belongs on the Pixelmon tracker, as it's a Pixelmon bug. Please write to: https://pixelmonmod.com/tracker.php?p=2.
