### ISSUE TITLE
Evolution Clause in Gyms

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#876]
**Describe the Bug**
Evolution Clause is not enabled when challenging Gyms.

**To Reproduce**
1. Go to Gym
2. Throw Pokemon at the Gym Leader
3. See UI Evolution clause is not enabled
4. Bring Full evolved pokemon to Gyms that they usually wouldnt be allowed

**Servers with the Bug**
All, tested on Kyurem

**Expected behavior**
Shouldnt allow you to bring these Pokemon

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/143922972-243cff69-d5d2-4e52-b219-059f7d0da99b.png)
![image](https://user-images.githubusercontent.com/84816052/143923029-fe979383-a5d5-42c9-88ed-2cc73c838383.png)
![image](https://user-images.githubusercontent.com/84816052/143926521-b32b4128-864d-4f61-bd87-8b9a5bbea481.png)
![image](https://user-images.githubusercontent.com/84816052/143926548-8f7989b6-0573-4f80-9001-79f0cbb348ec.png)
 
**Additional context**
Dragapult evolves at lvl60 so shouldnt be allowed in the first lvl30 Gym. The issue applies to all

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
