### ISSUE TITLE
Miner's madness not working

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#877]
**Describe the Bug**
If miner's madness is the same as before reset, it should give buffs (Haste and speed) for a limited amount of time when you right click a pickaxe, and now whenever you do such a thing, nothing happends.

**To Reproduce**
1. Get pickaxe
2. RIght click
3. Doesn't do anything

**Servers with the Bug**
All pixelmon servers

**Expected behavior**
should give the speed and haste when you right click

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
