### ISSUE TITLE
Bug with a npc mission

### ISSUE THREAD

**Issue by Al3xq** [SmashMC-Development/Bugs-and-Issues#878]
**Describe the Bug**
I think i have gotten a bug with a npc quest where i have to defeat the lugia in the drowned quest. I still have the mission that says "Defeat Lugia!" but i lost to it and went to heal my pokemons but when i came back it wasn't there and the mission did not reset like it was used to.

**To Reproduce**

**Servers with the Bug**
The server i'm on is the kyogre server

**Expected behavior**
Once i lost to the lugia i expected that i could heal my pokemons and try again but when i came back it wasn't there. I also expected that if it wasn't there then the challenge would dissapere

**Screenshots**
![image](https://user-images.githubusercontent.com/95141702/143932784-dc0656af-e1fd-48f4-9d15-b9237dc0fa55.png)

**Additional context**
My ing is: Al3xq
I hope you some how can restart the mission for me.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
