### ISSUE TITLE
Gym battles giving you nothing

### ISSUE THREAD

**Issue by Sensouu** [SmashMC-Development/Bugs-and-Issues#879]
**Describe the Bug**
I don't have any proof for them not giving me anything.. But I'll explain it really quick as to why it didn't give me anything! 
Since Reshiram got gyms just a few days ago, I was testing my luck! The water gym claimed to give me "2 ever eggs" And "3 soothe bands". Since neither of those are items, it didn't give me anything. Not a big deal, honestly, since I can't even tell what they're supposed to be. Every gym past the water gym seemed to give me the proper items though! Just seems like the prizes for the water gyms are a little bit buggy! 

**To Reproduce**
1. Go to '/warp gyms
2. Battle the level 40 water gym
3. succeed 

**Servers with the Bug**
Reshiram (Maybe others? But the gyms here have always been a little.. err... goofy...) 

**Expected behavior**
The expected behavior should be receiving an item, instead of just text saying that you claimed an item. (And for the items to be existing, haha) 

**Screenshots**
https://media.discordapp.net/attachments/798728264276901919/914968451997630524/IMG_8975.jpg?width=1424&height=1899

**Additional context**
I'll add to this bug report if I ever get past the fighting gym! I wasn't sure if I should make a ticket or not? But I'm assuming this isn't intentional.

**Comment by Sensouu** [comment]
I see this was fixed! This one was just a month old! Could I possibly get… the missed items too 👉👈

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
