### ISSUE TITLE
Minigame Pyro Ball

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#880]
**Describe the Bug**
In minigames pyro ball dosent shout out a effect or a move

**To Reproduce**
1. Go to minigames
2. Choose scoorbunny
3. enter a game
4. use pyro ball

**Servers with the Bug**
minigames

**Expected behavior**
suppose to use pyroball

**Screenshots**
![image](https://user-images.githubusercontent.com/84050975/143987137-dbc5848a-93c2-4dee-8e16-74ea886a8c89.png)

**Additional context**
'N/A'.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
