### ISSUE TITLE
Infinite Warzone Time

### ISSUE THREAD

**Issue by AstroLuvsMemes** [SmashMC-Development/Bugs-and-Issues#882]
**Describe the Bug**
Theres a bug/glitch in wz where you can get infinite time

So the bug/glitch is if 2 players decide to forfeit at the same time, the timer stays at "Timer Frozen" 
But if you catch or KO a pokemon in WZ the timer resumes.

**Servers with the Bug**
Rayquaza

**Comment by ghost** [comment]
Pretty sure this is a visual glitch. Your timer still goes on, but not sure.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
