### ISSUE TITLE
Money dissapear glitc

### ISSUE THREAD

**Issue by Massivelist5419** [SmashMC-Development/Bugs-and-Issues#884]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Resolved in a ticket, didn't lose money. In the future, @Massivelist5419, fill out the format which provides us the information to resolve the issue. You've provided no information here, it doesn't allow us to help you and resolve the issue.
