### ISSUE TITLE
AFK Glitch

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Bugs-and-Issues#885]
**Describe the Bug**
When going afk on the server, and being marked after being afk you don't get kicked, have accidently afked over night multiple times and when checking PC I'm still online

**To Reproduce**
1. Go to any server
2. wait until you are afked
3. wait more, making sure you arent moved and you don't get kicked for being afk

**Servers with the Bug**
from what I can see, on all, know its on kyo, kyurem and reshiram for surte

**Expected behavior**
you get kicked after being afk for a while

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
IT IS A CHOICE AND WE CHOSE NOT TO AFK KICK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
