### ISSUE TITLE
Not receiving rare keys from tournaments after wining

### ISSUE THREAD

**Issue by br183adl** [SmashMC-Development/Bugs-and-Issues#887]
**Describe the Bug**
not receiving rare keys from tournaments after wining

**To Reproduce**
1. join tournament
2. wait till tournament is finished 
3. be the winner
4. rare key is not given to you

**Servers with the Bug**
rayquaza

**Expected behavior**
the rare crate to be awarded to the winner upon wining

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://user-images.githubusercontent.com/84156993/144271501-5287ee4a-b4c0-48d6-9a74-6dff35ae90d0.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
@br183adl - this should now be fixed. Please can you confirm from next reboot?

**Comment by HackuJacku** [comment]
Fixed
