### ISSUE TITLE
Gts not working properly

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Bugs-and-Issues#888]
**Describe the Bug**
Unable to open the Global Trade Station in the /gts tab.

**To Reproduce**
1. Type /gts.
2. Click on the trading machine icon.
3. It goes no further and you are unable to enter the gts.

**Servers with the Bug**
Kyogre

**Expected behavior**
A window with pokemons should open with options to make an enlistment and other stuff.

**Screenshots**
N/A

**Additional context**
Opening the sts and auction still works.

**Comment by DinglePringleUwU** [comment]
Yeah does not work for me either atm (kyogre)
Likely a temporary issue

**Comment by HackuJacku** [comment]
Fixed.
