### ISSUE TITLE
Rayquaza tournament

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#889]
**Describe the Bug**
Tournament does not give 

**To Reproduce**
1. participate in tournament on ray
2. Win the tournament
3. See that no key is given upon winning

**Servers with the Bug**
Rayquaza

**Expected behavior**
A rare key should be given when u win.

**Screenshots**
![image](https://user-images.githubusercontent.com/45851395/144386240-e6455b9a-9b54-4d3c-b13f-5d586bfa3688.png)

**Additional context**
Tournament also does not give a random team at the start.

**Comment by HackuJacku** [comment]
Fixed - next time be more specific in the issue please, @Indorlan
