### ISSUE TITLE
people able to jump off boat in Char warzone and land on Lucario

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#89]
**Describe the Bug**
you are able to jump and block glitch your way off the boat in the warzone on charizard and land on the lucario build.

**To Reproduce**
Go to warzone
have  elytra and blocks to block glitch off the boat
fly around and land on lucario
**Servers with the Bug**
Charizard

**Expected behavior**
block off the boat like the boarders in the warzone

**Screenshots**
https://gyazo.com/bfe31a5ca9fbbec0a2292cede419ee66

**Additional context**

**Comment by HackuJacku** [comment]
@Shoji007 - I've blocked off a lot of areas where I believe people could escape from. Please can you try again and let me know please? 

If you're still able to do, please can you show me exactly what you're doing when you next see me?

**Comment by Shoji007** [comment]
@HackuJacku if you can see in the screenshot i took i was watching someones live Daddy_Mikey to be exact. as i dont have those types of pokemon nor do i rename my pokemon unless its for ha hunting. so i wouldnt know what to do exactly

**Comment by HackuJacku** [comment]
@Shoji007 - I looked at the screenshot but this does not tell how where on the boat players are block glitching from. The area of the boat has barrier blocks all around it to stop people from getting out of this area.

**Comment by Shoji007** [comment]
@HackuJacku  i had limo test by showing barriers for the boat. there shouldnt be a way off now. closing
