### ISSUE TITLE
Broken things in wz/ genral battling

### ISSUE THREAD

**Issue by SenpaiCantAim** [SmashMC-Development/Bugs-and-Issues#890]
right so today in wz I had a battle where the player DID NOT miss even 1 air slash flinch and 1 sleep powder and i know for a fact this shouldn't be the case in competitive Pokémon battling, The player used togekiss air slash which flinched every single time, I get he was using kings rock super luck and using a move that has a 30% chance of flitching but man that just shouldnt exist. With the next problem vivion with compound eyes increasing the accuracy of the move but it be so only 1 mon on the team can be put to sleep at any 1 point however this isnt the case in the current smash battling system. think these should be looked and and maybe changed

**Comment by ghost** [comment]
If I am not mistaken togekiss is RU pokemon and very much part of competeive pokemon. Togekiss with serene grace is 60% chance to flinch. Getting flinched on every turn just comes down to you being unlucky. I was using togekiss earlier today and didn't get a single flinch during the entire match. Pokemon is a mix of skill + luck even at the most highest level. That being said, I think the staff meant to add sleep clause to warzone but it is not working right now as some other players have also confirmed.

**Comment by ThePapaChunks** [comment]
I think they should add the base comp rules like OH-KO Clause, Sleep Clause, accuracy based moves like minimize, and prob look into or straight up ban dmax as anyone can win with dmax it doesn't take the least amount of skill to get kills or spiraling a battle with dmax it can snowball a mon to be unbeatable.

**Comment by ghost** [comment]
oh yes..ohko clause use to work in wz..but it is not rn. A guy used sheer cold on 3 of my pokemon and connected which was really stupid.

**Comment by Superfire96** [comment]
Everything should be fixed, OHKO clause and Sleep Clause are in warzone battles
