### ISSUE TITLE
Advent Calendar Day 21 

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#891]
**Describe the Bug**
There is no reward listed for Day 21 of Advent Calendar

**To Reproduce**
1. Go to any server
2. Do /adventcalendar
3. Hover over day 21
4. No reward listed

**Servers with the Bug**
All

**Expected behavior**
Should list reward

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/144483363-123eae3a-5fc9-4f3f-8d1b-1066fb3dc4fb.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Fixed for next restart. <3
