### ISSUE TITLE
teleport into wz please as smod

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#892]
**Describe the Bug**
when i do /teleport i cannot teleport into warzone if players are there.
I would like it if i was able to bc sometimes i need to check where ppl are and what they are doing.
I cannot teleport into warzone but i can teleport them out.
I used to ahve access to this before reset

**To Reproduce**
become mod+
do /teleport (ign)
when they in warzone doesnt work

**Servers with the Bug**
all

**Expected behavior**
i expect to be able to teleport to ppl if they in warzone

**Screenshots**
NA

**Additional context**
NA

**Comment by HackuJacku** [comment]
Not possible
