### ISSUE TITLE
I dont recive a crate key when i vote

### ISSUE THREAD

**Issue by StreakLXCB** [SmashMC-Development/Bugs-and-Issues#894]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jahangir6969** [comment]
Going to close this ticket off as there no info at all. If this still an issue. Please fill in the template correctly.
