### ISSUE TITLE
Groudon E4 don’t work

### ISSUE THREAD

**Issue by Brushyboi** [SmashMC-Development/Bugs-and-Issues#896]
**Describe the Bug**
When I accept a challenge from someone won the second gym it doesn’t allow the battle to start 

**To Reproduce**
Accept a challenge on the second e4 

**Servers with the Bug**
Groudon 

**Expected behavior**
it should start the battle 

**Screenshots**
n/a

**Additional context**
Idk if it is like this for others past the second one

**Comment by Rasgnarok** [comment]
I checked into this one. @HackuJacku , a few weeks ago when you asked. On my end I am not seeing anything wrong when I compare it with Rayquaza's. Thoughts?

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
