### ISSUE TITLE
2 Delibirds on /adventcalendar

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#897]
**Describe the Bug**
There is 2 Delibirds on advent calendar on days 15 and 23

**To Reproduce**
1. Go to any server
2. Check days 15 and 23 
3. See 2 Shiny Delibirds

**Servers with the Bug**
All

**Expected behavior**
Shouldnt have 2 Delibirds

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/144694844-a79858bf-eee6-4e09-9b0f-303710eeebc5.png)
![image](https://user-images.githubusercontent.com/84816052/144694849-ff502a53-0bd6-4175-aaa6-cda13c2e3a42.png)

**Additional context**
N/A

**Comment by Mikirae** [comment]
Fixed for next restart. <3
