### ISSUE TITLE
Low Kick not imprinting onto Blank Galarian TM

### ISSUE THREAD

**Issue by Audiio** [SmashMC-Development/Bugs-and-Issues#899]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
play.smashmc.co
**Expected behavior**
When trying to imprint Low Kick on a Blank Galarian TM using the move does not Imprinting and the Blank Tm Stays blank not allowing you to get a Low Kick TR
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
Works with other moves allowed to be imprinted but not Low Kick

**Comment by Superfire96** [comment]
It's because you need a Blank TR and not a Blank TM
