### ISSUE TITLE
Using endbattle and First Aid skill whilst part of a tournament bracket

### ISSUE THREAD

**Issue by HackuJacku** [SmashMC-Development/Bugs-and-Issues#9]
**Describe the Bug**
Players can `/endbattle` in tourney then use  the First Aid skill. Battle restarts afterwards.

**To Reproduce**
1. Join a `/tourney`.
2. Use the `/endbattle` command whilst in a battle.
3. Use the First Aid Skill.

**Servers with the Bug**
All Pixelmon Servers.

**Expected behavior**
Players are unable to use these commands whilst in the tournament bracket.

**Screenshots**
![FYhgDTuPSeu9g94-1r1q_A](https://user-images.githubusercontent.com/18508413/114943497-fc6b0d80-9e3d-11eb-80ec-bbb48fb4216c.png)

**Comment by HackuJacku** [comment]
**Potential Fix**
- Blocking specified commands from being used whilst part of the tournament bracket.
- Blocking specified AquaSkills abilities from being used whilst part of the tournament bracket.

**Comment by Superfire96** [comment]
Fixed
