### ISSUE TITLE
People able to /server in warzone to log out

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#90]
**Describe the Bug**
people are able to /kyogre/mew/char/ray , ect.  to dip out of warzone

**To Reproduce**
go to warzone on dialga or whatever server you are on
type /Kyogre and get warped to that server or vise versa

**Servers with the Bug**
all servers

**Expected behavior**
block the use of  all /servernames and /server and /hub while in warzone

**Screenshots**

**Additional context**

**Comment by HackuJacku** [comment]
@Shoji007 - from the way Warzone currently is, this is not possible to change. Warzone is getting re-written in the coming weeks so it might be possible then. The issue is that the `/server` command isn't handled by the server, it's handled by the proxies.

**Comment by HackuJacku** [comment]
Added to the master Warzone ticket, unable to do anything about this currently.
