### ISSUE TITLE
/adventcalender redeem problem

### ISSUE THREAD

**Issue by HypherDeath** [SmashMC-Development/Bugs-and-Issues#901]
I cannot redeem/claim the advent calendar prize even if i have played more than 5 hours,when i go to claim it everytime it shows you need to play 29 minutes to claim.

This happened on Groudon server.

**Comment by Mikirae** [comment]
Did you play for 30 consecutive minutes?

**Comment by HypherDeath** [comment]
yes i played for like 2 hours

**Comment by HackuJacku** [comment]
The advent calendar has now been removed from the server.
