### ISSUE TITLE
The tournament wont let me join

### ISSUE THREAD

**Issue by Camcar0123** [SmashMC-Development/Bugs-and-Issues#902]
![image](https://user-images.githubusercontent.com/95540413/144717352-f4421c99-137f-45bd-be6d-2638ae47cdac.png)
I got a helper and they found this in my log file. IT will say "The tournament will start in five minutes" then it wont let me join

**Comment by Rasgnarok** [comment]
We would need to be able to reproduce it. Any idea what happened after? Sadly, this isn't an informative error.

**Comment by Camcar0123** [comment]
What do you mean reproduce it?

**Comment by Camcar0123** [comment]
its working afain

**Comment by HackuJacku** [comment]
This is caused by a Pixelmon Battle Glitch. Forwarded the issue and details.
