### ISSUE TITLE
Broken things in wz

### ISSUE THREAD

**Issue by SenpaiCantAim** [SmashMC-Development/Bugs-and-Issues#905]
Nice and short, Mind reader with sheer cold or sheer cold in general should be banned, Moves like mind reader makes sheer cold always hit and sheer cold is a 1 hit KO like man this shouldnt be a thing

**Comment by Rasgnarok** [comment]
This is a suggestion, not a bug. Please move this to: https://github.com/SmashMC-Development/Suggestions.
