### ISSUE TITLE
/pokesee for mod+ pls in warzone

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#906]
**Describe the Bug**
When someone is in warzone i would like to be able to use /pokesee on them. Now when someone is in warzone i cannot look at their team. When they disconnect while in warzone or if they are kicked while in warzone and i try to do /pokesee then the game will still tell me that i do not have access to that because they are in warzone. I would like to have access to this even when they are in warzone bc i would like to see someones team in case a rebattle is needed. to make sure they use the same team. Bc now i cannot check what the team was they were using.

**To Reproduce**
Someone disconnects in warzone or is still in warzone
i try do /pokesee on them
Says i cannot perform that action on someone who is in warzone

**Servers with the Bug**
All

**Expected behavior**
please let me see their team

**Screenshots**
NA

**Additional context**
NA

**Comment by HackuJacku** [comment]
Spoken about in Staff Discord
