### ISSUE TITLE
Pls give staff perms while in warzone

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#909]
**Describe the Bug**
When i am in warzone i do not have access to my staff commands bc i am in warzone (for example /mute or /notes).
I would like to have access to that when i am in warzone bc now i gotta wait untill im out of warzone before i can note them (i might have like 9 mins of wz time left)

**To Reproduce**
go to warzone (/warzone)
someones does somethign noteworthy
i cannot check this until im out of wz

**Servers with the Bug**
All

**Expected behavior**
I would expect to have access to the staff commands while in warzone

**Screenshots**
NA

**Additional context**
NA

**Comment by Rasgnarok** [comment]
Are you not able to execute these commands if you ignore warzone?

**Comment by jantjewieger** [comment]
I probably could but unfortunately i don't have access to this command. Pretty sure its admin+

**Comment by HackuJacku** [comment]
Done
