### ISSUE TITLE
Ray prices are wack

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#911]
**Describe the Bug**
I saw a blazikenite being sold at 5000 dollars, it definitely should not do that. I will provide screenshot below

**To Reproduce**
1. Go to rayquaza
2. Sell a megastone
3. you can sell it for 5000

**Servers with the Bug**
Rayquaza

**Expected behavior**
Should be a higher minimum price

**Screenshots**
![image](https://user-images.githubusercontent.com/89798207/144756631-27a8b068-632e-4193-ba07-42b3389d89b6.png)

**Additional context**
Maybe make the lowest price 50,000? Or more? Blazekinite is mad rare

**Comment by HobnobberJunior** [comment]
Minimum prices in general would be a good thing, since a lot of people are underpricing stuff.

**Comment by Mikirae** [comment]
Ras is the GTS config pro so assigning her here

**Comment by Superfire96** [comment]
Minimum gts pricings are now on the server, but not for the items, a megastone it's something really really rare, especially for some pokemons, i don't think a minimum pricing for that is needed
