### ISSUE TITLE
Loss of pokemon in wz bank during resets or updates

### ISSUE THREAD

**Issue by TheCatalyst525** [SmashMC-Development/Bugs-and-Issues#912]
I was in warzone when the new update came through. I caught a Celbi with a beast ball ( For the alien Celebi) and now after the reset it is not in my warzone bank ?

**Comment by HackuJacku** [comment]
@TheCatalyst525 - follow the format provided, you just need to add the detail. This isn't a bug, you need to create a support ticket.
