### ISSUE TITLE
Warzone bug

### ISSUE THREAD

**Issue by SenpaiCantAim** [SmashMC-Development/Bugs-and-Issues#913]
When a player disconnects during warzone you are unable to steal from them, this allows a lot of players who don't want to battle and lose a Pokémon leave the game so they do not lose a Pokémon, even thou doing is so against the rules atm the server has nothing to counter this other then it clears your warzone bank when you do but that's not an issue for them players who have not caught anything.

**Comment by Superfire96** [comment]
Fixed
