### ISSUE TITLE
tournament bug

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#914]
**Describe the Bug**
Some players could not battle in the tourny because it kept erroring. They tried /tournament flag and it did not work. Also /endbattle did not work. Forfeiting works to move onto the next round but then the problem continues. 
**To Reproduce**
1. Go to a server
2. join a tournament
3. try to battle
4. See if it happens

**Servers with the Bug**
Please provide a list of which servers have this bug.
all servers

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
![tournybug](https://user-images.githubusercontent.com/85481519/144778272-8a5c3f38-efc5-4554-873e-d5434c2f38bb.png)

Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by piplupqueenn** [comment]
This just happened again on Kyurem

**Comment by HackuJacku** [comment]
Endbattle or flag won't work because they're not in battle. This is a Pixelmon battle glitch. You'll need to provide specific details on which moves were used, in a new GitLab issue.
