### ISSUE TITLE
Waiting bug

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#916]
**Describe the Bug**

When you either catch or kill a Pokémon after you kill/catch them it keeps giving you the waiting bug
And if u made a move, it gives u a waiting bug too.

**To Reproduce**
1. Attack a Pokémon 
2. Pick a move to attack or run away
3. After picking a move or running away, it gives u the waiting bug and u can't /endbattle and even if u /endbattle u are still stuck in waiting

**Servers with the Bug**
Probably all servers but mainly Groudon 

**Screenshots**
![image](https://user-images.githubusercontent.com/93119451/144829855-462396aa-f674-4d75-b8a3-cafa43fea98e.jpeg)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Issue with Pixelmon. Should be fixed in the next version.
