### ISSUE TITLE
Legendary Resize wouldn't let me sell items on gtws

### ISSUE THREAD

**Issue by geusbi** [SmashMC-Development/Bugs-and-Issues#918]
**Describe the Bug**
so, basically what happened was that i couldn't sell any items on gts because i had a legendary resize on my inventory.
**To Reproduce**
1. have a legendary resize in your inventory.
2. go in gts
3. click on global trade station, new listing then click on click on show items.
4. then you should have your normal inventory there, with no prices while hovering over the items and when pressing on them nothing happens. you just move them, as if you we're on your normal inventory

**Servers with the Bug**
only tested on Groudon for now

**Expected behavior**
i expected to normally sell items on gts, even with legendary resize in my inventory

**Screenshots**
![image](https://user-images.githubusercontent.com/93953225/144908102-9986d01c-6b20-41ec-9679-d851094b8fcd.png)
**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
