### ISSUE TITLE
Frosmoth raids

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Bugs-and-Issues#919]
**Describe the Bug**
Frosmoth raids seem to be either completely broken or only broken under certain condition. Have had to raids today that both ended with an error. 

**To Reproduce**
1. Enter raid with frosmoth, in this case with a gardevoir with trace
2. Use moves
3. Wait for it to close the raid and produce error message

**Servers with the Bug**
Kyogre

**Expected behavior**
The raid will finish as usual without error

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
So this is kinda vague description of the issue. Its hard to say exactly what the bug is, since I do not recall in what order I used my moves. I am however pretty sure I Dmaxed on both occasions. The first time the frosmoth did not have its hidden ability, however in the second attempt it did. Hard to try and make the bug occur again, since I will need to find another frosmoth raid.

**Comment by HackuJacku** [comment]
PixelmonMod bug. Forwarded to them to get it fixed.
