### ISSUE TITLE
Valentines Gardevoir loses texture

### ISSUE THREAD

**Issue by Jasha1112** [SmashMC-Development/Bugs-and-Issues#92]
My Valentinesday Gardevoir loses its skin randomly it started yesterday and happened today again.

I only noticed it on Giratina

Valentinesday Gardevoir keeping its Skin

**Comment by HackuJacku** [comment]
@Jasha1112 - is this still occurring please? Can you also explain what you were doing when you noticed that this has occurred?

**Comment by Jasha1112** [comment]
yes i teleported home or to a platform to ha hunt then the texture sometimes just changes to the normal amsterdan has seen it himself

**Comment by HackuJacku** [comment]
Unable to reproduce.
