### ISSUE TITLE
Galarian Yamask evolution is broken

### ISSUE THREAD

**Issue by Gygor-137** [SmashMC-Development/Bugs-and-Issues#920]
**Describe the Bug**

I have completed the steps to evolve galarian yamask into runerigas while inside the desert temple.  The pokemon starts the evolution process but gets stuck and it keeps resetting never to finish.

**To Reproduce**

I have tried the evolution in 2 different temples, in a number of ways with the same result of getting caught in the evolution.

**Servers with the Bug**
Only tried it on Kyogre

**Expected behavior**
The galarian yamask should evolve into runerigas.

**Screenshots**
Can provide video capture if needed.

**Additional context**
N/A

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
