### ISSUE TITLE
Warzone box mons glitch 

### ISSUE THREAD

**Issue by eboyJay69** [SmashMC-Development/Bugs-and-Issues#921]
**Describe the Bug**
It doesn't let you go back in the warzone box, on the steal screen. 

**To Reproduce**
1. Win a battle in warzone
2. Have the steal screen up
3. Try to click back, to look threw the warzone mons at the bottom
4. You will not be able to go back and see the pokemon as a blank screen. 

**Servers with the Bug**
This was on reshiram, im sure it might be on other servers. 

**Expected behavior**
Let you go back through warzone enemys pokemon 

**Screenshots**
Ticket 39938- couldnt steal weird bug 

**Additional context**
Big sadge :(

**Comment by eboyJay69** [comment]
https://user-images.githubusercontent.com/84190150/148652369-162bdbf9-ed80-4b94-9818-554d9834e9a7.mp4

**Comment by Superfire96** [comment]
The issue is fixed
