### ISSUE TITLE
Paralysis doesn't get cured when a battle ends in warzone

### ISSUE THREAD

**Issue by Elibats** [SmashMC-Development/Bugs-and-Issues#923]
**Describe the Bug**
Paralysis doesn't get cured when a battle ends in warzone against a pokemon. I don't know if it's the same for other status affects or for battles against players.

**To Reproduce**
1. Go to warzone
2. get paralyzed by a wild mon/player
3. kill him
4. join another battle to see the paralysis is still there

**Servers with the Bug**
Kyurem but could happen on other servers too

**Comment by Elibats** [comment]
This happened with burn too so it should happen for all the status effects

**Comment by ghost** [comment]
Status effects are not healed after battling wild pokemon in warzone on Groudon as well.

**Comment by DinglePringleUwU** [comment]
Happens a lot on kyogre as well.
A simple, but not quite common, solution is to search for pokemon with the "limber" ability in wz. Mareanie for example. (if you are tracing for ha's that is)

**Comment by HackuJacku** [comment]
Forwarded to the developer
