### ISSUE TITLE
Rtp cooldown on Ray

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#924]
**Describe the Bug**
There is no /rtp and /rtp ultra cooldown on Ray

**To Reproduce**
1. Go to Rayquaza
2. Click on your keyboard to type /rtp or /rtp ultra
3. Click on your keyboard to type /rtp or /rtp ultra
4. See there is no cooldown

**Servers with the Bug**
Rayquaza

**Expected behavior**
There should be a cooldown for rtp on all servers.

**Screenshots**
N/A

**Additional context**
Actually forgot about this and noticed just now there is still no cooldown on Ray.

**Comment by HackuJacku** [comment]
Fixed
