### ISSUE TITLE
Survival bug report

### ISSUE THREAD

**Issue by IsTired** [SmashMC-Development/Bugs-and-Issues#925]
**Describe the Bug**
may have to see in game 

Emperor rank not showing in game
proof is in ticket 39950 

spawners dont work as intended as nothing is spawning

Villagers dont breed

**To Reproduce**
emporer rank
1. look in ticket 39950

Villagers not breeding
1.find villagers
2. trap them
3. give throw them breedable food
4. see error

spawners not working
1.place spawner 
2. wait till spawn
3. wont spawn and see error

**Servers with the Bug**
Please provide a list of which servers have this bug.
survivial

**Expected behavior**

Rank should be seen in game

villagers should bree to spawn baby villagers

spawners should spawn given entity

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

![image](https://user-images.githubusercontent.com/95708824/145082746-4fec4b58-70f1-4c91-9902-49182e747116.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
from Rambo1654 / Rambo9o#9637

**Comment by Archie4690** [comment]
@ZzSleep1101 The Spawner's are not an issue, the way spawners work changed in 1.17 and the farms that everyone uses on the server no longer works. They need to spawn on solid blocks now. 
With the Villager issue I have just tested and they are breeding perfectly, would probably be something to do with a faulty farm. (see pictures below for proof of villagers working)
![image](https://user-images.githubusercontent.com/86004012/145696464-3439929e-d3fd-4d12-9c42-48643aa46b63.png)
![image](https://user-images.githubusercontent.com/86004012/145696466-ce5d5146-01e3-4146-a8b6-efc466756f29.png)

As with the Rank icons not showing I believe that would be something that PokeKhan would need to look into to fix this.

**Comment by jahangir6969** [comment]
The issue with the rank has been fixed. That was an issue with a placeholder. read the other at the moment and will see which are bugs and which are not

**Comment by jahangir6969** [comment]
Had an look at the other issue. As @Archie4690 has said and I have tested also. I can confirm the villagers does work without and within an claim and the 1.17 have changed how stuff is spawned with spawner. They cannot be placed in the air at the moment.
