### ISSUE TITLE
Aura Crate Bug

### ISSUE THREAD

**Issue by Fr0st3O** [SmashMC-Development/Bugs-and-Issues#926]
**Describe the Bug**
Opened an aura crate and message said i had received a specific pokemon with aura. When i went to redeem i realised i had received a random legend paper + a legendary aura paper

**To Reproduce**
1. Open Aura Crate
2. Receive Specific Pokemon with Aura
3. Check inventory

**Servers with the Bug**
Kyurem 

**Expected behavior**
Expected to receive a Specific Pokemon with Aura paper.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed from next reboot
