### ISSUE TITLE
Dynamax quest

### ISSUE THREAD

**Issue by xXbumisXx** [SmashMC-Development/Bugs-and-Issues#927]
**Describe the Bug**
completed dynamax quests dont give you the reward (the band)
**To Reproduce**
1. get dynamax quest
2. complete it
3. go to npc
4. dont get the reward

**Servers with the Bug**
Zekrom / may also bee others

**Expected behavior**
fixed

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
