### ISSUE TITLE
/Skills not working

### ISSUE THREAD

**Issue by Snorrlax** [SmashMC-Development/Bugs-and-Issues#929]
**Describe the Bug**

**To Reproduce**
1. Go to Zekrom
2. Type /skills
3. Nothing happens

**Servers with the Bug**
Zekrom

**Expected behavior**
/Skills should open skills menu and you should gain exp 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Dxhcky** [comment]
Try /mmo

**Comment by HackuJacku** [comment]
Fixed from next reboot.
