### ISSUE TITLE
VILLAGE QUEST NOT WORK RAY

### ISSUE THREAD

**Issue by surporentr** [SmashMC-Development/Bugs-and-Issues#93]
**Describe the Bug**
when your in a village, find a village quest does not complete 

**To Reproduce**
1. find a village

**Servers with the Bug**
Please provide a list of which servers have this bug.
Ray
(unsure about other servers) 
 
**Expected behavior**
Quest completes

**Comment by HackuJacku** [comment]
Does this still occur as of 8.2 please?

**Comment by HackuJacku** [comment]
Looked into and the structures are messed up. I'm unable to really do anything currently due to it being related to the world. I've found that random locations now show as a location even though there are no builds.
