### ISSUE TITLE
Server wide bug (Zekrom) relating /skills

### ISSUE THREAD

**Issue by Davddn** [SmashMC-Development/Bugs-and-Issues#930]
**Describe the Bug**
/skills isn't working

**To Reproduce**
1. Go to zekrom
2. type /skills
3. It should say "unknown command.. you know the rest"
4. Boom nothings there

**Servers with the Bug**
Zekrom alone so far.

**Expected behavior**
/skills to be working again

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Dxhcky** [comment]
Try /mmo

**Comment by HackuJacku** [comment]
Fixed from next reboot.
