### ISSUE TITLE
castle dungeon bugged

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#931]
**Describe the Bug**
The first room is missing 5 mons. it says there are 5 mons left but there are no mons so u cant progress

**To Reproduce**
go to any server
type /dungeons
join the castle dungeon
5 mons are missing

**Servers with the Bug**
Reshiram and Kyurem for sure (unsure bout the others)

**Expected behavior**

**Screenshots**
NA

**Additional context**
NA

**Comment by RatedPG21** [comment]
Can confirm that the dungeon works fine in Groudon, might be an issue specific to those servers

**Comment by Mikirae** [comment]
Did a clear happen at that time?

**Comment by jantjewieger** [comment]
could have been. I don't remember its too long ago. If it was that then i know issue is fixed now

**Comment by HackuJacku** [comment]
Fixed clears causing this
