### ISSUE TITLE
Cannot vote on Groudon

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#932]
**Describe the Bug**
/vote is an unknown command on the groudon server
**To Reproduce**
1. Go to groudon
2. /vote
3. see that it's an unknown command
**Servers with the Bug**
Please provide a list of which servers have this bug.
groudon
**Expected behavior**
expected to take you to the vote links
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
<img width="1129" alt="vote" src="https://user-images.githubusercontent.com/85481519/145348741-d16560bc-99e5-4a62-b7d4-e3a33b026a91.png">

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
