### ISSUE TITLE
Fix the disappear glitch

### ISSUE THREAD

**Issue by haloser22** [SmashMC-Development/Bugs-and-Issues#933]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by haloser22** [comment]
Every time I play on the server it glitches my items when im finish battling a pokemon and it glitches my items which i gotta re log to re fix it.

**Comment by HackuJacku** [comment]
@haloser22 - please follow the format provided, the lack of information doesn't allow us to resolve the issue.
