### ISSUE TITLE
Cant use /vote

### ISSUE THREAD

**Issue by Korristube** [SmashMC-Development/Bugs-and-Issues#934]
When i try to use the command /vote it say in chat Unknown command.

1. Log on to the server
2. Choose the groudon server
3. Write /vote in chat

play.smashmc.co 
Groudon

When i wrote /vote in the chat i thought it would let me vote for the server so i can get the vote keys to open crates. 

![fonkar itne](https://user-images.githubusercontent.com/95979024/145687016-1e6ee39e-f234-4529-8dee-717605223ab6.jpg)

**Comment by HackuJacku** [comment]
Fixed.
