### ISSUE TITLE
Tournament Prize

### ISSUE THREAD

**Issue by vische** [SmashMC-Development/Bugs-and-Issues#935]
After winning the random rock paper scissors tournament that happens every so often, i never get the rare crate key from it.

**To Reproduce**
Win the tournament

**Servers with the Bug**
I only play on Rayquaza so that's the only one i know about.

**Expected behavior**
To get a rare crate key after winning

**Screenshots**
![image](https://user-images.githubusercontent.com/95987710/145695438-b42c2f1f-f180-42bf-b9b8-d0b0cd7ea68d.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed.
