### ISSUE TITLE
Ice gym kyurem kicking players out supposedly randomly.

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Bugs-and-Issues#936]
**Describe the Bug**
Ice gym on kyurem kicks player (Zain____) out after killing random amount of pokemon. He appeared to sweep the gym with a reshiram but got kicked out with the message: "Something ended this battle thus has not been scored" after killing the pokemon. Apparently this has happened to him multiple times.

**To Reproduce**
1.Go on kyurem
2. Go to level 90 Ice gym
3. Battle gym leader there
4. Kill their mons and appear to be kicked out with the message: "Something ended this battle thus has not been scored"

**Servers with the Bug**
Kyurem

**Expected behavior**
Battle continues smoothly and the gym should be able to be beaten

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Pixelmon battle bug. Forwarded.
