### ISSUE TITLE
Discord Server Channels Not Linked

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#937]
**Describe the Bug**
Server chat channels on discord are not linked. So, not able to in-game chat on the server.

**Servers with the Bug**
All.

**Expected behavior**
Should be able to see in-game chat on discord server channels.

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Caused by updates required to fix the security issue within Minecraft. Developer is aware of the bug and is working on a fix.

**Comment by ghost** [comment]
Thanks for the update.
