### ISSUE TITLE
Female Rufflet for hunt

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#938]
**Describe the Bug**
Advanced hunt  showed you needed to catch a female rufflet, sadly those are not a thing

**To Reproduce**
1. Go to any server?
2. Be very patient, wait for female rufflet hunt

**Servers with the Bug**
All servers I'm guessing tho I saw it on Ray

**Expected behavior**
Female rufflet is not a thing as it is a male only pokemon.

**Screenshots**
![Screenshot (1274)](https://user-images.githubusercontent.com/45851395/145717961-bea94e3c-f02c-49f0-8d93-448cfcf72a7e.png)

**Additional context**
Might as well check all pokemon with only one possible gender xd

**Comment by HackuJacku** [comment]
Forwarded to the developer to fix it
