### ISSUE TITLE
./pokecolor not working as intended

### ISSUE THREAD

**Issue by Bkdevileu** [SmashMC-Development/Bugs-and-Issues#939]
**Describe the Bug**
Everytime I try to do ./pokecolor, the command sends me to pokenick and I'm not able to change the pokemon's nick color, only the nick

**To Reproduce**
Do ./pokecolor, it goes to pokenick

**Servers with the Bug**
Kyurem and Zekrom, probably all of them

**Expected behavior**
Do ./pokecolor and be able to change pokemon's nick color

**Screenshots**
![image](https://user-images.githubusercontent.com/84034504/145719149-d6c0716a-bb44-425e-8ac7-ebf8b95ead8a.png)
![image](https://user-images.githubusercontent.com/84034504/145719156-6ac99bb3-3a25-4884-a9e3-e32610272db8.png)
![image](https://user-images.githubusercontent.com/84034504/145719164-a5e63163-1df6-4e67-a70c-57bd3a439349.png)
![image](https://user-images.githubusercontent.com/84034504/145719168-cea9d236-15e8-4faa-bb33-121a7181d6ed.png)

**Additional context**
N/A

**Comment by Bkdevileu** [comment]
I wasn't aware that, since this changed, you needed the color codes to change the nick of the pokemon. You can close this issue ^_^

**Comment by HackuJacku** [comment]
Not a bug. Pokecolor is an alias for PokeNick. You can't change the colour as you don't have permission to use them as part of your rank.
