### ISSUE TITLE
Legendary ivboost instead of non-legendary in mythic crate

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Bugs-and-Issues#94]
**Describe the Bug**
The mythic crate is giving you a Legendary IV boost instead of a Non-Legendary IV boost

**To Reproduce**
Go to Giratina -> open a mythic crate -> get a non - legendary ivboost

**Servers with the Bug**
Giratina

**Expected behavior**
Get a paper saying non-legendary iv-boost

**Comment by HackuJacku** [comment]
@Sparklix - in the crates preview GUI, what's the name of the reward you are winning for this to occur please? There's no reward which gives you a single Non-Legendary IV Boost.

**Comment by HackuJacku** [comment]
Fixed from next server reboot - confirmed that it's fixed on Rayquaza (using the same configs).
