### ISSUE TITLE
GTS on Kyogre is flashing and not working

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#940]
**Describe the Bug**
On the kyogre server the gts is flashing and glitching. You can sometimes buy things as some pokemon allow you to click on them while others you cannot. 
**To Reproduce**
1. Go to Kyogre
2. Do /gts
3. See error

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyogre
**Expected behavior**
Expected for gts to function normally and allow people to buy pokemon. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

https://user-images.githubusercontent.com/85481519/145732108-f7ffcbc5-976c-4678-90f8-8f282d9a623d.mov

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed.
