### ISSUE TITLE
Ore sense

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#941]
**Describe the Bug**
Maybe not a bug to be exact, rather X-ray built into the Pixelmon mod

**To Reproduce**
1. Any server
2. Get a pokemon with the moves magnet rise, metal sound or the ability magnet pull
3. go in a cave
4. use the ability see the ores light up

**Servers with the Bug**
All servers

**Expected behavior**
Built in X-ray even tho it has a cooldown seems possibly problematic for server 

**Screenshots**
N/A

**Additional context**
https://pixelmonmod.com/wiki/Ore_Sense

**Comment by HackuJacku** [comment]
Not a bug, intended feature. These items do not sell so they are worthless.
