### ISSUE TITLE
Dex Reward Issue

### ISSUE THREAD

**Issue by ItsBapo** [SmashMC-Development/Bugs-and-Issues#943]
**Describe the Bug**
After redeeming the 25% dex reward i didnt get access to ./vaults but i did get the rank.

**To Reproduce**
Im not too sure if this is an issue with me, however if its not then below are the steps
1. Redeem the 25% dex reward

**Servers with the Bug**
Possibly all, however i only know about zekrom.

**Expected behavior**
I expected to be able to use atleast 1 vault and get the rank.

**Screenshots**
![image](https://user-images.githubusercontent.com/96070359/145844513-4728007c-1ae0-4777-a35c-d3bb120f1127.png)
![image](https://user-images.githubusercontent.com/96070359/145844546-4439d6f5-34af-489a-a46c-a7c04caa9388.png)

**Additional context**
'N/A'

**Comment by HackuJacku** [comment]
Fixed. Please create a ticket on our Discord.
