### ISSUE TITLE
Dmax Galarian Darmanitan Zen Mode

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#944]
**Describe the Bug**
Zen Mode Galarian Darmanitan does not show the galarian zen mode texture but the regular darmanitan zen mode texture

**To Reproduce**
1. Any server
2. Find a Galarian Darmanitan raid (be lucky to get a hidden ability one)
3. fight it and get it to half health
4. See the regular darmanitan zen mode texture

**Servers with the Bug**
All servers

**Expected behavior**
It should show the distinct Galarian zen mode texture if it is a Hidden ability Darmanitan

**Screenshots**
![Screenshot (1275)](https://user-images.githubusercontent.com/45851395/145847607-bd52ab28-86cc-46df-ac86-ba2ea4f4e744.png)

**Additional context**
N/A

**Comment by Superfire96** [comment]
Pixelmon bug, not much that we can do to fix it
