### ISSUE TITLE
Double Clear (Kyogre and Zekrom Only)

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#945]
**Describe the Bug**
The Pokeclear happens two times in a row in the same minute. 

**To Reproduce**
1. Go to 'Kyogre'
2. Watch chat for clear Message
3. Wait for clear to happen
4. Wait for second clear to happen 50~ seconds after the first one

**Servers with the Bug**
Only Kyogre and Zekrom (I checked all the other Servers)

**Expected behavior**
Only one clear within the 10 minutes. No double clears a minute after the first clear.

**Screenshots**
![2021-12-14_15 56 09](https://user-images.githubusercontent.com/94211853/146023876-7f1e7a4c-d48a-4031-b776-584d1a1c8a07.png)

**Comment by DinglePringleUwU** [comment]
Addendum: This double-clear does not longer happen on Kyogre.

**Comment by HackuJacku** [comment]
Fixed
