### ISSUE TITLE
WZ Hole

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#946]
**Describe the Bug**
Found a two-blocks high hole in the Warzone Dimension at x -211 z 89 y 93

**To Reproduce**
1. Join Kyogre
2. Navigate to  x -211 z 89 y 93 in the Warzone

**Servers with the Bug**
At least Kyogre

**Expected behavior**
Hole not being high enough to get stuck

**Screenshots**
N/A

**Additional context**
Moved from "https://github.com/SmashMC-Development/Suggestions/issues/799" due to wrong section. Could be outdated.

**Comment by Archie4690** [comment]
Hey, Thank you for reporting this! I have fixed each of these holes. All servers should be fixed.
