### ISSUE TITLE
You can dex Tournament Pokemon

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#947]
**Describe the Bug**
The Random pokemon you get from the tourneys count towards dex progression. You also become the OT of the Tourney pokemon.

**To Reproduce**
1. Check your Dexed pokemon to know which pokemon are undexed and which not or keep track of your Dex percentage.
2. Join Tourney
3. Look if the pokemon you got are dexed for you now.

**Servers with the Bug**
At least Kyogre

**Expected behavior**
Pokemon from Tourney should not count towards dex progression.

**Screenshots**
N/A

**Additional context**
This Report was moved from "https://github.com/SmashMC-Development/Suggestions/issues/794" due to wrong Section.

**Comment by HackuJacku** [comment]
Upcoming fix
