### ISSUE TITLE
Missing Pokestop on Kyogre

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#948]
**Describe the Bug**
A pokestop on Kyogre is missing.

**To Reproduce**
1. Join Kyogre
2. Navigate to x- 36 z- 300 y 70 in the Spawn
3. See missing Pokestop

**Servers with the Bug**
This only applies for Kyogre, every other Server has it.

**Expected behavior**
It should work like the rest of the pokestops. 

**Screenshots**
![2021-12-14_17 15 26](https://user-images.githubusercontent.com/94211853/146036833-027d6e5a-467e-4469-8552-97a23ae6b23f.png)

**Additional context**
The other 17 Pokestops on Kyogre do work.
This report was moved from "https://github.com/SmashMC-Development/Suggestions/issues/797" due to wrong section.

**Comment by HackuJacku** [comment]
Added
