### ISSUE TITLE
Ev training area dropping items

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Bugs-and-Issues#95]
**Describe the Bug**
On charizard the ev training area pokemon drops items

**To Reproduce**
/warp ev and kill 1 pokemon

**Servers with the Bug**
charizard -> will look into the others

**Expected behavior**
not drop anything

**Screenshots**
https://gyazo.com/4dad68947ff68362c37b72cda953f01a

**Comment by HackuJacku** [comment]
Added DropPrevent plugin - requires set up.

**Comment by HackuJacku** [comment]
@Sparklix - fixed on Charizard. Does this occur on the other servers please?

**Comment by Sparklix** [comment]
@HackuJacku This got resolved
