### ISSUE TITLE
Cant battle the Champion and my Elite 4 progress got reset

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Bugs-and-Issues#950]
**Describe the Bug**

**To Reproduce**
1. Go to Elite 4 
2. Click on Icon and join que
3. Scroll down to Beat all the Elite 4
4. See error No champion icon and when u click on the elite 4 icon your progress gets reset.

**Servers with the Bug**
Rayquaza but can be all servers

**Expected behavior**
Should be able to battle the champion or become the champion when beaten all the elite 4 members

**Screenshots**
https://medal.tv/games/minecraft/clips/58f0LRrmDnQsH/d1337MOVaPZ7?invite=cr-MSx2V1MsNzkxMTI3Nyw
**Additional context**
No

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
