### ISSUE TITLE
Warzone bug glitching screen zekrom

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#951]
**Describe the Bug**
A player had a glitch when they entered warzone their screen started flashing (see video below, also refer to ticket 40219 for reference). They safeplaced and then went back into warzone and it happened again. When this happened, their logs below say a message "minimap is not loading" over and over again. They also had 2 death waypoints on their minimap when they got glitched. I had them restart their mc launcher and try again and the glitch did not happen again.
**To Reproduce**
1. Go to warzone
2. If it happens safeplace
3. Go back into wz
4. See it happen again
(This is what happened to the player)

**Servers with the Bug**
Please provide a list of which servers have this bug.
Zekrom

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

https://user-images.githubusercontent.com/85481519/146127803-1efa0d14-8c47-4145-ab7a-6c12ce9e3705.mp4

<img width="1511" alt="nondox" src="https://user-images.githubusercontent.com/85481519/146137824-b946d5aa-7fa0-494e-86a3-f51a40d49afa.png">

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Pixelmon battle bug. Reported to them.
