### ISSUE TITLE
My pokemon didn't evolve

### ISSUE THREAD

**Issue by xKnuckles** [SmashMC-Development/Bugs-and-Issues#953]
**Describe the Bug**
My Pinplup reached level 16 where he should evolve to Prinplup but after the animation of evolution it didn't evolve. I tried to feed him a Rare Candy but nothing happen besides it level up

**Comment by Indorlan** [comment]
This is something you need to make a ticket for on the discord or try /fixevo <slot>, slot being the slot piplup is in in your party

**Comment by HackuJacku** [comment]
Use `/fixevo` - part of upcoming changelog.
