### ISSUE TITLE
Clear making dungeon pokemon despawn

### ISSUE THREAD

**Issue by KUCHIHA10** [SmashMC-Development/Bugs-and-Issues#954]
**Describe the Bug**
So basically a clear happened while I was in dungeon and it cleared out the two dungeon pokemon I had left to defeate and there is no more spawning. 
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
Kyurem
**Expected behavior**
I expected for pokemon to not despawn or new ones to spwan 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
Same as #959
