### ISSUE TITLE
Rayquaza 4th elite 4 battle teleports the challenger to a place in spawn instead of the elite 4 arena, and does not provide them with their team

### ISSUE THREAD

**Issue by stumbles23** [SmashMC-Development/Bugs-and-Issues#955]
**Describe the Bug**
Rayquaza 4th elite 4 battle teleports the challenger to a place in spawn instead of the elite 4 arena, and does not provide them with their team

**To Reproduce**
Challenge the rayquaza elite 4 4th battle, ghost normal dual typing,  and be accepted.

**Servers with the Bug**
Rayquaza 

**Expected behavior**
Player is teleported to the elite 4 arena and provided their pokemon

**Screenshots**
N/A

**Additional context**
The issue involving not receiving their team for the battle is also present in the 2nd and 3rd battles, but the teleportation error is specific to the 4th

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
