### ISSUE TITLE
Got kicked from the server when i engaged a xerneas in warzone

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#956]
**Describe the Bug**
I was in warzone and engaged a xerneas. As soon as i engaged the xerneas i got an error and got kicked from the server. Not sure if the issue was on my side or server side but making this github anyway. When i got disconnected i didn't even get an error message it just straight up kicked me from the server. I can provide my logs if u wanna take a loot at em. just dm me and i can send em :) . I'm sure you guys will make more sense of the logs than i can

**To Reproduce**
Go to warzone
engage a mon
get disconnected from the server

**Servers with the Bug**
Happened on reshiram but all im guessing?

**Expected behavior**
I don't expect to get kicked from the server

**Screenshots**
NA

**Additional context**
NA

**Comment by jantjewieger** [comment]
did it again and this time it gave me this message

![image](https://user-images.githubusercontent.com/87021826/146287030-a8d2a98f-9860-4a0b-81f4-2da96d359423.png)

**Comment by HackuJacku** [comment]
Create a ticket please, we'll need your client logs.
