### ISSUE TITLE
Fossil pokemon in bingo card

### ISSUE THREAD

**Issue by Toonfaes2003** [SmashMC-Development/Bugs-and-Issues#958]
I have a bingo card and it says i have to catch an arctovish(fossil pokemon), but when you put the fossils in the fossil machine and catch it it doesn't fill up the bingo card.

**To Reproduce**

**Servers with the Bug**
Pokesmash

**Expected behavior**
Maybe find a solution to this because i just realised it know after more than 3 weeks of casually catching the other pokemon.

**Screenshots**
N/A
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed in next release.
