### ISSUE TITLE
Clear ruining dungeon

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#959]
**Describe the Bug**
I've had multiple players tell me that their dungeon attempt has been ruined because of a clear that has cleared the bosses that you are supposed to defeat to progress in the dungeon.

**To Reproduce**
1. Go to a dungeon (pretty sure this happened with all dungeons)
2. clear happenes
3. bosses get cleared

**Servers with the Bug**
P
All pixelmon sevvers i beleive

**Expected behavior**
the clear shoudnt clear dugeon bosses

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Made some modification to the worlds blacklist. This should be better now. Can you monitor and let me know please?

**Comment by WalkAway7** [comment]
Sure. I'll give an update tomorrow, I'll try stay relatively AFK in the dungeons on groudon and kyurem untill a clear happeneds, and ill see what happeneds.

**Comment by HackuJacku** [comment]
Making the assumption that this is fixed.
