### ISSUE TITLE
Dusk tools

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Bugs-and-Issues#96]
**Describe the Bug**
Players are able to take in dusk sword and hammer

**To Reproduce**
1. Go to charizard
2. Click on /warp warzone with dusk sword or hammer
3. Scroll down to then you get teleported into warzone

**Servers with the Bug**
all

**Expected behavior**
not supposed to be able to use dusk tools in warzone

**Screenshots**

**Additional context**

**Comment by oLimooo** [comment]
works, dusk hammer nor sword can be used in warzone

**Comment by HackuJacku** [comment]
Changes are now live.
