### ISSUE TITLE
/Skills isnt working

### ISSUE THREAD

**Issue by Davddn** [SmashMC-Development/Bugs-and-Issues#960]
**Describe the Bug**
/skills isnt working

**To Reproduce**
1. Go to zekrom
2. Type up /skills

**Servers with the Bug**
Zekrom only from what I know

**Expected behaviour /skills fixed**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
