### ISSUE TITLE
Players can sell Pokemon while it is in a Ranch Block which makes them unusable for whoever buys them

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#961]
**Describe the Bug**
Players can sell Pokémon While in Breeders which makes them unusable for whoever buys them

**To Reproduce**
1. Put a Pokémon in a breeder
2. Open the create a listing area of GTS
3. Find the Pokémon that is in a breeder
4. Sell it on GTS
5. Whoever buys it will be unable to move it from either their party or pc as the game still thinks it is in a ranch block

**Servers with the Bug**
All

**Expected behavior**
Shouldn't be able to sell Pokémon that is currently in a ranch block
 
**Screenshots**
Shows Pokemon in breeder you can tell as the Pokemon in the left bar doesn't have a green circle on it
![image](https://user-images.githubusercontent.com/84816052/146605943-73ef5e44-9190-4780-82c6-8b246e6c249c.png)

Shows result of selling a Pokemon in a breeder on the players end
https://youtu.be/5CyDaxstiuI

**Additional context**
'N/A'

**Comment by HackuJacku** [comment]
Forwarded to Pixelmon.
