### ISSUE TITLE
GTS not working properly

### ISSUE THREAD

**Issue by SirMorningW00d** [SmashMC-Development/Bugs-and-Issues#962]
**Describe the Bug**
Bug is that gts caps non leg non hidden ability mons at 20k, meaning you can't sell battle perfects for higher than 20k, this has been an issue for several weeks and hurts the economy badly.

**To Reproduce**
1. Go to gts
2. Click on "sell pokemon"
4. See error capping at 20k

**Servers with the Bug**
Please provide a list of which servers have this bug.
As far as i know only groudon has this bug
**Expected behavior**
I expect the GTS to allow the selling of bps for higher than 20k, as they are worth 80k atleast
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://user-images.githubusercontent.com/96324089/146626521-53b853e8-a02a-4c10-abbf-1ba3a0faeaa3.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
That should be about it, hope this gets looked into and fixed.

**Comment by HackuJacku** [comment]
Forwarded to Pixelmon.

**Comment by Rasgnarok** [comment]
Duplicate.
