### ISSUE TITLE
Breeding Male HA with Ditto

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#963]
**Describe the Bug**
Seems when breeding a male ha with ditto all eggs produced are Galarian (ha and not). I have a Kantonian male ha Slowpoke and a Unova male ha Darmanitan. Breeding with ditto trying to get a female Kantonian/Unova ha female seems to not work. Looking around on google seems others solve this issue by giving both the male and ditto an everstone but this too does not work for me, the eggs are still all Galarian.

**To Reproduce**
1. Go to Rayquaza
2. Get either a male ha slowpoke or a male ha Darmanitan, both standard forms
3. Breed them with ditto ( seems when both are holding everstone the eggs should be standard forms)
4. See that whoever is holding the stone the offspring is not standard form only Galarian

**Servers with the Bug**
Far as I am aware Rayquaza, but I saw other githubs about this for others servers so perhaps all servers

**Expected behavior**
It should be able to get a standard form female ha when breeding standard male ha with ditto.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
So, this is currently a Pixelmon bug, as far as I'm aware. The solution for everyone else was the one you mentioned, using an everstone, so I'm not sure why that wouldn't be working in this case. Try giving just the male the everstone, perhaps?

**Comment by DaniloJonko** [comment]
> So, this is currently a Pixelmon bug, as far as I'm aware. The solution for everyone else was the one you mentioned, using an everstone, so I'm not sure why that wouldn't be working in this case. Try giving just the male the everstone, perhaps?

i've tried this on groudon with an everstone and it still gives galar slowpoke

**Comment by Mikirae** [comment]
Then it's unfortunately a Pixelmon bug and will require an update on their
end :(

**Comment by Bkdevileu** [comment]
Since the new update (the reset one), even with everstones on both parents, the offspring always comes out as galar (got female HA kantonian slowpoke but I always get galar slowpokes whatever I do). It's a pixelmon bug =(

**Comment by Superfire96** [comment]
The problem can be solved by breeding them in the ultraspace
