### ISSUE TITLE
Stuck in dungeon

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#964]
**Describe the Bug**
When you enter the first dungeon (the easy glacial one) u can get stuck in the first room if you don't have access to /fly. In the corner where the mons spawn the hole is 1.5 blocks deep. If u fall in, for whatever reason, you cannot get back out since u can only jump 1 block high.

**To Reproduce**
do /dungeons
join the easy glacial dungeon
in the first room fall in one of the holes in the corner
be unable to get out

**Servers with the Bug**
All

**Expected behavior**
I would expect to be able to get out

**Screenshots**
This is the hole im talking about

![image](https://user-images.githubusercontent.com/87021826/146681037-544fe4e8-d3b9-4ff8-b50a-429fdb578049.png)

**Additional context**
NA

**Comment by Indorlan** [comment]
Does /trapped work in dungeons?

**Comment by jantjewieger** [comment]
It does not

**Comment by jantjewieger** [comment]
It says 'I can't use that here' when i try using /trapped

**Comment by Mikirae** [comment]
Well just don't fall in smh my head!!! But I'll get to fixing this soon. Thank you for reporting! :)

**Comment by Mikirae** [comment]
Super has done this :)
