### ISSUE TITLE
gts glitching out on groudon

### ISSUE THREAD

**Issue by DaniloJonko** [SmashMC-Development/Bugs-and-Issues#965]
**Describe the Bug**
gts is glitching out on GROUDON

**Servers with the Bug**
GROUDON

**Expected behavior**
please fix it my g

**Screenshots**

https://user-images.githubusercontent.com/95652558/146686406-985e43f5-8415-47ee-839d-d0471f83a68f.mp4

**Comment by Rasgnarok** [comment]
Duplicate, thanks!
