### ISSUE TITLE
Warzone glitch

### ISSUE THREAD

**Issue by Yattott** [SmashMC-Development/Bugs-and-Issues#967]
**Describe the Bug**
I went to warzone and caught some pokemon and 2 legendaries. Someone challenged me in warzone but we got stuck on the "waiting..." glitch and my opponent just left the game and I got the message "no one won the fight". After that, I got the "frozen time" glitch but I can move yet I can't throw my pokemon. I made a ticket to report the glitch but I had to relog then after connecting, I spawned in the overworld. I checked my warzone bank but the pokemon I caught went missing.

**To Reproduce**

**Servers with the Bug**
Reshiram

**Expected behavior**

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Superfire96** [comment]
The issue of the timer being stuck and you not being able to throw your pokemons should be fixed
