### ISSUE TITLE
Groudon GTS is broken flashing and it is hard to click the Pokemon

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#968]
**Describe the Bug**
On the Groudon server, the gts is flashing and does not allow you to click on pokemon. 
**To Reproduce**
1. Go to Groudon server. 
2. Do /gts
3. See flashing and try to click on pokemon

**Servers with the Bug**
Please provide a list of which servers have this bug.
Groudon
**Expected behavior**
It is expected that the gts is functioning and not flashing and is able to allow you to click on pokemon to buy or sell. 

https://user-images.githubusercontent.com/85481519/146707440-dea626ee-8f74-4f93-97db-9b6b005c7b86.mov

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
Forwarded, looks like latency to me.

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Bugs-and-Issues/issues/965
