### ISSUE TITLE
Shadow Pokemon

### ISSUE THREAD

**Issue by GirthyGlowWorm** [SmashMC-Development/Bugs-and-Issues#969]
**Describe the Bug**
Shadow Pokemon Papers not giving shadow Pokemon

**To Reproduce**

**Servers with the Bug**
Kyurem but possibly all servers, not too sure

**Expected behavior**
Hopefully we can get working shadow Pokemon

**Screenshots**
https://prnt.sc/23qjxs6

**Additional context**
Got this Arbok from a paper, it's just standard

**Comment by Superfire96** [comment]
I just tested it, and looks like it's working correctly, you might have the wrong texturepack, if you need help finding the latest one, please open a ticket.
