### ISSUE TITLE
/discord doesn't work

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#970]
**Describe the Bug**
Whenever you do /discord it says, "Unkown command. Try /help for a list of commands"

**To Reproduce**
1. Type /discord
2. see error message

**Servers with the bug**
tried on all servers, none have the command

**Expected behavior**
Should give you an invite link to the discord

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Fixed, thanks!
