### ISSUE TITLE
Warzone Bug with throwing out your Mon

### ISSUE THREAD

**Issue by ChewbaccaOnSmth** [SmashMC-Development/Bugs-and-Issues#971]
If u go into wz most of the time you cant throw out ur mon meaning u cant catch smth and cant kill 25 sec mons, so it means u loose money for nothing.

Go to wz and try to throw out your mon

I just know it on zekrom

to throw out my mon and not loosing money for nothing

N/A

**Comment by Mikirae** [comment]
I've made some changes that will hopefully fix this for the next restart. Please let me know if it's still an issue. And if you have this issue, feel free to open a ticket and we'll get your money refunded :)
