### ISSUE TITLE
equipment being replaced by blocks and blocks going missing when mined

### ISSUE THREAD

**Issue by Superpuglead** [SmashMC-Development/Bugs-and-Issues#972]
**Describe the Bug**
what is happening is that when I put my pickaxe in my hotbar and start mining with it turns into dirt or something i have in my inventory. Also when i mine a block it disappears and it doesn't go into my inventory and I've tried to disconnect and reconnect but still nothing.

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.
the pixelmon server smash mc rayquaza 
**Expected behavior**
well i expected not for my tools to not automatically swapped out for blocks and blocks going missing after being mined 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
n/a
**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
n/a

**Comment by HackuJacku** [comment]
This is an issue with your connection. We're sadly unable to do anything about this :(
