### ISSUE TITLE
Clear not working

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Bugs-and-Issues#973]
**Describe the Bug**

**To Reproduce**
1. Go to Kyogre
2. Wait for clear
3. Only a few mons despawn if even any

**Servers with the Bug**
Kyogre

**Expected behavior**
The mons should disappear.

**Comment by Superfire96** [comment]
Looks like it is working correctly, please if it happens again please open a new tracker providing us some proof.
