### ISSUE TITLE
Kyogre Server, 2 Gym (psychic) error/

### ISSUE THREAD

**Issue by SiennaAffliction** [SmashMC-Development/Bugs-and-Issues#974]
**Describe the Bug**
Yesterday I tried to fight the second gym on the Kyogre server.
I've already done the first one, nothing went wrong.
I have a full team of 40 (as that's the level cap that's advertised) but when I finish selecting my team, the battle doesn't commence.
It instead says the level cap is 30 instead.

**To Reproduce**
Steps to reproduce the behaviour:
N/A

**Servers with the Bug**
Kyogre.

**Expected behaviour**
I would like the level cap to be fixed to 40 

**Screenshots**
![2021-12-21_19 26 34](https://user-images.githubusercontent.com/96515683/147168227-c2e7a353-6880-4eea-a0f3-19133d3bd456.png)
![2021-12-21_19 26 43](https://user-images.githubusercontent.com/96515683/147168230-344c977a-7b55-4521-952c-a88e67c8e4c0.png)
![2021-12-22_16 37 45](https://user-images.githubusercontent.com/96515683/147168235-dc18e71f-637b-48b8-b3a9-d77c0452c413.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
This should be fixed. Please check now and let me know.

**Comment by SiennaAffliction** [comment]
This has been fixed now, thanks tons!
