### ISSUE TITLE
Gts glitched, cant list items

### ISSUE THREAD

**Issue by TheDrPH** [SmashMC-Development/Bugs-and-Issues#975]
![image](https://user-images.githubusercontent.com/96399316/147191204-21bcc9c7-a8ec-4337-ba45-c5e303597788.png)

I cant list items on the gts using /gts sell, because when i type it the server doesnt give me a response.
I also canto use the gts menu to list items because it wont send them into the menu and will just select them on my mouse.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
