### ISSUE TITLE
GTS Is Broken

### ISSUE THREAD

**Issue by ThePapaChunks** [SmashMC-Development/Bugs-and-Issues#976]
**Describe the Bug**
So for example i put a bp mon on gts and the max price is 20k so if i wanna sell a bp for 80k on Groudon which is the price bp unbreed sell for everyone sells them at 80k I cannot but the gts doesnt allow it so I have to say it in chat over and over. So when I try to sell my bp grookey for 80k and click OK it doesnt allow for it to be higher than 20K.

**Servers with the Bug**
Groudon I dont know if the other servers have a issue.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
I was told I could put the ticket into this and the ticket number is 40518

**Comment by Rasgnarok** [comment]
Duplicate, closing.
