### ISSUE TITLE
Exp Candy from Adventcalender

### ISSUE THREAD

**Issue by Indorlan** [SmashMC-Development/Bugs-and-Issues#977]
**Describe the Bug**
Seems the day 21 reward only gives 1 Exp candy XL instead of 5.

**To Reproduce**
1. Go to any server
2. Spend enough time get to day 21 reward of /adventcalender
3. Use /adventcalender and click the day 21 reward
4. See it only giving you 1 candy instead of 5

**Servers with the Bug**
Was on Rayquaza but I'm assuming all servers

**Expected behavior**
It should give 5 Exp candies XL for day 21 reward

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Mikirae** [comment]
Sorry that it took a while, but this is fixed on all servers for the next restart. Thank you for reporting, and let me know if you still need the candies! :)

**Comment by HackuJacku** [comment]
The advent calendar now has been removed.
