### ISSUE TITLE
If you are the only player doing a tournament you istantly win.

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Bugs-and-Issues#978]
**Describe the Bug**
If a tournament starts and there's only one player, he's going to win the crate 

**To Reproduce**
1. Join tournament
2. Be the only player on it 
3. Get a free key

**Servers with the Bug**
Everyone

**Expected behavior**
When there aren't at least 2 players on the tournament, it simply get cancelled 

**Screenshots**
https://i.gyazo.com/00e3fe67fc773303c36780d40d8d71d7.png

**Comment by HackuJacku** [comment]
Fixed in upcoming version
