### ISSUE TITLE
Tourney bugs sometimes

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#979]
**Describe the Bug**
Some battles in tourney keep erroring. It will send a message saying 'Wiepie_ vs Eboyjay69 errored! Restarting match in 30 seconds'. Except this will happen every time the battle restarts and the battle will never start. This always happens at the start of the battle so u cant even choose 1 move in the battle.

**To Reproduce**
Join a tourney
Have a chance to engage this bug
keep getting restarted endlessly

**Servers with the Bug**
Happened to me on Reshi but might be all

**Expected behavior**
I would expect the battle to start at some point

**Screenshots**
![image](https://user-images.githubusercontent.com/87021826/147260398-e5f26d2b-bfc5-4d8e-b540-5faeff67b757.png)

**Additional context**
NA

**Comment by Rasgnarok** [comment]
This is due to the battle start itself erroring, it's found in battle timestamps. Please simply give me the timestamp in the other channel next time it happens.
