### ISSUE TITLE
Smash Palkia doesnt show as their own category

### ISSUE THREAD

**Issue by Mizugorou49** [SmashMC-Development/Bugs-and-Issues#98]
**Describe the Bug**
Smash Palkia rank on the discord server doesnt show separately like all the other ranks do, and just gives a colour instead

**To Reproduce**
1. Go to the discord and scroll down on the right side where all the people are shown

**Servers with the Bug**
The Discord server

**Expected behavior**
Smash Palkia rank should be shown differently on the side bar as all the other ranks are

**Screenshots**
![smash](https://user-images.githubusercontent.com/83819638/117534566-f2ad7380-afbf-11eb-95e1-755105e4b927.PNG)

**Additional context**

**Comment by HackuJacku** [comment]
@Mizugorou49 - there's no fix to the roles. I'll be removing the `<server> <rank>` e.g: Smash Palkia, and replacing them with a global role `Smash` down the line. 

The way it is set up doesn't allow for this and is partly the reason why the roles are such a mess. Our custom Discord bot will address these issues.
