### ISSUE TITLE
i havent received any of the benefits within the server ie: masterball or anything since being prompted to Download the modpack and to join the discord

### ISSUE THREAD

**Issue by PSUEDO7** [SmashMC-Development/Bugs-and-Issues#981]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
You need to run the '/modpack' command as prompted in chat.
