### ISSUE TITLE
Water gym item bug

### ISSUE THREAD

**Issue by Yattott** [SmashMC-Development/Bugs-and-Issues#982]
**Describe the Bug**
I fought the water gym in reshiram server and won but I did not get some of the rewards "2 ever eggs" and "3 soothe band". But I got the 16 level balls and 3000 coins.

**To Reproduce**
Steps to reproduce the behaviour:
4. See an error

**Servers with the Bug**
Reshiram

**Expected behaviour**

**Screenshots**
'N/A'.

**Additional context**
'N/A'.

**Comment by Mikirae** [comment]
Should be able to get to this tomorrow. Thank you for reporting! :)

**Comment by Mikirae** [comment]
It's been fixed. Thank you! Just reply back to this with your ign and I'll get you the items :)
