### ISSUE TITLE
Galar forms

### ISSUE THREAD

**Issue by ACShade** [SmashMC-Development/Bugs-and-Issues#983]
When breeding for normal pokemon after the egg is collected it appers galar form and not normal form example breeding Yamask. 

This issue is happening in kyogre

https://user-images.githubusercontent.com/96602026/147303686-09eb5525-db69-4419-8d6d-d5a9653b9249.mp4

**Comment by HobnobberJunior** [comment]
This is a pixelmon bug and can not be fixed on the server as far as ive understood from earlier githubs.

**Comment by Mikirae** [comment]
The person above is correct. This is a Pixelmon bug and I'm unsure if they'll fix it. I know some people have had success by giving the non-galarian Pokemon an everstone, but some others have reported to me that it doesn't work, unfortunately.
