### ISSUE TITLE
Christmas Sale Message doesn't appear correctly in chat

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#984]
**Describe the Bug**
The message displayed after make a purchase in the Christmas Sale doesn't appear correctly

**To Reproduce**
1.  Buy something during the sale
2. Message is not displayed correctly in chat

**Servers with the Bug**
Seen on Rayquaza but possibly all

**Expected behavior**
message should be displayed correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/147370903-851bae04-d16a-4bdb-82d7-8f8a9a1369ff.png)
![image](https://user-images.githubusercontent.com/84816052/147370930-23ba63f6-9a0a-4524-9017-25db75882927.png)
![image](https://user-images.githubusercontent.com/84816052/147370961-c2fee4f8-87e7-4e74-95ef-3f52c536b336.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Fixed
