### ISSUE TITLE
Psychic Gym level cap glitch

### ISSUE THREAD

**Issue by SiennaAffliction** [SmashMC-Development/Bugs-and-Issues#985]
**Describe the Bug**
The level cap is still broken, I've already made a post about this like 5 days ago and no ones seen it.
Idk what I have to do to get a response around here but I'm gonna guess I still won't.
Why this is still an issue is beyond me and the fact that I've tried to deal with this for 5 days is a joke.

Want more info, read my previous post.

**Comment by SiennaAffliction** [comment]
Just delete the npcs for the psychic gym and replace them, its doesn't matter what team I go in with it just won't work.

**Comment by Mikirae** [comment]
We have lives, we have holidays, we have other jobs, we have things to fix, we have features to create. Not everything will be done in your timetable. It's something that we can look into, but we definitely do not appreciate the sass when we're going around and doing tickets.

**Comment by HackuJacku** [comment]
@SiennaAffliction this can't be fixed based on this issue because you've provided a lack of information. For example: which server is this for starters?
