### ISSUE TITLE
Spawn announcements show wrong info

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Bugs-and-Issues#986]
**Describe the Bug**
When a pokemon (Boss/Ultrabeast/Legendary/Shiny) spawns the spawn announcement does state that a player is near to it, that is not near to it. 
In the Screenshot for example, you can see that a wild legendary Reshiram spawned next to the player "FadeFire", which was not near any Mega Taiga Hills. The Player TheVideoGamester was the player that the Reshiram spawned on. He also stated that afterwards.
I asked the players mentioned if they are okay with me including them in the screenshot. 

**To Reproduce**
1. Go to 'Any place on Kyogre that allows Legendaries/Bosses to spawn'
2. Watch the Chat
3. Wait for a Boss or Legendary spawn to occur
4. See if the stated player is near it

**Servers with the Bug**
At least Kyogre

**Expected behavior**
It should show the correct player that got the spawn. 

**Screenshots**
![2021-12-25_03 22 57](https://user-images.githubusercontent.com/94211853/147376262-13fc05b8-d8d4-4e85-b5f0-656e69d1e1b5.png)

**Additional context**
Other issues that are related to this issue:
The Ultra Beast spawns always show that "the respective biome is near the spawn", as if the biome was a player.
If a megaboss spawns, the announcement does only state the pokemon name, but not that it is a megaboss.

**Comment by Mikirae** [comment]
We're looking into this one and I tagged Hacko in a different ticket, so I'll be closing this one. Thank you for reporting!
