### ISSUE TITLE
WZ lag out caused me to lose all the pokemon i caught

### ISSUE THREAD

**Issue by MattyIce3D** [SmashMC-Development/Bugs-and-Issues#987]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by MattyIce3D** [comment]
Caught a 95% Yveltal and a shiny Shinx in WZ, then suddenly my game shut down. Logged back in, nothing caught from WZ. :/

**Comment by Dxhcky** [comment]
I believe you can make a ticket about this in the discord with proof from your logs and you can get the Pokemon you lost back... I'm not sure about ivs though unless you have proof of them

**Comment by Dxhcky** [comment]
If you don't know what logs are or how to access them I'm sure staff will be happy to help in a ticket

**Comment by HackuJacku** [comment]
Please create a ticket on our Discord.
