### ISSUE TITLE
v8 Addons Pack doesnt contain Shadow Pokemon Textures

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#988]
**Describe the Bug**
v8 Addons Pack doesn't contain Shadow Pokemon Textures

**To Reproduce**
1. Go to any server and look at any Shadow Pokémon while having the v8 Texture Pack on
2. Will not be able see the Textures
3. Go to any server with the V7.2 Pack on and be able see the Textures

**Servers with the Bug**
All

**Expected behavior**
Should be able see textures with the v8 Pack on

**Screenshots**
With v8
![2021-12-25_18 48 36](https://user-images.githubusercontent.com/84816052/147391739-f6839aa9-0cf6-4a2f-bf9b-6726585d93c0.png)
![2021-12-25_18 48 33](https://user-images.githubusercontent.com/84816052/147391744-7b066f26-6d0d-4482-94a2-9be35229ec18.png)

With v7.2
![2021-12-25_18 49 07](https://user-images.githubusercontent.com/84816052/147391745-b2b4e983-50a3-413b-af2b-f264b0c0f1be.png)
![2021-12-25_18 49 16](https://user-images.githubusercontent.com/84816052/147391746-a8b80cd1-6175-4317-b2a0-ec52814f3851.png)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Yes it does. Wrote a converter for old Shadow ID to new Shadow ID.
