### ISSUE TITLE
/endbattle not working in the wild

### ISSUE THREAD

**Issue by linefax** [SmashMC-Development/Bugs-and-Issues#989]
**Describe the Bug**
The command /endbattle which should work when you are fighting wild pokemon doesn`t work. It wont work in Warzone, but it should work in the wild which it doesn`t. I tested it with wild trainers and pokemon. The "Error" message is: You have no permission to use this command.

**To Reproduce**
1. Press /rtp
2. Go in a Pokemon fight and use /endbattle
4. See error (i have the Expert Rank, it might work with ranks from the shop)

**Servers with the Bug**
Playing on the Rayquaza Server

**Expected behavior**
Thats its possible to use this command in wild battles, for example when you have the waiting bug in the wild. (not in warzone of course)

**Comment by Mikirae** [comment]
Fixed this. Thank you! :)
