### ISSUE TITLE
Joining survival

### ISSUE THREAD

**Issue by BPuncake** [SmashMC-Development/Bugs-and-Issues#99]
**Describe the Bug**
Players need to link their mc account to the discord before joining survival (Not sure if this is a bug or a feature?)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to hub
2. Attempt to join survival (On a non-linked account)

**Servers with the Bug**
Hub/Survival

**Expected behaviour**
Attempting to join survival from the hub should just send you into the survival server without having to link.

**Screenshots**
![2021-05-08_22 47 56](https://user-images.githubusercontent.com/82549547/117560954-b9244900-b04f-11eb-9b3b-412e5d45d685.png)

**Additional context**
N/A

**Comment by BPuncake** [comment]
Khan's fixed this in-game, will close it now as it's resolved.

**Comment by jahangir6969** [comment]
GOD DAM IT PUN. WAS GOING TO CLOSE IT. but issue was wrong config setting was enabled.
