### ISSUE TITLE
/Vote doesnt work on Rayquaza

### ISSUE THREAD

**Issue by xSire** [SmashMC-Development/Bugs-and-Issues#990]
**Describe the Bug**
When Voting on the rayquaza server, the vote system wont work if you vote when not online. It only works when your logged on in  the server when voting. 

**To Reproduce**
1. Dont open mincraft 
2. Vote using the vote links for raquaza server 
3. after voting luaunch mincraft pixelmon and log on to smashmc rayquza server 
4. You wont get the five vote keys

**Servers with the Bug**
Rayquaza (could has happen in other servers im not sure)

**Expected behavior**
when voting off line you should still get the keys

**Screenshots**
'N/A'.

**Additional context**
'N/A'.

**Comment by Mikirae** [comment]
Thank you for reporting. This should hopefully be fixed soonish but I'm unsure if the developer of the plugin is busy.

**Comment by HackuJacku** [comment]
Forwarded to the developer.
