### ISSUE TITLE
Clear

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Bugs-and-Issues#991]
**Describe the Bug**
The clear is not removing all mons.

**To Reproduce**
Go to Kyogre
Wait for clear
Not all mons disappears.

**Servers with the Bug**
Kyogre

**Expected behavior**
Clear should remove all mons.

**Screenshots**
Before clear:
![2021-12-27_15 17 15](https://user-images.githubusercontent.com/93604984/147480392-c76588cf-48a4-4b5b-b18a-58733d19eddc.png)

After Clear:
![2021-12-27_15 17 21](https://user-images.githubusercontent.com/93604984/147480443-f4ef0150-d05c-4c27-a7af-1de47b5afd5a.png)

**Additional context**
Tried to make a ticket before but it was closed before it was really investegated, so I will try again with SS this time.

**Comment by Mikirae** [comment]
Are you sure they didn't quickly spawn after? Just making sure as the config looks correct here so I'm trying to figure things out.

**Comment by HobnobberJunior** [comment]
If you look closely, the ones remaining are the exact same mons that were there before in the exact same place. I Took a ss right before and right after. I can do it again where its easier to see if you want that?

**Comment by Mikirae** [comment]
Oh, sorry, I’m stupid and thought they were two examples. That seems like a bug with the plugin. I’ll see what I can find out. Thank you for reporting it! :)

**Comment by HobnobberJunior** [comment]
Ye I probably didnt explain that one well enough looking at it now.

**Comment by HackuJacku** [comment]
Fixed from next reboot
