### ISSUE TITLE
Boss spawning not accurate

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Bugs-and-Issues#992]
**Describe the Bug**
Whenever a boss spawns near someone, it isn't always accurate at all. 

**To Reproduce**
1. Boss spawns
2. Says it spawned on one person
3. Is on another person

**Servers with the Bug**
From what I know it's only on reshiram

**Expected behavior**
Should say who is actually near it

**Screenshots**
![Screenshot (186)](https://user-images.githubusercontent.com/89798207/147485187-542520c7-8d14-4343-bd4f-a9c33ab99bae.png)

**Additional context**
As you can see in the screenshot above, a legendary rolycoly spawned, it says it spawned on someone else, but it was actually on me

**Comment by HobnobberJunior** [comment]
This is also a problem on kyogre. A github on this problem has also been made for kyogre.

**Comment by Mikirae** [comment]
Looks like a problem with Pixelmon Broadcast's placeholders? @HackuJacku

**Comment by HackuJacku** [comment]
Forwarded to PixelmonMod, unsure what the cause is currently but I'll look into
