### ISSUE TITLE
Hubbing in warzone

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Bugs-and-Issues#993]
**Describe the Bug**
People can hub in warzone right before they are about to lose, and not really get punished for it. If they hub, all that happens is they have a 5min cool down when the log back on, and they lose the Pokémon they caught or stole that wz trip, which is really not fair, especially for the person who was about to beat them.

**To Reproduce**
1. Battle someone In warzone
2. They /hub while in the battle
**Servers with the Bug**
Groudon, probably all

**Expected behavior**
You should be able to steal a Pokémon from the person that hubed, and the cool down should increase the more they hub, to prevent them from doing it in the future.

**Comment by Mikirae** [comment]
It's a bit confusing from a player's perspective so I won't bore you with the details, but this is actually something that is decently difficult to patch. We're currently working on it, so please be patient and always make a ticket if someone does this!

**Comment by RatedPG21** [comment]
Thanks for the notice, no rush I know you have a lot on your plate, it’s just I don’t record my screen since my laptop is trash and can barely run minecraft, so when someone hubs I don’t have proof and don’t get to steal a Pokémon most of the time

**Comment by Mikirae** [comment]
Just try to get a screenshot and open a ticket. We can gather logs on our end if necessary :)

**Comment by Superfire96** [comment]
Fixed
