### ISSUE TITLE
HA announcements in wz

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Bugs-and-Issues#994]
**Describe the Bug**
It is not announced in chat when someone catches a HA in warzone. It is whoever announced in chat when someone kills an HA in warzone. I don't know if this is intentional or not. In my opinion, it would be nice if players in warzone got notified when someone catches a HA. With all the talks going on about warzone spawns, making warzone competitive and eliminating throws in warzone...announcing HA catches in warzone, would be a step in the right direction because it will prevent people from taking throws to hunt HAs in warzone and reward people who spend their time and money building a real time.

**Servers with the Bug**
Groudon.

**Comment by Mikirae** [comment]
Looking into this as I don't know if it was intentional or not. Should be resolved within a day or so :)

**Comment by ghost** [comment]
ok thanks :)

**Comment by Mikirae** [comment]
Done for next restart :)

**Comment by ghost** [comment]
oh nice! Thanks!
