### ISSUE TITLE
cant sell items gts

### ISSUE THREAD

**Issue by uval1** [SmashMC-Development/Bugs-and-Issues#995]
hey when i use /gts sell nothing happened
also whem im trying to sell from the /gts conned also i cant 
help someone?

**Comment by Mikirae** [comment]
Not sure I understand everything exactly. Can you provide a video of what's happening?

**Comment by Rasgnarok** [comment]
Maybe similar to: https://github.com/SmashMC-Development/Bugs-and-Issues/issues/975

**Comment by HackuJacku** [comment]
Fixed from next reboot.
