### ISSUE TITLE
Buymoves

### ISSUE THREAD

**Issue by FadeFire** [SmashMC-Development/Bugs-and-Issues#996]
**Describe the Bug**
Buymoves currently allow you to buy moves from the Kanto Ninetales for the Alolan Ninetales, so you can basically have an Alolan Ninetals with Inferno and all that stuff.
**To Reproduce**
1. Go to '/buymoves' while having an alolan/galar pokemon in the party
2. Click on the alolan/galar pokemon
3. See the library of moves for their regular form pop up which you can for some reason teach to them

**Servers with the Bug**
Kyogre, maybe more

**Expected behavior**
Adjust them so the moves of Alolan Ninetales/ the others if they are bugged aswell show up instead of their normal form ones

**Screenshots**
![2021-12-29 (3)](https://user-images.githubusercontent.com/93608157/147626342-4b01c5d4-77ce-4b80-bb42-2e9c05471e41.png)

**Comment by Mikirae** [comment]
Thank you for reporting this! We'll get it fixed as soon as we can :)

**Comment by HackuJacku** [comment]
This is not an issue with buymoves. It's an issue with the stat file, on Pixelmon's end. I have however fixed it from the next reboot.
