### ISSUE TITLE
Legend despawn

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Bugs-and-Issues#998]
**Describe the Bug**
A legendary spawn somehow despawned following a clear.

**To Reproduce**
1. Kyogre
2. Wait for a legend (Tapu Bulu)
3. Then wait for a clear to occur. This however will be tricky since the clear isn't working properly on kyogre right now, so not all mons will be cleared and therefore you might have to wait for it to be "chosen" by the clear.
4. See the Tapu bulu disappear.

**Servers with the Bug**
Kyorgre

**Expected behavior**
The legend spawn, in this case Tapu bulu, should stay even when a clear occurs.

**Screenshots**
![2021-12-29_21 58 54](https://user-images.githubusercontent.com/93604984/147705124-a181962f-e777-4560-8bc9-5311a8983492.png)

**Additional context**
In this case it was a tapu bulu, but there has been several cases where legend spawn has despawned after a very short period.

**Comment by Mikirae** [comment]
I'll take a look at clear and see what's up here. As for the other part, legends do despawn quickly (not from clears) which is an issue with Pixelmon as I've seen it happening on a bunch of servers, unfortunately.

**Comment by HackuJacku** [comment]
Fixed from next reboot.
