### ISSUE TITLE
Minecraft maps refusing to flip+be placed down

### ISSUE THREAD

**Issue by Sensouu** [SmashMC-Development/Bugs-and-Issues#999]
**Describe the Bug**
This bug has been around for awhile, I just got conformation today to make a GitHub about it due to it being strange and inconvenient. As the title states this bug has to do with maps having trouble when players interact with them, flipping or placing down on occasion. I used to be able to fix it by simply moving where the map was, but now that its gotten bigger and bigger it's gotten more hard to do. Also, it can be fixed by making a brand new map/copy of the map but after 12+ maps it gets a bit expensive.  

**To Reproduce**
1. Create a quick map of your claim
2. Item frame, place map in frame
3. Sometimes the map wont flip at all if it gets.. old..? broken too often?

**Servers with the Bug**
This footage is from Reshiram

**Expected behavior**
Being able to have all the vanilla interactions with a map, and have them permanently stay that way without needing a replacement. 

**Screenshots**

https://user-images.githubusercontent.com/93282314/147711212-332635d8-f68c-41c8-8c64-6fd430e05886.mov

Here's a quick video! If my item frame still won't place as I move it back to its intended spot I'll add it to the comments. 

**Additional context**
When I move my maps I typically break the block behind it as it's faster, but that doesn't explain why I needed to move them in the first place...

**Comment by Sensouu** [comment]
Here would be the other half of this glitch. It happens occasionally at different spots. Not sure what makes them not go down, but all because one map wont go down I need to move the whole thing to a new spot. again. 

https://user-images.githubusercontent.com/93282314/147711469-e6979cd0-0b34-403e-af3e-7235247ff34b.mov

**Comment by Mikirae** [comment]
Can you get someone else to try this with your maps? I just auto clicked mine hundreds of times and couldn't get it to break :(

**Comment by Sensouu** [comment]
I had actually! With Pipplop! They were the one who suggested the ticket in the first place! 
![FD968A19-7AC1-43E5-9E3F-90CF5D76C8E2](https://user-images.githubusercontent.com/93282314/147904771-e59c4647-5f92-4928-93bf-516a92c58ef5.jpeg) (sorry. On mobile. No idea if the image would work..) She had teleported to me and looked at my map while I was moving it, said it was cool! But I said something about it “being broken, so I need to move it”. We ended up moving off my claim and everything to fool around with the maps. I’m surprised that my maps are the only ones with the problem though! Hearing your luck with spinning one hundreds of times with no breakage makes me quite envious! (lightheartedly of course)

**Comment by Mikirae** [comment]
Huh, I'm a bit confused then. I'll try go put down like 30 maps later and see what's up and if it can break. But yeah, many people envy my map turning skills. I was voted Best Map Turner 2019.
Did it work when you exited your claim or no?

**Comment by Sensouu** [comment]
It didn't :( there was still some that refused to flip. I wish I could help better with why/how it happened

**Comment by Superfire96** [comment]
I'm guessing it was fixed, i've tried several times now and it has always worked for me
